### ISSUE TITLE
GridItem Tooltip?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1000]
I'm wondering, if there could be a Tooltip on a GridItem.
Often there is not enough space to show the whole GridItem, columns smaller then content, too much columns so we need to scroll horizontally.
So it would be useful to show more infos from an item just in a tooltip. 
Tom

**Comment by cwensley** [comment]
Have you tried changing the gridview.Tooltip during mouse move events?

**Comment by TomQv** [comment]
Changing the gridview.Tooltip during mouse move events works somehow, but needs some more magic, because the position of the tooltip is not moving with the mouse.

```
void ListPresenter_MouseMove(object sender, MouseEventArgs e)
{
    var item = this.GetCellAt(e.Location)?.Item as ListPresenterItem;
    if (item != null)
        this.ToolTip = item.Mark.Name;
    else
        this.ToolTip = string .Empty ;
}
```

**Comment by cwensley** [comment]
I think if you want to do something like this your best bet would be to create your own tooltip with a new Form.  It'd be fairly straight forward with a UITimer, and attach to the MouseMove event of the control.
