### ISSUE TITLE
Form on Gtk3+windows cannot maximize

### ISSUE THREAD

**Issue by ghost** [picoe/Eto#1001]
Hello everyone and @cwensley,

I have tried to show with Maximize/Restore at capital of Form.
![problem_with_maximizable](https://user-images.githubusercontent.com/3496136/36064614-fac894d6-0e8d-11e8-923b-69517fd09a6c.JPG)
It looks like common because Eto.Forms.Form has "forgotten" to access with Gtk-Sharp-3 Maximize/Restore
Like this
Find in Form.cs or IHandle ( I don't know you have written backand part for Gtk Sharp 3 and Gtk Sharp 2.x )
`this.TypeHint = Gdk.WindowTypeHint.Dialog;`

Replace with:
`this.TypeHint = Gdk.WindowTypeHint.Desktop;` or `this.TypeHint = Gdk.WindowTypeHint.Menu`

I have to write a simple Form MyForm.cs
```
namespace EtoTest
{
    public class MyForm : Form
    {
        private Eto.Forms.MenuBar menubar;

        public MyForm()
        {
            Console.WriteLine("Openning an application!");
            Title = "My Cross-Platform App";
            ClientSize = new Size(500, 350);
            Icon = Eto.Drawing.Icon.FromResource("EtoTest.TextTemplate.ico");
            


            menubar = new Eto.Forms.MenuBar
            {
                Items =
                {
                    new ButtonMenuItem
                    {
                        Text = "File",
                        Items =
                        {
                            new NewCommand(),
                            new Eto.Forms.SeparatorMenuItem(),
                            new ButtonMenuItem
                            {
                                Text = "Recent files...",
                                Items =
                                {
                                    new Command()
                                    {
                                        MenuText = "File: Lol.abc"
                                    }
                                }
                            },
                            new Eto.Forms.SeparatorMenuItem(),
                            new ExitCommand()
                        }
                    },
                    new ButtonMenuItem
                    {
                        Text = "Edit",
                        Items =
                        {
                            new UndoCommand()
                        }
                    }
                }
            };

            Menu = menubar;

            GlWidget glWidget = new GlWidget();

            var layout = new DynamicLayout();

            layout.Padding = 4;

            layout.BeginVertical(); // fields section
            layout.AddRow(glWidget.ToEto());
            Trace.WriteLine("GlWidget loads with OpenGL.Net");
            layout.EndVertical();
            Content = layout;

            // For OpenGL
            glWidget.Hexpand = true;
            glWidget.Vexpand = true;

            glWidget.SetSizeRequest(200, 200);
            glWidget.SizeAllocated += GlWidget_SizeAllocated;
            glWidget.ContextCreated += GlWidget_ContextCreated;
            glWidget.Render += GlWidget_Render;

        }

        private void GlWidget_ContextCreated(object sender, GlWidgetEventArgs e)
        {
            Gl.ClearColor(0.39f, 0.58f, 0.93f, 1.0f);
            Gl.MatrixMode(OpenGL.MatrixMode.Projection);
            Gl.LoadIdentity();
            Gl.Ortho(0.0, 1.0, 0.0, 1.0, 0.0, 1.0);
        }

        private void GlWidget_SizeAllocated(object o, SizeAllocatedArgs args)
        {
            Gl.Viewport(0, 0, args.Allocation.Width, args.Allocation.Height);

        }

        private void GlWidget_Render(object sender, GlWidgetEventArgs e)
        {
            Gl.Clear(OpenGL.ClearBufferMask.ColorBufferBit);

            // Animate triangle
            Gl.MatrixMode(OpenGL.MatrixMode.Modelview);
            Gl.Rotate(_Angle, 0.0f, 0.0f, 45.0f);

            if (Gl.CurrentVersion >= Gl.Version_110)
            {
                // Old school OpenGL 1.1
                // Setup & enable client states to specify vertex arrays, and use Gl.DrawArrays instead of Gl.Begin/End paradigm
                using (MemoryLock vertexArrayLock = new MemoryLock(_ArrayPosition))
                using (MemoryLock vertexColorLock = new MemoryLock(_ArrayColor))
                {
                    // Note: the use of MemoryLock objects is necessary to pin vertex arrays since they can be reallocated by GC
                    // at any time between the Gl.VertexPointer execution and the Gl.DrawArrays execution

                    Gl.VertexPointer(2, OpenGL.VertexPointerType.Float, 0, vertexArrayLock.Address);
                    Gl.EnableClientState(OpenGL.EnableCap.VertexArray);

                    Gl.ColorPointer(3, OpenGL.ColorPointerType.Float, 0, vertexColorLock.Address);
                    Gl.EnableClientState(OpenGL.EnableCap.ColorArray);

                    Gl.DrawArrays(OpenGL.PrimitiveType.Triangles, 0, 3);
                }
            }


        }

        private static float _Angle;

        /// <summary>
        /// Vertex position array.
        /// </summary>
        private static readonly float[] _ArrayPosition = new float[] {
            0.0f, 0.0f,
            0.5f, 1.0f,
            1.0f, 0.0f
        };

        /// <summary>
        /// Vertex color array.
        /// </summary>
        private static readonly float[] _ArrayColor = new float[] {
            1.0f, 0.0f, 0.0f,
            0.0f, 1.0f, 0.0f,
            0.0f, 0.0f, 1.0f
        };

        [STAThread]
        static void Main(string[] args)
        {
            Environment.CurrentDirectory = Path.Combine("Runtimes");

            if (args.Length > 0 && args[0] == "console")
            {
                Console.WriteLine("Hello world!");
                Console.ReadLine();
            }
            else
            {
                var app = new Eto.Forms.Application(new Eto.GtkSharp.Platform());
                app.Run(new MyForm());
            }
        }
    }
}
```
Why does it happen with Maximize/Restore doesn't see enabled. I didn't change from Dialog - just use only "Form" I already get fresh MyForm.cs from Program.cs and I start Tutorial -> Hello Eto Form ->  C# Script.

Is it bug? Or did you forget compatibility of Gtk2 and Gtk3?
Thanks!

// EDIT Found Eto.Gtk3/Forms/FormHandler.cs 
```
		public FormHandler()
		{
			Control = new Gtk.Window(Gtk.WindowType.Toplevel);
#if GTK2
			Control.AllowGrow = true;
#else
			Control.Resizable = true;
#endif
			Control.SetPosition(Gtk.WindowPosition.Center);
			Control.TypeHint = Gdk.WindowTypeHint.Desktop;

			var vbox = new Gtk.VBox();
			vbox.PackStart(WindowActionControl, false, true, 0);
			vbox.PackStart(WindowContentControl, true, true, 0);
			Control.Child = vbox;
		}
```
You have forget to add `Control.TypeHint = Gdk.WindowTypeHint.Desktop;`

Please update next release!

**Comment by cwensley** [comment]
Hey @sourceskyboxer, thanks for submitting the issue!

Just to confirm, you're seeing this issue on Windows?  Have you tried any other platforms?

**Comment by sourceskyboxer** [comment]
You know I have tried native Gtk Sharp 3 without Eto.Forms = It works fine.

Only Gtk Sharp 3:
```
        [STAThread]
        static void Main(string[] args)
        {
            Environment.CurrentDirectory = Path.Combine("Runtimes");

            if (args.Length > 0 && args[0] == "console")
            {
                Console.WriteLine("Hello World!");
                Console.ReadLine();
            }
            else
            {
                Gtk.Application.Init();
                Console.WriteLine("Start Gtk.Window...");
                Gtk.Window win = new Gtk.Window(Gtk.WindowType.Toplevel);
                win.SetSizeRequest(300, 300);
                win.DeleteEvent += delegate { Gtk.Application.Quit(); };
                win.Show();
                Gtk.Application.Run();
            }
        }
```
It sees with "enabled" Maximize/Restore on title bar:
![gtk_show_enabled_mr](https://user-images.githubusercontent.com/3496136/36072110-5ba44426-0f1a-11e8-8b98-e3294e86aa9e.JPG)

With Eto.Forms
It forgets to enable or goes wrong if Window has not WindowTypeHint.Normal.

**Comment by sourceskyboxer** [comment]
Hello I am back now - because I found @Nihlus has explained me about GLArea But @cra0zy  didn't tell me truth. That is why good work but I have problem with stupid access violation executing location exception if I use SizeAllocated event than GL.Viewport(0, 0, args.Allocation:Width, args.Allocation.Height);

Than it throws error because latest version of OpenTK I already downloaded from Github and I tried and no success :(

Check OpenTK's [issue](https://github.com/opentk/opentk/issues/741#issuecomment-372984457) !

Thanks!

**Comment by cwensley** [comment]
Hi @sourceskyboxer, thanks for the additional comments, but those seem related to etoViewport (the OpenTK control for Eto.Forms), not Eto.Forms itself.

Also, this particular issue is about having the maximize button appear correctly when run in windows, so it would help if the discussion here revolved around that.

**Comment by sourceskyboxer** [comment]
Really etoViewport ?? I have to know because etoViewport looks incompatible to latest version.

Yes But I want use native GTK Sharp 3 ( 3.22.6.4 ) And it has still exception "Access violation executing location". I can't understand why I have exception of OpenTK ( Latest I have downloaded and compiled but SizeAllocaed makes GL.Viewport as exception problem. Check issue in OpenTK!

I have tried Eto:Forms = No Problem! but it can't use SizeAllocated or Resize problem with GLWidget

PS: Why do I need many unusable assemblies of Eto.Forms like System:Runtime.dll and any dlls and it cannot bundle into executable because it throws exceptions and errors and it sees like invisibly.

**Comment by cwensley** [comment]
> Really etoViewport ?? I have to know because etoViewport looks incompatible to latest version.
>
> Yes But I want use native GTK Sharp 3 ( 3.22.6.4 ) And it has still exception "Access violation executing location". I can't understand why I have exception of OpenTK ( Latest I have downloaded and compiled but SizeAllocaed makes GL.Viewport as exception problem. Check issue in OpenTK!
>
> I have tried Eto:Forms = No Problem! but it can't use SizeAllocated or Resize problem with GLWidget

Ah, didn't realize you weren't using it.  Regardless, it sounds like this isn't a problem with Eto, so I'm not sure what you're asking us to do about it.

>PS: Why do I need many unusable assemblies of Eto.Forms like System:Runtime.dll and any dlls and it cannot bundle into executable because it throws exceptions and errors and it sees like invisibly.

These are for .NET Standard compatibility, they are not the "actual" assemblies from the runtime.  The higher version of .NET you target (e.g. .NET 4.7), the fewer of these compatibility assemblies will be needed.

**Comment by sourceskyboxer** [comment]
@cwensley Wow too manc unusable assemblies from Net Frameworks 4.7, uh?
I have tried to bundle with mkbundle but bundled application by mkbundle throws exception in msys2 / pacman like Net Frameworks = 4.0.0.

Thanks for statement! But Mono hates higher version of net frameworks because they can't bundle into native executables like executables don't need to install net frameworks or mono runtime. Example in schools, students, public net cafes or whatever if you present 3D Cad or Office ( written from Eto or Gtk Sharp 3 with Mono-Bundled executables ). It looks like Unity Engine or bundled applications.

How are Ubuntu users now? They are arguing because sometime executables can't show user interface like Unity Editor under Ubuntu happens - It can't show gui only black window. That is why - I really want without unusable assemblies - if you use Eto.Forms without Net Frameworks 4.7 just only Net Frameworks 4.5 without WPF. Than they bundle with Mono mkbundle than release to Ubuntu, Mac OS or Windows and executables show real like native executables without problems or eceptions. Thanks I wish you have to decide to remove WPF version in Eto.Forms with sensitive Mono make-bundler.

Please give me chance without higher unusable assemblies!

**Comment by cwensley** [comment]
@sourceskyboxer I'm not sure what you're trying to say, you would never use WPF in linux so there's no problem there.  And it will never be removed from Eto as it is required for Windows support.  

Just don't include it with your application, it is not required.
