### ISSUE TITLE
Text area with watermark - auto-defocus?

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#1021]
Recently, I developed a simple derivative of ```TextArea``` to support a watermark (i.e. when the control is empty, a watermark is shown to give the user a hint on what to enter). It all works fine, except that I have to manually move the focus *away* from the control prior to loading. It would be nice if there was a way to automatically do that, but I haven't found it. Is it possible?

For reference, this is the control I'm using:

      /// <summary>
      /// Textarea with a watermark. When no text is entered, the watermark is shown for e.g. a hint on what to enter.
      /// For this to work on load, the focus should be taken OFF this control as soon as possible (after construction) by moving it to another control.
      /// </summary>
      public class WatermarkTextArea : TextArea
      {
        /// <summary>
        /// The watermark shown when no text is entered
        /// </summary>
        public String Watermark
        {
          get { return _watermark; }
          set
          {
            if (string.Equals(_watermark, value)) return;
            _watermark = value;
            OnWatermarkChanged(new EventArgs());
          }
        }

        /// <summary>
        /// Triggered when the <see cref="Watermark"/> has changed.
        /// </summary>
        /// <param name="e"></param>
        protected virtual void OnWatermarkChanged(EventArgs e)
        {
          Properties.TriggerEvent(WatermarkChangedEvent, this, e);
        }

        /// <summary>
        /// Identifier for handlers when attaching the <see cref="WatermarkChanged"/> event
        /// </summary>
        public const string WatermarkChangedEvent = "WatermarkTextArea.WatermarkChanged";

        /// <summary>
        /// Occurs when the <see cref="Watermark"/> property is changed.
        /// </summary>
        public event EventHandler<EventArgs> WatermarkChanged
        {
          add { Properties.AddHandlerEvent(WatermarkChangedEvent, value); }
          remove { Properties.RemoveEvent(WatermarkChangedEvent, value); }
        }

        /// <summary>
        /// Binding for the <see cref="Watermark"/> property
        /// </summary>
        public BindableBinding<WatermarkTextArea, string> WatermarkBinding
        {
          get
          {
            return new BindableBinding<WatermarkTextArea, string>(
              this,
              c => c.Watermark,
              (c, v) => c.Watermark = v,
              (c, h) => c.WatermarkChanged += h,
              (c, h) => c.WatermarkChanged -= h
            );
          }
        }

        /// <summary>
        /// The foreground color of the watermark text
        /// </summary>
        public Color WatermarkColor { get; set; } = Colors.DarkGray;

        private Color _previousColor = Colors.Black;
        private bool _watermarkRemoved;
        private string _watermark;

        /// <summary>
        /// When load is complete, the watermark text is set
        /// </summary>
        /// <param name="e"></param>
        protected override void OnLoadComplete(EventArgs e)
        {
          _previousColor = TextColor;
          _watermarkRemoved = false;

          var bgc = BackgroundColor;
          Text = Watermark;

          BackgroundColor = bgc;
          TextColor = WatermarkColor;

          base.OnLoadComplete(e);
        }

        /// <summary>
        /// When the control receives focus, the watermark is removed and the text color is reinstated.
        /// </summary>
        /// <param name="e"></param>
        protected override void OnGotFocus(EventArgs e)
        {
          if (_watermarkRemoved) return;
          _watermarkRemoved = true;

          if (Text == Watermark || string.IsNullOrEmpty(Text))
          {
            Text = String.Empty;
            TextColor = _previousColor;
          }

          base.OnGotFocus(e);
        }

        /// <summary>
        /// When the control loses focus, the watermark is restored iff there is no text in the controls.
        /// </summary>
        /// <param name="e"></param>
        protected override void OnLostFocus(EventArgs e)
        {
          if (String.IsNullOrWhiteSpace(Text))
          {
            OnLoadComplete(e);
          }

          base.OnLostFocus(e);
        }
      }

**Comment by cwensley** [comment]
Hm, interesting.  The only way to programatically "unset" focus at this point is to set focus to some other control.  I'm guessing it's the first control in your form?  Otherwise it would not have focus initially.

Another option is to show the watermark when it doesn't have focus _or_ is empty.  This can get a wee tricky, but when the user inserts text (the TextInput event might work), then you'd clear out the watermark and set the text.  When the user deletes all the text then you'd go back into the showing watermark mode.

Also, just FYI it's probably not a good idea to call `OnLoadComplete` from `OnLostFocus`, you should move that logic to a separate method and call it from both places.

**Comment by mennodeij** [comment]
It is indeed the first control *that can receive keyboard focus* (if I place a label above it, and focus on that, it still puts keyboard focus on the text area). 
I'll try and see about the TextInput event, that is a good suggestion. And you're right, cutting corners with OnLoadComplete is a bit dodgy :smile: 

I'll close this for now. Thanks for your quick reply.
