### ISSUE TITLE
Error upgrading to v2.4.1 from v2.4.0-build1195

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#1034]
Trying to update the Eto.Forms package from v.2.4.0-build1195 to v2.4.1 on Visual Studio 2015 (Windows 10) gives the following error:

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The attribute "Update" in element <Compile> is unrecognized.  C:\Users\Daniel\Source\Repos\dwsim5\packages\Eto.Forms.2.4.1\build\Eto.Forms.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Internal.ProjectXmlUtilities.ThrowProjectInvalidAttribute(XmlAttributeWithLocation attribute)
   at Microsoft.Build.Internal.ProjectXmlUtilities.VerifyThrowProjectAttributes(XmlElementWithLocation element, String[] validAttributes)
```

Are you using specific VS 2017 commands on the install scripts?

**Comment by cwensley** [comment]
That isn't the install script, but the .targets file that is included with the nupkg.  I have updated everything (templates, etc) to require VS 2017, but we may be able to make at least the nuget packages work on VS 2015 by checking the tools version.

Thanks for reporting the issue!

**Comment by DanWBR** [comment]
I'll close this issue as you're explicitly supporting VS2017 only from now on.

**Comment by cwensley** [comment]
Hey @DanWBR, for the VS extension and templates that is true, but I think we can still support VS2015 toolset for the nuget packages fairly easily.

**Comment by DanWBR** [comment]
I think you already have too much to worry about, this is not a big deal as vs 2017 is much better than 2015, there is no reason not to upgrade...

**Comment by cwensley** [comment]
Cool, thanks for the feedback @DanWBR.
