### ISSUE TITLE
WebView throws exception on new, running on linux

### ISSUE THREAD

**Issue by davidscherf** [picoe/Eto#1040]
## Expected Behavior
Web = new WebView();
Create the object so I can place it on the screen

## Actual Behavior
web = new WebView()
Exception
DLL not found libwebkit2gtk-4.0.so.37

## Steps to Reproduce the Problem

  1.  Raspberry PI running Raspbian
       Mono 5.10.0
       GTK 3 installed
  2. Run some test code that just makes a new WebView

## Code that Demonstrates the Problem
WebView Web;
Web = new WebView();
## Specifications

  - Version: 2.4.1 From Nuget
  - Platform: Gtk3, Mono, Raspbian

**Comment by cra0zy** [comment]
The error you are getting could give you any more information on what you are missing... https://packages.debian.org/sid/libwebkit2gtk-4.0-37

**Comment by davidscherf** [comment]
ok, installed package libwebkit2gtk-4.0-37
I did not know the exact name is apt could not find it.
Now WebView works again thx

**Comment by cra0zy** [comment]
@cwensley This can be closed.
