### ISSUE TITLE
Exception thrown when attempting to overwrite ReactiveProperty's value outside constructor

### ISSUE THREAD

**Issue by YSRKEN** [picoe/Eto#1041]
Raise an exception when overwrite the value of ReactiveProperty.Value not in constructor method

## Expected Behavior

- When you press "Button 1" button, the black image of width 100 and height 200 displayed in ImageView will be replaced with a black image with width 200 and height 100.
- When you press "Button 2" button, the word "B" is added to the end of the character string displayed on the Label.

## Actual Behavior
  Whichever button you press, the exception "System.Reflection.TargetInvocationException" occurs in mscorlib.dll.

## Steps to Reproduce the Problem

  1. Clone this repository(https://github.com/YSRKEN/EtoApp1)
  2. Build all projects by Visual Studio 2017
  3. Run EtoApp1.Desktop.exe
  4. Press "Button 1" or "Button 2" button

## Code that Demonstrates the Problem

  Please show MainForm.xeto.cs and MainForm.xeto in this repository(https://github.com/YSRKEN/EtoApp1)

## Specifications

  - Version: Eto.Forms v2.4.1, ReactiveProperty v4.2.0, VisualStudio 2017 v15.5.7
  - Platform(s):  Windows 10 Pro v1709 (64bit)

**Comment by cwensley** [comment]
Thanks for reporting the issue! I can't see anything obvious why it isn't working, so I'll have to track that down.

**Comment by cwensley** [comment]
Hey @YSRKEN, sorry for this taking so long, but I finally verified that all other platforms behave the same way where the synchronization context is available after the application is created.

Thanks again!  And thanks @oigami for the fix!
