### ISSUE TITLE
Incorrect AppIcon assets

### ISSUE THREAD

**Issue by thomas-goerlich** [picoe/Eto#1042]
## Expected Behavior
Creating a XamMac project creates a correct AppIcon assets catalog.

## Actual Behavior
The 2x icons are not added (due to incorrect Icon names).

## Steps to Reproduce the Problem

  1. Create a new project including XamMac
  2. Check out the Assets in XamMac
  3. 2x images are missing

## Specifications

  - Version: 2.4.1.1
  - Platform(s): XamMac

Finder Window:
![etoappiconpossiblebug](https://user-images.githubusercontent.com/1237975/37063081-9f7ff06a-2198-11e8-9df4-7d363409c4ae.png)
Visual Studio:
![etoappiconpossiblebug2](https://user-images.githubusercontent.com/1237975/37063084-a2a0dbba-2198-11e8-8473-6bb7533ef008.png)

Renaming the Icons (replacing %40 with @) fixes the problem.
The assets seem to be named correctly in the Addins Template:
https://github.com/picoe/Eto/tree/develop/src/Addins/Eto.Forms.Templates/content/App-CSharp/EtoApp.1.XamMac/Assets.xcassets/AppIcon.appiconset

**Comment by cwensley** [comment]
Hey @thomas-goerlich ah, I thought I had that problem solved.  It might be due to an (extremely) old version of the dotnet template engine that's embedded in VS for Mac.  It could also have something to do with the packaging of the template.  Thanks for submitting the issue!

**Comment by cwensley** [comment]
This looks to be resolved in the latest version of VS for Mac (and probably for a while).  Tested with VS for Mac 7.6.5.

Thanks again for reporting the issue!
