### ISSUE TITLE
Preview not working in Visual Studio 15.6 (2.4.1)

### ISSUE THREAD

**Issue by avinabmalla** [picoe/Eto#1048]
The Eto.Forms preview is not working for me with Visual Studio 2017. It crashes with the following message.
![2018-03-14](https://user-images.githubusercontent.com/6552000/37381446-556f7e64-2765-11e8-83c4-7464246f0398.png)

**Comment by avinabmalla** [comment]
I installed the 2.4.0 extension from https://github.com/picoe/Eto/releases and it works.

**Comment by cwensley** [comment]
Hi @avinabmalla, thanks for reporting the issue!

Must be something to do with the dark theme support, I'll check into it!

**Comment by cwensley** [comment]
Should now be fixed, and in the marketplace for auto update!

**Comment by avinabmalla** [comment]
It's working now. Dark mode looks great! Thanks!

**Comment by cwensley** [comment]
Hey @avinabmalla, I really appreciate the quick verification.  It's very helpful to know it's working!
