### ISSUE TITLE
WPF : GroupBox Font is null when queried.

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1052]
For an instantiated GroupBox, the Font property is null under WPF. This makes querying or setting the Font problematic.

To see this, simply create a GroupBox and inspect its properties - the Font will be null.

On WinForms, this is defined.

This is with the Eto.Forms 2.4.1 release. Test platform is Win 10 x64 Redstone 4 build 17115, VS 2017.

**Comment by cwensley** [comment]
Thanks for reporting the issue!

**Comment by cwensley** [comment]
Should now be fixed!  Also found an issue with Gtk for GroupBox and CheckBox which should also be fixed (thanks unit testing!).

Cheers, and thanks again for reporting!
