### ISSUE TITLE
Visual Studio Plugin: Could not setup proxy for domain

### ISSUE THREAD

**Issue by Mike-EEE** [picoe/Eto#1054]
I'm kicking the tires on this after seeing [Hanselman's plug for it on his blog](https://www.hanselman.com/blog/CrossPlatformGUIsWithOpenSourceNETUsingEtoForms.aspx) (congratulations 😄).  I installed the Visual Studio Extension, created a new project with Code Preview, but when I attempt to open `MainForm.etc.cs`, I get the following error:

![image](https://user-images.githubusercontent.com/2931376/37501520-1612e2ce-28a5-11e8-915c-29b66d9c4bc0.png)

FWIW, my whole intention here is to find out what "Code Preview" is as it doesn't make any sense to me.., yet. LOL.  Any guidance here would be greatly appreciated!

**Comment by cwensley** [comment]
Hey @Mike-EEE, thanks!  Yes, this error popped up with the VS 15.6 update, it worked in 15.5 and was reported with #1048.  I have a fix incoming.  Marking this as duplicate and you can follow the other issue for when it's fixed!

**Comment by Mike-EEE** [comment]
Ah! OK... I did do a search for the error message but it turned up empty.  Hopefully this issue will assist those who do the same going forward.  Thank you for your quick reply @cwensley !

**Comment by cwensley** [comment]
@Mike-EEE So you know, this should now be fixed (;

**Comment by Mike-EEE** [comment]
Woohoo!  And it is!  Checking it out now... super cool!  Thanks again!
