### ISSUE TITLE
Label text is cut off when adding integer value

### ISSUE THREAD

**Issue by BlackDragonDv** [picoe/Eto#1057]
#When I'm trying to (in function called by button event) add integer value to string and set label text to result, string is cut off. When I do same thing in constructor (label is created in this constructor) everything works fine.

Here is example:
```csharp
public MainForm()
{
label = new Label { Text="Lorem ipsum" };
button.Click += buttonClicked;
}

void buttonClicked(object sender, EventArgs e)
{
int val = 10;
label.Text = val + "Lorem ipsum";
}
```

After button click "Lorem ipsum" become "10Lorem". But when I use code from buttonClicked method in constructor after Label creation it working without problems and text is "10Lorem Ipsum". I'm using GTK backend (working on Linux with Mono).

**Comment by BlackDragonDv** [comment]
Yes, there is enough space to expanded label. When I do same thing in constructor, label show full text after change (same code). I got issue when trying to do this in function called by button event. Only here, because in another function (not called by Event) this working too.

**Comment by cwensley** [comment]
When you do it in the constructor, the form will be auto sized to the expanded label.  Doing it in the event means that if the form was too small to show the changed label it will cut it off.

Do you have a more complete example of your problem?  It'd help to see where in your layout you have the label.

**Comment by BlackDragonDv** [comment]
I can see when this happens - label is in GroupBox with own layout (after end I add GroupBox to main layout). I don't know why this happen, because layout is enough big.

Here is full code with same issue. I hope this can help You understand issue:
```csharp
        Label label;

        public MainForm()
        {
            Title = "My Eto Form";
            ClientSize = new Size(400, 350);

            var layout = new PixelLayout();

            var button = new Button { Text = "Click Me" };
            layout.Add(button, 0, 0);

            var groupBoxLay = new PixelLayout();
            groupBoxLay.Size = new Size(200, 200);
            label = new Label { Text = "Lorem ipsum" };
            groupBoxLay.Add(label, 0, 0);

            var groupBox = new GroupBox();
            groupBox.Content = groupBoxLay;

            layout.Add(groupBox, 0, 40);

            button.Click += buttonClick;

            Content = layout;
        }

        void buttonClick(object sender, EventArgs e)
        {
            int val = 10;
            label.Text = val + "Lorem ipsum";
        }
```

Results is same - after clicking button "Lorem ipsum" become "10Lorem".

**Comment by cwensley** [comment]
Hey @BlackDragonDv,

Thanks, I really appreciate the full sample!  Also, thanks for testing windows to verify behaviour there. Looking at your code, this is definitely a bug.  

Just as an aside, I'm not sure you're aware that using `PixelLayout` is discouraged as controls will typically have different sizes depending on the platform you're on (labels, buttons, etc all have different sizes on Mac, Windows, and Linux).  `TableLayout`, `StackLayout`, and `DynamicLayout` are great for dealing with varying control sizes.  There are times when `PixelLayout` makes perfect sense though, so forgive me if this is what you intended.

**Comment by BlackDragonDv** [comment]
Good to know this, thank You very much.

Yeah, I know this. I'm using PixelLayout, because I'm writing application only for Linux. I know this sounds weird but I'm just rewriting one of my small application from WinForms to Eto. I'm doing this not because I need this app on Linux, but I just want to check and learn Eto API and features. I will use proper layout when I will be developing real application. This one is only for testing purposes.

**Comment by BlackDragonDv** [comment]
One thing more - I've changed GroupBox Layout to DynamicLayout from PixelLayout, and it's working on Linux too. I get "10Lorem Ipsum" just like on Windows. It looks like problem is limited only to PixelLayout. I've checked other layouts (TableLayout, StackLayout, DynamicLayout) and they were working as well.

**Comment by cwensley** [comment]
Thanks @BlackDragonDv, it's good to know that the other layouts work.  It'll help narrow down the issue.

**Comment by cwensley** [comment]
Hey @BlackDragonDv, thanks again for reporting this issue!  This should now be fixed in the develop branch.

**Comment by DragonSWDev** [comment]
Hey @cwensley, nice to hear it's fixed. Thank you and all contributors for Eto.
