### ISSUE TITLE
Xaml does not work on .net core

### ISSUE THREAD

**Issue by emmauss** [picoe/Eto#1060]
## Expected Behavior
Default template form loads and shows up.

## Actual Behavior
Throws an exception in the form's xeto class file at the contructor's `XamlReader.Load()`. The exception is
```Portable.Xaml.XamlObjectWriterException: 'Cannot set unknown member '{http://schema.picoe.ca/eto.forms}```. 

## Steps to Reproduce the Problem

  1. Create default eto.forms project with xaml and combined platforms
  2. change the target of the desktop project to `netcoreapp2.0` it its project file, or create a .net core 2.0 console project. Install necessary nugets. 
  3. Run the form in the desktop project.

## Code that Demonstrates the Problem
No change in code.

## Specifications

  - Version: 2.41
  - Platforms : Windows, WPF and GTK

**Comment by cwensley** [comment]
Thanks for submitting the issue, I'll have to take a look into why it's doing that.

Just so you know, GTK is the only platform that actually supports .NET Core at this point.

**Comment by dsoronda** [comment]
I'm trying same thing on Linux and I have question :
Shouldn't XAML serialization be separated from UI engine or I'm missing something here?

**Comment by cwensley** [comment]
@dsoronda, you are correct.  All of the XAML serialization is done in Portable.Xaml and Eto.Serialization.Xaml, which is separate from Eto.dll.

**Comment by dsoronda** [comment]
Well, I found part of problem 

For error: 
`Portable.Xaml.XamlObjectWriterException: 'Cannot set unknown member '{http://schema.picoe.ca/eto.forms}` 

Solution:
Problem is that file `MainForm.xeto` should have Build action as `Embedded resource` .

Now I get new error:
`Cannot set unknown member '{http://schema.picoe.ca/eto.forms}Form.Title'` from XamlReader.cs line 186 
 in Eto.Serialization.Xaml project.

**Comment by dsoronda** [comment]
Actaully, problem is in Eto.Serialization.Xaml.EtoXamlSchemaContext line 33
~~~csharp
		protected override XamlType GetXamlType(string xamlNamespace, string name, params XamlType[] typeArguments)
		{
			XamlType type = null;
			try
			{
		NULL->>>		type = base.GetXamlType(xamlNamespace, name, typeArguments);
			}
			catch
			{
				if (!DesignMode || type != null)
					throw;
				// in designer mode, fail gracefully
				type = new EtoDesignerType(typeof(DesignerMarkupExtension), this) { TypeName = name, Namespace = xamlNamespace };
			}
			return type;
		}
~~~
`type = base.GetXamlType(xamlNamespace, name, typeArguments);` returns null and it should be :

  | Name | Value | Type
-- | -- | -- | --
◢ | $ReturnValue | {{http://schema.picoe.ca/eto.forms}Form} | Eto.Serialization.Xaml.EtoXamlType

So, problem is in Portable.Xaml after all.

**Comment by cwensley** [comment]
@dsoronda thanks for looking into the issue in detail, it is really helpful!  This should now be fixed.

Thanks @emmauss for reporting the issue.

**Comment by dsoronda** [comment]
@cwensley np, Thank you for Eto.Forms :)
