### ISSUE TITLE
Visual Studio Multi Project Template Issues

### ISSUE THREAD

**Issue by mindingdata** [picoe/Eto#1061]
When I downloaded and installed the Eto.Forms Visual Studio extension, then created a *multi* project solution, the WPF project is not setup correctly. 

## Expected Behavior

I would expect that after creating the base project. The WPF project is able to be deployed and ran immediately. 

I would also expect that all projects run on Any CPU. 

## Actual Behavior

For some reason, the solution is configured first that all other projects are built using Any CPU, but the WPF project is set to use only X86. This isn't too much of an issue, more of a hassle because then you have this weird configuration setup. I checked the single project and it uses Any CPU so it's not a requirement of the WPF project as far as I know. When I remove this configuration and make it run on Any CPU and completely delete all X86 configuration, everything still runs fine. 

![image](https://user-images.githubusercontent.com/1021021/37570293-fa03dbd2-2b52-11e8-8bc5-61023b0b561f.png)

The second thing you will notice is obviously it's not set to build. Meaning when you try and build the solution, it doesn't actually build the WPF project. 

And the final thing is that the output path wasn't written to the csproj correctly. I'm not really sure how this comes to be, but if you right click on the project, go Properties, then Build, then say you remove the trailing slash (Doesn't make a difference but it allows you to save), and then save, your output path will be written to CSProj and you will be able to build. For example if you try and build the Wpf project immediately after creating the solution, it will complain about not having an output path. 

## Steps to Reproduce the Problem

  1. Install the Eto.Forms Visual Studio Extension
  2. Create a Multi Project Solution using Code as the form builder
  3. Do nothing else. And try and run the Wpf project. 

This is using version 2.4.1.1 of the tools. 

I should also note this does not happen when using a dotnet new command to template your code.

**Comment by cwensley** [comment]
Hey @mindingdata, thanks for submitting the issue!  

> For some reason, the solution is configured first that all other projects are built using Any CPU, but the WPF project is set to use only X86

This is because the default WPF project template is set up the same way (the csproj in Eto's template was created from a new WPF project).  Many people complain about it, so perhaps I should just make it Any CPU instead of preferring 32-bit.

Regardless, I'm not sure why VS is not setting it as part of the build, I'll have to take a look at what can be done about it.  Possibly because of it being set to x86, I'm not sure.   My testing involved setting the WPF project as the startup and then running, which does seem to work without any modifications to the solution.

**Comment by cwensley** [comment]
@mindingdata what version of Visual Studio are you using?  I can't seem to reproduce it on 15.6.2.

**Comment by mindingdata** [comment]
Hmmm. 15.3.4. I'll update shortly and give it another go.

**Comment by mindingdata** [comment]
With updating Visual Studio, It's set to build and set Any CPU? Did you change anything?

![image](https://user-images.githubusercontent.com/1021021/37624021-93b2088e-2c2b-11e8-82c5-1e0bcb1f8dbc.png)

**Comment by cwensley** [comment]
@mindingdata nope.  Same template as before, I think it's probably a bug in VS or just different behaviour.  I only ever tested the new templates with VS 15.5+

**Comment by cwensley** [comment]
This is the csproj used for the template: https://github.com/picoe/Eto/blob/develop/src/Addins/Eto.Forms.Templates/content/App-CSharp/EtoApp.1.Wpf/EtoApp.1.Wpf.csproj

**Comment by cwensley** [comment]
So just to confirm, everything is working with the latest VS release?

**Comment by mindingdata** [comment]
Would appear that way :) 

I will also say that the multi project template using dotnet from terminal also is fine (And always was).

**Comment by cwensley** [comment]
Cool, thanks!
