### ISSUE TITLE
Problem GetBrush in Pen Wpf

### ISSUE THREAD

**Issue by mdeejee** [picoe/Eto#1066]
## Expected Behavior

In Eto.Wpf.Drawing.PenHandler.cs  : 
public Brush GetBrush (Pen widget)		
{			
    var brush = ((swm.Pen)widget.ControlObject).Brush;			
    return brush.GetValue(brushProp) as Brush;		
}

This method returns the correct Brush

## Actual Behavior

Always return null

## Steps to Reproduce the Problem

  1. Create a Pen with Color
  2. 
  3. 

## Code that Demonstrates the Problem

```
To solve problem temporary :

public Brush GetBrush (Pen widget)
		 => new SolidBrush((((swm.Pen)widget.ControlObject).Brush as swm.SolidColorBrush).ToEtoColor());
```

## Specifications

  - Version: All
  - Platform(s):  WPF

**Comment by cwensley** [comment]
Thanks for submitting the issue!
