### ISSUE TITLE
Incorrect value of Form.Size after start (initialization with ClientSize)

### ISSUE THREAD

**Issue by JAD-SVK** [picoe/Eto#1067]
## Introduction to problem

I˝m new to Eto.Forms and I tried to create my first application *(change of answer/example to a Stackoverflow question)*.

This problem is (somewhat) related to the issue #456 *(at least in the incorrect value of `Size`)*

## Expected Behavior

Place the application to right bottom corner of screen. *(Stackoverflow question)*

The `Size` property of the `Form` contains correct values *(current application size)*.

## Actual Behavior

The application is placed on the left bottom corner of right secondary screen *(on the level of task bar)*.

The `Size` property of the `Form` contains incorrect values {-1, -1}.

When the form is initialized with using `Form.Width` and `Form.Height` *(after line `SuspendLayout();` and before `Form.ClientSize` on line 29 from the example)* the value/initialization of `Form.ClientSize` is ignored and the application is placed on a correct place. But the `Width` must be greater than minimum. When the `Width` is small *(e. g. 35)* the application has 35 pixels on the primary screen and the rest is on the secondary screen.

## Steps to Reproduce the Problem

  1. Run the application
  2. *(break point on line 38 to see the value of `Form.Size`)*

## Code that Demonstrates the Problem

```C#
using System;
using Eto.Drawing;
using Eto.Forms;

namespace ApplicationPosition
{
  internal class Program : Form
  {
    [STAThread]
    private static void Main()
    {
      using (Application application = new Application())
      using (Program dlg = new Program())
      {
        application.Run(dlg);
      }
    }

    public Program()
    {
      InitializeComponent();
    }

    private void InitializeComponent()
    {
      SuspendLayout();
      //this.Width = 35;
      //this.Height = 35;
      this.ClientSize = new Size(315, 218);
      this.Title = "Application title";
      this.Load += Program_Load;
      ResumeLayout();
    }

    private void Program_Load(object sender, EventArgs e)
    {
      var workingArea = Screen.PrimaryScreen.WorkingArea;
      var left = workingArea.Left + workingArea.Width - this.Size.Width;
      var top = workingArea.Top + workingArea.Height - this.Size.Height;
      this.Location = new Point((int)left, (int)top);
    }
  }
}
```

## Specifications

  - Version: 2.4.1 *(downloaded yesterday with Visual Studio NuGet package)*
  - Platform(s):  WinForms
  - OS: Windows 7, x64,
  - Environment: Visual Studio 2017 Express for Windows Desktop,
  - Screens: two screens *(primary screen is left, secondary with the same resolution and placement (top = 0) is on right)*,
  - Other: task bar is at bottom of the primary screen,

**Comment by cwensley** [comment]
Sorry for the late reply, but the Size is only set after the `Shown` event, not `Load`.

**Comment by cwensley** [comment]
Closing this as I don't think it's an issue.  The wrong event is being used to detect the size.

Feel free to comment further or reopen if that solution doesn't work for you.

Thanks again for your inquiry!
