### ISSUE TITLE
Eto.Drawing does not exist?

### ISSUE THREAD

**Issue by kot-mapku3** [picoe/Eto#1071]
## Expected Behavior
When I downloaded extensions for VS Mac i successfully installed them. Then i pushed **Create New Project** and pressed run. VS Mac answer: Eto.Drawings does not exist in namespace Eto.
One more: Application(Eto.Platform.Detect).Run(new MainForm()); -> red underline, because Platform does not exist in namespace Eto.

## Steps to Reproduce the Problem

  1. Install Extension Eto for VS Mac
  2. Run the program

## Code that Demonstrates the Problem

```
using System;
using Eto.Forms;
using Eto.Drawing;

namespace Eto.Desktop
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            new Application(Eto.Platform.Detect).Run(new MainForm());
        }
    }
}
```

## Specifications

  - Version: Lastest version extension.
  - Platform(s): Mac, VS Mac

**Comment by cwensley** [comment]
Hi @kot-mapku3, thanks for reporting the issue!

Did you wait for the nuget packages to restore before building the app?  These errors point to a problem restoring the nuget packages.  Also, check your nuget config for any sources that may be invalid.  In some cases on macOS, the nuget packages won't restore if one of the sources is invalid.

Also, what version specifically of VS for Mac are you using?

**Comment by kot-mapku3** [comment]
Hi @cwensley now it's ok, really it was just nuget restore. Next time i created apps and he worked!

**Comment by cwensley** [comment]
Thanks @kot-mapku3, great to know you got it working.  Cheers!
