### ISSUE TITLE
WPF - Dispatcher.Invoke

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1074]
in WPF we have Control.Dispatcher.Invoke(action) to modify a control from another thread.
In my use-case, the control is in a dynamic splash-screen, which was not created from the main-thread.
So Application.Instance.Invoke() is not working.

I didn't find this in Eto. Is there something to Invoke an Action on the thread of a control which was not created on the main thread?
Reason is, it should also work on Mac.

**Comment by cwensley** [comment]
`Application.Instance.Invoke()` should work.  Have you created the `Application` class at that point?

**Comment by TomQv** [comment]
Yes, but still System.InvalidOperationException: calling thread can't access object, because it belongs to another thread.

The control I want to modify was not created in the main-thread. So I must Invoke in this worker-thread.

**Comment by cwensley** [comment]
What's the full stack trace?  I'll probably need a repro for this as it's known to work.

**Comment by cwensley** [comment]
Ah.. this:

> The control I want to modify was not created in the main-thread

You cannot create controls on the worker thread, they *must* be created on the UI thread.

The only exception is Eto.Drawing.* which should be available on any thread assuming you're not modifying a Bitmap that the UI is using.

**Comment by TomQv** [comment]
Ok, I know, where I'm trapped in.

As I said, its about a dynamic splash screen. So while main-form is build up and filled, I show a splash screen with a label with some progress. All on the main thread.
For this I called Application.Instance.Invoke(() => _label.Text = status);
Although, it was actually not necessary, it worked. Status was nicely updated.
But since one or two Eto-updates ago, _label was not refreshed any more and I figured out, that you replaced Invoke() by In InvokeIfNecessary(). And InvokeIfNecessary is doing nothing, if both threads are the same. Conclusion:  Invoke()  - even if on the same thread - is doing something, at least my Label was refreshed. So I'm not sure, if replacing Invoke() by InvokeIfNecessary() is good in all cases.

Unfortunate on the mac-side, its not working, my splach-label is never refreshed.
So whats your idea for refreshing a dynamic splash-screen if all is on the ui-thread? In the past we were just using DoEvents()....

**Comment by cwensley** [comment]
This isn't supported on macOS or Gtk afaik, so you'll have to change your code to create all UI on the UI thread.

**Comment by TomQv** [comment]
So no dynamic splash screens? 
Ok, its working on Windows, just not on Mac.
But actually, although I'm not a mac-user, just doing this because my clients are demanding a mac-version, are there apps with splash-screens on mac anyway?
Visual Studio Mac doesn't have one, VS Windows does, maybe for a reason, maybe I should just leave it.

Its ok, issue solved, thanks :)
