### ISSUE TITLE
[Mac] Unable to force the Height for a Button

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1081]
## Expected Behavior
A button should have the height set by its property Height or stretched to fit the height of the control that is containing it. 

## Actual Behavior
No matter if I force a Height or if I set things so that the Button should be stretched to the height of its container control, the height of the Button is always the same.

## Steps to Reproduce the Problem

Just run the following demo code and you'll get this:

![image](https://user-images.githubusercontent.com/21080030/38711129-2dbd01ea-3ec4-11e8-88c1-9c14a50448ab.png)

also explicitly setting a Height does not change.
I think this is a regression because in my application I used to force a Height and let Eto stretch the buttons horizontally, but after pulling the latest Eto code now all my buttons have a fixed standard minimal height. 
For Eto.Wpf the behaviour is still the old one.

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyMainForm());
		}

		public class MyMainForm : Form
		{
			public MyMainForm()
			{
				Size = new Size(500, 400);
				Button btn = new Button { /*Height = 54,*/ Text = "Click me!", BackgroundColor = Colors.Yellow };
				Content = new StackLayout
				{
					BackgroundColor = Colors.Pink,
					Padding = 30,
					HorizontalContentAlignment = HorizontalAlignment.Stretch,
					VerticalContentAlignment = VerticalAlignment.Stretch,
					Items = 
					{
						new StackLayoutItem(btn, VerticalAlignment.Stretch, true)
					}
				};
			}
		}
	}
}
```

## Specifications

  - Version: 
  - Platform: Mac, pulled the code 13th April 2018.

**Comment by msasso69** [comment]
if you also look at the "test\Eto.Test\Sections\Controls\ButtonSection.cs", the code:
```
var control2 = new Button { Text = "Button With Text", Size = new Size(-1, 50) };
```
produces this (on Mac):
![image](https://user-images.githubusercontent.com/21080030/38727365-185da8ce-3f0d-11e8-9fdb-69447be40505.png)

instead of this (on Windows):
![image](https://user-images.githubusercontent.com/21080030/38727222-acf64000-3f0c-11e8-930b-9f6b0af0341d.png)

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I'm on it.
