### ISSUE TITLE
Eto.forms viusal studio extension is broken?

### ISSUE THREAD

**Issue by Donaut** [picoe/Eto#1086]
I install the latest version that's is 2.4.1.1. And I create a project where is each platform is separated but I don't have WinForms and Gtk3 project.
![eto forms](https://user-images.githubusercontent.com/30203762/38785672-9f6bf8d6-4122-11e8-81ae-27ab3ecb48e0.jpg)

**Comment by SlowLogicBoy** [comment]
Each platform means: Windows, Mac and Linux
Wpf - Windows
Mac - Mac
Gtk - Linux
