### ISSUE TITLE
New Project Template - Error: This template atempted to load component assembly / Nuget issue?

### ISSUE THREAD

**Issue by edwardchanjw** [picoe/Eto#1091]
Sorry if i am too new to C# development, what need to be configured for Nuget to able to create new project?

## Expected Behavior
Successful Create New Project after download [EtoFormsVisualStudioAddin](https://marketplace.visualstudio.com/items?itemName=CurtisWensley.EtoFormsVisualStudioAddin)

## Actual Behavior
![capture](https://user-images.githubusercontent.com/2706887/38975448-733429da-43e0-11e8-99a4-61bc8a1f4eb9.PNG)

## Steps to Reproduce the Problem

  1. New ->Project -> Visual C# -> Eto.Forms
  2. Error 
  

## Specifications

  - Version: 2.4.1.1
  - Platform(s): Visual Studio 2017 Community Version
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hi, thanks for submitting the issue!  What version of VS 2017 do you have?

**Comment by edwardchanjw** [comment]
It is Version 15.1 (26403.7) Release.
Details: [VS Studio About Info](https://gist.github.com/edwardchanjw/618f320527f16b12f67d80f837598db7)

**Comment by cwensley** [comment]
Hey @edwardchanjw, thanks for the info.  It's known that the addin has issues on anything less than 15.5.  Could you try updating VS to see if that resolves it for you?

**Comment by edwardchanjw** [comment]
Thanks for you quick support. Will let you know in few days. I am using the manual step to setup the project now, to evaluate Eto for cross platform feasibility, as a alternative to Electron (Actually if Electron without fancy bloated HTML5 app loaded, the memory usage should be around 70-80MB or under 100). Would love to see a list of awesome list of desktop app build on C# rather than [Electron's Apps](https://github.com/sindresorhus/awesome-electron#apps)

My next concern is to how new user friendly is for the cross platform UI Library, #1076 it would be good to document build step that not really work similar on different platform. really don't mind to setup VS and build environment freshly. Hopefully .NET Standard 2.1 above keep improve it, the goal is to have simple 5 minutes working step for generate project, able to build like other UI framework: React Native, Electron and etc.

**Comment by cwensley** [comment]
Hey @edwardchanjw, thanks for the feedback.

I agree, Electron or other HTML based apps are usually quite bloated and often in my experience does not have the same response as you'd get from a fully native app.

Check the [Quick Start Guide](https://github.com/picoe/Eto/wiki/Quick-Start), which addresses your concern about #1076 issue and also this one.  There's a link to the Quick Start from the README.

Hope this helps!
Curtis.

**Comment by cwensley** [comment]
Closing as this is a known issue with earlier versions of VS.
