### ISSUE TITLE
[Mac] Satellite assemblies not correctly deployed to the app folder

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1092]
I noticed that satellite assemblies for localised applications are not deployed to Contents\MonoBundle\<locale> but only in Contents\MonoBundle

This raises the exception "FileNotFoundException" when I try to load the resource.
Notice that the exception is only caught after creating a "New Exception CatchPoint" in order to break at every exception.

When using the english locale two exceptions are caught before the program defaults to the file present in Contents\MonoBundle:
FileNotFoundException for file ...app/Contents/MonoBundle/en-US/Resources.resources.dll
and
FileNotFoundException for file ...app/Contents/MonoBundle/en/Resources.resources.dll

When using other locales the resource is not found at all and the text is not translated (at least not in the provided demo program, in my application it again defaults to the localised resource in Contents\MonoBundle after raising the first exception)

I think that if satellite assemblies would be in the correct place we could avoid a lot of exceptions and speed up the application as well (in fact placing the satellites manually in the localised folders does not through the exceptions anymore).

## Expected Behavior
Satellite assemblies should be present under Contents\MonoBundle\<locale>\

## Actual Behavior
resources are looked first in the localized folders under Contents\MonoBundle, an exception of FileNotFoundException is raised and then looked for in Contents\MonoBundle. This happens every time I access the ResourceManager. 

## Steps to Reproduce the Problem

  1. download the small demo program at http://s000.tinyupload.com/?file_id=62808921811698399041
  2. create a "New Exception CatchPoint"
  3. launch the program
  4. click on the button to swap the locale

## Specifications

  - Version: 2.5.0-alpha
  - Platform(s): Mac
  - Operating System(s): tested on macOS 10.13

**Comment by cwensley** [comment]
Thanks for reporting the issue!  We'll have to update the .targets so it copies those over when building the .app bundle.  Not sure what ItemGroup those are in, perhaps `ResourceCopyLocalItems` or `ReferenceCopyLocalPaths`..

**Comment by cwensley** [comment]
Thanks for reporting the issue!  This should now be fixed.  I tested with a new project that included multiple .resx files for different locales and worked like a charm.

**Comment by msasso69** [comment]
thanks to you
