### ISSUE TITLE
Examples for to use it with PowerShell Core

### ISSUE THREAD

**Issue by Juanito99** [picoe/Eto#1094]
Hi there,

could you provide a few simple examples that show how to use it with PowerShell Core?
That would open also cross platform GUIs for sysadmins like me :grinning: 

Thanks in advance

Ruben

**Comment by cra0zy** [comment]
This... doesn't make sense... you just use `dotnet new` like with every other cmd/bash.

**Comment by SlowLogicBoy** [comment]
@cra0zy you can call .net methods using PowerShell.

**Comment by cra0zy** [comment]
Oh, didn't realize that... hmm... need to test this on Linux.

**Comment by Juanito99** [comment]
@SlowLogicBoy Thanks for this comment. That is exactly what I meant.

@cra0zy Just for your reference, [here](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/creating-a-custom-input-box?view=powershell-6) is an example for traditional windows.forms library and windows powershell. 

I am just looking for something to get started. A small form with an input field a few basic controls and a text-field. - That should be sufficient for most cases.  Thank you :bowing_man:

**Comment by ALIENQuake** [comment]
@Juanito99 Sorry for bringing bad news: using ANY GUI framework with Powershell won't work for MacOS bacause of the "GUI must be on main thread" limitation. Please see this issue: https://github.com/ironmansoftware/psavalonia/issues/1 So cross-platform GUI is not possible to achieve when you start with Powershell, but you can create c# app, add Powershell Core as NuGet package and call ps1 scripts from the c#.

**Comment by Juanito99** [comment]
@ALIENQuake 
1. Nice name ;-)
2. It's a pity, but many thanks for you feedback :bowing_man:  :smile:

**Comment by Hexality** [comment]
Not the case anymore specially on linux since psavalonia works, how is it going?

**Comment by Hexality** [comment]
![image](https://github.com/user-attachments/assets/317fb3c0-5c17-4a02-8b0a-6ec3d116b44b)
Welp, I guess I got it.
