### ISSUE TITLE
Editable spreadsheet using... GridView?

### ISSUE THREAD

**Issue by JonSargent** [picoe/Eto#1097]
Hi all,

Trying to build up a basic user-editable spreadsheet. I assume GridView is right control for this? 

I tried creating a row class with an array of values for binding purposes, but didn't work as expected. All cells seems to bind to the last index in the loop + 1.

```c#            
for (int i = 0; i < numRows; i++)
{
	Columns.Add(new GridColumn
	{
	    HeaderText = "Column " + i,
	    Editable = true,
	    DataCell = new TextBoxCell { Binding = Binding.Property<MyRowClass, string>(r => r.Value[i]) },
	});
}
```

(Value is just a string array property of MyRowClass.) I'm probably butchering this... Suggestions?

Thanks,

Jon

PS. Using Eto.Wpf 2.4

**Comment by SlowLogicBoy** [comment]
That's because you pass `i` variable (not the value) to binding, which you change in a for loop.
