### ISSUE TITLE
Unable to localize the Eto-generated text in the "About" dialog

### ISSUE THREAD

**Issue by SteveGilham** [picoe/Eto#1105]
## Expected Behavior

At worst, that the control hierarchy of the dialog would be sufficiently navigable that the text like the tab labels or the credits sub-headings could be supplied from resource files before the dialog is shown.

## Actual Behavior

Strings are [hard-coded in English](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/ThemedControls/ThemedAboutHandler.cs#L206) within `src\Eto\Forms\ThemedControls\ThemedAboutHandler.cs` method `ShowDialog(Window parent)`, which creates and shows the dialog in one atomic operation.

**Comment by SteveGilham** [comment]
Work-around

1. Create a full copy of the ThemedAboutHandler type and add the desired behaviour (the existing type isn't set up for tweaking by sub-classing, alas)
2. Use reflection to find the set_Handler method in the AboutDialog instance
3. Dispose the old, use the new

**Comment by cra0zy** [comment]
Do note that Gtk has native implementation for this: https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/AboutDialogHandler.cs

**Comment by SteveGilham** [comment]
Gtk provides a large range of .po files for its own strings which should do the job automagically.  Non-Gtk platforms are not so lucky as things stand.

Yes, the work-round can be more sophisticated and do type-detection (if handler is themed then swap)

**Comment by SteveGilham** [comment]
FWIW, I did consider doing a bulk scripted reformatting of the 100+ Gtk .po files to .resx, but license incompatibility makes that a non-starter.
