### ISSUE TITLE
Building Eto in VS2017 Community

### ISSUE THREAD

**Issue by abulka** [picoe/Eto#1114]
Is there a trick to getting the Eto project compiled under VS Community in Windows 10?  I completely cloned master from github so that I could run the tutorial samples in there. 

I noticed that all references to the GTK project give errors. 

## Expected Behavior

Clean compilations, the ability to run the tutorial projects.

## Actual Behavior

Hundreds of errors relating to GTK and missing references. atk-sharp, gdk-sharp etc.

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	2	Active
    Error	CS0246	The type or namespace name 'Entry' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	13	Active
    Error	CS0246	The type or namespace name 'Button' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	14	Active
    Error	CS0246	The type or namespace name 'Requisition' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	34	Active
    Error	CS0246	The type or namespace name 'GLib' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	40	Active
    Error	CS0115	'BaseComboBox.OnExposeEvent(Gdk.EventExpose)': no suitable method found to override	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	41	Active
    Error	CS0246	The type or namespace name 'Gdk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	41	Active
    Error	CS0246	The type or namespace name 'Entry' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	106	Active
    Error	CS0246	The type or namespace name 'Button' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	108	Active
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	110	Active
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\BaseComboBox.cs	133	Active
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\DateComboBoxDialog.cs	6	Active
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\DateComboBoxDialog.cs	9	Active
    Error	CS0246	The type or namespace name 'Gtk' could not be found (are you missing a using directive or an assembly reference?)	Eto.Gtk2	C:\Users\Andy\Desktop\Eto\src\Eto.Gtk\CustomControls\DateComboBoxDialog.cs	11	Active
    etc 
    etc

By 

- removing the Eto.Gtk2 reference from a specific project, and 
- disabling builds on all other projects, 

the specific project runs ok.GT

## Steps to Reproduce the Problem

  0. install VS 2017, install the Eto forms plugin as instructed in https://github.com/picoe/Eto/wiki/Quick-Start
  1.  clone Eto repository from github
  2. open solution in visual studio community 2017
  3. run tutorial 1 project for C#
  4. See all the GTK errors....

There's probably something really simple I'm doing wrong... I looked for GTK in the visual studio marketplace, and via the Visual Studio installer, but found nothing.

**Comment by cra0zy** [comment]
You have to install gtk-sharp 2 if you want to compile Eto.Gtk2 project: https://github.com/mono/gtk-sharp/releases

**Comment by cwensley** [comment]
Please check the [contributing](https://github.com/picoe/Eto/wiki/Contributing) wiki page, it mentions the gtk-sharp2 package for windows.  Although it is out of date in some of the other information, that part is still relevant. (;
