### ISSUE TITLE
How to use drawable? (handle should not be NULL exception)

### ISSUE THREAD

**Issue by TN-1** [picoe/Eto#1119]
Hi all,

Apologies for the basic question, but it seems like im just taking stabs in the dark trying random methods without any success, so i figured id just skip a lot more wasted time and just ask.  
Obligatory "Ive done the searching without any success"    
I am attempting to use a Drawable in order to (for now) just get the control red, however I am getting the following exception:    
  
> [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: handle should not be NULL    
  
Full text of the exception is:  
  
> {System.ArgumentException: handle should not be NULL
> Parameter name: handle
  at Cairo.Context..ctor (System.IntPtr handle, System.Boolean owner) [0x00022] in <9450a43440924225af45351b36ae6fc4>:0 
  at Gdk.CairoHelper.Create (Gdk.Window window) [0x0001d] i…}   
  
The relevant code is:  
    
```
 _drawable.Size = new Size(128, 64);

using (Graphics g = _drawable.CreateGraphics())
{
    g.Clear(new Color(255,0,0));
}

```

[Full file](https://gist.github.com/TN-1/bb1aae09f3758ea97f7e34b0aebe8713)  
  
I am working on Ubuntu 18.04, using Eto and Eto.Gtk3 from nuget and latest Mono from the mono project repos.  
  
Thanks in advance

**Comment by TN-1** [comment]
Was able to figure it out. For anyone in the future, I was able to solve like so:  
  
```
            _drawable.Paint += (sender, e) =>
            {
                e.Graphics.Clear(new Color(255,0,0)); 
                e.Graphics.DrawRectangle(new Color(0,255,0), 10, 10, 20 ,20 );
            };
```

**Comment by cwensley** [comment]
Hey @TN-1,

Glad you figured it out.  `Drawable.CreateGraphics()` is actually not very useful any more, it should be deprecated. It was a way to draw directly to the screen buffer, at least on Windows Forms.  MacOS no longer supports it, and I'm not sure it works with Gtk anymore either.  

Regardless, you would have had to handle the `Paint` event anyway in case the control needed redrawing such as when it is resized or scrolled.

**Comment by TN-1** [comment]
Thanks for the info @cwensley   
Im not sure if this is a known issue, but the docs seem to be quite out of date. They don't include the `Drawable.Invalidate()` among other things.   
Just wanted to mention that so you can add another thing to im sure what is a long todo list :)

**Comment by cwensley** [comment]
@TN-1, I don't think documentation isn't out of date; the docs for each class just don't include inherited methods, such as `Control.Invalidate()`.  

I might change the settings next time they are generated so it does include inherited methods to avoid that confusion.

Thanks for the feedback!

**Comment by TN-1** [comment]
Understood, I will keep that in mind. Thanks!
