### ISSUE TITLE
Nightly build versioning

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#1121]
Hi Curtis,

Could you update the version numbering of the nightly builds? I'd like to try your recent fixes but am currently unable to do it since the latest NuGet version is v2.4.1 and the nightly ones are being generated as v2.4.0-x, hence the package manager cannot recognize them as being newer (pre-release).

Thanks!

**Comment by cwensley** [comment]
Thanks for reporting the issue!  That does indeed make it difficult to use the nightly nuget packages.  Should now be fixed!

**Comment by DanWBR** [comment]
Thanks for the fix. Aren't you building the libraries for macOS anymore?

**Comment by cwensley** [comment]
@DanWBR you’re welcome. 

The xammac binaries have never been built by CI as it can only be built on a Mac and CI is currently on windows using appveyor. 

I’ve been investigating building it on windows but have not yet been fully successful.
