### ISSUE TITLE
[MAC] Tray application with hidden main window still visible in dock

### ISSUE THREAD

**Issue by MartinRothschink** [picoe/Eto#1128]
I'm trying to create a tray application with an invisible main window. The only visible element should be the tray icon with a context menu. The code below works on WPF, on GTK and MAC the main window is still visible. I have overriden OnShown as workaround and used Vissible = false there again. Now GTK is fine but MAC still shows an empty application menu and an icon in the dock. How can I get this working?

Thanks
Martin

## Expected Behavior

No main window, only tray icon visible

## Actual Behavior

WPF: ok
GTK: Main window visible
MAC: Main window visible, application menu visible, dock icon visible

## Code that Demonstrates the Problem

```
using Eto.Forms;
using Eto.Drawing;

namespace EtoTrayApp
{
    partial class MainForm : Form
    {
      void InitializeComponent()
      {
         Title = "My Eto Form";
            
         var quitCommand = new Command { MenuText = "Quit", Shortcut = Application.Instance.CommonModifier | Keys.Q };
         quitCommand.Executed += (sender, e) => Application.Instance.Quit();
         var icon = Eto.Drawing.Icon.FromResource("EtoTrayApp.error.ico");

         var tray = new TrayIndicator() { Image = icon};
         tray.Menu = new ContextMenu
         {
            Items =
            {
               new ButtonMenuItem { Text = "Quit", Command = quitCommand}
            }
         };

         ShowInTaskbar = false;
         Visible = false;

         tray.Visible = true;
      }
    }
}

```

## Specifications

  - Version: 2.4.1
  - Platform(s): WPF, Gtk3, Mac
  - Operating System(s): Windows 10, Ubuntu 18.04, macOS 10.13.5, Mono 5.12
  
The sample project is available here:
https://1drv.ms/u/s!Ajb182QihKkLs8g67P4XvgehKm9GNg

**Comment by MartinRothschink** [comment]
Found the solution. You have to add these two line to the info.plist file:

```
<key>LSUIElement</key>
<true/>

```

The plist editor in VS for Mac shows this as "Application is agent (UI Element)".

**Comment by cwensley** [comment]
Hey @MartinRothschink,

Glad you found the answer to your question.  Is this issue now closed?  I don't think there's anything in Eto that can be done to make this easier as it does require you to edit the plist.

Thanks for reporting the issue and your findings!  It's a big help to the community.

**Comment by MartinRothschink** [comment]
Yes, this issue can be closed.
Maybe you can add the above information to the online documentation of ShowInTaskbar?

**Comment by cwensley** [comment]
Hm, not sure `ShowInTaskbar` is the right place for that documentation, because what if you don't even create a main window?  It probably is best in the docs for TrayIndicator.

**Comment by cwensley** [comment]
after reading about LSUIElement does, you are probably correct about it being relative to ShowInTaskbar.  Added note, thanks!
