### ISSUE TITLE
Command.Shortcut Wpf-Mac

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1144]
`
LayoutNextCommand = new Command
{
    MenuText =  "Toggle view",
   Shortcut = Keys.F3,
};
`
When added into the MenuBar of the mainform, with WPF its fine, Text and shortcut are displayed and shortcut F3 is working.

Same with macOS, F3 is ignored, instead the C-key is displayed in the menuitem and the command is also only executed when pressing C.

**Comment by cwensley** [comment]
@TomQv Are you adding this to the top level (e.g. MenuBar.Items), or a submenu?

Menu items at the top level must be submenus on macOS from what I recall.

**Comment by cwensley** [comment]
@TomQv, thanks for the follow up.  Sounds like it could just be a key mapping issue.

**Comment by TomQv** [comment]
Its only the F-keys, but also in combination with alt/shift/control

Normal keys a-z etc. are fine.

**Comment by cwensley** [comment]
Looks like it was an issue on Xamarin.Mac - the NSKey values are different than with MonoMac.  Thanks again for reporting the issue!
