### ISSUE TITLE
Scrollable overflows instead of scrolling

### ISSUE THREAD

**Issue by kovikti** [picoe/Eto#1148]
Hi,
I'm trying to make a two-panel UI where the width of the left side is fixed, the right side can grow, even larger than the desktop (imagine an image here).
However when I place the scrollable it overflows to its contents, scrollbars do not show up. ExpandContentWidth/Height does not seem to have any effect.
If I explicitly set the size of the scrollable, it works, however I want it to fill up the remaining space in the UI.
What am I missing here?
I'm on Windows, but I'd like to run it on mac as well.

```
Title = "My Eto Form";
ClientSize = new Size(400, 350);
Padding = 10;
var drawPanel = new Drawable() { Width = 1500, Height = 1500, BackgroundColor = Colors.Black };
var scrollPanel = new Scrollable() { Content = drawPanel, ExpandContentHeight = false, ExpandContentWidth = false };
var splitter = new Splitter() { Panel1=new Panel() { Width=150 }, Panel2=scrollPanel };
Content = new StackLayout
	{
		Items =
			{
				splitter
			}
	};
```

**Comment by cwensley** [comment]
Hey @kovikti,

Try removing the top level `StackLayout`.  It by default will make its contents auto size, which it sounds like you want the splitter to encompass the entire form.  E.g.

```c#
var drawPanel = new Drawable() { Width = 1500, Height = 1500, BackgroundColor = Colors.Black };
var scrollPanel = new Scrollable() { Content = drawPanel, ExpandContentHeight = false, ExpandContentWidth = false };
var splitter = new Splitter() { Panel1=new Panel() { Width=150 }, Panel2=scrollPanel };
Content = splitter;
```

**Comment by kovikti** [comment]
Awesome it works, thanks!
