### ISSUE TITLE
DragDrop files/links into controls

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1149]
When dragging a file from Explorer/Finder into a control, the filenames should be in DragEventArgs.Data.Uris.
- WPF: ok
- OSX; not ok, only something like file:///.file/id=1334234 is provided, don't know how to get the actual filename

When dragging a web-link into a control (from a browser), the address should be in DragEventArgs.Data.Uris:
- WPF:  not ok, DragEventArgs.Data.Uris is empty, but the http-address is in DragEventArgs.Data.Text
- OSX:  ok

Btw, for web-links  being dragged there is a way to get the title of the web-page as well:

```
// hack to extract the title of a webpage from DataObject
// http://windowsclient.net/blogs/faqs/archive/2006/05/26/how-do-i-support-drag-and-drop-of-a-hyperlink-from-ie-into-a-control.aspx
static string GetTitle(DataObject data)
{
    var b = data.GetData("FileGroupDescriptor");
    if (b!=null)
    {
        string title = "";
        for (int i = 76; i < b.Length ; i++)
        {
            if (b[i] == 0)
                break;
            else
                title += (char)b[i];
        }
        if (title.EndsWith(".url", StringComparison.CurrentCultureIgnoreCase))
            title = title.Substring(0, title.Length - 4);
        return title;
    }
    return null;
}
```

For this hack to work Eto.Wpf.Forms.DataObjectHandler.GetData(string type) needs the following addition:

```
if (data is System.IO.MemoryStream)
{
	using (var ms = (System.IO.MemoryStream)data)
		return ms.ToArray();
}
```

Would be cool also to get the title with OSX.

**Comment by cwensley** [comment]
Thanks for reporting the issue!

**Comment by birbilis** [comment]
Which browser are you trying to drag a link from? e.g. Edge doesn't allow dragging icon from address bar onto desktop etc. as one would do in IE, but have to first show the favorites bar, then drag from favorites pane there, then from the favorites bar drag to desktop (!!!)

**Comment by flashback19** [comment]
@TomQv 
you can do something like this:

var nsUrl = new NSUrl("file:///.file/id=1334234", false);
return nsUrl.FilePathUrl.Path;

**Comment by TomQv** [comment]
Thanks, but this doesn't work for me.
Result is something like "app/Contents/Resources/file:/.file/id=1334234"
but not the path to the original file.

**Comment by flashback19** [comment]
@TomQv 
try without 'file://' ->  "/.file/id=6571367.8608113621"

**Comment by TomQv** [comment]
yepp!
Thank you :)

**Comment by cwensley** [comment]
Thanks again for reporting the issue @TomQv, and to those who helped troubleshoot.  Apparently, macOS is giving us a file _reference_ URI, which isn't usable with most .NET API's.  I've fixed it by getting the actual path of the file, after noticing a [missing api](https://github.com/xamarin/xamarin-macios/pull/5562) that is required to test for that.

Give it a try and let me know if you run into any further problems!
