### ISSUE TITLE
_UpdatePList error compiling with Mac64

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1150]
After today pull (10th July 2018) I get this error compiling with Mac64:

```
/Users/utonto/VSeo/Eto/build/MacTemplate/MacTemplate.targets(3,3): Error MSB4036: The "_UpdatePList" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "/Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin" directory. (MSB4036) (EtoFormGui.Mac64.mono.msbuild)
```

I see that MacTemplate had been modified recently, should I change something in my projects to comply with the changes?

## Specifications

  - Version: pulled 10th July 2018
  - Platform(s): Mac64
  - Operating System(s): macOS 10.13

**Comment by msasso69** [comment]
Found the catch: needed to add RoslynCodeTaskFactory as a NuGet package (I didn't notice at first but there was also a warning in the output window saying that)

**Comment by cwensley** [comment]
Hey @msasso69, glad you figured it out!

We should probably fix that error so that if the package isn't included it just shows the warning.  

However, including MacTemplate.targets manually as you have done (I assume) isn't really supported. It's recommended to use the nuget packages directly, which would have included the RoslynCodeTaskFactory dependency.

**Comment by msasso69** [comment]
Yes you are correct, and I do not consider it a bug, that's why I closed it, I'm including the MacTemplate in my projects because I want to debug the Eto code too and try to fix any issue on my own before bothering you ;)
