### ISSUE TITLE
System.ArgumentNullException in XamlReader.Load(this)

### ISSUE THREAD

**Issue by RotsiserMho** [picoe/Eto#1155]
## Expected Behavior

I have a very simple Xeto-based Eto app I'm developing with Visual Studio on macOS. I started with the Eto new application wizard and chose to generate separate projects for each platform. The first thing I did was move the MainForm.xeto and MainForm.xeto.cs files to a folder called "Views". The app then throws an exception in MainForm.xeto.cs at the `XamlReader.Load(this)` statement. The pop-up states the the `input` parameter is null.

## Actual Behavior

I expected the XamlReader to load the associated Xeto file without issue.

## Steps to Reproduce the Problem

  1. Create a new Xeto Eto app with the wizard.
  2. Move the MainForm files to a subfolder
  3. Build and run

## Specifications

  - Version: 2.4.1 via NuGet
  - Platform(s): macOS 10.13.5 using Visual Studio for Mac 7.5.3, targeting XamMac2
  

It would be helpful if I could debug into the Eto code. Are there instructions for building a NuGet package with debug symbols? Or even just the required assemblies?

**Comment by LikoIlya** [comment]
Hi there, @RotsiserMho, I'm testing right now on 2.4.1 on macOS 10.13.5 and also moved MainForm to Views folder and successfully started application. Check your namespaces in target Program.cs or smth else

**Comment by cwensley** [comment]
Hey @RotsiserMho, you're missing a step.

2a. Change the namespace of MainForm to match the subfolder

`XamlReader.Load(this)` will try to find the matching xaml embedded resource of the class you pass in. 

For example, if your `MainForm`'s full type name including namespace is `MyProject.SomeFolder.MainForm`, then it tries to load the xaml file of `MyProject\SomeFolder\MainForm.xaml`. If you haven't changed the namespace of MainForm, then it will look for `MyProject\MainForm\xaml`, which is incorrect.

Hope this helps!

**Comment by RotsiserMho** [comment]
Thanks! The problem was due to me not changing the namespace.
