### ISSUE TITLE
[WinForms] TrayMenu won't hide on focus lost

### ISSUE THREAD

**Issue by MeikelLP** [picoe/Eto#1161]
## Expected Behavior
The tray menu hides just like on a native WinForms app.

## Actual Behavior
The tray menu does not hide.

## Steps to Reproduce the Problem

using the [sample app](https://github.com/picoe/Eto/issues/1132#issuecomment-397241140) from @MartinRothschink 

  1. Build the app and run it
  2. Right click on the tray icon
  3. Click anywhere else on your screen

## Specifications

  - Version: 2.1.4
  - Platform: WinForms
  - Operating System: Windows 10

**Comment by cwensley** [comment]
Cool, thanks for verifying that it is fixed in the latest version.
