### ISSUE TITLE
Relative Image source for ImageView

### ISSUE THREAD

**Issue by ALIENQuake** [picoe/Eto#1171]
Hi,

How to set Relative Image source for ImageView? I'm trying to simply use xeto:

```
<Panel >
	<StackLayout HorizontalContentAlignment="Center">
      <ImageView Image="../Resources/image.bmp">
      </ImageView>
	</StackLayout>
</Panel>

```
But it doesn't work. Full path to the file works but I want relative path from bundled resource.

  - EtoApp XAML Single for all platforms
  - Version:
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hi, thanks for reporting the issue.  Relative paths for image resources are not currently supported, but it is a good suggestion.  Thanks!

**Comment by ALIENQuake** [comment]
@cwensley Thanks, just give me example of how to add simple bmp image as background. I try read docs, other app source but didn't find anything.

**Comment by SwiTool** [comment]
@ALIENQuake are you still waiting ? 😂

**Comment by ALIENQuake** [comment]
@SwiTool Not really ...
