### ISSUE TITLE
Proportional width operator in xeto?

### ISSUE THREAD

**Issue by tymokvo** [picoe/Eto#1175]
I'm trying to populate a `TableLayout` with 3 columns that scale to .33 * `Form.Width`. I thought I would be able to use the standard XAML proportional operator in the `Width` field as in: `<TableLayout Width="33*">` but Designer complains that the string is not in the correct format.

## Expected Behavior

`Width="33*"` should scale the container to .33 * the `Width` of the parent.

## Actual Behavior

Error: `Input string was not in a correct format`

## Steps to Reproduce the Problem

See code.

## Code that Demonstrates the Problem

```
  <TableLayout>
    <TableRow>
      <TableLayout Width="33*">
        <Label Text="Source Directory" TextAlignment="Center"></Label>
        <Button Text="Open Source Directory" Click="HandleOpenSourceDirectory" Height="32"></Button>
        <Scrollable></Scrollable>
      </TableLayout>
    </TableRow>
  </TableLayout>
```

## Specifications

  - Version: 2.4.1
  - Platform(s): Winforms 
  - Operating System(s): Win 10 
  
I know that there might be a different syntax for this, but I can't seem to find it documented anywhere.

Thanks for any help!

**Comment by cwensley** [comment]
Hi @tymokvo, there isn't currently an equivalent to give a weight, but the `TableLayout` does allow you specify that each cell is "scaled", in that it should take up an equal amount of space with other scaled columns.

For example, this would work:

```xml
<TableLayout>
    <TableRow>
        <TableCell ScaleWidth="True">
            <Label Text="Column 1"/>
        </TableCell>
        <TableCell ScaleWidth="True">
            <Label Text="Column 2"/>
        </TableCell>
        <TableCell ScaleWidth="True">
          <TableLayout>
            <Label Text="Column 3"/>
            <Label Text="Source Directory" TextAlignment="Center" />
            <Button Text="Open Source Directory" Click="HandleOpenSourceDirectory" Height="32" />
            <Scrollable />
          </TableLayout>
        </TableCell>
    </TableRow>
  </TableLayout>
```

See the [wiki page on containers](https://github.com/picoe/Eto/wiki/Containers) for more information on how the layout system works in Eto.

Hope this helps!

**Comment by tymokvo** [comment]
Hi! Yep that is a good replacement. Thanks for the help!
