### ISSUE TITLE
Data Validation and GridView Masked TextBoxCell

### ISSUE THREAD

**Issue by RotsiserMho** [picoe/Eto#1177]
This is more of a question/feature request than an issue.

I have a data-bound, xeto-defined GridView in my application with editable columns that represent currency. Ideally there would be a MaskedTextBoxCell I could use that would prevent the user from entering non-numeric characters, or more than two decimal places. Could someone point me in the right direction so I can create such a cell on my own? In general, how should one implement this kind of data validation with Eto? Is there any documentation available? I'm assuming I'd have to do the validation in the bound property setter and somehow signal to the GridView to draw a red box around the cell or something but that seems a little clunky, and for my use case I think a Masked TextBoxCell would work better anyway, but I'd like to better understand how this is done generally. Thanks.

**Comment by cwensley** [comment]
Take a look at using the CustomCell, which you can specify a custom control for editing.  In this case, you can use the MaskedTextBox directly.  For GTK and/or WinForms you also have to supply a 'Paint' method so it can draw the content when not in edit mode (Mac and WPF use the control directly, even when not editing).

**Comment by cwensley** [comment]
Closing as using CustomCell should provide what you need.  Please let me know if that doesn't work for you.
