### ISSUE TITLE
Hello helpers please remove my account from MonoGame Community

### ISSUE THREAD

**Issue by sourceskyboxer** [picoe/Eto#1185]
Hello everyone, please tell administrators @Jjagg, and other persons ( outer @cra0zy )

I want remove my account from MonoGame, if they don't remove than I will notice to police whatever.
Please help me again @cra0zy !

![beweis](https://user-images.githubusercontent.com/3496136/44628039-1bd56500-a939-11e8-9f2e-54d1c366cd38.jpg)

Please promise me! I want they remove my account from MonoGame Community!

If they don't remove = It means extortion again my right. Caution policy of Germany is very strict. Thanks

**Comment by Jjagg** [comment]
This is really not the place to say this Jens, but I will remove your account.

**Comment by sourceskyboxer** [comment]
Thank you @Jjagg for security!
