### ISSUE TITLE
Bind an enum to a ComboBoxCell

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1189]
Hi All, 

I'm trying to bing an enum to a ComboBoxCell but I get an exception when I change the selection of the combo.
In my real application what I show in the combo is a localized description of every enum value, but the problem is also present simply showing the ToString() of the enum values as shown in the code below.
I'm not probably doing the correct binding, but I start to think that there's a problem in the Eto code (or a limitation) because in the SetValue method of the ComboBoxCellHandler 
```
void SetValue(object dataItem, object value)
```
the type of 'value' is always a string rather than my enum.
(same happens in the corresponding method of Eto.Mac\Forms\Cells\ComboBoxCellHandler)

## Expected Behavior
It should be possible to change the selection of a ComboBoxCell bound to an enum

## Actual Behavior
When changing the selection of the ComboBoxCell we get an InvalidCastException

## Steps to Reproduce the Problem

  1. Launch the sample program below
  2. select a combo
  3. select a different item in the combo
  4. we get a System.InvalidCastException because we cannot cast from String to MyEnum

## Code that Demonstrates the Problem

```
using System;
using System.Collections.Generic;
using Eto;
using Eto.Forms;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyMainForm());
		}

		public class MyMainForm : Form
		{
			public MyMainForm()
			{
				GridView grid = new GridView() { Width = 200, Height = 80 };

				ListItemCollection operatorDataStore = new ListItemCollection
				{
					new ListItem { Tag = MyEnum.Enum1, Text = MyEnum.Enum1.ToString() },
					new ListItem { Tag = MyEnum.Enum2, Text = MyEnum.Enum2.ToString() },
					new ListItem { Tag = MyEnum.Enum3, Text = MyEnum.Enum3.ToString() },
					new ListItem { Tag = MyEnum.Enum4, Text = MyEnum.Enum4.ToString() }
				};

				grid.Columns.Add(new GridColumn
				{
					DataCell = new ComboBoxCell("ColEnum")
					{
						DataStore = operatorDataStore,
						//ComboKeyBinding = Binding.Property<MyItem, MyEnum>(m => m.ColEnum).Convert(r => r.ToString(), v => (MyEnum)Enum.Parse(typeof(MyEnum), v))
					},
					Editable = true,
					HeaderText = "Enum",
					Width = 100
				});

				List<MyItem> model = new List<MyItem>();
				model.Add(new MyItem { ColEnum = MyEnum.Enum1 });
				model.Add(new MyItem { ColEnum = MyEnum.Enum2 });
				grid.DataStore = model;

				Content = new StackLayout
				{
					HorizontalContentAlignment = HorizontalAlignment.Stretch,
					Items =
					{
						grid,
					}
				};
			}

			public enum MyEnum
			{
				Enum1,
				Enum2,
				Enum3,
				Enum4
			}

			public class MyItem
			{
				public MyEnum ColEnum { get; set; }
			}
		}
	}
}
```

## Specifications

  - Version: latest in develop
  - Platform(s): tested using WPF and XamMac
  - Operating System(s): Windows 7, macOS 10.13

**Comment by cwensley** [comment]
Hey @msasso69, try this for the column.  The `Binding` property of `ComboBoxCell` is what you have to convert, as the value (Key) for each item in the combo box must be a string value.  By default, the key value is `ListItem.Key` or `ListItem.Text` if the Key is empty.

```c#
			grid.Columns.Add(new GridColumn
			{
				DataCell = new ComboBoxCell("ColEnum")
				{
					DataStore = operatorDataStore,
					Binding = Binding
						.Property((MyItem m) => m.ColEnum)
						.Convert(r => r.ToString(), v => (MyEnum)Enum.Parse(typeof(MyEnum), v))
						.Cast<object>()
				},
				Editable = true,
				HeaderText = "Enum",
				Width = 100
			});
```

Hope this helps!
Curtis.

**Comment by msasso69** [comment]
Oooh yesss!
It definitely helps!
Thank you so much.
I can close the issue :)
