### ISSUE TITLE
How to refresh a UI control immediately?

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1190]
In Winforms I can immediatly invoke the repaint of a control calling the method Refresh.
Is there a way to achieve an immediate refresh also in Eto.Forms? Calling the method Invalide (like the Winforms Invalidate) has not an immediate effect.
Thanks

**Comment by msasso69** [comment]
No, for all controls. The specific case I bumped into is a progress bar that I need to pop up during a long time background processing. Before launching the background thread I make it visible and hide when the background thread is done. Unfortunately most of the time the progress bar pops up only when the background process is almost done making it not really useful.

**Comment by cwensley** [comment]
Hey @msasso69, how long of process are we talking about? If it is over a few seconds and still not showing, then you may have something locking up the UI thread. It shouldn't take that long. 

If it's just a fraction of a second long process, then it makes more sense that it's not showing up before it's done.

**Comment by msasso69** [comment]
Hi Curtis, thanks for your interest. I'm talking of seconds (2-3 seconds usually). Maybe, as you say, there's something keeping busy my UI thread, but I did not figure out what. I'll keep you informed if I manage to narrow down or solve the problem.

**Comment by cwensley** [comment]
Closing as it's been a few years.  If you do get a repro of the issue please let me know.
