### ISSUE TITLE
Set different context menu for each item in a treegridview

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#1193]
## Expected Behavior
TreeGridItem and GridItem can accept a ContextMenu, that shows when right clicking on them specifically. This is a common feature.

## Actual Behavior
Only the TreeGridView can accept a ContextMenu. Trying to change the ContextMenu on the SelectionChanged event doesn't work either, the contextmenu is shown before this event is raised.

## Specifications

  - Version: 2.4.1
  - Platform(s): All
  - Operating System(s): All

**Comment by cwensley** [comment]
Use the `ContextMenu.Opening` event to modify the menu based on your selection.

**Comment by cwensley** [comment]
@claunia were you able to give my suggestion a try?

**Comment by claunia** [comment]
@cwensley no, sorry, been busy with other things, but still it sounds like a workaround :(

**Comment by claunia** [comment]
@cwensley I tried the workaround, and it works. But how can I be sure that past menuitems do not stay zombie in memory waiting for the GC....

**Comment by cwensley** [comment]
> But how can I be sure that past menuitems do not stay zombie in memory waiting for the GC....

I'm not sure how this relates to this issue?  You can remove the menu items and dispose them if you like after the menu is closed using the `ContextMenu.Closed` event, though disposing doesn't really do much and they still have to run through the GC to get cleaned up (everything does).

**Comment by cwensley** [comment]
Closing as it is working for you, thanks for verifying!  Note that I would not consider it a work around, this is how you must modify the context menu to respond to the selection.
