### ISSUE TITLE
ProgressBar and Label not updating in loop

### ISSUE THREAD

**Issue by tymokvo** [picoe/Eto#1199]
## Expected Behavior
ProgressBar Progress to update
Label text to update

## Actual Behavior
Loop executes (files in a list are copied to a new directory) but the ProgressBar and Label do not render their new values

## Steps to Reproduce the Problem

  1. Create ProgressBar/Label in .xeto
  2. Set their values in a loop in the MainForm class
  3. Delegate to `Action` and call through `Application.Instance.Invoke`

## Code that Demonstrates the Problem
The full code is long and arduous, but this should get the point across. I have a button that has an event handler which loops over a list of `IO.FileInfo` objects, calls their `.CopyTo` method and is supposed to be updating the `ProgressBar` and `Label` objects using the `MainForm.UpdateStatus` method. The loop executes (I can see the files being copied in Explorer) but the updated progress bar and label are never rendered until after the whole loop exits. After following #541, I put the updating method into an `Action` object and tried calling it through `.Invoke` and `.AsyncInvoke` to no effect. Help!

```
member this.UpdateStatus () =
        let sb = this.FindChild("StatusBar") :?> ProgressBar
        let st = this.FindChild("StatusText") :?> Label
        st.Text <- String.Format("Copying: {0}", this.currentFile)
        sb.MaxValue <- this.nFiles
        sb.Value <- this.fileN

// In the event handler...
let inFiles = Logic.sourceDir.EnumerateFiles()
let ua = new Action(this.UpdateStatus)


let mutable count = 1
for file in inFiles do
    this.currentFile <- file.Name
    this.fileN <- count
    Application.Instance.AsyncInvoke(ua)
                   
    Logic.copyFile file outDir
    count <- count + 1
```

## Specifications

  - Version: 2.4.1
  - Platform(s): WinForms 
  - Operating System(s): Win10

**Comment by cwensley** [comment]
Hey @tymokvo,

This is because you're doing the loop in the UI thread.  If you want the UI to update you have to perform your work in a separate thread.  One easy way to do this is to use `Task.Run` like so (C#):

```c#
Task.Run(() => {
  foreach (var file in files)
  {
    // do work
    Application.Instance.Invoke(MyUpdateUIMethod);
  }
});
```

**Comment by cwensley** [comment]
Closing as there hasn't been a response for a while.  Feel free to comment/reopen if you still have the issue after doing the work in a background thread.
