### ISSUE TITLE
Modifying the Mac64 Launcher to use pre-bundled apps

### ISSUE THREAD

**Issue by turbo** [picoe/Eto#1208]
Hi,

How exactly does the Mac64 target bundle the application? Outside of the app bundle, the binary doesn't run at all (`mono Eto.Test.Mac64.exe`). However, the bundle itself runs.

I noticed from the app package contents, that the whole output directory is included. I think this can be streamlined by using mkbundle. Running mkbundle on the result binary works:

```
mkbundle --simple -L /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/4.5 --machine-config /Library/Frameworks/Mono.framework/Versions/5.10.0/etc/mono/4.5/machine.config Eto.Test.Mac64.exe --deps
```

But how can I bundle the resulting file, which now no longer depends on mono, to be a valid app package?

I'm avoiding Xamarin.Mac, because I think installing all the dependencies and tooling is completely unnecessary when Mac64 works fine as it is. Since `mono Eto.Test.Mac64.exe` and `./a.our` (the bundle) produce the same error:

```text
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Eto.Mac.Forms.ApplicationHandler.AttachEvent (System.String id) [0x00026] in <cd9f6ae82e544a7a9d5b091ae3cd9e20>:0
  at Eto.WidgetHandler`1[TWidget].HandleEvent (System.String id, System.Boolean defaultEvent) [0x000b7] in <232a5ee7801344b4afb04ff66b5ce3b5>:0
  at Eto.Widget.HandleEvent (System.String id) [0x00007] in <232a5ee7801344b4afb04ff66b5ce3b5>:0
  at Eto.PropertyStore.AddHandlerEvent (System.String key, System.Delegate value) [0x00055] in <232a5ee7801344b4afb04ff66b5ce3b5>:0
  at Eto.Forms.Application.add_NotificationActivated (System.EventHandler`1[TEventArgs] value) [0x00007] in <232a5ee7801344b4afb04ff66b5ce3b5>:0
  at Eto.Test.TestApplication..ctor (Eto.Platform platform) [0x00042] in <d825a5072e704eb385f553b52005bd48>:0
  at Eto.Test.Mac.Startup.Main (System.String[] args) [0x0000d] in <fbc2189f65fd44079ae7a5c1027c6189>:0
```

I guess there is nothing wrong the binary. So how do I get from the binary to a working app package?

**Comment by cwensley** [comment]
Hi @turbo,

Thanks for the inquiry, hopefully I can help:

> How exactly does the Mac64 target bundle the application? Outside of the app bundle, the binary doesn't run at all (mono Eto.Test.Mac64.exe). However, the bundle itself runs.

The .app bundle is created using [MacTemplate.targets](https://github.com/picoe/Eto/blob/develop/build/MacTemplate/MacTemplate.targets) targets file, which is included in the nuget package.

You cannot run a macOS application using `mono MyApp.exe` (this is a restriction on how macOS works).  The only way is to properly create an .app bundle folder structure, along with a valid Info.plist, icon, etc.   What I'd recommend is to take a look at the `MacTemplate.targets` file linked above to see how that could be done.  Your native executable would go into the `MyApp.app/Contents/MacOS` folder and be referenced by the Info.plist's `CFBundleExecutable` value. 

You may be able to use Eto's .app output as a starting point and replace the executable in the `Contents/MacOS` folder.

You may still need all the .dll's, as I'm not sure how mkbundle works with that.  I also doubt it'd know how to get at them in the MonoBundle folder (like Eto's .app bundle), so you may have some issues with that.

Hope this helps!

**Comment by cwensley** [comment]
Just as an update.  I tried using your `mkbundle` command then replaced `Eto.Test.Mac64.app/Contents/MacOS/Eto.Test.Mac64` with the generated `a.out` file, and it appears to work well! 

.. everything except for the json/xaml sections that is, which is probably due to the embedded resources getting lost or renamed.

Cheers!
Curtis.

**Comment by turbo** [comment]
The old way is this:

```bash
export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/usr/bin/codesign_allocate"
codesign --force --sign "Developer ID Application: <my name>" Eto.Test.Mac64.app
```

and to verify:

```bash
codesign -dv --verbose=4 Eto.Test.Mac64.app
```

But I don't have a Mac around atm to test this. Leaving this here as a note for me and maybe others to try.

**Comment by turbo** [comment]
A more portable command using the Current version symlink:

```bash
$ mkbundle --simple -L /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5 --machine-config /Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/machine.config --deps -L /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Facades -o App App.exe
```

I've also confirmed that the app runs without the MonoBundle folder present in the bundle, as there is no launcher looking for it anymore.

Judging from the binary, it acutally doesn't depend on anything Mono anymore, which is great:

```bash
$ otool -L macOS
macOS:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.64.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.63.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

However, in order to be able to sign the main binary, the app has to be statically compiled. Currently, that involves jumping through some major hoops until the mkbundle fix lands in Mono stable.

Even with the fix though, the sign tool complains a few steps later. Oh well, I give up. You can create unsigned apps with this approach, but looks like XamMacModern might be the way to go :/
