### ISSUE TITLE
Is it possible to create a `MenuItem` and `ContextMenu` shims/mocks/stubs for `.Net Core 2.0` without GUI implementation

### ISSUE THREAD

**Issue by silentnightwalk** [picoe/Eto#1209]
Is it possible to create a `MenuItem` and `ContextMenu` shims/mocks/stubs for `.Net Core 2.0` without GUI implementation (using Eto.Forms technology)?

For example, is it possible to 

```
    var x = new MenuItem();  //GTK or something else running on .Net Core 2
```
I tried to do it but problem with Eto.Forms: cannot create instances of abstract cllasses.

And i didn't manage to succeed with Eto.Gtk with creating new MenuItem.

GUI is not important. The main thing is to have ready mocks/shims/stubs for `.net core 2` for items like MenuItem and so on...

Thanks!

**Comment by cwensley** [comment]
@silentnightwalk try using `ButtonMenuItem` (which supports child menus as well).  The `MenuItem` is an abstract base class for `ButtonMenuItem`, `RadioMenuItem`, `CheckMenuItem`, and `SeparatorMenuItem`.

**Comment by silentnightwalk** [comment]
Thanks a lot!

**Comment by cwensley** [comment]
@silentnightwalk you're welcome!
