### ISSUE TITLE
[WinForms] FilePicker can damage form size and presence of other controls

### ISSUE THREAD

**Issue by ItEndsWithTens** [picoe/Eto#1225]
When running on the WinForms platform, if a FilePicker control is added to a dialog, it sometimes negatively affects the visibility (or perhaps size, or very existence?) of several controls on said dialog, itself included.

## Expected Behavior
A FilePicker nested several controls deep in a Dialog shows its text box and browse button as usual.

## Actual Behavior
The FilePicker is invisible, potentially along with some nearby controls, and any positive or negative buttons attached to the dialog.

## Steps to Reproduce the Problem

  1. Clone the test project I've uploaded at https://github.com/ItEndsWithTens/EtoFilePickerTest

  2. Build and run the WinForms project, and click the "Spawn TestDialog" button. The resulting dialog box will be a little too small, but if you resize it larger you can see a collection of controls, arranged neatly, as I ultimately want them to be in the project they're lifted from.

  3. Build and run the WPF project, and again click the spawn button. The dialog again contains all my controls, present and accounted for, neat and tidy.

  4. Modify the NuGet packages for the entire solution, replacing Eto 2.4.1 with the latest development build, currently 2.5.0-build1580.

  5. Rebuild and run the WPF project, spawn a TestDialog again, and see things are still good.

  6. Rebuild and run the WinForms project, click spawn, and note a few things:
    **a**) The dialog appears at its absolute bare minimum size, only large enough for the Windows minimize, maximize, and close buttons.
    **b**) Although you can resize the dialog to see what's in it, the contents of the TabControl's TabPage are mostly blank. The two GroupBoxes on the Resources tab are there, but are as small as can be, with no content.
    **c**) The FilePicker is nowhere to be seen, and to top it all off, the positive and negative buttons are missing.

  7. Edit TestDialog.eto.cs to uncomment the line that assigns an explicit Size to the dialog, then rebuild and run the projects. WPF handles the Size assignment with aplomb, but now WinForms has totally given up, and the dialog is blank.

## Specifications

  - Version: >2.4.1 (actually commit 57beb09 and later)
  - Platform(s): WinForms
  - Operating System(s): Windows 10 x64, 1803
##

Git bisect tells me this all started with commit 57beb09, and has continued up to the present day, tested earlier this evening with 2.5.0-build1580. I'm sorry to say I've had no luck digging through that commit to find the culprit. Commit 6200daa and earlier, going back to at least release 2.4.1, work as expected.

I hate to be the bearer of further bad news, but the Eto test GUIs also show signs of this issue. Run Eto.Test.WinForms, and in the Unit Tests subsection of Automated Tests, tick the "include ManualTest" checkbox and click Start. Click Pass on the first test dialog that appears, then see that the one running for Expander is only large enough for the Windows window buttons. Resize it to see its contents, and you'll find the "blue rectangle" referenced by its text is missing. Keep going, and you'll get another case of this with DocumentPage; minimal size at first, and no blue rectangle when it appears.

That's what led me to include all those extra buttons in my test project; forgive me for the eye-watering wall of code it required, but it seemed useful to have them there just in case.

There also seems to be a strange issue with DocumentControl in WPF, where it's not highlighted blue and is offset so far vertically it's almost invisible until you hover over it, but that goes back further than 57beb09, and is probably its own investigation; I'm afraid I don't have the energy to track that one down right now.

**Comment by ItEndsWithTens** [comment]
Sorry to just gloss over that one, but I felt a little awkward opening a separate issue for something I hadn't even begun to try digging into. That's silly, of course, I know it's important to track these things regardless, and screenshots would at least document the problem.

It's an easy enough repro in the Eto test apps, I'll throw a new issue together ASAP!

**Comment by cwensley** [comment]
@ItEndsWithTens no problem, even I am guilty of creating issues with a "by the way, this other issue" remark. (;

This should now be fixed!  Apparently it was creating new form handlers for the parent window for any themed control, which would initialize them each time ParentWindow was accessed.  

Thanks again for reporting the issue!
