### ISSUE TITLE
[WPF] RichTextArea Selection not working correctly

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#1234]
## Expected Behavior

Text correctly selected according to defined range.

## Actual Behavior

There is a misplacement of 5 characters to the right.

## Steps to Reproduce the Problem

  1. Create a RichTextArea control
  2. Input some text
  3. Define a selection to set its color

## Code that Demonstrates the Problem

```
rtfcontrol.Appen(initialtext, true);
rtfcontrol.Append(sometext, true);
rtfcontrol.Selection = new Range<int>(rtfcontrol.Text.Length - sometext.Length, rtfcontrol.Text.Length -1);
rtfcontrol.SelectionForeground = Colors.Blue;
rtfcontrol.Append("\n", true);
rtfcontrol.Selection = new Range<int>(rtfcontrol.Text.Length);
```
## Specifications

  - Version: 2.5.0-ci-10013
  - Platform(s): WPF
  - Operating System(s): Windows 10
 
WPF:
 
<img width="865" alt="wpf" src="https://user-images.githubusercontent.com/2669419/46476561-812d3900-c7b6-11e8-8845-cf51728cacf8.png">

GTK2 (Linux):

<img width="796" alt="gtk2_linux" src="https://user-images.githubusercontent.com/2669419/46476563-81c5cf80-c7b6-11e8-84a5-a2324bf9a72c.png">

Xamarin.Mac:

<img width="778" alt="xamarin mac" src="https://user-images.githubusercontent.com/2669419/46476565-81c5cf80-c7b6-11e8-9193-84a802d18ac3.png">

**Comment by ManuelHu** [comment]
On Windows, the line ending characters are somehow not counted to the indices for selections. I currently use the following code as work-around:

```csharp
private void Write(string message, Color c)
        {
            Append(message + Environment.NewLine, true);

            int idx = -1, last = -1;
            if (Environment.OSVersion.Platform == PlatformID.Unix)
            {
                idx = Text.LastIndexOf(message);
                last = Text.Length;
            }
            else
            {
                var lines = string.Join("", Text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries));
                idx = lines.LastIndexOf(message);
                last = lines.Length;
            }

            if (idx == -1)
                return;

            Selection = new Range<int>(idx, idx + message.Length);
            SelectionForeground = c;
            Selection = new Range<int>(last, last);
        }
```

But this is definitely a bug...

**Comment by cwensley** [comment]
Yeah I've used the same hack as @ManuelHu before, it isn't pretty.  I'm not sure yet how to effectively address this without being dog slow with large text.

Thanks for reporting the issue!

**Comment by DanWBR** [comment]
Hi @cwensley, there's still one character left to fix:

<img width="1065" alt="captura de tela 2018-11-16 as 08 06 39" src="https://user-images.githubusercontent.com/2669419/48620517-c7111b80-e976-11e8-843b-2d8aa25b31d7.png">

**Comment by cwensley** [comment]
Hey @DanWBR, do you have a repro for the off by one issue?  I can't seem to reproduce it.

**Comment by DanWBR** [comment]
https://github.com/DanWBR/dwsim5/blob/windows/DWSIM.UI.Desktop.Forms/Forms/Flowsheet/Flowsheet.eto.cs#L1245

Maybe I'm using wrong indexes? It does work on macOS and GTK, though.

**Comment by cwensley** [comment]
@DanWBR, ah yes that won't work the way you have it unfortunately - WPF adds a newline at the end of the `Text` property (regardless if your text has it or not).  I have not found a way around that at this point, but it is a separate issue from this one.

What I'd recommend is to keep the current position in a variable and increment it after appending text.  Accessing the `Text` property each time just to get the length will slow down as the text gets larger.
