### ISSUE TITLE
TreeGridView.ReloadItem no longer working

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1236]
In my application I progressively populate a TreeGridView after assigning a TreeGridItemCollection to the TreeGridView DataStore, this is because I want the user to see the intermediate results.
Unfortunately after my last pull of the Eto code the ReloadItem is no longer working

## Expected Behavior
When a node isexpanded, a ReloadItem on the same node re-displays its children

## Actual Behavior
ReloadItem has no effect

## Steps to Reproduce the Problem

  1. Run the following code
  2. Click on the Start button
  3. the root node does not show its children while despite I'm calling a ReloadItem on it afte adding each chile node

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);

			TreeGridView tree = new TreeGridView();
			tree.Columns.Add(new GridColumn { DataCell = new TextBoxCell(0), HeaderText = "Text" });//, AutoSize = true, Width = 150, Resizable = true, Editable = true });

			// fill the model
			TreeGridItemCollection model = new TreeGridItemCollection();
			TreeGridItem root = new TreeGridItem();
			root.Values = new object[] { "root" };
			model.Add(root);
			tree.DataStore = model;

			Button start = new Button() { Text = "Start" };
			start.Click += (sender, e) =>
			{
				Task.Run(() =>
				{
					for (int i = 0; i < 20; i++)
					{
						TreeGridItem node = new TreeGridItem() { Values = new object[] { i.ToString() } };
						root.Children.Add(node);
						if (root.Children.Count == 1)
							root.Expanded = true;
						Application.Instance.Invoke(() => tree.ReloadItem(root));
						Thread.Sleep(1000);
					}
					Application.Instance.Invoke(() => tree.ReloadData());
				});
			};

			// create the layout
			var table = new StackLayout
			{
				HorizontalContentAlignment = HorizontalAlignment.Stretch,
				VerticalContentAlignment = VerticalAlignment.Stretch,
				Items =
				{
					start,
					new StackLayoutItem(tree, true)
				}
			};
			var form = new Form { Content = table, Size = new Size(200, 200) };

			app.Run(form);
		}
	}
}
```

## Specifications

  - Version:
  - Platform(s): tested on WPF, and XamMac2
  - Operating System(s): Windows 7, macOS 10.13

**Comment by cwensley** [comment]
Hm, this is actually changed behaviour, the ReloadItem(object) should be passing true not false to update children.  Thanks for reporting the issue!
