### ISSUE TITLE
Exception when clearing items in a StackLayout

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1237]
In my application I programmatically add/remove items to/from a StackLayout Items collection based on some needs of mine (notice that the items I remove are not wasted but "parked" somewhere, so that they can be added again later).
Unfortunately after my last pull of the Eto code (I previously pulled approximately on month ago) I get a "Control was unloaded more than once" exception after removing an item that had already been added and subsequently removed from the Items collection.

Has some logic in Eto changed so that what I do is no longer possible? 

I tried to repro the exception in a smaller program but in there it looks like adding/removing items to/from the StackLayout Items collection is still possible, on the other hand when I debug the Eto code from my application  I get the exception but I also get lost in the chain of Unload/TriggerUnload/OnUnload calls before figuring out what is going wrong.

What is the purpose of the Unload method? Why has it to be propagated to all the children?
Is the StackLayout the right control to be used if I need to alter its content after it has already been rendered?

Thanks for any piece of advice

## Specifications

  - Version:
  - Platform(s): tested on WPF, XamMac2
  - Operating System(s): tested on Windows 7, macOS 10.13

**Comment by cwensley** [comment]
Hey @msasso69, thanks for reporting the issue.

You should be able to do what you have described.  I wonder if it has to do with themed controls?  What control(s) are you adding/removing from the StackLayout?

**Comment by msasso69** [comment]
Hard to answer, I have a hell of controls cascading the one that I'm removing.
I'll try to narrow down the problem and see if I can reproduce it in a simple way, good to know that I'm not doing anything discouraged.

**Comment by cwensley** [comment]
Thanks, @msasso69.  Dynamic updates to the UI is certainly not discouraged.  A repro would be awesome as it would be good to get this into a unit test.

**Comment by msasso69** [comment]
Found the catch, it was my fault (as usual).
Basically in one of the controls contained in the Panel I was removing from the StackLayout Items list, I was overriding the OnLoad but forgot (in some cases) to call the base.OnLoad,
as a consequence the second time I was removing (unloading) my main Panel the controls contained in this sub component resulted as already unloaded.
Happy end, sorry for the false alarm.

**Comment by cwensley** [comment]
Hey @msasso69,

That's great, I'm glad I didn't break anything.  (;

No worries about the false alarm, it's good to know when people run into issues to know where pain point(s) may arise, and how to resolve them. For example, I never thought what would happen if you didn't call base.OnLoad(), but now I do (;
