### ISSUE TITLE
[Mac] Wrong horizontal scrollbar in Scrollable

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1241]
On Mac (I'm using XamMac2) the Scrollable shows a horizontal scrollbar when not necessary. 
This happens for example if the contained control is bigger in height (but not in width) than the Scrollable. Notice that as soon as the Scrollable is somehow resized the horizontal scrollbar disappears.
(I haven't tried the dual case of a contained control bigger in width but not in height) 

## Expected Behavior
Horizontal/Vertical scrollbars should only appear when necessary.

## Actual Behavior
An horizontal scrollbar is present if the contained control is bigger in height (but not in width) than the Scrollable

![image](https://user-images.githubusercontent.com/21080030/47617691-0eb82c00-daca-11e8-949a-334b830665ce.png)

In this case the Scrollable has a Size of 100x100, the contained Panel a Size of 50x100, though a horizontal scrollbar appears.

If I resize the form the horizontal scrolbar disappers as it should be since the beginning
![image](https://user-images.githubusercontent.com/21080030/47617791-555a5600-dacb-11e8-8e70-cfa384739c93.png)

In Windows (Eto-Wpf) it works correctly
![image](https://user-images.githubusercontent.com/21080030/47617435-5ab5a180-dac7-11e8-84a6-3e742456da5a.png)

To work around the problem I'm currently setting a timer (that starts after the main form is shown) in order to programmatically resize the controls (but it is an ugly hack)

## Steps to Reproduce the Problem

  1. run the following snippet of code
  2. resize a little the form (even a pixel smaller) to make the scrollbar disappear

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);
			var scrollable = new Scrollable()
			{
				ExpandContentHeight = false,
				ExpandContentWidth = false,
				Content = new Panel() { BackgroundColor = Colors.Green, Size = new Size(50, 150) },
			};
			var form = new Form { Content = scrollable, Size = new Size(100, 100) };
			app.Run(form);
		}
	}
}
```

## Specifications

  - Version:
  - Platform(s): teste on WPF (works fine) and XamMac2 (issue)
  - Operating System(s): tested on Windows 7 and macOS 10.13

**Comment by cwensley** [comment]
Hey @msasso69, this appears to be fixed in the latest develop branch.  Give it a go and let me know if it's still a problem.

**Comment by msasso69** [comment]
Hi Curtis, I pulled the latest develop changes but I still have the issue in my app, and also the repro produces the same result. Are you sure it's fixed?
