### ISSUE TITLE
XamlReader.Load(this) gives ArgumentNullException

### ISSUE THREAD

**Issue by mattpre** [picoe/Eto#1243]
I'm new to c#, having coded in c++ and mainly in python lately. For a Rhino plugin I was hoping that development in Visual Studio 2017 with Eto.Forms would make it easier to produce a clean plugin that I can distribute.

## Expected Behavior
Adding an Eto.Form to an existing c# project in Visual Studio 2017 seems fairly straightforward.

## Actual Behavior
ArgumentNullException is thrown at XamlReader.Load(this);

## Steps to Reproduce the Problem

  1. In VS17: Project -> Add Component -> Eto.Forms. Form: Xaml, Base: Form. 
      This creates 2 files, MyPanel1.xeto with a template StackLayout and a label, and MyPanel1.xeto.cs with the code for the form.
  2. The Form should get loaded from my Rhino plugin through a command. So I was trying to create the form within the RunCommand method:
```
            MyPanel1 zsf = new MyPanel1();
            zsf.Show();
```
  3. The code compiles, but throws an ArgumentNullException on the line "XamlReader.Load(this);"

I think the problem is that somewhat the Load-method cannot find the .xeto file. I don't know how to fix this as I'm basically just trying to run a sample problem created by Visual Studio.

## Code that Demonstrates the Problem

```
File MyPanel1.xeto.cs

using System;
using System.Collections.Generic;
using Eto.Forms;
using Eto.Drawing;
using Eto.Serialization.Xaml;

namespace ZSoilTools
{	
	public class MyPanel1 : Form
	{	
		public MyPanel1()
		{
			XamlReader.Load(this);
		}

		protected void HandleClickMe(object sender, EventArgs e)
		{
			MessageBox.Show("I was clicked!");
		}

		protected void HandleAbout(object sender, EventArgs e)
		{
			new AboutDialog().ShowDialog(this);
		}

		protected void HandleQuit(object sender, EventArgs e)
		{
			Application.Instance.Quit();
		}
	}
}

File HelloWorldCommand.cs:

using System;
using System.Collections.Generic;
using Rhino;
using Rhino.Commands;
using rc = Rhino.Commands.Command;
using Rhino.Geometry;
using Rhino.Input;
using Rhino.Input.Custom;
using Eto.Forms;
using Eto.Drawing;

namespace ZSoilTools
{
    public class HelloWorldCommand : rc
    {
        public HelloWorldCommand()
        {
            // Rhino only creates one instance of each command class defined in a
            // plug-in, so it is safe to store a refence in a static property.
            Instance = this;
        }

        ///<summary>The only instance of this command.</summary>
        public static HelloWorldCommand Instance
        {
            get; private set;
        }

        ///<returns>The command name as it appears on the Rhino command line.</returns>
        public override string EnglishName
        {
            get { return "HelloWorldCommand"; }
        }

        protected override Result RunCommand(RhinoDoc doc, RunMode mode)
        {
            MyPanel1 zsf = new MyPanel1();
            zsf.Show();

        }
    }
}
```

## Specifications

  - Version: Eto 2.4.1.1
  - Platform(s): Xaml
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @mattpre, thanks for submitting the issue.

When you use `XamlReader.Load(this);`, it tries to load an embedded resource in the same assembly as the class, with the same namespace and name.

So, in your case your `ZSoilTools.MyPanel1` class would require the embedded file `ZSoilTools.MyPanel1.xeto` in your assembly.  If you want to put your .xeto files elsewhere or with a different resource ID, then you can pass that as an extra argument like `XamlReader.Load(this, "My.Path.To.MyPanel1.xeto");`

Alternatively, you can pass a `Stream`, `TextReader`, or `XmlReader` to the Load method.

I hope this helps!
Curtis.

**Comment by mattpre** [comment]
Dear Curtis,

Thanks a lot for your explanation.

I apologize, I believe now that my problem is not so much Eto-related, but rather due to my lack of understanding assemblies and namespaces in c#. My Solution Explorer in VisualStudio looks like this:

![image](https://user-images.githubusercontent.com/44694657/48544375-beabd880-e8c3-11e8-8914-0389b0339c3a.png)

How can I add MyPanel1.xeto to the assembly?

Or, alternatively, how can I add the form to the same namespace (ZSoilTools)?

I updated the code snippets above, the class HelloWorldCommand wasn't in the namespace ZSoilTools previously.

Best,
Matthias
