### ISSUE TITLE
GridView headers do not support tooltips

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1253]
I would be nice to have tooltips in the headers of GridView(s) (and TreeGridView(s)).
I would expect to have them in the GridColumn(s). Since in there they are not available I'm currently emulating them setting the ToolTip of the parent GridView according to the location of the mouse in the grid on the MouseMove, but it would be nice to have them available natively.

## Specifications

  - Version: 2.4.999

**Comment by cwensley** [comment]
Thanks for the suggestion, it would indeed be useful.
