### ISSUE TITLE
How to compile and run on OSX dotnet core

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1262]
## Expected Behavior
running `dotnet eto-test.dll` should result in the application running.

## Actual Behavior
Receive error:
> A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/DWAK/eto-test/eto-test.XamMac/bin/Debug/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /Users/DWAK/eto-test/eto-test.XamMac/bin/Debug/eto-test.runtimeconfig.json file specifying the appropriate framework.

## Alternatively...
`cd {app-name}.XamMac`
`dotnet run` produces:
> /Users/DWAK/eto-test/eto-test.XamMac/eto-test.XamMac.csproj(92,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.2.100-preview2-009404/Xamarin/Mac/Xamarin.Mac.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

> The build failed. Please fix the build errors and run again.

## Steps to Reproduce the Problem

  1.  Follow Quick Start
  2. `cd {app-name}/bin/Debug`
  3. `dotnet {app-name}.dll`

## Code that Demonstrates the Problem

```
// No code, just follow the Quick Start
```

## Specifications

  - Version: Whatever is installed via the Quick Start for dotnet core as of NOV 22, 2018.
  - Platform(s): mac
  - Operating System(s): macOS 10.14.2

**Comment by DWAK-ATTK** [comment]
Nevermind.  I seem to have figured it out.

**Comment by SwiTool** [comment]
Hey don't leave other noobs in trouble, just share the solution man.
