### ISSUE TITLE
macOS does not appear to fire the Window.Closing event?

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1263]
On macOS (10.14.2 if it matters), how would you detect when someone has closed the main window via the little red dot in the title bar?  This does not currently appear to trigger the `Closing`, `Closed`, or `UnLoad` events.

**Comment by cwensley** [comment]
Hi @DWAK-ATTK,

In macOS, applications don't typically actually close the main form.  Clicking the icon opens it up again to where it left off, keeping its state (this is what most users expect on macOS).  So, in terms of Eto, the form is not actually closed it is hidden and loses focus.

If you want the main form to actually close when clicking the 'x', add this style to the beginning of your `Startup.Main` for your Mac launcher:

```c#
Eto.Style.Add<Eto.Mac.Forms.ApplicationHandler>(null, h => h.AllowClosingMainForm = true);
```

If you want to be notified if the window has lost focus, you can use `Window.LostFocus` instead.

Another option is to not use your form as the MainForm and instead create/show it during `Application.Initialize` like so:

```c#

var app = new Application(Eto.Platform.Detect);
app.Initialized += (sender, e) => {
  var form = new MyForm();
  form.Show();
};
app.Run();
```

Hope this helps!

**Comment by DWAK-ATTK** [comment]
That is perfect.  Thank you!

All these little platform differences.. my word.

I wish Microsoft, Apple, and Linux would just standardize.  They could all get together and agree on a kernel and a default UI system.  And write their respective OSes on top of that.  That would greatly simplify my life.  And isn't that what drives these mega-corps - what makes my life easiest? :)

Again, thank you!
