### ISSUE TITLE
App icon on macOS?

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1265]
Using VS Code on macOS (10.14), project created with `dotnet new etoapp -sln -m code -s`.

How would one change the app's icon during the build process?

Thanks.

**Comment by cwensley** [comment]
You need to modify the Icon.icns file that is part of the template.  See https://en.wikipedia.org/wiki/Apple_Icon_Image_format.  There are a few [ico to icns converters](
https://www.google.com/search?client=safari&rls=en&q=ico+to+icns+online&ie=UTF-8&oe=UTF-8) online.

**Comment by DWAK-ATTK** [comment]
Thnaks.
