### ISSUE TITLE
Feature Request/Enhancement: Notification Area/Menubar access

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1270]
I'm not sure how to add a label to an issue.. something like "enhancement" or "feature" might be appropriate for this one.

I'd like to make an xplat app that utilizes the Notification Area on Windows and the Menubar (near the clock) on macOS  (not sure what the linux equivalent is).

Neither API appears to be accessible in Eto at the moment.  I'm happy to write these components myself and contribute them to Eto - but I'll need some guidance.  I'm only familliar with Windows development.  macOS and Linux are foreign beasts to me.  Also, I'm pretty new to Eto - not quite up-to-date on your design philosophy.

From a rough sketch design perspective I'm thinking something like `Application.SecondaryCommands` as the entry-point for this API.  Then you would just add normal `Command` objects to it.  

Thoughts?
Anyone willing to provide guidance if I attempt this?

**Comment by cwensley** [comment]
Hey @DWAK-ATTK,

To create a tray icon, you can use the [TrayIndicator](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/TrayIndicator.cs) class.

To create a notification, use [Notification](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/Notification.cs).

Hope this helps!

**Comment by DWAK-ATTK** [comment]
Huh.  Didn't see that one in the [Controls](https://github.com/picoe/Eto/wiki/Controls) list.  Thanks!

This will work cross-platform?

**Comment by cwensley** [comment]
Hey @DWAK-ATTK,

Yes they should work on Gtk, WinForms/Wpf, and MacOS.  There may be fixes in the latest develop branch.

**Comment by DWAK-ATTK** [comment]
Thank you very much!
