### ISSUE TITLE
[Mac] SizeChanged Event not firing

### ISSUE THREAD

**Issue by MeestorX** [picoe/Eto#1291]
Similar issue as here: https://github.com/picoe/Eto/issues/822
I was creating a GridColumn that fills the space depending on the width of the Grid.
Works fine on WPF/Windows, but on Mac, the SizeChanged Event does not get fired. I tested GridView.SizeChanged and Content.SizeChanged but neither seem to be getting fired on the Mac.

Form.SizeChanged does however fire.

Is there a fix for this one?

**Comment by cwensley** [comment]
Hey @MeestorX, 

afaik, this has been fixed in the develop branch.  You can give it a try from the [myget feed](
https://www.myget.org/gallery/eto).

**Comment by MeestorX** [comment]
Thanks, cwensley! I'm not sure how to do that, but I guess I should learn! :-)

**Comment by cwensley** [comment]
Just add the myget feed to your nuget sources in `Tools > Options > NuGet package Manager > Package Sources` (VS for Windows) or `VS > Preferences > Nuget > Sources` (VS for Mac), then update your Eto nuget packages to the latest 2.5 CI build.  Make sure check "show pre-release packages" so they show up.

**Comment by MeestorX** [comment]
That was easy! Thank you so much!!

**Comment by MeestorX** [comment]
This is new:
"A reference to the NuGet RoslynCodeTaskFactory is required to build the MacOS .app bundle, or add <MacBuildBundle>False</MacBuildBundle> to your project."

I guess I should just add that reference? What is that?

**Comment by cwensley** [comment]
@MeestorX hm, that reference _should_ have been added automatically (it is a new dependency for Eto.Platform.Mac).  Are you referencing things manually?  Did you update the nuget version(s) manually instead of through the UI or with a nuget command?

**Comment by MeestorX** [comment]
I updated as you instructed. Added the feed and updated each project to 2.5 within VS2017.
Now I just added the RosylnCodeTaskFactory to each project and now it seems to compile without the error.
No doubt it was something I did. I'm just flailing around with this.

**Comment by cwensley** [comment]
@MeestorX, did updating to the develop feed work for this issue?

**Comment by MeestorX** [comment]
I'm sorry, I should have written back. It did fix the issue, thank you!

**Comment by cwensley** [comment]
Not a problem, thanks for following up and verifying that it worked!
