### ISSUE TITLE
AutoSize not working with TabControl

### ISSUE THREAD

**Issue by lukas-gerster** [picoe/Eto#1299]
## Expected Behavior
```
TabControl tabs = new TabControl {Size = new Size(-1, -1) };
TableLayout.AutoSized(tabs) 
```
This should lead to the TabControl expanding to fill the TableLayout

## Actual Behavior
The TabControl is not resized

## Steps to Reproduce the Problem

  1. Create TabControl
  2. Try to make it resizing
  3. Fail

## Code that Demonstrates the Problem

```
public partial class ClassForm : Form
    {
        public GUI gui;

        public ShipClassForm(GUI gui)
        {
            this.gui = gui;
            Title = "Classes";
            ClientSize = new Size(400, 350);

            TabControl tabs = new TabControl {Size = new Size(-1, -1) };

            tabs.Pages.Add(new TabPage { Text = "Test", Size = new Size(-1, -1), Content=new TextArea {Text = "Testortestor"} });
            tabs.Pages.Add(new TabPage { Text = "Test" });

            Content = new TableLayout
            {
                Padding = 20,
                Spacing = new Size(5, 5),
                Rows =
                {
                    new TableRow(new ListBox{ Width=50, Items = { "Item 1", "Item 2" } },TableLayout.AutoSized(tabs), new Label {Text = "Stats"}),

				}
            };
        }
    }
```

## Specifications

  - Version: MonoDevelop 2.4.1
  - Platform(s): Mac
  - Operating System(s):  macOS 10.11

**Comment by cwensley** [comment]
> This should lead to the TabControl expanding to fill the TableLayout

This is an incorrect assumption, using `TableLayout.AutoSize()` auto sizes the control to its contents, and will not expand to fill its container.  Perhaps you want something like this:

```c#
    public partial class MainForm : Form
    {
        public MainForm()
        {
            Title = "Classes";
            ClientSize = new Size(400, 350);

            TabControl tabs = new TabControl { };

            tabs.Pages.Add(new TabPage { Text = "Test", Content = new TextArea { Text = "Testortestor" } });
            tabs.Pages.Add(new TabPage { Text = "Test" });

            Content = new TableLayout
            {
                Padding = 20,
                Spacing = new Size(5, 5),
                Rows =
                {
                    new TableRow(
                        new ListBox{ Width=50, Items = { "Item 1", "Item 2" } },
                        new TableCell(tabs, true), 
                        new Label {Text = "Stats"}),

                }
            };
        }
    }
```

The key is you need to set `TableCell.ScaleWidth = true` for the cell that the tabs are placed in.  This is set via the `TableCell` constructor above.

Note that if you have multiple rows, you would set `TableRow.ScaleHeight = true` to specify the row(s) that you want to expand with the form.

Hope this helps!
Curtis.

**Comment by lukas-gerster** [comment]
Thank you for your help. That seems to work, it seems however inconsistent with Example 2 of https://github.com/picoe/Eto/wiki/TableLayout from which I based my thing on

**Comment by cwensley** [comment]
Hey @lgerster,

What exactly were you looking at?  That example uses `TableLayout.AutoSized()` for the DropDown so it does _not_ expand to the width of the cell..

This line is what causes the 2nd column to expand when resizing the form:
```c#
new TableCell(new TextBox(), true), 
```

**Comment by cwensley** [comment]
Note in the diagram:
```
//  ---------------------------------------------------------
// | First Row  | [Text Box                     ] | [Button] |
// |------------|---------------------------------|----------|
// | Second Row | [                             ] |          | expands to
// |            | [List Box                     ] |          | container's
// |            | [                             ] |          | height
// |------------|---------------------------------|----------|
// | Third Row  | [Drop Down]                     |          |
//  ---------------------------------------------------------
```

Notice 
```
[Drop Down]
```
vs.
```
[Text Box                     ]
```

**Comment by lukas-gerster** [comment]
I interpreted the AutoSized as affecting the width, my mistake

**Comment by cwensley** [comment]
@lgerster not a problem.  Do you have any suggestions to make that page a bit more clear?  I'm thinking a break down of each of the important lines might help.

**Comment by lukas-gerster** [comment]
A breakdown would certainly help. Also possibly describing TableCell as helper, since I jumped on AutoSized() since it was mentioned there.

**Comment by cwensley** [comment]
Awesome.  I've added the breakdown there.  TableCell isn't a helper method but a class.  I think this information should go in the Scaling section which doesn't even mention TableCell or TableRow (but should).

Thanks for the feedback!

**Comment by lukas-gerster** [comment]
You are welcome, thank you for the fast and helpful replies.
