### ISSUE TITLE
Throw a specific error if object is disposed.

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#1301]
After a control is disposed, calling most methods/properties would throw a `NullReferenceException` when trying to access the `Handler` property.  Instead, we could do a check and throw an `ObjectDisposedException` which would be much more useful.

Also investigate whether an `IsDisposed` property would be useful.

**Comment by simplexidev** [comment]
IMHO, I like having an `IsDisposed` method (or equivalent). I do that with in [tacdevel/tcdfx](https://github.com/tacdevel/tcdfx) with a custom[`Disposable`](https://github.com/tacdevel/tcdfx/blob/master/source/TCD.Disposable/src/TCD/Disposable.cs) base class.
