### ISSUE TITLE
Unable to set MainWindow to Visible=false on App launch

### ISSUE THREAD

**Issue by thomas-goerlich** [picoe/Eto#1302]
## Expected Behavior
Setting Visible=false in InitializeComponent hides the window.

## Actual Behavior
The window is visible.

## Steps to Reproduce the Problem

  1. Set Visible = false in InitializeComponent.
  2. Start the app

## Code that Demonstrates the Problem

```
Visible=false;
```

## Specifications

  - Version: 2.4.1 / develop as of 2019/01/13
  - Platform(s): only tested WPF, sorry
  - Operating System(s): Windows 10
  
## Workaround
My workaround is doing this right now in InitializeComponent:

```
System.Threading.Tasks.Task.Run(() => {
    System.Threading.Tasks.Task.Delay(2000);
    Application.Instance.Invoke(() => Visible = false);
});
```

I am writing a small Pomodoro Timer. I want to run it as an tray only app and usually i don't want to see the window all the time which is why i want to be able to hide it on launch.

**Comment by thomas-goerlich** [comment]
Okay i just realised that my workaround is not really working. I mean yes it hides the window but from that point forward it seems that i am unable to make the window visible again.

**Comment by cwensley** [comment]
Hey @thomas-goerlich,

Just don't pass anything to `Application.Run()`:

```c#
var app = new Application();
app.Initialized +=.(sender, e) {
  // do your stuff to show the tray icon.
};
app.Run();
```

Passing a form to `Application.Run` makes it the main form (`Application.MainForm`) and will show it automatically when the application is initialized.

**Comment by thomas-goerlich** [comment]
Thanks @cwensley!
Works perfectly 😃

**Comment by BrianAllred** [comment]
@cwensley Didn't want to open a new issue for such a related question, but...

I have a use case where my application is essentially a tray service with a settings dialog. However, using the above snippet, the entire application closes when I close the dialog. I can think of a few workarounds (use a dialog singleton and only show/hide, for example), but was wondering if there was a way to just not exit the app.

```
public static void Main(string[] args)
{
    var app = new Application(Eto.Platforms.Gtk);
    app.Initialized += (sender, e) =>
    {
        new MainTray().Show();
    };

    app.Run();
}
```

```
public class MainTray : TrayIndicator
{
    public MainTray()
    {
        var settingsCommand = new Command { MenuText = "Settings" };
        settingsCommand.Executed += (sender, e) => new SettingsDialog().ShowModalAsync();

        var quitCommand = new Command { MenuText = "Quit", Shortcut = Application.Instance.CommonModifier | Keys.Q };
        quitCommand.Executed += (sender, e) => Application.Instance.Quit();

        var trayMenu = new ContextMenu(new List<MenuItem>() {
            settingsCommand,
            quitCommand
        });

        Menu = trayMenu;
        Image = new Icon("./Assets/icon.ico");
    }
}
```

`SettingsDialog` is currently just a blank 200x200 dialog.

**Comment by thomas-goerlich** [comment]
@BrianAllred not sure that it helps you, but in my case my windows inherit from the _Form_ class and I can close them without it quitting the app.

**Comment by BrianAllred** [comment]
@thomas-goerlich Unfortunately, in my case, the behavior is the same.
