### ISSUE TITLE
Cannot start WebView on Ubuntu 18.04 with GTK2

### ISSUE THREAD

**Issue by Marti2203** [picoe/Eto#1304]
## Expected Behavior
Start a WebView

## Actual Behavior
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'webkit-sharp, Version=1.1.15.0, Culture=neutral, PublicKeyToken=eaa1d335d2e19745' or one of its dependencies.

## Steps to Reproduce the Problem

  1.  Make Clean Solution
  2.  Install Eto.Forms and Eto.Platform.GTK2
  3.  Try to construct a webview

## Code that Demonstrates the Problem (F#)

```
let web = new WebView()
```

## Specifications

  - Version: 2.4.1
  - Platform(s): Gtk2
  - Operating System(s):  Ubuntu 18.04

**Comment by Marti2203** [comment]
With Eto.Platform.GTK3 it works

**Comment by SlowLogicBoy** [comment]
install `webkit-sharp` package to your Linux distribution.
@cra0zy is GTK2 still supported?
I found `libwebkit2-sharp-4.0-cil-dev` package but not sure if this will work since its 2.0 instead of 1.0.

**Comment by Marti2203** [comment]
Not found and I did try that I have :
* libwebkit2-sharp-4.0-cil/bionic,now 2.10.9+git20160917-1.1 amd64 [installed]
  CLI bindings for WebKitGTK+ 4.0 using GObject Introspection

* libwebkit2gtk-4.0-37/bionic-updates,bionic-security,now 2.22.5-0ubuntu0.18.04.1 amd64 [installed]
  Web content engine library for GTK+

* libwebkit2gtk-4.0-37-gtk2/bionic-updates,bionic-security,now 2.22.5-0ubuntu0.18.04.1 amd64 [installed]

* libwebkitgtk-1.0-0/bionic,now 2.4.11-3ubuntu3 amd64 [installed]
  Web content engine library for GTK+

* libwebkitgtk-3.0-0/bionic,now 2.4.11-3ubuntu3 amd64 [installed]

**Comment by harry-cpp** [comment]
WebKit 1 is no longer supported by Linux distros and a good chunk of them have started to remove it.

WebKit 2 only supports Gtk 3.

@cwensley You can close this.

**Comment by Marti2203** [comment]
Okay, thank you.
