### ISSUE TITLE
[Mac] controls in a PixelLayout need to be repositioned after resizing them

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1316]
Many of my controls (mainly grids and trees) are added to a PixelLayout together with a progress bar that I make visible when loading lots of data.
In order to fit my controls to the size of the PixelLayout I am also sizing them on the SizeChanged event of the PixelLayout.
Unfortunately from commit 2da1cdc I also need to reposition my controls after sizing them, otherwise their location go bananas :)
An example of the described behaviour is in the following code where there is a GridView in a PixelLayout (I omitted the progress bar since it is not needed to show the regression).

## Expected Behavior
![image](https://user-images.githubusercontent.com/21080030/52444191-f4a9d300-2b27-11e9-83a8-3d71fb562b58.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/21080030/52444414-9a5d4200-2b28-11e9-85cb-9b2203d417b9.png)

## Steps to Reproduce the Problem

  1. Run the following repro
  2. uncommenting pl.Move(grid, 0, 0); the grid is positioned correctly

## Code that Demonstrates the Problem

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Eto;
using Eto.Drawing;
using Eto.Forms;

namespace VisualSEO.EtoFormGui
{
    public class Program
    {
        [STAThread]
        public static void Main(string[] args)
        {
            var app = new Application(Platform.Detect);

            MyGrid grid = new MyGrid() { Width = 200, Height = 100 };
            grid.Columns.Add(new GridColumn { DataCell = new TextBoxCell("Col1") });
            grid.Columns.Add(new GridColumn { DataCell = new TextBoxCell("Col2") });
            ObservableCollection<Data> model = new ObservableCollection<Data>();
            model.Add(new Data { Col1 = "row 1 col 1", Col2 = "row 1 col 2" });
            model.Add(new Data { Col1 = "row 2 col 1", Col2 = "row 2 col 2" });
            model.Add(new Data { Col1 = "row 3 col 1", Col2 = "row 3 col 2" });
            model.Add(new Data { Col1 = "row 4 col 1", Col2 = "row 4 col 2" });
            grid.DataStore = model;

            var form = new Form { Content = grid, Size = new Size(250, 150) };

            app.Run(form);
        }
    }

    public class Data
    {
        public string Col1 { get; set; }
        public string Col2 { get; set; }
    }

    public class MyGrid : Panel
    {
        PixelLayout pl;
        GridView grid;

        public MyGrid()
        {
            grid = new GridView();
            pl = new PixelLayout() { BackgroundColor = Colors.Salmon };
            pl.Add(grid, new Point(0, 0));
            Content = pl;

            pl.SizeChanged += (sender, e) =>
            {
                grid.Size = new Size(pl.Width, pl.Height);
                //pl.Move(grid, 0, 0); // needed from commit 2da1cdc (Mac: fixes for dark mode support)
            };
        }

        public IEnumerable<object> DataStore
        {
            get { return grid.DataStore; }
            set { grid.DataStore = value; }
        }

        public GridColumnCollection Columns
        {
            get { return grid.Columns; }
        }
    }
}
```

## Specifications

  - Version: develop from commit 2da1cdc (Mac: fixes for dark mode support)
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13.4

**Comment by cwensley** [comment]
Awesome! thanks for taking the time to submit the issue, @msasso69.
