### ISSUE TITLE
ITreeGridItem does not contain Children

### ISSUE THREAD

**Issue by lukas-gerster** [picoe/Eto#1321]
## Expected Behavior
ITreeGridItem should contain a TreeGridItemCollection children property that is being used like  TreeGridItem's child properties

## Actual Behavior
It is not obvious to me how to add children to a custom object that implements ITreeGridItem

```
internal class ComponentGridItem : ITreeGridItem
    {

        public int Amount { get; set; }

        public bool Expanded { get; set; }

        public bool Expandable { get; private set; }

        public ITreeGridItem Parent { get; set; }

        public TreeGridItemCollection Children; //Not part of the interface

        public ComponentGridItem() {

        }
    }
```

## Specifications

  - Version: 2.4.1
  - Platform(s): All
  - Operating System(s): All

**Comment by cwensley** [comment]
You need to specify the type of child by using `ITreeGridItem<ITreeGridItem>` or `ITreeGridItem<MyITreeGridItemClass>`.  It requires a `Count` property and a `this[int index]` accessor to support showing children.  You can easily forward this to your own children collection.

Also, make sure you set the Parent properly when building the tree.  `TreeGridItem` and `TreeGridItemCollection` does this automatically.

**Comment by cwensley** [comment]
Hey @lgerster, have you tried my suggestions?  I don't think this is an issue.

**Comment by lukas-gerster** [comment]
Yes, it solved the issue. I overlooked that Interface required the additional type specification

**Comment by cwensley** [comment]
@lgerster awesome, thanks for the update!
