### ISSUE TITLE
[Mac] How to copy & paste text in a TextBox using the keyboard?

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1323]
This is not a bug but a question: how can I copy and paste a text in a TextBox using the keyboard keys  "command + c" and "command + v"?
I noticed that in the Eto Test application I can do it, but in my application I cannot.
What am I missing? A style?

**Comment by cwensley** [comment]
@msasso69 add a menubar to your window.  It will (by default) add the standard macOS menu items that are required for the keyboard shortcuts to be wired up.  On other platforms it is benign, so you don't need to test if you're running on macOS or not.

`myWindow.Menu = new MenuBar();`

Hope this helps!

**Comment by msasso69** [comment]
Yes, it works, thanks, but now have a lot of other unlocalized menu items that I'm not using, included a Help/Search functionality.
They are grayed out but they look really out of context with my application. Any chance to hide them somehow?

**Comment by msasso69** [comment]
solved hooking the system commands I need to my menu with a code similar to this:
```
menu = new MenuBar() { IncludeSystemItems = MenuBarSystemItems.None };
var edit = new ButtonMenuItem();
menu.Items.Add(edit);
var lookup = menu.SystemCommands.ToLookup(r => r.ID);
edit.Items.Add(new ButtonMenuItemEx(lookup["mac_copy"].First()));
edit.Items.Add(new ButtonMenuItemEx(lookup["mac_paste"].First()));
```
In fact what I needed was just the possibility to copy and paste from my keyboard without adding all the extra menu items in my main menu (in fact I was using MenuBarSystemItems.None).
In this way I do not have the extra entries that I do not want, but I still have two unwanted entries:

![image](https://user-images.githubusercontent.com/21080030/53108333-21ea7e00-3537-11e9-8d0a-e0d22c779f9b.png)
How do I get rid of them? :)

**Comment by cwensley** [comment]
Hm, you're still missing things like Cut, Select All, undo/redo, etc that users will expect to be able to use in a text box (and will frustrate any Mac user).  However, I guess if you _really_ don't want them in your menu you can do what you desire.  I'm glad you figured out how to use the `MenuBar.SystemCommands` collection, that was what I was going to suggest.

The other two are added by macOS, a quick google search yields [this technique](https://stackoverflow.com/questions/21369736/remove-start-dictation-and-special-characters-from-menu).  Without them, users won't be able to use dictation or popup the emojis/symbol selector in your app.

Hope this helps!

**Comment by msasso69** [comment]
Thanks for the hint!
Yes you right, I agree with you that some more system commands should be included (and I will),
but some others need to me removed from my main menu because we let the user to choose among a set of supported languages, so those items that I cannot translate I have to remove.
I'll try now to figure out how to remove the "Start Dictation" and "Emoji & Symbols" entries from the link you passed me, even if (I confess) I don't have a clue from where to start ;)

**Comment by cwensley** [comment]
Makes sense.  The system-added menu items are automatically translated for you afaik, it's just the ones that are added by Eto to create the standard menu options are not.

Also, I'm not sure if you're aware but you can now provide translation for all of the system commands (and any other system strings, like in the AboutDialog) via the new [Application.Instance.LocalizeString](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/Application.cs#L46) event.

**Comment by msasso69** [comment]
I knew you added some support to localization from your commits, but I never investigated how it works.
I'll have a look at it, Thanks!

**Comment by cwensley** [comment]
I think this issue is closed, feel free to comment/reopen if it's still an issue for you.

Thanks!
