### ISSUE TITLE
ThemedDocumentControlHandler.TabPadding

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1331]
Per discussion in gitter, it turns out that ThemedDocumentControlHandler.TabPadding is not accessible and is also static rather than an instance property. This ticket is thus filed to request the relevant changes.

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I agree the padding it too big by default so I've reduced it to 6 instead of 10.  Also, you can now change the padding via a style:

```c#
Style.Add<ThemedDocumentControlHandler>(null, h => h.TabPadding = 2);
```
