### ISSUE TITLE
GTK3 Function not found: warnings

### ISSUE THREAD

**Issue by trampster** [picoe/Eto#1338]
## Expected Behavior
Can run with GTK3 backend without warnings

## Actual Behavior
[WARNING] Function not found: gtk_normalise_detailed_action_name
[WARNING] Function not found: g_source_get_type

[WARNING] Function not found: cairo_atsui_font_face_create_for_atsu_font_id
[WARNING] Function not found: cairo_glitz_surface_create
[WARNING] Function not found: cairo_quartz_surface_create
[WARNING] Function not found: cairo_directfb_surface_create
[WARNING] Function not found: cairo_win32_font_face_create_for_logfontw
[WARNING] Function not found: cairo_win32_scaled_font_done_font
[WARNING] Function not found: cairo_win32_scaled_font_get_metrics_factor
[WARNING] Function not found: cairo_win32_scaled_font_select_font
[WARNING] Function not found: cairo_win32_surface_create
[WARNING] Function not found: cairo_win32_surface_create_with_ddb

## Steps to Reproduce the Problem

  1. First two warnings happen when the app loads
  2. The cairo warnings happen while using a Eto.Forms.Drawable

## Code that Demonstrates the Problem

1. checkout code from https://github.com/trampster/Ropu
2. navigate to ClientUI folder
3. dotnet run

## Specifications

  - Version: 2.4.1
  - Platform(s): Gtk3 
  - Operating System(s): ubuntu 18.04

**Comment by cwensley** [comment]
@cra0zy?

Afaik, it is not a goal of [GtkSharp](https://github.com/GtkSharp/GtkSharp) to run without warnings.

**Comment by trampster** [comment]
Either the warnings matter, and should be fixed.

Or they do not matter and should be suppressed.

**Comment by cwensley** [comment]
Also, did you try updating to the latest version of GtkSharp [from nuget](https://www.nuget.org/packages/GtkSharp/)?

**Comment by cwensley** [comment]
These warnings aren't generated by Eto, so really you are reporting the issue in the wrong place.

**Comment by trampster** [comment]
I'm referencing Eto.Platform.Gtk 2.4.1 which is the latest version. I don't actually reference GtkSharp directly. How do I use a later GtkSharp?

**Comment by cwensley** [comment]
[Eto.Platform.Gtk](https://www.nuget.org/packages/Eto.Platform.Gtk/) v2.4.1 has a dependency on [GtkSharp](https://www.nuget.org/packages/GtkSharp/) >= 3.22.24.29.   Simply update GtkSharp to the latest (3.22.24.37).

**Comment by cwensley** [comment]
> I don't actually reference GtkSharp directly

This is how sdk style .csproj's work (they hide all of the child dependencies).  You can just add GtkSharp as a specific dependency of your project and voila.

**Comment by trampster** [comment]
Yes that version fixes it. Will Eto.Forms update it's dependency version?

**Comment by cwensley** [comment]
> Will Eto.Forms update it's dependency version?

Yes, it's been updated for v2.5.0 already, which will be released soon.

**Comment by trampster** [comment]
Sweet feel free to close this issue

**Comment by cwensley** [comment]
Cheers, and thanks for reporting it!  It may help others as well.
