### ISSUE TITLE
Married surname unavailable

### ISSUE THREAD

**Issue by Dreamer451** [picoe/Eto#1357]
## Expected Behavior
Able to add a 'Married surname' while editing an individual.

## Actual Behavior
The 'Married surname' textbox remains greyed out.

## Steps to Reproduce the Problem

1.   Create a male individual (e.g., Joe Smith)
2.   Create a female individual (e.g., Mary Jones)
3.   When editing the individual Mary Jones, add Joe Smith as her spouse
4.   Wanting to set "Smith" as Mary's 'Married surname' cannot be done because that textbox is greyed out.

## Specifications

  - Version: 2.15.0
  - Platform(s): 
  - Operating System(s): Windows 10 (64-bit)

**Comment by cwensley** [comment]
Hey @Dreamer451,

I think you have the wrong repo.. this is a cross platform UI toolkit, not an application to enter individuals.
