### ISSUE TITLE
question -- unit testing Eto.Forms

### ISSUE THREAD

**Issue by pablocar80** [picoe/Eto#1358]
Hello!
Is it possible, and is there a recommended/suggested approach to unit test apps developed with Eto.Forms? This would mean writing code that simulates a user clicking on buttons, typing, etc.
Thank you!

**Comment by SlowLogicBoy** [comment]
It is possible to mock Eto.Forms itself:
I use [Moq](https://github.com/moq/moq4) to mock all the buttons etc.
Create Test Platform by inheriting [Platform class](https://github.com/picoe/Eto/blob/develop/src/Eto/Platform.cs#L110)
Run app by passing that platform to application class `new Eto.Forms.Application(new MyTestPlatform()).Run(new MyForm());`
At first it will throw exceptions, so you'll have to mock all required classes.
As an example I use, [Gtk Platform](https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Platform.cs#L99).
`p.Add<Button.IHandler>(() => Mock.Of<Button.IHandler>());`

**Recommended approach** would be to use MVVM pattern, and test functionality of ViewModels.

**Comment by cwensley** [comment]
Closing as I believe this is answered.  Thanks @SlowLogicBoy for helping out!!
