### ISSUE TITLE
Eto.Gtk2 : etoViewport viewports not resizing their contents

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1359]
## Expected Behavior

With reference to https://github.com/philstopford/etoViewport, the Eto.Forms specific bits are largely contributed. The test application permits resizing of the viewports by splitter and also by resizing the window. The resizing should cause the viewports to 'expand' to fill the control.

## Actual Behavior

On Gtk2, the viewports are drawn in a fixed size within the control and do not react to resize events from splitter or the window.

## Steps to Reproduce the Problem

  1. Build the TestEtoGl.Gtk2 project in the source
  2. Run the binary.
  3. Resize the window and/or move the splitter.

## Code that Demonstrates the Problem

https://github.com/philstopford/etoViewport

## Specifications

  - Version: 2.4.1, head
  - Platform(s): Gtk2
  - Operating System(s): Linux Mint, CentOS, OpenSUSE

**Comment by ItEndsWithTens** [comment]
In toying with etoViewport in my own project, I've found my GLSurfaces resize just as well in GTK as in any other platform, so out of curiosity I dug into this to see if I could understand why mine worked. The answer seems to be my personal preference of handling as much GL bookkeeping (MakeCurrent, SwapBuffers, and namely in this case, GL.Viewport) as possible by hand, whereas the etoViewport test projects rely on the control itself to do some of that work, and not all platforms bother.

Looking at WinForms for example: there's [an "updateView" method](https://github.com/philstopford/etoViewport/blob/d71472da36a132d16d38776e31e738558ce3138b/Eto.Gl.WinForms/WinGLSurfaceHandler.cs#L44) that calls MakeCurrent, sets a GL viewport, calls the draw callback, and swaps the buffers:
```C#
public void updateView() {
    if (!Control.IsInitialized)
        return;

    MakeCurrent();
    GL.Viewport(Control.Size);
    Callback.OnDraw(Widget, EventArgs.Empty);
    SwapBuffers();
}
```

It's attached through an event handler [here](https://github.com/philstopford/etoViewport/blob/d71472da36a132d16d38776e31e738558ce3138b/Eto.Gl.WinForms/WinGLSurfaceHandler.cs#L68), so every time the control's SizeChanged or Paint events are raised, all that stuff happens.

In contrast, the GTK handler attaches an anonymous method that [just calls the draw callback](https://github.com/philstopford/etoViewport/blob/d71472da36a132d16d38776e31e738558ce3138b/Eto.Gl.Gtk2/GtkGlSurfaceHandler.cs#L51):
```C#
case GLSurface.GLDrawEvent:
    Control.Resize += (sender, args) => {
        if (Control.IsInitialized)
            Callback.OnDraw (this.Widget, args);
    };
```

So when the Resize event is raised, the widget draws itself, but there's no change to the OpenGL viewport, and the content doesn't update properly. If you replace that anonymous method with something like this:
```C#
Control.Resize += (sender, args) => {
    if (Control.IsInitialized)
    {
        MakeCurrent();
        GL.Viewport(0, 0, Widget.Width, Widget.Height);
        Callback.OnDraw(this.Widget, args);
        SwapBuffers();
    }
};
```

The control now changes size when the window does, or when the splitter moves. Not that I'd necessarily want to copy and paste code like that for every custom platform handler, but it does seem to get the job done in the short term.

To be fair, I don't know if this approach is really necessary; [the Mac handler](https://github.com/philstopford/etoViewport/blob/d71472da36a132d16d38776e31e738558ce3138b/Eto.Gl.Mac/MacGLSurfaceHandler.cs#L98) doesn't seem to have any special accommodations, but the viewports resize just fine on my High Sierra machine. Off the top of my head I couldn't say why, I'm afraid, so take my suggestion with a grain of salt, but ultimately this seems like an OpenGL/OpenTK issue more than an Eto one.

**Comment by philstopford** [comment]
I could be persuaded. The odd thing is that I could have sworn this worked previously without that, so this is why I raised the ticket (in case something broke or was changed and this was a known side effect).

**Comment by ItEndsWithTens** [comment]
Ah, yes, good point. Now that you mention it I want to say I have a vague recollection of it working at some point in some distant, bygone era, but I haven't run the test projects regularly enough to be confident about when something might have changed.

**Comment by cwensley** [comment]
Closing this as think this has be resolved.  If it is still happening, please file an issue on the https://github.com/picoe/Eto.OpenTK repo
