### ISSUE TITLE
Support Visual Studio 2019 in Eto.Forms Addin

### ISSUE THREAD

**Issue by canton7** [picoe/Eto#1368]
It looks like the Eto.Forms Visual Studio Addin does not support Visual Studio 2019

**Comment by cwensley** [comment]
Thanks for reporting the issue, the addin has not been updated to VS 2019, but will be soon!

**Comment by andreakarasho** [comment]
news?

**Comment by mikel785** [comment]
Is there any progress?

**Comment by mheilemann** [comment]
This is something I am also interested in, any ETA?

**Comment by waliarubal** [comment]
I am also looking for the addin to support VS2019.

**Comment by cwensley** [comment]
Hey guys, thanks for your patience in this.  Updating the VS addin for Mac and Windows is next on my list when I get spare time.

**Comment by SCLD-JBuczkowski** [comment]
We're definitely interested in it.
Is there an updates regarding progress?

Thx

**Comment by cwensley** [comment]
Yes there's been some movement.  I've updated everything to VS2019 but haven't had a chance to test it much.  It would be helpful if someone could give it a go and report back any issues!  

You can download it from [here](https://dev.azure.com/picoe/Eto.Forms/_build/results?buildId=532&view=artifacts&type=publishedArtifacts).

**Comment by SCLD-JBuczkowski** [comment]
Thx so much. I'm pulling it today and will start looking at it.

**Comment by SCLD-JBuczkowski** [comment]
Naive question and probably not the forum, but I didn't want to open an issue.
Q: What is the difference between "embedding Eto in WPF" vs "embedding WPF in ETO?"
When would I use either?

Thx

**Comment by SCLD-JBuczkowski** [comment]
Are sources available for the samples?

**Comment by rafntor** [comment]
I tried it briefly ; It installs flawlessly and New-Project:Eto.Forms.Application + New-Item:Eto.Forms.View works just as expected. But the forms preview-view does not pop up, opening a file xxx.eto.cs opens as plain text only (same with xaml & json) ;

![image](https://user-images.githubusercontent.com/44544090/72541858-831fec00-3883-11ea-9d0d-108fa58fec32.png)

**Comment by rafntor** [comment]
And there is this, but you are probably aware of that ;
![image](https://user-images.githubusercontent.com/44544090/72542280-2bce4b80-3884-11ea-8d3d-d593811be2f7.png)

**Comment by cwensley** [comment]
@SCLD-JBuczkowski:
> Q: What is the difference between "embedding Eto in WPF" vs "embedding WPF in ETO?"

- "Embedding Eto in WPF" is when you have an existing WPF app and want to use Eto controls in it without replacing the whole WPF app.
- "Embedding WPF in Eto" is when you want to use Eto as the primary app but embed a WPF control into it.

>Are sources available for the samples?

They are all [here](https://github.com/picoe/Eto/tree/develop/samples).

**Comment by cwensley** [comment]
@rafntor thanks for the quick test!  Bummer though, it looks like VS on both Mac _and_ Windows messed up the entire designer piece by rewriting all of their editor interfaces.  Yay.  On the slightly plus side, I think they might be using the same interfaces now so I might be able to reuse some code.  That's just a guess though.

As for the warnings restoring packages, that would go away if you added the [myget feed](https://www.myget.org/F/eto/api/v3/index.json) to your nuget sources.  It also won't be a problem after the final release.

**Comment by cwensley** [comment]
@rafntor actually, I just did a quick test on that, it appears the preview is working but it just starts out collapsed.  If you drag the splitter on the top of the window down it reveals the designer surface.  Could you confirm?

**Comment by rafntor** [comment]
Yes, you are right, I was fooled (the collapse really hides it completely)
It does not quite work for me, though, some references mixed up, but indeed the preview area is there;
![image](https://user-images.githubusercontent.com/44544090/72547886-d434dd80-388d-11ea-9b3a-58b7a11280c1.png)

**Comment by cwensley** [comment]
@rafntor yes that's the same as #1552, which only happens with .eto.cs files when using .NET Standard 2.0.  I still need to fix that one up.  It appears to be working with .xaml files at least.

**Comment by rafntor** [comment]
Yes, can confirm xaml working for me too. When I downgrade to Eto.Forms 2.4.1 and netstandard1.6 the reference-error changes ;
![image](https://user-images.githubusercontent.com/44544090/72553804-ba999300-3899-11ea-8bbd-20a1e9bd9912.png)

**Comment by cwensley** [comment]
@rafntor great thanks for the additional test there, I'll try to get that resolved as well.

**Comment by SCLD-JBuczkowski** [comment]
@cwensley : This really looks promising for our cross platform UI solution for .Net Core.

**Comment by ejongejans** [comment]
> @rafntor yes that's the same as #1552, which only happens with .eto.cs files when using .NET Standard 2.0. I still need to fix that one up. It appears to be working with .xaml files at least.

Just to add; it happened as well when switching the main project file to .NET4.6.1 instead of .NET Standard x.x. Seems only 2 different references are double references.  

Another observation today; on my Ubuntu machine with MonoDevelop i do as well get a split screen when opening a .eto.cs file. Not sure how that works without the VSIX, however also these reference errors. Can check tomorrow which ones if it would help? 

Last, i just tried to use the latest .VSIX referenced above. I have VS2019 installed however when i double click the VSIX installer i don't get past the accept. 
How to find out what prerequisites I'm missing?

![image](https://user-images.githubusercontent.com/2496269/72558557-36e4a400-38a3-11ea-9de7-6c36d3d747dd.png)

**Comment by cwensley** [comment]
@ejongejans these are the prerequisites:

<img width="345" alt="Screen Shot 2020-01-28 at 1 24 53 AM" src="https://user-images.githubusercontent.com/367446/73251047-0804e280-416d-11ea-9e24-2ad0edb8ac7f.png">

Perhaps you need to update VS to the latest version?  I'm not sure how to make it so it installs or shows the prerequisites when trying to install it..

**Comment by cwensley** [comment]
Addin for the latest VS for Mac can be downloaded [here](https://dev.azure.com/picoe/Eto.Forms/_build/results?buildId=558&view=artifacts&type=publishedArtifacts).  

Please give it a whirl!
