### ISSUE TITLE
WPF - contextmenu on customcell

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1370]
I have a CustomCell with a Image, CheckBox and a Label.
The problem is with ContextMenu, when I click with right mouse button on a row, which was previously not selected.

When I click the Image or the CheckBox, the selection first changes to that row and then the contextmenu comes up.
Thats expected behaviour.

But when I click the Label, the selection is not changed, but the contextmenu still comes up. 
Thats not expected behaviour.
Selection should always change first, also when the label was clicked.

What causes this different behaviour with Label, while its fine with Image and Checkbox?
Any workaround?

Problem is only with WPF, Mac is fine.
```
public class CheckboxImageTextCell : CustomCell
{
	protected override Control OnCreateCell(CellEventArgs args)
	{
		var check = new CheckBox { };
		check.BindDataContext<bool>("Checked", "Visible");
		check.BindDataContext<bool>("Visible", "CheckBoxVisible");

		var image = new ImageView { };
		image.BindDataContext<Image>("Image", "Icon");

		var text = new Label { Wrap = WrapMode.Word };  
		text.BindDataContext<string>("Text", "NameStatus");

		var control = new StackLayout
		{
			Orientation = Orientation.Horizontal,
			VerticalContentAlignment = VerticalAlignment.Center,
			Padding = new Padding(1, 1, 0, 0),
			Spacing = 3,
			Items =  { new StackLayoutItem( image, VerticalAlignment.Top ),
					   new StackLayoutItem( check, VerticalAlignment.Top ),
					   new StackLayoutItem( text,  VerticalAlignment.Top , true )  },
		};
		return control;
	}
}

```

**Comment by TomQv** [comment]
Ok, workaround is not using TreeGrid.ContextMenu, but using MouseUp-Event, change selection manual and then create and show contextmenu.

**Comment by cwensley** [comment]
Hm, your example doesn't actually include anything regarding ContextMenu..  This needs more info to repro, please reopen with more info and if it is still an issue for you.
