### ISSUE TITLE
DropDown and a potential ItemValueBinding

### ISSUE THREAD

**Issue by MDueh** [picoe/Eto#1378]
If the DropDown control ddTest is set up like below:

MainViewModel vmMain = .....;  //MainViewModel containing a TestValue property
List\<TestViewModel\> datasource = ....; //List of TestViewModel objects

ddTest.DataStore = datasource;
ddTest.ItemTextBinding = Binding.Property((TestViewModel tvm) => tvm.UIDisplayProp);
ddTest.SelectedValueBinding.Bind(vmMain, vm => vm.TestValue);

The UI will display the UIDisplayProp property value for each TestViewModel item in the DropDown. Also, when the user selects an item in the DropDown, the selected TestViewModel object/item, will be assigned to MainViewModel.TestValue. 
My question is then, would it be possible to add something like:

ddTest.ItemValueBinding = Binding.Property((TestViewModel tvm) => tvm.SomeValueProp);

So the selected TestViewModel object/item is not assigned to MainViewModel.TestValue, but the TestViewModel.SomeValueProp property value is instead? Maybe that's actually what ItemKeyBinding is intended for? If that is the case, it does not seem to be working (on Windows 10 / WPF at least)?

**Comment by cwensley** [comment]
Hey sorry for the late response, but you can already do this using the (many) binding features.

Here's a full working example that keeps two-way binding:

```c#
	class MainViewModel
	{
		int _testValue;
		public int TestValue
		{
			get => _testValue;
			set
			{
				_testValue = value;
				Console.WriteLine($"Set to {value}");
			}
		}
	}

	class TestViewModel
	{
		public string UIDisplayProp { get; set; }
		public int SomeValueProp { get; set; }

	}

	public class TestForm : Form
	{
		public TestForm()
		{
			var ddTest = new DropDown();
			var vmMain = new MainViewModel(); //MainViewModel containing a TestValue property
			var datasource = new List<TestViewModel>(); //List of TestViewModel objects
			datasource.Add(new TestViewModel { SomeValueProp = 1, UIDisplayProp = "one" });
			datasource.Add(new TestViewModel { SomeValueProp = 2, UIDisplayProp = "two" });
			datasource.Add(new TestViewModel { SomeValueProp = 3, UIDisplayProp = "three" });

			ddTest.DataStore = datasource;
			ddTest.ItemTextBinding = Binding.Property((TestViewModel tvm) => tvm.UIDisplayProp);
			ddTest.SelectedValueBinding
				.Convert(d => (d as TestViewModel)?.SomeValueProp, v => datasource.FirstOrDefault(r => r.SomeValueProp == v))
				.Bind(vmMain, m => m.TestValue);

			var layout = new DynamicLayout();
			layout.AddCentered(ddTest);
			Content = layout;
		}
	}
```

Hope this helps!
Curtis.
