### ISSUE TITLE
[Mac] Extra 12 pixel padding at the bottom of a Dialog

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1379]
I don't know whether this is a bug or the intended behaviour, but I noticed that now Dialogs have an extra 12 pixel padding at the bottom while in the past the default padding was zero for all sides (I cannot say when this extra padding appeared for the first time, probably around a couple of months ago).

## Expected Behavior
As I said I'm not sure whether this is a bug or not, but since in the past it was not present and on Windows (Eto-Wpf) it is not present, I assume this is a regression and that there should not be any extra padding.

## Actual Behavior
A dialog has a 12 pixel padding at the bottom by default, this is particularly noticeable in Dialog2 of the following picture:

![image](https://user-images.githubusercontent.com/21080030/56838381-150f4100-687e-11e9-81af-886f8e53cf28.png)

The downside of this extra padding is that while designing our dialogs, if we want to position our controls at the same distance from the borders, we need to take into account this extra padding.

As you can see forms do not have this extra padding.
## Steps to Reproduce the Problem

  1. Run the following repro
  2. Click the buttons
  3. Enjoy :)

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyForm());
		}

		public class MyForm : Form
		{
			public MyForm()
			{
				this.Width = 200;
				this.Height = 100;
				Title = "MyForm";
				Padding = 12;
				BackgroundColor = Colors.Orange;

				var btn = new Button { Text = "Click me" };
				btn.Click += (sender, e) =>
				{
					new MyDialog().ShowModal();
				};

				Content = btn;
			}
		}

		public class MyDialog : Dialog
		{
			public MyDialog()
			{
				this.Width = 200;
				this.Height = 100;
				Title = "MyDialog";
				Padding = 12;
				BackgroundColor = Colors.Yellow;
				var btn = new Button { Text = "Click me" };
				btn.Click += (sender, e) =>
				{
					new MyDialog2().ShowModal();
				};
				Content = btn;
			}
		}

		public class MyDialog2 : Dialog
		{
			public MyDialog2()
			{
				this.Width = 200;
				this.Height = 100;
				Title = "MyDialog2";
				Content = new StackLayout
				{
					HorizontalContentAlignment = HorizontalAlignment.Stretch,
					VerticalContentAlignment = VerticalAlignment.Stretch,
					Padding = 12,
					BackgroundColor = Colors.Pink,
					Items =
					{
						new StackLayoutItem(new Button { Text = "I'm not centered :(" }, true)
					}
				};
			}
		}
	}
}
```

## Specifications

  - Version: commit d6260d4
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13

**Comment by msasso69** [comment]
I'm afraid it's even worse than I thought: I have cases where I have StackLayout controls with 12 pixels of padding at the bottom even if no padding is set at all! :(

**Comment by cwensley** [comment]
Hey @msasso69, 

Thanks for reporting the issue!  Looks like a bug was introduced recently that caused this.  It was due to the logic that adds the positive/negative buttons at the bottom.

This should now be fixed, give it a go and let me know if you still see any problems!
