### ISSUE TITLE
Binding SelectedIndex in RadioButtonList when DataStore is also binding crashes

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#1385]
## Expected Behavior
SelectedIndex value is ignored until the DataStore has elements

## Actual Behavior
Crashes on RadioButtonList.SelectedIndex_set()

## Steps to Reproduce the Problem

  1. Create a RadioButtonList in XAML
  2. Bind both DataStore and SelectedIndex

## Specifications

  - Version: 2.4.1
  - Platform(s): WPF, Gtk3, XamMac
  - Operating System(s): Windows 10, ArchLinux, macOS Mojave

**Comment by cwensley** [comment]
This is actually expected.  SelectedIndex must be specified _after_ the DataStore so that it is valid.  It is not valid to set the SelectedIndex to an invalid value.
