### ISSUE TITLE
Can't Install Vs/Mac Extensions Because of Hard Dependency on Old Versions

### ISSUE THREAD

**Issue by turbo** [picoe/Eto#1387]
## Expected Behavior

MonoDevelop extension 2.4.1.1 should install.

## Actual Behavior

Installation is rejected by VS, because the extensions require older versions of dependencies. See:

<img width="460" alt="Screenshot 2019-05-06 at 12 49 28" src="https://user-images.githubusercontent.com/8023543/57220985-aa889e80-6ffd-11e9-9b56-59485a0fad64.png">

## Steps to Reproduce the Problem

  1. Download extensions
  2. Try to install

## Specifications

  - Version: N/A (extension version: 2.4.1.1)
  - Platform(s): N/A
  - Operating System(s): macOS 10.14.3
  - VS version: 8.0 Build 869

**Comment by turbo** [comment]
Bump, cause this is still an issue

**Comment by cwensley** [comment]
Hey @turbo, thanks for submitting the issue.  It has already been reported with #1366.  Please subscribe to that issue for further updates.

With VS for Mac, extensions can't specify a "soft" dependency, so it needs to be updated and recompiled for the new version.
