### ISSUE TITLE
[Mac] Resource based localization ignored

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#1393]
## Expected Behavior
Takes strings from appropriate language/Assembly.resources.dll

## Actual Behavior
Doesn't

## Steps to Reproduce the Problem

  1. Create a localized resource file and set strings
  2. Change language in System Preferences

Please note this works in Linux and Windows

## Specifications

  - Version: 2.4.1.1
  - Platform(s): XamMac
 - Operating System(s): macOS 10.14

**Comment by cwensley** [comment]
Hey @claunia, I think this is fixed in Eto 2.5, could you give it a try?

**Comment by cwensley** [comment]
This should be fixed in Eto 2.5.  In 2.4.1 it did not copy the associated dll's in the right spot in the .app bundle.
