### ISSUE TITLE
WPF: TabControl.SelectedIndex being set does not update control in UI

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1395]
## Expected Behavior

Setting TabControl.SelectedIndex should switch to the TabPage on all platforms. Under the current Eto 2.4 / 2.5 code, this isn't working.

## Actual Behavior

Under WPF, the TabControl takes the selected index value, but does not update the representation in the UI. No exceptions or errors are raised.

## Steps to Reproduce the Problem

  1. Example code attached. Load, build and run.
  2. Navigate to the second page of the inner tab control and double-click the label.
  3. On macOS, the first page of the nested tab control will become selected. On WPF, no change in the selected index tab controls is evident.

## Code that Demonstrates the Problem

Attached project
[tabcontrol_test.zip](https://github.com/picoe/Eto/files/3170426/tabcontrol_test.zip)

## Specifications

  - Version: 2.4, head
  - Platform(s): WPF
  - Operating System(s):Windows 10

**Comment by cwensley** [comment]
Thanks for reporting the issue and providing a test project, @philstopford!  It really helps.

**Comment by cwensley** [comment]
Add this line to your MouseDoubleClick handler:

`e.Handled = true;`

.. and it will work.  The problem is that when you don't handle the mouse event, the default implementation is executed, which prevents the TabControl from changing the tabs.
