### ISSUE TITLE
ListBox SelectedXBinding throw exceptions in XAML

### ISSUE THREAD

**Issue by SilkStack** [picoe/Eto#1398]
## Expected Behavior

When using XAML to bind the current selected item/index/key to a datacontext said value is bound and updated when a new selection is made in the UI.

## Actual Behavior

A TargetInvocationException is thrown stating: "Cannot set unknown member '{http://schema.picoe.ca/eto.forms}ListBox.SelectedValueBinding'"

## Steps to Reproduce the Problem

  1. Create a .xeto form in XAML
  2. Add a ListBox with a SelectedKeyBinding property like: SelectedKeyBinding="{Binding SelectedItemKey}" with an appropriate backing property on the datacontext object
  3. Start a debug session that attempts to load the .xeto form

## Code that Demonstrates the Problem

```
<?xml version="1.0" encoding="UTF-8" ?>
<Panel
    xmlns="http://schema.picoe.ca/eto.forms"
    xmlns:drawing="clr-namespace:Eto.Drawing;assembly=Eto"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>
    <ListBox
        DataStore="{Binding ActiveFonts}"
        ItemTextBinding="{Binding FullName}"
        SelectedKeyBinding="{Binding SelectedFont}"
    />
</Panel>
```

## Specifications

  - Version: 2.5.0-ci-10206
  - Platform(s): Mac64
  - Operating System(s): OSX Mojave

**Comment by cwensley** [comment]
Hey @SilkStack,

Try using `SelectedKey="{Binding SelectedFont}"` instead.  SelectedKeyBinding is used to set up MVVM bindings via code, and only has a getter.

**Comment by SilkStack** [comment]
Thanks, that worked nicely.
