### ISSUE TITLE
[Mac] Should About item be in the Help menu?

### ISSUE THREAD

**Issue by Berrysoft** [picoe/Eto#1402]
https://github.com/picoe/Eto/blob/af970beb104de3a3d70723b59ac814677d3a57f0/src/Eto.Mac/Forms/Menu/MenuBarHandler.cs#L87

The AboutItem is put into the ApplicationMenu. Should it be in the HelpMenu?

**Comment by claunia** [comment]
Not in Mac. In Mac it always goes into the ApplicationMenu, in all applications, is part of the Apple Human Interface Guidelines.

**Comment by Berrysoft** [comment]
Oh, I see. Thanks!
