### ISSUE TITLE
Wait can this framework convert a winforms app to a etoforms app?

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#1406]
I was reading up on this.. 
https://github.com/picoe/Eto/wiki/Embedding-Eto.Forms-in-an-existing-application
 and I was wondering if its possible to convert a whole winforms app to a etoforms app with `.ToEto()`

if so that would be amazing because this I can just build a winforms app and convert it before running.

**Comment by cwensley** [comment]
Hey @Shadowblitz16,

Thanks for the inquiry, but no this is not possible (sorry, no magic pill here).  The .ToEto() extension is so you can use existing WinForms (or WPF, Xamarin.Mac, Gtk) components inside Eto, but _only_ when running on that particular platform.  So using .ToEto() would allow you to embed WinForms inside an Eto window, _only_ when running using Eto.WinForms on Windows.

Hope this helps clear the confusion.

Cheers!
Curtis.

**Comment by Shadowblitz16** [comment]
ok thankyou
