### ISSUE TITLE
Form.Location ignored in Linux/GTK

### ISSUE THREAD

**Issue by pablocar80** [picoe/Eto#1413]
Hello! I have a "hello world" app in Linux/GTK, and the "location" property gets completely ignored. I'm using the latest version available in Nuget.

## Expected Behavior
The form created should be positioned in the coordinates set in the Location property.

## Actual Behavior
The form created gets positioned instead in the top-left corner (0, 0).

## Steps to Reproduce the Problem

  1. Create a new project in Linux
  2. Add Eto.Forms and Eto.Platform.GTK packages
  3. Copy and paste the code below

## Code that Demonstrates the Problem

```
using Eto.Drawing;
using Eto.Forms;

namespace TestCore22
{
    internal static class Program
    {
        public static void Main(string[] args)
        {
            new Application().Run(new MyForm());
        }
    }

    internal sealed class MyForm : Form
    {
        public MyForm()
        {
            Title = "hello on the top-left corner";
            Location = new Point(1000, 800);
            Size = new Size(500, 500);
        }
    }
}
```

## Specifications

  - Version: 2.4.1 on Net Core 2.2
  - Platform(s): Eto.Platform.GTK
  - Operating System(s): Fedora 30

**Comment by SlowLogicBoy** [comment]
Can't reproduce this on Windows:

Version: 2.4.1 on Net Core 2.2
Platform(s): Eto.Platform.GTK (mingw-w64-x86_64-gtk3 3.22.29-1)
Operating System(s): Windows 10 x64

Edit:
mingw-w64-x86_64-gtk3 3.24.8-1 also works fine

**Comment by pablocar80** [comment]
I found the issue moving from Windows to Linux, so yes, no issues in Windows. What is mingw?

**Comment by SlowLogicBoy** [comment]
[Minimalist GNU for Windows](http://mingw.org/)

**Comment by harry-cpp** [comment]
Are you by any chance running your DE under Wayland? If you are, that is your issue, Wayland does not allow windows to be positioned from code, nothing an app can do about that.

**Comment by Itaros** [comment]
Why it is fail-silently then?

**Comment by harry-cpp** [comment]
> Why it is fail-silently then?

What would you expect to occur, an exception? That would be silly.

**Comment by Itaros** [comment]
Or at least logspam. Considering GTK# does it even in normal operation.

**Comment by pablocar80** [comment]
How do other apps manage to create a screen-centered splash screen in GTK?

**Comment by harry-cpp** [comment]
https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindowPosition

**Comment by pablocar80** [comment]
Awesome, and it's possible to specify GTK_WIN_POS_CENTER from Eto?

**Comment by cwensley** [comment]
To specify that from Eto, you can do this as a native style:

```c#
Style.Add<Eto.GtkSharp.Forms.FormHandler>("mystyle", h => h.Control.SetPosition(Gtk.WindowPosition.Center));
```

then for your form that you want to center:
```c#
var myForm = new Form { Style = "mystyle" };
```
