### ISSUE TITLE
Add strong name signing

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1418]
It would be nice if all Eto assemblies could be strong named. Some older .NET Framework 4.x applications (like mine) still need this feature for e.g. Sandboxing and such assemblies need also a strong named version of all dependencies. Currently I'm compiling Eto myself from source but it would be much easier to be able to use the provided packages.

As strong names are only meant to provide identity, it would be no security problem to check in the key to the repo. (See [here](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies) on the official Microsoft docs).

Adding the signing should not be problematic; my self-compiled version runs just fine.

Thanks in advance!

**Comment by cwensley** [comment]
Thanks for the request.  I'd like to strong name Eto, though I hesitate as it would be an ABI breaking change.  This might have to wait for 3.0, but I'll investigate for a 2.x release to see if it's possible.

**Comment by ManuelHu** [comment]
Great, thanks!

**Comment by ManuelHu** [comment]
I don't know if this is still needed, especially with more and more people migrating to .NET Core. 

At least, I now can use the normal Eto nuget packages without strong naming as I don't use .NET Sandboxing any more.

If you want to, you can close this issue.
