### ISSUE TITLE
Nesting items within TreeGridView by drag/drop

### ISSUE THREAD

**Issue by JonSargent** [picoe/Eto#1421]
Hi all,

I'd like the user to be able to nest items within a TreeGridView control by dragging one or more items and dropping them onto the desired parent item.  Is there a built in mechanism for this?  If not, what's the best way to set one up?  Advice or a simple example would be lovely :)

Thanks,

Jon

**Comment by cwensley** [comment]
Hey @JonSargent,

No there is no built-in mechanism for this.  You need to start your drag using `myTreeGrid.DoDragDrop()` along with the item info in the DataObject, and then handle DragOver & DragDrop events to handle dropping the item, moving it in code, then refreshing the appropriate node(s).

**Comment by cwensley** [comment]
Closing as I believe this was answered.  Please let me know if there are other questions.
