### ISSUE TITLE
Scrolling not working on GTK2/Linux

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#1433]
First of all, I'm sorry but I don't have time to follow the procedures for reporting a bug.

Just want to inform that there seems to be a bug with Gtk2 on all currently available preview versions. 

Scrolling panels are not working on Gtk2/Linux. You can't scroll the panels, no scrollbars are shown. Tried many versions including the latest preview one but had to go all the way back to 2.4.1 so it would work again as expected.

Regards
Daniel

**Comment by cwensley** [comment]
Hey @DanWBR, thanks for the report but I'll at least need to know what Operating System and OS Version you are running this on.

**Comment by DanWBR** [comment]
@cwensley I'm testing it on Ubuntu 14.10 64-bit, but I have at least one extra report of the bug: https://sourceforge.net/p/dwsim/discussion/linux_newui/thread/198fe744a4/

**Comment by cwensley** [comment]
@DanWBR thanks.  I'll look into it.

**Comment by DanWBR** [comment]
@cwensley I'm not sure but I think it was working on 2.5.0-ci-10123. Looking at the commits I've saw that you did some changes to the gtk backend after that.

**Comment by cwensley** [comment]
Closing as it looks like the latest version is working.  Please reopen or comment further if there is still something missing.  Thanks for your feedback!
