### ISSUE TITLE
Can not open a ContextMenu at an arbitrary location

### ISSUE THREAD

**Issue by GeneThomas** [picoe/Eto#1437]
Thanks for Eto.Forms.

I am implementing the [≡] menu button in an application with a large Canvas so I want the ContextMenu to open at the location inside the selected item (drawn graphics not Widgets). ContextMenut.Show() only allows one to specify the Control not the co-ordinates and there does not seem to be a way to ‘warp’, that is set the mouse pointer location either.

## Specifications

  - Version: 2.4.0.0
  - Platform(s): WinForms
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @GeneThomas,

Thanks for submitting the issue!

You can show the ContextMenu at a specific screen location or a location relative to a control in 2.5 with some [new apis](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/Menu/ContextMenu.cs#L99).  The beta is on nuget or you can use the latest develop branch on myget (see link in readme).  Give it a try!

To set the mouse position, you can use `Mouse.Position`, which should be available in 2.4.1.
