### ISSUE TITLE
does any border thickness or hide border of button properties?

### ISSUE THREAD

**Issue by chenjeff622** [picoe/Eto#1439]
as title . anyone can help?

**Comment by pablocar80** [comment]
Hi, I run into this issue converting a WinForms app where buttons had no borders. The only way I found to fix this is by using the platform-specific handlers for buttons on Windows. On Linux, the default borders looked acceptable. More information below:

https://github.com/picoe/Eto/wiki/Styling

**Comment by cwensley** [comment]
I think this has been answered sufficiently, please comment further if you need more info.

You can use platform-specific styles do do things with particular platforms that aren't supplied by the Eto api, such as a Button border.

Alternatively, use Label or Drawable with the MouseDown/MouseUp events.
