### ISSUE TITLE
Wpf - crashes with DataGrid

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1448]
I'm receiving crashreports from clients with the following stacktraces:
```
System.NullReferenceException
bei System.Windows.Controls.DataGridRow.RestoreAttachedItemValue(DependencyObject objectWithProperty, DependencyProperty property)
   bei System.Windows.Controls.DataGridRow.SyncProperties(Boolean forcePrepareCells)
   bei System.Windows.Controls.DataGridRow.PrepareRow(Object item, DataGrid owningDataGrid)
   bei System.Windows.Controls.DataGrid.PrepareContainerForItemOverride(DependencyObject element, Object item)
   bei System.Windows.Controls.ItemsControl.MS.Internal.Controls.IGeneratorHost.PrepareItemContainer(DependencyObject container, Object item)
   bei System.Windows.Controls.VirtualizingStackPanel.InsertContainer(Int32 childIndex, UIElement container, Boolean isRecycled)
   bei System.Windows.Controls.VirtualizingStackPanel.AddContainerFromGenerator(Int32 childIndex, UIElement child, Boolean newlyRealized, Boolean isBeforeViewport)
   bei System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, 

```
The stacktrace does not include my code oder eto-code, so hard to say, what triggered it.

I have no idea, what is happening there, seems like a hard to reproduce random thing. Myself I never had this, but we just released an app which is using eto and now we receive this error quiet often from users. Any idea what we can do?

**Comment by cwensley** [comment]
Sorry, @TomQv, I'm not sure what would cause it.  All I can suggest is to collect data on what version of .NET they are using.  There have been many fixes/changes with WPF with the various .NET framework versions so perhaps it could be because they have an older version of .NET installed.

**Comment by cwensley** [comment]
Closing as there's nothing that can be done here without more info and/or a repro.  Sorry I can't be more helpful!  If you do find anything that can help please comment/re-open.

**Comment by TomQv** [comment]
This specific crash didn't occur any more since a couple of weeks, maybe with some net-updates it was fixed. We are using 4.8 in the meanwhile. But we have another exception also regarding with DataGrid coming now quiet often -> new issue #1555
