### ISSUE TITLE
Changing DataContext on Form doesn't update Splitter Panels

### ISSUE THREAD

**Issue by luksal** [picoe/Eto#1450]
## Expected Behavior
Changing the DataContext on a Form should update DataContext on all Child Elements.

## Actual Behavior
When using a Splitter, the DataContext on the Panel1 and Panel2 isn't updated.

## Code that Demonstrates the Problem

```
public class MyForm : Form
{
	public MyForm()
	{
		var textBox = new TextBox();
		textBox.TextBinding.BindDataContext((MyModel m) => m.MyString);

		Content = new Splitter
		{
			Panel1 = textBox,
		};

		// set the view model for the form and all child controls
		var model = new MyModel { MyString = "Hello!" };
		DataContext = model;
	}
}

// typically implemented view model
public class MyModel : INotifyPropertyChanged
{
	string myString;
	public string MyString
	{
		get { return myString; }
		set
		{
			if (myString != value)
			{
				myString = value;
				OnPropertyChanged();
			}
		}
	}

	void OnPropertyChanged([CallerMemberName] string memberName = null)
	{
		PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(memberName));
    }
	public event PropertyChangedEventHandler PropertyChanged;
}
```

## Specifications
Tested only with Mac & Windows Platforms
  - Version: 2.5.0-beta.1
  - Platform(s): WPF, WinForms, XamMac
  - Operating System(s): Windows 10, macOS 10.14

**Comment by cwensley** [comment]
Thanks @luksal for reporting the issue!  You're right, it should propagate through the splitter.

**Comment by cwensley** [comment]
This appears to be working with the latest 2.5.0 release.  Thanks for reporting the issue!  Please let me know if it isn't working for you.
