### ISSUE TITLE
Documentation: PixelFormat.Format24bppRgb

### ISSUE THREAD

**Issue by nrother** [picoe/Eto#1457]
The documentation for [PixelFormat.Format24bppRgb](http://api.etoforms.picoe.ca/html/T_Eto_Drawing_PixelFormat.htm) states: 

```
24-bits (4 bytes) per pixel, ordered by Red in the highest order, followed by Green, and Blue.
```

24bits are not 4 bytes. Which one is correct?

**Comment by ItEndsWithTens** [comment]
I believe 24 bits is correct, and as of commit 5ec5b7bbe6e693565e98d34577f82568c14bd893 that comment has been fixed; I imagine that API docs site just needs to be regenerated, but I'm not familiar with how that's done. I gather it's one of the "build-help" scripts in [the build directory](https://github.com/picoe/Eto/tree/develop/build), but I've never had occasion to experiment with those myself.

**Comment by nrother** [comment]
Oh, I should have look in the `develop` branch. I thinks it better to only update the documentation when 2.5.0 is released, otherwise the documentation will be more recent than the default NuGet package, which might be confusing.
