### ISSUE TITLE
[Mac] the Width of a DrawableCell is not preserved after manually resizing it and adding a child to a node of the tree

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1459]
## Expected Behavior
the width of a DrawableCell in a TreeGridView is not preserved after manually resizing it and after adding a child to the node in tree

## Actual Behavior
When adding a node to a node already in the tree, the width of a DrawableCell column is not preserved (if the column had previously been resized)

Note the this only happens if adding child nodes to nodes already in the tree. If I add a node at root level (directly to the model bound to the DataStore) the size is preserved.

## Steps to Reproduce the Problem

  1. run the report, you'll get this:
![image](https://user-images.githubusercontent.com/21080030/62398547-5435e800-b579-11e9-9579-fcce087998cd.png)
  2. expand the tree
![image](https://user-images.githubusercontent.com/21080030/62398590-7465a700-b579-11e9-89ee-bf31beff6b22.png)
  3. enlarge the width of the tree column
![image](https://user-images.githubusercontent.com/21080030/62398656-9d863780-b579-11e9-8258-7b8480e2f1e3.png)
 4. click the button "Add node"
![image](https://user-images.githubusercontent.com/21080030/62398716-c3abd780-b579-11e9-9b3e-9e2ee43760cf.png)
as you can see the width is restored to its original size (WRONG)

Other anomalie:
 5. uncomment the following line 
```
	//root.Expanded = true;
```
and restart from step 1., at step .4 you'll get this:
![image](https://user-images.githubusercontent.com/21080030/62399124-0c17c500-b57b-11e9-8b71-09eaa78d6061.png)
that is an even stranger behaviour but I guess strongly related with the previous one

The trivial workaround is to wrap the ReloadItem with some code like this:
```
	int width = tree.Columns[0].Width;
	tree.ReloadItem(root);
	if (tree.Columns[0].Width != width)
		tree.Columns[0].Width = width;
```

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Drawing;
using Eto.Forms;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyForm());
		}

		public class MyForm : Form
		{
			TreeGridItemCollection model;
			TreeGridView tree;
			static GridColumn column;
			TreeGridItem root;

			public MyForm()
			{
				this.Width = 500;
				this.Height = 250;
				tree = new TreeGridView();
				root = new TreeGridItem();

				if (Platform.Supports<DrawableCell>())
				{
					var drawableCell = new DrawableCell();
					drawableCell.Paint += (sender, e) =>
					{
						string text = "sfsgh rthysdgs rsths wetd shrswe tsdvwsdwe dsgewwe dsr";
						e.Graphics.DrawText(SystemFonts.Label(), Colors.Black, (float)0, (float)-8, text);
					};
					tree.Columns.Add(column = new GridColumn
					{
						DataCell = drawableCell, AutoSize = false, Width = 600 
					});
				}

				model = new TreeGridItemCollection();
				tree.DataStore = model;
				model.Add(root);
				root.Children.Add(new TreeGridItem());
				root.Children.Add(new TreeGridItem());
				root.Children.Add(new TreeGridItem());
				//root.Expanded = true;
				tree.ReloadData();

				tree.Columns[0].Width = 200;

				Button button1 = new Button() { Text = "Add node" };
				button1.Click += (sender, e) =>
				{
					TreeGridItem node = new TreeGridItem();
					root.Children.Add(node);
					tree.ReloadItem(root);
				};

				Content = new StackLayout
				{
					HorizontalContentAlignment = HorizontalAlignment.Stretch,
					Items =
					{
						new StackLayout
						{
							Items = { button1 }
						},
						new StackLayoutItem(new StackLayout
						{
							HorizontalContentAlignment = HorizontalAlignment.Stretch,
							VerticalContentAlignment = VerticalAlignment.Stretch,
							Items =
							{
								new StackLayoutItem(tree, true),
							}
						}, true)
					}
				};
			}
		}
	}
}
```

## Specifications

  - Version: commit ab680e6 (13 June 2019)
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13

**Comment by cwensley** [comment]
Thanks for reporting the issue.  I'll investigate to see if this is still a problem.

**Comment by cwensley** [comment]
@msasso69 thanks again for reporting the issue and especially the sample to reproduce it.  Both the issues you have reported should now be fixed. Give it a try!

**Comment by msasso69** [comment]
Thanks for fixing the issue. Works like a charm now!
