### ISSUE TITLE
Error:t this Template attempted to load componet

### ISSUE THREAD

**Issue by GeeSuth** [picoe/Eto#1463]
i'm try to use Eto.Forms for first time 
My VS version is Community 2017 
first i install Eto from **Tools** > **Extensions and updates** > searching for **Eto.Forms** and install successful
restart my vs and try to create project by choose ### new project > **C#** > **Eto.Forms Application** 
Okay And the message popup 

![Untitled](https://user-images.githubusercontent.com/10328974/62684102-cc831b80-b974-11e9-978b-e8162af68927.png)

resolved failed :
run vs like administrator

**Comment by cwensley** [comment]
@GeeSuth this is possibly because you don't have all the necessary VS 2017 components installed.  I'm not quite too sure what those are though.  Possibly adding the .NET Core stack would help?

**Comment by cwensley** [comment]
Hey @GeeSuth, the VS 2017 extension is no longer supported now that the VS 2019 extension is available.  It should hopefully not have this problem.  Give it a try!  It's in the extension gallery.  Please file any issues you run into.
