### ISSUE TITLE
NumericMaskedTextBox<T> suspress seperator if CultureInfo.CurrentCulture use comma

### ISSUE THREAD

**Issue by fleixi** [picoe/Eto#1468]
## Expected Behavior

Set Value of NumericMaskedTextBox<T> to numeric value like 0.9 sould be displayed as 0,9 if  CultureInfo.CurrentCulture use comma as separator

## Actual Behavior

Value is displayed as 09 in this example. 42.357 is displayed as 42357

## Steps to Reproduce the Problem

  1. create new NumericMaskedTextBox<double> { Value = 0.9 }
  2. run dialog
  3. inspect output on display

## Specifications

  - Version: 2.4
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @fleixi, thanks for reporting the issue! Have you tried 2.5 (it's in RC). I doubt it has been fixed but it would be good to verify it.

Cheers!
Curtis.
