### ISSUE TITLE
Error with Quick start demo

### ISSUE THREAD

**Issue by bobbyski** [picoe/Eto#1476]
## Expected Behavior

Expect the template to display a hello world demo (my first test of Eto framework. (following the guide here: [Quick Start](https://github.com/picoe/Eto/wiki/Quick-Start)

## Actual Behavior

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')

## Steps to Reproduce the Problem

On Mac with latest VS
  1. dotnet new -i "Eto.Forms.Templates::*"
  2. dotnet new etoapp -sln -xm -m xaml 
  3. nuget restore
  4. msbuild
  5. Load in visual Studio and change configration target (I chose 10.12)
  6. Run application (the error above occurs before any window is shown.

NOTE: This is my first Eto app and my first use of Xamarin.Mac so this may be a newbie issue

## Code that Demonstrates the Problem

The default code generated by the template

## Specifications

  - Version: 2.4.1
  - Platform(s): XamMac, etc
  - Operating System(s): Mac OS X 10.14.6

**Comment by cwensley** [comment]
Hey @bobbyski, I'm not seeing the same issue given the same steps you took.  

I am using VS for Mac 8.3, so perhaps the issue has been fixed with that version?

**Comment by bobbyski** [comment]
I am using 8.3 build 1805

**Comment by bobbyski** [comment]
Here is the full application log - only a couple more lines:

Loaded assembly: /Users/bobby/Documents/learning/eto/eto.XamMac/bin/Debug/eto.XamMac.app/Contents/MonoBundle/eto.XamMac.exe
Loaded assembly: /Users/bobby/Documents/learning/eto/eto.XamMac/bin/Debug/eto.XamMac.app/Contents/MonoBundle/Eto.dll
Resolved pending breakpoint at 'Program.cs:10,1' to void eto.XamMac.MainClass.Main (string[] args) [0x00001].

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')

I did notice some warnings:
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3243: No way to resolve conflict between "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" and "eto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. (MSB3243) (eto.Desktop)
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3243: No way to resolve conflict between "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" and "eto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. (MSB3243) (eto.XamMac)
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. (MSB3276) (eto.XamMac)
/Users/bobby/Documents/learning/eto/eto.XamMac/MMP: Warning MM2006: Native library 'libSystem.B.Dylib' was referenced but could not be found. (MM2006) (eto.XamMac)

i tried editing the csproj files with same results - the last one seems like a good candidate to be the problem

**Comment by cwensley** [comment]
@bobbyski ah, it looks like you named your application "eto", which conflicts with Eto.dll.  You should name it something else.  By default, when using `dotnet new`, it takes the folder you are in as the name of the project.

**Comment by bobbyski** [comment]
I feel stupid now - but that was it

**Comment by bobbyski** [comment]
Here is the full application log - only a couple more lines:

Loaded assembly: /Users/bobby/Documents/learning/eto/eto.XamMac/bin/Debug/eto.XamMac.app/Contents/MonoBundle/eto.XamMac.exe
Loaded assembly: /Users/bobby/Documents/learning/eto/eto.XamMac/bin/Debug/eto.XamMac.app/Contents/MonoBundle/Eto.dll
Resolved pending breakpoint at 'Program.cs:10,1' to void eto.XamMac.MainClass.Main (string[] args) [0x00001].

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000007 from typeref (expected class 'Eto.Platforms' in assembly 'Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null')

I did notice some warnings:
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3243: No way to resolve conflict between "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" and "eto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. (MSB3243) (eto.Desktop)
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3243: No way to resolve conflict between "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" and "eto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Eto, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. (MSB3243) (eto.XamMac)
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. (MSB3276) (eto.XamMac)
/Users/bobby/Documents/learning/eto/eto.XamMac/MMP: Warning MM2006: Native library 'libSystem.B.Dylib' was referenced but could not be found. (MM2006) (eto.XamMac)
