### ISSUE TITLE
[WPF] Tree scroll position jumps to selection on collapse/expand of another item

### ISSUE THREAD

**Issue by brtn** [picoe/Eto#1479]
I am guessing this may be useful when the selected/focused item is being edited but when you are not, it is pretty annoying. What is the reason for this and can we make it configurable?

This is the line that causes the jump:
https://github.com/picoe/Eto/blob/4e53ea91de7dd8b6f842969e6edfcad28e377af0/src/Eto.Wpf/Forms/Controls/TreeGridViewHandler.cs#L142

**Comment by cwensley** [comment]
Thanks for reporting the issue!
