### ISSUE TITLE
macOS bundle not launch-able

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1487]
## Expected Behavior

Compiled .app bundle is launch-able without error.

## Actual Behavior

.app bundle cannot be launched : macOS 10.14.6 complains that the application is damaged or incomplete.

![Screen Shot 2019-10-10 at 11 44 29 AM](https://user-images.githubusercontent.com/1983851/66584580-6755cd00-eb53-11e9-8389-1874f478c25b.png)

## Steps to Reproduce the Problem

  1. Compile the attached test case
  2. Try and run the generated .app through Finder (VS for mac silently fails)
  3. Note the error message
  4. Within a terminal, dive into the .app bundle Contents/MacOS folder.
  5. Manually launch the temp executable in the MacOS folder. The application will run.

## Code that Demonstrates the Problem

[temp.zip](https://github.com/picoe/Eto/files/3713402/temp.zip)

## Specifications

  - Version: 2.5-rc4
  - Platform(s): Mac 
  - Operating System(s): 10.14.6

**Comment by cwensley** [comment]
This is because your csproj has these lines:

```
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
```

This tells it to use the startup object (the .exe), instead of letting Eto.Platform.Mac64's targets file specify the launch .app bundle.

**Comment by cwensley** [comment]
Hm, sorry just realized you're also saying it doesn't launch if you double click the .app from Finder (I just tried running from VS).  It is working correctly for me (I'm on macOS 10.15 though).. did you do a full clean/rebuild?

**Comment by cwensley** [comment]
Also what version of VS for Mac and mono do you have installed?  I currently have the latest stable versions (8.3.4 and 6.4.0.208 respectively)

**Comment by philstopford** [comment]
Filesystem related oddness. This can be closed, I think.
