### ISSUE TITLE
[Gtk] Custom control scroll wheel events throw NotSupportedException

### ISSUE THREAD

**Issue by ItEndsWithTens** [picoe/Eto#1491]
I believe I know some of the solution for this, but I'm not sure if it's as simple as it sounds, so I've gone with an issue instead of a pull request.

## Expected Behavior
A custom control, running on the Gtk platform, allows use of the scroll wheel.

## Actual Behavior
Scrolling over said custom control throws a System.NotSupportedException.

## Steps to Reproduce the Problem

  1. Check out the master branch of https://github.com/ItEndsWithTens/Eto.Veldrid
  2. Build and run the TestEtoVeldrid.Gtk project
  3. Scroll your scroll wheel over the rotating colored rectangle, and you should see an exception

## Specifications

  - Version: 2.5.0-rc.4
  - Platform(s): Gtk
  - Operating System(s): Linux Mint 19.2, Ubuntu 16.04 (both with all updates as of October 15th, 2019)

The exception seems to come from [GtkControlConnector.HandleScrollEvent](https://github.com/picoe/Eto/blob/98542b0c387238903ccc4e18a98b128329a7e028/src/Eto.Gtk/Forms/GtkControl.cs#L505), as the default switch case. That method accommodates the scroll directions down, left, right, and up, but not the fifth one, "smooth", which my systems seem to use.

In my brief, informal testing, a fifth switch case does the trick:
```csharp
case Gdk.ScrollDirection.Smooth:
  delta = new SizeF((float)args.Event.DeltaX, (float)args.Event.DeltaY);
  break;
```

Another part of the problem is that the 2.5.0-rc.4 Nuget package for Eto.Platform.Gtk, when restored in both of my test environments, brings in GtkSharp version 3.22.24.29, while the first version that supports retrieving the DeltaX and DeltaY properties of a Gdk.EventScroll is [3.22.24.36](https://github.com/GtkSharp/GtkSharp/releases/tag/3.22.24.36) (released shortly after [this issue](https://github.com/GtkSharp/GtkSharp/issues/37)).

I see that [Eto.Gtk.csproj already uses a newer version](https://github.com/picoe/Eto/blob/98542b0c387238903ccc4e18a98b128329a7e028/src/Eto.Gtk/Eto.Gtk.csproj#L20), so a pull request to add that one switch case wouldn't totally solve the problem, and I thought it warranted discussion first. Is it expected that I get a transitive dependency on an older version of GtkSharp when installing a release candidate? I wouldn't put it past me to just be missing the finer points of Nuget package management, honestly.

EDIT: Ha! I swear it's always moments after I post things like this that I have an epiphany of some sort. This time, it was the thought to check the .nuspec file for Eto.Platform.Gtk. Sure enough, it still has the older version [specified as a dependency](https://github.com/picoe/Eto/blob/98542b0c387238903ccc4e18a98b128329a7e028/build/nuspec/Eto.Platform.Gtk.nuspec#L28), which at least explains that part of my dilemma.

**Comment by cwensley** [comment]
Hey @ItEndsWithTens, thanks for reporting the issue and researching a good fix!  This should now be fixed.

**Comment by ItEndsWithTens** [comment]
Yep, everything's good as of 2.5.0-ci-10357 (commit 937a099), thanks!
