### ISSUE TITLE
Missing Eto.XamMac2.dll

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1495]
I am missing Eto.XamMac2.dll while building PabloDraw for Mac and do not seem to be able to generate it.

Can someone zip it up for me and post it here?

Much appreciated.

**Comment by cwensley** [comment]
@LaraSQP Try using the Eto.Platform.XamMac2 NuGet package instead.  You also need to build the XamMac version on a Mac using VS for Mac.

Hope this helps!

**Comment by LaraSQP** [comment]
Makes sense. Thank you very much for the quick reply.
