### ISSUE TITLE
Nuget Package compatibility 

### ISSUE THREAD

**Issue by Crogarox** [picoe/Eto#1496]
When trying to use the dropbox api on a Mac, viva their nuget package, I get this error. 
System.Configuration.ConfigurationErrorsException
"Error Initializing the configuration system."

Just trying their tutorials will cause this error in a Eto solution runnning as a Mac platform. https://www.dropbox.com/developers/documentation/dotnet#tutorial . This is actually the same for several other nuget packages too. Is there anyway around this? I've read that it might be trying to read the app.conf or system.conf, which would not exist on the mac solution.

**Comment by cwensley** [comment]
Hey @Crogarox, this issue has been [reported before](https://github.com/picoe/Eto/search?q=Error+Initializing+the+configuration+system&type=Issues).  Using Eto 2.5 should fix the issue (there are prerelease packages on nuget.org).

Hope this helps!

**Comment by Crogarox** [comment]
It does, thank you very much.
