### ISSUE TITLE
Permission to add a 'workarounds' section to the wiki

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1503]
As I battle my way through eto, I have come to discover some of its beautiful madness.

I would like explicit permission from Curtis to add a 'workarounds' section to the wiki where to report these strange discoveries so that they might lighten the burden of future adopters.

**Comment by cwensley** [comment]
Hey @LaraSQP,  thanks for asking!

Yes, you are very welcome to add a new wiki page and if we need to we can reorganize from there.

**Comment by LaraSQP** [comment]
Do you want me to run it by you before modifying the wiki or just go for it?

**Comment by cwensley** [comment]
Naw, just go for it and perhaps create an issue for review so I know when you're done?

It would be nice to have PR's for the wiki but alas there's no way to do that afaik.

**Comment by LaraSQP** [comment]
I will be adding workarounds as I find them.

The first one has to do with the Selection range in RichTextArea not working properly (Windows) with multiple lines of text and a workaround the problem.

**Comment by cwensley** [comment]
> The first one has to do with the Selection range in RichTextArea not working properly (Windows) with multiple lines of text and a workaround the problem.

Hm, are you using Eto 2.5?  There have been fixes revolving around this since 2.4.1.

**Comment by LaraSQP** [comment]
Good point.

I am using the default created by the vs2017 template.

I did check Nuget but it does not show a later version.

Is this a manual upgrade or...?

**Comment by LaraSQP** [comment]
Github also has 2.4.1 as the latest release.

**Comment by LaraSQP** [comment]
But I did a compile from source of Eto and have 2.5 dll's.

Drop in and replace seems kind of dirty and will be required to do so every build.

hmm.

**Comment by LaraSQP** [comment]
Nope.

Could not make it to work at all with my 2.5 dll's.

Darn.

**Comment by cwensley** [comment]
@LaraSQP if you create an issue with a repro then perhaps it can be looked at in more detail?  There is a small inconsistency between the platforms afaik (newline always at end vs. not), but it should always have a single \n character between lines in terms of positioning.

Also, 2.5-rc.4 is on nuget.org, you have to check the 'prerelease' checkbox to show it.

**Comment by LaraSQP** [comment]
Did not see anything in prerelease before, but I see it now. Update done.

Only issue came up:

`Warning MSB3270	There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference ``"C:\Users\user1\.nuget\packages\eto.platform.mac64\2.5.0-rc.4\lib\net45\MonoMac.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.`

Thanks for the reply and for the heads up regarding the EOL character. I was aware of the different flavors between systems but not that Eto have settled on a single \n character between lines. I was foolishly using `Environment.NewLine` thinking I was doing god's work and yet...

**Comment by LaraSQP** [comment]
Adding insult to injury, I am now getting a second warning:

`C:\Users\user1\.nuget\packages\eto.platform.mac64\2.5.0-rc.4\build\MacTemplate.targets(123,5): warning : Couldn't find mkbundle, so app bundle will require mono to be installed! Install mono from https://mono-project.com to bundle it with your app or set MonoPath to where it is installed.`

I'm all thumbs when it comes to these things.

Darn.

**Comment by cwensley** [comment]
@LaraSQP Those warnings are just that.. warnings.  All should be good even if you ignore those.

To give some explanation of each warning:

> Warning MSB3270	There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference 

This is because MonoMac.dll is build for x64 only since on macOS that is the only architecture that runs.  I intend to build it for "AnyCPU" in the future to get rid of this warning.

> warning : Couldn't find mkbundle

If you install mono on your (windows) development machine, you can now build a self-contained macOS .app bundle, which by default it only does it in Release mode.  This means you can build on Windows, and run the .app on Mac without having mono installed on the target system.

Hope this helps!
