### ISSUE TITLE
[Mac] cannot position a form to a desired location

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1509]
I'm implementing a help form that appears at the side of the main form that shrinks to make space to the help form.
Everything works fine on Windows (I'm using Eto-Wpf) but on Mac (I'm using XamMac2) I cannot position the help form (setting the helpForm.Location has no effect).

## Expected Behavior
When clicking on the button in the repro I should see the two forms aligned as in the second picture with the main form shrinked to make space to the second form.
![image](https://user-images.githubusercontent.com/21080030/68999209-a64b1100-08bd-11ea-9b4e-5eb3932e5361.png)
![image](https://user-images.githubusercontent.com/21080030/68999206-98958b80-08bd-11ea-950f-7c2635b96bea.png)
This would happen if setting mainForm.Location worked (like it does on windows).

## Actual Behavior
When clicking the button in the main form the second form is never positioned at the desired location but in the location it was present the last time it was opened.
![image](https://user-images.githubusercontent.com/21080030/68999204-83206180-08bd-11ea-9c7f-230e8710539e.png)

## Steps to Reproduce the Problem

  1. Run the repro that follows and click the button in the form. 

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Drawing;
using Eto.Forms;
using System.Collections.Generic;
using System.Linq;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);
			mainForm = new MainForm();
			helpForm = new HelpForm();
			app.Run(mainForm);
		}

		static bool helpVisible;
		static Form mainForm;
		static Form helpForm;

		public class MainForm : Form
		{
			public MainForm()
			{
				this.Width = 500;
				this.Height = 250;
				Button button1 = new Button() { Text = "Click Me!" };
				button1.Click += (sender, e) =>
				{
					if (helpVisible)
						HideHelp();
					else
						ShowHelp();
				};
				Content = button1;
			}
		}

		public class HelpForm : Form
		{
			public HelpForm()
			{
				this.Closing += HelpForm_Closing;
			}

			private void HelpForm_Closing(object sender, System.ComponentModel.CancelEventArgs e)
			{
				// do not really close the form, just hide it
				e.Cancel = true;
				HideHelp();
			}
		}

		public static void ShowHelp()
		{
			bool maximize = false;
			if (mainForm.WindowState == WindowState.Maximized)
			{
				mainForm.WindowState = WindowState.Normal; // THIS DOES NOT WORK ON MAC
				maximize = true;
			}

			// identify on which screen the mainform is
			IEnumerable<Screen> screens = Screen.Screens;
			Point loc = mainForm.Location;
			int screenIdx = -1;
			for (int i = 0; i < screens.Count(); i++)
			{
				RectangleF wa = screens.ElementAt(i).WorkingArea;
				if (loc.X >= wa.Left &&
					loc.X <= wa.Right &&
					loc.Y >= wa.Left &&
					loc.X <= wa.Right)
				{
					screenIdx = i;
					break;
				}
			}

			SizeF size;
			if (maximize)
				size = screens.ElementAt(screenIdx).WorkingArea.Size;
			else
				size = mainForm.Size;
			int width = (int)(size.Width * .75);

			if (maximize)
			{
				PointF loc2 = screens.ElementAt(screenIdx).WorkingArea.Location;
				mainForm.Location = new Point((int)loc2.X, (int)loc2.Y);
			}
			mainForm.Size = new Size(width, (int)size.Height);

			mainForm.Focus();
			helpForm.Size = new Size((int)size.Width - width, (int)size.Height);
			helpForm.Visible = true;
			helpForm.Location = new Point(mainForm.Location.X + width, mainForm.Location.Y); // THIS DOES NOT WORK ON MAC 
			helpVisible = true;
		}

		public static void HideHelp()
		{
			mainForm.Size = new Size(mainForm.Width + helpForm.Width, mainForm.Height);
			helpForm.Visible = false;
			helpVisible = false;
		}
	}
}
```

## Specifications

  - Version: last pull of Eto code the 25 of October 2019
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13

**Comment by msasso69** [comment]
Looking at the Eto code I noticed that the location is only set after the form has been loaded:
![image](https://user-images.githubusercontent.com/21080030/69010667-26c34d80-0962-11ea-87eb-ce7e323f949d.png)
so I tried both to handle the LoadComplete event and to override the OnLoadComplete and set my new location there, but the code is never hit (yes, I know that one of the two is enough ;)
Looks like the LoadComplete event (for my second form) is never fired. Is that normal?

**Comment by msasso69** [comment]
Found the catch!
I missed to invoke the method Show() for the help form (at least once during its life cycle).

Adding the code:
```
			if (!helpForm.Loaded)
				helpForm.Show();
```
into the ShowHelp() of my repro:
```
		public static void ShowHelp()
		{
			...
			if (!helpForm.Loaded)
				helpForm.Show();
			helpForm.Size = new Size((int)size.Width - width, (int)size.Height);
			helpForm.Visible = true;
			helpForm.Location = new Point(mainForm.Location.X + width, mainForm.Location.Y); // THIS DOES NOT WORK ON MAC 
			helpVisible = true;
		}
```
fixed the problem.

Strange is that with Wpf this is not necessary, anyway @cwensley I leave it to you to close this issue if you think it is a mistake not calling the form Show() method at least once :)

**Comment by cwensley** [comment]
Hey @msasso69,

Yes the call to `Show()` is mandatory on all platforms otherwise things might not work quite right.  However, it would be fairly easy to make setting `Visible = true` call Show() if the form is not loaded which would solve this issue.  Thanks for reporting it!

**Comment by cwensley** [comment]
Ok, PR is in to fix this.  I've also fixed an issue where `Form.ShowActivated` doesn't work in WPF when setting the window location.

So instead of having to set focus to the main form, you can just set `helpForm.ShowActivated = false` and it will show but keep the main form active.

Cheers!
