### ISSUE TITLE
[Wpf] Cannot execute a script in the WebView

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1511]
I'm implementing a help form where I'd like to load an html content using the WebView and position to the exact point containing the text that I want the user to see.
On Mac everything works fine, but on Wpf unfortunately the ExecuteScript method of the WebView has no effect if I don't click the control first (does it depend on the fact that it is on a second form?)
## Expected Behavior
I expect that I can execute a script on the WebView in the second form without having to click on it first.

## Actual Behavior
The ExecuteScript method of the WebView has no effect if I don't click the control first (this happens with Wpf, on Mac it works as expected)

## Steps to Reproduce the Problem

  1. Run the repro
![image](https://user-images.githubusercontent.com/21080030/69009812-9d0f8200-0959-11ea-8b60-33d5fab29974.png)
  2. click on the button "Show Help"
![image](https://user-images.githubusercontent.com/21080030/69009834-bca6aa80-0959-11ea-8e75-4f4958a87f99.png)
  3. click on the button "Load HTML and executescript"
![image](https://user-images.githubusercontent.com/21080030/69009846-dcd66980-0959-11ea-8aec-f33737051892.png)
  3. (we should have already positioned to a specific element in the html document, but it didn'work)
      Now click on any of the two buttons in the second form (nothing will happen!)
  4. Now click in the WebView control
  5. Now click again on any of the two buttons in the second form (NOW THEY WORK! :)
![image](https://user-images.githubusercontent.com/21080030/69010090-14461580-095c-11ea-8e85-447c73161b2e.png)
     (the alert pops up and the html document content is positioned at the desired position)

(the repro is only meant to highlight the problem in the subject, it is not robust to loading the html again after closing the second form, my apologies for that ;)

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Drawing;
using Eto.Forms;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);
			mainForm = new MainForm();
			helpForm = new HelpForm();
			app.Run(mainForm);
		}

		static MainForm mainForm;
		static HelpForm helpForm;

		public class MainForm : Form
		{
			public MainForm()
			{
				this.Width = 500;
				this.Height = 500;
				Button button1 = new Button() { Text = "Show Help" };
				Button button2 = new Button() { Text = "Load HTML and execute script" };
				button1.Click += (sender, e) =>
				{
					mainForm.Focus();
					helpForm.Visible = true;
					helpForm.Location = new Point(mainForm.Location.X + mainForm.Width, mainForm.Location.Y); // THIS DOES NOT WORK ON MAC 
				};
				button2.Click += (sender, e) =>	{ helpForm.SetDocumentText(); };
				Content = new StackLayout
				{
					Items =
					{
						new StackLayoutItem(button1),
						new StackLayoutItem(button2),
					}
				};
			}
		}

		public class HelpForm : Form
		{
			Button btn1;
			Button btn2;
			WebView webBrowser1;
			public HelpForm()
			{
				this.Width = 250;
				this.Height = 500;
				btn1 = new Button() { Text = "Position to Id" };
				btn2 = new Button() { Text = "Show Alert" };
				webBrowser1 = new WebView() { Size = new Eto.Drawing.Size(230, 450) };
				// STRANGELY I DIDN'T SUCCEED IN USING STACKLAYOUT OR TABLELAYOUT: THE WEBVIEW TOOK ALWAYS ALL THE AVAILABLE SPACE!
				PixelLayout pl = new PixelLayout();
				pl.Add(btn1, new Eto.Drawing.Point(0, 0));
				pl.Add(btn2, new Eto.Drawing.Point(0, 24));
				pl.Add(webBrowser1, new Eto.Drawing.Point(0, 50));
				Content = pl;
				webBrowser1.DocumentLoaded += WebBrowser1_DocumentLoaded;
				btn1.Click += (sender, e) => ExecuteScript();
				btn2.Click += (sender, e) => { webBrowser1.ExecuteScript("alert('this is called from code'); return 'return value from ExecuteScript';"); };
			}

			public void SetDocumentText()
			{
				Focus();
				webBrowser1.Focus();
				string html = 
					"<html>" +
					"<head>" +
					"<style type = \"text/css\" >p.int-min { margin - top:-15px }</style>" +
					"</head>" +
					"<body style = \"background -color:#FFFFE0;\" >" +
					" <div>" +
					" <h1 id = \"startpage\">Start Page</h1><p class=\"int-min\">grge eger gre gd f sfg e vs f ec se frew g r vewf w f sc</p>" +

					"<h2 id = \"startpage_projects\">Projects </h2><p class=\"int-min\">htjfg rh ge rtrdfref sfergersf wef rec sfcwfw f wf</p>" +
					"<h3 id = \"startpage_projects_colProjectName\">Project Name</h3><p style = \"margin-top:-15px; \" > gyhd ehj fgrs ht s v esgr ve ce g ve v weg ve f eecr fe</p>" +
					"<h3 id = \"startpage_projects_colLastModified\">Last Modified</h3><p style = \"margin-top:-15px; \" > rgtrhy jtyhyt j fge f eg rt h rg ve grs e f</p>" +
					"<h3 id = \"startpage_projects_colRename\">Rename</h3><p style= \"margin-top:-15px; \" > sfsf sdfsd g dgh ryhjrt h ryjh h tr h</p>" +
					"<h3 id = \"startpage_projects_colOpen\">Open</h3>< p class=\"int-min\">fhgf hf h trh erg gf wf wefr we f wef sf as</p>" +
					"<h3 id = \"startpage_projects_colDelete\">Delete</h3>< p class=\"int-min\">jghjgfh f g g ef se df d ad q wed qwds</p>" +

					"<h2 id = \"startpage_sessions\">Sessions</h2><p class=\"int-min\">rtrh ytj yukj th rg e fre gf e f cfw</p>" +

					"<h3 id = \"startpage_sessions_colID\">ID</h3><p class=\"int-min\">hytjhr gw g e fr g ve gf wreg ewf</p>" +
					"<h3 id = \"startpage_sessions_colSessionName\">Session Name</h3><p class=\"int-min\">yujtyhrg gef efe f gf vce  fr reg we f</p>" +
					"<h3 id = \"startpage_sessions_colBaseUri\">Base Uri</h3><p class=\"int-min\">hfh f rty dg e d gsfwfwerg gs fg sg sfrws</p>" +
					"<h3 id = \"startpage_sessions_colCrawlType\">Crawl Type</h3><p class=\"int-min\">hfgh fh fh fte t r weh fhj ry et wr wf</p>" +
					"<h3 id = \"startpage_sessions_colFetchedUrls\">Fetched Urls</h3><p class=\"int-min\">kjty u hdyg eg tr wfq wrdf wfs gft ert w fsd</p>" +
					"<h3 id = \"startpage_sessions_colStartDate\">Start Date</h3><p class=\"int-min\">fgdfg d dfgdf gdfg dg dg drgter tertet</p>" +
					"<h3 id = \"startpage_sessions_colEndDate\">End Date</h3><p class=\"int-min\">fgdfg d dfgdf gdfg dg dg drgter tertet</p>" +
					"<h3 id = \"startpage_sessions_colCrawlDuration\">Crawl Duration</h3><p class=\"int-min\">fgdfg d dfgdf gdfg dg dg drgter tertet</p>" +
					"<h3 id = \"startpage_sessions_colCompletionReason\">Completion Reason</h3><p class=\"int-min\">fgdfg d dfgdf gdfg dg dg drgter tertet</p>" +
					"<h3 id = \"startpage_sessions_colDomain\">Domain</h3><p class=\"int-min\">fgdfg d dfgdf gdfg dg dg drgter tertet</p>" +

					"<h2 id = \"startpage_administeredsites\">Administered Sites</h2><p class=\"int-min\">rtrh ytj yukj th rg e fre gf e f cfw</p>" +
					"<h3 id = \"startpage_administeredsites_colBaseUrl\">Base Url</h3><p class=\"int-min\">hytjhr gw g e fr g ve gf wreg ewf</p>" +
					"<h3 id = \"startpage_administeredsites_colValid\">Valid</h3><p class=\"int-min\">fgerg eg e g s feg sf wgf sgfsgf</p>" +
					"<h3 id = \"startpage_administeredsites_colLastVerifiedWith\">Last Verified With</h3><p class=\"int-min\">fhr h eg eg se t wf sf e sf af asf df</p>" +
					"<h3 id = \"startpage_administeredsites_colExpire\">Expire</h3><p class=\"int-min\">hfgh dfh rh dg wgf sf we f f wef wsf</p>" +
					"<h3 id = \"startpage_administeredsites_colNotes\">Notes</h3 ><p class=\"int-min\">yk yjk tjk t jr yh eg we t wqdqe dq rd</p>" +
					"<h3 id = \"startpage_administeredsites_colEditNotes\">Edit Notes</h3><p class=\"int-mi\">jyg jtr hjrgh e gtw f qwr f wef</p>" +
					"<h3 id = \"startpage_administeredsites_colDeleteRow\">Delete Row</h3><p class=\"int-mi\">hrh erh e gfwg vfw serfw g w ef w gw gf</p>" +

					"</div>" +
					"</body>" +
					"</html>";

					webBrowser1.LoadHtml(html);
			}

			private void WebBrowser1_DocumentLoaded(object sender, Eto.Forms.WebViewLoadedEventArgs e)
			{
				webBrowser1.Focus();
				ExecuteScript();
			}

			void ExecuteScript()
			{ 
				string id = "startpage_sessions_colSessionName";
				string script = string.Format("document.getElementById('{0}').scrollIntoView();", id);
				var ret = webBrowser1.ExecuteScript(script);
			}
		}
	}
}
```

## Specifications

  - Version: Eto src last pull 25 October 2019
  - Platform(s): WPF
  - Operating System(s): Windows 7

**Comment by cwensley** [comment]
Hey @msasso69, thanks for the details and the repro, it is very helpful!

I'm not sure what's going on there, maybe something needs to be called before executing the script.  On WPF the control is actually a WinForms WebBrowser control as it has more features.. I hope to use the edge browser when it becomes more mature, which might get around some of these oddities.

**Comment by msasso69** [comment]
You rang me a bell so I added a 
```
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```
in the head of my html file and now the control works as expected.
Looks like the oddities come from IE7 that is the default browser for the Winforms control.

It is not the solution to the problem but a valid workaround for my application.
Hope this helps

**Comment by cwensley** [comment]
Ah right, the good 'ol IE issue.  Unfortunately, there's no way to programatically set the IE version (other than [bad registry hacks](https://stackoverflow.com/a/25650219/981187)), which I'd hesitate to do in Eto by default.

I think a better solution would be to use the new edge powered [WPF WebView](https://www.nuget.org/packages/Microsoft.Toolkit.Wpf.UI.Controls.WebView/) control, however that is being migrated to yet another new [WebView2](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2) control to support edge with the chromium engine.

Another option would be to use Chromium directly and embed it with your app (this obviously bloats your app, like other web-based apps using Electron, etc).

I've created https://github.com/picoe/Eto.Toolkit/issues/28 to address this via a separate package since it would add additional dependencies that are not ideal as part of core Eto, and also requires .NET 4.6.2, whereas Eto.Wpf/WinForms targets .NET 4.5.
