### ISSUE TITLE
Setting DataContext after XamlReader.Load() not subscribe PropertyChanged

### ISSUE THREAD

**Issue by nrother** [picoe/Eto#1534]
I have a `TestView` (defined via XAML). This view has a Binding to `Image`:
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<Panel
	xmlns="http://schema.picoe.ca/eto.forms" 
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	Padding="4"
	>
	<Scrollable>
		<ImageView Image="{Binding Image}" />
	</Scrollable>
</Panel>
```
I create an instance of this view at runtime like this (it is added to a DocumentControl):
```csharp
new TestView() { DataContext = new TestViewModel() }
```
When the `Image` of the `TestViewModel` changes, the view does not update. A bit of debugging showed, that the `PropertyChanged` event of the view model is `null`, which looks suspicious to me.

When the `DataContext` is passed in the ctor and set *before* the call to `XamlReader.Load(this);` everything works as expected. `OnDataContextChanged` is always called as expected.

Is this a bug, or am I missing something?

  - Version: 4.2.1, 4.5.0-rc.4
  - Platform(s): Gtk3
  - Operating System(s): Ubuntu 18.04

**Comment by cwensley** [comment]
Hey @nrother thanks for reporting the issue!

This should work, what does `TestViewModel` look like?  Have you implemented `INotifyPropertyChanged` on that class?

**Comment by nrother** [comment]
It implements `INotifyPropertyChanged` via a base class:
```csharp
public class TestViewModel : ViewModelBase 
{
    private Image image;
    public Image Image
    {
        get => image;
        private set => SetField(ref image, value);
    }
}
public abstract class ViewModelBase : INotifyPropertyChanged
{
	public event PropertyChangedEventHandler PropertyChanged;
	protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
	   => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

	protected bool SetField<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
	{
		if (EqualityComparer<T>.Default.Equals(field, value)) return false;
		field = value;
		OnPropertyChanged(propertyName);
		return true;
	}
}
```

**Comment by cwensley** [comment]
Ok I looked into this and I think what you're running into is that the Scrollable does not change size after it is initially created.  If you set a size for the Scrollable, you may be able to see the results.  Here's a sample I put together that works for me:

[ImageBindingSample.zip](https://github.com/picoe/Eto/files/4072643/ImageBindingSample.zip)

**Comment by nrother** [comment]
I just tried to explicitly set a size for the Scrollable, this did not change anything. Please note that the initial image is shown correctly, just subsequent changes to the image are ignored by the ImageView.

I'll have a look into you example code.

**Comment by cwensley** [comment]
Hey @nrother, I'm closing this as there hasn't been any feedback for a while.  Please let me know if it's still an issue.

**Comment by nrother** [comment]
Hey, the project I was using Eto for is currently on hold, therefore I hadn't had the time to look further into it. I'll let you know if there are any updates.
