### ISSUE TITLE
Exceed Extended WPF Toolkit license change, commercial usage restrictions.

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1544]
Not a functional issue, so ignoring the template.

The Exceed Extended WPF Toolkit recently made a license change that appears to make it incompatible with commercial applications without a license fee being paid. I wondered whether this might be an issue for Eto-based applications where Eto licensing doesn't require a license to be paid for commercial usage. Ticket is https://github.com/xceedsoftware/wpftoolkit/issues/1557

There is a fork at https://github.com/dotnetprojects/WpfExtendedToolkit that might be a suitable replacement, if an alternative is needed.

**Comment by cwensley** [comment]
Hm, that's fairly frustrating..   Thanks for bringing this to my attention.. perhaps we could remove this dependency by creating our own implementations of some of the controls..

**Comment by cwensley** [comment]
Closing this as we'll stay at 3.6.0 for now, and move to the fork only if/when necessary.

**Comment by philstopford** [comment]
Just wanted to link this to https://github.com/picoe/Eto/pull/2307

**Comment by philstopford** [comment]
@cwensley : From https://github.com/xceedsoftware/wpftoolkit/issues/1557 it seems that you could update to 3.8.2 as the last MS-PL licensed version, at least until you can move to a fork that isn't so restrictively licensed.

**Comment by cwensley** [comment]
Thanks @philstopford, although they "say" it was released with that license, the actual .nupkg contains the restrictive license so I hesitated to update.  They have since clarified [here](https://github.com/xceedsoftware/wpftoolkit/issues/1776) that although it includes the XCEED license in the nupkg, it is indeed MS-PL.  

However, nothing is stopping consumers of Eto to update to that version themselves.  I would rather remove this dependency completely than switch to something else.

**Comment by philstopford** [comment]
@cwensley : generally, I pick up Eto from nuget rather than building from source, so I was curious whether it would be worth updating the existing dependency for your next patch release until such time that you can avoid the dependency entirely.

**Comment by cwensley** [comment]
@philstopford is there any particular reason you need/want the updated version?

**Comment by philstopford** [comment]
Nothing specific. Just thought it might carry some fixes that would be worth the effort, and wasn't sure if their weird handling of this specific version might allow you to benefit from them until a better option was available :)
