### ISSUE TITLE
.NET Core 3.1 sets up .NET Framework 4.6.1 projects for executables

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1546]
## Expected Behavior

Project files are set to be .NET Core 3.1 applications

## Actual Behavior

Project files are set to use the .NET 4.6.1 framework.

## Steps to Reproduce the Problem
Confirm the dotnet version installed : 
dotnet --version
3.1.100

For the 3.1 version installed, do:

  1. dotnet new -i "Eto.Forms.Templates::2.5.0-ci-10403" --nuget-source https://www.myget.org/F/eto/api/v3/index.json
  2. dotnet new etoapp -sln -s -m code -wf
OR
  2. dotnet new etoapp -sln -m code -wf

Review the resulting project files (e.g. under .Desktop for the not-separate case) or under the platform folders for the separate case :

```
<Project Sdk="Microsoft.NET.Sdk">
        
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
        
  <ItemGroup>
    <ProjectReference Include="..\nc31\nc31.csproj" />
  </ItemGroup>
        
  <ItemGroup>
    <PackageReference Include="Eto.Platform.Windows" Version="2.5.0-ci-10403" />
    <PackageReference Include="Eto.Platform.Wpf" Version="2.5.0-ci-10403" />
    <PackageReference Include="Eto.Platform.Gtk" Version="2.5.0-ci-10403" />
    <PackageReference Include="Eto.Platform.Mac64" Version="2.5.0-ci-10403" />
  </ItemGroup>
        
</Project>
```
I would expect TargetFramework to be : netcoreapp3.1

## Specifications

  - Version: 2.5.0-ci-10403
  - Platform(s): All
  - Operating System(s): All
 
Example ZIP attached for the result of the dotnet commands under Linux, for both the all-in-one and separate project creation

[nc31_linux.zip](https://github.com/picoe/Eto/files/4022034/nc31_linux.zip)

**Comment by cwensley** [comment]
Hey @philstopford thanks for submitting the issue, but no the default will not be netcoreapp3.1.  A separate parameter for the project templates should be added to optionally target .NET Core instead.
