### ISSUE TITLE
Does Eto support .Net Core?

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [picoe/Eto#1559]
Hi:

I'm in the process evaluating some CrossPlatform UI solutions for our existing application.
We are currently have a WPF based GUI.

Does Eto currently or plan to support .Net Core?

Thanks,
JohnB

**Comment by cwensley** [comment]
@SCLD-JBuczkowski, yes the current CI builds of Eto.Wpf, Eto.WinForms, Eto.Gtk, and Eto.Mac64 platforms support running under .NET Core 3.x.

A new 2.5.0 RC will be released very soon that will enable you to take advantage of .NET Core on all platforms.
