### ISSUE TITLE
Can you point me to Eto discussion forums/chats?

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [picoe/Eto#1560]
Hi:

I understand that this section should really be reserved for issues. Is there another forum/chat group that is more appropriate for questions and discussions?

Thanks,
JohnB

**Comment by cwensley** [comment]
Take a look at the top of the readme, particularly:

> [![forums](https://img.shields.io/badge/join-the%20forums-yellowgreen.svg)](http://groups.google.com/group/eto-forms)
[![Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg)](https://gitter.im/picoe/Eto)

I'm always on Gitter, feel free to chat there.
