### ISSUE TITLE
Gtk: (Rich-)TextArea does not trigger MouseUp/MouseDown with alternate mouse button

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1567]
Both OnMouseUp as well as the event MouseUp don't get called when the right mouse button is pressed on the TextArea. Instead a default context menu is opened.

At least at some time back with Eto 2.4.0 it was possible to hook into that event to show a custom context menu, at least on Wpf.

## Expected Behavior
1) The event is triggered.
2) It is possible to suppress the default context menu by setting `e.Handled = true;` (this is not strictly part of this issue, but may be related)

## Actual Behavior
Event is not triggered and the default context menu is shown.

## Code that Demonstrates the Problem

```csharp
public sealed class LogControl : RichTextArea
{
        private readonly ContextMenu menu;

        public LogControl()
        {
            ReadOnly = true;

            menu = new ContextMenu();
            var itm = new ButtonMenuItem
            {
                Text = "Clear",
                Enabled = true,
            };
            menu.Items.Add(itm);
        }

        protected override void OnMouseUp(MouseEventArgs e)
        {
            if (e.Buttons == MouseButtons.Alternate)
            {
                menu.Show(this);
                e.Handled = true;
            }
            base.OnMouseUp(e);
        }

        protected override void Dispose(bool disposing)
        {
            menu?.Dispose();
            base.Dispose(disposing);
        }
    }
```

## Specifications

  - Version: 2.5.0-rc5 (myget)
  - Platform(s):  Gtk
  - Operating System(s): Ubuntu 19.10

**Comment by ManuelHu** [comment]
Im clearly no expert at Gtk programming, but I did some debugging, and it looks like this is not directly possible in Gtk.

It feels like the built-in right mouse click click event is hardwired to opening the context menu and cannot be changed. There is a event `PopulatePopup` which can be used to customize the menu - but apparently not to disable it.

Calling `Dispose` on the provided menu in this callback, does prevent the menu from showing (in a hacky way, it does output a warning...), but does NOT restore all events properly. (MouseUp works, MouseDown still doesn't)

Maybe this handler could be used to fire a custom made mousedown event.

Or if Eto would provide a ContextMenu property on (Rich)TextArea, this could be use to change the default menu...

**Comment by cwensley** [comment]
@ManuelHu  did you try the MouseDown event?  It happens much earlier and typically could override any default behaviour of the control.

**Comment by ManuelHu** [comment]
I'm quite sure I tried MouseDown some long time ago and it did'nt work, but now I tried it again, and it works... Thanks ;-)

**Comment by cwensley** [comment]
Thanks.  I'll close the issue as that is expected behaviour then.  If you set `e.Handled = true` on `MouseDown`, you should then also get a MouseUp event.

**Comment by ManuelHu** [comment]
Yes that works, too. Thanks again!
