### ISSUE TITLE
NumericMaskedTextBox<T> value not being set correctly

### ISSUE THREAD

**Issue by NoOne2246** [picoe/Eto#1568]
## Expected Behavior
NumericMaskedTextBox.Value = 10;
NumericMaskedTextBox.Value = 100;
NumericMaskedTextBox.Value = 150;

## Actual Behavior
NumericMaskedTextBox.Value = 1;
NumericMaskedTextBox.Value = 1;
NumericMaskedTextBox.Value = 15;

## Steps to Reproduce the Problem

  1. Set default value of the masked textbox in the form code to be based on saved value from previous close.
  2. Run Dialog with default values from previous close.
  3. Inspect form for value displayed.

## Code that Demonstrates the Problem
    private NumericMaskedTextBox<double> Slope_0 = new NumericMaskedTextBox<double>();
    Slope_0.Value = 10.0;

    Slope_0.AllowDecimal = true;
    Slope_0.AllowSign = false;
    Slope_0.TextAlignment = TextAlignment.Right;
## Specifications

  - Version: Runtime (4.0.30319) Version (2.5.0.0)
  - Platform(s): 
  - Operating System(s):  Windows 10 
  
## Other
Eto/Source/Eto/Forms/MaskedTextProvider/NumericMaskedTextProvider.cs:
Line 31:

    { typeof(double), new Info { Parse = s => { double d; return double.TryParse(s, out d) ? (object)d : null; }, ToText = v => ((double)v).ToString("F99").TrimEnd('0', '.'), AllowSign = true, AllowDecimal = true } },

I believe the trim end is removing the 0.

**Comment by cwensley** [comment]
@NoOne2246 thanks for reporting the issue!
