### ISSUE TITLE
NU 1701 netcore3.1

### ISSUE THREAD

**Issue by andreakarasho** [picoe/Eto#1570]
Hi, i referenced eto.forms and eto.platform.wpf DLLs from nuget [v 2.4.1] to my netcore3.1 project.

The eto.platform.wpf generates the warning error NU 1701.

**Comment by ManuelHu** [comment]
I suppose that only Eto 2.5.0 is compatible with netcore3. Those builds currently just exist as Release Candidate/beta. If someone knows more, please correct me...

**Comment by cwensley** [comment]
@ManuelHu This is correct, only the 2.5.0-rc.5 release in myget supports .NET Core.  It has bugs that need squashing before going to nuget.org.
