### ISSUE TITLE
BitmapData.Dispose is very slow

### ISSUE THREAD

**Issue by weierstrass1** [picoe/Eto#1575]
I was doing a Drawable component to render a big grid, then i did a Paint method for paint event:

```
private void paint(object sender, PaintEventArgs e)
{
    if (image.Width * image.Height != grid.Lenght)
        image = new Bitmap(grid.WidthWithZoom, grid.HeightWithZoom, PixelFormat.Format24bppRgb);
    using (BitmapData bd = image.Lock())
    {
        unsafe
        {
            byte* bs = (byte*)bd.Data;
            grid.CopyTo(bs);
        }
    }
    e.Graphics.DrawImage(image, 0, 0);
}
```

My problem is that the BitmapData.Dispose is the bottle neck here, because all others things including grid.CopyTo and all rendering things are very fast (i am using gpu to do the grid) and just need less than 2 milliseconds, but the BitmapData.Dispose requires like 16 or 18 milliseconds (if the grid have zoom x8) or 50 milliseconds (if the grid have zoom x16). 

How can i skip the use of image and draw directly on the component? is it necessary use a Drawable to draw directly on the component? what can i do?

**Comment by cwensley** [comment]
Hey @weierstrass1, I believe we already talked about this and found a way around your issue. 

The slowness can unfortunately not be avoided with an image that large. Also you should only recreate the bitmap if its size isn't big enough (you can use a larger bitmap to draw a smaller area).  It would mean you would have to copy the image data per row, but that would be much more efficient that recreating the image (potentially) every frame.

For those that might come across this again, the way around this is to use the `PaintEventArgs.ClipRectange` to only paint what is needed, along with the `Drawable(bool largeCanvas)` constructor if using WPF.
