### ISSUE TITLE
Multiline Labels not working from XAML

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1576]
A Label with multiline content is not rendered as expected when declared in XAML.

Assigning the content in C# by setting the label's property to something containing newlines works just fine, so I suppose this is a XAML bug.

---

I'm also pretty sure this worked already at some point between 2.4.1 and now. In between I updated Eto to 2.5.0-rc5 and my library project containing the code to `netstandard2.0`.

## Expected Behavior
Line breaks are preserved:

```
Test 

Hello
```

## Actual Behavior
Line breaks are replaced with spaces:
```Test Hello```

## Steps to Reproduce the Problem

  1. Create a form using xaml containing the following code somewhere 

## Code that Demonstrates the Problem

```xaml
      <Label>
Test

Hello
       </Label>
```
## Specifications

  - Version: 2.5.0-rc5, 2.5.0-rc6
  - Platform(s): Gtk(3) on Mono using **netstandard2.0**
  - Operating System(s): Ubuntu 19.10

**Comment by cwensley** [comment]
Hey @ManuelHu this might be due to an update of Portable.Xaml.  I think there were new options on how to treat whitespace.  I'm not sure if you can control that so I'll take a look at what makes sense.  For normal xaml, usually adding `xml:space="preserve"` to the tag would help, but this doesn't appear to work either.

**Comment by ManuelHu** [comment]
Thanks for your effort! I didn't know `xml:space`, but as you said, it doesn't work...

**Comment by cwensley** [comment]
This is a problem with Portable.Xaml.  By default, whitespace is actually _not_ preserved for compatibility with System.Xaml, which is different from earlier versions of Portable.Xaml.

I have just published 0.25.0 of Portable.Xaml to nuget.org that now supports `xml:space` attribute, which should fix your issue.  Please give it a go and let me know if it works!

**Comment by ManuelHu** [comment]
Yes, it works! Thanks for your work!

It would be nice if there was a CI build of Eto with it, then i could use it in my app...

**Comment by cwensley** [comment]
Thanks for confirming the fix!  To use it you should be able to reference the Portable.Xaml package from your app project(s) directly with the new version.  I'll also update the reference in Eto shortly.

**Comment by ManuelHu** [comment]
Thanks, that worked!
