### ISSUE TITLE
Default Eto 2.5.0 project (attached) does not run on Mac

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1585]
Project attached just below, any clues most appreciated, as are any questions.

[EtoApp1.zip](https://github.com/picoe/Eto/files/4233076/EtoApp1.zip)

- VS2019
- Choose:
	- Template: Eto.Forms Application
	- Framework: .Net Framework 4.6.1
	- Launcher: "Single Windows, Linux, Mack desktop project"
	- Framework: Full .Net Framework
	- Form: Code Preview
- Create default project
- Set EtoApp1.Desktop as the "Startup Project"
- Compile Release version
- Run on Windows OK
- Run on Linux OK
- Zip [EtoApp1.Desktop.app] folder
- Transfer zip to Mac OS 10.15.3
- Click on zip file produces EtoApp1.Desktop (Application)
- Click on EtoApp1.Desktop produces error: The application "EtoApp1.Desktop" can't be opened
- Manually install Mono for Mac
- Click again on EtoApp1.Desktop produces same error: The application "EtoApp1.Desktop" can't be opened

**Comment by cwensley** [comment]
@LaraSQP Thanks for reporting the issue.  

This is unfortunately a new "security feature" of macOS Catalina (10.15.x).  It no longer _automatically_ adds the executable flag (to `EtoApp1.Desktop.app/Contents/MacOS/Eto1.Desktop` in this case) when unzipping.  

Unfortunately, the only way to do that is to package it up using a .DMG when compiling on Windows (and set the executable flag when building it), or some other .zip utility that can set the executable flag on specific files (I don't know of any).

I am investigating ways to make it so the build automatically produces a .dmg on any platform to streamline this, but have not come to a solution yet.

**Comment by LaraSQP** [comment]
Thank you for the quick reply, as always.

How do I set "to package it up using a .DMG when compiling on Windows"?

**Comment by cwensley** [comment]
Perhaps take a look at [genisoimage](https://stackoverflow.com/a/7553878/981187) via Cygwin or [WSL](https://docs.microsoft.com/en-us/windows/wsl/about). I've known it to work for others but have not used it myself.

**Comment by LaraSQP** [comment]
So no workaround at this time?

**Comment by cwensley** [comment]
workaround is `chmod +x EtoApp1.Desktop.app/Contents/MacOS/Eto1.Desktop` after unzipping then open the .app bundle.  

You also need to hold down ctrl then right click > open the first time it is launched if you've downloaded it from the internet as macOS flags it as unsafe unless it is code signed and notarized.

**Comment by LaraSQP** [comment]
The command was almost correct, just missing the App in the last chunk, so that:

`chmod +x EtoApp1.Desktop.app/Contents/MacOS/Eto1.Desktop`

should be

`chmod +x EtoApp1.Desktop.app/Contents/MacOS/EtoApp1.Desktop`

The problem now is an error stating that: _"EtoApp1.Desktop" is damaged and can't be opened. You should move it to the Trash._

We seem to be almost there.

**Comment by cwensley** [comment]
For that error, see my second comment about holding down ctrl and right click > open. Before Catalina you only had to right click and open without holding down ctrl.

It might apply to files being copied now not just from the internet, I guess depending on how you are copying the file..

**Comment by cwensley** [comment]
.. and I'm fairly annoyed about the error message saying that it is "damaged".  Apple is really forcing people to sign and notarize apps.

**Comment by LaraSQP** [comment]
Same error with ctrl + right click + open. Damaged.

**Comment by cwensley** [comment]
hmm.. you need to hold down ctrl the entire time (not just the right click part).. it works for me at least.

Alternatively, you could try `xattr -c EtoApp1.Desktop.app`

**Comment by LaraSQP** [comment]
The ctrl workaround still does not work.

However, the `xattr` command did it. Now a click on the app runs it no problem.

So, summing up, the following are required:

`chmod +x EtoApp1.Desktop.app/Contents/MacOS/EtoApp1.Desktop`
`xattr -c EtoApp1.Desktop.app`

Good enough for me.

Thanks again.

**Comment by LaraSQP** [comment]
> Unfortunately, the only way to do that is to package it up using a .DMG when compiling on Windows (and set the executable flag when building it), or some other .zip utility that can set the executable flag on specific files (I don't know of any).

Ok, I got `WSL` up and running and can package up the app as a `.DMG` with `genisoimage`, much appreciated.

The problem seems to be setting the _"**executable flag** when building it"_ because Mac spits "corrupt executable" or some such.

I'm out of my depth and wits here.

Any hints?

**Comment by LaraSQP** [comment]
I'm burned out.

This is the workaround I have found:

https://bitbucket.org/twocanoes/repackage/src/master/

Drop the app bundle and it creates a `.pkg` just like that.

Unidentified developer remains a problem when installing so the user has to go through `Security & Privacy`.

**Comment by cwensley** [comment]
Closing this as it has been resolved (executing an app zipped from windows).  The issues with packaging are tracked with #1748
