### ISSUE TITLE
How to populate a PropertyGrid? Any which way is fine

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1589]
As the question reads, how to populate a PropertyGrid?

There is no documentation of this new control as of yet so any which way anyone does it is fine by me.

Thank you all.

**Comment by cwensley** [comment]
`new PropertyGrid { SelectedObject = myObjectToEdit }`.  I have yet to update the docs for 2.5, but until then the documentation is in the code [here](https://github.com/picoe/Eto/blob/develop/src/Eto/Forms/Controls/PropertyGrid.cs#L71).

If you have any suggestions for the documentation please let me know!

**Comment by cwensley** [comment]
Also, another great resource for any control is the [Eto.Test](https://github.com/picoe/Eto/tree/develop/test/Eto.Test/Sections) application.  For the PropertyGrid, check the sample out [here](https://github.com/picoe/Eto/blob/develop/test/Eto.Test/Sections/Controls/PropertyGridSection.cs#L8)

**Comment by LaraSQP** [comment]
You rock.
