### ISSUE TITLE
Ironpython with Eto.Mac64  issue

### ISSUE THREAD

**Issue by mahaidong** [picoe/Eto#1595]
i run `ipy.exe  etoTest.py` for the following ironpython file

In  windows  the platform **Eto.Wpf.dll** ,  it  is ok

```
import System
import clr
clr.AddReference("Eto.Wpf")
clr.AddReference("Eto")

import Eto
import Eto.Drawing as drawing
import Eto.Forms as forms

class MainForm(forms.Dialog[bool]):
    def __init__(self):
        # Initialize dialog box
        self.Title = 'Eto Form'
        self.Size = drawing.Size(200,200)

forms.Application(Eto.Platforms.Wpf).Run(MainForm())

```

But when i try to figure out in mac **Eto.Mac64.dll**,  I got **error**.

Eto.Platform.Mac64 Version="2.5.0"
files: Eto.dll,  Eto.Mac64.dll,  MonoMac.dll

```
import System
import clr
clr.AddReference("MonoMac")
clr.AddReference("Eto.Mac64")
clr.AddReference("Eto")

import Eto
import Eto.Drawing as drawing
import Eto.Forms as forms

class MainForm(forms.Dialog[bool]):
    def __init__(self):
        # Initialize dialog box
        self.Title = 'Eto Form'
        self.Size = drawing.Size(200,200)

#line 17
forms.Application(Eto.Platforms.Mac64).Run(MainForm())  

```
I got "Error".

```
Traceback (most recent call last):
  File "etoTest,py", line 17, in <module>
SystemError: Error creating instance of platform type 'Eto.Mac.Platform, Eto.Mac64'
```

  
  - Platform(s):  Mac64
  - Operating System(s):  macOS Catalina version 10.15.3

**Comment by cwensley** [comment]
You need to create an .app bundle (folder) with the proper structure and files.  Please see the .targets files [here](https://github.com/picoe/Eto/tree/develop/src/Eto.Mac/build) for how it is done for mono or .NET Core based projects with msbuild.

**Comment by mahaidong** [comment]
> You need to create an .app bundle (folder) with the proper structure and files. Please see the .targets files [here](https://github.com/picoe/Eto/tree/develop/src/Eto.Mac/build) for how it is done for mono or .NET Core based projects with msbuild.

Thanks for fast reply.
But I still can not got it.   
I run ironpython file in terminal as `mono ipy.exe  myEtoHolloWorldFile.py` .  
If I create a bundle(folder) , How can I execute it? 
The Example you give me is create a bundle for dll file.

**Comment by cwensley** [comment]
Hey @mahaidong,

You have two ways, it appears:

1. Compile your .py file into an exe [using pyc](https://stackoverflow.com/a/2437485/981187)
2. Create a small c# or f# wrapper project that executes the .py using the [IronPython NuGet package](https://www.nuget.org/packages/IronPython/2.7.10-candidate1)

I would suggest doing 2, as you can then utilize Eto's existing infrastructure to build the .app bundle.
