### ISSUE TITLE
Wpf comboboxcell is broken on the latest release

### ISSUE THREAD

**Issue by bow-meow** [picoe/Eto#1601]
## Expected Behavior
Clicking a Wpf ComboBoxCell in edit mode will display its menu content.

## Actual Behavior
It commits its edit and exits edit mode.

## Additional info

Adding an override in the comboboxcell handler for the mouse down, setting the menu to open and setting ishandled  is not enough. If the combobox menu is outside the bounds of the grid rows, it will treat them as not clickable.

The issue seems to stem from the HandleMouseUp event in the Wpf GridHandler, setting for empty selection.

## Specifications

  - Version: Lastest
  - Platform(s): Wpf
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @bow-meow, thanks for reporting the issue!  I'm seeing the same behaviour.  It was caused by a change to make the click+drag semantics work better by starting editing only after the MouseUp (vs. the WPF default behaviour of doing it on MouseDown).
