### ISSUE TITLE
WinForms: Font.MeasureString() and Graphics.MeasureString() measure \n as wider then 0

### ISSUE THREAD

**Issue by GeneThomas** [picoe/Eto#1602]
On WinForms

Font.MeasureString("Test\n") and Graphics.MeasureString(font, "Test\n") are wider than Font.MeasureString("Test") and Graphics.MeasureString(font, "Test")

See attached project:
[EtoFormsFault-MeasureStringNewline.zip](https://github.com/picoe/Eto/files/4265105/EtoFormsFault-MeasureStringNewline.zip)

**Comment by GeneThomas** [comment]
- Version:
    Eto 2.5.0
  - Platform(s): WinForms,
    not a problem on WPF
  - Operating System(s): 
    .Windows 10

**Comment by cwensley** [comment]
This is a factor of using "compatible text rendering", which uses GDI+ for font measuring and rendering.  You can use GDI rendering which gives you expected results using the following styles:

```c#
Eto.Style.Add<Eto.WinForms.Drawing.FontHandler>(null, h => h.UseCompatibleTextRendering = false);
Eto.Style.Add<Eto.WinForms.Drawing.GraphicsHandler>(null, h => h.UseCompatibleTextRendering = false);
```

Hope this helps!
Curtis.
