### ISSUE TITLE
vs mac cannot run targetFramework netcore3.1

### ISSUE THREAD

**Issue by jzlhll** [picoe/Eto#1606]
<img width="471" alt="屏幕快照 2020-02-28 下午4 30 23" src="https://user-images.githubusercontent.com/19789292/75523922-e5096f00-5a47-11ea-9601-f6a24c0d3748.png">

<img width="321" alt="屏幕快照 2020-02-28 下午4 32 40" src="https://user-images.githubusercontent.com/19789292/75523961-f5214e80-5a47-11ea-85c6-ab3b73dc9316.png">

<img width="435" alt="屏幕快照 2020-02-28 下午4 30 42" src="https://user-images.githubusercontent.com/19789292/75523897-dde26100-5a47-11ea-91fa-6afe3dadb5d8.png">

When create a new test proj, Run it with target framework netcore3.1 will get this "not exist".

OSX : 10.14.6
eto 2.5.0

**Comment by cwensley** [comment]
Hey @jzlhll, thanks for the report!  This is a known limitation and was already fixed in #1590 (it was mentioned in the [2.5.0 release notes](https://github.com/picoe/Eto/releases/tag/2.5.0)).  

Please give one of the [CI builds](https://www.myget.org/gallery/eto) a try!

**Comment by jzlhll** [comment]
Oh,thanks!
