### ISSUE TITLE
How can I get WebView loaded document/html

### ISSUE THREAD

**Issue by jzlhll** [picoe/Eto#1607]
I'm using the eto.Forms.WebView on Mac.It is perfect when loaded.
I can only get "title" or "uri" from 'DocumentLoaded' or
'DocumentTitleChanged' events. 
While,  how can I get the Html document ? 

OSX 10.14.6
Eto 2.5.1 CL
netcoreapp3.1

**Comment by cwensley** [comment]
Something like this would work (in the `DocumentLoaded` event):

`var html = myWebView.ExecuteScript("return document.documentElement.outerHTML;");`

Hope this helps.
