### ISSUE TITLE
WinForms: TextArea and TextBox renders urls blue with underline

### ISSUE THREAD

**Issue by GeneThomas** [picoe/Eto#1610]
## Expected Behavior

All text in TextArea shown in same font

## Actual Behavior

ᴜʀʟs a rendered blue and underlines

## Steps to Reproduce the Problem

Run the attached solution
Uncomment form.Fix() to fix.

## Code that Demonstrates the Problem
[EtoFormsFault-TextAreaHttp.zip](https://github.com/picoe/Eto/files/4273194/EtoFormsFault-TextAreaHttp.zip)

## Specifications

  - Version: 2.5.0
  - Platform(s):  WinForms
  - Operating System(s):  Windows 10
  
Not  a problem in WPF nor in TextBox.

**Comment by cwensley** [comment]
Thanks for the report!
