### ISSUE TITLE
WinForms: DrawText() width irregularities

### ISSUE THREAD

**Issue by GeneThomas** [picoe/Eto#1613]
## Expected Behavior
```c#
    
    DrawText(..., "Axxx xx xxxxxxx xxxxxx xx xxxx xxxxx xxxxx\nxxxx"); // and 
    DrawText(..., "Axxx xx xxxxxxx xxxxxx xx xxxx xxxxx xxxxx"); // should be the same width
```
## Actual Behavior

The DrawText() with the \n is printed 2 pixels wider so there is a fault.
![test](https://user-images.githubusercontent.com/514360/75731229-f4dcc800-5d53-11ea-943d-c8788e910e5c.png)

Working out which is correct relates to other issues I have raised with faults in MeasureString() and DrawText().
If we take the second as correct one can write a DrawText() that splits the lines then called the original DrawText() for each line.

## Steps to Reproduce the Problem

Run the attached program and look at test.png.
[EtoFormsFault-DrawTextWidth.2.zip](https://github.com/picoe/Eto/files/4278732/EtoFormsFault-DrawTextWidth.2.zip)

```C#
                string text = "Axxx xx xxxxxxx xxxxxx xx xxxx xxxxx xxxxx\nxxxx";
                string textOneLine = text.Split('\n')[0];

                g.DrawText(font, Colors.Black, 10, 10, text);
                // wider
                g.DrawText(font, Colors.Black, 10, 50, textOneLine);
                // narrower
```

## Specifications

  - Version: 2.5.0
  - Platform(s):  WinForms [not WPF]
  - Operating System(s): Windows 10

**Comment by GeneThomas** [comment]
My application Sɪᴀ — the serious mind mapping tool, released last month, relies on fast and accurate layout of text.
![Sia Screenshot](https://user-images.githubusercontent.com/514360/75731784-797c1600-5d55-11ea-9f43-d4238f4e7a77.png)

You may find it useful or could cite it as an example of Eto.Forms: http://sia.planetearthsoftware.com

**Comment by GeneThomas** [comment]
On WPF both render like the second DrawText(). Which supports that the second one is correct.

**Comment by cwensley** [comment]
This is an underlying issue with Windows Forms / System Drawing it appears.  I created a standard winforms application and the results are the same.

<img width="498" alt="Screen Shot 2020-04-03 at 11 53 54 AM" src="https://user-images.githubusercontent.com/367446/78395266-04913b80-75a2-11ea-9e26-c78079b3a6e2.png">

This issue should be filed here: https://github.com/dotnet/winforms.
