### ISSUE TITLE
Close() throws Gtk-CRITICAL error and hangs

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1617]
Calling `Close()` in the main form, exits the app (as it should) and then spits the error:

`Gtk-CRITICAL **: 12:29:51.325: gtk_main_quit: assertion 'main_loops != NULL' failed`

**Comment by cwensley** [comment]
Hey @LaraSQP, thanks for reporting the issue and sorry for the late response.

I can't reproduce this on Ubuntu 21.04 using the Eto.Test.Gtk app.  Perhaps something else is causing it?

If you're still running into it, more detail would help like a small app that causes the same issue.

**Comment by LaraSQP** [comment]
I introduced the error trying (and still failing) to solve the issue "_Mac empty menu (missing Quit)_" (https://github.com/picoe/Eto/issues/2011)

Consider this issue closed but please look into the other one.
