### ISSUE TITLE
ListBox multiple selection?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1618]
I seem unable to find a `MultiSelect` property (or some such) for the `Listbox` control or up its inheritance tree.

My mistake?

**Comment by cwensley** [comment]
Not a mistake, there's no way to select multiple items as it only has a SelectedIndex or SelectedValue.  You can use a GridView with a single column instead.  It, consequently, is more flexible as you can customize the content of the cell, have checkboxes, etc.

**Comment by LaraSQP** [comment]
Much appreciated.
