### ISSUE TITLE
Broken Dynamic Layout sizing with labels with Gtk3

### ISSUE THREAD

**Issue by Sejsel** [picoe/Eto#1622]
## Actual Behavior
Having a Label in a horizontal section makes the section taller (vertically) if the text of the Label is made longer. This seems to be a mixup in axes.

In addition, trying to make the form window smaller doesn't work with this layout, there seems to be an implicit minimum size that cannot be overridden.

## Expected Behavior
A form is rendered with proper layout. Increasing the length of the text in the Label makes the layout wider, not taller.

## Steps to Reproduce the Problem

  1. Run the application
  2. Observe weird sizes
  3. Try to make the form window smaller

## Code that Demonstrates the Problem

```cs
using Eto.Forms;
using Eto.Drawing;

namespace GtkResizeIssues
{
	public class MainForm : Form
	{
		public MainForm()
		{
			Title = "My Eto Form";
			ClientSize = new Size(400, 350);

			var layout = new DynamicLayout();
			layout.BeginHorizontal();
			{
				layout.Add("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");
				// layout.Add("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum ultricies augue, non mollis ligula sagittis ac."); - using this makes the window not fit on the screen vertically
				layout.Add(new Button {Text = "Button"});
			}
			layout.EndHorizontal();

			Content = layout;
		}
	}
}
```

## Specifications

  - Version: 2.5.0
  - Platform(s): Gtk3
  - Operating System(s): Linux, Gtk 3.24
  
## An image of the form above
![image](https://user-images.githubusercontent.com/998408/76255212-1eaf5680-624e-11ea-95be-f481c20d6161.png)

**Comment by Sejsel** [comment]
This was introduced with 2.5.0, the dynamic layout worked correctly on 2.4.1.

**Comment by cwensley** [comment]
Hey @Sejsel,

Thanks for reporting the issue!

**Comment by Sejsel** [comment]
Seems to be affected by the HeightForWidth size request mode on the Label. Changing it to WidthForHeight fixes it, but breaks labels almost everywhere else. I don't know enough about how size allocation works in GTK, so I can't really help much more with this without spending an enormous amount of time researching it.

https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/Controls/LabelHandler.cs#L89
