### ISSUE TITLE
[Mac] TextBoxCellHandler sometimes crashes on macos 10.9.5

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1623]
I understand that without a repro it's not going to be easy to undestand what happens, anyway my app crashes on old macos (10.9.5) when filling in some grids.
The output I get is:
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Eto_Mac_Forms_Cells_EtoCellTextField setUsesSingleLineMode:]: unrecognized selector sent to instance 0x600000580410'
abort() called
terminating with uncaught exception of type NSException
```
along with a lot of other info of course.

Notice that this only happens on my old 10.9.5 macOS and with the latest pull of Eto (9th March 2020), with my previous pull that was dating back 13th Dec 2019 everything works fine also in my 10.9.5 macos machine.

Since in the grids that crash I'm only using TextBoxes I guess that the code that crashes is the following:
![image](https://user-images.githubusercontent.com/21080030/76544160-e1360d80-6487-11ea-9409-8a330a358a60.png)
but as I said not all the grids crash, only some of them (always the same and they never show up).
I can't provide more info since I do not have a development environment on that machine (Visual Studio for Mac is not even supported on 10.9.5), I'm only using it to test back compatibility with 10.9.x since I declare that the supported OS is from 10.9 on)

I'll try to narrow down the problem with a repro, in the meantime I hope that the above code rings somebody a bell ;)

## Specifications

  - Version: commit 1bf6c69 9th March 2020
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.9.5

**Comment by cwensley** [comment]
Hey @msasso69, thanks for reporting the issue.  Looks like that property should only be set on macOS 10.10 or later.

**Comment by cwensley** [comment]
So it looks like it was `ImageTextCell` that caused the problem, as that is the only cell that calls `setUsesSingleLineMode` on `EtoCellTextField`, which is what the uncaught exception is pointing to.  Perhaps if you aren't using the ImageTextCell on all of your grids it could explain why it only crashed in certain circumstances.

**Comment by msasso69** [comment]
I confirm that it is no longer crashing. Thanks!
