### ISSUE TITLE
[Mac] PropertyGrid on Eto.Test crashes

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1624]
Just pulled Eto code, ran Eto.Test and tried everything to seek for new cool stuff,
and found that PropertyGrid crashes (both compiling with net461 or xamarin20)
 

## Specifications

  - Version: commit 1bf6c69 9 March 2020
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13

**Comment by cwensley** [comment]
Hey @msasso69 awesome, thanks for reporting the issue.  Looks like it was a regression due to some recent changes with NumericMaskedTextProvider (after 2.5).
