### ISSUE TITLE
How to change output MyProgram1.Mac.app to MyProgram1.app

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1636]
Is there a way to change the output folder from `MyProgram1.Mac.app` to `MyProgram1.app` without changing the project name?

I suppose it can be done manually every time after compiling but, clearly, that is not preferred.

Changing the name of the `Assembly` can be done simply via the project `Application` properties but this only changes the name of the executable not of the bundle.

**Comment by ManuelHu** [comment]
Adding 
```
<MacBundleName>MyProgram1</MacBundleName>
```
to the first `<PropertyGroup>` in ypour csproj file should work. (Notice there is no .app in the value). At least I think so by looking at the msbuild targets file ;-)

**Comment by LaraSQP** [comment]
Much appreciated.

**Comment by LaraSQP** [comment]
And tested.

Works for me.
