### ISSUE TITLE
How chould I set eto.WebView proxy on Mac

### ISSUE THREAD

**Issue by jzlhll** [picoe/Eto#1637]
I read the code show that on Mac the webview using Mono webkit.

I want to set the http proxy of the webview when load website.
What can I do with eto webview.

Does something like this help?
https://stackoverflow.com/questions/13232153/change-the-proxy-settings-on-webkit-sharp-for-mono

**Comment by cwensley** [comment]
Hey @jzlhll, thanks for reporting the issue.  You are correct in that there's no API to set the proxy for the WebView.

The link you suggested is the mono webkit for GTK, which is not the same as what is used on macOS.  Instead it uses [WkWebView](https://developer.apple.com/documentation/webkit/wkwebview), which is also based on WebKit but provided by macOS directly.

Unfortunately, there isn't really a good way to provide a proxy for each of the platforms.  Instead, you can create your own web server (using `HttpListener` or some other mechanism), and forward your requests to the proxy you desire.  See the [HttpServer](https://github.com/picoe/Eto/blob/develop/src/Eto.Wpf/CustomControls/HttpServer.cs) used in Eto.Forms for local content as an example of how to get that going.

**Comment by jzlhll** [comment]
Thanks a lot. I will try it and study the wkwebview api.
