### ISSUE TITLE
Mac - how to change com.example.MyProgram to something else

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1639]
Looking at `EtoSpecialFolder.ApplicationSettings`, I found that Mac uses an Androidesque naming convention for `Application Support` (whatever that means).

In that location(?), it seems to create a folder named `com.example.MyProgram` or some such, presumably a parameter of some sort being created by default but that might (should?) be possible to overwrite, perhaps like `MacBundleName` in the `.csproj` file.

So, how to change `com.example.MyProgram` to, for example, `com.MyCompany.MyProgram`?

Thank you guys.

**Comment by cwensley** [comment]
It's in your Info.plist.

**Comment by LaraSQP** [comment]
Manual modification after each build, then?

**Comment by LaraSQP** [comment]
Found it, I think.

`CFBundleIdentifier`?

**Comment by cwensley** [comment]
No, it's part of the template when you create a new solution (MyProject.Mac\Info.plist).  If it isn't there, you can create one.

**Comment by LaraSQP** [comment]
Got it.

Thanks for the quick reply.
