### ISSUE TITLE
[Winforms] Graphics.FillPath crashes with LinearGradientBrush

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1645]
I noticed that (using Eto.Winforms) Graphics.FillPath() crashes when using a LinearGradientBrush because the brush.ControlObejct is null
(side question: is Eto.Winforms maintained? this is just one of the many issues I have with Eto.Winforms, shall I file also the others?)

## Steps to Reproduce the Problem

  1. run the repro
  2. (do not pay attention to expected result, the GraphicPath I wrote is not meant to get a meaningful drawing ;)

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;
namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);
			var myControl = new Drawable { BackgroundColor = Colors.LightCoral };
			myControl.Paint += (sender, e) =>
			{
				//Brush brush = new SolidBrush(Colors.Red);
				LinearGradientBrush brush = new LinearGradientBrush(
				new Rectangle(0, 0, 100, 100),
				Colors.Blue,
				Colors.Green,
				0);
				GraphicsPath path = new GraphicsPath();
				path.AddLine(0, 0, 100, 100);
				e.Graphics.FillPath(brush, path);
			};
			var form = new Form { Content = myControl, Size = new Size(400, 300) };

			app.Run(form);
		}
	}
}
```

## Specifications

  - Version: pulled code 4th April 2020
  - Platform(s): WinForms
  - Operating System(s): Windows 7

**Comment by cwensley** [comment]
Hey @msasso69, thanks for reporting the issue!  I'm sure that used to work at one point, it might be something that was overlooked.

>(side question: is Eto.Winforms maintained? this is just one of the many issues I have with Eto.Winforms, shall I file also the others?)

You can think of it this way: XamMac and WPF are more well tested as they are used in commercial project(s) that I work on professionally.

Gtk, MonoMac, and WinForms are community-driven.  I can fix things where I can but only when I have some spare time.

Gtk itself has seen some awesome contributions from the community and has had more testing/interest.  MonoMac shares codebase with XamMac so it is fairly well maintained.  WinForms is probably the last on the totem pole, but is not unmaintained.

Hope that sheds some light.  This is also consequently why I recommend people to use WPF.

**Comment by cwensley** [comment]
Looks like this wasn't implemented properly (or at all) on _any_ platform.  Fortunately the logic to determine the start/end points based on a bounding rectangle was already figured out to implement GradientWrapMode.Pad for System.Drawing, which can be used to extrapolate the correct Start/End points based on a rectangle so the gradient fills the entire area.

Thanks again for reporting the issue!
