### ISSUE TITLE
KeyDown event handler doesn't get triggered by some keys

### ISSUE THREAD

**Issue by morphx666** [picoe/Eto#1654]
## Expected Behavior
The `KeyDown` event handler should get triggered by the same keys as `KeyUp`.

## Actual Behavior
The `KeyDown` event handler doesn't get triggered by some keys under Linux/Mac platforms.
For example, Space, Enter and Arrow keys work just fine if captured by the `KeyUp`  event handler, but not using `KeyDown`.

## Steps to Reproduce the Problem

Capture the `KeyDown` event and display a dialogbox, `KeyDown += (object s, KeyEventArgs e) => MessageBox.Show(e.Key.ToString())`;, to test which keys are actually captured by the `KeyDown` event handler.

## Specifications

Linux (tested under various Ubuntu versions, including Raspbian), as well as macOS Catalina.
Works as expected under Windows 10.

**Comment by cwensley** [comment]
@morphx666 thanks for reporting the issue.  What control(s) have you tried?

**Comment by morphx666** [comment]
I have tried attaching the `KeyDown` handler to both a `Form` and a `Drawable`:

Json: https://github.com/morphx666/Newton/blob/master/Newton(Eto)/Newton/MainForm.jeto
Event Handler: https://github.com/morphx666/Newton/blob/f21a8420442d0eaf6ba07598dc594b3dd7f79d63/NewtonEngine/Common.cs#L326

**Comment by cwensley** [comment]
@morphx666 to get key events on a Drawable, you need to set CanFocus = true so it can get keyboard focus, and give it keyboard focus by calling Focus() or clicking on it.  

As for the Form not getting the KeyDown it could be a bug, but the above should work for you.

**Comment by morphx666** [comment]
Thanks @cwensley, attaching the `KeyDown` event to the `Drawable` control and setting the `CanFocus` property to true worked perfectly!
