### ISSUE TITLE
[Mac] shortkey to open a help

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1657]
I want to open a help page starting from my menu, and I'd like to add the standard shortkey Coomand+?, but I cannot find it among the identifiers in the enum Eto.Forms.Keys
I only found Keys.Help but it does not have any effect (was it meaat for old keyboard layouts?)

Would it be possible to add something like this?
```
Shortcut = Application.Instance.CommonModifier | Keys.QuestionMark;
```

## Specifications

  - Version: 2.4.0
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13

**Comment by cwensley** [comment]
Unfortunately, it looks like macOS hard-codes that key combo to go to the Help menu's search (try it with Safari, Finder, etc).  I can't seem to get it to work (on macOS 10.15.4) even if I remove the Help menu and manually set the NSMenuItem's KeyEquivalent with a style like so:

```
Style.Add<ButtonMenuItemHandler>("help", h =>
{
	h.Control.KeyEquivalent = "?";
	h.Control.KeyEquivalentModifierMask = NSEventModifierMask.CommandKeyMask;
});
```

This should theoretically work, but I think macOS is interfering so there's nothing that can be done afaict.

**Comment by msasso69** [comment]
ok, thanks for trying

**Comment by cwensley** [comment]
You're welcome, thanks for reporting it.  I'll close the issue as there's nothing actionable that can be done right now.
