### ISSUE TITLE
How would I implement Eto for my own UI system?

### ISSUE THREAD

**Issue by Thraka** [picoe/Eto#1663]
I'm just discovering this framework, but I'm curious, how would someone implement it into something else, like MonoGame, or SFML, or some other graphical rendering framework that could use a UI?

Up front it seems that the Eto framework is designed in a generic way that needs a provider of some sort to creating the true backing objects for all the UI stuff. How do I design and provide that?

**Comment by cwensley** [comment]
Yes, Eto.Forms is simply an abstraction on top of other UI toolkits so this is certainly possible.

I would suggest getting familiar with one of the existing platform implementations, such as Eto.Wpf or Eto.Mac64.  They are all put together using the same way as you'd create your own [custom platform controls](https://github.com/picoe/Eto/wiki/Custom-Platform-Controls)

The first control(s) to focus on would be Platform, Application, Form, Dialog, and TableLayout.

Hope this helps!

**Comment by Thraka** [comment]
Thanks for the reply. I'll check it out.
