### ISSUE TITLE
Error "LSOpenURLsWithRole() failed with error -10810" occurs under macOS Catalina 10.15.4 when compiling in Release mode

### ISSUE THREAD

**Issue by morphx666** [picoe/Eto#1670]
I have already tried many of the "fixes" suggested on other forums by setting the appropriate extended attributes (xattr) as well as setting the executable flag (chmod) for the compressed package.

I've also tried opening the file using CTRL+click, as suggested elsewhere.
Nothing's worked so far.

## Expected Behavior

When double clicking the `App.Desktop.app` under macOS, the program should run.
Running it from the terminal, using `open -a App.Desktop.app` should also work.

## Actual Behavior

When running the program via Finder, it immediately closes without giving any error message.
When running it from the terminal, it outputs the `LSOpenURLsWithRole() failed with error -10810`  error.

## Steps to Reproduce the Problem

  1. Create an Eto.Forms project targeting a "Single Windows, Linux, and Mac desktop project" with "Full .NET Framework" support, using "Json" as the forms' design language.
  2. Compile the project in Release mode.
  3. Try to run it under macOS Catalina

## Code that Demonstrates the Problem
This is a "toy" project I'm using to test Eto.Forms under non-Windows platforms.
I'm hoping that the Eto.Forms version looks and behaves as closely as possible to the WinForms version.
https://github.com/morphx666/SharpFlappyBird

## Specifications

  - Version: Eto.Forms 2.5.0
  - Operating System(s): macOS Catalina 10.15.4

**Comment by cwensley** [comment]
Hey @morphx666, thanks for reporting the issue!

When compiling for release, Eto uses mkbundle to bundle up your app into a single executable to pack up into the .app bundle.  I think a number of things are going on here:

1. The native .dylib is not being loaded by your code nor included when bundling using Eto
2. Any file with "Copy to output" is not being copied to the output directory, which in the case of mkbundle is undefined at this point.  The question is, should these be copied to the MonoBundle folder (which no longer exists), the Resources folder, or the MacOS folder?
3. In debug, Copy to output files will not retain their folder structure

I'll see what I can do to fix those up and make this work better out of the box.

**Comment by morphx666** [comment]
Thanks for the prompt reply... looking forward to version 2.5.2
