### ISSUE TITLE
Eto.Forms.Control does not Expose BackgroundImage property

### ISSUE THREAD

**Issue by Razcer** [picoe/Eto#1674]
## Problem
Eto.Forms.Control does not Expose BackgroundImage property

## Code That Shows Issue
```
[Control Metadata]
...
        public virtual bool Visible { get; set; }
        public Color BackgroundColor { get; set; }
// Declaration would go here I believe.
        public Container VisualParent { get; }
...
```
## Current Workaround
I am currently adding a background image to the Form in this manner but it then has issues with other controls added to the form.
```
((winForms.Control)this.BackgroundStackLayout.ControlObject)
     .BackgroundImage = (System.Drawing.Image)backgroundImage.ControlObject;
```

## Specifications

  - Version: 2.5.0
  - Platform(s): WinForms (Gtk in future)
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hi @Razcer, use a [`Drawable`](http://api.etoforms.picoe.ca/html/T_Eto_Forms_Drawable.htm) (which is also a container), something like this:

```
var drawable = new Drawable();
drawable.Paint += (sender, e) => {
  e.Graphics.DrawImage(myImage, 0, 0);
};
drawable.Content = /* your child controls */
myForm.Content = drawable;
```

Hope this helps!

**Comment by Razcer** [comment]
I missed some stuff I guess
BackgroundStackLayout is a Eto Stacklayout
backgroundImage is an Eto BitMap

**Comment by cwensley** [comment]
Thanks, but I'm not sure how that changes my recommendation?

**Comment by Razcer** [comment]
It doesn't, I was just adding info.
The code you gave worked to add the image correctly, thank you.
I'm having another issue with trying to set the top padding for a series of labels on that main background control. I want to drop them form the top but not move them in so Padding: X isn't working as it moves the label x,y. 
Further there's an issue with fonts that I need to understand. How to load an Eto.Drawing.Font from an Embedded application font file and not a system font?

**Comment by cwensley** [comment]
Hey @Razcer, perhaps https://gitter.im/picoe/Eto would be a good place to ask questions.  It sounds like this particular issue is resolved so I will close it.
