### ISSUE TITLE
Raspberry Pi 3 B+ Build: "Out of Memory"

### ISSUE THREAD

**Issue by JohnnyErnest** [picoe/Eto#1675]
<img width="960" alt="EtoError3" src="https://user-images.githubusercontent.com/25945156/81346374-cc3cbb80-907f-11ea-8d08-4302a4cf7b80.png">

Please note that I also recently installed .NET Core 3.1 and ASP .NET Core 3.1 on the Raspberry Pi 3 B+. which may be a contributing factor. 

This is the message that came after trying to run **build.sh** on a fresh boot of the Pi, which had previously hung during the same build operation. The Mac64 parts of the build will still try to run on Raspbian, but after a reboot the scripts would finish eventually.

I don't imagine this problem occurs on newer 4GB Raspberry Pi 4B models, but just posting the error as a cautionary for anyone with the same unit that you may need no other apps running in order to build. EmbedEtoInWinForms.exe sample is working now.

**Comment by cwensley** [comment]
@JohnnyErnest thanks for the report, it is really appreciated.

This looks like a memory issue when building (specifically, linking the Eto.Test.Mac64 app into a single exe), unrelated to Eto.  Considering you don't actually need to compile Eto on a Raspberry Pi as you can use the NuGet packages, or compile on a different platform then copy to RPi, I don't see a need to try to fix this (if even possible).

Most likely building the Debug configuration would work, or disabling the linking process.

**Comment by cwensley** [comment]
Closing as this is not a problem with Eto while running only building.  I suggest building on a full fledged computer then simply running on Raspberry Pi.
