### ISSUE TITLE
How should one use ImageHandler?

### ISSUE THREAD

**Issue by piersdeseilligny** [picoe/Eto#1677]
I apologize if this is a slightly basic question, but I can't seem to figure it out.

On macOS, I'd like to style `NSImage`, in order to define it as a [template image](https://developer.apple.com/documentation/appkit/nsimage/1520017-template), so that it responds to switching dark/light theme (this image is inside a `ToolbarItem`).

In order to do so, I've tried setting `image.Style = "templateimage"` and then adding the following style:
```
            Eto.Style.Add<ImageHandler<NSImage,Image>>("templateimage", handler => {
                handler.Control.Template = true;
                handler.Control.Tint(NSColor.Blue);
            });
```

However it's obviously not working, mainly because I don't think I understand how one should use `ImageHandler`. Would it be possible to have a little guidance?

**Comment by cwensley** [comment]
Hey @piersdeseilligny, try using `BitmapHandler` instead.  This works for me:

```
Eto.Style.Add<BitmapHandler>("template", h =>
{
	h.Control.Template = true;
	h.Control.Tint(NSColor.Blue);
});
```

then:
```
var bmp = Bitmap.FromResource("Eto.Test.Images.TestImage.png");
bmp.Style = "template";
```

Hope this helps!

**Comment by piersdeseilligny** [comment]
Thanks for the fast reply @cwensley ! In your example, did it correctly tint the image? It doesn't appear to be working for me:

![image](https://user-images.githubusercontent.com/42496508/81797280-785e2680-9506-11ea-9977-0ed340f75b61.png)

I've used the BitmapHandler as you have - and the style code is being executed - but the image isn't changing in the slightest. Using `h.Control.Background` doesn't appear to working either.

**Comment by cwensley** [comment]
Ah yes, I thought that was a standard API but it's actually an extension method in Eto that returns a tinted _copy_ of the image.

Something like this would work then:
```
Eto.Style.Add<BitmapHandler>("template", h =>
{
	h.Control.Template = true;
	h.Control = h.Control.Tint(NSColor.Blue);
});
```

.. just be sure to set the style before using the bitmap anywhere else.

**Comment by piersdeseilligny** [comment]
So that does technically work, but there seems to be an issue with using an image with `Template = true` inside a ToolbarItem. I set up the following test:

```c#
var bmp = Bitmap.FromResource("Test.addfile.png");
bmp.Style = "template";

imageView.Image = bmp;
var buttonToolItem = new ButtonToolItem() { Text = "Add Files", Image = bmp};
ToolBar = new ToolBar() { Items = { buttonToolItem } };
```

The ImageView works fine:

![image](https://user-images.githubusercontent.com/42496508/81804830-b1e85f00-9511-11ea-9cdf-3232353384fb.png)
![image](https://user-images.githubusercontent.com/42496508/81804865-c75d8900-9511-11ea-992e-959b17a671c8.png)

As you can see, it's a slightly different grey-ish color depending on the theme (I checked with Photoshop, these are actually different greys, it's not an optical illusion). However, using the `ButtonToolItem` doesn't change depending on context, as Template Images should:
![image](https://user-images.githubusercontent.com/42496508/81805381-a8132b80-9512-11ea-821e-82a5975cd362.png)

The white .png remains white, no matter what. 

Does Eto use the `LockFocus` API in `ButtonToolItem` by any chance? The Xamarin.Mac documentation [warns that doing so breaks Template Images](https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/image#working-with-template-images)

**Comment by cwensley** [comment]
Thanks @piersdeseilligny for pointing that out, I didn't know that using lockFocus breaks things.  In that case, you cannot use that Tint API that Eto provides, and instead do something similar to the Xamarin.Mac documentation you linked to (note this won't work on Eto.Mac64 currently as it does not have the required API):

```c#
Eto.Style.Add<BitmapHandler>("template", h =>
{
	var sourceImage = h.Control;
	sourceImage.Template = true;
	h.Control = NSImage.ImageWithSize(sourceImage.Size, false, rect =>
	{
		sourceImage.DrawInRect(rect, CGRect.Empty, NSCompositingOperation.SourceOver, 1f);

		NSColor.Blue.Set();
		NSGraphics.RectFill(rect, NSCompositingOperation.SourceAtop);
		return true;
	});
});
```

If necessary, the `NSImage.ImageWithSize()` api could be added to monomac so you can use it with Eto.Mac64.

The slightly bad news: Eto has some resizing code for the toolbar that doesn't handle the above scenario (NSCustomImageRep reports PixelsWide/High as 0), but that is relatively easy to fix.

**Comment by cwensley** [comment]
Ok, the above should now work now that #1713 is merged.  Thanks for the report!
