### ISSUE TITLE
Button text is not available to Microsoft screen reader

### ISSUE THREAD

**Issue by elsanussi-s-mneina** [picoe/Eto#1679]
## Expected Behavior
The Microsoft Narrator screen reader should read the text on a button when the user navigates to that button using the keyboard.

I have had inconsistent results with menu items. 

## Actual Behavior
It only says "button". The text on the button is not read out. 

## Steps to Reproduce the Problem
  1. Create an Eto Form.
  2. Put a button on the form.
  3. Run the Eto Forms application in Windows.
  4. Turn on Windows Narrator.
  5. Navigate to the Window, and press Tab.

  - Version:
  - Platform(s): WPF, WinForms
  - Operating System(s): Windows 8.1

**Comment by elsanussi-s-mneina** [comment]
The following link may help find a solution. It explains which properties could be set in WPF [Audio descriptions with Narrator](https://docs.microsoft.com/en-us/learn/modules/narrator-and-voice-input/2-audio-descriptions-with-narrator).

**Comment by cwensley** [comment]
Hey @elsanussi-s-mneina, thanks for reporting the issue!

**Comment by elsanussi-s-mneina** [comment]
You are welcome. The suggestion to test out Eto Forms accessibility on multiple platforms came from someone else.

**Comment by cwensley** [comment]
Thanks again for reporting the issue.  It turned out to be a quick fix and I found the toolbar buttons weren't working quite right either.  Feel free to report any accessibility issues in the future, it is really appreciated!
