### ISSUE TITLE
Translate PropertyGrid displayed text

### ISSUE THREAD

**Issue by thomas-goerlich** [picoe/Eto#1683]
## Expected Behavior
I'd like to translate the displayed text in a PropertyGrid.

## Actual Behavior
It's not possible to add non static values in the attributes. So i'm not sure how i would translate the displayed text on the left side of the property grid or in the sections title.
I have my resx file and would like to use values from that to display.

## Code that Demonstrates the Problem

```
[Display(GroupName = "Misc", Name = "Play sound")]
```

See also test project: https://github.com/picoe/Eto/blob/develop/test/Eto.Test/Sections/Controls/PropertyGridSection.cs#L162 

## Specifications

  - Version: 2.5.0
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
@thomas-goerlich,

Try using the [`ResourceType`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.resourcetype?view=netcore-3.1#System_ComponentModel_DataAnnotations_DisplayAttribute_ResourceType) property of the `DisplayAttribute`.  This allows you to specify a class (resources or not) that returns the localized version of the strings.

**Comment by thomas-goerlich** [comment]
Oh man, Thanks! I didn't know that. Work perfectly.
