### ISSUE TITLE
DynamicLayout/TableLayout multiple controls per cell?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1684]
Is it possible to add multiple controls per cell in either `DynamicLayout` or `TableLayout`?

Failing that, is it possible for a control to span (take up) more than one cell horizontally or vertically in either layout or perhaps in another one I am unaware of?

Thank you.

PS @cwensley 
I remember there is a page somewhere (in the wiki?) where you list software developed with Eto. I do not want to spam but you might want to know that my employer has Mac and Linux beta ports of their software developed with Eto. If you are interested in having a look at them, let me know.

**Comment by LaraSQP** [comment]
Worked around my ignorance on this issue by grouping controls with `StackLayout` before adding them to the `DynamicLayout`.

Good enough for me.

**Comment by cwensley** [comment]
Just FYI, using a DynamicLayout you can add multiple controls in a cell by using  `BeginVertical` and `EndVertical`.

Fore example:

```c#
var layout = new DynamicLayout();

layout.AddRow("Some Controls", "Beside Each other");

layout.BeginHorizontal(); // start a new row

layout.BeginVertical();
layout.AddRow("These", "go under 'Some Controls'");
layout.EndVertical();

layout.BeginVertical();
layout.Add("These");
layout.Add("go under the right label");
layout.Add("vertically");
layout.EndVertical();

layout.EndHorizontal(); // end the row
```

**Comment by LaraSQP** [comment]
Much cleaner. Thank you.
