### ISSUE TITLE
Attached dialogs on macOS don't close until you move your mouse

### ISSUE THREAD

**Issue by harry-cpp** [picoe/Eto#1685]
Attached dialogs on macOS don't close until you move your mouse.

## Steps to Reproduce the Problem

1. Open eto test app and navigate to the "Dialog" section.
2. Set `DisplayMode` to `Attached`
3. Show the dialog
4. Click the close button without moving your mouse

## Specifications

  - Version: 2.5.1 development brach
  - Platform(s): Mac
  - Operating System(s): macOS

**Comment by cwensley** [comment]
Thanks for reporting the issue, @harry-cpp.  I'll investigate.
