### ISSUE TITLE
Clipboard does not take Unicode strings

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1686]
I'm trying to put strings like `əbæk` in the `Clipboard` via the `Text` property but only get noise.

Inspecting the clipboard (Windows 10) shows only a `CF_TEXT` entry.

There is no `CF_UNICODETEXT` entry or anything else.

**Comment by LaraSQP** [comment]
It appears not to be a problem for Gtk.

**Comment by LaraSQP** [comment]
It appears not to be a problem for `Mac` either.

Good enough for me.

**Comment by cwensley** [comment]
Thanks for the report. This should be fixed in the latest CI build.
