### ISSUE TITLE
Gtk ComboBox does not work with Fonts.Monospace(...)

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1687]
As the title says, assigning `Fonts.Monospace(...)` to the `Font` property of a `ComboBox` in `Gtk` results in nothing being displayed. The text is there but invisible. Some rendering issue, I presume.

`Wpf` works fine.

Note that this is not an issue with other controls, for example, `ListBox`, which works as expected with monospace fonts.

**Comment by LaraSQP** [comment]
Apparently `Gtk` does not create the font until the `ComboBox` is displayed so the following was causing the problem:

> cb.Font = Fonts.Monospace( cb.Font.Size );

Still, `Gtk` does create the font in the constructor of other controls, such as `Button`, so the following works:

> var bt = new Button();
> cb.Font = Fonts.Monospace( bt .Font.Size );

Good enough.

**Comment by LaraSQP** [comment]
FYI, the `ListBox` control also chokes on the font like `ComboBox` does.

`Label` works like `Button` and, imo, like all controls should work.

This is a `Linux` and `Mac` problem. `Wpf` works fine.

**Comment by cwensley** [comment]
Thanks for reporting the issue.. Yes, all controls should report a font.

**Comment by LaraSQP** [comment]
All have a font but **only** after they are displayed.

Except on `Wpf`, when they do at creation (i.e., constructor) and which is most convenient.

**Comment by cwensley** [comment]
Hm, odd, but I do agree that the Font property should not return null even when not displayed.
