### ISSUE TITLE
Sample code for Apple's StoreKit or some in-app purchase alternatives?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1689]
Has someone submitted an `Eto` app the Apple store and, if so, how are you blessed folk handling in-app purchases and all that jazz?

The documentation speaks of some `StoreKit` which I cannot begin to fathom how to make work with c#.

https://developer.apple.com/documentation/storekit

**Comment by LaraSQP** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/platform/in-app-purchasing/store-kit-overview-and-retreiving-product-information

Xamarin?

**Comment by cwensley** [comment]
@LaraSQP yes, you need to use Xamarin.Mac (Eto.XamMac2) which contains all of the API's for platform-specific things like StoreKit.

**Comment by LaraSQP** [comment]
Got it, thanks.
