### ISSUE TITLE
Dropping files no longer works after updating from 2.4.1 to 2.5.0

### ISSUE THREAD

**Issue by piersdeseilligny** [picoe/Eto#1691]
## Expected Behavior

A form with `AllowDrop==true` should respond to files being dragged from the file explorer onto it, by firing the `DragDrop` event (this is the behaviour on v2.4.1)

## Actual Behavior

This doesn't work. None of the other drag events are fired either (`DragOver`, `DragEnter`, etc...)

## Steps to Reproduce the Problem

  1. Create an Eto.Forms project with v.2.5.0
  2. Set `AllowDrop` on a control or form to true and subscribe to the `DragDrop` event
  3. Observe that the event is never fired

## Code that Demonstrates the Problem

```
[Paste your code here]
```

## Specifications

  - Version: 2.5.0
  - Platform(s): WPF, may also occur on other platforms
  - Operating System(s): Windows 10 (build 19041)

**Comment by cwensley** [comment]
@piersdeseilligny thanks for reporting the issue!

**Comment by cwensley** [comment]
Hey @piersdeseilligny,

Thanks again for reporting the issue.  In 2.4.1, you are right in that you only needed to handle the `DragDrop` event.  However, this only worked on Wpf (and probably WinForms).  This did not work with any other platform.

In 2.5 you need to handle DragEnter and/or DragOver and set `e.Effects = DragEffects.[some effect]`.  Wpf and Gtk had a bug in that you _had_ to set this on DragOver, though it should only be required for DragEnter so you can only test once for the existence of certain data (e.g. file list, text, etc) before enabling the drop.
