### ISSUE TITLE
Eto.Forms.Window.get_Screen() exception?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1696]
Testing with the latest Ubuntu version, Mono, etc.

Eto 2.5.1 has broken my app on launch with the following:

> Marshaling show signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: VTable setup of type Eto.GtkSharp.Forms.ScreenHandler failed
  at Eto.Forms.Window.get_Screen () [0x00006] in <9f31206c67204fa29c9b971807a7db11>:0 
...

**Comment by cwensley** [comment]
@LaraSQP check to ensure all dll's are the correct version in your output folder.

**Comment by LaraSQP** [comment]
You rock, sir.

(I am an idiot)
