### ISSUE TITLE
[MAC] Unable to set 'EnableAnimation' in the ExpanderHandler

### ISSUE THREAD

**Issue by bow-meow** [picoe/Eto#1709]
## Expected Behavior
setting 'EnableAnimation' to false would set the property in the propertystore to false.

## Actual Behavior
setting 'EnableAnimation' to false does nothing.

## My thoughts
The propertystore has Get & Set methods that take a default value. These default values are based on the type if not set.
This means that if there is no default value set for a boolean type, the default value will be false.

In the EnableAnimation getter, there is a default value set to true, but there is no default value for the setter.

I believe the fix for this would be to set both the get/set default values to true, if that is the default behaviour you want.

These are just my thoughts though, I could be wrong 

  - Version: lastest
  - Platform(s): Mac, XamMac
  - Operating System(s): macOS 10.13

**Comment by cwensley** [comment]
Thanks @bow-meow for submitting the issue!

You're right, it should be passing the default of `true` to the set method.
