### ISSUE TITLE
Windows Application Packaging Project unable to package WPF Eto app

### ISSUE THREAD

**Issue by piersdeseilligny** [picoe/Eto#1711]
## Expected Behavior

Packaging Eto WPF project should work just the same as packaging a normal WPF project.

## Actual Behavior

Windows Application Packaging Project fails when the source app is an Eto WPF project.

## Steps to Reproduce the Problem

  1. Attempt packaging a WPF Eto app from a [Windows Application Packaging Project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
  2. Observe that the packaging project is unable to build, and triggers `error MSB4057: The target "GetDeployableContentReferenceOutputs" does not exist in the project.`

## Specifications

  - Version: 2.5.2
  - Platform(s): WPF
  - Operating System(s): Windows 10 (build 19041)

**Comment by cwensley** [comment]
@piersdeseilligny thanks for the report.  Are you trying to package a .NET Core (netcoreapp3.1) application or .NET Framework (net4xx)?

If it is a .NET Core app, this might help: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/packaging-a-net-core-3-0-application-with-msix/ba-p/386432

**Comment by cwensley** [comment]
I also wonder if the packaging just doesn't work with sdk-style csproj's...

**Comment by cwensley** [comment]
Hm, also appears to be issues using multiple targets in your .csproj as well: https://stackoverflow.com/questions/58863918/msix-and-multiple-target-frameworks-not-working

**Comment by piersdeseilligny** [comment]
It uses netcoreapp3.1, and I've followed the instructions in that article from Microsoft. Also, I'm not specifying multiple targets, so I think it may have to do with the template .csproj which eto makes, which appears to be quite different from the default WPF app one.

**Comment by cwensley** [comment]
Hm, try replacing `<TargetFrameworks>` (which is default for Eto templates) with `<TargetFramework>` (note the 's')
