### ISSUE TITLE
Localizable default Menu titles on every platform (Especially Gtk, Wpf)

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1716]
On the Eto.Mac{,64} and XamMac2 platforms all menu default items can be localized using the `Application.LocalizeString` event.

On all other platforms (Gtk, Wpf, WinForms) this is currently not the case; but I think that would be useful, not only for consistency between platforms.

If you want, I can prepare a pull request...

## Specifications

  - Version: Current CI build
  - Platform(s): Gtk, Wpf, WinForms
  - Operating System(s): n/a

**Comment by cwensley** [comment]
Hey @ManuelHu, thanks but I don't believe there are any default menu items other than on macOS..  what exactly would you want to use `Application.LocalizeString` for?

**Comment by ManuelHu** [comment]
I mean the File, Quit and Help menu items. Those are also localized on Mac, but not on other platforms.

**Comment by cwensley** [comment]
Ah, you are right.. the ApplicationMenu and HelpMenu properties have hard coded strings, which I overlooked.  Yes, a PR would be very welcome.
