### ISSUE TITLE
Bug in Wpf.GraphicsHandler

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1723]
In DrawImage-method should check for !=0 not >0, because can also be negative

```
public void DrawImage(Image image, RectangleF source, RectangleF destination)
...
// bool translate = source.X > 0 || source.Y > 0; 
bool translate = source.X != 0 || source.Y != 0;
```

**Comment by cwensley** [comment]
Hey @TomQv, no source should not be negative, as it is outside the bounds of the image.  The destination could, however.

**Comment by cwensley** [comment]
Closing as the source should lie in the bounds of the image.
