### ISSUE TITLE
[Mac] MouseMove, MouseUp with primary button in GridView, ListBox doesn't work drag drop.

### ISSUE THREAD

**Issue by MingboPeng** [picoe/Eto#1726]
## Expected Behavior
I am trying to make the ListBox and GridView as the source of DragDrop action on mac, both MouseMove and MouseUp should work with primary click, drag. I have the same code works very well on Windows WPF, but having trouble on Mac.

## Actual Behavior
GridView, ListBox don't work the mouse primary button (both touchpad and mouse on Mac). In MouseMove (ListBox), and MouseUp (GridView and ListBox), nothing happens with primary button click or pressed, but works with alternate button.

## Steps to Reproduce the Problem

  1. MouseUp, MouseMove with primary button in GridView, ListBox doesn't work.

## Code that Demonstrates the Problem

```
var library_GV = new GridView();

library_GV.MouseUp += (sender, e) =>
            {
                if (e.Buttons == MouseButtons.Primary)
                {
                    // this is never happens
                }
            };
```

## Specifications

  - Version: 2.5.2
  - Platform(s): Mac, XamMac
  - Operating System(s): macOS 10.14.6

**Comment by cwensley** [comment]
Hey @MingboPeng, thanks for reporting the issue.

`MouseUp` does not get called on some platforms unless you also handle `MouseDown` and set `e.Handled = true`. This unfortunately also circumvents all of the basic functionality of the control though.

However, to properly implement drag/drop from a GridView, something [like this](https://github.com/picoe/Eto/blob/develop/test/Eto.Test/Sections/Behaviors/DragDropSection.cs#L119-L133) is what you need to do.

Hope this helps.

**Comment by MingboPeng** [comment]
Hi @cwensley, thanks for your reply. It is good to know this MouseUp needs to work with MouseDown.

Yes, I found your examples are very helpful. 
I am closing this issue unless you think it is worth to keep it open.

-Mingbo
