### ISSUE TITLE
Attempting to run a script in WebView Crashes

### ISSUE THREAD

**Issue by Krutonium** [picoe/Eto#1738]
## Expected Behavior
The script runs

## Actual Behavior
A crash with this output: https://paste.ubuntu.com/p/R7qxs632tR/

## Steps to Reproduce the Problem

  1. Try to inject a script into a page once it loads

## Code that demonstrates the problem
```
var Twitch = new WebView();
Twitch.Url = new Uri("https://www.twitch.tv/popout/" + Settings.Username + "/chat?popout=");
WebClient wb = new WebClient();
string Script = wb.DownloadString("https://cdn.frankerfacez.com/static/ffz_injector.user.js");
Twitch.DocumentLoaded += (sender, args) => Twitch.ExecuteScript(Script););
```

## Specifications

  - Version: 2.5.2
  - Platform(s): GTK
  - Operating System(s): Arch Linux
  - Runtime: .Net Core

**Comment by cwensley** [comment]
Thanks for reporting the issue!  This is due to .NET Core's inability to marshal generic delegates, whereas mono does not have the same issue.  See https://github.com/dotnet/runtime/issues/13197 for reference. 

We just need to use a non-generic delegate instead.  Annoying, but easy enough.
