### ISSUE TITLE
Gtk: Recent CI build broke Alt-Shortcuts for buttons with "&" in Text

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1739]
Somwhere between `2.5.3-ci-20200612.4` and `2.5.3-ci-20200625.10` buttons with an Ampersand in their Text stopped working like before. Before, the letter was underlined when the ALt key was pressed, now the underscore is shown before the letter (see screenshot), and all the time... And the shortcuts don't work any more.

![grafik](https://user-images.githubusercontent.com/10050780/85833752-8a341a00-b792-11ea-9e37-7d7de675a71b.png)

On menus, everything works fine. This is only about normal buttons.

## Expected Behavior

SHoprtcuts work and show as before, as you would expect (only when Alt key pressed).

## Actual Behavior
Shortcuts are always shown (in a weird way) and do not work at all.

## Specifications

  - Version: 2.5.3-ci-20200625.10
  - Platform(s): Gtk
  - Operating System(s): Fedora 32

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I'm not sure why that was changed, just an oversight on my part.
