### ISSUE TITLE
[Enhancement] Zoomable and scrollable ImageView

### ISSUE THREAD

**Issue by onepiecefreak3** [picoe/Eto#1741]
I wanted to realize an ImageView that at least has zoom and scroll support just like the WinForms equivalent by Cyotek found here: https://github.com/cyotek/Cyotek.Windows.Forms.ImageBox

There already is an open issue asking for Zoom support here: https://github.com/picoe/Eto/issues/418, but this issue is ~4 years old.

The main question I would have to creating such a control would be, what the best approach of inheritance would be. Should I inherit from ImageView and expand it? Or should I use a Drawable and add scroll support manually, since I can't mix Drawable and Scrollable in a single inheritance?
The main problem is, that I either can't mix drawable and scrollable in one class through inheritance and ImageView does not expose its drawing methods.

I would like some pointers where to start and try to realize this control and maybe the result can be PR'ed to Eto.Forms to solve linked issue and a long standing feature request.

**Comment by rafntor** [comment]
Hi, I set up a little repo here https://github.com/rafntor/Eto.ImageViewEx with a basic but working way of implementing what you ask for. Feel free to expand on it !

**Comment by onepiecefreak3** [comment]
Oh, I really like this control, that's exactly what I needed! Thanks.
