### ISSUE TITLE
How to compile on Win10/VS 2019?

### ISSUE THREAD

**Issue by devmaestro1** [picoe/Eto#1742]
Hello,
I have been trying for several days now to compile this source under Win10/VS 2019 and have had no success. I would be grateful if someone could help me. Usually, I would expect just to open the sln file and compile but I see that with all the GTK dependencies, that is not possible.  With that said, I have also tried to just compile some of the Winforms projects but unfortunately I get a series of errors such as:

`Error	NETSDK1005	Assets file 'C:\Users\Name\Documents\Projects\Other\Eto-develop\artifacts\obj\Windows\Eto.WinForms\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project.	Eto.WinForms	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	`

When I try to compile the source with build.cmd from a Visual Studio 2019 Developer Prompt, I get:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(282,5): error MSB3202: The project file "C:\Users\Name\Documents\Projects\Other\Eto-develop\lib\monomac\src\MonoMac.cs
proj" was not found. [C:\Users\Name\Documents\Projects\Other\Eto-develop\src\Eto.sln]
```

I've obviously tried searching the Issue list in GIT and also doing a number of Google searches but I can only assume that I am doing something wrong because I am getting lots of other compile errors regarding missing dependencies.

Can someone kindly give me some steps that I should be using to compile Eto.Forms just for Winforms to begin with?

Thanks.

**Comment by cwensley** [comment]
After loading Eto.sln, select "Windows" from the platform drop down, this excludes Xamarin.Mac and Gtk2/3 projects.  You  need to have the .NET Core SDK 3.1 installed to compile.

There is a submodule in this repo (monomac). It appears you did not do a recursive clone, or you just downloaded the .zip archive of the source (which does not include submodules).  Without this, the nuget restore would probably fail causing your first error message.

Do something like this to clone this repo properly:

```
git clone --recursive https://github.com/picoe/Eto.git
```

Hope this helps.

**Comment by devmaestro1** [comment]
Thank you so much, @cwensley! Such a simple fix. I was using a zip download instead of a GIT clone.
The entire build went through perfectly now!
