### ISSUE TITLE
Visual Studio-style docking in 2020

### ISSUE THREAD

**Issue by devmaestro1** [picoe/Eto#1744]
Hello,

I am just wondering what the state of Eto.Forms is for docking in 2020. I've looked at issue #753 but following the threads I am not clear whether this was resolved. 

I was hoping to use something like [DockingPanelSuite](http://DockingPanelSuite.com) within Eto.Forms but not sure if this is possible. I saw that VisualSEO Studio seemed to include these libraries in their code, but couldn't actually see any actual docking functionality within the app (It looks like maybe they are maybe using the tabbing functionality of DPS?).

I don't suppose anyone has a reference at some projects I can look at with this sort of functionality (or share some of their own code) to get me started?

Thank you!

**Comment by cwensley** [comment]
Hey @devmaestro1,

The resolution was that this type of functionality is/should not be part of core Eto.  Eto.Toolkit would be an appropriate place for such a control.

This could theoretically be implemented using the existing Eto Window/Screen/Splitter/etc api's, however no one has contributed to this effort yet.

**Comment by devmaestro1** [comment]
Thanks again for your reply, @cwensley . Would you have a rough idea of how much effort it would be to make a very simplistic version of a window docking system within Eto.Forms? If I understood your reply correctly, it would not require platform-specific knowledge, it would just need to be implemented within the existing Eto API?

**Comment by cwensley** [comment]
@devmaestro1, sorry I do not know how much effort it would take.  It _shouldn't_ require platform-specific knowledge, theoretically.

I'm closing this one in favour of tracking it with https://github.com/picoe/Eto.Toolkit/issues/9, thanks again for submitting the issue.
