### ISSUE TITLE
Eto.Drawing vs System.Drawing

### ISSUE THREAD

**Issue by devmaestro1** [picoe/Eto#1746]
Hello,

I am currently trying to evaluate Eto.Forms as a solution for a pre-existing project that uses Winforms System.Drawing. I have done a quick review of some of the primitive functions available in Eto.Drawing and it looks very similar to System.Drawing.

Would it be correct to say that to port my project over to Eto, I would just need to update the references of System.Drawing to Eto.Drawing? Or would it be a lot more work than that? Could someone share any experience of the coverage and/or any issues that may occur in the process?

Thank you.

**Comment by cwensley** [comment]
@devmaestro1 the API's are similar, but they are not exact.  You will have to rework your code to work with Eto's API's.  There's also advanced System.Drawing stuff that may not exist in Eto.Forms, such as some of the gradient operations.

It really depends on your existing codebase and what things you are doing on how much effort would be involved.

What I would suggest is to take a small subset of your code and do a "trial port" to see what sort of things you might run into when porting, perhaps in a test app.  You can then extrapolate on how long it'll take based on the complexity of the rest of your code.
