### ISSUE TITLE
Use Winforms on Windows Versions less then 10

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#1750]
Eto Forms should use wpf for windows 10 or anything newer however I think Winforms should be used for anything older then window 10.

The Reason for this is that Winforms looks native for older os's however it isn't native on windows 10
I would suspect in any newer releases of windows they will also be using WPF

Older os's aren't supported by microsoft anymore however they are still used by some people.

The issue here is do we want Eto to look native on every platform?

**Comment by cwensley** [comment]
Yes, Eto.Forms will default to Wpf for `Eto.Platform.Detect` on Windows, but you can customize this however you like with something like this in your main() method for your windows launcher application:

```
        class MainClass
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var platform = Environment.OSVersion.Version.Major >= 10 ? Eto.Platforms.Wpf : Eto.Platforms.WinForms;
			new Application(platform).Run(new MainForm());
		}
	}
```

Hope this helps!

**Comment by Shadowblitz16** [comment]
so if I was on windows 7 then it would use winforms?

**Comment by cwensley** [comment]
Correct.

**Comment by Shadowblitz16** [comment]
ok I will close this then thankyou
