### ISSUE TITLE
PropertyGrid crashes on macOS.

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#1755]
## Expected Behavior
Should be able to use the PropertyGrid

## Actual Behavior
It crashes! aaaah!

## Steps to Reproduce the Problem

  1. Open Eto.Test
  2. Navigate to the PropertyGrid section

## Specifications

  - Version: 2.5.3
  - Platform(s): Mac, XamMac
  - Operating System(s): macOS 10.15.6

**Comment by harry-cpp** [comment]
> It crashes! aaaah!

Love the behavior description XD
