### ISSUE TITLE
Make the last cell in a TreeGridView auto size to the full width of the control

### ISSUE THREAD

**Issue by morphx666** [picoe/Eto#1759]
I have a `TreeGridView` where the last column needs to be as wide as possible.

Here, I need the "Progress" column to expand to fill the full available width.

![image](https://user-images.githubusercontent.com/12353675/89147776-b1b29b00-d525-11ea-9f6c-9dd116a2b335.png)

Under WinForms, this can be done for the `ListView` control by setting the last column's width to -2

Is there anyway to do the same for the `TreeGridView` control?

**Comment by cwensley** [comment]
Duplicate of #718
