### ISSUE TITLE
Eto.Platform.Gtk + newer version of Gtk: failure

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#1761]
I'm working on making a Gtk3 based handler for gtksourceview using the recently published [GtkSourceSharp ](https://www.nuget.org/packages/GtkSourceSharp).

The latest Eto.Platform.Gtk has a dependency on GtkSharp >= 3.22.25.74
GtkSourceSharp has a depencency on GtkSharp >= 3.22.25.118

So I have two projects: the "neutral" EtoSourceView and the "gtk-specific" EtoSourceView.Gtk (see also attached
[EtoSourceView.zip](https://github.com/picoe/Eto/files/5022903/EtoSourceView.zip) )

Unfortunately, the EtoSourceView.Gtk does not build, because it references GtkSharp 3.22.25.118. The error message is:

The type 'Gtk.ScrolledWindow' cannot be used as type parameter 'TControl' in the generic type or method 'GtkControl<TControl, TWidget, TCallback>'. There is no implicit reference conversion from 'Gtk.ScrolledWindow' to 'Gtk.Widget'.	EtoSourceView.Gtk	D:\zandbak\EtoSourceView\EtoSourceView.Gtk\XmlTextAreaHandler.cs	

The type 'Widget' is defined in an assembly that is not referenced. You must add a reference to assembly 'GtkSharp, Version=3.22.25.74, Culture=neutral, PublicKeyToken=null'.	EtoSourceView.Gtk	D:\zandbak\EtoSourceView\EtoSourceView.Gtk\XmlTextAreaHandler.

I am at a loss how to solve this. I have tried to use the older GtkSharp, but then I get other errors. Also I have tried to use an app.config file with assembly redirect, but that also did not work. 

Any hints on how to proceed are much appreciated!

**Comment by cwensley** [comment]
@mennodeij, this appears to be because GtkSharp 3.22.25.118 is strong named, whereas the older version is not.  This is a breaking change for any binaries using the older GtkSharp, and they must be recompiled.

 So, the only option is to wait for Eto to switch to the strong named version.  Or, you _might_ be able to use the `AppDomain.CurrentDomain.AssemblyResolve` event to load the (newer) version.  Assuming there were no other ABI breaking changes.

**Comment by mennodeij** [comment]
Ah, _that_ is what it is. Well I'm glad that you found that out. I'll see what I can do to get it working now that I have a lead on where to start. Thanks 🙂

**Comment by harry-cpp** [comment]
Hmm, I'm just gonna revert strong naming, not worth breaking changes like these.

**Comment by mennodeij** [comment]
Thanks, that is very helpful!
