### ISSUE TITLE
Eto.Platform.Mac64 bundle doesn't recognize .NET 5

### ISSUE THREAD

**Issue by Berrysoft** [picoe/Eto#1762]
https://github.com/picoe/Eto/blob/a8f7dae2d0a10809c111876d5aac77374cda80ce/src/Eto.Mac/build/Mac.targets#L44

It checks if it is .NET Core by `TargetFramework`, but the value is `net5.0` when using .NET 5.

**Comment by cwensley** [comment]
Hey @Berrysoft, thanks for reporting the issue!  Yes we'll have to test for net5 prefix as well.  For now, you should be able to set this property in your csproj directly.
