### ISSUE TITLE
Does Eto support web-to-app linking?

### ISSUE THREAD

**Issue by lmtr0** [picoe/Eto#1767]
# This is not an actual issue of the code, but i am making an app that needs this functionality.

## The basic behavior is:
-> If you have [visual studio code](https://code.visualstudio.com/?wt.mc_id=DX_841432) install, you can go to an we browser and type `vscode://[SOMETHING]`
-> After that you will notice that the browser ask permission to open an external app. This also works with GitHub when you clone a  new repo, the is a option to open in desktop, is the same idea.

I need to implement this functionality on my app that i am building with your technology because I want it to be cross-platform.
UWP (Universal Windows Platform) already has this functionality if you want a reference, [Here](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking)

**Comment by cwensley** [comment]
Hey @nacktech, you need to do that on a per-platform basis, usually via your installer on Linux/Windows (updating the registry or config files), or with the Info.plist for macOS apps.

With a few searches these look like some documentation that can get you started for [Windows](https://stackoverflow.com/a/38205984/981187), [Linux](https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler), and [macOS](https://stackoverflow.com/a/471642/981187)

Unfortunately, there's not much Eto.Forms can do to make this process cross platform.

**Comment by lmtr0** [comment]
thank you for your time
