### ISSUE TITLE
PropertyGrid ShowDescription do not work before set content

### ISSUE THREAD

**Issue by hxbb00** [picoe/Eto#1770]
## Expected Behavior

ShowDescription  work before set content

## Actual Behavior

[before content]
![image](https://user-images.githubusercontent.com/14104435/90123359-440e3680-dd91-11ea-903d-9389c05030df.png)

[after content]
![image](https://user-images.githubusercontent.com/14104435/90123472-74ee6b80-dd91-11ea-9c0f-f3d0a77b62c8.png)

## Code that Demonstrates the Problem

```
[not works]
{
            DynamicLayout layout = new DynamicLayout()
            {
                Padding = new Padding(2)
            };

            _propertyGrid.ShowCategories = true;
            _propertyGrid.ShowDescription = false;// not work

            layout.BackgroundColor = Colors.LightGrey;

            layout.Add(_propertyGrid, true, true); // true == scale horizontally
            Content = layout;
}

[works]
{
            DynamicLayout layout = new DynamicLayout()
            {
                Padding = new Padding(2)
            };

            _propertyGrid.ShowCategories = true;

            layout.BackgroundColor = Colors.LightGrey;

            layout.Add(_propertyGrid, true, true); // true == scale horizontally
            Content = layout;

            _propertyGrid.ShowDescription = false;// work
}

```

## Specifications

  - Version:2.5.4
  - Platform(s): Gtk3
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I'm seeing the same thing too, though it's not apparent why it is happening..

**Comment by cwensley** [comment]
I'm not seeing this issue anymore.  Probably a fix in GTK+.  Closing this but let me know if you're still running into this issue and we can reopen.
