### ISSUE TITLE
Bitmap memory leak

### ISSUE THREAD

**Issue by hxbb00** [picoe/Eto#1771]
## Actual Behavior

![image](https://user-images.githubusercontent.com/14104435/90278280-c1bd6980-de99-11ea-8fdc-9135885db539.png)

## Code that Demonstrates the Problem

```
【works fine】
IntPtr outData;
int lSize = pinvoke_get_byte_array(out outData);
if (lSize > 0)
{
                    byte[] bytes = new byte[lSize];
                    Marshal.Copy(outData, bytes, 0, lSize);

                    pinvoke_free_byte_array(outData);
}

【memory leak】
IntPtr outData;
int lSize = pinvoke_get_byte_array(out outData);
if (lSize > 0)
{
                    byte[] bytes = new byte[lSize];
                    Marshal.Copy(outData, bytes, 0, lSize);

                    Bitmap bmp = new Bitmap(bytes);
                    //paintEventArgs.Graphics.DrawImage(bmp, paintEventArgs.ClipRectangle.TopLeft);
                    bmp.Dispose();
                    bmp = null;
                    GC.Collect();

                    pinvoke_free_byte_array(outData);
}
```

## Specifications

  - Version:2.5.4
  - Platform(s): Gtk3
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hm, interesting issue!  Did you do a `GC.WaitForPendingFinalizers()` call as well?  Perhaps there's some native stuff being held that don't get cleaned up with `Dispose()` call.

**Comment by davidscherf** [comment]
Getting the same issue on
Version 2.5.8
Platform Gtk3
Operating System: Raspbian (arm32hf)

Creating a Eto.Drawing.Bitmap from a byte array, 
leaks when Using or Dispose()
I am trying to make a camera view, and using the Paint event or a Drawable
GC.Collect does nothing
At 30 frames / second, I run out of memory very fast

**Comment by cwensley** [comment]
Hm, it could be the MemoryStream that is being called when using the `Bitmap(byte[])` constructor.  Again, the `GC.WaitForPendingFinalizers()` is needed after a `GC.Collect()` for things to actually get cleaned up which would resolve that.

Try this:

```
using (var stream = new MemoryStream(bytes, false))
{
  bmp = new Bitmap(stream);
}
```

I'll change the constructor to do the above as well so it releases the byte data immediately.

**Comment by davidscherf** [comment]
Tried the following, its still leaking at the same rate, memory is not recovered until app closes.
You can repo this, by loading an image from disk, and running the following 30 times per second

using (var stream = new MemoryStream(bytes, false))
{
  using (var bmp = new Bitmap(stream))
  {
  }
}
GC.Collect();
GC.WaitForPendingFinalizers();

**Comment by cwensley** [comment]
Weird.  It's nothing in Eto's code afaict.  Maybe @harry-cpp has some ideas?

It would be interesting to do the following using Gtk directly to see if it still happens.  Perhaps this constructor has an issue, or Pixbuf in general..
```
var bmp = new Gdk.Pixbuf(stream);
bmp.Dispose();
```

**Comment by davidscherf** [comment]
could the issue be in BitmapDataHandler
Control is assigned the Gdk.Pixbuf
but in dispose, I do not see Control being cleaned up, only the Surface is being cleaned up
should not the Control if not null and not disposed then be disposed and set to null?

**Comment by cwensley** [comment]
@davidscherf the dispose of Control is done in the base class.

**Comment by davidscherf** [comment]
i tested
using (var thisBuf = new Gdk.Pixbuf(stream){
}

and yes its the Gdk.Pixbuf leaking

**Comment by davidscherf** [comment]
How about the solution at https://www.bountysource.com/issues/92954999-pixbuf-memory-leak
Not seeing a leak with the solution
Gtk.Application.Invoke (delegate
{
    PixbufLoader loader = new PixbufLoader();
    loader.Write(image.ToBytes(".bmp"));
    _rawImage.Pixbuf = loader.Pixbuf;
    loader.Close();
});

does that work with the code

**Comment by cwensley** [comment]
Interesting, that actually comes from the gtksharp repo.  Good to link to that issue on GitHub so they see it there: https://github.com/GtkSharp/GtkSharp/issues/186

**Comment by cwensley** [comment]
Looks like a good solution until GtkSharp is fixed, thanks for pointing it out!

**Comment by cwensley** [comment]
The Pixbuf constructor basically does the same thing as using the loader, _except_ that by using `PixbufLoader.PixbufHandle`, it appears like it adds an extra reference to the handle, which means the pixbuf is never cleaned up.

**Comment by davidscherf** [comment]
For anyone that wants to get around the issue
Create a copy of the gtk BitmapHandler, and using the following Constructor

public BitmapHandler(byte[] buffer)
{
        Gdk.PixbufLoader loader = new Gdk.PixbufLoader();
	loader.Write(buffer);
	this.Control = loader.Pixbuf;
	loader.Close();
}

then you can assign the handler to a new bitmap

**Comment by cwensley** [comment]
Thanks, @davidscherf.  Also see the PR I created on GtkSharp repo to fix the issue.  Hopefully it gets merged soon.

**Comment by cwensley** [comment]
Looks like the [PR](https://github.com/GtkSharp/GtkSharp/pull/203) was merged.  Now to just wait for the next GtkSharp release.  Closing this as it will be resolved there.  Thanks everyone for your feedback!
