### ISSUE TITLE
Drawable doesnt draw right away in Paint event

### ISSUE THREAD

**Issue by MarkWilds** [picoe/Eto#1777]
I cant seem to get my Drawable to draw right away, I have tried putting invalidate into several events for the dialog.
Drawing only starts when I drag the window out of the operating system window bounds and back.

## Expected Behavior
![image](https://user-images.githubusercontent.com/2270089/90951542-26f5f980-e45c-11ea-9fd7-792a16944f22.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/2270089/90951548-3117f800-e45c-11ea-8ec9-efe261c93b76.png)

## Steps to Reproduce the Problem

  1.  Create dialog/window with drawable on windows.
  2.  Subscribe to Paint event, get graphics object and draw something.
  3.  Run your application and open the form/dialog.

## Code that Demonstrates the Problem

```
    public class FamilyTreeForm : Dialog
    {
        public FamilyTreeForm(IServiceProvider serviceProvider)
        {
            InitializeLayout();
        }

        private void OnPaint(object sender, PaintEventArgs eventArgs)
        {
            using (var graphics = ((Drawable) sender).CreateGraphics())
            {
                graphics.Clear(Colors.CornflowerBlue);
                graphics.DrawEllipse(Colors.Black, 100, 100, 100, 100);    
            }
        } 

        private void InitializeLayout()
        {
            Size = new Size(800, 700);
            MinimumSize = Size;
            Resizable = false;
            ShowInTaskbar = false;
            // this.ToCenter();
            Title = "Stamboom";

            var drawable = new Drawable();
            drawable.Paint += OnPaint;
            Content = drawable;
        }
    }
```

## Specifications

  - Version: 2.5.4
  - Platform(s): WinForms
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Try using the `eventArgs.Graphics` object instead of using `CreateGraphics()`.  The latter was for drawing directly to the screen, which does not really work that well anymore and should be deprecated.
