### ISSUE TITLE
Visual Studio Addin crashes when adding a new Eto dialog

### ISSUE THREAD

**Issue by MartinRothschink** [picoe/Eto#1811]
I'm trying to add a new Eto dialog to my project with VS 2019 (Version16.7.7). This fails.
My current workaround: Open project on Mac and add dialog with VS for Mac.  

## Expected Behavior

Dialog with code preview added to my project.

## Actual Behavior

Addin crashes and VS shows a message box:

---------------------------
Microsoft Visual Studio
---------------------------
Fail to run wizard 'C:\Users\mrk.AXONET\AppData\Local\Microsoft\VisualStudio\16.0_331f88ce\VTC\a5e0a5cbbbe76b9703ee9aab738aca2f\~IC\Item\CSharp\Eto.Forms\File.zip\File.vstemplate'.

**Message: StartIndex must not be less than zero.**

Parameter name: startIndex

## Steps to Reproduce the Problem

  1. Create a new project with "dotnet new etoapp -m preview -sln"
  2. Open project in VS 2019
  3. Add/New element. Select Eto.Form View, select Code preview and Dialog

## Specifications

Eto.Addin.VisualStudio-2.5.6.vsix
Windows 10, 20H2
Visual Studio 2019, 16.7.7

**Comment by SaculRennorb** [comment]
This also happens for axml/form.
might just happen on every configuration

**Comment by cwensley** [comment]
Thanks for reporting the issue guys!  Probably something to do with the dotnet template or how it is wired up..

**Comment by cwensley** [comment]
Thanks again for reporting the issue.  Please try the extension from [here](https://github.com/picoe/Eto/suites/1607389744/artifacts/29383941) to see if it works for you.  If it does, I'll publish it to the extension marketplace.

Cheers!

**Comment by MartinRothschink** [comment]
Curtis, looks good now. Thanks.
