### ISSUE TITLE
Form Preview no longer works on Windows Visual Studio

### ISSUE THREAD

**Issue by soopercool101** [picoe/Eto#1817]
Seemingly related to #1811 as these behaviors started at roughly the same time.

## Expected Behavior
Clicking an .eto.cs file in Visual Studio with the addin installed should show a form preview as well as the code.

## Actual Behavior
Just shows code.

## Steps to Reproduce the Problem

  1. Open a previously-previewable .eto.cs file

## Specifications

  - Version: 2.5.0
  - Platform(s): Addin for Visual Studio 2019
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Thanks for reporting the issue!  What version of Visual Studio are you seeing the issue with?

**Comment by soopercool101** [comment]
I am on Visual Studio Community 2019 v16.7.7, apologies for not including that in the initial report

**Comment by cwensley** [comment]
Hmm.. I'm not seeing the same issue with 16.7.7.  Do you have other extensions installed that might be interfering?

<img width="979" alt="Screen Shot 2020-11-06 at 4 17 42 PM" src="https://user-images.githubusercontent.com/367446/98425885-afdc0480-204b-11eb-9786-82fb39e17cd4.png">

**Comment by soopercool101** [comment]
Disabling all other extensions does not fix the issue, neither does a reinstall of the plugin.

Could it possibly be something in my code? It compiles and runs perfectly fine and it's still incredibly basic: https://github.com/soopercool101/BrawlCrateNeo/blob/main/BrawlCrate.UI/BrawlCrate.UI/MainForm.eto.cs

(I would make a new form to test but #1811 is still affecting me unfortunately)

**Comment by cwensley** [comment]
@soopercool101 it could certainly be something in your code, since the form previewer has limitations.  Usually it'd show you an error message right above the splitter in that case.

Does the split view show or is it showing only the code?  Also, perhaps the splitter is at the top of the code and you can drag it down?

**Comment by soopercool101** [comment]
The split view does not appear at all for me anymore, only the code.

**Comment by soopercool101** [comment]
![image](https://user-images.githubusercontent.com/35675593/98580593-12641900-2275-11eb-9d26-8a22980d6e95.png)

**Comment by LaraSQP** [comment]
Might be foolish to suggest this but make sure the split separator is not jammed against the margin.

Has happened to me.

**Comment by cwensley** [comment]
Hey @soopercool101, could you try the extension from [here](https://github.com/picoe/Eto/suites/1607389744/artifacts/29383941) to see if it works for you?  I've tested with the latest version of VS with no issues.

**Comment by soopercool101** [comment]
Certainly properly fixes #1811 but unfortunately the split view still does not appear for me, even when creating a new form or panel. Additionally, attempting to create a new Eto.Forms project hangs Visual Studio indefinitely on the "Creating Project..." loading bar for me with the new addin, seemingly regardless of settings.

(Tested both without any additional extensions enabled and with my usual load)

**Comment by cwensley** [comment]
@soopercool101 thanks for the feedback.  If you haven't already, could you try updating to VS 16.8.2?  This is the version I tested the new extension with.

**Comment by soopercool101** [comment]
Apologies for neglecting to clarify in my original comment but my tests were already performed on the latest non-preview build of VS Community 2019, 16.8.2. I also updated my Eto.Forms Nuget dependencies to 2.5.8 but this also did not fix my original issue.

**Comment by cwensley** [comment]
Ah bummer.  Odd that it is hanging when creating the new project, that is one of the bugs I fixed.  Did you uninstall the extension then re-install? you must do that due to the version of the one I linked is older than the released version(s).

**Comment by soopercool101** [comment]
I did uninstall before installing the new version (it wouldn't allow me to do otherwise)

**Comment by cwensley** [comment]
Ok, well the last thing I think I need to test (especially for this particular issue) is VS Community vs. Professional.

What would also be very helpful is if you can export your vsconfig so I know what components you have installed.  You can get this file by opening Visual Studio Installer, and click More > Export Configuration for the version you are using.

**Comment by soopercool101** [comment]
Here you are, hopefully it helps. I will say that form preview was working on Community edition on my end at some point shortly before I created this issue.
[vsconfig.zip](https://github.com/picoe/Eto/files/5644414/vsconfig.zip)

**Comment by cwensley** [comment]
Yes that is certainly very weird that it just started happening.  Was it a VS update do you think?

**Comment by cwensley** [comment]
By the way, to fix the project template(s) hanging, could you delete `C:\Users\<you>\.templateengine\vs` and try again?  It could be using a cached version of the templates.

**Comment by soopercool101** [comment]
Deleting the template folder still results in infinite loading when generating a new project unfortunately. I'm not certain on the exacts of what happened but I *believe* it was a VS update rather than anything I did as to my knowledge it stopped working in between a gap of me working on the UI

**Comment by cwensley** [comment]
Ok, I've tested with a fresh install of VS Community and that's not it, everything seems to be working for me using the .vsconfig you supplied.  I have no idea why it isn't showing for you currently.  As for the projects hanging when creating, it could still be a caching issue.  I'll release 2.5.9 and we can see if things are any better with that and go from there.

**Comment by ghost** [comment]
Eto.Forms 2.5.9
VS Community 16.8.4
Windows 7 (in VirtualBox 6, on Mint 20.1)
Eto.Forms template project, compiles; Wpf version run in windows; Gtk version runs in Linux
in VS solution explorer, selecting form using 'Open With...', dialog shows entry 'Eto.Forms preview (default)', selecting shows error 'The file cannot be opened with the selected editor. Please choose another editor.'

[vsconfig.txt](https://github.com/picoe/Eto/files/5874618/vsconfig.txt)

**Comment by ghost** [comment]
FYI...
Saw that v2.5.10 was released.
Downloaded, installed, and tried again.
Same result as 2.5.9 described above.

**Comment by cwensley** [comment]
I've done a ton of updates for 2.5.11.. please give it a try!

**Comment by LaraSQP** [comment]
Working on it. So far, so good.

**Comment by soopercool101** [comment]
Form preview works on my end with the latest updates, I think it's safe to call this issue closed

**Comment by cwensley** [comment]
Thanks for testing @soopercool101 and @LaraSQP!  Great to hear it is working.
