### ISSUE TITLE
Add Microsoft.Web.WebView2 handler

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#1825]
Now that the WebView2 control is [officially released](https://devblogs.microsoft.com/dotnet/announcing-general-availability-for-microsoft-edge-webview2-for-net-and-fixed-distribution-method/), we should add this to core Eto.

Ideally this should be opt-in as it adds a bunch of extra dll's to your app.  I'd like to investigate a few approaches to this:

1. Use a separate nuget package to enable the feature.  Ideally just by adding the package would enable the feature so something would need to be figured out there.
2. Compile it into Eto.Wpf and Eto.WinForms, but exclude it from the nuget dependencies.  If you add the 
Microsoft.Web.WebView2 package then it would enable it.  This would rely on a TypeLoadException to detect if it was installed.  I'm not sure if there are drawbacks to this.
3. Compile it in a separate assembly and enable it with a property in the .csproj, such as `<UseWebView2>`

**Comment by lubos** [comment]
I think option 2 is the cleanest and seems like the lowest effort since we would be leveraging `Microsoft.Web.WebView2` package. I'm excited to see this supported in `Eto.Forms`.

**Comment by cwensley** [comment]
I'm aiming for 2, then if that is not possible then 3.

Option 3 wouldn't require an extra nuget package either as the extra assembly would be included in Eto's existing packages.

Then again, for my future reference we might be able to use a separate assembly and use it if we detect that the WebView2 package is also installed..  

Regardless I like to make it as easy as possible to use the new control.

**Comment by cwensley** [comment]
Done!  Not too difficult to add to be honest.  Eto will now do this:

- If Microsoft.Web.WebView2 is installed with your app, and the WebView2 runtime is _not_ installed, it will prompt you to download, install, or use old browser.  You can control this with `WebView2Loader.InstallMode`. Modes are Manual, Automatic, or Fallback.

- If you want to bundle a fixed version of WebView2 with your app, you can set `WebView2Handler.CoreWebView2Environment` as described [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode)

- If Microsoft.Web.WebView2 is _not_ installed with your app, it falls back to the Windows Forms WebBrowser and prints a warning message when compiled for Debug.

**Comment by lubos** [comment]
This is great. Thanks. I will upgrade as soon as 2.5.8 is on NuGet.

**Comment by lubos** [comment]
I'd like to set `InstallMode` to `Automatic` but I've noticed `Eto.WinForms.Forms.Controls.WebView2Loader` is internal class. Shouldn't it be `public` ?

**Comment by cwensley** [comment]
@lubos you're right, it should!  I've created https://github.com/picoe/Eto/issues/1905 to get that done.
