### ISSUE TITLE
Project template not being created in Visual Studio

### ISSUE THREAD

**Issue by SinsofSloth** [picoe/Eto#1827]
## Expected Behavior
Creating a project using the Eto Forms template.

## Actual Behavior
I'm unsure if this a Visual Studio 2019 issue or a problem with my computer and the extension, but Visual Studio is not responding and not creating a project using the 2.5.0 extension. I tried using the 2.5.7 extension, but I get an error message of "Exception has been thrown by the target of an invocation." 

It should be noted that the extension was working fine for me on the day of the problem, and then this happened.

**Comment by cwensley** [comment]
Hey @SinsofSloth,

Thanks for reporting the issue!  I recently ran into this too with the VS 2019 16.8 update (ugh).  I think there's something in Eto's templates that does not work with it.  I've attempted to fix it but haven't found the issue yet, so I have to start from scratch and add things until it breaks.

I'll try to get this resolved soon.

**Comment by SinsofSloth** [comment]
[ActivityLog.xml.txt](https://github.com/picoe/Eto/files/5585813/ActivityLog.xml.txt)
This is a log I have from loading a xeto file, noting where the exception is being called from, with ver. 2.5.7. Hopefully, this should help with narrowing one of the problems.

**Comment by bmuessig** [comment]
For me the project creation also fails, as it never finishes creating, regardless the configured settings.

I should add that I have just installed VS2019 Pro for the first time; so it fails with the stock configuration.
After manually installing the latest version, I am now also getting an exception instead of the UI hanging.

**Comment by DomDom3333** [comment]
For me the creation stalls after creating the project folder. Task Manager reports that its still using more than just idle amounts of CPU time so (from the outside) it looks like its still doing something at least... I'm getting these issues on VS2019 16.8 and 16.9 Preview. Is there a error code/log file I can provide to help fix this?

**Comment by cwensley** [comment]
Thanks everyone for taking the time to chime in and help.  I think I have all the information I need at this point, since I can easily reproduce this with 16.8.  I'll try to get this fixed soon so you can all start working on fun stuff instead!

In the meantime, you should still be able to create new projects and files via [`dotnet new`](https://github.com/picoe/Eto/wiki/Quick-Start#dotnet-new) which are the same templates as VS.

**Comment by cwensley** [comment]
Hey everyone, thanks again for reporting the issue.  Please try the extension from [here](https://github.com/picoe/Eto/suites/1607389744/artifacts/29383941) to see if it works for you.  If it does, I'll publish it to the extension marketplace.

Cheers!

**Comment by bmuessig** [comment]
The issue is still present. While it is not crashing (and while I can't target lower .NET FW versions anymore), the created projects are simply blank, no matter the configuration. They're just empty folders.

**Comment by cwensley** [comment]
Hm, it could be caching the template from an earlier installed version, if you've installed the 2.5.8 extension.  From a fresh install (and my not so fresh install), it appears to work for me.  I'll reopen until that is verified.

**Comment by bmuessig** [comment]
> Hm, it could be caching the template from an earlier installed version, if you've installed the 2.5.8 extension. From a fresh install (and my not so fresh install), it appears to work for me. I'll reopen until that is verified.

How would I clear the cache to test?

**Comment by JackP74** [comment]
> Hey everyone, thanks again for reporting the issue. Please try the extension from [here](https://github.com/picoe/Eto/suites/1607389744/artifacts/29383941) to see if it works for you. If it does, I'll publish it to the extension marketplace.
> 
> Cheers!

I tried this version and it did create the project, couldn't find the Eto.anything version (>= 2.5.9-ci-20201204.400055691)

**Comment by cwensley** [comment]
@JackP74 awesome, glad that worked.  That is normal as that version of Eto is not published to nuget.  I'm hopeful that the correctly packaged 2.5.9 will fix this issue for everyone.

**Comment by JackP74** [comment]
@cwensley any kind of ETA on 2.5.9? don't want to rush just curious

**Comment by cwensley** [comment]
Ok guys, 2.5.9 is released, _and_ published to the VS marketplace.  I had the 2.5.0 extension from the marketplace and tried creating a project -> boom.  Updated to 2.5.9, then worked.  Please give it a whirl and let me know how it goes.
