### ISSUE TITLE
Missing Grasshopper.Instances.EtoDocumentEditor in 2.5.7

### ISSUE THREAD

**Issue by teocomi** [picoe/Eto#1828]
Hello,

Apologies if this issue is more relevant to McNeel rather than Eto, but I thought to post it here first. 
I've referenced the `2.5.7` Eto nuget package in a project that contains a GH plugin and get the following error:

![image](https://user-images.githubusercontent.com/2679513/99944566-009d6e00-2d6b-11eb-95c1-83ff69ec7cae.png)

If I copy locally and reference the `Eto.dll`  contained in my Rhino (6.31.20315) installation folder everythig works as expected. I also noticed that Eto assembly has a `2.5.7-dev` version.

As you can see I'm just trying to set the owner of an Eto Dialog, maybe there's an alternative solution?

Many thanks!

PS
I'm on windows for reference!

**Comment by cwensley** [comment]
Hi @teocomi,

The correct place for anything McNeel related should be posted to https://discourse.mcneel.com.  Just add an 'eto' tag and I'll see it there.

However, you are getting this because of a conflict between your own copy of Eto*.dll and the one shipped with Rhino.  The one shipped with Rhino is strong named whereas the public Eto dll's are not. To resolve this, simply delete any Eto*.dll's in the output folder of your plugin.

Also, using the RhinoCommon NuGet Package already includes Eto.dll, so you shouldn't have to reference any Eto package(s) directly with your plugin.

Hope this helps!

**Comment by teocomi** [comment]
Hey Curtis, thanks for the quick reply. 
To clarify, the error I'm getting is not thrown at runtime, it's displayed by Visual Studio when I reference Eto from nuget (either the latest 2.5.7 or the one that comes when referencing RhinoCommon 2.5.0).
The error not displayed when referencing the Eto version found in my Rhino installation.

This is not a dealbreaker for us as we can continue to reference the local dll, but it shows the nuget version is not fully aligned with version that comes with Rhino :).

I might report this on the McNeel forum, so feel free to close the issue if not relevant.

**Comment by cwensley** [comment]
Ah, that will happen if you're mixing the Eto.Forms and RhinoCommon nuget together, and happens more often using sdk-style projects.

You can add an `Alias="eto"` to your PackageReference in your .csproj to resolve this, e.g.:

`<PackageReference Include="Eto.Forms" Version="2.5.7" Alias="eto" PrivateAssets="all" />`

This will allow you to reference both at the same time.  Again, as I mention you should _only_ reference Eto.dll from RhinoCommon, and remove any references to Eto.Forms, Eto.Platform.Wpf, etc. from all of your projects.

Note the `PrivateAssets="all"` is added so it does not copy Eto.dll to your output.

If you want to post a full example of what you're doing so I can help further, yes please do that on the McNeel forum.

**Comment by teocomi** [comment]
Thanks again, maybe I didn't explain myself well :) . Here's a clearer example: https://discourse.mcneel.com/t/eto-forms-nuget-differs-from-the-version-coming-with-rhino/113072

Cheers!

**Comment by cwensley** [comment]
Thanks I'll continue the conversation there.
