### ISSUE TITLE
No templates after installing the Addin in Visual Studio for Mac

### ISSUE THREAD

**Issue by alexvinidiktov** [picoe/Eto#1845]
## Expected Behavior
1. installi Eto.Addin.MonoDevelop-2.5.8.mpack  in Visual Studio for Mac.
2. Go to File -> New Solution...
3. Select an Eto.forms template

## Actual Behavior
1. installi Eto.Addin.MonoDevelop-2.5.8.mpack  in Visual Studio for Mac.
2. Go to File -> New Solution...
3. Can'f find any Eto.forms templates

## Specifications

  - Version: Eto Addin version 2.5.8
  - Visual Studio for Mac version 8.8
  - Operating System(s): macOS 10.15.6

**Comment by cwensley** [comment]
Hey @vinidiktov, thanks for reporting the issue, I'm seeing it as well with 2.5.8.  However, installing the 2.5.0 version seems to still work so something changed between then.
