### ISSUE TITLE
[Wpf] SEHException in EnableThemingInScope.DeactivateActCtx

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1849]
```
System.Runtime.InteropServices.SEHException: Eine externe Komponente hat eine Ausnahme ausgelöst.
bei Eto.Wpf.Forms.EnableThemingInScope.DeactivateActCtx(UInt32 dwFlags, IntPtr lpCookie)
   bei Eto.Wpf.Forms.EnableThemingInScope.Dispose(Boolean disposing)
   bei Eto.Wpf.Forms.EnableThemingInScope.Finalize()</StackTrace>
    Source: Eto.Wpf
```
Translation of the exception message: `An external component has thrown an exception` (Yes, that message will be definitely helpful)

## Steps to Reproduce the Problem

Not completely clear what leads to this problem. Happens randomly when hovering/clicking on Menu items aor opeingn dialogs. Or using dropdowns. Seems like some sort of race condition, as this does not happen every time. In 2.5.9-ci it definitely happens more often than on 2.5.8...

I cannot remmeber seeing this error before, even though the code is present since ~2018.

I found this for using `DeactivateActCtx` in Finalizers.
https://stackoverflow.com/questions/26514954/registration-free-com-interop-deactivating-activation-context-in-finalizer-thro

## Specifications

  - Version: 2.5.8 and current CI
  - Platform(s): WPF
  - Operating System(s): Win10 20H2

**Comment by ManuelHu** [comment]
I suppose I found the solution, this exception occured when my custom `UnhandledException`-Handler fired the second time and the first had already started to close the application.

I think we can close this issue.

**Comment by cwensley** [comment]
Cool, thanks for the update.
