### ISSUE TITLE
Partial dark mode WPF style

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1850]
Just noting it here as I'm a WPF novice and perhaps others can complete this / improve it to allow for easy dark mode WPF UIs.

Various things aren't working nicely at the time of writing. Build and run the EtoTest WPF application (I hacked this around also to avoid having to install additional frameworks - just wanted to work on the dark mode styling.

https://github.com/philstopford/Eto/tree/dark_mode_experiment

The attempt was spawned by stumbling across https://github.com/manju-summoner/DynamicAero2

**Comment by InfinityGhost** [comment]
I've tried this recently myself and I've had essentially no luck. The most I could get is a dark scrollbar in a Table using WpfPlus.
![image](https://user-images.githubusercontent.com/39218853/102293136-76cd6480-3f14-11eb-87e1-54cbcf6d4d9e.png)
```cs
[STAThread]
public static void Main(string[] args)
{
    void appCallback()
    {
        var app = Application.Current;
        app.Resources.MergedDictionaries.Add(new ResourceDictionary { Source = new Uri("pack://application:,,,/WpfPlus;component/DarkTheme.xaml") });
        foreach (Window window in app.Windows)
            window.SetResourceReference(ContentControl.StyleProperty, "FlatWindowStyle");
    };
    App.Run(Eto.Platforms.Wpf, args, appCallback);
}
```

**Comment by philstopford** [comment]
Give the test application a whirl; I don't pretend it's ideal or correct, but wanted to try and get a ball rolling :)

![image](https://user-images.githubusercontent.com/1983851/102296740-987a1c00-3f13-11eb-87e0-ba62dd7f9e6f.png)

![image](https://user-images.githubusercontent.com/1983851/102296775-acbe1900-3f13-11eb-81ef-35f0672fb413.png)

**Comment by philstopford** [comment]
Still haven't figured out how to style those background elements...

**Comment by cwensley** [comment]
I think I helped with this earlier, is it still an issue?   I still want to do #1896 which covers this, so I'm closing this issue as a dupe.

**Comment by philstopford** [comment]
I didn't get much further with this, sadly, so anything that can be done at the library/framework level would be very welcome

**Comment by cwensley** [comment]
@philstopford what about https://github.com/philstopford/Eto/pull/1 ?  did they not work for you?  It should have fixed up most of the issues.

**Comment by philstopford** [comment]
Actually, you're right. That gets a lot closer (there was something with label colors before, I remembered, that I couldn't fix).  There are some oddities in the Test Application, e.g. color drop-down arrows remain bright, and there are a few very bright areas displayed in TabControl and other areas. I haven't had a chance to look into the code, but this is a lot further along than I thought.

How tricky would this be to support directly in the framework, perhaps using this as a springboard?

**Comment by cwensley** [comment]
I think I can use it as a reference when implementing theme/appearance support, yes.  I'd ideally like to make it easier to make custom WPF themes, however.

**Comment by philstopford** [comment]
I've merged the PR into my code (took some manual changes). Thanks again for this - I would have picked it up sooner, except for the persistent impression that label color was getting transferred around (all the text went green after visiting one of the test sections, I recall)
