### ISSUE TITLE
MessageBox on WPF on .NET 5 does not follow modern system design

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1851]
## Expected Behavior
A more modern / more integrated look of the message box (built with WPF for net461):
![grafik](https://user-images.githubusercontent.com/10050780/102713838-20bd4000-42cb-11eb-99bf-4606e04d1bee.png)

## Actual Behavior
"Old" look 
![grafik](https://user-images.githubusercontent.com/10050780/102713818-06836200-42cb-11eb-8d6e-f39fc227dd0c.png)

## Specifications

  - Version: 2.5.8
  - Platform(s): WPF on .NET 5
  - Operating System(s): Windows10 20H2

**Comment by cwensley** [comment]
Looks like a WPF problem: https://github.com/dotnet/wpf/issues/179

However, I did add code that worked for WPF on .NET Framework to enable the visual styles.. I guess it doesn't work on .NET 5 so I'll have to investigate that.  Perhaps the only way is to add a manifest like shown [here](https://stackoverflow.com/a/5289462/981187).

**Comment by ManuelHu** [comment]
Ah okay, I'll try that ;-)

**Comment by ManuelHu** [comment]
Adding a manifest file worked - even in my hacky cross-build on Linux setup... Thanks!
