### ISSUE TITLE
2.5.9 Not available on NuGet?

### ISSUE THREAD

**Issue by piersdeseilligny** [picoe/Eto#1864]
Hi! This isn't quite a bug, but I was just wondering if there was a specific reason for which 2.5.9 is available in releases, but isn't yet available on NuGet?

**Comment by cwensley** [comment]
@piersdeseilligny I have to "press a few buttons" to make it go as the CI trigger to do it automatically got messed up.  I should be able to do it sometime today.

**Comment by piersdeseilligny** [comment]
Awesome - no worries. Thanks!

**Comment by cwensley** [comment]
Just as a follow up, nuget packages are now properly published.
