### ISSUE TITLE
JSON Serialization doesn't handle "Shortcut" property correctly

### ISSUE THREAD

**Issue by sfesenko** [picoe/Eto#1866]
How to reproduce:
Just create and run a new app from a template with json ui definition.

Command
```dotnet new etoapp -n test -m json && dotnet run -p test/test.Gtk/test.Gtk.csproj -f netcoreapp3.1```

Fails with error:

```Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "CommonModifier+Q" to type 'Eto.Forms.Keys'. Path 'Menu.QuitItem.Shortcut', line 26, position 89.```

It seems, that Json.NET doesn't use converters for enums by default, so it doesn't call `KeysConverter`.

Version 2.5.8
Platform Gtk3
Operating System ArchLinux

**Comment by cwensley** [comment]
@sfesenko thanks for reporting the issue!  I think this was working before when Eto had its own converter implementation due to being a PCL.  It should be an easy fix to make it use the system TypeConverter in this case.
