### ISSUE TITLE
Menu takes a while to draw on first click.

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1869]
## Expected Behavior

Near-instant display of File or Help menu contents

## Actual Behavior

First display stalls during drawing of menu contents:
![image](https://user-images.githubusercontent.com/1983851/103838526-e4bc0600-5052-11eb-8abe-b5f23015cd40.png)

## Steps to Reproduce the Problem

  1. Build
  2. Run
  3. Click File menu

## Code that Demonstrates the Problem

https://github.com/philstopford/Commonality

## Specifications

  - Version: 2.5.9-ci
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
This isn't an issue with the Menu, the entire application is stalled. This is happening because of the extreme amount of columns you are adding.  WPF's DataGrid only virtualizes rows by default.  Adding this style to your WPF startup before you run the application should make it _much_ snappier:

```c#
Style.Add<Eto.Wpf.Forms.Controls.GridViewHandler>(null, h =>
{
	h.Control.EnableColumnVirtualization = true;
});
```

**Comment by philstopford** [comment]
Nice - thanks for that. Much better! Is there a reason that this isn't done by default?

**Comment by cwensley** [comment]
@philstopford probably due to overhead.. who knows.  It could probably be turned on by default (in Eto) without any tremendous consequence (needs testing), or at least have a threshold of number of columns before it gets turned on automatically..
