### ISSUE TITLE
KP_Enter on Linux

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1880]
I need to capture `KP_Enter` (enter key in number pad) with `KeyUp` of a `ComboBox` on **Linux** but it is not in the `Keys` enumeration.

A search revealed this open issue but it is 5 years old:

https://github.com/picoe/Eto/issues/531

**Comment by LaraSQP** [comment]
It occurs to me that since `KP_Enter` is such a special case, it might be simpler to translate that key press into a regular `Enter` as a workaround until the full enumeration can be dealt with.

Just a thought (and possible inane, I suspect).

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Yeah it's probably best to map it to Enter, as on windows there's no (easy) way currently to detect the number pad keys vs. other keys anyway.  There's a few others that are missing as well, I'll add those too.

**Comment by LaraSQP** [comment]
Much appreciated. You are the man.
