### ISSUE TITLE
OSX- Row height in DataGrid

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1886]
I have a DataGrid where one column contains a ImageCell.
Images in these cells can have different heights and in WPF the row-height is set according to the image-height.

But not with OSX, all rows stay the same constant size.

Any idea on how to force the Mac to behave like WPF? I mean scaling the row-height according to the image height?

**Comment by cwensley** [comment]
Unfortunately it doesn't auto size on Mac or Gtk..  You have to set the RowHeight explicitly currently.

**Comment by TomQv** [comment]
I thought so.
Where do I set the RowHeight individual for each row ?

**Comment by cwensley** [comment]
You can't unfortunately, it's only one size for all rows.

**Comment by TomQv** [comment]
ok, I see. Thank you.

**Comment by cwensley** [comment]
Closing as this is answered, and adding individual heights for rows is covered in #971.
