### ISSUE TITLE
Using VS project template creates invalid code when project name contains hyphen

### ISSUE THREAD

**Issue by geoff-m** [picoe/Eto#1897]
## Steps to Reproduce the Problem
  1.  Go to New Project dialog in Visual Studio 2019
  2. Select "Eto.Forms Application"
  3. Enter "hello-world" as the project name and click Create.
  4. Select any option in the next dialog and click OK.

## Expected Behavior
Error messages should not be displayed, and the generated project should build.

## Actual Behavior
The generated project fails to build with a variety of errors.

MainForm.cs, for example, is found to contain the line:
```
namespace hello-world
```
which is bad syntax.

## Specifications
  - Version: Eto.Forms Visual Studio Addin 2.5.9
  - Platforms: N/A
  - Operating System: Windows 10

**Comment by geoff-m** [comment]
By contrast, Microsoft's templates replace hyphens entered in that dialog with underscores in the namespace name. They preserve hyphens in project, solution, and assembly names.

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Should be a relatively easy fix.  I think I may have broken this recently.
