### ISSUE TITLE
How would one run / build a GTK project for Windows?

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#1911]
The wiki states:
> For Eto.Gtk, you must install [Gtk+ 3](https://www.gtk.org/download/windows.php).

However the link it points to is dead, it redirects to a nonexistant page.

So, I tried to follow the instructions on [the GTK instructions page](https://www.gtk.org/docs/installations/windows/) instead, but so far have no luck to actually run my program.

What I've tried:
- Install MSYS2, and download the `mingw-w64-x86_64-gtk3` package, as the wiki states
- Install the `mingw-w64-x86_64-toolchain base-devel` package.
- In the `Building and distributing your application` section, follow steps 1-6 (with slight modifications: my installation folder was my build folder, and step 4 I did in `C:\msys64\mingw64\` and then pasted everything from `C:\msys64\mingw64\share\glib-2.0\schemas` to installation folder + "share/glib-2.0/schemas")
- Build again

What I've also tried:
- copy-paste every library from `C:\msys64\mingw64\bin` into my build path and try executing it.

While the application gets successfully build, for both ways, I get a runtime error when starting it.
```cs
Unkown Exception has occured in your application.
The type initializer for 'Gtk.Application' threw an exception.
*****Stack Trace*****

   at Gtk.Application.InitCheck(String progname, String[]& args)
   at Eto.GtkSharp.Helper.Init()
   at Eto.GtkSharp.Forms.ApplicationHandler.Initialize()
   at Eto.WidgetHandler`1.Eto.Widget.IHandler.Initialize()
   at Eto.Widget.Initialize()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at Eto.Forms.Application..ctor(String platformType)
   at AM2RLauncher.Gtk.MainClass.Main(String[] args) in C:\Users\Narr\source\repos\AM2RLauncherRewrite\AM2RLauncher\AM2RLauncher.Gtk\Program.cs:line 19
```
Line 19 is `Application GTKLauncher = new Application(Eto.Platforms.Gtk);`
The GTK project has been build like this (from windows, not msys2)
`dotnet publish -c release -r win-x86 -o "builds\win86"`
The GTK project also only has Eto.Platform.Gtk as a NuGet package.

I've also tried running it via Visual Studio, and have gotten from the exception details, that `Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll` are all missing. Except from libgtk-3-0.dll which is in the build folder, none of the files actually exist even in the msys installation folder.

**Comment by borjafdezgauna** [comment]
I did that using the installer in this [answer](https://github.com/picoe/Eto/issues/442#issuecomment-174317888). You also need to set the RuntimeIdentifier of the project to "win-x64", I think

**Comment by cwensley** [comment]
Running Gtk+3 applications on Windows or other platforms is unfortunately beyond the scope of this project.  While possible, it is up to you to figure out and since Eto is simply an abstraction it is no different from running a GtkSharp application on these platforms directly.

That being said, I would welcome contributions to the wiki to help others run Gtk+ on non-linux platforms.

**Comment by rafntor** [comment]
I use and can recommend ; https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by cwensley** [comment]
Closing as this is answered and beyond the scope of this project.  While you can run Gtk on any platform such as macOS, Windows, and Linux, doing so is up to you.  Wiki contributions for hints on how to do that might be useful.
