### ISSUE TITLE
Text not aligning properly with DrawText

### ISSUE THREAD

**Issue by axx0** [picoe/Eto#1921]
Hi, I'm using DrawText to draw text on a Drawable panel.
Example:
```
g.DrawText(new Font("Arial", 9, FontStyle.Bold), new SolidBrush(Color.FromArgb(87, 171, 39)), new RectangleF(0, 0, 200, 100), "Food", FormattedTextWrapMode.None, FormattedTextAlignment.Right, FormattedTextTrimming.None);
```

## Expected Behavior
The text on the rectangle should be right aligned.

## Actual Behavior
The text is left aligned.

This also happens with Center alignment.

My system:
  - Version: EtoForms 2.5.10
  - Platform(s): WinForms
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Alignment appears to work with multi-lines, but not a single line.. Works fine with WPF and other platforms.
