### ISSUE TITLE
KeyboardEvent returns Keys.None for + sign on German keyboard layout

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1925]
On a German keyboard, there is an extra key for the plus sign that is located to the left of the enter key. With eto the keypress returns a `Key=Keys.None, KeyChar='+'`. I suppose this is not optimal...

See Wikipedia: https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg

e.g. on Gtk3, Gtk returns `Key.plus` which is not handled in the `KeyMap`: https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/KeyMap.cs. I did not test on other platforms...

## Expected Behavior
Pressing `+` on my keyboard returns a meaningful keycode (e.g. `Keys.Plus`) and not `Keys.None`. Returning `Keys.Equal` would be misleading, as the plus key on a German keyboard layout cannot produce an equals sign... [1].

## Specifications

  - Version: latest CI build
  - Platform(s): Gtk3

[1] Note/addition: there is also no equals key on German keyboards *at all*, as the equal sign is produced with `Shift+0`.... But those keys at least return some meaningful Key value)

**Comment by cwensley** [comment]
Awesome, thanks for reporting the issue!  I'll see if I can get the virtual keyboard to show a German layout, but if not I might not be able to know which key it reports on the various platforms.

One way you could help is to run your application in debug on the other platforms (Wpf, WinForms, Mac). You should then get an output like `Unknown key XX`, where it will tell us which key to map it to.

**Comment by ManuelHu** [comment]
Working on it. Good news: On Windows everything seems quite fine; I'm currently preparing testing on macOS. Bad news: Also some other keys (8 in total) on the German keyboard do not work on Eto.Gtk

**Comment by cwensley** [comment]
Awesome, that is much appreciated and will make this very quick to fix!

**Comment by ManuelHu** [comment]
The following table contains the output of `$"{e.KeyChar}|{e.Key.ToString()}"` where non-printable key chars have been omitted. The platforms behave completely different... In bold there are some of my ideas how to change 

On Windows, 4 events will be raised (duplicating first and second Key value); those are only shown once per distinct event args. For the second press of a dead key the same keychar is emitted 4 times!

I don't know if the macOS result is right, as I'm using a VM with a Standard German keyboard - a German mac keyboard has a different layout...

| Key                         | Windows                                          | Mac             | Gtk (GtkSharp Key value)                                                                  |
|-----------------------------|--------------------------------------------------|-----------------|-------------------------------------------------------------------------------------------|
| +                           | \|Equals +\|None                                 | +\|RightBracket | +\|None (Key.plus)  **+\|Equals**                                                                      |
| Ü                           | \|Semicolon ü\|None                              | ü\|LeftBracket  | no event (Key.udiaeresis)                                                                 |
| Ä                           | \|Quote ä\|None                                  | ä\|Quote        | no event (Key.adiaeresis)                                                                 |
| Ö                           | \|Grave ö\|None                                  | ö\|Semicolon    | no event (Key.odiaresis)                                                                  |
| ß                           | \LeftBracket ß\|None                                                 | ß\|Minus        | no event (Key.ssharp)                                                                     |
| Keypad Point                | \|Decimal ,\|None                                | ,\|Decimal      | no event (Key.KP_Separator)      **,\|Decimal**                                                         |
| Shift+dead_acute (Backtick) | \|LeftShift \|RightBracket (second time `\|None) | n/a             | \|LeftShift \|None (Key.dead_acute) Note: KeyChar is non-printable for both events        |
| dead_acute ("Forward tick") | \|RightBracket (second time ´\|None)             | n/a             | no event (Key.dead_acute)                                                                 |
| Circumflex                  | \|Backslash   (second time ^\|None)                                  | n/a             | no event, except with shift but then non-printable (instead of "°") (Key.dead_circumflex) |


The most problematic is probably the `+` as requiring umlaut or dead keys for custom actions is *hopefully* uncommon... But still emitting events for those would be needed for e.g. implementing custom input on controls. The inconstency on the + key for macOS still isn't great, but is a quirk of macOS?

**Comment by cwensley** [comment]
Hm, I'm seeing the same results on macOS using the accessibility on-screen keyboard so it's probably a quirk (feature) of that platform.  It doesn't appear to be giving a different key code so there's not much I can do about that.

As for Gtk that should be no problem to fix those two at the very least.

**Comment by ManuelHu** [comment]
Fixing the two keys on Gtk would be great ;-) Than I could bundle the fixed version with the next release of my app...

**Comment by mxrlbo** [comment]
Is there a way to get the Key-Events to fire with ä, ö and ü on GTK or would I have to add mappings for that?

**Comment by cwensley** [comment]
@BlackBirdTV if they are not coming through, they would need to be mapped.  I'm not sure if there are equivalents to those keys in Eto.Forms.Keys, so they may need to be added as well.
