### ISSUE TITLE
Borderless Window Inconsistency between Wpf and Gtk

### ISSUE THREAD

**Issue by Sarund9** [picoe/Eto#1928]
From the Discusion:
_Borderless Window? https://github.com/picoe/Eto/discussions/1926_

We found something that might be considered an Issue

This window is in "borderless" mode, but it still contains a border in Wpf.
![Borderless Window](https://user-images.githubusercontent.com/53350334/114963046-41913e80-9e42-11eb-86ff-88b4381ca77b.png)
Is this intended behaviour of a Wpf window?
According to Documentation, this Window in Gtk does not have a Border at all.
This might be considered a platform inconsistency.

**Comment by cwensley** [comment]
This is the default of WPF when creating resizable windows. It doesn't have a border if it is not resizable.  To change it, you could do something like:

```
// in your startup code:
Eto.Style.Add<Eto.Wpf.Forms.FormHandler>("noborder", handler => {
  System.Windows.WindowChrome.SetWindowChrome(handler.Control, 
    new System.Windows.WindowChrome { ResizeBorderThickness = new System.Windows.Thickness(2) }
  )
});

// when creating your window:

myWindow.Style = "noborder";
```

**Comment by Sarund9** [comment]
That breaks the MenuBar (Items can't be clicked on)

**Comment by cwensley** [comment]
You'll have to play around with the WindowChrome properties then, perhaps don't allow resizing at the top of the window by using `new Thickness(2, 0, 2, 2)`.

**Comment by InfinityGhost** [comment]
Could just disable resizing and then there's no border at all, which IMO should be the default behavior to match GTK.

**Comment by Sarund9** [comment]
> You'll have to play around with the WindowChrome properties then, perhaps don't allow resizing at the top of the window by using `new Thickness(2, 0, 2, 2)`.

A Thickness of 0 still does not allow clicking on the menus. 

> Could just disable resizing and then there's no border at all, which IMO should be the default behavior to match GTK.

That does work, but i want a resizable window with no borders

**Comment by InfinityGhost** [comment]
Potentially could override the OnMouseDown function on the window class itself, and check it the cursor position is at the edge of the window and resize from there.

**Comment by cwensley** [comment]
This should be easier to do, regardless of the default.  I think my suggestions aren't quite working correctly so it needs to be figured out.
