### ISSUE TITLE
Form HasFocus has incorrect value when starting external process from application

### ISSUE THREAD

**Issue by GulamY** [picoe/Eto#1937]
## Overview
The value of the Form property `HasFocus` is incorrect (set to `true`) when an external process is spawned from the application.
This behavior has only been tested with Wpf backed Eto project. It could be reproducible on other platforms, but I did not verify other cases.  When I checked the `IsFocused` property on the native control via `Handler` it was correctly reporting `false`. I was expecting the `HasFocus` value to be in sync with the native property in this case.

## Steps to Reproduce the Problem

  1.  With a default project structure replace the content of `MainForm` and run the application
  2.  Click `Click me!` button. The application should launch Explorer in the root of disk C
  3.  In the output window check the printed HasFocus value (will be reported as `true`)

## Code that Demonstrates the Problem

```
using System.Diagnostics;
using Eto.Drawing;
using Eto.Forms;

namespace HasFocusIssue
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            MinimumSize = new Size(200, 200);
            
            var clickMe = new Command { MenuText = "Click Me!", ToolBarText = "Click Me!" };
            clickMe.Executed += (sender, e) =>
            {
                // Start external process: Explorer in this case
                Process.Start(@"C:\");

                Trace.WriteLine($"This ({this}) HasFocus = {HasFocus}");
            };
            
            ToolBar = new ToolBar { Items = { clickMe } };
        }
    }
}

```

## Specifications

  - Version: 2.5.10
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @GulamY,

I think what you're running into is that you are assuming that the focus is lost _immediately_.  Try adding this snippet to the constructor and you'll see the form does lose focus, just not right after Process.Start:

```
	this.LostFocus += (sender, e) => {
		Trace.WriteLine($"LostFocus: {HasFocus}");
	};
	this.GotFocus += (sender, e) => {
		Trace.WriteLine($"GotFocus: {HasFocus}");
	};
```

**Comment by GulamY** [comment]
Hello @cwensley! Thank you for looking into it. Indeed with your snippet I can see when `GotFocus` and `LostFocus` occur. The events are fired consistently in reaction to user's actions. I also added a timer to monitor the focus status. 

There is something that got my attention which flips my observation upside down. There is a situation when `GotFocus` occurred before the application actually came to the foreground and became available for user input (the `HasFocus` property became `true`). The WPF handler in the meantime reported the `IsFocused` as false. I think this is discrepancy that is the root of the problem I am experiencing.

With the snippet I provided the situation is not reproducible. I will need look deeper to see how I can provide a better example for the case.

**Comment by cwensley** [comment]
Closing as this was answered.  The focus of the form will not ever be lost right after calling Process.Start() as that is dependant on how quickly the OS loads said application and brings it to the foreground.

If you do find a reproducible case that shows an invalid state please feel free to reopen.
