### ISSUE TITLE
Cannot run program on macOS from Visual Studio

### ISSUE THREAD

**Issue by julian-baumann** [picoe/Eto#1949]
Whenever I try to run my project in Visual Studio for mac I get this error:
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/julian/Projects/MyApp/MyApp/MyApp.Mac/bin/Debug/net5.0/MyApp.Mac.app/Contents/MacOS/MyApp.Mac does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

The program exists in that path and when I open the terminal and run `/Users/julian/Projects/MyApp/MyApp/MyApp.Mac/bin/Debug/net5.0/MyApp.Mac.app/Contents/MacOS/MyApp.Mac` the program opens

This problem occures on all of my projects since a few months now. I already reinstalled Visual Studio multiple times and also tried to create new projects, but without success.

A friend also tried this on his mac with visual studio for mac and got the same problem.

## Expected Behavior
Launch the program

## Actual Behavior
Does not launch the program

## Steps to Reproduce the Problem

  1. Create a new project on macOS with the newest Visual Studio for mac with the newest .NET (.NET 5.0.203 is what I use to this date)
  2. Select the macOS target, like MyApp`.Mac`
  3. Press run

## Specifications

  - Visual Studio for mac version: 8.9.9 (build 3) 
  - .NET Version: 5.0.203
  - ETO.Forms version: 2.5.10
  - Platform(s): Mac
  - Operating System(s): macOS Big Sur 11.2.3 on a M1 Mac

**Comment by cwensley** [comment]
Hey @julian-baumann, 

Thanks for reporting the issue!  I did notice this as well, and should be fixed for 2.5.11.    A way around this for now is to set your target to net48.

However, you still can't _debug_ .NET 5/6 with Visual Studio for Mac due to its limitations (there is no way to tell it to launch a native executable).   I only got non-debug working by hacking it to use `dotnet run`.

Currently the only way to debug a .NET 5 application on Mac is to use VSCode, which works quite well.

**Comment by julian-baumann** [comment]
Ah I understand. Thanks for the quick response and the workaround.

**Comment by julian-baumann** [comment]
Also noticed that IntelliSense does not work on Eto.Forms with xeto or c# files in Visual Studio for Mac. Is this a normal behaviour?

**Comment by cwensley** [comment]
It isn't normal, they removed the "old" way of doing intellisense in one of the recent versions.  This should also already be fixed with 2.5.11.  It could use some testing though..  You can download the latest addins from this build here: https://github.com/picoe/Eto/runs/2569081623

**Comment by julian-baumann** [comment]
I think I solved my problem with IntelliSense, by running `dotnet new -i "Eto.Forms.Templates::*"`, that's why I deleted that comment. But thanks for the link to the latest addins. I will try that. Especially when this fixes this issue with not being able to run the mac app

**Comment by cwensley** [comment]
The new addin won't fix that problem unfortunately; it was fixed in the nuget package targets.

**Comment by cwensley** [comment]
BTW, 2.5.11 was _just_ released.  Give it a go to see if it fixes this issue for you.

**Comment by julian-baumann** [comment]
Works great, thank you.
