### ISSUE TITLE
Project template for rider?

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#1952]
Is there a possibility we can see a template for the rider IDE?

**Comment by cwensley** [comment]
Use the [dotnet templates](https://github.com/picoe/Eto/wiki/Quick-Start#dotnet-new).  I thought rider supported them out of the box?

**Comment by cwensley** [comment]
Yeah, according to https://blog.jetbrains.com/dotnet/2017/12/21/project-templates-rider-2017-3/, you simply need to install the templates with `dotnet new --install "Eto.Forms.Templates"` and go..
