### ISSUE TITLE
[Feature Request] Custom WndProc on Wpf

### ISSUE THREAD

**Issue by hamarb123** [picoe/Eto#1954]
Hi, I implemented https://github.com/picoe/Eto/issues/1790 for WinForms, could I also implement it for Wpf if it's feasible with another PR?
Thanks!

**Comment by cwensley** [comment]
I don't think anything is necessary for that, in WPF you can hook into the wndproc without a subclass..

E.g. based on [this example](https://stackoverflow.com/a/624424/981187), you can do something like this with Eto:

```c#
Style.Add<Eto.Wpf.Forms.FormHandler>(null, handler =>
{
	IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
	{
		//  do stuff

		return IntPtr.Zero;
	}
	var source = HwndSource.FromHwnd(handler.NativeHandle);
	source.AddHook(new HwndSourceHook(WndProc));
});
```

**Comment by cwensley** [comment]
although, I would welcome a PR to add something to the WpfWindow to hook into the WndProc with less code.. (;

**Comment by hamarb123** [comment]
Hi, I'll try the first solution for my code, and I might add a PR at some point in the future.
Thanks!
