### ISSUE TITLE
Eto.dll gets flagged as virus.

### ISSUE THREAD

**Issue by chhaugen** [picoe/Eto#1964]
## Expected Behavior
Sample app launches.

## Actual Behavior
Eto.dll gets flagged as virus
![image](https://user-images.githubusercontent.com/8987475/121101684-9c209880-c7fc-11eb-9b28-f0f25e6e9f74.png)

## Steps to Reproduce the Problem

  1. Create a new Eto.Forms C# prosject
  2. launch EtoApp1.Wpf
  3. Profit?

## Code that Demonstrates the Problem

```
[Paste your code here]
```

## Specifications

  - Version: 2.5.11
  - Platform(s): WPF 
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Ugh, looks like MS' latest defender definitions thinks it is a virus.. 🤦🏻‍♂️

I've submitted it to Microsoft as a false positive.  We'll see how long it takes for them to rectify the issue. 🤞

For now you have to go into security and allow the file manually.

**Comment by cwensley** [comment]
Ok, the submission was successful!  It should now work with the latest defender definitions.  Give it a go!

**Comment by chhaugen** [comment]
Can confirm it works as expected now! Thanks! 😄
