### ISSUE TITLE
Add Control to dynamiclayout at runtime doesn't work

### ISSUE THREAD

**Issue by vincent-pp** [picoe/Eto#1973]
I want to click the button and add a label in DynamicLayout when the app is running , but it doesn't work anyway, the label can not show up

related code is below here:

    private void btnAdd_MouseDown(object sender, MouseEventArgs e)
        {
            try
            {
                Label lbl= new Label { Text = "test", BackgroundColor = Color.FromArgb(255, 0, 0) };
                panel1.BeginHorizontal();
                panel1.Add(lbl);
                panel1.EndHorizontal();
                panel1.Invalidate();
            }
            catch { }
        }

  - Version: 2.5.11
  - Platform(s):  WinForms
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Try using [`DynamicLayout.Create()`](http://pages.picoe.ca/docs/api/html/M_Eto_Forms_DynamicLayout_Create.htm)

**Comment by cwensley** [comment]
Closing as there's no response..  feel free to comment/reopen if the above does not work for you.

Cheers!
