### ISSUE TITLE
Mac cannot run eto project

### ISSUE THREAD

**Issue by jzlhll** [picoe/Eto#1975]
Actual Issue:

When run from Visual studio for mac 8.10.2, eto version 2.5.11; It cannot run, it can only build it to bin/.

Last version, visual studio for mac 8.9.9, it can runs eto project while cannot debugger it. So I deside update vs;
When updated to 8.10.2 vs for mac, it cannot run.

Expect :
Run it success from vs for mac triangle button; and can debugger code.

Please test and try it.

**Comment by cwensley** [comment]
Thanks for submitting the issue, I'll give 8.10.2 a try.

> visual studio for mac 8.9.9, it can runs eto project while cannot debugger it

This is a known limitation of VS for Mac with .NET Core/.NET 5, there was no easy way to get the .NET Core debugger to work with this.  I'll try poking around the new version to see if maybe I can get it going.  Hopefully I can at least get it to run properly again.  You can always just set your csproj to net48 to enable full debugging.

Another option that does work for debugging on Mac with .NET Core/.NET 5 is to use VS Code.

**Comment by jzlhll** [comment]
Thanks a lot. I see 'a known limitation'. Please let it going on 8.10.2.

**Comment by cwensley** [comment]
Just to confirm, using `net48` also works for 8.10.2, so you can use that in the meantime.  

Hope this helps!

**Comment by jzlhll** [comment]
Thanks.
