### ISSUE TITLE
NumericStepper Truncates (u)long value. Change Value from double to decimal.

### ISSUE THREAD

**Issue by SinsofSloth** [picoe/Eto#1976]
## Expected Behavior
NumericStepper retaining precision point of (u)long value.

## Actual Behavior
NumericStepper truncating (u)long value.

## Steps to Reproduce the Problem

  1. Use the max (u)long value (0xFFFFFFFFFFFFFFFF) in a NumericStepper.

## Code that Demonstrates the Problem
Change NumericStepper's Value's data type from ``double`` to ``decimal`` like .NET Framework's WinForms does.

## Specifications

  - Version: 2.5.11
  - Platform(s): WinForms
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Unfortunately this isn't possible as the NumericStepper supports decimal places.  Try using `NumericMaskedTextStepper<ulong>`.
