### ISSUE TITLE
Oxyplot

### ISSUE THREAD

**Issue by seghier** [picoe/Eto#1978]
Hello
Can you add oxyplot to eto?

**Comment by InfinityGhost** [comment]
[Oxyplot](https://github.com/oxyplot/oxyplot)

This is actually pretty interesting and would be a nice addition, however I don't think it would belong in the main Eto.Forms library, maybe as a separate thing of its own?

**Comment by seghier** [comment]
Thanks, but the problem how to use it as separated tool?
For many users lime me who don't understand anything about compiling or visual basic programing , it is better to see this tool or an alternative one included in eto

**Comment by davidjgall** [comment]
I concur! a plot/graph/chart solution should be an inherent part of any "forms" library. Just because Microsoft can't seem to do it doesn't mean their pattern is the correct pattern....

**Comment by cwensley** [comment]
This project looks interesting.. maybe we can poke mostanes to put up a nuget package.. 😄

https://github.com/mostanes/OxyPlot.EtoForms

**Comment by rafntor** [comment]
Possible alternative in the making ; https://github.com/ScottPlot/ScottPlot/discussions/1425

**Comment by mostanes** [comment]
> This project looks interesting.. maybe we can poke mostanes to put up a nuget package.. smile
> 
> https://github.com/mostanes/OxyPlot.EtoForms

Hi, poke received. It looks like @rafntor has managed to publish a nuget package already.
Since I'm not very keen on maintaining it and rafntor seems to have taken up the development, I'll leave it up to him.
Anyway, even if he won't maintain it, I'm not sure I will either, and more importantly I won't support dotnet core and related tooling (including sdk-style projects), which may (or may not) be a dealbreaker for some.

**Comment by seghier** [comment]
> Possible alternative in the making ; [ScottPlot/ScottPlot#1425](https://github.com/ScottPlot/ScottPlot/discussions/1425)

Thanks rafntor, i will try it with visual studio 2022.
I just need the dll to test it in Rhino 3d
Which example is for eto?
![image](https://user-images.githubusercontent.com/6026588/141654076-03955743-f938-45bb-96d9-2401edd4e51f.png)

**Comment by rafntor** [comment]
@seghier : Check this branch ; https://github.com/rafntor/ScottPlot/tree/port_to_eto/src/demo

**Comment by cwensley** [comment]
Closing this as Oxyplot and other charting controls are not part of the core Eto framework.  Thanks again for all your input! 

Please let me know how I can help with those efforts.

**Comment by rafntor** [comment]
FYI : Eto NuGet packages now available 

[OxyPlot](https://oxyplot.github.io/) | [ScottPlot](https://scottplot.net/)
---|---
[![NuGet](http://img.shields.io/nuget/v/OxyPlot.Eto.svg?style=flat)](https://www.nuget.org/packages/OxyPlot.Eto/)| [![NuGet](http://img.shields.io/nuget/v/ScottPlot.Eto.svg?style=flat)](https://www.nuget.org/packages/ScottPlot.Eto/)

**Comment by hazzik** [comment]
> Possible alternative in the making ; [ScottPlot/ScottPlot#1425](https://github.com/ScottPlot/ScottPlot/discussions/1425)

@rafntor ScottPlot provides just a wrapper around System.Drawing.Common (GDI+) that depends on mono-libgdiplus on non windows platform, so it is really not a fair port to Eto.

**Comment by rafntor** [comment]
True - it is not a port on that level, just an adaption or a 'bridge' that allows using ScottPlot in Eto.
ScottPlot also is considering how to proceed and get rid of System.Drawing and when that materializes the Eto control needs to update and adapt to that evolution

**Comment by greatawesome** [comment]
I recently created Eto support for ZedGraph as well, using the same technique that ScottPlot used:

https://github.com/greatawesome/ZedGraph

I'd personally look at ScottPlot for new projects, but for an app already using ZedGraph this is a way to take it cross-platform without rewriting for a new plot control.
