### ISSUE TITLE
MacBook Air M1 launch issues

### ISSUE THREAD

**Issue by johmarjac** [picoe/Eto#1983]
Hi,

so I basically created a Eto project on my Mac M1. The first thing I don't understand is, the Etoproject.Mac project is The only project that has by default an external application to launch when debugging and it fails to start whatever it tries to start when I want to debug the project. If I set it to Launch Project in the debug configuration, it compiles fine, but I get a runtime error:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/30114127/125073697-a2848780-e0bc-11eb-9609-d47e9302f65a.png">

Latest Xcode is installed too, the mpack extension for Visual Studio too.

Please help

**Comment by cwensley** [comment]
In order to debug with VS for Mac, you need to target net48.  It cannot debug .NET Core/.NET 5 .app bundles currently.

Hope this helps!

**Comment by johmarjac** [comment]
@cwensley Thanks a lot, that was the issue

**Comment by cwensley** [comment]
No problem, thanks for reporting the issue.  I should at least make a note of it in the project creation wizard so that people have a chance of knowing why it isn't working.
