### ISSUE TITLE
ComboBox ignores background colour

### ISSUE THREAD

**Issue by ausern-error** [picoe/Eto#1984]
## Expected Behavior
ComboBox uses background color that is specified in style.
## Actual Behavior
ComboBox ignores the background color and only uses text color.

## Steps to Reproduce the Problem
1. Create a style for a Combobox using Eto.Style.Add.
2. Set style to null.
3. Set background color
4. Set text color
5. Run and view any ComboBox
## Code that Demonstrates the Problem

```
            Eto.Style.Add<ComboBox>(null, comboBox =>
            {
                comboBox.BackgroundColor = Color.FromArgb(0, 0, 0);
                comboBox.TextColor = Color.FromArgb(255, 0, 0);
            });
```

## Specifications
  - Version: Eto.Forms 2.6.0-ci-20210612.931419801
  - Platform(s): Wpf
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hm, I'm not seeing the same issue.. do you have a more specific reproduction?

This is in the Eto.Test.Wpf app > Controls > Control Fonts & Colors section:
<img width="131" alt="Screen Shot 2021-10-23 at 11 38 41 PM" src="https://user-images.githubusercontent.com/367446/138583676-c1e4526c-8b6b-411b-8934-ec24861a3080.png">

**Comment by cwensley** [comment]
Closing as there's no reproduction of this issue.  If you have further information on how this isn't working, please let me know.
