### ISSUE TITLE
macOS Eto.Forms Problems

### ISSUE THREAD

**Issue by InochiPM** [picoe/Eto#1999]
## Expected Behavior
To launch the app bundle .app file and the program load as well as the plugin section to contain the actual plugins used by the program to load. 

## Actual Behavior
Shows "You can't open the application "Kuriimu2" because it may be damaged or incomplete." 

App>Contents>MacOS>Kuriimu2 Executable - Opens the program, but all of the plugins are missing and unhandled exceptions are thrown when trying to remotely do anything within that version of the program.  

## Steps to Reproduce the Problem
Downloading the latest actions build of Kuriimu2 or the official release for mac will result in the same issues
application refuses to open, but executable opens with none of the required plugins showing or working through the program but their present in the plugins folder that comes with the release or build. 

## Specifications

  - Version: 2.6.0-ci-20210612.931419801
  - Platform(s): Mac
  - Operating System(s): macOS 11.4 Big Sur

**Comment by cwensley** [comment]
Thanks for submitting the issue!  Do you have an example of what you're trying to do?

**Comment by InochiPM** [comment]
> Thanks for submitting the issue! Do you have an example of what you're trying to do?

I'm trying to get the mac app to work correctly. The auto build from github is weird and apparently they had tried to get the paths to work to load the plugin .dll files but they refuse to show up. We know the app needs to be signed and we can do that but other than that the app bundle .app file refuses to launch correctly after built from the github repo.

**Comment by cwensley** [comment]
I hope it's not just this: https://github.com/FanTranslatorsInternational/Kuriimu2/actions/runs/1053400474

A few problems with it:
1) you need to compile on macOS to code-sign and notarize
2) you need to distribute the .dmg, not the .zip that is generated from GitHub actions.
3) you need to put the plugins _inside_ the .app bundle _before_ codesigning instead of beside the .app.

**Comment by InochiPM** [comment]
> I hope it's not just this: https://github.com/FanTranslatorsInternational/Kuriimu2/actions/runs/1053400474
> 
> A few problems with it:
> 
> 1. you need to compile on macOS to code-sign and notarize
> 2. you need to distribute the .dmg, not the .zip that is generated from GitHub actions.
> 3. you need to put the plugins _inside_ the .app bundle _before_ codesigning instead of beside the .app.

Me and one other are the only ones with a mac to be able to code-sign and notarize so theres that.
When i download their git repo source but it refuses to restore the package for the solution. 
I figured thats what the plugin issue was but i wasn't to sure.

**Comment by cwensley** [comment]
I notice that the projects are using a development version:

```
    <PackageReference Include="Eto.Forms" Version="2.6.0-ci-20210612.931419801" />
```

.. but no nuget.config to specify that the myget nuget source should be used...  So you'd need to add Eto's myget nuget source to your global nuget.config for it to work.

**Comment by InochiPM** [comment]
How would i add that correctly? I thought it was just the link to the myget that wold work but that was just a shot in the dark.

**Comment by cwensley** [comment]
Hm, adding a nuget source is pretty easy..  https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source.. or use visual studio to add it..  github actions also has facility to add other nuget sources.

the nuget source is https://www.myget.org/F/eto/api/v3/index.json (linked in Eto's readme).

Another option is to use a released version of Eto on nuget.org vs. a development version

**Comment by InochiPM** [comment]
> Hm, adding a nuget source is pretty easy.. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source.. or use visual studio to add it.. github actions also has facility to add other nuget sources.
> 
> the nuget source is https://www.myget.org/F/eto/api/v3/index.json (linked in Eto's readme).
> 
> Another option is to use a released version of Eto on nuget.org vs. a development version

Thank you, i managed to get them in and updated them but now im having some issues with the code ill get it figured out hopefully soon!

**Comment by InochiPM** [comment]
> A few problems with it:
> 
> 1. you need to compile on macOS to code-sign and notarize
> 2. you need to distribute the .dmg, not the .zip that is generated from GitHub actions.
> 3. you need to put the plugins _inside_ the .app bundle _before_ codesigning instead of beside the .app.

How would i go about putting the plugins inside before codesigning? I managed to compile and build the etoforms for mac and got the app working because of the github actions removing the EtoForms.Mac form the extension caused the app to not work. Now were faced with the plugins not showing/loading or working in any capacity.

**Comment by cwensley** [comment]
Include the plugins as Content in the .csproj for the .app bundle, which you'd use `Eto.EtoEnvironment.GetSpecialFolder(EtoSpecialFolder.ApplicationResources)` to get the base path to that folder, or set Copy To Output = true, and use `Eto.EtoEnvironment.GetFolderPath(EtoSpecialFolder.EntryExecutable)` for that folder.

**Comment by cwensley** [comment]
Btw, if you're using something like `System.IO.Path.GetDirectoryName(myAssembly.Location);` for where the plugins are located, this won't work when compiling using a single file assembly.

**Comment by cwensley** [comment]
Closing as I have submitted a fix to the repo in question.  The conversation can continue there.
