### ISSUE TITLE
Microsoft is dropping linux/mac support for System.Drawing.Common

### ISSUE THREAD

**Issue by trampster** [picoe/Eto#2000]
This was just announced, It seems to affect System.Drawing.* of which Eto.Forms has a bunch of usage.

https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

**Comment by cwensley** [comment]
Thanks for reporting the issue, however Eto.Forms doesn't actually use System.Drawing.* for anything and provides its own Color, Size, Rectangle, etc. 

The Windows Forms platform does use System.Drawing, but in that case Windows Forms is windows-only anyway.

**Comment by trampster** [comment]
There seems to be usage in:

-  src/Eto.Mac/Mac64Extensions.cs
- src/Eto.Mac/Forms/EtoDragSource.cs
- src/Eto.Mac/Forms/ClipboardHandler.cs
- src/Eto.Mac/Forms/Controls/LabelHandler.cs
- src/Eto.Mac/Forms/Controls/NativeControlHandler.cs
- src/Eto.Mac/Forms/OpenFileDialog.cs
- src/Eto.Mac/Forms/OpenWithDialogHandler.cs
- src/Eto.Mac/Forms/FloatingFormHandler.cs
- src/Eto.Mac/IO/SystemIconsHandler.cs
- src/Eto.Mac/Forms/ToolBar/SeparatorToolItemHandler.cs
- src/Eto.Mac/Forms/Controls/ImageViewHandler.cs
- src/Eto.Mac/Drawing/ImageHandler.cs
- src/Eto.Mac/Forms/MouseHandler.cs
- src/Eto.Mac/AppDelegate.cs
- plus more

Most of these are in a #if SDCOMPAT check, I'm not sure what SDCOMPAT it

**Comment by cwensley** [comment]
SDCOMPAT was used for old versions of MonoMac, and Xamarin.Mac Classic.  both are deprecated now.  None of those ran on .NET Core or .NET 5 anyway.  Rest assured, System.Drawing is not necessary for any platform other than on windows.
