### ISSUE TITLE
Wpf Eto.Forms ImageView/scaling issue on arm64 Windows

### ISSUE THREAD

**Issue by hamarb123** [picoe/Eto#2008]
## Expected Behavior
![image](https://user-images.githubusercontent.com/25316035/128450103-fb111bd1-9887-449a-96ac-836313e8f121.png)

## Actual Behavior
![image (3)](https://user-images.githubusercontent.com/25316035/128450116-41d384f2-89e5-47d6-b7f2-22b74dabb132.png)

## Steps to Reproduce the Problem

Both images are on Windows running through Parallels.
First is .NET 5 on x64 with Windows 10.0.19043.1110
Second is on .NET 6 preview 6 on arm64 with Windows 10.0.21354.1 (running on a M1)
Both have retina displays and thus the scaling is about 200-300%
I'm not sure why it's only happening for one of them.
Eto version: 2.5.11
Using `ImageView` class and also `new Bitmap(bitmap, size.Width, size.Height, size.Width * size.Height < bitmap.Width * bitmap.Height ? ImageInterpolation.High : ImageInterpolation.None)` (to scale image).
I can provide code once I make a simple reproduction, but this is an image from my actual application.
It's probably to do with scaling down case because the bible hangman one and the 2dcraft one are the only ones scaled up and are the only ones that are fine (cog is text I think).

## Code that Demonstrates the Problem

Some above, can provide more soon as specified above.

## Specifications

Above

**Comment by hamarb123** [comment]
It could be a problem with wpf or windows as well (as it is an insider build). Let me know what you think.

**Comment by cwensley** [comment]
Hey @hamarb123 have you tried .NET 6 RC2 and/or with Windows 11 yet?  Those may fix the issues you're having.

**Comment by hamarb123** [comment]
No, I'll let you know when I do. Might be a while though.
Thanks!

**Comment by cwensley** [comment]
No worries, thank you for your prompt reply!

Otherwise a simple repro would help troubleshoot the issue on my end.

**Comment by hamarb123** [comment]
Hi, I tested it on Windows 11 with .NET 6 RC2 and the issue seems to still exist. I'll try to make a repro, but I'm guessing it's probably an issue with Wpf/GDI+/etc.

**Comment by hamarb123** [comment]
I've just tested it again on .NET 6.0.1 and it seems to work now!
Thanks for your help!
