### ISSUE TITLE
Mac empty menu (missing Quit)

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#2011]
When running an app, a default menu appears but it contains nothing (crucially, missing the Quit entry).

Furthermore, closing the app does not quit it and this must be done via the launcher.

This is on Mac BigSur using Eto 2.5.10.

Let me know if you need more info.

**Comment by LaraSQP** [comment]
Is this related?

https://github.com/picoe/Eto/issues/535#issuecomment-647209594

**Comment by cwensley** [comment]
Hey @LaraSQP you need to add the quit item manually at this time.  See the default template for how to add one.

As for automatically adding the quit item, it could certainly be done like the other default items, but hasn't been done yet.

**Comment by LaraSQP** [comment]
Did not know. Thank you for getting back to me on this.

**Comment by LaraSQP** [comment]
For those as clueless as I.

_Add a Quit menu item. Note this is optional. On OS X, one will be added for you if you don't specify a Quit item (otherwise there is no easy way for the user to quit your application)._

```
Menu.QuitItem = new Command((sender, e) => Application.Instance.Quit())
{ 
	MenuText = "Quit", 
	Shortcut = Application.Instance.CommonModifier | Keys.Q
};
```

https://github.com/picoe/Eto/wiki/Tutorial-2-Menus-and-Toolbars

**Comment by LaraSQP** [comment]
And..

```
	Menu = new MenuBar
	{
		Items =
		{
			new ButtonMenuItem
			{ 
				Text = "&File",
				Items =
				{ 
					// you can add commands or menu items
					new MyCommand(),
					new ButtonMenuItem { Text = "Click Me, MenuItem" }
				}
			} 
		},
		// quit item (goes in Application menu on OS X, File menu for others)
		QuitItem = new Command((sender, e) => Application.Instance.Quit())
		{ 
			MenuText = "Quit", 
			Shortcut = Application.Instance.CommonModifier | Keys.Q
		},
		// about command (goes in Application menu on OS X, Help menu for others)
		AboutItem = new Command((sender, e) => new Dialog { Content = new Label { Text = "About my app..." }, ClientSize = new Size(200, 200) }.ShowModal(this))
		{ 
			MenuText = "About my app"
		}
	};
```

https://github.com/picoe/Eto/blob/develop/samples/Tutorials/CSharp/Tutorial2/Main.cs

**Comment by cwensley** [comment]
Hm.. interesting, maybe something broke?  I need to check into this more..

**Comment by LaraSQP** [comment]
Broken how?

To be honest, my only issue is that I do not want a menu other than in Mac. Compiler directives?

**Comment by cwensley** [comment]
Ah yes, the Quit menu is being added as per the comment so it isn't broken. I assumed you were at least setting the menu.  You _do_ need to at least set the form's Menu like so:
```
if (Platform.IsMac)
  myForm.Menu = new MenuBar();
```

This adds all of the standard menu items you need for normal macOS operations, such as cut/copy/paste shortcuts, etc.

**Comment by LaraSQP** [comment]
You rock, man, you rock.
