### ISSUE TITLE
Forms.Dialog buttons with images autosize incorrect

### ISSUE THREAD

**Issue by akasob** [picoe/Eto#2020]
## Expected Behavior
Negative or Positive buttons on buttonbar have apropriate sizes.

## Actual Behavior
Buttons extremely large by Height.

## Steps to Reproduce the Problem

  1.  Create project.
  2. Add class file based on Dialog class.
  3. Create button with some picture.
  4. Add button in list don't care negative or positive.
  5. Run app and see how your dialogbox flies to the Moon.

## Code that Demonstrates the Problem

```
                        var png = new Bitmap("path/to/file.png");
			var btn = new Button
			{
				//Height = 26, // to avoid bug I set height manually
				Text = "test",
				Image = png
			};
			NegativeButtons.Add(btn);
```

## Specifications

  - Version: 2.5.11
  - Platform(s): WPF 
  - Operating System(s): Win10

**Comment by cwensley** [comment]
Hi @akasob, thanks for reporting the issue!  One thing to consider is the size _and_ DPI on image you are using.  If you have a large image or with low DPI it will be shown larger than expected.

One way you can fix this is by using the `Bitmap.WithSize()` method, e.g. `btn.Image = png.WithSize(24, 24);`

**Comment by cwensley** [comment]
Closing as I need more information such as a reproduction of the issue.  If you've tried the above and if it doesn't work please let me know and we can look into it further.
