### ISSUE TITLE
ImageView mouse events don't work

### ISSUE THREAD

**Issue by trampster** [picoe/Eto#2022]
ImageView mouse events don't trigger

## Expected Behavior
Mouse events trigger 

## Actual Behavior
Mouse events don't trigger

## Steps to Reproduce the Problem
  1. Subscribe to some ImageView mouse events
  2. Try to trigger the mouse events
  3. Nothing happens

## Code that Demonstrates the Problem

```
            var editButton = new ImageView()
            {
                Image = imageService.Edit,
                Height = 20,
                Width = 20
            };
            editButton.MouseUp += (sender, args) => Console.WriteLine("Clicked");
            editButton.MouseEnter += (sender, args) => editButton.BackgroundColor = colorService.Grey;
            editButton.MouseLeave += (sender, args) => editButton.BackgroundColor = colorService.Transparent;
            addressLayout.Items.Add(editButton);
```

## Specifications

  - Version: 2.4.1
  - Platform(s): GtkSharp 3.22.24.37
  - Operating System(s):  Ubuntu 18.04

**Comment by trampster** [comment]
I'm trying to use a ImageView as an ImageButton, because although Button has an Image property there appears to be no way to remove the border.

**Comment by cwensley** [comment]
@trampster 2.4.1 is very old (> 3 years!), please try the latest Eto as this is probably already fixed as I am seeing mouse events on ImageView there.

**Comment by cwensley** [comment]
Closing unless this is confirmed as an issue on the latest code.
