### ISSUE TITLE
Eto.Platform.Mac64 Bundle fails

### ISSUE THREAD

**Issue by jvyden** [picoe/Eto#2037]
## Expected Behavior
The build operation succeeds and creates an app bundle.

## Actual Behavior
The build operation fails with the following error:
```
/Users/jvyden/.nuget/packages/eto.platform.mac64/2.5.11/build/BundleDotNetCore.targets(35,76): error MSB4186: Invalid static method invocation syntax: "[System.String]::Copy().StartsWith('osx')". Method 'System.String.Copy' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. [/Users/jvyden/Desktop/UnionPatcher/UnionPatcher.Gui.MacOS/UnionPatcher.Gui.MacOS.csproj]
```
## Steps to Reproduce the Problem

  1. Clone https://github.com/LBPUnion/UnionPatcher
  2. Attempt to build on MacOS
  3. See the error.

## Code that Demonstrates the Problem
There's not really any relevant code I can show that shows the problem...

## Specifications

  - Version: 2.5.11
  - Platform(s): Mac64
  - Operating System(s): MacOS Mojave 10.14.6 with .NET 5.0.207

### .NET Info
```
jvydens-Mac-mini:UnionPatcher jvyden$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.207
 Commit:    b2bfcafcec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/Cellar/dotnet/5.0.207/libexec/sdk/5.0.207/

Host (useful for support):
  Version: 5.0.10
  Commit:  52296950a9

.NET SDKs installed:
  5.0.207 [/usr/local/Cellar/dotnet/5.0.207/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/Cellar/dotnet/5.0.207/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/Cellar/dotnet/5.0.207/libexec/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by cwensley** [comment]
Hi @jvyden, thanks for reporting the issue!

You are missing this property in your csproj:

`<RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>`

However, that message isn't overly helpful and should be changed so you know what you need to do there.  It used to be better but I broke it at one point.

**Comment by jvyden** [comment]
Ah, that was it. Thank you!
