### ISSUE TITLE
Problem showing icon on form (on Gtk)

### ISSUE THREAD

**Issue by axx0** [picoe/Eto#2054]
I'm having problems showing an icon on the sample form below. The icon shows up on Windows (WinForms) but not on Ubuntu (Gtk),

## Code that Demonstrates the Problem

```
using Eto.Forms;
using Eto.Drawing;

public class MyForm : Form
{
	public MyForm ()
	{
		Icon = new Icon("icon.ico");
		Title = "My Cross-Platform App";
		ClientSize = new Size(200, 200);
		Content = new Label { Text = "Hello World!" };
	}
}
```

## Specifications

  - Version: Eto 2.5.11
  - Platform(s): Gtk
  - Operating System(s): Ubuntu 20.04.3 LTS

**Comment by cwensley** [comment]
For Ubuntu you need a .desktop file for the icon to show in the dock or applications list.  [this](https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles) has a bit of information about how to do that.

Hope this helps!

**Comment by axx0** [comment]
Understood, thanks!
