### ISSUE TITLE
Please support intermediate mode package.

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#2066]
Please support a easier to use intermediate mode GUI API.
I find the current library really hard to use and I can't use xaml because I am on vscode and linux and it doesn't support hot reload and viewing the GUI.

The main issue I have is that many controls do not have a clear way to set the data like ImageViewCell.
There is also things like the fact you have to use layouts when the controls themselves could be layouts like what winforms did.
And then there is a bunch of controls that looks like they work but are actually abstract controls.

I think having a intermediate mode would be much cleaner code wise and easier to understand if done right.
It could also be used in game dev easier since its loop driven instead of event driven.

https://github.com/picoe/Eto/discussions/2063

**Comment by cwensley** [comment]
Eto is simply an abstraction over other UI toolkits.  Other UI toolkits use a run-loop style interface, which isn't compatible with the pseudocode you posted as you have to actually build the UI and present it to the user before you can know if the user pressed a button.  e.g. this isn't possible to implement:

```c#
       if (ImEto.TextButton("my text button"), 4,4,4,4); // the 4's are padding around the control.
       {
           //I was pressed. 
       }
```

Passing a delegate to that method would be, however.

I'm not really sure what "intermediate mode GUI API" really means, however based on your example you could easily create your own extension methods to achieve something similar.  Creating API like this isn't something I'm keen to add to the core library. 

Additionally, using pixel positioning and docking like Windows Forms is not part of the plan as it does not lend itself well to the various toolkits which have different intrinsic sizes for things like buttons, check boxes, etc.

**Comment by cwensley** [comment]
Hi @Shadowblitz16,

Thanks again for the suggestion, but an "immediate mode" API is not a goal of this library and it is highly unlikely that it would ever be done.  I understand the desire for this coming from a gaming background, but this is not how any of the underlying UI frameworks that Eto abstracts work.
