### ISSUE TITLE
VB6 to Eto.Forms Converter?

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#2067]
Is it possible to get a vb6 form to eto form converter?

**Comment by cwensley** [comment]
Thanks for the suggestion, but I'm not sure there's enough resources to work on something like this.

Are there really that many VB6 forms out there (it ended support in 2008)?  I would have thought VB.NET or C# Windows Forms are more popular.

At any rate, considering the layout models are vastly different, this could not be easily done.

**Comment by Shadowblitz16** [comment]
Idk if there is a lot of apps that use VB6 but but supposedly you can convert vb6 to vb.net winforms and that to C# winforms, 
Although I hear there are still compatibility issues.

**Comment by cwensley** [comment]
Hm, if they can't get VB6 > VB.NET/C# conversion right, I'm not sure there's any way to do it with Eto.Forms any better.

**Comment by cwensley** [comment]
Closing as this isn't feasible, thank you for the suggestion!
