### ISSUE TITLE
Consider making this library easier to use.

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#2070]
Consider the following for the next major update.
- [ ] `Control`'s are treated as dockable pixel layouts like winforms.
- [ ] `Layout`'s are just `Control`'s like winforms.
- [ ] Merge `Content` and `Item` into `Children` property.
- [ ] Allowing public setter for `Parent` property.
- [ ] Allowing public setter for `Children` property.
- [ ] Renaming abstract controls to have `Base` in the front of their name to be less confusing. 
- [ ] `Control`'s and `Form`'s `Parent` property can take a `Form` or `Control` (this would be part of the MDI api).
- [ ] Controls take in Text and Command in Constructor (text depending on if they support it).
- [ ] Methods are implicitly converted to commands if they match the definition (`Control.Command = OnMyCommand;`).
- [ ] Some sort of web ui backend. (idk about this one).
- [ ] Value and Collection data binding is optional through a more simple `Bindable<T>`.

Let me know what you think.

**Comment by cwensley** [comment]
Hey @Shadowblitz16.  I appreciate the feedback, but these only seem to be subjective API changes that don't really add much functionality.  I will try to give my feedback on each though.

>  Control's are treated as dockable pixel layouts like winforms.
>   Layout's are just Control's like winforms.
>   Merge Content and Item into Children property.
>   Allowing public setter for Parent property.
>   Allowing public setter for Children property.

See my comment in #2066.  Winforms pixel and docking layouts with the same API is not possible.  Pixel layouts are handled with `PixelLayout`, and a docking layout may be created in the future, but it will be a separate control.  Having an identical or similar API to winforms is not a goal of Eto.Forms.

> Renaming abstract controls to have Base in the front of their name to be less confusing.

Agreed that this would be nice, there's also some other naming issues I'd like to clean up.  Alas, it would break ABI compatibility so it'll have to wait for a 3.x release.

> Controls take in Text and Command in Constructor (text depending on if they support it).

Great idea, it would be very useful in some cases to have less verbose code.  There are some cases where Eto has this already, and more can be added.  Although if you create extension methods like you mention in #2066 then this would be moot.

>  Methods are implicitly converted to commands if they match the definition (Control.Command = OnMyCommand;).

I'm not sure this is possible with C#.  Using commands is optional and you can simply use the event instead like `myButton.Click += OnClick;`

> Some sort of web ui backend. (idk about this one).

Fun fact: Eto.Forms used to have an ASP.NET web forms back end when it started out.  I would welcome anyone to create a web ui backend now that Web Assembly is a thing and it could run entirely on the browser.

> Value and Collection data binding is optional through a more simple Bindable<T>.

You'd have to give me more details on this.  What is `Bindable<T>`?  How would it work? 

Hope this sheds some light.

**Comment by Shadowblitz16** [comment]
> See my comment in #2066. Winforms pixel and docking layouts with the same API is not possible. Pixel layouts are handled with PixelLayout, and a docking layout may be created in the future, but it will be a separate control. Having an identical or similar API to winforms is not a goal of Eto.Forms.

So you can't just implicitly nest pixelLayouts in controls by default?
I don't think the `Content` and `Items` is necessary it just adds more code per nested control.

> Agreed that this would be nice, there's also some other naming issues I'd like to clean up. Alas, it would break ABI compatibility so it'll have to wait for a 3.x release.

Its just confusing when I try to use a control and its abstract.

> Great idea, it would be very useful in some cases to have less verbose code. There are some cases where Eto has this already, and more can be added. Although if you create extension methods like you mention in #2066 then this would be moot.

Ya this is part of the `Content` and `Item` suggestion its a pain to make any sort of nested control.

> I'm not sure this is possible with C#. Using commands is optional and you can simply use the event instead like myButton.Click += OnClick;

The could probably be just a `static implicit operator <type to return>(<type to pass>)`

> Fun fact: Eto.Forms used to have an ASP.NET web forms back end when it started out. I would welcome anyone to create a web ui backend now that Web Assembly is a thing and it could run entirely on the browser.

Thats cool, I was just thinking about more cross platform compatibility 

> You'd have to give me more details on this. What is Bindable<T>? How would it work?

I don't know anything about data binding but the idea is it data binding would be easier and optional.

**Comment by cwensley** [comment]
> So you can't just implicitly nest pixelLayouts in controls by default?

The use of pixel layouts is actually quite discouraged as it does not lend itself well to autosizing and controls with varying sizes per platform.  There are times where you want to use it, but most of the time you will probably not be using them.

> Ya this is part of the Content and Item suggestion its a pain to make any sort of nested control.

How so?  do you have an example of what you'd like to do and how adding these would make using nested controls easier?  Adding parameters to constructors is certainly one thing but if you derive your own controls then you'd have to add all that boilerplate constructor code again.. which in itself is a huge pain.

> The could probably be just a static implicit operator <type to return>(<type to pass>)

The type to return is an interface (ICommand), which Eto doesn't own.. the type to pass is a method.  There's no way to add an implicit operator on either of those.

> I don't know anything about data binding but the idea is it data binding would be easier and optional.

Binding is completely optional in Eto.Forms and is in no way required to do anything.  It sits atop all existing functionality that you have at your disposal, such as click and change events.  

Cheers!

**Comment by Shadowblitz16** [comment]
> The use of pixel layouts is actually quite discouraged as it does not lend itself well to autosizing and controls with varying sizes per platform. There are times where you want to use it, but most of the time you will probably not be using them.

 What about doing something like the godot engine does?  They use 4 normalized floats for margin and anchor and size flags, but allow multiple controls and per pixel layouts too. The only thing I don't like about godot gui is containers don't respect a lot of these things.

You could use a margin class and static readonly fields for things like Top, TopLeft, TopRight, Left, Center, Right, BottomLeft, Bottom and BottomRight it could even be made in a way so people can divide these to get even more accurate docking (aka Control.Margin  = Margin.Right / 4)

> How so? do you have an example of what you'd like to do and how adding these would make using nested controls easier? Adding parameters to constructors is certainly one thing but if you derive your own controls then you'd have to add all that boilerplate constructor code again.. which in itself is a huge pain.

I think controls could have parameterless constructors.

> The type to return is an interface (ICommand), which Eto doesn't own.. the type to pass is a method. There's no way to add an implicit operator on either of those.

Thats too bad :/

> Binding is completely optional in Eto.Forms and is in no way required to do anything. It sits atop all existing functionality that you have at your disposal, such as click and change events.

Oh ok I was just looking at GridImageView and it looked like it had to be binded.

**Comment by cwensley** [comment]
Hi @Shadowblitz16,

Thanks again for the suggestions.  I don't plan to change Eto.Forms so drastically in the future.  Also, an all-encompassing issue does not really help prioritize issues.  The only suggestions I could probably fathom doing at one point is "Some sort of web ui backend.", and "Controls take in Text and Command in Constructor".  Breaking API changes are not something I'd like to do for a long while.

Feel free to create separate issues for the above if you feel you still would like them done and we can continue discussion on those individually.
