### ISSUE TITLE
Adding a timer to an ETO form

### ISSUE THREAD

**Issue by RayaanABT** [picoe/Eto#2079]
What is the most suitable method to add a timer, starting at zero and counting in seconds, to the ETO form?

Could this be added to the tutorials?
https://github.com/picoe/Eto/wiki/Tutorials

**Comment by cwensley** [comment]
You mean like a timer to display to the user?  A simple `Label` and a `UITimer` should do the trick..

```
var label = new Label();

// put the label somewhere in your UI

var start = DateTime.Now;
var timer = new UITimer { Interval = 1.0 };
timer.Elapsed += (sender, e) => {
  label.Text = $"Elapsed: {DateTime.Now - start}";
};
timer.Start();
```
