### ISSUE TITLE
Drawing Performance (GTK)

### ISSUE THREAD

**Issue by piedar** [picoe/Eto#209]
I load a 2.9M [OSM](http://wiki.openstreetmap.org/wiki/OSM_XML) file and render the resulting map.  My [`EtoRenderer2D`](https://github.com/piedar/MachoMap/blob/master/MachoMap/EtoRenderer2D.cs) averages about 0.25 seconds per [`OnPaint`](https://github.com/piedar/MachoMap/blob/33babb690a56c988dcd213ebf96dc9ee80d23207/MachoMap/RenderedMap.cs#L104) on GTK.  This is slow enough to lag window resize.  On WinForms I see about 0.02 seconds per paint.  Are there any glaring deficiencies in my approach?

**Comment by piedar** [comment]
After upgrading to Eto 2.0.7 and OsmSharp 4.2.0.723, I found a massive increase in drawing performance.  Not sure which caused the improvement, but nice either way!

**Comment by cwensley** [comment]
That's great to hear!  Thanks for the feedback.
