### ISSUE TITLE
Tabbed MDI interface

### ISSUE THREAD

**Issue by carlokok** [picoe/Eto#21]
It would be great if the tab pages could support a "close button" and ways to deal with closing tabs with it; this would be a very nice base for a tabbed MDI interface written with Eto.

**Comment by cra0zy** [comment]
@cwensley This can be closed.

**Comment by cwensley** [comment]
I was keeping it open as there's no MDI in Eto, but I think you're right that @carlokok was just looking for the closable tabs.

**Comment by cra0zy** [comment]
If I remember correctly, there should be an open issue on an actual MDI control.

**Comment by cwensley** [comment]
no, this was it.. but it's basically taken care of now so thanks!
