### ISSUE TITLE
[GTK] GNOME ignores program icon

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2115]
## Expected Behavior
GNOME should show the icon that the program specified.

## Actual Behavior
GNOME shows the "placeholder program icon" instead.  
Status bar:
![grafik](https://user-images.githubusercontent.com/38186597/149770929-fddd5f49-f9da-46a5-bdc1-ff6b775185b5.png)  
Panel:  
![grafik](https://user-images.githubusercontent.com/38186597/149771009-458ab09f-fa18-4d33-95b9-cec8143b5f5e.png)

## Steps to Reproduce the Problem

  1. Compile Eto.Test.Gtk for Linux and execute it

## Specifications

  - Version: 2.6.1
  - Platform(s): Eto.Gtk
  - Operating System(s): Fedora 35 (using GNOME 41.0)

**Comment by cwensley** [comment]
Thanks for reporting the issue, however this is something you have to provide in a .desktop file.  See [this comment](https://github.com/picoe/Eto/issues/2054#issuecomment-972985283).

**Comment by Miepee** [comment]
Must've missed that, sorry.
On a note though, this resource should probably be referenced instead of the ubuntu wiki:
https://specifications.freedesktop.org/desktop-entry-spec/latest/

**Comment by cwensley** [comment]
No need to be sorry, it isn't documented, but probably should be on the Window.Icon property.

**Comment by Miepee** [comment]
Not sure if I can fork the wiki, otherwise I would've tried adding a "Publishing your app" page later.

**Comment by cwensley** [comment]
You should be able to just change the wiki directly, at least from within GitHub.  A publishing your app page would be very useful.  

I have plans to add additional build automation for both Windows and Linux to build .msi and .deb/.rpm files for you, create the .desktop file, etc. much like what I added for Mac where it can build a .dmg, code sign, and notarize it.  In the meantime it is somewhat of a manual process for those platforms.
