### ISSUE TITLE
Add support to load fonts from file

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#2120]
### Discussed in https://github.com/picoe/Eto/discussions/2114

<div type='discussions-op-text'>

<sup>Originally posted by **HaanstootZA** January 14, 2022</sup>
Hi

I am busy converting some winforms to Eto, but some of my code uses a font file.
Are there any plans to allow Eto to load from font files?

`
var fontCollection = new PrivateFontCollection()
var heighInPixels = 12;
fontCollection.AddFontFile(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "glyphfont.ttf"));
return new Font(fontCollection.Families[0], heightInPixels, GraphicsUnit.Pixel);`</div>

**Comment by morphx666** [comment]
I have been waiting for this since 2020 ;)

https://groups.google.com/g/eto-forms/c/lhW3RktLdZg

**Comment by cwensley** [comment]
😬 sorry it has taken so long!  Hopefully it'll be an easy (ish) project.  Did you end up using platform-specific code for these purposes?

**Comment by morphx666** [comment]
No worries @cwensley, I appreciate all the hard work that has been put into this project.

So, answering your question: no, I didn't use any platform-specific code. I simply included the font file as part of the install script.
