### ISSUE TITLE
System.Drawing.Common 6 is only for Windows

### ISSUE THREAD

**Issue by davidscherf** [picoe/Eto#2122]
Component Referenced - System.Drawing.Common 6.0
By Component - Emgu.CV.Bitmap 4.5.5.4823

See this link
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Affects Platforms
Linux x86, Linux x64, Linux arm32, Linux arm64

Working Component System.Drawing.Common 5.0.3

Unless there is a way to go from a bmp byte array to Emgu.CV.Image<Gray, byte> without using a System.Drawing.Bitmap. Then I cannot update.

**Comment by cwensley** [comment]
Hey @davidscherf,

I'm not sure how this relates to Eto?  Perhaps you reported to the wrong repo, this isn't [Emgu CV](https://github.com/emgucv/emgucv).

**Comment by davidscherf** [comment]
My bad, opening too many git sites at one time
