### ISSUE TITLE
Mobile development

### ISSUE THREAD

**Issue by Barshan-Mandal** [picoe/Eto#2124]
how to start development for mobile platforms too using eto.forms

**Comment by cwensley** [comment]
Hey @Barshan-Mandal, unfortunately the iOS and Android platforms have not been kept up to date so aren't very usable right now.  It would take a some effort to get those mobile platforms working again.

The main reason the focus shifted primarily to desktop is that there wasn't enough interest in mobile use with Eto.Forms.  This could change, however.
