### ISSUE TITLE
[Feature Request] Support XDG-Desktop-Portals for consistent file pickers

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2138]
On Linux, it's possible to pass the environment variable `GTK_USE_PORTAL=1` to GTK applications in order for those to use XDG-Desktop-Portals for consistent file pickers and similar.
Currently, Eto does not support those. Here's a demonstration showing an Eto application trying to invoke a file picker and Firefox (a gtk program) run with the aforementioned environment variable:
![image](https://user-images.githubusercontent.com/38186597/152955775-04f0cab1-758b-4f94-aaa6-e724c7bf5705.png)
![image](https://user-images.githubusercontent.com/38186597/152955762-7a36c24c-c7d3-4ea5-84c4-f4ecb213610d.png)

As far as I can see, GTK already handles [invoking native file pickers](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkfilechoosernativeportal.c#L445) if the environment variable is set, which GTKSharp also [seems to support/call](https://github.com/GtkSharp/GtkSharp/blob/a23d44fb82975711cfcaa400cd7f3e4988d15bbf/Source/Libs/GtkSharp/NativeDialog.cs).

**Comment by cwensley** [comment]
I'm not sure I follow.. Eto uses the standard FileChooserDialog apis like any other GTK+/GtkSharp app, and the code to look at the environment variable is in GTK+ to determine which type of FileChooserDialog implementation to use, then why wouldn't it just work?  How are you setting the environment variable?

**Comment by cwensley** [comment]
Ah.. it appears Eto needs to use `Gtk.FileChooserNative` in this case, which looks like it could easily be done.

**Comment by cwensley** [comment]
Looks like we'll have to wait till the next GtkSharp release, as it doesn't have [this fix](https://github.com/GtkSharp/GtkSharp/commit/c362ad14685f358ea261c7753685f238ffd0ce3b) in where it allows a null parent.  @harry-cpp is there something stopping a new GtkSharp release?

**Comment by harry-cpp** [comment]
I've merged some less safe stuff to the develop branch 😅, I'll try to push out a new stable version of GtkSharp nuget tomorrow.

**Comment by cwensley** [comment]
No worries, it's much appreciated @harry-cpp.  I haven't made a release in a while too so no rush!

**Comment by harry-cpp** [comment]
I've pushed the new version of the nugets after a bit of testing, hopefully everything is fine :D

**Comment by Miepee** [comment]
Leaving a note here, that ideally it should work with all current Dialogs (About, Color, Dialog, File, Font, OpenWith, SelectFolder) Although I'm not sure how feasible that is. Not that familiar with GTK, so don't know if they provide native dialogs for anything else other than filepickers.

**Comment by harry-cpp** [comment]
Gtk only provides native dialogs for file pickers, as it wouldn't make sense for anything else.
