### ISSUE TITLE
Cannot get icons with Icon.FromResources

### ISSUE THREAD

**Issue by WileyNg** [picoe/Eto#2164]
## Expected Behavior
Getting the icons with Icon.FromResources

## Actual Behavior
![image](https://user-images.githubusercontent.com/5993201/158283071-68c0530b-ac8d-4f70-ab2e-0e629449e5f5.png)
![image](https://user-images.githubusercontent.com/5993201/158283246-e4dac286-ef03-4eae-9ce2-717345e47309.png)

Error
System.ArgumentException: 'Resource 'Terrain.Resources.Terrain.png' not found in assembly 'Terrain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
Parameter name: resourceName'

## Steps to Reproduce the Problem

  1.  Import Eto.dll (2.6)
  2. Eto.Drawing.Icon SculptIcon_icon = Eto.Drawing.Icon.FromResource("Terrain.Resources.Terrain.png");
  3. 

## Code that Demonstrates the Problem

```
Eto.Drawing.Icon SculptIcon_icon = Eto.Drawing.Icon.FromResource("Terrain.Resources.Terrain.png");
```

## Specifications

  - Version: 2.6
  - Platform(s): 
  - Operating System(s):

**Comment by cwensley** [comment]
The Icon/Image must be an Embedded Resource.  In your csproj, something like this is usually helpful:

```
<EmbeddedResource Include="Resources\**\*.*" />
```

Hope this helps.

**Comment by WileyNg** [comment]
Big Thanks! You saved me hours of research time!

![image](https://user-images.githubusercontent.com/5993201/158334541-f5b20bf0-85ff-4e15-8f1e-90f7256ed31a.png)

I also wonder how I can align the text in TabControl --> TabPage to middle? 
Right now it looks weird having the Text aligning to the Top.

TabControl didn't have such exposed properties..

Also how do I change the text font for the TabPage.Text?

**Comment by WileyNg** [comment]
After asking a while, I am assuming Eto has limits and these unexposed properties cannot be changed?

**Comment by cwensley** [comment]
For properties that aren't exposed, or platform-specific functionality you can use native styles.  E.g. this would fix it for you:

```c#
myTabControl.Styles.Add<Eto.Wpf.Forms.Controls.TabPageHandler>(null, h =>
{
	if (h.Control.Header is System.Windows.Controls.StackPanel stackPanel)
	{
		var textBlock = stackPanel.Children.OfType<System.Windows.Controls.TextBlock>().FirstOrDefault();
		if (textBlock != null)
		{
			textBlock.VerticalAlignment = System.Windows.VerticalAlignment.Center;
		}
	}
});
```

That being said, I think having it centred by default would make sense so I've added #2197 to get that fixed up.

Do note that other platforms may limit the logical size of the icon to 16x16 (e.g. MacOS, WinForms).

Closing this issue as it has been answered.
