### ISSUE TITLE
Add a HostControl to enable hosting native controls

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#2167]
This control would allow one to host native controls without having to create platform-specific assemblies.

This is mainly necessary for platforms such as WPF, where by default it has only a single HWND for the entire window.

**Comment by rafntor** [comment]
What is returned as `NativeHandle` for controls when targeting Wpf today; do all controls return the (same) Hwnd of the Main-window?

**Comment by rafntor** [comment]
Also, would this control also provide a 'setable' handle so that when interfacing to a native control that offers a handle for Eto to display can be supported (as opposed to Eto offering a handle for the native control to use) ?
