### ISSUE TITLE
Unable to mkbundle or run app under MacOS

### ISSUE THREAD

**Issue by devmaestro1** [picoe/Eto#2173]
Hello,

I am trying to create a MacOS deployment of my ETO app that works fine under Windows. Under a windows command-prompt I am executing this command:

`mkbundle App.exe --simple -o App --cross mono-6.8.0-osx-10.9-x64 `

When I do so, I get the error:

_ERROR: Unable to load assembly `netstandard' referenced by `(projectdir)\artifacts\bin\Eto.dll'_

I should add that I am very new to understanding how to bundle with MacOS. I have read a number of StackOverflow articles and a number of issues raised in this project but haven't managed to understand what I am missing.  

I have also tried to simply try running my app under MacOS mono by copying my artifacts folder directly over to MacOS and trying "mono App.exe" but I get the follow error suggesting gtk-2 is missing even though I know it is installed:

`System.TypeInitializationException: The type initializer for 'GLib.Global' threw an exception. ---> System.DllNotFoundException: GLib: libglib-2.0-0.dll, libglib-2.0.so.0, libglib-2.0.0.dylib, glib-2.dll`

Any help to get the app running and bundled on MacOS would be much appreciated.

**System info:** 
Windows 10 w/ Mono 6.10
MacOS 10.16 w/ Mono 6.12

**Comment by cwensley** [comment]
Hey @devmaestro1, did you figure out your issue?  For macOS, you need to zip up the .app bundle, which when you compile in Release mode will (by default) bundle mono (for .net 4.x), or .NET Core for .NET 5+.  Do note, however, that building on Windows will make your users will have to run a few commands in Terminal to allow it to run (on macOS 10.11 Big Sur or later), as detailed [here](https://github.com/picoe/Eto/wiki/Publishing-your-App#publish-for-mac).  Additionally, you'll want to [code sign and notarize your app](https://github.com/picoe/Eto/wiki/Mac-Code-Signing-and-Notarization) which can only be done on a Mac.

**Comment by cwensley** [comment]
To be clear, when you build using the Eto.Platform.Mac64 nuget package, it'll build an `MyProgram.app` folder in your output directory that is used to run on Mac.  You can't simply run the .exe like you can on windows or linux.

**Comment by cwensley** [comment]
Another thing to consider is to use .NET 6 vs. .NET 4.x/mono, which is old and no longer getting updates.

**Comment by devmaestro1** [comment]
Hi @cwensley, Thanks very much for taking the time to give me a primer! I tried the .app folder out and it's running fine now! Apologies I missed some of the Wiki content. I am going through it now.  Is there any where I can find out how this .app folder is built?

Can I ask a related question - would you recommend that I change my solution so it compiles on VS for Mac? Would this make life easier for running/testing my ETO app?

Also, you mention moving to .NET 6 but my hope is to allow the software to run on as many Windows versions as possible (back to Win7 if possible). Are there some gotchas that I might be missing while attempting this? I obviously don't want to find a later Mac version breaks my app because I'm using .NET 4.x.

Thanks again!

**Comment by cwensley** [comment]
Hey @devmaestro1,

Glad you got it working.  The .app folder is built using the targets files in the .nuget package, which are located [here](https://github.com/picoe/Eto/tree/develop/src/Eto.Mac/build).

I use VS Code on Mac these days, which works really well.  The VS for Mac Preview might be worth looking at these days but trying to use it will just be an exercise in frustration imo.

.NET 6 is supported for running on pretty much any version of windows possible, see [here](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#supported-releases).  Or, you could easily target .NET 6 on Mac and .NET 4.x on Windows.    The gotcha's of using mono on Mac mean you won't be able to distribute an ARM64/Apple Silicon version of your app, as it is only supported running with x64.

Hope this helps.

**Comment by devmaestro1** [comment]
Thanks very much for all that useful information, @cwensley. It's a little hard to get my head around all the dependencies but that was very helpful!
