### ISSUE TITLE
How to update the parent's (stacklayout) autosizing? (Solved)

### ISSUE THREAD

**Issue by WileyNg** [picoe/Eto#2179]
### Discussed in https://github.com/picoe/Eto/discussions/2178

<div type='discussions-op-text'>

<sup>Originally posted by **WileyNg** April  4, 2022</sup>

![image](https://user-images.githubusercontent.com/5993201/161497433-6e7d9e2c-82bc-40b2-83fc-364bb69eb9d3.png)

![image](https://user-images.githubusercontent.com/5993201/161495829-0075f256-edf3-421d-92ac-1c2f1ed7d0f6.png)
![image](https://user-images.githubusercontent.com/5993201/161495868-080b3eea-f2fa-423e-9e54-fe4bfc71a341.png)

I made a custom-made expander box but i am getting a hard time to update the parent's autosizing, after the expander is expanded.
Is it possible to shed some light for me on this?

```C#
        public void OnExpanded()
        {
            Content = expanded ? Control : new DynamicLayout();
            
            int _ContentSize = (int)Content.GetPreferredSize().Height + (Padding * 4) + (int)textSize.Height;
            Height = _ContentSize;
            DrawGraphics();
            Parent.Parent.Invalidate(); ;
            Invalidate();
        }
```

I made a method which is called when the Header is clicked(MouseUp). 
The collapsed expander will just have an empty DynamicLayout, while the expanded one will have all the controls.
The height I get it with a GetPreferredSize. 

The problem is, the control (StackLayout) which the Custom-Expander is nested in, doesn't adjust the sizing itself whenever the child control height is changed.

I tried to call Invalidate() function for the StackLayout by finding the Parents of the custom-expander, but in vain.

</div>

**Comment by WileyNg** [comment]
Problem Solved.

**Comment by allsorts46** [comment]
I've had a similar issue, perhaps this can help you:

Most of the XxxLayout classes inherit from a base Layout class, but StackLayout does not. Actually StackLayout is not really a layout in its own right, internally it's a Panel which contains nesteted TableLayouts.

There is a Layout.Update() method which is supposed to take care of updating layouts, but as StackLayout doesn't inherit from Layout it doesn't have this method.

To work around this, I did the following:

Create an interface to provide the method:

```
public interface ILayout
{
	void Update();
}
```

I put this in /src/Eto/Forms/Layout/Layout.cs. Make the Layout class implement the interface (it already has the public method).

Then you can also make StackLayout (/src/Eto/Forms/Layout/StackLayout.cs) implement ILayout, with an implementation that looks like this:

```
public virtual void Update()
{
	if (Content is ILayout nestedLayout)
		nestedLayout.Update();
}
```

Which will pass the request on to the inner table.

**Comment by cwensley** [comment]
Looks like it was solved as noted in the discussion.

**Comment by WileyNg** [comment]
Hi @allsorts46 
Many Thanks! I tried your way but couldn't get it to work.
at the end I worked it around by forcing the control to GetPreferredSize of its children whenever there is a MouseUp event. 

Here is the result:

https://user-images.githubusercontent.com/5993201/163891153-9fc8ec07-064b-44ef-8a44-440b3dae2200.mp4

**Comment by greatawesome** [comment]
I like the look of that expander. Is it entirely custom, or does it derive from the Eto Expander control?

**Comment by WileyNg** [comment]
It is entirely from custom, as with everything else.
