### ISSUE TITLE
Generated .Mac project failed to build in Visual Studio 2019 for Mac

### ISSUE THREAD

**Issue by kztk-m** [picoe/Eto#2180]
The project `PROJECTNAME.Mac` generated from the Eto.Forms template with the default setting failed to build in Visual Studio 2019 for Mac. Interestingly, there is no problem in Visual Studio 2022 for Mac Preview, the `dotnet` command installed as a part of .NET 6.0 SDK, and `MSBuild.dll` bundled in `Visual Studio.app`. The issue happens when I try to build the generated project (e.g., by Command + K) in Visual Studio 2019.

## Expected Behavior

The building of the generated template succeeds, while we need an additional step to run the generated executable.

## Actual Behavior

The build failed at Line 255 of Eto.Platfrom.Mac64.targets, located at ~/.nuget/packages/eto.platform.mac64/2.6.1/build/Eto.Platform.Mac64.targets. The line includes:

     <Exec Command="chmod +x &quot;$(LauncherFileWithPath)&quot;" Condition="'$(OS)'=='Unix'" EchoOff="True" />

The error happened is:

      chmod: bin/Debug/net5.0/PROJECTNAME.Mac.app/Contents/MacOS/PROJECTNAME.Mac: No such file or directory

I realized that there is no "PROJECTNAME.Mac" file in the directory `obj/Debug/net5.0/macbuild/bin/net5.0/osx-x64/`, and the file has not been copied to `bin/Debug/net5.0/PROJECTNAME.Mac.app/Contents/MacOS/` at the step "Target MacBuildAppBundleWithoutRuntime". 

When I use `dotnet build`, it generates `obj/Debug/net5.0/macbuild/bin/net5.0/osx-x64//PROJECTNAME.Mac` at a point of the building step, and no issue happens. I also tried `mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll` as I (mistakenly) thought that this is the build command Visual Studio 2019 for Mac uses, but it has no issue (i.e., it generates `obj/Debug/net5.0/macbuild/bin/net5.0/osx-x64/PROJECTNAME.Mac` and copies the file to `bin/Debug/net5.0/PROJECTNAME.Mac.app/Contents/MacOS/`). Interestingly, there is no such issue in Visual Studio 2022 for Mac Preview. 

## Steps to Reproduce the Problem

  1. Generate a project from the "Eto.Forms" template  
  2. Right click the project "PROJECTNAME.Mac" and choose "Build PROJECTNAME.Mac" in the context menu. 
  

## Code that Demonstrates the Problem

Just the generated code from the Eto.Forms template, with the default setting. 

## Specifications

  - Version: 2.6.1
  - Platform(s): Mac
  - Operating System(s): macOS 12.3
  - XCode: Version 13.3 (13E113)
  - Visual Studio 2019 for Mac: 8.10.21 (build 4)

I am afraid that I do not know how to test (even build) the latest commit in the development branch as I am quite new to .NET/C# ecosystem.

**Comment by cwensley** [comment]
I'm not sure why, and I'm not super inclined to figure this out.  VS for Mac 2019 has so many errors and problems like this that I can hardly recommend using it.  Additionally, you'll be limited to using net4x and mono for debugging. 

You've already figured out a great solution to this problem, which is to use VS for Mac 2022.  Better yet, use VS Code.

**Comment by cwensley** [comment]
By the way, [this the same problem that I reported for VS 2022](https://developercommunity.visualstudio.com/t/UseAppHost-property-is-not-respected-in/1543417), which is why it is fixed in that version.  This was _not_ an issue with VS 2019 before, but I guess it is now.  

To get it working in VS 2019, you can add `TreatAsLocalProperty="UseAppHost"` to the Project tag, and add `<UseAppHost>true</UseAppHost>` in a PropertyGroup, like so:

```
<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="UseAppHost"> <!-- add this -->
	
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>
    <UseAppHost>True</UseAppHost>. <!-- and add this -->
...
```

**Comment by kztk-m** [comment]
Thank you. I added the suggested edit to .csproj and now the project compiles successfully! 
Also, I understand the situation about VS for Mac 2019, and I am happy to use VS for Mac 2022 Preview, or VSCode.
Thank you again.

**Comment by cwensley** [comment]
Great, glad it's working for you.  I'm closing this since this is a bug in VS for Mac 2019.
