### ISSUE TITLE
Display ContextMenu under ButtonToolItem

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2182]
I'm using Eto 2.6.1.

Is there any way to display the ContextMenu strictly under the bottom left corner of the ButtonToolItem?

Or: how to find out the coordinates/boundaries of an arbitrary toolbar button?

Or maybe there is a possibility to develop a "DropDownToolItem"?

**Comment by cwensley** [comment]
Hey @Serg-Norseman, thanks for the feedback!

Currently there's no way to get the locations of the tool items, but that would be nice to have.

I think having a DropDownToolItem would be a more ideal solution for what you're trying to do.

**Comment by Serg-Norseman** [comment]
I'm trying to make such a component. So far only for Wpf.

```
   [Handler(typeof(DropDownToolItem.IHandler))]
    public class DropDownToolItem : ToolItem
    {
        new IHandler Handler { get { return (IHandler)base.Handler; } }

        public ContextMenu ContextMenu
        {
            get { return Handler.ContextMenu; }
            set { Handler.ContextMenu = value; }
        }

        public DropDownToolItem() : base()
        {
        }

        public new interface IHandler : ToolItem.IHandler, IContextMenuHost
        {
        }
    }
```

```
public class DropDownToolItemHandler : ToolItemHandler<swc.Button, DropDownToolItem>, DropDownToolItem.IHandler
    {
        Image image;
        readonly swc.Image swcImage;
        readonly swc.TextBlock label;
        ContextMenu contextMenu;

        public DropDownToolItemHandler()
        {
            Control = new swc.Button();
            swcImage = new swc.Image { MaxHeight = 16, MaxWidth = 16 };
            label = new swc.TextBlock();
            var panel = new swc.StackPanel { Orientation = swc.Orientation.Horizontal };
            panel.Children.Add(swcImage);
            panel.Children.Add(label);
            Control.Content = panel;
            Control.Click += Control_Click;
            sw.Automation.AutomationProperties.SetLabeledBy(Control, label);
        }

        private void Control_Click(object sender, RoutedEventArgs e)
        {
            //Widget.OnClick(EventArgs.Empty);
        }

        public override string Text
        {
            get { return label.Text.ToEtoMnemonic(); }
            set { label.Text = value.ToPlatformMnemonic(); }
        }

        public override string ToolTip
        {
            get { return Control.ToolTip as string; }
            set { Control.ToolTip = value; }
        }

        public override Image Image
        {
            get { return image; }
            set {
                image = value;
                swcImage.Source = image.ToWpf(Screen.PrimaryScreen.LogicalPixelSize, swcImage.GetMaxSize().ToEtoSize());
            }
        }

        public override bool Enabled
        {
            get { return Control.IsEnabled; }
            set {
                Control.IsEnabled = value;
                swcImage.IsEnabled = value;
            }
        }

        public ContextMenu ContextMenu
        {
            get { return contextMenu; }
            set {
                contextMenu = value;
                Control.ContextMenu = contextMenu != null ? contextMenu.ControlObject as sw.Controls.ContextMenu : null;
            }
        }
    }
```

`platform.Add<DropDownToolItem.IHandler>(() => new DropDownToolItemHandler());
`

At runtime, an exception is thrown on the DropDownToolItem() constructor:
InvalidOperationException: Type for '...DropDownToolItem' could not be found in this platform.

Why?

**Comment by cwensley** [comment]
Very odd, everything looks correct.  Are you adding it to the correct platform instance?  E.g. if you're creating the instance yourself, are you passing it to the constructor of Application?

**Comment by Serg-Norseman** [comment]
Wow! Thanks a lot! This is exactly what I didn’t think to do - pass the created platform instance to the Application constructor. 

Happened! Now I have a prototype for experiments :)

**Comment by Serg-Norseman** [comment]
I was able to write a draft working implementation for Wpf and Gtk only. For Mac, unfortunately I can't. If necessary, I can also make an implementation for WinForms. I tried to follow your coding style. 

I hope this will be useful for the Eto project and will be included in the new version, because very much in demand in my project.

If you need - put the requirements and I will add everything that is missing.

**Comment by cwensley** [comment]
Fixed in #2317

**Comment by Serg-Norseman** [comment]
I recently got free and began to translate my program to this new functionality. Does not work.

If I write:
`<DropDownToolItem x:Name="tbLoadMRU" />`
- everything is ok. Starting up. Works.

If I write:
```
<DropDownToolItem x:Name="tbPedigree" Image="{Resource Resources.btn_scroll.gif, GKCore}">
        <ButtonMenuItem x:Name="miPedigree_dAboville2" Click="miPedigree_dAbovilleClick" />
        <ButtonMenuItem x:Name="miPedigree_Konovalov2" Click="miPedigree_KonovalovClick" />
</DropDownToolItem>
```
I am getting an exception:
'Cannot set unknown member '{http://schemas.microsoft.com/winfx/2006/xaml}_UnknownContent'' Line number '28' and line position '10'.
where line 28 is: "`<ButtonMenuItem x:Name="miPedigree_dAboville2" Click="miPedigree_dAbovilleClick" />`".

All variants do not work:
- `<ButtonMenuItem x:Name="miPedigree_dAboville2" Click="miPedigree_dAbovilleClick" />`
- `<ButtonMenuItem x:Name="miPedigree_dAboville2" />`
- `<ButtonMenuItem  />`
- `<ButtonMenuItem Text="test" />`

If I write:
```
<DropDownToolItem x:Name="tbPedigree" Image="{Resource Resources.btn_scroll.gif, GKCore}">
</DropDownToolItem>
```
- it work.

If I add items with code at runtime, it works.

Version: 2.7.2

**Comment by Serg-Norseman** [comment]
And in vain we decided to do without ContextMenu. Now OnOpening/OnClosed/OnClosing are unavailable. Flexibility is lost.

Moreover, now with the new version, the names of DropDownToolItem are no longer available and my working classes will have to be renamed to keep the functionality.

**Comment by cwensley** [comment]
> I am getting an exception:
'Cannot set unknown member '{[http://schemas.microsoft.com/winfx/2006/xaml}_UnknownContent](http://schemas.microsoft.com/winfx/2006/xaml%7D_UnknownContent)'' Line number '28' and line position '10'.

This is likely because we need to add a `ContentProperty` attribute to the `DropDownToolItem`, this would likely work for now until that is put in:
```
<DropDownToolItem x:Name="tbPedigree" Image="{Resource Resources.btn_scroll.gif, GKCore}">
   <DropDownToolItem.Items>
        <ButtonMenuItem x:Name="miPedigree_dAboville2" Click="miPedigree_dAbovilleClick" />
        <ButtonMenuItem x:Name="miPedigree_Konovalov2" Click="miPedigree_KonovalovClick" />
   </DropDownToolItem.Items>
</DropDownToolItem>
```

> And in vain we decided to do without ContextMenu. Now OnOpening/OnClosed/OnClosing are unavailable. Flexibility is lost.

Yes these should be added to DropDownToolItem directly, thanks for pointing that out.

**Comment by Serg-Norseman** [comment]
Thanks a lot! It worked!

**Comment by Serg-Norseman** [comment]
Also, it seems to me (but I don’t insist) that it would be nice if we added the ISubmenu interface to DropdownToolItem - this could simplify the code in some cases (uniform access to Items).

**Comment by Serg-Norseman** [comment]
Just now I accidentally noticed that in Windows (Wpf), the background color of the DropdownToolItem is different from the neighboring buttons. Somewhere something is missing

**Comment by Serg-Norseman** [comment]
The following is also broken:

`tbModes.Items.Add(new ButtonMenuItem());` - it work
`tbModes.Items.Add(new SeparatorMenuItem());` - it throws exception: "Unable to cast object of type 'System.Windows.Controls.Separator' to type 'System.Windows.Controls.MenuItem'."

(where tbModes - DropdownToolItem)

When there was a ContextMenu - everything worked properly.

**Comment by Serg-Norseman** [comment]
And one more thing: if several RadioMenuItems are added, now the item with Checked has a black square if the mouse is not hovered, and a normal image if the cursor is on the item.

**Comment by cwensley** [comment]
@Serg-Norseman thanks for the update, though could you create a separate issue(s) for the additional problems so it can be tracked and fixed?  

Thanks!
