### ISSUE TITLE
is it possible to make the leftmost control in a DynamicRow "stretch" instead of always the rightmost 

### ISSUE THREAD

**Issue by WileyNg** [picoe/Eto#2189]
![image](https://user-images.githubusercontent.com/5993201/163831694-a607adf9-31be-4a7f-bed6-381879ed305b.png)

is it possible to make the leftmost control in a DynamicRow "stretch" instead of always the rightmost 

I am trying to make a blank space on the left-most cell so that it is the one that is "stretched"
But I don't seem to be able to do that without some obtuse lines of code.

Am I missing anything?

**Comment by cwensley** [comment]
Yes, just set the xscale parameter to true, which maps to the `DynamicControl.XScale` property.

e.g.
```c# 
layout.BeginHorizontal();
layout.Add(myControlToExpand, xscale: true);
layout.Add(autoSizingControl1);
layout.Add(autoSizingControl2);
layout.EndHorizontal();
```
Hope this helps!

**Comment by cwensley** [comment]
I'm assuming the thumbs up is that it worked.  Closing, thanks!
