### ISSUE TITLE
SubMenuItem doesn't respond to click, but right is ok(GTK)

### ISSUE THREAD

**Issue by keepwn** [picoe/Eto#219]
I Build a ContextMenu.
The code like this:

    var menu = new ContextMenu();
    menu.Items.Add(new Actions.Refresh());
    var create = menu.Items.GetSubmenu("Add");
    create.Items.Add(new Actions.CreateDir());
    create.Items.Add(new Actions.CreateFile());

When i click the `CreateDir` SubMenuItem, it doesn't respond to click. (But right-click is ok)
Then i found, when change these code (Eto\Source\Eto.Gtk\Forms\Menu\ButtonMenuItemHandler.cs):

    protected override void Initialize()
    {
        base.Initialize();
        Control.Activated += Connector.HandleActivated;
    }

To:

    protected override void Initialize()
    {
        base.Initialize();
        Control.ButtonPressEvent += Connector.HandleActivated;
    }

Will be ok.

Should Change others MenuItem's HandleActivated Event replace with `ButtonPressEvent`?

**Comment by cwensley** [comment]
Closing as this does not seem to be reproducible.  If you are still running into this problem, feel free to reopen but I'll need more details on how to reproduce it. Thanks for reporting the issue!
