### ISSUE TITLE
Using Eto.Forms in .NET Plugin

### ISSUE THREAD

**Issue by tymokvo** [picoe/Eto#2202]
Hello,

I'm trying to use `Eto.Forms` in an F# plugin to a closed-source C++/C# application where the host application may call the method in the plugin that I'm authoring a number of times throughout the lifetime of the main thread.

Since I don't have access to the `Main` method, I am not able to successfully display an `Eto.Forms.Form` instance more than once, as the `Eto.Forms.Application` instance either already exists or has been disposed when the library method is called more than once. 

The plugin class is also instantiated and destroyed every time the plugin is run, so there is not a long-lived reference to the `Application` that I can use.

## Expected Behavior

Instantiating `Form` instances can be done from plugin libraries that are called an indeterminate number of times from a host application.

## Actual Behavior

A few different outcomes are possible:
1. `System.InvalidOperationException: The Eto.Forms Application is already created.`
2. `System.ObjectDisposedException: Cannot access a disposed object.`

## Steps to Reproduce the Problem

Since it's a peculiar situation, I created an example repo [here](https://github.com/tymokvo/issue-examples/tree/main/picoe/Eto/UseInPlugin). The readme has the steps to reproduce.

- Version: `2.6.0.0`
- Platform(s): Winforms
- Operating System(s): Windows 10
  
Thank you!

**Comment by cwensley** [comment]
Try using something like the following to 'attach' to an existing application:
```c#
if (Application.Instance == null)
  new Application([platform of host app]).Attach();
```

**Comment by tymokvo** [comment]
Hm, I've tried that (That F# library has a type that calls `.Attach()`) with and without a platform and it still results in `System.ObjectDisposedException: Cannot access a disposed object.`

**Comment by cwensley** [comment]
Hm, though it looks like you're explicitly disposing the Application object.  You may have to set `Application.Instance = null` as well so it doesn't try to use it again..

**Comment by cwensley** [comment]
.. or simply just don't dispose the application.

**Comment by tymokvo** [comment]
Lol, just noticed that, thanks. It seems to work in my example, so I'll close if it works in the real plugin too. Though, I thought that I had tried that before.

**Comment by tymokvo** [comment]
Ok, so that mostly works. I've ended up with:

```fsharp
let app = match Application.Instance with
          | null -> (new Application(Eto.Platforms.WinForms)).Attach()
          | a -> a
```
which is called early in the plugin entrypoint.

But I can never call `.Run()` on any form or it throws a null ref exception. However, calling `.Show()` or `.ShowDialog()` on a form does work.

Thanks again!

**Comment by cwensley** [comment]
Cool!  Just do note that this won't work on macOS unless it is run inside an .app bundle and has associated AppKit things actually running.

**Comment by tymokvo** [comment]
Got it, thanks for the tip. The host app is Windows only, so it shouldn't be an issue.
