### ISSUE TITLE
Is it possible to build a Net6 Eto app for Mac+Linux from Windows vs2022?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#2205]
I am trying to port a working app from `vs2019, Eto 2.5.11, netcoreapp3.1` to `vs2022, Eto 2.6.1, net6` and failing.

What would the setup look like? Without a template or extension, I am at a loss.

Thanks.

**Comment by cwensley** [comment]
Not sure what to suggest here.. change the tfm to net6.0 and update your NuGet packages ought to be enough..  What problems are you running into?

**Comment by LaraSQP** [comment]
I got everything updated to net6 but for the wpf project that seems to go no further than net4.6.2

My mistake?

**Comment by cwensley** [comment]
can you not just update the .csproj and write 'net6.0' instead of 'net462' ??  or are you trying to use the GUI?

**Comment by LaraSQP** [comment]
Found it.

The correct switch is `net6.0-windows`, as in:

    <TargetFrameworks>net6.0-windows</TargetFrameworks>

All is well with the world now.

Thank you for the quick replies.
