### ISSUE TITLE
Linux, net6, problems with EtoSpecialFolder and Assembly.GetEntryAssembly

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#2210]
I am trying to get the path to the folder where a `net6.0, single-file, self-contained` program is executed.

Consider a user `u`, a program named `pathTest` in the folder `/home/u/Desktop/pathTest`

Running `pathTest` at the prompt in its folder via `$./pathTest` yields the following `EtoSpecialFolders`:

	EtoSpecialFolder.ApplicationResources = [null]
	EtoSpecialFolder.ApplicationSettings = /home/u/.config
	EtoSpecialFolder.Documents = /home/u

Using Assembly.GetEntryAssembly:

	Assembly.GetEntryAssembly().Location = /home/u/.local/share

How do I get `/home/u/Desktop/pathTest`, the folder from which `pathTest` is being run?

Thank you.

**Comment by cwensley** [comment]
Take a look at this info: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview#api-incompatibility

In particular, you're probably looking for [AppContext.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory#system-appcontext-basedirectory)

**Comment by LaraSQP** [comment]
Thank you for the quick reply.
