### ISSUE TITLE
How to set the Cursor property of an arbitrary component in xeto?

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2215]
Does not work:

`<Label x:Name="lbl1" TextAlignment="Center" VerticalAlignment="Center" MouseDown="lbl1_Click" Cursor="Pointer" />`

**Comment by cwensley** [comment]
`Cursor="{x:Static Cursors.Pointer}"` ?

**Comment by Serg-Norseman** [comment]
It worked! Thanks a lot!!!

P.S. Sorry for the stupid question. I didn't think of that option
