### ISSUE TITLE
Multiple target frameworks for Eto.Forms

### ISSUE THREAD

**Issue by cyanfish** [picoe/Eto#2248]
Currently the main Eto.Forms [project](https://github.com/picoe/Eto/blob/develop/src/Eto/Eto.csproj) only has a single target for netstandard:
`<TargetFrameworks>netstandard2.0</TargetFrameworks>`

Depending on a netstandard project can cause some issues (e.g. https://github.com/dotnet/standard/issues/545).

This could be fixed by building against multiple target frameworks, e.g.
`<TargetFrameworks>netstandard2.0;netcoreapp3.1;net462</TargetFrameworks>`

I'm trying to avoid using netstandard builds in my project because of the linked issue. It would be awesome if the Eto nuget package could have multiple builds.

**Comment by cwensley** [comment]
Thanks for submitting the request!  I don't see why we couldn't add more frameworks to Eto.dll.  I'd probably jump to net6.0 vs netcoreapp3.1 as its EOL this year.
