### ISSUE TITLE
[Gtk] PropertyGrid has no text 

### ISSUE THREAD

**Issue by Sejsel** [picoe/Eto#2251]
With 2.7.0, PropertyGrid stopped showing text on the Gtk platform. On 2.6.1, text was blurry, but readable, on 2.7.0 it does not appear at all.

## Expected Behavior (2.6.1)
![image](https://user-images.githubusercontent.com/998408/178162016-d0ce0ce1-9266-49d0-9e95-21f535d7f5fc.png)

## Actual Behavior (2.7.0)
![image](https://user-images.githubusercontent.com/998408/178161916-f4219455-f63c-49d0-9225-9ed6480cc05d.png)

## Steps to Reproduce the Problem
Look at any property grid with contents in Eto 2.7.0.

## Code that Demonstrates the Problem
The test application PropertyGrid section exhibits the issue.

## Specifications

  - Version: 2.7.0
  - Platform(s): Gtk3
  - Operating System(s): Arch Linux, Adapta Nokto Eta gtk theme

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Are you using Eto.Gtk or Eto.Gtk3?

**Comment by Sejsel** [comment]
I am using Eto.Gtk, sorry, should've been more specific :)

**Comment by cwensley** [comment]
No worries, I only ask to try to eliminate that as a possibility before looking into it further. 😀
