### ISSUE TITLE
WPF: StackLayout ToNative() produces empty container

### ISSUE THREAD

**Issue by GulamY** [picoe/Eto#2272]
## Expected Behavior
The content of StackLayout converted to native WPF component is preserved

## Actual Behavior
The content of StackLayout converted to native WPF component is missing
The issue is reproducible with TableLayout as well.

## Steps to Reproduce the Problem

  1. Create a WPF application and add ETO nuget package references (Eto.Forms and Eto.Forms.WPF)
  2. Create two classes (see snippet section) of Eto controls.
  3. Add `new StackLayoutDemoClass().ToNative()` to WPF grid (created by default) and run the application.
Notice that that the background changed color, but there is no text.
  4. Change `StackLayoutDemoClass` to `PanelDemoClass ` and run the app again
Notice that the text is now displayed on the screen

## Code that Demonstrates the Problem

```
public class StackLayoutDemoClass : StackLayout
{
    public StackLayoutDemoClass()
    {
        BackgroundColor = Colors.Bisque;
        var label = new Label { Text = "Test" };
        Items.Add(label);
    }
}

public class PanelDemoClass : Panel
{
    public PanelDemoClass()
    {
        BackgroundColor = Colors.Bisque;
        var label = new Label { Text = "Test" };
        Content = label;
    }
}
```

## Specifications

  - Version: 2.7.0
  - Platform: WPF
  - Operating System(s): Win 10 and Win 11

**Comment by cwensley** [comment]
Hey @GulamY, try `ToNative(true)`.  You need to specify that you are using it outside of an Eto container so that it properly calls OnLoad/LoadComplete/etc, which the StackLayout uses to create its contents.

**Comment by GulamY** [comment]
It worked! Thanks a lot.
I will close this issue.
