### ISSUE TITLE
Fresh project in JetBrains Rider (latest version) fails to start debug

### ISSUE THREAD

**Issue by MelanieT** [picoe/Eto#2289]
## Expected Behavior
Debugging should start when debug button is pressed

## Actual Behavior
Exception is thrown:
---> System.InvalidOperationException: Platform type 'Eto.Mac.Platform, Eto.Mac64' was loaded but is not valid in the current context.  E.g. Mac platforms require to be in an .app bundle to run
   at Eto.Platform.Get(String platformType, Boolean allowNull, List`1 errors)
   --- End of inner exception stack trace ---
   at Eto.Platform.Get(String platformType, Boolean allowNull, List`1 errors)
   at Eto.Forms.Application..ctor(String platformType)
   at EtoTest.Mac.Program.Main(String[] args)

## Steps to Reproduce the Problem

  1. Instal or upgrade JetBrains Rider to newest version
  2. Run: ~/.dotnet/dotnet new -i "Eto.Forms.Templates::*"
  3. Start Rider and, from the new project templated, select "Eto Application"
  4. Wait for the application template to generate the application, unload the WPF and GTK stubs
  5. Click on the debug icon (or run icon)

## Specifications

  - Version: 2.7.1
  - Platform(s): Mac
  - Operating System(s): MacOS 11.6.1

The expectation would be that the template generates code and project that are capable of being compiled and worked with. This doesn't happen, the template generated project cannot be debugged from within the GUI and I know no other way to debug it. Compile is successful as long as the project representing other platforms are unloaded.

**Comment by cwensley** [comment]
Thanks for submitting the issue.  While I have not used Rider, you may need to set the "executable" to `/path/to/MyApp.app/Contents/MacOS/MyApp` for debugging to work.  

Eto's .props files in the nuget packages set the `<RunCommand>` property which should theoretically be used by Rider (it is used when you execute `dotnet run` from the command line), and also the `<StartProgram>` property which is used by VS for Mac.  

If there's a way from the project file to specify what executable to use when debugging in Rider, then we can add something.  Otherwise you'll have to do it manually I guess.

**Comment by MelanieT** [comment]
The template does it wrong. With the hint from you, I was able to make it work. Error messages on the command line guided me to install the runtime separately, Rider installs it in a nonstandard location. After that, I got the same issue on the command line, but better error reporting led me to the run/debug configuration in Rider, which the template had set to attempt to directly execute the built DLL, rather than the mac executable bundle. Adjusting the path to run the exe within the app bundle solved it for me and I can now work with Eto. Thank you so much for the quick reply. The template should be changed to do the right thing, though, it's a real trap for adoption if the generated template doesn't even work. Rider doesn't allow to select the built executable because, unlike a native .net project, it doesn't end in .exe, so the path has to be manually entered, that, however, is a Rider bug.

**Comment by cwensley** [comment]
If there's something that can be done with the template, I'm all for it.  Investigating a little it looks like the template would have to add a Rider-specific `.run/MyApp.Mac.run.xml`, which really isn't ideal here as anyone _not_ using Rider would also get those superfluous files.  

It appears others have asked for RunCommand/RunArguments support [here](https://rider-support.jetbrains.com/hc/en-us/community/posts/360009847400-RunCommand-RunArguments-support), which would be the ideal solution, but unlikely given how old that request is.

**Comment by MelanieT** [comment]
To the extent of my knowledge, this is not about arguments. It's actually about the path to the executable, which is set to point to the "meat" of the app, which is compiled to a .dll. However, for the Mac wrapper to work correctly, the .exe file (which isn't suffixed .exe!) needs to be run. That is merely a variation of the path to be made in the MyApp.Mac/MyApp.Mac.csproj file, specifying the executable inside the Mac app bundle rather than the .dll. I don't know where these templates come from, nor do I know where their source is, and I never dealt with Rider templates, but since the MyApp.Mac.csproj is generated separate from the Gtk and Windows variants anyway, it doesn't seem like it would be ultra hard to do, for someone who knows their stuff. Instead of /redacted/net6.0/MyApp.dll, it needs to be /redacted/net6.0/MyApp.Mac.app/Contents/MacOS/MyApp.Mac. That's really all.

**Comment by cwensley** [comment]
I hear ya, but there's no way to tell rider to use that. It figures it out all on its own, and appears to not use the RunCommand (which points to the proper path) for console apps.  There's nothing in the eto templates that tells it to run the .dll.  I'll still investigate what can be done, but likely this will need the jetbrains folks to do something about it.

**Comment by MelanieT** [comment]
Well, if they ignore the heavy hint you drop, then I guess so. I simply experience them as not very responsive, look at low long the XAML previewer feature request has been stuck, 6 years or so, I think? May be the Eto github readme should simply state the need for mac users wanting to develop, rather than just compile, to change the setting. Easy when you know what do do, I was banging my head against the proverbial wall.

**Comment by cwensley** [comment]
Thanks for the suggestion.  The [quick start guide](https://github.com/picoe/Eto/wiki/Quick-Start#jetbrains-rider) does actually mention that already.

**Comment by MelanieT** [comment]
I see. It would be more clear if you moved that to the Mac section, e.g.

For JetBrainsRider, do ....

instead of having it in an obscure section at the bottom.

**Comment by cwensley** [comment]
Hmm... are we looking at the same thing?  that _is_ the Jetbrains Rider section..

<img width="906" alt="Screen Shot 2022-08-24 at 4 19 52 PM" src="https://user-images.githubusercontent.com/367446/186540237-5dc5d909-1351-4722-8d74-e0959b48184f.png">

**Comment by MelanieT** [comment]
Yes we are. I suggest to remove the section and rolling it into the Mac section. That suggestions comes from the fact that I read that doc exectly up to the end of the Mac section (I'm Mac only) and no further, the rest seeming to be Gtk. So it's better to place that info inside the Mac section, not at the very end, in an obscure clause most would never see.

Restructure, like

Mac

- Visual Studio
 .....

- Rider
 ---

**Comment by cwensley** [comment]
The Mac section? you mean Visual Studio for Mac?  That is different than Rider.  There are these sections:
- Visual Studio for Windows
- Visual Studio for Mac
- dotnet new (maybe rename to command line)
- Visual Studio Code
- JetBrains Rider

I don't think adding JetBrains Rider specific stuff to the Visual Studio for Mac section makes any sort of sense.

**Comment by MelanieT** [comment]
I updated my comment. The intent of my suggestion is to deemphasize VisualStudio as the premier development tool, regroup the document by platform and then IDE, rather than IDE/Platform, lesser used IDE/niche.
Visual Studio isn't the be all end all

**Comment by MelanieT** [comment]
To make this more clear:

- Windows
  - Visual Studio
  - VSCode
  - Rider
- Mac
  - Visual Studio
  - VSCode
  - Rider
 - Linux
   - VSCode
   - Rider
