### ISSUE TITLE
Disable autoscaling for last TableRow in TableLayout

### ISSUE THREAD

**Issue by kimimaru4000** [picoe/Eto#2292]
## Expected Behavior
I can't find a way to disable autoscaling for the last row in a `TableLayout`. I would like to do this to prevent an `ImageView` in a child horizontal `TableLayout` from being centered with the rest of the content and looking off.

## Actual Behavior
Image attached:
![Autoscaling Bottom](https://user-images.githubusercontent.com/1388037/186963948-ae22cffa-d501-4c7a-a572-53e1abadfe77.png)

Note how the last row at the bottom, with the Terminal icon, is not in line with its text ("XJVE[h@m") like the other rows are.

## Code that Demonstrates the Problem

ChatRowView.cs - Contains an `ImageView` and `Label` inside of a horizontal `TableLayout`.
```cs
public class ChatRowView : Panel
{
    public readonly ChatRowViewModel ViewModel = null;

    private ImageView ServiceImgView = null;
    private Label TextLabel = null;

    public ChatRowView(ChatRowViewModel viewModel)
    {
        ViewModel = viewModel;

        ServiceImgView = new ImageView()
        {
            Image = viewModel.ServiceImage,
            Size = viewModel.ImageSize
        };

        TextLabel = new Label()
        {
            Text = viewModel.MessageText,
            TextColor = viewModel.TextColor,
            TextAlignment = viewModel.TextAlignment,
            Wrap = WrapMode.Word,
        };

        TableCell imgCell = new TableCell(ServiceImgView);
        imgCell.ScaleWidth = false;
        
        TableCell labelCell = new TableCell(TextLabel);
        labelCell.ScaleWidth = false;

        TableLayout tableLayout = TableLayout.Horizontal(10, imgCell, labelCell);

        Content = tableLayout;
    }
}
```

ChatDisplayView.cs - Contains a `Scrollable`, which has a vertical `TableLayout` as its content. The `TableLayout` contains ChatRowViews.
```cs
public class ChatDisplayView : Panel
{
    private readonly List<ChatRowView> ChatRows = new List<ChatRowView>();

    public ChatDisplayView()
    {
        RebuildView();
    }

    private void RebuildView()
    {
        TableRow[] tableRows = ChatRows
            .Select(cr =>
            {
                TableRow tableRow = new TableRow(cr);
                tableRow.ScaleHeight = false;

                return tableRow;
            })
            .ToArray();

        TableLayout scrollableContent = new TableLayout(tableRows);
        scrollableContent.Spacing = new Size(0, 3);

        Content = new Scrollable()
        {
            BackgroundColor = Colors.Black,
            Border = BorderType.Line,
            Content = scrollableContent
        };
    }

    public void AddChatRow(ChatRowView chatRowView)
    {
        ChatRows.Add(chatRowView);
        
        RebuildView();
    }
}
```

`ScaleWidth` and `ScaleHeight` is set to false for every cell and row I see possible, so I'm wondering if there's something I'm missing.

Please let me know if you need more code or information.

Thanks in advance!

## Specifications

  - Version: 2.7.1
  - Platform(s): Gtk3
  - Operating System(s): Linux Mint 20.3

**Comment by cwensley** [comment]
Hey @kimimaru4000, 

In Eto, the TableLayout will always expand its children to the extents of the container.  The last row/column will be expanded if none have ScaleWidth or ScaleHeight set to true.  

To allow for extra space, you can add a blank row at the bottom.

**Comment by kimimaru4000** [comment]
Awesome, thank you so much! This solves it!
