### ISSUE TITLE
Wpf crashes on Windows 7

### ISSUE THREAD

**Issue by hamarb123** [picoe/Eto#2295]
## Expected Behavior
App runs and works on Windows 7.

## Actual Behavior
App crashes on Windows 7 (Wpf).

## Stack trace
![image](https://user-images.githubusercontent.com/25316035/187064489-752598f8-c92f-4fbe-a4be-fc03c4d7a5b8.png)

## Cause
The issue is that some apis, like this one, aren't supported on older versions of Windows, I'm happy to go through the code, find these, and guard them.

## Specifications

  - Version: 2.7.1 (was using 2.6.0 previously, edit: it seems to be fine in 2.7.0)
  - Platform(s): WPF
  - Operating System(s): Windows 7

**Comment by cwensley** [comment]
Hm, I don't support Windows 7 as neither has MS (since January 2020).  However I will accept any fixes. 😄

**Comment by hamarb123** [comment]
Fair enough, I would like to say that both .NET 6 and .NET framework 4.8 do support Win 7 though, although the upcoming newer versions will not 'support' it (but .NET 7 will not go out of their way to break on it). So I think was a reasonable assumption that it would support Windows 7, but I'm more than happy to fix any issues I encounter until I decide to not support Windows 7 anymore lol.
