### ISSUE TITLE
How to add form-menu item dynamically ? 

### ISSUE THREAD

**Issue by PrestigeDevop** [picoe/Eto#2296]
## Expected Behavior
(instantiate a new form / adding menu item dynamically  during runtime  )

## Actual Behavior
```System.InvalidOperationException: 'Platform instance is null. Have you created your application?'```

## Steps to Reproduce the Problem

  1. clone this project [photino.net](https://github.com/tryphotino/photino.Blazor)
  2. add Nuget package references (Eto.forms)
  3. in HelloWorld Sample add necessary namespace and inherit the prgroam from  'form' code base library .
  4. add a button which call  instantiate a new form - add menu item dynamically  
  

## Code that Demonstrates the Problem

```

namespace forms
{
	public partial class MainForm : Form
	{
		public MainForm()
		{
			Title = "My Eto Form";
			MinimumSize = new Size(200, 200);

			Content = new StackLayout
			{
				Padding = 10,
				Items =
				{
					"Hello World!",
					// add more controls here
				}
			};

			// create a few commands that can be used for the menu and toolbar
			var clickMe = new Command { MenuText = "Click Me!", ToolBarText = "Click Me!" };
			clickMe.Executed += (sender, e) => MessageBox.Show(this, "I was clicked!");

			var quitCommand = new Command { MenuText = "Quit", Shortcut = Application.Instance.CommonModifier | Keys.Q };
			quitCommand.Executed += (sender, e) => Application.Instance.Quit();

			var aboutCommand = new Command { MenuText = "About..." };
			aboutCommand.Executed += (sender, e) => new AboutDialog().ShowDialog(this);

			// create menu
			Menu = new MenuBar
			{
				Items =
				{
					// File submenu
					new SubMenuItem { Text = "&File", Items = { clickMe } },
					// new SubMenuItem { Text = "&Edit", Items = { /* commands/items */ } },
					// new SubMenuItem { Text = "&View", Items = { /* commands/items */ } },
				},
				ApplicationItems =
				{
					// application (OS X) or file menu (others)
					new ButtonMenuItem { Text = "&Preferences..." },
				},
				QuitItem = quitCommand,
				AboutItem = aboutCommand
			};

			// create toolbar
			ToolBar = new ToolBar { Items = { clickMe } };
		}
	}
```

## Specifications

  - Version:Eto.forms 2.7.1
  - Platform(s): Microsoft.netcoreapp
  - Operating System(s): Windows 11Pro,

**Comment by cwensley** [comment]
The exception is because you have not created an Application class.  To start an Eto.Forms app you need something like:

```
var app = new Application(Platform.Detect);  // you're missing this.
var form = new MainForm();
app.Run(form);
```

If you are running this from an existing application with its own message loop, you can use `app.Attach()` instead of `app.Run(form)`.

Hope this helps.

**Comment by cwensley** [comment]
Hi @PrestigeDevop, thanks again for reporting the issue.

I'm closing this as I believe this was answered and is not a problem with Eto directly.  If you feel that there is some sort of issue wth Eto, please provide a more directly usable example of what isn't working and I'll take a look.  Perhaps create a branch of the code that isn't working so I can at least see what you have done.

Cheers!
