### ISSUE TITLE
Align ImageView to top of horizontal TableLayout

### ISSUE THREAD

**Issue by kimimaru4000** [picoe/Eto#2313]
## Expected Behavior

I have a horizontal `TableLayout` with an image followed by text. I want the image to be top-aligned so it's clear which image belongs to which piece of text. This is mainly an issue for multi-line text. See the attached image:

![IconVerticalCenter](https://user-images.githubusercontent.com/1388037/190849823-d73fe736-96a4-4a19-bb07-d876f8b79f41.png)

In the above picture, I want the image to be at the start  of the string, where the "O7B`" part is.

## Actual Behavior

The element is always center aligned vertically in the TableLayout.

## Steps to Reproduce the Problem

  1. Create `TableLayout.Horizontal` with two elements: an `ImageView` and a `Label` with text consisting of multiple lines.
  2. Place this horizontal `TableLayout` in a vertical `TableLayout`.
  3. Observe that the `ImageView` is vertically centered with the `Label`. Settings on the `ImageView` don't seem to have any effect on its vertical alignment.

## Code that Demonstrates the Problem

- [`ChatRowView` has the horizontal table layout](https://codeberg.org/kimimaru/TRBotChatDisplay/src/commit/9fe02efd0dabde58062b7aabf88c37ad11c0ad45/TRBotChatDisplay/TRBotChatDisplay/ChatRowView.cs#L48) - this consists of the `ImageView` and the `Label` mentioned.
- Each `ChatRowView` is added to a [vertical `TableLayout`](https://codeberg.org/kimimaru/TRBotChatDisplay/src/branch/main/TRBotChatDisplay/TRBotChatDisplay/ChatDisplayView.cs#L70), which is inside a `Scrollable`.

## Specifications

  - Version: 2.7.1
  - Platform(s): Gtk3 
  - Operating System(s): EndeavourOS (KDE Plasma 5.25.5), Linux Mint 20.3

**Comment by cwensley** [comment]
Try `TableLayout.Horizontal(10, new TableLayout(ServiceImgView, null), TextLabel);`

**Comment by kimimaru4000** [comment]
Thank you; that did the trick!

Can you explain how this is working? I'm used to toolkits that allow specifying anchors, alignment, and etc directly. For example, what if I want the icon bottom-aligned in the future?

**Comment by cwensley** [comment]
In Eto, the containers determine where controls go.  Controls themselves only supply the desired size.

If you want it bottom aligned, just move the null before the `ServiceImgView`.  null is a shortcut for `new TableRow { ScaleHeight = True }`

**Comment by kimimaru4000** [comment]
Thanks for the clarification. I'll close this issue since it's now resolved. I appreciate the help!
