### ISSUE TITLE
RichText-like Label

### ISSUE THREAD

**Issue by kimimaru4000** [picoe/Eto#2322]
## Task
I'm looking for a way to color individual parts of text. The text contains a username, a separator, and message components.

The following picture from ChatGameFontificator demonstrates what I'm looking for:
![ChatGameFontificator](https://user-images.githubusercontent.com/1388037/192356779-4a11f53f-3e72-43f7-8d9d-a50dc4798c1c.png)

In particular, notice how the text wraps around like it's one piece. Having two separate labels like this in Eto is not possible (correct me if I'm wrong).

## Problem
I can't find an equivalent in Eto:

- `RichTextArea` doesn't support RTF on GTK and comes with scrollbars that I can't find a way to remove.
- Putting two separate labels in a container doesn't allow the text to act like one piece, as one label will make sure not to overlap with the other.
- I'm unsure if a custom control can be defined to either piece two labels together like this (preferred) or if I have to write an entirely custom label component to color parts of text separately.
  - If the latter is possible, I would like some guidance on how to achieve this since the documentation on custom components is scarce.

## Specifications

  - Version: 2.7.1
  - Platform(s): Gtk3
  - Operating System(s): EndeavourOS

**Comment by cwensley** [comment]
Hey @kimimaru4000, thanks for submitting the issue!

Eto doesn't support something like this directly other than using a `Drawable` and painting the parts manually. 

Fortunately there's also the [Eto.HtmlRenderer](https://www.nuget.org/packages/Eto.HtmlRenderer) control which you can feed it HTML and it will render it out however you like, giving you pretty much any flexibility you'd ever need.

**Comment by kimimaru4000** [comment]
For the time being, I decided to use a different design and will look into a custom control down the road. The HtmlRenderer is nice but unfortunately reports memory leaks in the console and has some interesting aliasing going on with Scrollables. Thanks a bunch for the help!
