### ISSUE TITLE
GTK and WinForms Label with WrapMode.None should not enable SingleLineMode

### ISSUE THREAD

**Issue by LeeARichardson** [picoe/Eto#2326]
Hi,
On GTK and WinForms, but not WPF (I can't check Mac) setting a Label to WrapMode.None also enables single line mode. There's no way to disable wrap but still allow multiple lines.
This is in contradiction to the documentation which states "Regardless of the mode, you can always add hard wraps by inserting newline characters."
https://github.com/picoe/Eto/blob/86f8ba20544b11447f30794718f3170ca971a726/src/Eto/Forms/Controls/Label.cs#L30
https://github.com/picoe/Eto/blob/86f8ba20544b11447f30794718f3170ca971a726/src/Eto.Gtk/Forms/Controls/LabelHandler.cs#L155
https://github.com/picoe/Eto/blob/86f8ba20544b11447f30794718f3170ca971a726/src/Eto.WinForms/Forms/Controls/LabelHandler.cs#L198

## Expected Behavior
Label with WrapMode.None should not restrict the text to a single line.

## Actual Behavior
Text with new lines is all shown on the same line due to the SingleLineMode being enabled.

## Steps to Reproduce the Problem

1. Set a Label's Wrap to WrapMode.None .

## Code that Demonstrates the Problem
```fsharp
let label = new Label()
label.Wrap <- WrapMode.None
```

## Specifications

  - Version: 2.7.1
  - Platform(s): Gtk3, WinForms
  - Operating System(s): Windows 10, Linux

**Comment by cwensley** [comment]
Fixed with #2327
