### ISSUE TITLE
Restrict Scrollable to scrolling only vertically

### ISSUE THREAD

**Issue by kimimaru4000** [picoe/Eto#2331]
## Expected Behavior
I would like a Scrollable to be clamped horizontally but not vertically. It seems like there's no way to do this from looking at the API. I'm writing an application that displays a chat and would like the Scrollable to work like a typical chat box.

**If you want an immediate example for the behavior I'm looking for**:
1. Write a lot of text as a comment on this issue, but don't submit it.
2. Resize your browser window, decreasing it's with. Observe how the textbox still scrolls vertically but the wraps the text horizontally. 

## Actual Behavior
See the screenshot below:

![IconScrollableNotClamped](https://user-images.githubusercontent.com/1388037/194766811-5c144338-12f1-40e0-b87d-a73cd6fcfc04.png)

Observe how the content is not clamped and the Scrollable displays a horizontal bar allowing one to see more.

I would like the content to be clamped to the horizontal size of the Scrollable so it wraps around if it doesn't fit. I would still like it to scroll vertically to see more entries.

## Steps to Reproduce the Problem

  1. Create a Scrollable.
  2. Fill it with wide content.
  3. Observe that the content continues horizontally past the bounds of the scrollable instead of wrapping.

## Code that Demonstrates the Problem

- Scrollable init is [here](https://codeberg.org/kimimaru/TRBotChatDisplay/src/commit/35d6cb78803faa5da13417a5a26acb30bd882448/TRBotChatDisplay/TRBotChatDisplay/ChatDisplayView.cs#L49).
- Code for populating the Scrollable content is [here](https://codeberg.org/kimimaru/TRBotChatDisplay/src/commit/35d6cb78803faa5da13417a5a26acb30bd882448/TRBotChatDisplay/TRBotChatDisplay/ChatDisplayView.cs#L186).
- ChatRowView code is [here](https://codeberg.org/kimimaru/TRBotChatDisplay/src/commit/35d6cb78803faa5da13417a5a26acb30bd882448/TRBotChatDisplay/TRBotChatDisplay/ChatRowView.cs#L51).

## Specifications

  - Version: Eto.Forms 2.7.1
  - Platform(s): Gtk3
  - Operating System(s): EndeavourOS (Arch Linux)

**Comment by cwensley** [comment]
The way you'd do this is to set the width of the scrollable content to the minimum size you want before it starts scrolling.. e.g. setting to 1 would cause it to never scroll.  Setting `Scrollable.ExpandContentWidth` to true (the default) will ensure it takes up the entire width of the client area of the scrollable even though you set its width.

**Comment by cwensley** [comment]
Closing as this is answered.  Please let me know if the above does not work for you.
