### ISSUE TITLE
Eto.Platform.Windows not supporting fx461

### ISSUE THREAD

**Issue by Beyley** [picoe/Eto#2353]
## Expected Behavior
Eto.Platform.Windows should be available on all frameworks that net standard 2 is available on (fx461+ and coreapp3.1+)

## Actual Behavior
Eto.Platform.Windows is only available on fx462+ and coreapp3.1+

## Steps to Reproduce the Problem

  1. Make fx461 app
  2. Import through nuget
  3. Try to build

## Specifications

  - Version: 2.7.2
  - Platform(s): WinForms
  - Operating System(s): Windows 10
  
Unless there is a specific reason fx461 cant be supported, it should work under fx461, same with the rest of the Eto nugets (which are netstandard2), it should be as simple as bumping the framework version from fx462 -> fx461

**Comment by cwensley** [comment]
Sorry, but .NET 4.6.1 is end of life, so it is not supported: https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/
