### ISSUE TITLE
GTK DropDown adds a lot of blank space above items if opened height is tall

### ISSUE THREAD

**Issue by metalmachine76** [picoe/Eto#2360]
I have a dropdown with several items in it. When the dropdown is opened, if the bottom of the opened dropdown would extend below the bottom of the screen, the dropdown will have a bunch of blank space added above the items for some reason. 

## Expected Behavior

The dropdown should not have blank space added above the items.

## Actual Behavior

The dropdown is adding a lot of blank space above the items.

## Steps to Reproduce the Problem

  1. Add a dropdown to a form. 
  2. Place several items (in my case, I have a dropdown with 22 items) in it,
  3. Run the application.
  4. Place the form near the bottom of the screen, such that the dropdown is also near the bottom of the screen, such that the bottom of the dropdown would extend below the bottom of the screen if it were opened. 
  5. Open the dropdown.

## Specifications

  - Version: 2.7.2
  - Platform(s): Gtk
  - Operating System(s): Windows 11, Ubuntu 22.x

## Screenshots

Before opening:
![dropdownpic1](https://user-images.githubusercontent.com/31862889/205468248-040ddbe4-755a-4659-bbee-ca9b584c2116.png)

Just after opening:
![dropdownpic2](https://user-images.githubusercontent.com/31862889/205468249-cea06729-2279-4347-a45e-bde153e77ecc.png)

After opening and scrolling down, the problem fixes itself:
![dropdownpic3](https://user-images.githubusercontent.com/31862889/205468250-9ef9b518-a795-4fff-abd8-73ef10a72b94.png)

**Comment by harry-cpp** [comment]
That is just how gtk is, its surprisingly not a bug :D

**Comment by metalmachine76** [comment]
I can accept the problem originates from GTK behavior, but I'm not going to agree that it's not a bug. It only happens in specific scenarios, it's behavior that runs contrary to UI norms, and it's a degraded user experience. Perhaps you're saying it's not a bug in Eto since Eto is just wrapping GTK, but any bugs in library code a product uses becomes a product bug, if that feature is exposed or used in said product. I mean, if I'm using, say, Chrome, and suppose Chrome uses a third party library for scrollbars (I don't know if it does, this is just an example) and the scrollbar glitches out, that's a bug in Chrome from my perspective as the user of Chrome. 

Anyway, perhaps there is a programmatic way to address the issue when the control is instantiated or displayed, etc. I don't know the best solution, I'm just reporting the issue.

**Comment by harry-cpp** [comment]
This is not a bug, this is just how GTK behaves (and has for the past 10 years at least). If you want it changed you are gonna have to open up an issue on the upstream GTK issue tracker.

There is also no way to correct this behaviour externally, the GTK library itself would need to be modified.

ping @cwensley

**Comment by cwensley** [comment]
Hey @metalmachine76, thanks for reporting the issue but I agree with @harry-cpp in that this is actually not a bug.  Gtk puts the selected item right where the DropDown is located by design.  Say for example you had "Hint" selected, then it will appear under your mouse after you click the drop down.  You can also follow along and chime in with [this gtk bug report](https://gitlab.gnome.org/GNOME/gtk/-/issues/270), which appears to have originally been opened in 2006.

There is unfortunately nothing we can do on our part to change how Gtk behaves in this regard.

**Comment by metalmachine76** [comment]
Fair enough. Thanks for linking the gtk bug. I can understand their desire to place the selected item where your mouse is, but their solution of putting all that blank space seems a very strange choice to me.

**Comment by cwensley** [comment]
Agreed that it is strange, it took some getting used to on my part as well.  However it will likely feel natural to anyone that is used to software built with Gtk.
