### ISSUE TITLE
Incorrect F# templates

### ISSUE THREAD

**Issue by somelinguist** [picoe/Eto#2370]
A couple of the F# app templates for Eto.Forms apps appear to have problems:

The MacOS template for F# doesn't include an item to compile the included `Program.fs` file.
https://github.com/picoe/Eto/blob/develop/src/Eto.Forms.Templates/content/App-FSharp/Separate/EtoApp.1.MacOS/EtoApp.1.MacOS.fsproj

The WPF template for F# contains a C# project, not an F# project:
https://github.com/picoe/Eto/tree/develop/src/Eto.Forms.Templates/content/App-FSharp/Separate/EtoApp.1.Wpf

I looked through the other project templates in the F# folder and didn't see any similar issues.

**Comment by cwensley** [comment]
WPF doesn't support F# (last I checked.. maybe that has changed?), thus is why it is in C#.  All of your Eto UI would still be in F# though.  As for the other issue it should be an easy fix.  

Thanks for the issue report!

**Comment by somelinguist** [comment]
Thanks for the info! 

Is WPF not supporting F# a recent thing? I remember having an old .net5 F# project with Eto.Forms that had a WPF target.

Interestingly, now that I went to run it, Windows complains I need to install .NET but won't actually install the needed version? It was a hobby project that I haven't worked on in over a year (and since abandoned), but I do remember it working at the time.

Not a big deal since the rest can still be in F#, I'm just curious. :)

**Comment by cwensley** [comment]
While you _can_ have an F# project that runs WPF, you can't use any xaml as that's not wired up last I checked.. the reason you'd have a WPF-specific project is so you can create custom WPF styles that would work with your project.

**Comment by somelinguist** [comment]
Thanks. That makes sense!
