### ISSUE TITLE
Loading local resources (JS, CSS, images) in WebView doesn't work on Mac when calling LoadHtml()

### ISSUE THREAD

**Issue by somelinguist** [picoe/Eto#2380]
_Originally posted by @somelinguist in https://github.com/picoe/Eto/discussions/2379#discussioncomment-4709766_
          

This is an issue with WkWebView's security. If you search for trying to load local resources with webview.LoadHtmlString(), there are tons of results (for, example https://developer.apple.com/forums/thread/126095?answerId=395382022#395382022). 

Basically, with WkWebView, you have to give it read access to the directory the resources are in, which you can do by calling `webview.LoadFileUrl`. 

The first parameter is a uri that must exist, and the second is the uri that file/directory at the first uri should have access too. I've found that calling it with both parameters set to the same thing works. After calling something like `webview.LoadFileUrl(baseURI, baseURI)`, subsequent calls to `webview.LoadHtmlString(html, baseURI)` should work.

Changing the the the Mac handler's LoadHtml() from this

https://github.com/picoe/Eto/blob/d51ed9c561800b444403f1fe7f307885a9dc7e93/src/Eto.Mac/Forms/Controls/WKWebViewHandler.cs#L291-L294

to something like the following should work:

```csharp
                public void LoadHtml(string html, Uri baseUri)
		{
			Control.LoadFileUrl(baseUri.ToNS(), baseUri.ToNS());
                        Control.LoadHtmlString(html, baseUri.ToNS());
		}
```

I didn't have the time to build Eto to test it, and I couldn't override LoadHtml() since it wasn't virtual, but calling `Control.LoadFileUrl(baseUri.ToNS(), baseUri.ToNS());` in a custom Mac handler's overridden `Initialize()` where baseUri was the same in later calls to LoadHtml() did work. (I hope that makes sense).

Another thing to note is that the baseURI on Mac must have a trailing `/`, otherwise the last element seems to get cut off .

I've tested it with setting the baseUri to `Eto.EtoEnvironment.GetFolderPath(Eto.EtoSpecialFolder.ApplicationResources)` with "/wwwroot/" appended. It then works on Mac, and I tested to make sure it didn't break the Wpf target as well.

**Comment by cwensley** [comment]
Hey @somelinguist, thanks for taking the time to figure out why this wasn't working and propose a fix!  Your explanation is quite detailed and clear so it should be easy enough to test this out and create a PR.

**Comment by somelinguist** [comment]
Thanks for the update! Glad I could help.
