### ISSUE TITLE
Building Platforms.macOS results in .app file not being placed in output directory

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2386]
## Expected Behavior
If I pass an output directory to the compile command via `dotnet publish -o foobar`, the resulting .app file should be placed into the directory that was passed (in this case `foobar`).

## Actual Behavior
The .app file gets placed into `{project dir}/bin/{configuration}/{RID}` (i.e. `MyProject/bin/Release/net6.0-macos`)

## Steps to Reproduce the Problem

  1. Compile an Platforms.macOS project

## Specifications

  - Version: 2.7.3
  - Platform(s): macOS
  - Operating System(s): M1 macOS Ventura

**Comment by cwensley** [comment]
This is unfortunately not something that Eto is doing.  You may need to file this issue in the [xamarin-macios](https://github.com/xamarin/xamarin-macios) repo.   E.g. the following puts the .pkg in the output folder, but not the .app bundle:

```
mkdir MyApp
cd MyApp
dotnet new macos
dotnet publish -o foobar
```

**Comment by Miepee** [comment]
Gotcha, then I'll close this as invalid.
