### ISSUE TITLE
[GTK] themed tabcontrol are always at left

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2410]
## Expected Behavior
Tabs should be where the dropdown says where they should be

## Actual Behavior
They're always on the left  
![image](https://user-images.githubusercontent.com/38186597/219117685-4335650b-37f7-449f-acfb-82a2d657edc8.png)

## Steps to Reproduce the Problem

  1. Open TabControl themed test on Eto.Test
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
The themed tab control section is just a test of the theming, it is not meant to be a full implementation of the tab control itself.  Thanks for reporting the issue, however!
