### ISSUE TITLE
[GTK] LinkButtons look like labels

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2412]
## Expected Behavior
They should look like buttons

## Actual Behavior
They look like labels  
![grafik](https://user-images.githubusercontent.com/38186597/219462735-ed37cff5-355e-4099-bb49-9a1c91372fea.png)

## Steps to Reproduce the Problem

  1. Open linkbuttons test in eto.test
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
This uses a standard GTK LinkButton control.  It will adopt whatever style is applied for the theme you are using.
