### ISSUE TITLE
[GTK] gridviews adjust themselves after being generated

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2414]
## Expected Behavior
Gridviews should just stay as is

## Actual Behavior
They adjust themselves for ~1.5seconds

## Steps to Reproduce the Problem

  1. Open the gridview test on eto.test
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
This is default behaviour of a grid on GTK when columns are auto sized, it scans all rows to detect the size of the columns whereas other platforms will adjust the size as you scroll.
