### ISSUE TITLE
[GTK] reoderable documentcontrollers look slightly weird

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2416]
## Expected Behavior
Should still look like some sort of tab with the header

## Actual Behavior
Looks less like a tab.

With reorderable enabled:
![grafik](https://user-images.githubusercontent.com/38186597/219466135-6ccf0219-0efb-4e58-8796-251be5af3095.png)

Disabled:  
![grafik](https://user-images.githubusercontent.com/38186597/219466172-2d0bdd42-ad24-4c19-8191-ab08dec858d4.png)

## Steps to Reproduce the Problem

  1. Open documentcontroller test on eto.forms
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
This uses the Gtk Notebook control and its look is up to the gtk theme.  There's nothing for us to do in Eto here.  I'm open to suggestions if there's some sort of property in the gtk control we can set to change this.

**Comment by Miepee** [comment]
Double checked this on Adwaita, looks much better there, so I'll report this to Breeze designers instead.
for anyone curious:
enabled 
![grafik](https://user-images.githubusercontent.com/38186597/225024042-3dca4e2d-94bb-497a-90f2-14b804453a6b.png)

disabled
![grafik](https://user-images.githubusercontent.com/38186597/225024113-dffe31a8-d16e-413e-a0d6-df1e2fd73105.png)
