### ISSUE TITLE
[GTK] inconsistent checkbox look

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2417]
## Expected Behavior
All disabled checkboxes should be consistent

## Actual Behavior
They look different:
![grafik](https://user-images.githubusercontent.com/38186597/219466803-ecfe4418-93d1-4a88-9168-1bb5e97cf4c1.png)

## Steps to Reproduce the Problem

  1. Open Windows test on eto.test
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
The look of the checkbox on GTK is up to the GTK theme.  There isn't anything in Eto specifying the look, it simply uses a CheckButton control.

**Comment by Miepee** [comment]
~~How is it then that there are *two* looks for a disabled state?~~

NVM I'm dumb - the ones who have two looks are due to having threestate enabled.
