### ISSUE TITLE
[GTK] Creating windows at screen corners test doesn't work

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2420]
## Expected Behavior
Windows should be created at the screen corners

## Actual Behavior
They all get spawned in at the middle. Potentially a wayland limitation

## Steps to Reproduce the Problem

  1. Open the corresponding test on eto.test
## Specifications

  - Version:2.7.2
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
Yes, as far as I understand Wayland, you do not have control over the location of any window.  which is insane.  but unfortunately the truth right now.  If ever Wayland gets this feature, I would expect the appropriate GTK APIs to be "lit up" and just start working, so this is not an Eto issue but an upstream issue.

**Comment by Miepee** [comment]
Ah right, I forgot that wayland doesn't allow this due to security measures. Closing as invalid then.
