### ISSUE TITLE
[GTK] isprimary check always saying false.

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2421]
## Expected Behavior
It should say that my primary screen is the primary

## Actual Behavior
All screens say they're not the primary window. shouldnt be a wayland issue, as wayland (now) does support a primary screen

## Steps to Reproduce the Problem

  1. Open Screen test on eto.test
## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
This simply calls GTK's `Gdk.Monitor.IsPrimary` API [here](https://github.com/cwensley/Eto/blob/develop/src/Eto.Gtk/Forms/ScreenHandler.gtk3.cs#L26) so this isn't an Eto issue.

**Comment by Miepee** [comment]
Since it's an upstream issue then, I'll close this as invalid.
