### ISSUE TITLE
[GTK] OpenFileDialog not working 

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2444]
## Expected Behavior

Calling OpenFileDialog.ShowDialog() after pressing the "Open" button returns `Ok`.

## Actual Behavior

Calling OpenFileDialog.ShowDialog() after pressing the "Open" button returns `Ignore`.

Returned 2.7.2 - ShowDialog() returns `Ok` as before.

## Specifications

  - Version: 2.7.3
  - Platform(s): Gtk
  - Operating System(s): Linux Mint

**Comment by cwensley** [comment]
Hey @Serg-Norseman, thanks for reporting the issue!

This should be fixed in 2.7.4 with #2381

**Comment by Serg-Norseman** [comment]
👍
