### ISSUE TITLE
Dropdown analogue for arbitrary content of the popup part

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2464]
Please advise.

Is it possible using only Eto.Forms (top level, without native handlers for each platform) to develop a control that could provide dropdown / popup extensions for an arbitrary other component (for example, for TextBox or MaskedTextBox)? That is, something like DateTimePicker or DropDown/ComboBox, but not for dates and not for a list.

That is, take for example a TextBox and add a button to it like a ComboBox, plus a Popup container for an arbitrary Layout with other controls inside.

If this is not possible at the top level, then please tell me - in which control there is already a similar functionality so that I can make my own on this basis?

**Comment by cwensley** [comment]
Hey @Serg-Norseman, thanks for the question.  Yes, you can create a borderless non-activating Form in the appropriate location to host whatever content you need.

**Comment by Serg-Norseman** [comment]
"borderless" - I understand
"non-activating" - How is that? I do not understand or know under some other name

**Comment by Serg-Norseman** [comment]
Is it the "Show Activated" flag in the TestApplication/Windows section?

**Comment by Serg-Norseman** [comment]
Thank you, in general terms, I understood how to solve the problem :)
