### ISSUE TITLE
Invalidating a TreeGridView fails to update it on Mac but works on WPF and GTK

### ISSUE THREAD

**Issue by jonko0493** [picoe/Eto#2473]
## Expected Behavior
After modifying the text of an item in a `TreeGridView`, calling `Invalidate()` will redraw the control so the new text will be visible.

## Actual Behavior
This happens on WPF and GTK but not on Mac.

## Steps to Reproduce the Problem

  1. Clone https://github.com/jonko0493/TreeGridViewMinRepo
  2. Run the application on Windows or Linux.
  3. Select one of the Hellos or Worlds and press F2 (or select Rename from the File menu). Observe that the text of that item changes.
  4. Run the application on macOS.
  5. Select one of the Hellos or Worlds and press F2 (or select Rename from the File menu). Observe that the text does not change.
  6. Collapse and then re-expand the category of the item you just changed. Observe that the text has now changed.

## Code that Demonstrates the Problem
https://github.com/jonko0493/TreeGridViewMinRepo

But the important part is:

```cs
treeGridView.SelectedItem.Text = "New Text";
treeGridView.Control.Invalidate();
```

## Specifications

  - Version: 2.7.5
  - Platform(s): Affected platform: Mac64. Other platforms tested on: Wpf, Gtk
  - Operating System(s): Intel Mac running macOS 12.3. Windows 11, Ubuntu 22.04

**Comment by cwensley** [comment]
Hi @jonko0493, thanks for reporting the issue!

While `Invalidate()` may work on some platforms, you should be using `ReloadData()` or `ReloadItem()` instead to tell the TreeGridView which item(s) have changed.

Hope this helps!

**Comment by jonko0493** [comment]
That seems to work perfectly! Thanks so much for the help!
