### ISSUE TITLE
CollectionEditor does not have a test suite

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2484]
## Expected Behaviorss
There should be a section in Eto.Test to test functionality of the CollectionEditor control. If it is obsolete, it should be marked as such.

## Actual Behavior
No such section or clarification exists.

## Specifications

  - Version: 82b5ea586f7d281267abe785bf45591c8c764911
  - Platform(s): Gtk
  - Operating System(s): Arch Linux

**Comment by cwensley** [comment]
The CollectionEditor is tested in the PropertyGrid section.

**Comment by Miepee** [comment]
Is it? CTRL+F'ing through PropertyGrid.cs doesnt reveal anything to me by quick glance.

**Comment by cwensley** [comment]
No, but the PropertyGrid itself uses it when editing a collection.  Try searching through ThemedPropertyGridHandler.cs.
