### ISSUE TITLE
List component with complex items

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2487]
I need a list component (WinForms ListBox handled it in the past) with items that can be displayed with formatting and in multiple lines.

Please advise: what component or combination of ways can implement this now in Eto.Forms?

ListBox doesn't currently have item custom rendering functionality, so it's not entirely clear which way to go...

**Comment by cwensley** [comment]
GridView with a CustomCell is your best bet there.

**Comment by Serg-Norseman** [comment]
An unexpected choice. 
And the header of GridView after all is not switched off?

**Comment by cwensley** [comment]
Why unexpected?  It's a more flexible version of a ListBox 😄.  Yes the header can be hidden.

**Comment by Serg-Norseman** [comment]
I will try. Thank you :)
