### ISSUE TITLE
Custom Controls ?

### ISSUE THREAD

**Issue by RetroAndDev** [picoe/Eto#2556]
This is a question about how, and it is possible to make custom control who render the same on all platform ?
Like in WinForm or WFP it knows as user-control. Did there is a possibility to make custom controls with custom shapes, colours, rounded corner and other ?

## Specifications

  - Version:
  - Operating System(s): Work on macOS 14 Sonoma, and target macOS, Windows and Linux

**Comment by cwensley** [comment]
Yes, use `Drawable`, it has an `OnPaint` event you can override to paint whatever shapes/etc you like, can optionally get focus, receive keyboard input, etc.

**Comment by RetroAndDev** [comment]
Nice !
Do you have an simple exemple of a button ? Or an image with rounded corner ?

**Comment by cwensley** [comment]
Sorry for the late response, but yeah I do!  Check out the CustomButton/ImageButton implementation [here](https://github.com/cwensley/pablodraw/blob/main/Source/Pablo/Controls/ImageButton.cs).

Hope this helps.  Closing the issue as resolved.
