### ISSUE TITLE
Clipboard / Pasteboard Manager

### ISSUE THREAD

**Issue by adrnsoh** [picoe/Eto#256]
Hi,

Embedding Eto forms into an iOS app, would System.Windows still work?

I'm trying to use copy/paste from a PCL library.

**Comment by cwensley** [comment]
System.Windows is a windows-only namespace, so no it won't work.  Eto.Forms is an abstraction overtop the native toolkits, with its own implementation. So, have to use the Eto.Forms controls and functionality from the Eto.Forms namespace.  

There is an existing [Clipboard](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/Clipboard.cs) object, but it is not yet implemented for iOS.  However, this is not an overly onerous task if you need this functionality.
