### ISSUE TITLE
Sharing an executable version of Eto.Test

### ISSUE THREAD

**Issue by corbane** [picoe/Eto#2577]
Hello, 

## Expected Behavior

I'm trying to learn Eto.
For this I tried to see the available components using Eto.Test.
It would be very helpful to find the Eto.Test executable file in the Releases sections.

## Actual Behavior

Currently you need to download all the source code and compile it on your system although our goal is to use Eto.Forms via Nuget.
I have a lot of compilation problems and I can't use Eto.Test.
I just want to see the controls available for use in Rhino3d.

**Comment by Miepee** [comment]
The CI builds test versions for each commit to my knowledge
i.e. https://github.com/picoe/Eto/actions/runs/6789640563 the test asset here.

**Comment by corbane** [comment]
Thank you @Miepee 
It's exactly that !
kmv
