### ISSUE TITLE
Info.plist structure for MonoMac/XamMac (Tutorial?)

### ISSUE THREAD

**Issue by YvesSchelpeKdG** [picoe/Eto#261]
When building and debugging in Xamarin Studio/MonoDevelop using Eto.Forms and Eto.Forms.Mac in the use case with new Application().Run(Eto.Form).

Users should be adviced that when the application starts & then suddenly shuts down without having showed any UI they should check their Info.plist file for the entry "<key>NSMainNibFile</key><string>MainMenu</string>". They should change it to "<key>NSMainNibFile</key><string></string>" and then the application will start up.

When debugging one can see in the console output that Eto generates an exception. Eto.Exception: "Platform instance is null. Have you created your application?" The stack trace then points to the Main method, but without any indication or hint that the Info.plist was the issue.

Refer to this entry in the google groups: [ https://groups.google.com/forum/#!topic/eto-forms/jjWMisBJWKc ].

**Comment by cwensley** [comment]
Check this [wiki page](https://github.com/picoe/Eto/wiki/Running-&-Debugging-a-Mac-application-in-Xamarin-Studio).  Where were you looking for the information?

**Comment by cwensley** [comment]
I've now added a link to the Troubleshooting page from the main wiki landing page, and also added a section to it that describes the problem & solution.  Hopefully this is enough to help others!

Thanks for submitting the issue! It certainly helps move things forward.

**Comment by cwensley** [comment]
Closing this issue, hopefully it's resolved for you!  Thanks again for reporting.
