### ISSUE TITLE
Style enhancements

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#262]
Styles are simple yet powerful, but there are some scenarios that are still not covered:

- [x] Ability to set a style on a base class and have it apply to all subclasses.  E.g. `Style.Add<Control>(...)` should apply to all controls.
- [ ] Ability to have styles applied to a particular control that apply to direct children or all children.  This means we will have to hook into when a control is added to a container and go up the parent chain to find the applicable styles.  This will allow an instance of a control to specify what its children look like.

**Comment by Jojatekok** [comment]
The first scenario is much needed, especially for setting Window properties :)
