### ISSUE TITLE
Panel.MininumSize doesn't work on Eto.Gtk2 project.

### ISSUE THREAD

**Issue by BaseCrosser** [picoe/Eto#263]
**EDIT: It works as expected when using dll's that are build from the latest source code.
Are the NuGet packages up to date?**

When resizing the window the MininumSize gets ignored on a Gtk2 project. (I can't test the Gtk3 project)

Steps to reproduce:
- Create a new Console application.
- Change Change the project type to Executable with GUI.
- Add Eto.Forms Gtk2 NuGet package.
- Change code in MainClass in the Program.cs file to:
```C#
[STAThread]
public static void Main()
{
    Eto.Forms.Application application = new Eto.Forms.Application(Eto.Platform.Get(Eto.Platforms.Gtk2));
    Eto.Forms.Form form = new Eto.Forms.Form { Title = "Mininum Size Test Program", MinimumSize = new Eto.Drawing.Size(800, 600) };
    application.Run(form);
}
```
- Run the application and try to make the window smaller.

This code works in a WinForms and WPF project

Steps to test:
- Create a new Console application.
- Change Change the project type to Executable with GUI.
- Add Eto.Forms WinForms NuGet package.
- Change code in MainClass in the Program.cs file to:
```C#
[STAThread]
public static void Main()
{
    Eto.Forms.Application application = new Eto.Forms.Application(Eto.Platform.Get(Eto.Platforms.WinForms));
    Eto.Forms.Form form = new Eto.Forms.Form { Title = "Mininum Size Test Program", MinimumSize = new Eto.Drawing.Size(800, 600) };
    application.Run(form);
}
```
- Run the application and try to make the window smaller.

**Comment by BaseCrosser** [comment]
I see that you fixed this 5 days ago.
I am closing this issue.

**Comment by cwensley** [comment]
I will be pushing 2.1.0 (from current develop branch) to nuget in the next week or so.  In the meantime, you could use the [develop nuget feed](https://www.myget.org/F/eto/) on myget.

Thanks for taking the time to report the issue!
