### ISSUE TITLE
[WPF] Pressing Enter in GridView moves the selection to the next line

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2630]
How can I disable the feature that pressing Enter in a GridView moves the selection to the next row? 
This functionality greatly interferes with the introduction of another, it really needs to be turned off.

**Comment by cwensley** [comment]
Something like this _should_ work:
```c#
myGridView.KeyDown += (sender, e) => {
  if (!myGridView.IsEditing && e.KeyData == Keys.Enter)
    e.Handled = true;
};
```

**Comment by Serg-Norseman** [comment]
Thank you!
