### ISSUE TITLE
Add CustomControlCell

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#266]
For the GridView/TreeGridView, it would be nice to have a way to use any control as the content of a cell.  This should support data binding and custom logic to show different controls per row.

**Comment by BaseCrosser** [comment]
This would be really great when it gets added.
In the meantime I am working on a progress cell.
I have added a progress cell on WinForms and Gtk. But I have no clue to how I should do it on Wpf.
I did not look at Mac yet but will be shortly.

Here's the link if you want to check it out. https://github.com/BaseCrosser/Eto/commit/2c4ede7922327bd51a918870cdc9f369727dde91

**Comment by BaseCrosser** [comment]
This would be very nice.
I personally need this for a progress bar cell but I didn't have the time to wait.
I have implemented a ProgressCell on Wpf, WinForms, Gtk and Mac.

The progress bar cell on Mac just get drawn (similar to drawable cell).

The link to review is: https://github.com/BaseCrosser/Eto/commit/871cf0dd4f357a36e2c94c88c6ab4254f526f532

@cwensley Should I make a PR for it? Keep in mind that I'm not gonna work on it anymore in the near future. I want to work on some other stuff (I have put to many hours in it for now).

Did you get any progress on this issue?

**Comment by cwensley** [comment]
@BaseCrosser a PR would be great!  Don't worry about not being able to work on it later.  This issue isn't at the top of my todo, so I haven't had any progress on it yet.

**Comment by cwensley** [comment]
Now done!
