### ISSUE TITLE
Eto.Wpf.Forms.Screen.GetImage creates memory leaks

### ISSUE THREAD

**Issue by danilwhale** [picoe/Eto#2674]
## Expected Behavior

Calling Dispose should release all allocated memory from Screen.GetImage

## Actual Behavior

Calling Dispose doesn't do anything

## Steps to Reproduce the Problem

  1. Create Image using `Screen.GetImage`
  2. Dispose it
  3. Allocated memory doesn't release

![image](https://github.com/user-attachments/assets/2000d5b0-23d7-48ae-917b-acf76776b166)
>Memory usage before /\

![image](https://github.com/user-attachments/assets/f015555c-60c9-4c09-b9f2-f71e51b3d34c)
> Memory usage after creating and disposing Image from `Screen.GetImage` 10 times /\

## Code that Demonstrates the Problem

```cs
var screenshot = Screen.PrimaryScreen.GetImage(Screen.PrimaryScreen.Bounds);
screenshot.Dispose();
```

## Specifications

  - Version: 2.8.3
  - Platform(s): WPF
  - Operating System(s): Windows 11

**Comment by ktwrd** [comment]
@danilwhale Have you tried calling `GC.Collect()` after disposing the screenshot? And have you tried checking `GC.GetTotalMemory(true)` to see the true memory usage with your application.

**Comment by cwensley** [comment]
Thanks for the report!  Looks like it should be calling `DeleteObject` on the HBITMAP created [here](https://github.com/picoe/Eto/blob/6734d3280af85ddf9289bb8075b85672f2bd1f02/src/Eto.Wpf/Forms/ScreenHandler.cs#L60).
