### ISSUE TITLE
Support vertical tabs (like Windows 10 Settings UI), optionally icons

### ISSUE THREAD

**Issue by ris-work** [picoe/Eto#2702]
Please let me know if there are better ways of doing this.

## Expected Behavior
TabControl supporting vertical tabs (like Settings UI in Windows 10+, MS Edge), icons (similar to Firefox tabs, Chromium tabs)

## Code that Demonstrates the Problem
```cs
TabControl TC = new TabControl(){Orientation = Vertical}
```

Thank you!

**Comment by cwensley** [comment]
Thanks for the suggestion.  Unfortunately, some platforms don't support vertical tabs (namely Mac).

It might be worth changing the implementation of the DocumentControl to support different orientations instead, which has more functionality (drag/drop reordering, closing of tabs, etc).

**Comment by cwensley** [comment]
Actually, I [take that back](https://developer.apple.com/documentation/appkit/nstabview/tabtype/lefttabsbezelborder?language=objc)!  Looks like something could probably be easily wired up.  

.. although, it probably isn't what you are asking.  It sounds like you want a list-type control (vs rotated tabs) on the left which switches out the right panel.  I would recommend using two separate controls for that currently.

**Comment by cwensley** [comment]
Well, silly me.  `TabControl` already has a `TabPosition` property that does what I mentioned, added [here](https://github.com/picoe/Eto/commit/cdda9a742223b705ae3b9635c715718be54bd81a).  If you want a list/tree on the left with content on the right, please use a `ListBox`, `GridView`, or `TreeGridView` for the area selection, and a Panel on the right that can switch out its content.
