### ISSUE TITLE
FilterCollections cannot be sorted if there are less than 3 elements in them

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#280]
The application crashes whether I specify sorting for a FilterCollection during its creation.

**Comment by cwensley** [comment]
Thank you again for all the bug reports!  This should now be fixed.

**Comment by Jojatekok** [comment]
Awesome, your speed of development is just simply amazing :)

**Comment by Jojatekok** [comment]
@cwensley By the way, will there be a new NuGet package released in the near future? These recent fixes would be necessary for my upcoming application related to a cryptocurrency project.
