### ISSUE TITLE
Enhance support for multilingual applications

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#284]
If you don't deprecate the simple control Bind() functions (without a DataContext), then a simple call of UpdateBindings() on the main form could reload each localized string from the application's Resources, using a specific culture.

**Comment by cwensley** [comment]
Not all of the Bind() methods aren't being deprecated, only the ones that were actually binding to the data context.  They are now named BindDataContext to eliminate confusion on what they are doing.

Could you give an example of what you'd like to see for multilingual applications?

**Comment by Jojatekok** [comment]
I know, but I need the simple Bind() for reading data from Properties.Resources. When the user wants to switch languages at runtime, I just simply change the running thread's culture, and call UpdateBindings() on MainForm.

So, BindDataContext should be used in every case except handling localizable strings.

**Comment by cwensley** [comment]
Which deprecated Bind() method are you specifically referring to?  All of the deprecated version(s) were actually binding to a data context, so there is no lost functionality.  See [here](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/BindingExtensions.cs), [here](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/Controls/Control.binding.cs), and [here](https://github.com/picoe/Eto/blob/develop/Source/Eto/Binding/ObjectBinding.cs#L247) for all of the non-deprecated Bind() methods.

**Comment by cwensley** [comment]
@Jojatekok is this still an issue?  All of the deprecated code has now been removed.  Please let me know which Bind() method(s) you are referring to, and if they are no longer available (though they should be available).

**Comment by Jojatekok** [comment]
Okay, I'll let you know here as soon as I'll have time again to develop. Please keep this issue open until then.

**Comment by cwensley** [comment]
Closing this issue since the methods have already been removed.  If there's specific things that you feel necessary for multilingual support, feel free to comment or open a new issue with a sample of what you'd like to see.
