### ISSUE TITLE
FilterCollections cannot be made ReadOnly

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#285]
Because the FilterCollection object convert its DataStore to an IList, it simply loses its read-only property during conversion (I wanted to show a ReadOnlyObservableCollection's elements). I would suggest that developers could implicitly specify whether a collection should be ReadOnly or not.

**Comment by cwensley** [comment]
Thanks for the suggestion!  Though, I'm not sure a read-only FilterCollection makes sense.. If you change the Sort or Filter property of a FilterCollection, then its items will change positions and the count of the collection will change. Making it read only would mean you couldn't change the Sort or Filter..

What scenario are you trying to achieve with a read only FilterCollection?  I am probably just not understanding what you are trying to do.  An small example would help if possible.

**Comment by Jojatekok** [comment]
I just want to display items without the ability to delete any of them. There could also be a ReadOnly property added for GridViews, thus, I could achieve my goal.

**Comment by Jojatekok** [comment]
Basically, a ReadOnly property for GridViews would be a better aspect, as I could hook a FilterCollection as the grid's DataSource, and then the application just simply won't let users edit grid data.

**Comment by cwensley** [comment]
Ah, you're looking for the [GridColumn.Editable](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/Controls/GridColumn.cs#L89) property.  The GridView doesn't actually modify the *collection*, it modifies the items in the collection.  Hm, perhaps this property should be `false` by default.

Even if a collection is read-only, it doesn't make the items read only.

**Comment by Jojatekok** [comment]
But will all the __rows__ be undeletable if just a single __column__'s Editable property is set to false?

**Comment by cwensley** [comment]
You can't delete rows from the GridView UI, unless you add code specifically to do that.  If it is allowing you to do this, then it is a bug.  The Editable property allows you to edit the value of the cell.

**Comment by Jojatekok** [comment]
I can delete any item from a GridView using the delete key on my keyboard (on Windows). When using a FilterCollection, deleting items is possible, but whether the DataStore is a ReadOnlyObservableCollection, I cannot delete anything from the grid.

**Comment by cwensley** [comment]
Ah, well that shouldn't happen.. I've added issue #292 to fix that.

**Comment by cwensley** [comment]
With #292 now fixed, this should hopefully no longer be a problem.  I'll be closing this issue unless there are any objections - Making FilterCollection readonly will basically make any filtering/sorting throw an ReadOnlyException, making it provide no added value.  You could still wrap it in a ReadOnlyObservableCollection instead as you have pointed out.

**Comment by Jojatekok** [comment]
Great, the fix works exactly as I've imagined. Thank you! :)

**Comment by cwensley** [comment]
No problem!  Thank you for reporting the issue! (;
