### ISSUE TITLE
In GTK, long strings don't get split, even with AutoSize enabled

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#288]
![bug](https://cloud.githubusercontent.com/assets/1928320/6441383/9fd8e040-c0e7-11e4-9eae-34c14a2f9fba.png)

The address - as seen on the image - is shown as a multi-line string in WPF mode.

**Comment by cwensley** [comment]
Did you set Label.Wrap = WrapMode.Character?

**Comment by Jojatekok** [comment]
Ohh, I wasn't sure, because on Windows, the default wrap mode is word. Thanks for your feedback!

**Comment by cwensley** [comment]
The default WrapMode is Word on all platforms, though I believe wpf is a bit smarter in that it'll wrap long words as well.  Let me know if it works for you so I can close the issue.

**Comment by Jojatekok** [comment]
In WPF, the WrapMode.Character setting doesn't do anything. In fact, it makes the situation even worse: it's like WrapMode.None.

**Comment by cwensley** [comment]
Interesting.. WPF is probably mapping the wrong values for the wrap mode.
