### ISSUE TITLE
Add a tray icon control

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#291]

**Comment by ArsenShnurkov** [comment]
Yes, there is NotifyIcon class in .Net framework, but i was unable to use it properly. There should be something more integrated with DBus.

There is also *Workspace Switcher Applet* which would be nice to integrate with through DBus. Usage scenario - MDI programs which should show different set of documents on different workspaces. I will create additional issue for workspaces

**Comment by ArsenShnurkov** [comment]
"The common NotifyIcon isn't visible if you're running a default KDE-desktop;
it requires a Gnome Panel called Notification Area Applet"
http://www.codeproject.com/Articles/466805/AmberIndicator-a-systray-app-under-Linux

**Comment by ArsenShnurkov** [comment]
<h1>Icon as Panel Applet</h1>

https://en.wikipedia.org/wiki/D-Bus
D-BUS is an interprocess communication (IPC) system, providing a simple yet powerful mechanism allowing applications to talk to one another, communicate information and request services.
"D-BUS can become a unified and agnostic IPC mechanism used by both desktops (GNOME and KDE)"
*but, but, but - ICCCM is also interprocess, unified and agnostic...*
see The Kernel Event Layer - DBus a single bus shared by the entire system allows for propagation of events, from the kernel to the uppermost applications on the system.
Events such as disk full and printer queue empty or even battery power low can bubble up the system stack, available for whatever application cares, allowing the system to respond and react.

* The D-Bus specification
http://dbus.freedesktop.org/doc/dbus-specification.html

* DBus library for C# (not a wrapper, pure C#)
https://github.com/mono/dbus-sharp

* Panel Applet Library Reference Manual
https://developer.gnome.org/panel-applet/stable/

* GnomeGoal is to port all Gnome applets to the new DBUS api (from Bonobo). 
https://wiki.gnome.org/Initiatives/GnomeGoals/AppletsDbusMigration

**Comment by ArsenShnurkov** [comment]
<h1>Application Indicators</h1>

15\. Application Panel Indicators
https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators

**Comment by ArsenShnurkov** [comment]
<h1>The System Tray widget (Plasma/KDE)</h1>

https://userbase.kde.org/Plasma/SystemTray

**Comment by ArsenShnurkov** [comment]
<h1>GNOME Shell Message Tray</h1>

http://live.gnome.org/GnomeShell/Extensions

GNOME Shell allows for very limited customization (by design) and the system tray is not one of those areas. In fact the very fact that it exists is only to support certain legacy applications.

http://worldofgnome.org/shell-new-notifications-goodbye-message-tray/
2014-01-05, "GNOME developers are planning some significant changes towards to a completely new notifications system."

https://wiki.gnome.org/Design/OS/Notifications

**Comment by ArsenShnurkov** [comment]
<h1>WingPanel from Elementary OS</h1>

Stylish top panel that holds indicators and spawns an application launcher

elementary OS deprecating ayatana indicators:
https://github.com/dyson/indicator-workspaces/issues/3

**Comment by ArsenShnurkov** [comment]
One example of working with panels is Workrave application.
it have a class for each type of panel... - https://github.com/rcaelers/workrave/blob/branch_v1_10/frontend/applets/indicator/src/indicator-workrave.c

**Comment by hardhub** [comment]
Can somebody answer for my simple questions?

1) Can we now create tray icons with Eto?
2) Which OS are supported?
3) Where can I read that? Maybe class name?

**Comment by cra0zy** [comment]
Bad news, still no support, good news, I was gonna implement this for Linux and Windows over this weekend :)

**Comment by hardhub** [comment]
Really cool! :) Is only merge required now?

And MAC OS?

I do not think we need tray emulation in Android :)

**Comment by cra0zy** [comment]
> Really cool! :) Is only merge required now?

I still haven't started working on it... however I do know what needs to be done and I had to do #714 beforehand.

> And MAC OS?

Someone else will need to implement it for MacOS, the only MacOS I have is on a VirtualBox, which is slow as hell.

**Comment by cra0zy** [comment]
Linux Gtk version almost done :D

![indicator](https://cloud.githubusercontent.com/assets/6773302/23334073/aca96d2a-fb97-11e6-9693-741e8e497010.png)

**Comment by hardhub** [comment]
Good work! :)

Is it regular window or popup with limited content allowed?

**Comment by cra0zy** [comment]
> Good work! :)
> 
> Is it regular window or popup with limited content allowed?

That's just how context menu looks on GNOME with libappindicator extension on :P

**Comment by cra0zy** [comment]
Without the weird extensions I have on my system it looks like:

![withoutextension](https://cloud.githubusercontent.com/assets/6773302/23335356/9185718e-fbb4-11e6-8f19-4bbebd56aaaf.png)

**Comment by hardhub** [comment]
> That's just how context menu looks on GNOME with libappindicator extension on :P

Not sure I understand... I mentioned if it is possible to display any content there for example image instead of Hello World? For example in Windows we cannot do that (only menu items with icons).. to get that we have to implement own window and display it near tray icon or mouse click. In addition we will have to translate coordinates because tray icon (which most likely will be used) is part of Windows.Forms not WPF.

**Comment by cra0zy** [comment]
Again... it's just how a context menu looks on my system... look at the second screenshot, it's showing the exact same thing except with part of my theming disabled.

**Comment by cwensley** [comment]
@hardhub afaik, you can put custom controls in a menu item with winforms (and macOS).  I don't know if this would work on GTK# though.

**Comment by cra0zy** [comment]
@cwensley I just have to report one negative thing on this, appindicator does not allow loading icons from memory... so I had to make Eto's API load it from an actual filepath...

**Comment by cwensley** [comment]
@cra0zy well that is pretty sucky.  Perhaps we can write to a temp file or something..

**Comment by hardhub** [comment]
I mean this:
https://msdn.microsoft.com/en-us/library/system.windows.forms.notifyicon(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.windows.forms.menuitem(v=vs.110).aspx

You can put only text and icon there...

**Comment by cra0zy** [comment]
> @cra0zy well that is pretty sucky. Perhaps we can write to a temp file or something..

That's what I already did.

**Comment by cwensley** [comment]
@hardhub ah right, it uses `MenuItem`, not `ToolStripMenuItem`.. ugh.  Either way, we can just build in the custom window functionality into the windows platform so it won't have to be manually implemented when you want to use it.

**Comment by cra0zy** [comment]
Are you guys talking about a left click window like volume mixer was in Windows 7? I am a bit confused...

Anyway the following is the stucture of the API:
```c#
public bool Visible { get; set; }

public string Title { get; set; }

public event Activated { get; set; }

public void SetMenu(ContextMenu menu);

public void SetIcon(Icon icon);

public void Show();

public void Hide();
```

**Comment by hardhub** [comment]
@cra0zy, I think left click opens custom window. I wrote about right click. At least you example with "Quit" item looks like right-click menu.

**Comment by hardhub** [comment]
@cwensley 

We can try to use ContextMenuStrip property... but I think it will not be able to add anything custom...
https://msdn.microsoft.com/en-us/library/system.windows.forms.contextmenustrip(v=vs.110).aspx

I think you mentioned we can add image on the left of menu item... yes we can.. but I am custom layout of popup available from system tray. I mean image as custom content not as some small icon on the left.

**Comment by cra0zy** [comment]
WinForms implementation done:
![winforms](https://cloud.githubusercontent.com/assets/6773302/23340890/7adbc502-fc3e-11e6-8b7c-970ff8342629.png)

**Comment by cra0zy** [comment]
Gtk Mac/Windows implementation done: 
![2](https://cloud.githubusercontent.com/assets/6773302/23341256/176884f0-fc44-11e6-8e52-0f78cd86f22d.png)

**Comment by cra0zy** [comment]
Wpf implementation done:
![wpf](https://cloud.githubusercontent.com/assets/6773302/23341377/9d1c7082-fc46-11e6-937e-e00c3b0aa38f.png)

**Comment by cra0zy** [comment]
PR up: #731

**Comment by cra0zy** [comment]
@cwensley This can be closed.

**Comment by cwensley** [comment]
@cra0zy still need to do Mac port but that's covered with #750
