### ISSUE TITLE
"Remove Redundant" crap appears when using TUTORIAL code.

### ISSUE THREAD

**Issue by SuperNova2150** [picoe/Eto#294]
When using the freaking TableLayout tutorial's code, the code is dimmed and Xamarin Studio suggests the code is redundant. Um, GUI code is NOT redundant!

**Comment by cwensley** [comment]
I'm not sure what you mean.. it looks good to me.
![screenshot 2015-03-11 23 09 55](https://cloud.githubusercontent.com/assets/367446/6613026/c75e4b88-c843-11e4-8c73-707d0ce43dee.png)
