### ISSUE TITLE
WebView issue when using ExecuteScript

### ISSUE THREAD

**Issue by slothbag** [picoe/Eto#297]
I'm not sure if this is an upstream issue with the control itself but i'll try describe the problem.

If you use the ExecuteScript method to call some "in browser" javascript then when you try to close the Eto form down the app never closes.  The form disappears and all the shutdown events fire but then the app never ends.  In monodevelop you can see this because the debugger shows the app as still running.  Or if you run the app from the console, then the prompt never returns unless you hit ctrl-c.

Its definitely an issue in Linux.  I don't think this is an issue with IE because I never noticed it until switching to linux.  I think OSX has the same issue.

It makes no difference if the javascript executes successfully or not, or even if any return values are sent.

**Comment by cwensley** [comment]
I'm not able to reproduce this on either gtk2/3 or OS X.. what distro and mono version are you using?  Also, gtk2 or 3?  

Are you using the nuget version or a custom compiled version?  Note that sometimes you have to clean your outputs if using XS on OS X, and restart XS.  It sometimes compiles the pcl against the Xamarin.Mac dll's incorrectly.

**Comment by slothbag** [comment]
Don't you hate that. I had a small demo app that demonstrated the bug reliably and now its working fine.

I'll have to do some more testing to reproduce the error, perhaps it was a red herring due to other threading issues.

**Comment by cwensley** [comment]
Yeah that is quite annoying when that happens.  Thanks for reporting anyway!  Let me know if it crops up again.
