### ISSUE TITLE
Wpf set Splitter.Position from OnSizeChanged exception

### ISSUE THREAD

**Issue by firda-cze** [picoe/Eto#302]
I was trying to create sub-class of Splitter in boo, to be able to set the weight/ratio instead of pixels, but got following exception:

	System.ArgumentException: Parametr value nemůže být NaN.
	   v System.Windows.GridLength..ctor(Double value, GridUnitType type)
	   v Eto.Wpf.Forms.Controls.SplitterHandler.set_Position(Int32 value)
	   v Eto.Forms.Splitter.set_Position(Int32 value)
	   v Phi.Forms.Split.AdjustPosition() v B:\firda.net\PhiUtils\Controls\splitter.boo:řádek 29
	   v Phi.Forms.Split.OnSizeChanged(EventArgs e) v B:\firda.net\PhiUtils\Controls\splitter.boo:řádek 34
	   v Eto.Forms.Control.Callback.<>c__DisplayClass1b.<OnSizeChanged>b__1a()
	   v Eto.Platform.Invoke(Action action)
	   v Eto.Forms.Control.Callback.OnSizeChanged(Control widget, EventArgs e)
	   v Eto.Wpf.Forms.WpfFrameworkElement`3.<AttachEvent>b__3(Object sender, SizeChangedEventArgs e)
	   v System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
	   v System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   v System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
	   v System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   v System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   v System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
	   v System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
	   v System.Windows.ContextLayoutManager.fireSizeChangedEvents()
	   v System.Windows.ContextLayoutManager.UpdateLayout()
	   v System.Windows.UIElement.UpdateLayout()
	   v System.Windows.Interop.HwndSource.SetLayoutSize()
	   v System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
	   v System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
	   v System.Windows.Window.SetRootVisual()
	   v System.Windows.Window.SetRootVisualAndUpdateSTC()
	   v System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
	   v System.Windows.Window.CreateSourceWindow(Boolean duringShow)
	   v System.Windows.Window.CreateSourceWindowDuringShow()
	   v System.Windows.Window.SafeCreateWindowDuringShow()
	   v System.Windows.Window.ShowHelper(Object booleanBox)
	   v System.Windows.Window.Show()
	   v Eto.Wpf.Forms.ApplicationHandler.HandleStartup(Object sender, StartupEventArgs e)
	   v System.Windows.Application.OnStartup(StartupEventArgs e)
	   v System.Windows.Application.<.ctor>b__1(Object unused)
	   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   v MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
	   v System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   v System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	   v System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   v System.Windows.Threading.DispatcherOperation.Invoke()
	   v System.Windows.Threading.Dispatcher.ProcessQueue()
	   v System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   v MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   v MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   v MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
	   v System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   v MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   v MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   v System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   v System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	   v System.Windows.Threading.Dispatcher.Run()
	   v System.Windows.Application.RunDispatcher(Object ignore)
	   v System.Windows.Application.RunInternal(Window window)
	   v System.Windows.Application.Run(Window window)
	   v Eto.Wpf.Forms.ApplicationHandler.Run()
	   v Eto.Forms.Application.Run(Form mainForm)
	   v Phi.Dev.MainModule.Main(String[] argv) v B:\firda.net\PhiDev\main.boo:řádek 37

My code in boo:

	namespace Phi.Forms

	import System
	import System.Diagnostics

	import Eto.Forms
	import Eto.Drawing

	class Split(Splitter):

		private weight = single.NaN
		Weight as single:
			get:
				return weight
			set:
				return if value == weight
				weight = value
				AdjustPosition()
		
		protected def AdjustPosition():
			return if single.IsNaN(weight)
			if weight >= 1:
				Position = Math.Min( Width, weight cast int )
			elif weight <= -1:
				Positon = Math.Max( 0, Width - weight cast int )
			elif weight >= 0:
				pos = Math.Round( Width*weight )
				Debug.WriteLine( "pos=${pos}; width=${Width}; weight=${weight}" )
				Position = pos
			else:
				Position = Math.Round( Width*(1+weight) )
		
		protected override def OnSizeChanged( e as EventArgs ):
			AdjustPosition()
			super.OnSizeChanged( e )
		
		protected override def OnLoad(e as EventArgs):
			AdjustPosition()
			super.OnLoad( e )

Debug Output before exception:

    pos=-1; width=-1; weight=0,8
    pos=-1; width=-1; weight=0,8
    pos=900; width=1125; weight=0,8

**Comment by firda-cze** [comment]
After few more tests, it seems that it happens only if

    FixedPanel = SplitterFixedPanel.None

and after examining the source code of `Eto.Wpf/Forms/Controls/SplitterHandler.cs`, I'd guess the problem is on line 287 with variable `scale`

	var controlHeight = Control.IsLoaded ? Control.ActualHeight : Control.Height;
	switch (fixedPanel)
	{
		case SplitterFixedPanel.None:
			if (Widget.Loaded)
			{
				var scale = (row1.Height.Value + row2.Height.Value) / controlHeight;
				row1.Height = new sw.GridLength(value * scale, sw.GridUnitType.Star);
			}
			break;

**Comment by firda-cze** [comment]
More info: I have rewired my project that I can debug Eto.(Wpf.)Forms and it seems, that the problem is in inconsistency between `Control.IsLoaded` and `Widget.Loaded` or `Control.Width` and `Control.ActualWidth`.

**Widget.Loaded: true**
**Control.IsLoaded: false**
Control.ActualWidth: 1125
Control.Width: **NaN**
==> controlWidth: **NaN** 
==> scale: **NaN**
==> exception

The code involved (the other branch than reported before, logic is the same):

	var col1 = Control.ColumnDefinitions[0];
	var col2 = Control.ColumnDefinitions[2];
	if (!Widget.Loaded)
	{
		position = value;
		initialWidth = Size.Width;
		initialHeight = Size.Height;
	}
	if (splitter.ResizeDirection == swc.GridResizeDirection.Columns)
	{
		var controlWidth = Control.IsLoaded ? Control.ActualWidth : Control.Width;
		switch (fixedPanel)
		{
			case SplitterFixedPanel.None:
				if (Widget.Loaded)
				{
					var scale = (col1.Width.Value + col2.Width.Value) / controlWidth;
					col1.Width = new sw.GridLength(value * scale, sw.GridUnitType.Star);
				}
				break;

**Comment by firda-cze** [comment]
I think the Wpf SplitterHandler shall be altered as follows:
(explanation bellow the code)

		public int Position
		{
			get
			{
				if (!Widget.Loaded)
					return position ?? 0;
				if (splitter.ResizeDirection == swc.GridResizeDirection.Columns)
					return (int)Control.ColumnDefinitions[0].ActualWidth;
				return (int)Control.RowDefinitions[0].ActualHeight;
			}
			set
			{
				if (!Widget.Loaded)
				{
					position = value;
					initialWidth = Size.Width;
					initialHeight = Size.Height;
				}
				if (splitter.ResizeDirection == swc.GridResizeDirection.Columns)
				{
					var col1 = Control.ColumnDefinitions[0];
					var col2 = Control.ColumnDefinitions[2];
					
				//	var controlWidth = Control.IsLoaded ? Control.ActualWidth : Control.Width;
					var controlWidth = Control.ActualWidth;
					if (double.IsNaN(controlWidth)) controlWidth = Control.Width;
					
					switch (fixedPanel)
					{
						case SplitterFixedPanel.None:
							if (Widget.Loaded)
							{
								col1.Width = new sw.GridLength(value, sw.GridUnitType.Star);
								col2.Width = new sw.GridLength(controlWidth - value, sw.GridUnitType.Star);
							}
							break;
						case SplitterFixedPanel.Panel1:
							col1.Width = new sw.GridLength(value, sw.GridUnitType.Pixel);
							break;
						case SplitterFixedPanel.Panel2:
							if (Widget.Loaded)
								col2.Width = new sw.GridLength(controlWidth - value, sw.GridUnitType.Pixel);
							else
								col1.Width = new sw.GridLength(value, sw.GridUnitType.Pixel);
							break;
					}
				}
				else
				{
					var row1 = Control.RowDefinitions[0];
					var row2 = Control.RowDefinitions[2];
					
				//	var controlHeight = Control.IsLoaded ? Control.ActualHeight : Control.Height;
					var controlHeight = Control.ActualHeight;
					if (double.IsNaN(controlHeight)) controlHeight = Control.Height;
				
					switch (fixedPanel)
					{
						case SplitterFixedPanel.None:
							if (Widget.Loaded)
							{
								row1.Height = new sw.GridLength(value, sw.GridUnitType.Star);
								row1.Height = new sw.GridLength(controlHeight - value, sw.GridUnitType.Star);
							}
							break;
						case SplitterFixedPanel.Panel1:
							row1.Height = new sw.GridLength(value, sw.GridUnitType.Pixel);
							break;
						case SplitterFixedPanel.Panel2:
							if (Widget.Loaded)
								row2.Height = new sw.GridLength(Math.Max(0, controlHeight - value), sw.GridUnitType.Pixel);
							else
								row1.Height = new sw.GridLength(value, sw.GridUnitType.Pixel);
							break;
					}
				}
			}
		}

1. I took inspiration in Conversion.cs to handle the exception first:

		public static Size GetSize(this sw.FrameworkElement element)
		{
			if (!double.IsNaN(element.ActualWidth) && !double.IsNaN(element.ActualHeight))
				return new Size((int)element.ActualWidth, (int)element.ActualHeight);
			return new Size((int)(double.IsNaN(element.Width) ? -1 : element.Width), (int)(double.IsNaN(element.Height) ? -1 : element.Height));
		}

  and changed the current code to this:

            //  var controlWidth = Control.IsLoaded ? Control.ActualWidth : Control.Width;
                var controlWidth = Control.ActualWidth;
                if (double.IsNaN(controlWidth)) controlWidth = Control.Width;

2. The behaviour of current approach with the `scale` variable is wrong - it produces different ratio. It should be true, that `value/controlWidth = col1.Width/(col1.Width+col2.Width)` but that was not the case - in my tests, I have calculated `Position = 0.8 * Width` and got `1.6/(1+1.6)=0.6` in return. My code will rather alter both:

        col1.Width = new sw.GridLength(value, sw.GridUnitType.Star);
        col2.Width = new sw.GridLength(controlWidth - value, sw.GridUnitType.Star);

3. I have compared the result with WinForms and with my correction, it seems to behave the same now.

4. I am willing to create pull request from this, but would like to talk with some person first, because this would be my first contribution to the project. I don't want to mess things up ;)

**Comment by cwensley** [comment]
Wow, thank you for the detailed bug report and investigation of the problem! At first glance it appears like you are going down the right path for the fix, so go ahead and make a pull request.   Just be sure to read the [Contributing Guidelines](https://github.com/picoe/Eto/wiki/Contributing) on the wiki (especially the part near the end about licensing).

Thanks!
Curtis.
