### ISSUE TITLE
Windows Tablet Issues

### ISSUE THREAD

**Issue by arianitu** [picoe/Eto#304]
I'm using Manager.io (which uses Eto under the covers it looks like) and I'm having issues with text fields not popping up the keyboard on a Windows Tablet (http://www.asus.com/transformerbook)

Is this a known issue?

**Comment by cwensley** [comment]
No, this is not a known issue.  Manager.io is seems to be using a *super* old version of Eto (v1.1), so perhaps a newer version would help, I don't know.  Eto.Forms also (by default) uses the standard embedded IE WebBrowser control on windows, so it is unlikely that it is a specific problem with Eto.

Most likely it is something to do with the HTML and/or javascript that is generated by Manager, so I suggest filing a bug report on Manager's website and getting support there.

If you are interested in solving this particular issue with Eto, perhaps you can compile the source and run Eto.Test and give it a go on your tablet and see if its WebView control has the same problem.
