### ISSUE TITLE
Can't right click or paste in a Eto.Forms WebView (WinForms)

### ISSUE THREAD

**Issue by voltagex** [picoe/Eto#306]
I'm trying to paste from a password manager into a WebView - it doesn't work at all.
Expected result: on right click, open the browser's context menu or on paste - contents of clipboard are pasted.

**Comment by cwensley** [comment]
I believe this is fixed in the develop branch. Could you give it a try?

**Comment by cwensley** [comment]
Tested with 2.1 and it indeed works now. To get the context menu, you must set WebView.BrowserContextMenuEnabled = true.
