### ISSUE TITLE
Adding a context menu to a Label doesn't work

### ISSUE THREAD

**Issue by rooly4** [picoe/Eto#308]
using the following method:
```
label.MouseDown += (sender, e) => {
	if (e.Buttons != MouseButtons.Alternate)
		return;

	var button = new ButtonMenuItem () { Text = "Test" };
	var context = new ContextMenu (button);
	context.Show (sender as Label);
};
```
displays
![image](https://cloud.githubusercontent.com/assets/4007907/6832009/befe2162-d2f1-11e4-8f31-fbc896241230.png)

Error is consistent on WPF, GTK2#, no menu appears at all on WinForms

**Comment by rooly4** [comment]
On WPF, numerous errors appear as
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'MenuItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
```

**Comment by cwensley** [comment]
It appears, at least from your sample, that you're not adding the button to the context.Items collection..

Also, the Eto.Test application's `Behaviors > ContextMenu` test does exactly this and seems to work on all platforms.

Could you supply a full repro of your issue?

**Comment by cwensley** [comment]
Scratch that first part, I see the constructor.. d;

**Comment by cwensley** [comment]
And scratch the second part (regarding repro), it's due to using the constructor/AddRange. (smacks forehead)
