### ISSUE TITLE
In Gtk, windows' MinimumSize properties are not working as expected

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#313]
When the MinimumSize of a window gets set, the window starts to act weird:

- If the initial content of the window is a TableLayout with the last row's ScaleHeight property set to false (and a row in the middle with ScaleHeight=true), then the content gets adjusted according to the MinimumSize, but only the last TableRow's height gets increased.

- Windows can be resized to a size which is less than MinimumSize

![multiple bugs](https://cloud.githubusercontent.com/assets/1928320/6899949/db79b7c8-d703-11e4-9df2-381622f8891a.png)

**Comment by cwensley** [comment]
Should hopefully be fixed. Please re-open if this is still an issue, though I'll probably need a simple repro to go further.
