### ISSUE TITLE
In Gtk, the SynchronizationContext element doesn't always work

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#315]
I cannot describe this issue very well, so please refer to the code below:

https://github.com/Jojatekok/MoneroGui.Net/blob/a0646fe5dd86dd87824be5f8bed7160c9f84699b/MoneroGui.Net.Desktop/Windows/QrCodeDialog.cs#L265

From line 265, remove the platform check, and keep only the following line until 270:
    Utilities.SyncContextMain.Send(s => SetQrCodeImageSource(bitmap), null);

Try to run this code on Ubuntu Linux v14 (Gtk2): somehow, the execution will halt just as the SynchronizationContext gets utilized.

**Comment by cwensley** [comment]
That code is a little off actually - you are disposing the bitmap most likely before the async code can even use it.  (hence the resharper warning there).

You should dispose of the bitmap after it is used inside the async delegate's call to `SetQrCodeImageSource`.

**Comment by Jojatekok** [comment]
I've tried setting

    var x = "";

with a breakpoint in a SynchronizationContext, but the code didn't even run!

**Comment by cwensley** [comment]
Are you already in the main thread when running the code?  I'm not sure if the Gtk sync context deals with that

**Comment by cwensley** [comment]
Also, not sure if you're aware, but to post to the main thread, there's Application.Instance.Invoke(...) (blocking), and Application.Instance.AsyncInvoke(...)  (non-blocking)

**Comment by cwensley** [comment]
Yeah, it looks like it doesn't handle the case when the calling thread is actually the main thread: https://github.com/picoe/Eto/blob/develop/Source/Eto.Gtk/Forms/GtkSynchronizationContext.cs#L18

This should be changed to add a check for the current thread like it does for Application.Invoke:
https://github.com/picoe/Eto/blob/develop/Source/Eto.Gtk/Forms/ApplicationHandler.cs#L91-L92
