### ISSUE TITLE
Add a feature to set the startup location of dialogs

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#319]
I would like to set a Dialog's position to the center of its parent Window, but it seems that I cannot even get the parent Window of Dialogs...

_Related: http://stackoverflow.com/questions/4306593/wpf-how-to-set-a-dialog-position-to-show-at-the-center-of-the-application_

**Comment by Panzerfather** [comment]
Generally the window is set up to center position if you open it like this:

MyDialog.ShowModal(this); <= where "MyDialog" is the Dialog to open and "this" is the parent control.

You can then move it via the Location property.

BUT right now, Eto isn't setting up the Parent property of the control when runnig ShowModal-Functions.

Quick solution is to change following functions in the Eto.sln:

Forms\Dialog.cs
=======================
/// <summary>
/// Shows the dialog modally, blocking the current thread until it is closed.
/// </summary>
/// <remarks>
/// The <paramref name="parent"/> specifies the control on the window that will be blocked from user input until
/// the dialog is closed.
/// </remarks>
/// <param name="parent">Parent control that is showing the form</param>
public void ShowModal(Control parent = null)
{
	base.Parent = parent as Container;

	bool loaded = Loaded;
	if (!loaded)
	{
		OnPreLoad(EventArgs.Empty);
		OnLoad(EventArgs.Empty);
		OnDataContextChanged(EventArgs.Empty);
		OnLoadComplete(EventArgs.Empty);
	}

	Application.Instance.AddWindow(this);

	Handler.ShowModal(parent);
}

/// <summary>
/// Shows the dialog modally asynchronously
/// </summary>
/// <remarks>
/// The <paramref name="parent"/> specifies the control on the window that will be blocked from user input until
/// the dialog is closed.
/// </remarks>
/// <param name="parent">Parent control that is showing the form</param>
public Task ShowModalAsync(Control parent = null)
{
	base.Parent = parent as Container;

	bool loaded = Loaded;
	if (!loaded)
	{
		OnPreLoad(EventArgs.Empty);
		OnLoad(EventArgs.Empty);
		OnDataContextChanged(EventArgs.Empty);
		OnLoadComplete(EventArgs.Empty);
	}

	return Handler.ShowModalAsync(parent);
}

**Comment by Jojatekok** [comment]
Thank you! I just wanted to use the parent Window's properties :)

**Comment by Jojatekok** [comment]
This issue shouldn't be closed until it's pulled to the main repository

**Comment by Panzerfather** [comment]
This is finally merged into develop-branch, use the Window.Owner-Property to get the owning parent window. you can use the new OwnerChanged-Event to reposition the child. This can finally be closed.

**Comment by Jojatekok** [comment]
Awesome, thank you! :+1:
