### ISSUE TITLE
Drag and Drop support

### ISSUE THREAD

**Issue by JosefNemec** [picoe/Eto#320]
I've looked at API documentation and haven't found any mention about Drag&Drop support. Is it implemented and I'm just missing something or it's not part of the framework yet?

**Comment by cwensley** [comment]
No, Drag & Drop is not yet implemented.  I'm not sure when I will be getting to this, but has been on my radar.

**Comment by JosefNemec** [comment]
I will need it for one of the projects, so I may also start looking into it if you don't mind.

**Comment by cwensley** [comment]
Yes, that would be great!  I'm not sure of the best api for drag & drop, but I usually investigate all platforms first before deciding.  Usually, a blend of WinForms and WPF api's seems to work well as it makes it easy to use, yet flexible.

**Comment by JosefNemec** [comment]
I finally go time to do this and I was able to implement some initial stuff for WPF, WinForms and GTK (I don't have access to MAC right now). However in GTK I'm stuck on getting original (Eto) object being dropped. In WPF and WinForms I simply pass source Eto object to drag parameters of native D'n'D API, but GTK only supports passing of byte arrays, which means that I cannot simple pass Eto object to it (or at least I haven't found a way how to do it).

So I was wondering, is there an option to convert native widget to Eto widget since I only have source control as GTK widget?

**Comment by cwensley** [comment]
Wow, excellent!  I'm not sure the best way to get the source Eto control.. you'll probably have to keep a static dictionary of Eto controls while doing a drag/drop operation so you can look it up based on the Gtk handle.. this is probably what WinForms and/or WPF (and/or GTK) are doing behind the scenes to route to the drag operations to the right control instance.

**Comment by steffenWi** [comment]
@JosefNemec hey, I'm not that familiar with Eto, but maybe take a look at XWT. They've Drag&Drop implemented on the GTK side (take a look at the WidgetBackend.cs file for example). Maybe that helps.

**Comment by TomQv** [comment]
Again missing this....

**Comment by cwensley** [comment]
Fixed with #880

Thanks again for all the input everyone!
