### ISSUE TITLE
On the MonoMac platform, Buttons without Text have unnecessary space inside themselves

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#325]
On the right side of both buttons shown below, there is a few unneeded space (probably reserved for text). It doesn't seem to appear on any other platform.

![bug](https://cloud.githubusercontent.com/assets/1928320/7012877/cb27bce2-dcb4-11e4-8faf-e2e73d5a1fd3.png)

**Comment by cwensley** [comment]
This is a duplicate of #250, merging these issues together.
