### ISSUE TITLE
GTK2 on Linux fails to initialize - missing libgobject-2.0-0.dll

### ISSUE THREAD

**Issue by JosefNemec** [picoe/Eto#330]
I'm on linux Mint (Debian base) Mono 3.12.1, GTK# 2.12.26 . I'm trying to run GTK2 test application, but it fails on DllNotFoundException for libgobject-2.0-0.dll. I tried creating dllmap in test app's configuration file to libgobject-2.0.so.0, but it didn't help. Any ideas? I didn't have any problems running it on OSX and Windows.

    System.TypeInitializationException: An exception was thrown by the type initializer for Gtk.Application ---> System.TypeInitializationException: An exception was thrown by the type initializer for GLib.GType ---> System.DllNotFoundException: libgobject-2.0-0.dll
      at (wrapper managed-to-native) GLib.GType:g_type_init ()
      at GLib.GType..cctor () [0x00000] in <filename unknown>:0

**Comment by cwensley** [comment]
Hm, do you have gtk-sharp installed correctly?  This usually will happen if you don't have the correct gtk-sharp.dll.config, gdb-sharp.dll.config, etc files installed correctly.  Also, what version of Eto are you using?

Can you run other gtk-sharp 2 apps, such as monodevelop?

**Comment by Panzerfather** [comment]
As @cwensley stated, take a look at your /usr/lib/mono/gac/glib-sharp/2.12.0.0__{GUID}/glib-sharp.dll.config. This should look something like this:

```
<configuration>
  <dllmap dll="libglib-2.0-0.dll" target="libglib-2.0.so.0"/>
  <dllmap dll="libgobject-2.0-0.dll" target="libgobject-2.0.so.0"/>
  <dllmap dll="libgthread-2.0-0.dll" target="libgthread-2.0.so.0"/>
</configuration>
```

**Comment by JosefNemec** [comment]
@Panzerfather: glib-sharp.dll.config seems to be correct.
@cwensley: I'm building Eto myself from latest develop branch. Other GTK# apps seem to work just fine, even GTK# project created in MonoDevelop runs without problem.

**Comment by cwensley** [comment]
@JosefNemec, are the gtk-sharp.dll glib-sharp.dll, etc in your application directory?  That's the only other thing I can think of that would cause this issue.

**Comment by JosefNemec** [comment]
Yes that was it :( All GTK assemblies were in output folder, probably from time where I tried it on different platforms and I forgot to clean the folder. Thanks for the help

**Comment by cwensley** [comment]
@JosefNemec No problem, glad to help!
