### ISSUE TITLE
XAML: Defining items of a control differs form control to control

### ISSUE THREAD

**Issue by Panzerfather** [picoe/Eto#336]
When you want to define items/subitems in Eto-XAML of a ToolBar you have to declare something like this (same style even for MenuBar):

```
<Dialog.ToolBar>
    <ToolBar ID="MyToolbar">
        <ToolBar.Items>
            <ButtonToolItem ID="MyToolbarItem1" ToolTip="MyToolbarItem1" />
            <ButtonToolItem ID="MyToolbarItem2" ToolTip="MyToolbarItem2" />
            <ButtonToolItem ID="MyToolbarItem3" ToolTip="MyToolbarItem3" />
            <SeparatorToolItem />
            <ButtonToolItem ID="MyToolbarItem3" ToolTip="MyToolbarItem4" />
        </ToolBar.Items>
    </ToolBar>
</Dialog.ToolBar>
```

But when you want to define a TabControl you have to write like this:

```
<TabControl ID="MyTabControl">
    <TabPage ID="MyTabPage1" Text="MyTabPage1">
        ... Content ...
    <TabPage ID="MyTabPage2" Text="MyTabPage2">
        ... Content ...
    </TabPage>
    <TabPage ID="MyTabPage3" Text="MyTabPage3">
        ... Content ...
    </TabPage>
</TabControl>
```

Which is very confusing and nonintuitive. It should be the same stylistic approach for all controls which includes subcontrols.

The TabControl-Style is a much better approach and it is more Wpf-XAML like styling which will make it easier to convert an XAML-Application to Eto.

**Comment by cwensley** [comment]
Some controls may be missing the ContentPropertyAttribute for this.

**Comment by Panzerfather** [comment]
I will take a look at this later and recheck the ContentPropertyAttribute of the controls I found.

**Comment by Panzerfather** [comment]
You are right, they are missing the content attribute. Uploading a patch for this later.

But how to deal with the MenuBar-Class? Content is also Items, that's clear. But what's about ApplicationItems, HelpItems, IncludeSystemItems? You could only set one ContentProperty per class.

What did each of them do in a Mac-Environment?

**Comment by Panzerfather** [comment]
Uploaded a patch.

**Comment by Panzerfather** [comment]
Moved this from PullRequest to here for discussion:

So HelpItems, ApplicationItems, IncludeSystemItems have to stay that's clear. But shouldn't we try to "wrap" them to make the notation of the XAML-code and C#/VB-coding straighter?

e.g. if we would include two new properties "SpecialType" and a "MenuType" in the ButtonMenuItem-Class we could get rid of all the extra properties QuitItem, AboutItem, ApplicationItems, HelpItems and so on.
To create e.g. the Application-Menu you should only need to query the items via a linq query over the MenuType-Property of the button.

XAML-Code:

```XML
<Dialog.MenuBar>
    <MenuBar ID="MyMenubar">
      <Items>
        <ButtonMenuItem ID="MyItem1" ToolTip="MyItem1">
        <ButtonMenuItem ID="MyItem2" ToolTip="MyItem2">
        <ButtonMenuItem ID="MyQuitItem" ToolTip="Quit" SpecialType="QuitItem">
        <ButtonMenuItem ID="MyApplicationItem" ToolTip="MyApplication" MenuType="ApplicationMenu">
        <ButtonMenuItem ID="MyHelpItem" ToolTip="Help" Type="HelpItem" MenuType="HelpMenu">
      </Items>
    </MenuBar>
</Dialog.MenuBar>
```

C#-Code:

```C#
Menu = new MenuBar
{
    Items =
    {
        new ButtonMenuItem { Text = "MyItem1", ToolTip="MyItem1" } 
        new ButtonMenuItem { Text = "MyItem2", ToolTip="MyItem2" }
        new ButtonMenuItem { Text = "MyQuitItem", ToolTip="Quit", SpecialType="QuitItem" }
        new ButtonMenuItem { Text = "MyApplicationItem", ToolTip="MyApplication", MenuType="ApplicationMenu"}
        new ButtonMenuItem { Text = "MyHelpItem", ToolTip="Help" Type="HelpItem", MenuType="HelpMenu"}
    }
}
```

**Comment by Panzerfather** [comment]
I found another problem with the current approach of splitting QuitItem and HelpItem away from the menu.

If the user declares the QuitItem- and AboutItem-Property before he creates the menu for them:

```C#
var about = new Commands.About();
var quit = new Commands.Quit();

Menu = new MenuBar
{
	QuitItem = quit,
	AboutItem = about,
	Items =
	{
		new ButtonMenuItem
		{
			Text = "&File",
			Items =
			{
				...
			}
			Text = "&Help",
			Items =
			{
				...
			}
		}
	}
}
```

he will gets this crippled menu:

![crippledmenu](https://cloud.githubusercontent.com/assets/11777736/7135489/936c891a-e2a7-11e4-8c05-3f9b8dedfc1d.png)

This is not something the user will expect.

**Comment by Panzerfather** [comment]
I made a first draw which will remove the QuitItem and HelpItem and rebuild their platform usage.

https://github.com/Panzerfather/Eto/commit/a75e16dac93799040d9c23244566051dfe82619d

**Comment by cwensley** [comment]
Now tracking the MenuBar issue separately.  This one is fixed, in that we only need the appropriate `ContentPropertyAttribute`.  Otherwise, it is standard Xaml syntax.

Thanks again for reporting the issue(s)!
