### ISSUE TITLE
Direct2D Matrix transform produces invalid output

### ISSUE THREAD

**Issue by wieslawsoltes** [picoe/Eto#349]
The following code produces invalid transformations when used in Direct2D platform. The WinForms platform transformations are correct.

    var _gfx = gfx as Graphics;
    ...
    var gp = new GraphicsPath();
    ...
    var m = Matrix.Create();
    var c = new PointF((float)t.CenterX, (float)t.CenterY);
    // translate
    m.Translate((float)t.OffsetX, (float)t.OffsetY);
    // rotate
    m.RotateAt((float)t.RotateAngle, c);
    // skew
    m.Translate(-c.X, -c.Y);
    m.Prepend(
        Matrix.Create(
            1, 
            (float)Math.Tan(Math.PI * t.SkewAngleY / 180.0), 
            (float)Math.Tan(Math.PI * t.SkewAngleX / 180.0), 
            1, 
            0, 
            0));
    m.Translate(c.X, c.Y);
    // scale
    m.ScaleAt((float)t.ScaleX, (float)t.ScaleY, (float)t.CenterX, (float)t.CenterY);

    _gfx.SaveTransform();
    _gfx.MultiplyTransform(m);

    var brush = ToSolidBrush(path.Style.Fill);
    var pen = ToPen(path.Style, _scaleToPage);
    _gfx.FillPath(
        brush,
        gp);
    _gfx.DrawPath(
        pen,
        gp);
    brush.Dispose();
    pen.Dispose();

    _gfx.RestoreTransform();

NuGet package versions (.NET 4.5):
* Eto.Forms, version 2.0.5
* Eto.Platform.Direct2D, version 2.0.5
* Eto.Platform.Windows, version 2.0.5
* SharpDX, version 2.5.0
* SharpDX.Direct2D1, version 2.5.0
* SharpDX.DXGI, version 2.5.0

**Comment by wieslawsoltes** [comment]
Direct2D:
![direct2d](https://cloud.githubusercontent.com/assets/2297442/7937893/c8be4bb4-0942-11e5-9910-441bd83931a5.PNG)

WinForms:
![winforms](https://cloud.githubusercontent.com/assets/2297442/7937900/cf109b8e-0942-11e5-8d2d-2e227dcbc1d1.PNG)

**Comment by cwensley** [comment]
Hm, What values are you using?  I can't reproduce this with 2.0.5 or develop branch.. at least with a simple figure:

![screenshot 2015-06-02 22 46 03](https://cloud.githubusercontent.com/assets/367446/7953419/3f2c12fa-0979-11e5-8c45-061bf56d3d60.png)

**Comment by cwensley** [comment]
By the way, [this](https://gist.github.com/cwensley/7dc4f6755c8b20863eb6) is the code I'm testing with.

**Comment by wieslawsoltes** [comment]
Please try this [this](https://gist.github.com/wieslawsoltes/d0e5aa8b4c38d89e3982) code. I was able to reproduce the issue.

**Comment by cwensley** [comment]
Excellent, thanks!  I'll give it a go.

**Comment by cwensley** [comment]
Odd.. the only platform that this shows correctly is WinForms.  This might actually be a bug in winforms, not Direct2D..  Still investigating though.

**Comment by wieslawsoltes** [comment]
Please try this [this](https://gist.github.com/wieslawsoltes/1ac32267f6b998366a06) code. I have simplified the code and included ellipse drawing/filling. I have drawing issues in both Wpf and WinForms versions.

**Comment by wieslawsoltes** [comment]
Also I have created native WinForms test with exact same drawing instructions. Code is [here](https://gist.github.com/wieslawsoltes/5815d4ae0bdcae9b0583).

![native_winforms](https://cloud.githubusercontent.com/assets/2297442/7956358/a16bb57c-09df-11e5-9178-8f57b32077e5.PNG)

**Comment by cwensley** [comment]
Thanks again for the issue report and detailed tests!  It really helped ensure this worked correctly.  I've included your two samples in Eto.Test.  Let me know if this is a problem.

**Comment by wieslawsoltes** [comment]
No problem. Tested with v2.1.0-build0330 and its fixed in test and in my custom app.

**Comment by wieslawsoltes** [comment]
I have noticed something else during my test. The ellipse stroke and fill looks little bit off.

![ddd](https://cloud.githubusercontent.com/assets/2297442/9199315/0c3ed95e-4042-11e5-831f-96636b26c5ea.PNG)

**Comment by cwensley** [comment]
Yes, this is the intended result in `PixelOffsetMode.None`.  To correctly use fill operations in this mode you have to reduce the rect by 1 in both x/y to get the desired result.  If you change to PixelOffsetMode.Half (using the dropdown in the test), it will align everything correctly without having to do this.

`PixelOffsetMode.None` is designed (at least from an Eto perspective) to simplify aligning drawing operations to logical pixels using whole number values.  For example, drawing a 1px line from 10,10 to 100,10 will not be antialiased.  Similarly, filling a rect from 10,10 to 100,100 will also not be antialiased and will occupy the space *up to* but not including the 100th pixel.

I'd hesitate to change this behaviour as it'd break a lot of existing code.

**Comment by cwensley** [comment]
Although, it should be the same with winforms and it was in my testing.  I'll check that again as well.  Thanks for pointing that out.
