### ISSUE TITLE
GTK: When set resizable=false, size of dialog will be so small 

### ISSUE THREAD

**Issue by keepwn** [picoe/Eto#351]
You can test it:
Eto.Test.Gtk2.exe->Dialogs->Custom Dialog->Standard Dialog.

**Comment by cwensley** [comment]
Yeah I noticed this as well.  Thanks for reporting it!

I have a bunch of saved up work for GTK (now only in my head because I lost a bunch of work), but will get back to re-implementing that soon which should fix this!
