### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by NovaPikmin** [picoe/Eto#352]
How do I install ETO.Forms? I've seen the tutorial, however, that's outdated as it only installs version 1.0. Is there anyway to install the latest version of ETO via the add-in/plug-in manager?

**Comment by polgarijog** [comment]
If you are VS.NET user: the easiest way is to install the eto.forms project templates and then click New->Solution->select Eto.Forms projects.

https://visualstudiogallery.msdn.microsoft.com/469490d7-b7b0-41b6-a60f-630be148e494

**Comment by cwensley** [comment]
The latest release version of Eto.Forms is 2.0.7, however the addin is version 1.0.  I will be synchronizing the addin version with the version of Eto.Forms in the future.  The addin currently will use 2.0.3 of Eto.Forms for its templates, but all you have to do is update your nuget packages afterwards to update to the latest release.

If you want to create a project without using the addin, simply add the corresponding nuget packages you want.  There are instructions [here](https://github.com/picoe/Eto/wiki/Preparing-your-solution) to create a new project which you can then add the packages you like.

To use the latest develop branch, add the [MyGet Development Feed](https://www.myget.org/F/eto/) which is referenced on the main readme to your sources and update your packages to the latest prerelease version.

Please let me know if this resolves your issue!

**Comment by cwensley** [comment]
Flagging this as closed as it seems to be a misunderstanding on version numbers and how to install.  To 'install' Eto.Forms, you use nuget.  To install the develop branch, use the myget feed linked from the README.  The VS/XS addins provide easy to create templates, but still use nuget to install the packages.

If you are still having issues feel free to reopen this issue!
