### ISSUE TITLE
eto.forms - only for Windows and OSX

### ISSUE THREAD

**Issue by polgarijog** [picoe/Eto#354]
Hi,

I changed all the portable class libraries to normal class libraries in my solution. The reason: I'm developing only for the "normal" .NET platform in Windows, no winphone or anything else.

But OSX is still in target. What is or what can be the risk or issue after changing my library type to normal from portable?

Thanks in advance

**Comment by cwensley** [comment]
Hi, thanks for asking!

The only time you'll need to use PCL or a separately compiled version of your app is if you want to target Xamarin.Mac, which allows you to:
  1. bundle mono into your app so your users don't have to install mono to run your app on OS X, and
  2. run your app in 64-bit on OS X.

If you are using the **Eto.Platform.Mac.Template** nuget package to create your app bundle (or doing this manually), then you will have no issues using 'normal' .NET assemblies (as long as they can run on mono and don't p/invoke windows-specific functionality).  It uses the open source [monomac](https://github.com/mono/monomac) which requires mono to be installed before your app will run.

Hope this helps!

P.S. For general questions and discussion, you can use the [forums](http://groups.google.com/group/eto-forms) instead. (;

**Comment by polgarijog** [comment]
thank you!
