### ISSUE TITLE
Getting Window Handle from an Eto WPF form

### ISSUE THREAD

**Issue by voltagex** [picoe/Eto#355]
I need to get an IntPtr handle to the native form to process WM_ messages.

The code I have so far is 

```csharp
    class MainForm : Form
    {
        public MainForm()
        {
            var nativeWindow = this.ToNative() as System.Windows.Window;

            this.ClientSize = new Eto.Drawing.Size(400, 600);
            var wih = new WindowInteropHelper(nativeWindow);
            HwndSource source = HwndSource.FromHwnd(wih.Handle);
           // source.AddHook(new HwndSourceHook(WndProc));
        }
```

but that nativeWindow cast isn't right as I'm getting a zero every time.

Any ideas?

**Comment by cwensley** [comment]
Take a look at [this](http://stackoverflow.com/a/4826741/981187).  The hwnd of a WPF window isn't allocated until it is needed.  Use `WindowInteropHelper.EnsureHandle()` before getting the handle to ensure it is allocated.

**Comment by cwensley** [comment]
You can also use (in the develop branch), `myForm.NativeHandle`, which does the same thing.

**Comment by cwensley** [comment]
Flagging this as closed.  `myForm.NativeHandle` should give you what you need, or call `WindowInteropHandle.EnsureHandle()`.  If not, please feel free to reopen or open a new issue with a repro.
