### ISSUE TITLE
WebView unexpected keyboard behaviour in Winforms and WPF

### ISSUE THREAD

**Issue by wolfyreload** [picoe/Eto#357]
- I'm seeing strange behaviour in the WebView control in both Winforms and Wpf.
- GTK2 WebView is behaviour as I would expect.

Example of the issue: 
- The Up arrow key changes focus from the WebView to the previous control (would expect it to scroll up in the page)
- The Down arrow key changes the focus from the WebView to the next control (would expect it to scroll down in the page)
- If I have any defined shortcuts defined in the Eto.Forms.Command Menu items all the ctrl+1-9, alt+1-9, ctrl+a-z and alt+a-z shortcut keypresses appear get ignored when the WebView is selected.

**Comment by cwensley** [comment]
Ah good 'ol IE.. I can see ctrl/alt combo keys getting buried, since those are typically handled in the browser as accesskey shortcuts.  Up/Down I'm not sure why, those might have to be handled manually by Eto to scroll the view perhaps..

**Comment by wolfyreload** [comment]
Just checked out 2.1.0, this is working much better now. Thank you!
