### ISSUE TITLE
Eto.Wpf.Drawing.FontHandler.Dispose throws System.NullReferenceException

### ISSUE THREAD

**Issue by wieslawsoltes** [picoe/Eto#359]
A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
in Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing).

Code to reproduce exception https://gist.github.com/wieslawsoltes/8fedd8bdc0e5493ae35f

The exception is thrown only when using Wpf platform. I have checked Gtk2, Direct2d and WinForms, no problem therer.

**Comment by wieslawsoltes** [comment]
The code when run only once produces a lot of exceptions. Is this redrawing done over and over again?

    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31
    A first chance exception of type 'System.NullReferenceException' occurred in Eto.Wpf.dll
    Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w Eto.Wpf.Drawing.FontHandler.Dispose(Boolean disposing)
       w Eto.WidgetHandler`1.Dispose()
       w Eto.Widget.Dispose(Boolean disposing)
       w Eto.Widget.Dispose()
       w ConsoleApplication22.MyForm.<.ctor>b__1(Object sender, PaintEventArgs e) w g:\DOKUMENTY-FUSION\Visual Studio 2013\Projects\ConsoleApplication22\ConsoleApplication22\Program.cs:wiersz 31

**Comment by cwensley** [comment]
Great, thanks for reporting the issue!  I'll take a look.

**Comment by cwensley** [comment]
Thanks again for reporting!  This should now be fixed.
