### ISSUE TITLE
WPF Dropdown

### ISSUE THREAD

**Issue by jaebird** [picoe/Eto#368]
If I put a DropDown in a TableLayout and set the layout to Visible = False and then later set the layout to Visible = True, the DropDown cannot be used to select any items. If I use the Enabled property instead of the Visible property, the selection works fine.

This issue does not exist in WinForms or Gtk. Using latest git.

**Comment by cwensley** [comment]
Thanks for the error report!  This should hopefully now be fixed in the develop branch.
