### ISSUE TITLE
Binding Documentation

### ISSUE THREAD

**Issue by michaeled** [picoe/Eto#369]
I'm not entirely sure how to use the binding APIs that are provided. Could explicit examples be added to the test project or wiki?

Also, how do I send a parameter to a command's execute method? I'm working with a button control.

**Comment by cwensley** [comment]
I've been meaning to write an overview of the binding functionality, thanks for the prod.  

As for passing a parameter, what would be the example?  All your data *should* be coming from the view model, i'm not sure what you'd want to pass.

**Comment by michaeled** [comment]
I was thinking of something on the lines of the CommandParameter property that's available in WPF. I would like to give it a path to a property on another control. You're right though, it could be accessed through a view model. I wanted to get the feature implemented, and refactor after I understood the bindings, though.

**Comment by cwensley** [comment]
Binding wiki now written!  https://github.com/picoe/Eto/wiki/Data-Binding

Let me know if it's missing anything or is unclear.

**Comment by zxcdani** [comment]
Hi, can you add some binding syntax on XAML? I'm lost. 

Thanks
