### ISSUE TITLE
Mac: TextChanged event doesn't fire for ComboBox when selecting from list

### ISSUE THREAD

**Issue by JosefNemec** [picoe/Eto#376]
I have a standard ComboBox filled with items like this:
```c#
foreach (var cluster in Configuration.LabManagers.Select(a => a.Name).ToList())
{
    comboCluster.Items.Add(new ListItem { Text = cluster });
}
```

And databinding set on it for Text property (idea is that user have some list of possible values, but he's able to put any custom value):
```c#
comboCluster.BindDataContext(a => a.Text, (MachineDefinition b) => b.Cluster);
```

The problem is that when you select some item from drop down list, TextChanged event doesn't fire. It only fires when you manually change the text. I'm using latest develop branch and it works for me on WPF.

Btw I looked into ComboBoxHandler for Mac, trying to find where the problem is and I couldn't figure it out. It seems that appropriate change events are not fired by Cocoa it self, but maybe I was looking wrong.

**Comment by cwensley** [comment]
Thanks for submitting the issue!  It appears the custom cell to make the drop down width able to grow wider than the control itself messed up the change events.  Specifying the type overriding the CellClass static property seems to work for the events.
