### ISSUE TITLE
Font decoration not rendered using Eto.Platform.Direct2D (build: 2.1.0-build0347)

### ISSUE THREAD

**Issue by wieslawsoltes** [picoe/Eto#377]
Sample code to reproduce issue, other platforms are ok in my tests:

    using System;
    using Eto.Drawing;
    using Eto.Forms;

    namespace Demo
    {
        class MyForm : Form
        {
            public MyForm()
            {
                ClientSize = new Eto.Drawing.Size(800, 400);
                Title = "Eto.Forms " + Platform.ID;
                var drawable = new Drawable { Size = new Size(800, 400) };

                drawable.Paint += (sender, e) =>
                {
                    var g = e.Graphics;
                    g.Clear(Brushes.White);

                    var fontStyle = FontStyle.None;
                    fontStyle |= FontStyle.Bold;
                    fontStyle |= FontStyle.Italic;

                    var fontDecoration = FontDecoration.None;
                    fontDecoration |= FontDecoration.Underline;
                    fontDecoration |= FontDecoration.Strikethrough;

                    var font = new Font("Arial", 24f, fontStyle, fontDecoration);

                    g.DrawText(font, Brushes.Red, 50f, 50f, Platform.ID);

                };

                var layout = new PixelLayout();
                layout.Add(drawable, 0, 0);
                Content = layout;
            }
        }

        class Program
        {
            [STAThread]
            static void Main(string[] args)
            {
                new Application(Eto.Platforms.Direct2D).Run(new MyForm());
            }
        }
    }

**Comment by cwensley** [comment]
Thanks for the bug report and repro!  It should hopefully be fixed now.  Cheers!
