### ISSUE TITLE
anyone can conversion the ext.Notebook component to Eto.forms?

### ISSUE THREAD

**Issue by rakuten** [picoe/Eto#379]
![2015-09-09 7 03 43](https://cloud.githubusercontent.com/assets/165917/9760189/904303d4-5725-11e5-85f6-fc03032e03b1.png)

https://github.com/mono/xwt/blob/master/Xwt/Xwt/Notebook.cs

**Comment by cwensley** [comment]
You're looking for the [TabControl](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/Controls/TabControl.cs).  

It does not yet support having the tabs at the bottom, but that would be trivial to add support for.

**Comment by rakuten** [comment]
cwensley, Thank you for replying.

Yes, i know the TabControl, but on MacOS side, it is show on middl,

I hope it can be left-aligned  and a close button on each tab button.

I found XWT just have this feature, and support for multi-platform,

But I was a C # novice......

**Comment by cwensley** [comment]
Ah, you're looking more for something that can be used as an MDI?  OS X unfortunately doesn't have that capability built in (as an API).  I've just committed a [change](cdda9a742223b705ae3b9635c715718be54bd81a) to at least allow you to change the position of the tabs, but it won't get you everything you want.

Also, as far as I can tell, XWT also uses the native NSTabView on Mac (so they would show centered as well) and it does not support close buttons either.

To get a different style of TabControl for OS X, you'd have to do something like [this](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Handlers/TabControlHandler.cs) to theme the TabControl.  This way you can make the tabs appear however you want.

Ideally, I'd like to either extend the TabControl or add a new TabBar that works similarly to typical browser tabs for this purpose, which is tracked with issue #21.  This is unfortunately not on my radar at the moment though.

**Comment by rakuten** [comment]
thanks @cwensley,

I have to see your commit,

 but I think maybe use gtk is a better choice rather than monomac for me ....

Anyway, the last commit(cdda9a7) is great job,  thank you very much^^

**Comment by rakuten** [comment]
hi @cwensley,

when i looking for mlnodevelop (it is running on multi-platform right?), it have this feature, and is open source, base on gtk and Cairo)
![2015-09-10 6 08 02](https://cloud.githubusercontent.com/assets/165917/9785780/52483d5c-57e7-11e5-8fea-cb2c6234f478.png)
https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/TabLabel.cs

https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs

and at MacOS side, i found this one
https://github.com/MiMo42/MMTabBarView

more help or anything we can do?.....

**Comment by cwensley** [comment]
Closing this as I believe it is tracked appropriately with #21.
