### ISSUE TITLE
Hiding a SplitterPanel on OSX

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#380]
Hi Curtis, 

What is the best way to toggle visibility of a SplitterPanel?

Expected behaviour when hiding a panel is that the other panel would expand to fill the full space of the Splitter.

e.g.:
Splitter.Panel1.Visible=false  -> Panel1 hides and Panel2 expands using the whole space of the Splitter.

But this only works on WinForm, not on OSX. On OSX Panel1 is hiding, but Panel2 is not resizing to use the whole space.

Is there another way to do this on OSX? 

Tom

**Comment by cwensley** [comment]
Hi, thanks for submitting the issue!  Sorry, I saw your post on the forum but didn't get around to answering it yet.

The Splitter doesn't currently have the behaviour you describe, but I think it'd be great to have support for that scenario.

Currently your only option would be to set the splitter position manually when hiding a panel.

**Comment by cwensley** [comment]
Thanks again for the suggestion!  This is now implemented in the develop branch.  Give it a try and let me know if you run into any problems.

**Comment by TomQv** [comment]
Hi Curtis, sorry for coming back only now. Just tried eto.mac 2.2.0. Is this the develop branch? Its what I get when selecting "pre-release" in Add package. 
Anyway, its better, When I set Splitter.Panel.Visible=false, its working as expected. The panel disappears and the rest is resizing correctly. 
But when I set Visible=true the view is not refreshed, nothing is happening, only when resizing the form manually and then sometimes the panels doesn't have their expected size.
Only Mac, Winform works perfect.
Tom

**Comment by cwensley** [comment]
Hi @TomQv, to use the develop branch nuget assemblies, you have to add the https://www.myget.org/F/eto/ nuget package source.  You can do this through Tools > Options > Nuget Package Manager > Package Sources in VS, then yes you'll have to check pre-release to install the latest build.

**Comment by TomQv** [comment]
ok, but just Eto.Forms.Xamarin.Mac (unified)  (XamMac2) is missing in the list. 
All others are there in 2.2.0-build0514.

**Comment by TomQv** [comment]
Hi Curtis,

can you please also add Eto.XamMac2 to the develop branch?
Or is there a reason, why this is the only platform missing and only available 
in the release-branch?

Thanks and best regards,
Tom



Am 09.04.2016 um 18:03 schrieb Curtis Wensley:
> Hi @TomQv <https://github.com/TomQv>, to use the develop branch nuget
> assemblies, you have to add the https://www.myget.org/F/eto/ nuget package
> source. You can do this through Tools > Options > Nuget Package Manager >
> Package Sources in VS, then yes you'll have to check pre-release to install
> the latest build.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/picoe/Eto/issues/380#issuecomment-207818176>
>

-- 
/****************************************
**   Flemming Software Development CC
**   Thomas Flemming
**   PO Box 81244
**   Windhoek, Namibia
**   http://www.quovadis-gps.com
**   mail  tf@qvgps.com
**   +264 (0)81 3329923
**   +49  (0)6182 8492599
***************************************/

**Comment by cwensley** [comment]
Hey @TomQv, sorry but the develop branch is compiled by AppVeyor which does not support compiling Xamarin.Mac solutions, since it requires a Mac to do that.  Hopefully with Xamarin.Mac being open sourced it will make it easier to get it integrated.

That being said, I should have looked at the issue history more closely, these fixes did indeed land in 2.2 and you shouldn't need to use the develop branch anymore.  If you can put together a little repro of your problem, I can take a look.

Thanks!
Curtis.

**Comment by TomQv** [comment]
Hi Curtis,

it looks like an exception in the mac-splitterhandler.

I receive the attached error in output-window, when I set 
Splitter.Panel.Visible=false.

Splitter.Panel.Visible=True is fine, works as expected.

Thanks
Tom



Am 11.04.2016 um 15:34 schrieb Curtis Wensley:
> Hey @TomQv <https://github.com/TomQv>, sorry but the develop branch is
> compiled by AppVeyor which does not support compiling Xamarin.Mac solutions,
> since it requires a Mac to do that. Hopefully with Xamarin.Mac being open
> sourced it will make it easier to get it integrated.
>
> That being said, I should have looked at the issue history more closely, these
> fixes did indeed land in 2.2 and you shouldn't need to use the develop branch
> anymore. If you can put together a little repro of your problem, I can take a
> look.
>
> Thanks!
> Curtis.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/picoe/Eto/issues/380#issuecomment-208376821>
>

-- 
/****************************************
**   Flemming Software Development CC
**   Thomas Flemming
**   PO Box 81244
**   Windhoek, Namibia
**   http://www.quovadis-gps.com
**   mail  tf@qvgps.com
**   +264 (0)81 3329923
**   +49  (0)6182 8492599
***************************************/

2016-04-12 12:40:00.750 QvxMac[615:26108] <Eto_Mac_Forms_Controls_SplitterHandler_EtoSplitView: 0x600000129920>: the delegate <Eto_Mac_Forms_Controls_SplitterHandler_EtoSplitViewDelegate: 0x60000021ffb0> was sent -splitView:resizeSubviewsWithOldSize: and left the subview frames in an inconsistent state:
2016-04-12 12:40:00.753 QvxMac[615:26108] Split view bounds: {{0, 0}, {1322, 850}}
2016-04-12 12:40:00.756 QvxMac[615:26108]     Subview frame: {{0, 0}, {0, 0}}
2016-04-12 12:40:00.756 QvxMac[615:26108]     Subview frame: {{0, 20}, {1322, 850}}
2016-04-12 12:40:00.757 QvxMac[615:26108] The outer edges of the subview frames are supposed to line up with the split view's bounds' edges. NSSplitView is working around the problem, perhaps at the cost of more redrawing. (This message is only logged once per NSSplitView.)
