### ISSUE TITLE
WinForms Bitmap scaling

### ISSUE THREAD

**Issue by oliverdarvall** [picoe/Eto#383]
Build 0359 Pre-release:

		Stream ss = new StreamReader("Resources\\SaveShots.gif").BaseStream;
		button.Image = new Bitmap(new Eto.Drawing.Bitmap(ss), 14, 14);

Above code works perfectly on WPF/GTK2

On WinForms the resultant image is corrupted

**Comment by cwensley** [comment]
Thanks for the report, though I can't seem to reproduce this.  Perhaps something to do with the particular .gif you are using?   What does it look like before/after?

**Comment by oliverdarvall** [comment]
I will retry it with a few bmp/jpgs also and let you know.

**Comment by oliverdarvall** [comment]
See my test code below. Only btn3 display correctly.

		public MainForm()
		{
			Maximizable = false;
			BackgroundColor = new Color(1, 1, 1);

			Stream stream = new StreamReader("Resources\\btn1.gif").BaseStream;

			Button btn1 = new Button();
			btn1.Image = new Bitmap(new Bitmap(stream), 14, 14);

			Button btn2 = new Button();
			btn2.Image = new Bitmap(new Bitmap(stream));

			Button btn3 = new Button();
			btn3.Image = new Bitmap(stream);

			Content = new TableLayout()
			{
				Rows =
				{
					btn1,
					btn2,
					btn3
				}
			};
		}

![btn1](https://cloud.githubusercontent.com/assets/14215650/9848123/840c0608-5ade-11e5-9bc3-c73b42ff657d.gif)

**Comment by cwensley** [comment]
Thanks again for the detailed info!  Hopefully this is now fixed for you.
