### ISSUE TITLE
WPF: Delete and CTRL-C shortcuts doesn't work when GridView is focused

### ISSUE THREAD

**Issue by JosefNemec** [picoe/Eto#384]
So this is really weird, I have menu items with global shortcuts for all standard edit commands (Ctrl-C, Ctrl-X, Ctrl-V and Delete). They seems to work fine, except when GridView control has focus. Only Ctrl-X and Ctrl-V works in that case, while Delete and Ctrl-C shortcuts are being ignored.

Using latest develop branch.

**Comment by JosefNemec** [comment]
Did some research about this and it seems to be DataGrid feature:
http://stackoverflow.com/questions/26293133/ctrl-c-is-not-detected-in-wpf-datagrid

I'm currently working around this by using custom style and handling PreviewKeyUp manually, but having this solved in Eto globally would be preferred solution.

**Comment by cwensley** [comment]
I just *love* controls that have intrinsic keyboard shortcuts that get buried even though they do nothing.. seems windows forms and wpf love to do this, though it should be fairly easy to get around it.  Thanks for reporting the issue!
