### ISSUE TITLE
ArgumentOutOfRangeException on Mac when removing item from GridView's DataStore

### ISSUE THREAD

**Issue by oliverdarvall** [picoe/Eto#387]
MonoMac application in Xamarin: Click on the Crash button to see the System.ArgumentOutOfRangeException thrown.

From what I can see in the call stack things go pear shaped in Eto.Mac.Forms.Controls.GridViewHandler.EtoTableViewDataSource where a wrong row value is passed in.

using System;
using Eto.Forms;
using Eto.Drawing;
using System.Collections.ObjectModel;

namespace Test
{
	public class Item
	{
		public string Number { get; set; }
	}

	public class MainForm : Form
	{
		public ObservableCollection<Item> Items { get; private set; }

		GridView _itemsGrid;

		public MainForm()
		{
			Items = new ObservableCollection<Item>();

			Items.Add (new Item () { Number="1"});
			Items.Add (new Item () { Number="2"});
			Items.Add (new Item () { Number="3"});

			_itemsGrid = new GridView();

			_itemsGrid.Columns.Add(new GridColumn() { HeaderText = "", DataCell = new TextBoxCell() { Binding = Binding.Property<Item, string>(s => s.Number) }, Editable = false });

			_itemsGrid.DataStore = Items;

			Button crash1 = new Button () { Text= "Crash"};
			crash1.Click += Crash1_Click;

			Content = new TableLayout(_itemsGrid, crash1);
		}

		void Crash1_Click (object sender, EventArgs e)
		{
			Item item = Items [1];
			Items.Remove (item);
		}
	}
}

**Comment by cwensley** [comment]
Thanks for the bug report and the repro!  I'll take a look.

**Comment by cwensley** [comment]
Hm, this appears to be fixed in the develop branch, could you give that a try?

**Comment by cwensley** [comment]
Closing as this does appear to be fixed.  Let me know if you are still running into the issue with the develop branch and I'll re-open.  Thanks for the report!
