### ISSUE TITLE
Visual Studio Addin fails to load - can't find right assembly

### ISSUE THREAD

**Issue by rmunn** [picoe/Eto#389]
On Visual Studio 2013, Update 5, the Eto.Forms Visual Studio Addin appears to install correctly. But when I try to create a new Eto.Forms project, I get  an error. The exact error depends on whether I tried to create an Eto App or an Eto Library. If I create an app, I get a message box that says:

>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

If I try to create a library instead, the message box says:

>The 'EtoPreviewPackage' did not load correctly. The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\Robin\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml'.

The relevant error message in the ActivityLog.xml file is precisely the same as what I get when I try to create an app:
>"Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

I did a bit of Googling and found that this error has come up before in a different project:

https://github.com/VioletGiraffe/cppcheck-vs-addin/issues/138

However, the problem in their case appeared to be an incorrect version dependency on Microsoft.VisualStudio.Shell.11.0, which should have been Microsoft.VisualStudio.Shell.12.0. That doesn't appear to be the problem here.

I'll keep looking into this, and update this issue if/when I find out more.

**Comment by cwensley** [comment]
Thanks for reporting the problem!  I guess it runs on my machine because I have both VS 2015 and 2013 installed.  I'll have to try a clean install with only 2013 to make sure it works.  I don't think I depend on anything specific on 2015 so removing the reverences might work.

**Comment by cwensley** [comment]
Ok, I've re-built the plugin and 2.1.0.4 should work for VS 2013 without 2015 installed.  Give it a go!

**Comment by rmunn** [comment]
Confirm: 2.1.0.4 is working fine in VS 2013 without 2015 installed. Thanks for the quick response!

**Comment by christheenchanter** [comment]
@rmunn What did you do to fix it? i think @VioletGiraffe could use your help with [Her/His CppCheck plugin](https://github.com/VioletGiraffe/cppcheck-vs-addin/issues/142). Thanks in advanced.

**Comment by rmunn** [comment]
@christheenchanter I didn't do anything, just reinstalled the plugin after Curtis Wensley rebuilt version 2.1.0.4. He's the one you should ping for help with the CppCheck plugin; I don't have the knowledge to help you with it.

**Comment by VioletGiraffe** [comment]
I simply don't understand this issue, sorry. And I don't get it on any pf my 3 machines at the moment.

**Comment by christheenchanter** [comment]
Thanks for the quick replies guys. @VioletGiraffe i dont think you you necessarily need to know what this specific issue is, rather just whatever the maintainer did to fix it. Unless you think it's a waste of your time, in which case sorry for bothering you. If not should we move this conversation elsewhere?
