### ISSUE TITLE
Toolbar Mac XCode-style

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#390]
Hi Curtis, I'm wondering, if it might be possible to have a toolbar in Mac similar to how it looks in XCode.
Currently we can only have one toolbar in the main-window, but for some use-cases it would be useful to have these nice and slim toolbars like XCode has it even in sub-views in addition to the main-toolbar.
Tom

**Comment by cwensley** [comment]
You can do this currently with a style in your startup mac app, before running your application:

```c#
// In Xamarin.Mac:
Eto.Style.Add<Eto.Mac.Forms.FormHandler>("unified", h => h.Control.TitleVisibility = NSWindowTitleVisibility.Hidden);

// For MonoMac, since the TitleVisibility api hasn't been bound yet: 
Eto.Style.Add<Eto.Mac.Forms.FormHandler>("unified", h => {
	MonoMac.ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(h.Control.Handle, MonoMac.ObjCRuntime.Selector.GetHandle("setTitleVisibility:"), (IntPtr)1);
});
```

then just set `myWindow.Style = "unified"` to any form you want to have a unified toolbar.

**Comment by TomQv** [comment]
ok, this looks much better. Seems like this Style-feature is very powerful.

btw. is there a way to add other controls to the toolbar, like e.g. a SearchBox?
Can I group some toolbar-buttons so that they are rendered without a gap in between? 

Tom

**Comment by cwensley** [comment]
Hey Tom,

There's no way to put a search box on the toolbar just yet.  This should be doable with a new CustomToolItem that I'd like to implement (issue #32). It's been outstanding for a while - I should really get to that.  The more I hear of it bumps it up in priority though so I'll see if I can get to that soon (if no one else does).

As for grouping buttons on a toolbar, that will require a new control unless you want to implement your own [custom platform control](https://github.com/picoe/Eto/wiki/Custom-Platform-Controls). However, this will probably appear on my priority list fairly soon as I'll be needing this type of control as well.

**Comment by cra0zy** [comment]
Gtk 3 has something similar called HeaderBar:
![HeaderBar](http://www.manpagez.com/html/gtk/gtk-3.12.0/getting-started-app10.png)

**Comment by TomQv** [comment]
any news on this? 
grouping buttons? 
put a search box on the toolbar ?

**Comment by cwensley** [comment]
This issue itself appears to be resolved using the style supplied.

Grouping buttons is reported with #889 
Search box on toolbar is reported with #32
