### ISSUE TITLE
JSON Serialization: Preview pane works but actual code fails

### ISSUE THREAD

**Issue by rmunn** [picoe/Eto#393]
When I try to use padding or spacing in a TableLayout, the preview pane handles it but the actual code that loads the JSON is failing. I'm using version 2.1.0.4 of the Visual Studio Addin.

My Panel1.jeto file (I changed it to be a Form, but haven't bothered to change the filename since it's just a test project) looks like this:

```
{
    "$type": "Form",
    "Title": "My Form",

    "Content": {
        "$type": "TableLayout",
//        "Padding": "10",
//        "Spacing": "15,10",
        "Rows": [
            // ... snip contents that are working just fine
        ]
    }
}
```

Note how I've commented out the "Padding" and "Spacing" lines. (BTW, I appreciate the ability to put comments in .jeto files. It's not standard JSON according to the official spec, but I'm glad it's available here.) If I uncomment them, the Preview pane shows correct padding and spacing, but loading the actual file fails. Here's my F# code that loads the file:

```
namespace EtoApp1

open System
open Eto.Forms
open Eto.Drawing
open Eto.Serialization.Json

type Panel1 () as this =
    inherit Form ()

    do
        JsonReader.Load(this, "Panel1.jeto")
    // ... Rest of code is member functions to handle button events
```

Basically, I'm just using the template-generated code. I've made a few changes to it, but I don't think the part I just quoted has any changes at all from the template-generated code. (Again, I've called the class a Panel but it's really inheriting from Form; in a real project I'd use proper names, but I haven't bothered to change the names in this test project).

If I leave the "Padding" and "Spacing" lines commented out, my test Form (two Labels and two Buttons in a TableLayout) loads just fine. But when I uncomment them, even though the preview shows me what I want, running it gets this exception:

```
JsonSerializationException was unhandled

An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll

Additional information: Error converting value "10" to type 'Eto.Drawing.Padding'. Path 'Content.Padding', line 7, position 24.
```

Or:

```
Additional information: Error converting value "15,10" to type 'Eto.Drawing.Size'. Path 'Content.Spacing', line 8, position 27.
```

Clearly, something is different between the Preview pane code from the VS addin, and the actual JSON-loading code in the actual Eto library.

**Comment by cwensley** [comment]
Hm, this might be the difference between the PCL version of Eto.Serialization.Json vs net45.  What type of solution is your library?  You can try adding Eto.Serialization.Json to your startup project to see if it fixes your issue..

**Comment by rmunn** [comment]
I'm too busy this week to give this the attention it needs, but I suspect you're right: something very similar happened to me with Eto.Serialization.Xaml, which I eventually tracked down. When I created my test app, the EtoApp1.Desktop project was created targeting .Net Framework 4.5, but the EtoApp1 project was created targeting .Net Framework 4.0. The Eto.Serialization.Xaml reference went into the EtoApp1 project (since that's where the GUI windows lived), and so when Visual Studio downloaded it for me, it targeted .Net Framework 4.0, and gave me a very similar error about not being able to convert a string to a Padding object.

When I uninstalled Eto.Serialization.Xaml and reinstalled it targeting 4.5 instead of 4.0, everything worked. I suspect this is my problem with Json as well, but I won't be able to verify that until next week. At that point, I'll close the issue if my problem is indeed solved.

**Comment by cwensley** [comment]
Ah, that helps knowing the target framework.. I'll try it on my side with .net 4.0 as well and let you know what I find.  Thanks!

**Comment by cwensley** [comment]
Looking into this further, it seems Newtonsoft.Json works differently when used from F#.  I'm not sure how to fix this yet, but right now it seems like a problem in that library when dealing with base classes that are not themselves F#

**Comment by cwensley** [comment]
Thanks again for reporting!  Just to note that this happened because when creating your project for .NET 4.0, it would actually create the .Desktop project in .net 4.5. 

so, since the Eto.Serialization.Json is only referenced from the .net 4.0 library, it wouldn't work with the .net 4.5 version of Eto.dll used from the Desktop project.

You can fix this by either adding Eto.Serialization.Json to the Desktop (so it would use the .net 4.5 version), or downgrade the .Desktop project to .net 4.0 and re-add the Eto nuget packages.
