### ISSUE TITLE
Mac: Setting Visible triggers Closing event

### ISSUE THREAD

**Issue by oliverdarvall** [picoe/Eto#397]
Eto.Forms version 2.1 on MacOS Mavericks ...

When I set a form's Visibility property to false it fires a Closing event.

(What I am trying to do is to prevent a form from closing by just hiding it:
			Closing += (s, ea) =>
			{
				ea.Cancel = true;
				Visible = false;
			};
When the Visible property is set, it triggers another Closing event. Eventually the app crashes with a stack problem.
)

**Comment by cwensley** [comment]
Ah thanks for submitting the issue!  I'll take a look.

**Comment by cwensley** [comment]
Thanks again!  This should now be fixed in the develop branch.
