### ISSUE TITLE
Suggestion: JSON and XAML serializations should create dictionary of child controls by ID

### ISSUE THREAD

**Issue by rmunn** [picoe/Eto#401]
Several times as I've been writing Eto code in F# to test, I've come across a situation where I wanted to load a dialog/panel/form/whatever from JSON or XAML, then get access to one of its child controls later in an event handler. (For example, when a button is pressed, I want to change the text or color of a label).

When creating an Eto control the "classic" way, through code, that's easy: the code is creating the objects, so all I have to do is save the label in `this.MyChangeableLabel` when it's created, and then I can access that object from the button's event handler.

However, when loading from a JSON or XAML file, I don't know how to easily find the label named "MyChangeableLabel". (I have, of course, set its ID to that name in the JSON or XAML file.) I could take my parent control and iterate through its `Children` property, looking for the one whose `ID` property matches the name I want. It would be a pretty simple function; stick it in an EtoUtils class and call it a day, right? But that seems like something the Eto library should be doing for me, rather than something I should have to do for myself. After all, the Xaml serializer is already building the `NameScope.registeredNames` dictionary, so it should be pretty simple to return that dictionary to the user if they ask for it (perhaps with a `XamlReader.Load()` overload that has an extra `out` parameter). And the JSON serializer has the `idprop` variable in the guts of `EtoContractResolver.CreateProperties`. It could be used to build a name->object dictionary too, which could be optionally returned to the user.

Another reason to do this is that currently, the API has a curious asymmetry. `Eto.Forms.Control` descendants (which is just about every Eto object) have a `FindParent(String)` method to find a control in the *parent* hierarchy with a given ID. But there is no corresponding `FindChild(String)` method (and neither are there `FindChild(Type, String)` or `FindChild<T>(String)` methods). Why? Is it because those methods would be impossible to implement on at least one of the platforms Eto supports? Or is it just because that was an oversight, and a `FindChild(string)` method (and its two other versions that search by type) would be easy?

**Comment by cwensley** [comment]
There's no reason `Container.FindChild()` isn't implemented.  You can do this currently by using `Container.Children` like so: 

 ```c#
var myControl = myContainer.Children.OfType<TextBox>().FirstOrDefault(r => r.ID == "someID")
````

Adding FindChild helper methods as you suggest would certainly help make that more discoverable and easier to use.

That being said, there is a better way to do this when using xaml or json.  In your backing class, just add a property or field with the same name as the ID in xaml/json and it will be populated with the instance that was created during deserialization.  This is shown in the tests for [xaml](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Serialization/Xaml/Test.cs#L33-L34) and [json](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Serialization/Json/Test.cs#L10-L12).

**Comment by rmunn** [comment]
> In your backing class, just add a property or field with the same name as the ID in xaml/json and it will be populated with the instance that was created during deserialization. This is shown in the tests for [xaml][1]  and [json][2].

[1]: https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Serialization/Xaml/Test.cs#L33-L34
[2]: https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Serialization/Json/Test.cs#L10-L12

Ah, good to know. I had checked the source, but hadn't thought of checking the tests for usage examples!

However, I'm not quite ready to close this issue yet, because while the tests show me how to do it in C#, I can't seem to make it work in F#, and I don't know why. I set up a form with the following JSON:

```
{
    "$type": "Form",
    "Title": "My Form",

	"Content": {
        "$type": "TableLayout",
        "Padding": "5",
        "Spacing": "15, 10",
        "Rows" : [
            [ { }, { }], 
            { "$type": "Label", "ID": "ChangeThisLabel", "Text": "Hello world" },
            { "$type": "Button", "ID": "ChangeButton", "Text": "Change text", "Click": "ChangeClickHandler" },
            { }
        ]
    }
}
```

And then run it like so:

```
namespace EtoApp1

open System
open Eto.Forms
open Eto.Drawing
open Eto.Serialization.Json

type FormWithProperties () as this =
    inherit Form ()

    let mutable ChangeThisLabel : Label = null

    do
        JsonReader.Load(this, "FormWithProperties.jeto")
        
    member this.ChangeClickHandler (source : Object, e : EventArgs) = 
        ChangeThisLabel.Text <- "I got changed"
```

I've also tried making `ChangeThisLabel` a property rather than a mutable field, all with no success. No matter what I do, when I click the button, I still get a NullReferenceException because `ChangeThisLabel` hasn't been set to the loaded label and is still `null`.

It might be that this is something dead simple that I'm doing wrong, since I'm not yet an experienced F# coder. Or I could just be running into some difference between F# and C# that's making `Type.GetRuntimeFields()` not find the `ChangeThisLabel` field.

Once I'm able to get this sample code working, I'll be able to close this issue, because I'll have what I need: the ability to declare a widget in JSON and access it from F#. If I'm just making some newbie mistake, then there's no bug. But if I'm not making any newbie mistakes, and the cause is that the deserialization code that's supposed to be hooking up to properties or fields isn't working, then we should keep this issue open until that bug is fixed.

**Comment by janno-p** [comment]
As a matter of fact, I was having troubles with exactly same thing yesterday and finally got something working. You should declare `ChangeThisLabel` as property instead of mutable value binding. But that won't be enough since F# doesn't approve `JsonReader.Load` call when initializing the instance of a type (should give some F# specific error when called). To fix that I had to create separate static method to build such forms, so the working sample should look like that (I've tried with XamlReader, hopefully JsonReader works out the same way):

```fsharp
type FormWithProperties () as this =
    inherit Form ()

    member val ChangeThisLabel = Unchecked.defaultof<Label> with get, set

    member this.ChangeClickHandler (source : obj, e : EventArgs) = 
        this.ChangeThisLabel.Text <- "I got changed"

    static member Create () =
        let form = new FormWithProperties()
        JsonReader.Load(form, "FormWithProperties.jeto")
        form
```

Although it forces you to use static member instead of constructor to initialize new form.

If you figure out something better, please share :)

**Comment by rmunn** [comment]
@janno-p - Thanks for the example code! Sadly, when I copied it into my project, it failed: same NullReferenceError when I click the button. I then reimplemented the exact same code you wrote but substituted XAML instead of JSON, and it worked: clicking the button updates the label text as it's supposed to. Apparently there's a difference between how the JSON and XAML are being handled, and I've managed to blunder right into that difference.

------

For the sake of helping track this down, here's the code that failed:

**FormWithProperties.jeto**:
```
{
    "$type": "Form",
    "Title": "My Form",

	"Content": {
        "$type": "TableLayout",
        "Padding": "5",
        "Spacing": "15, 10",
        "Rows" : [
            [ { }, { }], 
            { "$type": "Label", "ID": "ChangeThisLabel", "Text": "Hello world" },
            { "$type": "Button", "ID": "ChangeButton", "Text": "Change text", "Click": "ChangeClickHandler" },
            { }
        ]
    }
}
```

**FormWithProperties.jeto.fs**:
```
namespace EtoApp1

open System
open Eto.Forms
open Eto.Drawing
open Eto.Serialization.Json

type FormWithProperties () as this =
    inherit Form ()

    member val ChangeThisLabel = Unchecked.defaultof<Label> with get, set

    member this.ChangeClickHandler (source : obj, e : EventArgs) = 
        this.ChangeThisLabel.Text <- "I got changed"

    static member Create () =
        let form = new FormWithProperties()
        JsonReader.Load(form, "FormWithProperties.jeto")
        form
```

------

And here's the code that succeeded:

**FormWithProperties2.xeto**:
```
<?xml version="1.0" encoding="UTF-8"?>
<Form
  xmlns="http://schema.picoe.ca/eto.forms" 
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="My Form"
  >
  <TableLayout Padding="5" Spacing="15, 10">
    <TableRow>
      <!-- Empty row with two columns to establish padding -->
      <TableCell/>
      <TableCell/>
    </TableRow>
    <TableRow>
      <TableCell>
        <Label ID="ChangeThisLabel" Text="Hello world"/>
      </TableCell>
    </TableRow>
    <TableRow>
      <TableCell>
        <Button ID="ChangeThisButton" Text="Change me" Click="ChangeClickHandler"/>
      </TableCell>
    </TableRow>
    <TableRow>
    </TableRow>
  </TableLayout>
</Form>
```

**FormWithProperties2.xeto.fs**:
```
namespace EtoApp1

open System
open Eto.Forms
open Eto.Drawing
open Eto.Serialization.Xaml

type FormWithProperties2 () as this =
    inherit Form ()

    member val ChangeThisLabel = Unchecked.defaultof<Label> with get, set

    member this.ChangeClickHandler (source : obj, e : EventArgs) = 
        this.ChangeThisLabel.Text <- "I got changed"

    static member Create () =
        let form = new FormWithProperties2()
        XamlReader.Load(form, "FormWithProperties2.xeto")
        form
```

------

Diff the two F# files, and literally the only differences are `Json` instead of `Xaml` (and `jeto` instead of `xeto`), and the extra `2` in the class name because I had them both in the same project:

```
diff -u FormWithProperties.jeto.fs FormWithProperties2.xeto.fs 
--- FormWithProperties.jeto.fs	2015-10-17 23:01:56.108581035 +0700
+++ FormWithProperties2.xeto.fs	2015-10-17 23:01:43.416328821 +0700
@@ -3,9 +3,9 @@
 open System
 open Eto.Forms
 open Eto.Drawing
-open Eto.Serialization.Json
+open Eto.Serialization.Xaml
 
-type FormWithProperties () as this =
+type FormWithProperties2 () as this =
     inherit Form ()
 
     member val ChangeThisLabel = Unchecked.defaultof<Label> with get, set
@@ -14,6 +14,6 @@
         this.ChangeThisLabel.Text <- "I got changed"
 
     static member Create () =
-        let form = new FormWithProperties()
-        JsonReader.Load(form, "FormWithProperties.jeto")
+        let form = new FormWithProperties2()
+        XamlReader.Load(form, "FormWithProperties2.xeto")
         form
```

So `Eto.Serialization.Xaml` and `Eto.Serialization.Json` are behaving differently with identical examples.

@cwensley - Want me to open a new ticket to track this, since I think we've drifted into a different issue than the one I originally reported?

**Comment by cwensley** [comment]
Hey guys thanks for the detailed analysis.. I've been working on better xaml and json support for the next release so this is perfect timing for these issues to be reported.

@rmunn, yeah a different issue would be great.  I'd like to keep this open one to track adding FindChild() methods.

For the json issue, did you try using $name instead of the ID property? This is what the examples use. I'm not sure if the ID property was hooked up the same as xaml where it is both ID and x:Name.

**Comment by rmunn** [comment]
Turns out that using `$name` in the JSON worked, and my problems went away. I'm still going to open a new issue as you requested, since the difference between `ID` in XAML and `$name` in JSON is surprising and non-intuitive, and should probably be fixed. But I'm now able to do what I need thanks to your mentioning that `$name` is what to use for JSON.

**Comment by cwensley** [comment]
@rmunn great, thanks!

**Comment by cwensley** [comment]
by the way, have you guys used newtonsoft.json with F# in mono?  I'm having a heck of a time getting it to even work..

**Comment by rmunn** [comment]
@cwensley - Not yet. My experience so far with Mono has been "Wow, Linux is *such* a second-class citizen so far in the C#/.NET world!" For example, NuGet doesn't appear to work out of the box: in all the projects I've seen so far, the NuGet.targets and NuGet.exe files are spelled exactly like that by default *as files*, but there are references to `nuget.exe` (NOT `NuGet.exe`) in the `NuGet.targets` file. This will work on Windows with its case-insensitive filesystem, but not on Linux's case-sensitive filesystems.

BTW, issue #402 opened now. Turns out there's not a bug, but there *is* a Principle of Least Surprise violation (IMHO anyway), so it's worth tracking as an issue. And @janno-p - I discovered that you *can* use fields just as well as properties. I put example code into issue #402. @cwensley or anyone else interested, feel free to take that sample code and put it on the Wiki. (I might do that myself if I find the time, but I can't make any promises).

**Comment by cwensley** [comment]
@rmunn I haven't had too many issues with nuget on mono these days.. The `NuGet.targets` is the 'old' way of doing package restore so few projects do that now.  That being said, Eto.Forms uses a fairly customized version of NuGet.targets so that it restores the packages to the right location when referencing the project files from other solutions.

I found out why it isn't working for me, it turns out it's because I updated to Newtonsoft.Json 7.0.1, which even on windows, doesn't work.  Looks like I'll revert back to Newtonsoft.Json 6.x for now.

**Comment by janno-p** [comment]
Would that `FindChild` helper work similarily to WPFs [FrameworkElement.FindName](https://msdn.microsoft.com/en-us/library/system.windows.frameworkelement.findname(v=vs.110).aspx)

Current option (`Container.Children`), makes very difficult to walk through and search correct element recursively, because containment can be different (`Children`, layouts have `Items`, `Rows` etc.)

**Comment by cwensley** [comment]
@janno-p Children returns all child controls, even on `TableLayout`, `StackLayout`, `DynamicLayout`, etc.  Since it is a property of the `Container` class, it is implemented for each container to return all of its controls and their child controls.

So, you don't need to look at `Items`, `Rows`, etc to find all children of a container.

The `FindChild` as I envision it would work pretty much identically as WPF's FindName though you will also be able to find by type if desired.

**Comment by cwensley** [comment]
basically, this is what will be implemented (working on it now): 

```C#
public T FindChild<T>(string id = null)
	where T: Control
{
	if (string.IsNullOrEmpty(id))
		return Children.OfType<T>().FirstOrDefault();
	else
		return Children.OfType<T>().FirstOrDefault(r => r.ID == id);
}

public Control FindChild(Type type, string id = null)
{
	if (id == null)
		throw new ArgumentNullException("type", "Type must not be null");
	if (string.IsNullOrEmpty(id))
		return Children.FirstOrDefault(r => type.IsInstanceOfType(r));
	else
		return Children.FirstOrDefault(r => type.IsInstanceOfType(r) && r.ID == id);
}

public Control FindChild(string id)
{
	if (id == null)
		throw new ArgumentNullException("id", "ID must not be null");
	return Children.FirstOrDefault(r => r.ID == id);
}
```

**Comment by janno-p** [comment]
Ok. Looking at the source of `Container` class, everything should be in order as promised. I have to check, because it seems that my current case does not get expected results (children of children are not returned, which is the cause of my confusion. I thought that it's up to me to find them manually.)

I'll recheck and create separate detailed issue, if I should discover something.

**Comment by cwensley** [comment]
@janno-p, yeah please do.  If there's a case where it does not return children of children it would probably be a bug.
