### ISSUE TITLE
Proposition: Children property should be updated during Json/Xaml deserialization

### ISSUE THREAD

**Issue by janno-p** [picoe/Eto#405]
Continuing discussion that started from issue #401:

I am trying to implement custom dialog using XamlLoader, using F# programming language. As discussed in #401, I could use the following implementation to get handles to control instances defined inside Xaml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Dialog xmlns="http://schema.picoe.ca/eto.forms" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="My Dialog">
  <StackLayout Padding="10" Spacing="5">
    <StackLayoutItem Expand="true">
      <DynamicLayout>
        <DynamicRow>
          <DynamicTable Padding="10" Spacing="5,5">
            <DynamicRow>
              <DynamicControl>
                <Label Text="Label" ID="Label1" />
              </DynamicControl>
              <DynamicControl>
                <TextBox ID="TextBox1" />
              </DynamicControl>
            </DynamicRow>
          </DynamicTable>
        </DynamicRow>
      </DynamicLayout>
    </StackLayoutItem>
    <StackLayoutItem>
      <StackLayout Orientation="Horizontal" Spacing="5">
        <Button ID="DefaultButton" Text="OK" Click="ButtonClick" />
      </StackLayout>
    </StackLayoutItem>
  </StackLayout>
</Dialog>
```

```fsharp
type MyDialog () =
    inherit Dialog ()

    // Order is very important 1) define values 2) Load 3) Ready to use

    // No need for mutable, but assignment of null value looks suspicious.
    // I'm forced to use same name as defined inside Xaml file.
    let Label1: Label = null

    do XamlReader.Load(this, "MyDialog.xeto")

    // Can hook up events programmatically
    do Label1.MouseEnter.Add(fun _ -> MessageBox.Show("Yay!") |> ignore)

    member __.ButtonClick(_: obj, _: EventArgs) =
        Label1.Text <- "Text Changed"
```

This approach works, but it's not very natural and causes some confusion when trying to figure out what is going on. I thought it could be done better. Introduction of `FindChild` extension would allow me to locate child control through name. So I tried following:

```fsharp
type MyDialog () as this =
    inherit Dialog ()

    // Only requirement is that loading must be done before accessing controls, which is reasonable
    do XamlReader.Load(this, "MyDialog.xeto")

    // No confusion here, value is initialized to handle of specific control.
    // Can use more conventional value names.
    let label = this.FindChild<Label>("Label1")
    do label.MouseEnter.Add(fun _ -> MessageBox.Show("Yay!") |> ignore)

    member __.ButtonClick(_: obj, _: EventArgs) =
        label.Text <- "Text Changed"
```

Sadly, it doesn't work, because after loading Xaml, Children contains only StackLayout container and other controls are not yet present. So FindChild method fails to locate my Label control.

After some investigation I figured out, that Children are completely populated inside OnPreLoad method, which is by default called when displaying the dialog to user (for example calling ShowModal). The F# code I presented is basically trying to access children inside MyDialog type constructor. In my mind current implementation makes this Children feature little bit awkward since I actually cannot use them before I display the dialog.

I could add call to this.OnPreLoad right after XamlReader.Load myself, which would make this sample work, but that would introduce weird ritual into my dialog initializations and might cause some unknown side-effects somewhere else.

Would it be possible to implement Children collection, so that all controls are present right after the Json or Xaml deserialization? I checked that adding controls on the fly in event handlers updates the Children collection, so why should deserialization work differently?

**Comment by cwensley** [comment]
Thanks for the suggestion!  This was actually implemented before using the ISupportInitialize interface, which would do as you propose.  With PCL/.NET4.5, this interface isn't available so it doesn't get triggered.  I'll take a look at a way to get this re-enabled so that it will work as you expect.
