### ISSUE TITLE
Bitmap from pointer

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#415]
How can I create Bitmap object from an existing pointer (as in System.Drawing.Bitmap) ?

I would like to share data between ImageView and Bitmap without the need to copy bytes.

**Comment by cwensley** [comment]
I'm not sure what you are trying to do here?  Not all platforms can pass around an IntPtr to reference a bitmap like windows, so you have to just use the instance of the Bitmap object in multiple places..

Do you have an example of what you are trying to accomplish?

**Comment by dajuric** [comment]
I am developer of the https://github.com/dajuric/dot-imaging library.

The image is represented as managed array (new Bgr<byte>[240, 320]).. It would be great if I could lock the array and pass it to an ImageView control to avoid data copy. In this case, I could tamper the array and in the same time, the updated information would be available (can be compared to data binding).

**Comment by dajuric** [comment]
The current solution invloved data copy:
     
    public void SetImage(Bgr<byte>[,] image)
        {
            if (bmp == null || bmp.Width != image.Width() || bmp.Height != image.Height())
            {
                bmp = new Bitmap(image.Width(), image.Height(), PixelFormat.Format24bppRgb);
            }

            BitmapData bmpData = bmp.Lock();
            if (bmpData.BytesPerPixel != image.ColorInfo().Size)
            {
                bmpData.Dispose();
                bmp = new Bitmap(image.Width(), image.Height(), PixelFormat.Format24bppRgb);
            }

            using (var uIm = image.Lock())
            {
                bmpData = bmp.Lock();
                Copy.UnsafeCopy2D(uIm.ImageData, bmpData.Data, uIm.Stride, bmpData.ScanWidth, uIm.Height);
                bmpData.Dispose();
            }

            imageView.Image = bmp;

            if (ScaleForm)
                ClientSize = new Size(image.Width(), image.Height());
        }

**Comment by cwensley** [comment]
Ah ok, that makes more sense..  I thought you meant the handle, but you mean the pointer to the data.

Unfortunately, you'd get little benefit on some platforms as they can store their bitmap data in different byte orders (e.g. OS X & GTK have ABGR byte order, WinForms/WPF/Direct2D is ARGB) so it'd have to copy the data (pixel by pixel) anyway..

Also, I haven't investigated but some platforms might not support updating the buffer in the background, so you'd have to re-create the bitmap..

So, I agree it would indeed be nice to have a way to pass the buffer directly, though it may come with a large number of caveats and make it difficult to use correctly in a cross platform way.

The `BitmapData.Translate/GetPixel/SetPixel` methods handle this difference, but I think we need something on the Bitmap and/or BitmapData to at least give you some indication on the byte order as well.

**Comment by dajuric** [comment]
Thank you for the reply. I was not aware of such platform incompatibilities.

**Comment by cwensley** [comment]
any time!  If you still would like having a way to pass a data pointer to the constructor (in the platform specific byte order), it could certainly be looked into.  

Feel free to reopen the issue if you would like that implemented or have any other ideas on how to address this.

**Comment by dajuric** [comment]
Thank you again. So far, consider the issue resolved.
