### ISSUE TITLE
Pen from TextureBrush with Image?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#419]
Hi, wouldit be possible, like in Windows - System.Drawing, to create a pen from a brush? 

var bmp = new Bitmap(new MemoryStream(imagebytesarray));
var brush = new TextureBrush(bmp);
var pen = new Pen( brush, width );

Thanks
Tom

**Comment by cwensley** [comment]
Thanks for the suggestion!  This isn't currently available, but I would like to add support for it.

This may be implemented (at least in some platforms) by way of a new `GraphicsPath.Widen` method so that you can fill a drawn path.

**Comment by cwensley** [comment]
This is actually now supported!  Thanks again for the suggestion.
