### ISSUE TITLE
XS addin hides existing templates

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#423]
Templates under crossplat/app or crossplat/library sometimes get hidden when the addin is loaded.

**Comment by cra0zy** [comment]
3 ideas:

 - Idea #1, setup a condition to check if "app" category exists:

https://github.com/mono/MonoGame/blob/develop/IDE/MonoDevelop/MonoDevelop.MonoGame/MonoDevelop.MonoGame.addin.xml#L79

https://github.com/mono/MonoGame/blob/develop/IDE/MonoDevelop/MonoDevelop.MonoGame/MonoDevelop.MonoGame.addin.xml#L114

https://github.com/mono/MonoGame/blob/develop/IDE/MonoDevelop/MonoDevelop.MonoGame/MonoGameConditions.cs#L7

 - <strike>idea #2, like the one before, except check if the running platform is Linux and let Linux stay broken.... I don't like this one, scratch it</strike>
 - Move the stuff to a new category crossplat/Eto with subcategories App and Library

**Comment by cwensley** [comment]
Ugh, and then we have [this](https://github.com/mono/monodevelop/commit/209960f4c7b11b02301761df9ed808a177726681) to look forward to.. `crossplat` was renamed to `multiplat`.

**Comment by cwensley** [comment]
Should now be fixed.  Thanks for the first suggestion!  It helped me figure out a good way to do this and seems to work really well.  I've tested with XS 5.10.1 on OS X which now the crossplat/library shows all other templates, and on Ubuntu XS 5.10 it also shows the app category.

I'll probably have to do something else when the `crossplat` => `multiplat` rename goes through, but I'll wait until it lands on a release.

**Comment by cra0zy** [comment]
Can you give me the new addin pretty pleaseeee :)

**Comment by cwensley** [comment]
@cra0zy, sorry it took a while (christmas and family stuff and all), however the latest addin is now on addins.monodevelop.com so you can install it from there.  Let me know if you run into any issues!

**Comment by cra0zy** [comment]
> @cra0zy, sorry it took a while (christmas and family stuff and all), however the latest addin is now on addins.monodevelop.com so you can install it from there. Let me know if you run into any issues!

Thanks for the info ^^
