### ISSUE TITLE
FileDialog - filters

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#431]
Hi,

   OpenFileFialog and SaveFileDialog do not display the specified filters (file extensions).
I did that:
   dialog.CurrentFilter = new FileDialogFilter("Image file types", ".png", ".jpg");

Also, dialog.Filters is read-only property (description says otherwise).

**Comment by cwensley** [comment]
Try:

```c#
var dialog = new OpenFileDialog();
dialog.Filters.Add(new FileDialogFilter("Image file types", ".png", ".jpg"));
dialog.Filters.Add(new FileDialogFilter("Documents", ".docx", ".pdf"));

// set current index either way:
dialog.CurrentFilter = dialog.Filters[1];
dialog.CurrentFilterIndex = 1;
```

**Comment by cwensley** [comment]
Hey, I've committed some changes to the documentation of the API to hopefully make it more clear.  If there's any changes/additions you think should be added, please let me know.

Thanks for pointing it out!

**Comment by dajuric** [comment]
Thanks :)
