### ISSUE TITLE
New Eto based library

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#432]
Hi,

  I did not find a contact information, so I am opening a new "issue".
Just wanted to tell you, that you can include another library in your list that is using Eto.Forms:

Take a look at:
https://github.com/dajuric/dot-imaging

or more precisely "DotImaging.UI"

Thank you very much for all the help :)
If something has to be changed, tell me.

Best regards,
Darko

**Comment by cwensley** [comment]
Nice, the library looks great!  Thanks for the link, I'll add it.  I think I may move that section to the wiki to make it easier for people to add.

**Comment by dajuric** [comment]
I just wanted to notify you that DotImaging.UI became DotImaging.UI.Image and it does not use Eto.Forms at least for now because NET Core is not supported by the Eto.Forms (yet).
You may update the README info.
