### ISSUE TITLE
Image loading

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#433]
Hi,

     Bitmap bmp = new Bitmap("out.jpg");

throws the InvalidUriException although the argument is file-name.
Also, why do I have to create an application in order to load the image ?

P.S.
It seems that the following code works:

      var platform = Platform.Detect;
      Bitmap bmp = new Bitmap("C:\\out.jpg");
      bmp.Save("out.bmp", ImageFormat.Bitmap);

But it would be nice if relative paths worked too.

**Comment by cwensley** [comment]
If you do not specify a path when loading a file, then it uses the current working directory (which gets changed when you use OpenFileDialog/SaveFileDialog, etc).  Basically I recommend to always use a full path when loading a file, as the working directory semantics are different on each platform.

You may be able to use `Environment.CurrentDirectory` to set the current directory first, but I have not tested it.

**Comment by dajuric** [comment]
OK. I just compared odrinary WinForms Bitmap loading and the one provided with Eto (WinForms platform I think). Native WinForms loaded the bitmap, but the Eto Bitmap did not suceed to load the file (Uri exception).

But OK, thanks.

**Comment by dajuric** [comment]
P.S.
I needed the extended PictureBox functionality (zoom and translation), so I wrote one residing in the "Components" folder under: https://github.com/dajuric/dot-imaging/tree/master/Source/UI

If you need to update your code or create something new you may "reuse" the source under UI package.

**Comment by cwensley** [comment]
It is probably throwing an exception [here](https://github.com/picoe/Eto/blob/develop/Source/Eto.Wpf/Drawing/BitmapHandler.cs#L55).  WPF requires you to use a Uri when loading a bitmap.  This may be solvable by passing `Environment.CurrentDirectory` as the baseUri, but again that will always be a volatile way of loading resources so I wouldn't recommend it, since the current directory can change while your application is running.

**Comment by dajuric** [comment]
OK. Thank you.
Let me know if you find something interesting in UI section of DotImaging framework (comment above).
