### ISSUE TITLE
Drawable component and keyboard events

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#436]
Hi,
  I inherited a class from Drawable, but I am unable to get the keyboard events (KeyDown, KeyUp, KeyPress) to work (fire). A form is using  only this component.

**Comment by cwensley** [comment]
Make sure you set `myDrawable.CanFocus = true`.  Without it, the control can't receive keyboard/input focus.

**Comment by dajuric** [comment]
Hi, many thanks.
It works now.

But what about the modifier keys (shift, control, alt) - they do not trigger the events ?

Thanks in advance.

**Comment by cwensley** [comment]
No, they do not trigger events.  Only non-modifiers will trigger an event, or a key with a modifier e.g. `Ctrl+C`.

**Comment by dajuric** [comment]
Hi,
  many thanks.
  I am asking you about the modifier keys, because I want to resize an image when I am holding a key and doing an action on my laptop's touchpad. When using a non-modifier key, or a combination, touchpad freezes :)
(probably to prevent accidentally mouse actions during typing)

I was able to to use modifier keys in WinForms (they triggered the events). Do you have a suggestion how to overcome this issue ? 

Thanks.

**Comment by cwensley** [comment]
All mouse operations have a way to access the modifiers using the `MouseEventArgs.Modifiers` property.  So, when you are clicking, moving the mouse, etc, check the Modifiers property to perform different actions based on what modifiers are pressed.

Alternatively, you can check the modifiers at any time using the `Keyboard.Modifiers` static property.

**Comment by dajuric** [comment]
Many, many thanks!

**Comment by cwensley** [comment]
Is this issue now closed for you? Let me know, thanks!

**Comment by dajuric** [comment]
It is closed.
