### ISSUE TITLE
Xaml: Enhance binding markup extension

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#439]
The Binding markup extension needs to be enhanced to support:
- Specifying mode (one way, two way, one time, etc)
- Support IIndirectBinding<T> properties like ComboBox.ItemTextBinding
- Support specifying a converter, possibly similar to how WPF's binding extensions work

**Comment by b-straub** [comment]
> Support IIndirectBinding properties like ComboBox.ItemTextBinding

This can be done e.g. by adding the following code to BindingExtension.ProvideValue

```
if (propertyType.GetGenericTypeDefinition() == typeof(IIndirectBinding<>))
{
	var propertyBaseType = provideValue.TargetObject.GetType().GetBaseType().GenericTypeArguments.FirstOrDefault();
	var propertyMethod = typeof(Binding).GetRuntimeMethod("Property", new[] {typeof(String)});
	return propertyMethod.MakeGenericMethod(propertyBaseType).Invoke(null, new String[] { Path });
}
```

Likely not the most elegant way to do,  my c# skills are a bit lost since forced to do  a lot of c++ nowadays!
