### ISSUE TITLE
Tabcontrol set tab visibility

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#440]
Add a way to make tabs invisible in tabcontrol.

PS. In Gtk you can set tabs invisible with:

``` c#
notebook1.ShowTabs = false;
```

I would also recommend adding:

``` c#
notebook1.ShowBorder = notebook1.ShowTabs ;
```

this will change the background color of notebook to the color of the background and remove the border.

**Comment by cwensley** [comment]
Not at the moment, but it's a good suggestion!  

In the meantime, using your own List<Control> and a Panel works really well.  E.g.

```c#
var myTabs = new List<Control> {
  new Panel { BackgroundColor = Colors.Red },
  new Panel { BackgroundColor = Colors.Green },
  new Panel { BackgroundColor = Colors.Blue }
};

var tabPanel = new Panel { Size = new Size(200, 200) };
tabPanel.Content = myTabs[0];

var myButton = new Button { Text = "Switch to tab 2" };
myButton.Click += (sender, e) => tabPanel.Content = myTabs[1];

// add tabPanel and myButton somewhere
```
