### ISSUE TITLE
Setting Icon in Xaml does not work in designer

### ISSUE THREAD

**Issue by JBildstein** [picoe/Eto#444]
Setting the Icon property of a Form  from a resource in Xaml fails in the Visual Studio designer.
The error says: Cannot convert Bitmap to Icon
It works fine at runtime though and the Icon shows up as it should.

Xaml:
```
<Form Icon="{Resource Resources.Icon.ico, MyAssembly}"></Form>
```
Using Eto 2.2 and Visual Studio 2015

**Comment by cwensley** [comment]
This should now be working with the 2.3 release and the new XS/VS addins.
