### ISSUE TITLE
First approach to eto.form 

### ISSUE THREAD

**Issue by 0vermind** [picoe/Eto#445]
I tried to run some sample project made in VSCommunity edition 2015 on windows 8.1.
The code is from the vs addin if eto.
I can run flawlessly a wfp or win form build but not a gtk2 or gtk3 build.
I have installed gtk# with no result, the app does not start silently. Is this expected?

**Comment by cwensley** [comment]
How did you install GTK# for .NET?  I can install from the package downloaded [here](http://www.mono-project.com/download/#download-win), and the GTK2 app works fine on windows.  Make sure you reboot after installing (;

There is no GTK#3 installer for windows afaik.

**Comment by 0vermind** [comment]
Sorry for the delay.
Yes I've installed from that link. I installed again and  I managed now to run GTKonWindowsTest  and another GTK2App instead of a GTK3.
The GTK2 app crushes a bit frequently http://i.imgur.com/s5gx5P9.png  but I will experiment more with it. :)
Thanks for the great project!

**Comment by 0vermind** [comment]
Sorry for the delay.
Yes I've installed from that link. I installed again and  I managed now to run a GTK2 app fine.
Thanks for the great project!
