### ISSUE TITLE
Drawable with content (e.g. StackLayout) auto-sizing and drawing.

### ISSUE THREAD

**Issue by firda-cze** [picoe/Eto#447]
I am currently trying to port my attendance app (used in our company) for eto (to enable support for mac) and wanted to mimic `ToolStrip` from WinForms by `Drawable` with simple `LinearGradientBrush`, but:

1. Autosizing does not work (both bars appear to be zero height if I set `height = -1`)
2. Drawing works only with Wpf, it probably gets over-painted in WinForms and GTK by the `StackLayout`

![eto-drawable-content](https://cloud.githubusercontent.com/assets/11376520/12536216/2d6ea2aa-c29f-11e5-9fee-7f6d258ee09c.png)

	def bar drawable
		onPaint, e paintEventArgs override protected
			var g = e.Graphics
			var rc = new rectangle point.empty, size
			using var b = new linearGradientBrush(
				color.fromGrayscale(0.8f),
				color.fromGrayscale(0.6f),
				new pointF(0, 0), new pointF(0, height))
				g.fillRectangle b, rc

	.ctor
		....
		content = new stackLayout
			horizontalContentAlignment horizontalAlignment.stretch
			items
				new bar
					size new size -1,30
					content = new stackLayout
						orientation orientation.horizontal
						verticalContentAlignment verticalAlignment.center
						padding new padding 6,2
						spacing 10
						items
							accountLabel
							accountBox
							todayLabel
							todayBox
				new bar
					size new size -1,30
					content = new stackLayout
						orientation orientation.horizontal
						verticalContentAlignment verticalAlignment.center
						padding new padding 6,2
						spacing 10
						items
							dateBox
							timeBox
							nowButton
				new bar
					size new size -1,50

BTW: This is written in my custom language (I call B#) which may look a bit similar to Boo (which appeared dead, but the author returned recently).

P.S.: Also, the `DateTimePicker` with `Time` mode is useless in WinForms and I cannot get rid of the seconds in WPF (I don't want seconds, hours and minutes only)

**Comment by firda-cze** [comment]
And this happens if I try transparent background color under WinForms:
(see the black boxes instead of labels)
![eto-drawable-swf-transparent](https://cloud.githubusercontent.com/assets/11376520/12537346/0fd04c9e-c2bd-11e5-8999-1efa03d21d8c.png)

Does not change the GTK2 version under Windows (did not test it under Linux).

**Comment by firda-cze** [comment]
After few tests and searching, I have probably found a fix of few problems in WPF and WinForms.

![eto-drawable-fix1](https://cloud.githubusercontent.com/assets/11376520/12538658/3ae09f7a-c2df-11e5-9682-5feed1a4d641.png)
...more to come

**Comment by firda-cze** [comment]
![eto-drawable-fix2](https://cloud.githubusercontent.com/assets/11376520/12538986/6bd17330-c2e8-11e5-97e6-b915cf896060.png)

I would personally do the same in PanelHandler ...and return `Padding.Size` in case there is no content.
It could speed things up and prevent problems (and I saw few when autosizing and docking were mixed).

It will require more testing and maybe adding part of the code I found in PanelHandler:

				var userSize = Handler.UserDesiredSize;
				if (userSize.Width >= 0)
					size.Width = Math.Max(userSize.Width, MinimumSize.Width);
				if (userSize.Height >= 0)
					size.Height = Math.Max(userSize.Height, MinimumSize.Height);

**Comment by cwensley** [comment]
Now merged!  Thanks again.  I think this issue is now closed, but feel free to reopen if you think there's more to do.

Cheers!
Curtis.
