### ISSUE TITLE
Gtk TreeGridView SelectedItems only registers first item

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#451]
With Gtk backed, and TreeGridView with multiselect enabled, I am unable to get selected items. The SelectedItems property is in most cases empty, and the only moment that it's not empty is if the tree root node is selected.

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I'll take a look.

**Comment by cra0zy** [comment]
The error is somewhere in either GetRowIndexOfPath or DataStore.

**Comment by cra0zy** [comment]
@cwensley Why didn't you make SelectedItems do the same thing as SelectedItem?

**Comment by cwensley** [comment]
@cra0zy, it looks like `TreeGridView.SelectedItems` was never implemented properly and was just copied from `GridView` four years ago.  It will need a proper implementation, and to be efficient the implementation should probably be moved to the handler.

**Comment by cra0zy** [comment]
> @cra0zy, it looks like TreeGridView.SelectedItems was never implemented properly and was just copied from GridView four years ago. It will need a proper implementation, and to be efficient the implementation should probably be moved to the handler.

That is something that's much easier to do. I can do it for few platforms, what should I do about the rest? Add a NotImplementedException?
