### ISSUE TITLE
Add API to get/set scroll information on scrollable controls

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#453]
2 things:
1) No way to scroll it from within code from what I could tell
2) Gtk and WPF react differently when text is changed, example:

``` c#
public class MainForm : Form
{
    TextBox textBox;
    Button buttonAdd;
    TextArea textView;

    public MainForm ()
    {
        Width = 640;
        Height = 480;

        var dynLayout = new DynamicLayout ();

        textBox = new TextBox ();
        textBox.Text = "Add me to the textbox bellow";
        dynLayout.AddRow (textBox);

        buttonAdd = new Button ();
        buttonAdd.Text = "Add";
        buttonAdd.Click += ButtonAdd_Click;
        dynLayout.AddRow (buttonAdd);

        textView = new TextArea ();
        for (int i = 0; i < 50; i++)
            textView.Text += textBox.Text + Environment.NewLine;
        dynLayout.AddRow (textView);

        Content = dynLayout;
    }

    private void ButtonAdd_Click (object sender, EventArgs e)
    {
        textView.Text += textBox.Text + Environment.NewLine;
    }
}
```

With Gtk every time you add something to the textview, it resets it's scrolling position to 0, with WPF, it just gets added to the textarea.

In order to insert text into a Gtk textarea you have to do something like:

``` c#
var iter = textView1.Buffer.EndIter;
textView1.Buffer.Insert(ref iter, text);
```

instead of:

``` c#
textView1.Buffer.Text += text;
```

**Comment by cwensley** [comment]
Try using the `TextArea.Append(string text, bool scrollToCursor)` method for this.  You should also be able to use the `CaretIndex` property to set the insertion position which would scroll the view to that position.

**Comment by cra0zy** [comment]
> Try using the TextArea.Append(string text, bool scrollToCursor) method for this.

That helps a lot, Thanks.

> You should also be able to use the CaretIndex property to set the insertion position which would scroll the view to that position.

Does not work, plus I wouldn't want to use caret in that way with what I am doing.

What I am trying to do is setup smart scrolling, if textarea is scrolled to the bottom, scroll it more, otherwise don't scroll.

**Comment by cwensley** [comment]
Hm, yeah we'll need to expose the scroll state through new API's to do this as you describe.

I've used the CaretIndex to turn on/off autoscroll if the caret is at the end of the text which seemed to work well, but exposing the scroll state would be great as well.

It'd be nice to use the same api's for any other controls with scrolling areas such as `Scrollable`, `GridView`, etc.  Perhaps by exposing a `ScrollInfo` class through `HorizontalScroll` and `VerticalScroll` properties on each of the controls.

**Comment by cra0zy** [comment]
#661 technically fixed this.
