### ISSUE TITLE
Exception: EtoGridScrollView does not inherit from IMacControl on OS X

### ISSUE THREAD

**Issue by faubulous** [picoe/Eto#455]
On the Mac platform I get an System.ArgumentException anytime when using the TreeGridView.

I have looked into the source code and there are a couple of controls which to not implmenent the IMacControl interface, although they already have a WeakReference which could easily be exposed.

**Comment by cwensley** [comment]
thanks for reporting the issue!  Do you have a snippet of code that causes the exception?  in particular, the event(s) you were trying to hook into.

**Comment by faubulous** [comment]
Dear cwensley,

thanks for your quick reply. I figured out that the problem only occurs if the OnSizeChanged method of the TreeGridView is overridden:

public class MyTreeView : TreeGridView
    {
        private GridColumn _column = new GridColumn();

        public MyTreeView()
        {
            Columns.Add(_column);
        }

        protected override void OnSizeChanged(EventArgs e)
        {
            base.OnSizeChanged(e);
        }
    }

The exception should be thrown when you create an instance of MyTreeView in a form's constructor and set it as the form's Content.

**Comment by cwensley** [comment]
Thanks, this will make sure I test your case explicitly.  I'll do a quick review of the other controls to ensure they are hooked up correctly as well.
