### ISSUE TITLE
OnSizeChanged: Form.Size is {-1,-1} until window resized

### ISSUE THREAD

**Issue by patridge** [picoe/Eto#456]
### Steps

In my main `Form`, I overrode `OnSizeChanged` to see how useful it would be to put any size-based layout logic in there instead of the constructor (and just rely on that firing when the form initially loads as well).

    public  class MainForm : Form
    {
        protected override void OnSizeChanged (EventArgs e)
        {
            base.OnSizeChanged (e);
            var newSize = this.Size;
            Debug.WriteLine("OnSizeChanged: {0}", newSize);
        }
        //…everything else…
    }

Unfortunately, when I watch the Application Output pad, it logs this as the form first loads.

> OnSizeChanged: -1,-1

As soon as I drag a corner of the window, I get `OnSizeChanged` events firing with appropriate size values. It is just those initial events that fire when the size appears to be invalid.

### Desired Outcome

Ideally, the first time `OnSizeChanged` is called is when the form has its initial size set. If it has to fire with `{-1,-1}` initially for whatever reason, I could work around that with a quick `if` check for negative height or width.

I could very easily be misunderstanding the nature of that event since I am completely new to Eto, but I was expecting the initial size values to be set at some point when that event fires as the form loads. If there is some other mechanism I should be using for tying into sizing/layout as it happens in Eto, I'd certainly be open to suggestions as well.

### System

Eto.Forms.XamMac2 (v2.2.0)
Eto.Forms (v2.2.0)
Xamarin Studio (5.10.2)
Mac OS X Yosemite (10.10.5)

**Comment by cwensley** [comment]
Hm, this event is possibly triggered by other toolkits, I'll have to take a look.

Typically, I've done initial size-based layout in the `LoadCompleted` event, such as positioning the form.  However, I agree that it should be fired when the initial size of the form and/or controls is determined.

Thanks for reporting the issue!

**Comment by cwensley** [comment]
@patridge, this should now be fixed.  In my testing it was only the Mac platform that didn't fire this event, but it should now do that when it is auto sized.

This should be very useful for many scenarios to perform logic before the form is shown.  Thanks again for reporting the issue!

**Comment by patridge** [comment]
Thank you so much for fixing it. I was only working on a Mac so far, so I had no idea it was the issue here.

**Comment by cwensley** [comment]
@patridge, not a problem!  I honestly never tried it on other platforms until now, so it's good to get the unit test in for that.
