### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by radhewro** [picoe/Eto#457]
Hi,

is it possible to use Eto.Forms with .NET Core?

**Comment by cwensley** [comment]
Hi,

Since there's no UI framework available for .NET Core, there's no way to get this going unfortunately.  However, I have done some work towards it:

For Mac, I have a [fork of monomac](https://github.com/cwensley/monomac/tree/mac64) that does run on a slightly modified .NET Core runtime (it needs https://github.com/dotnet/corefx/issues/1346 ) it requires `ICustomMarshaler`, but it appears like they do not want to implement this.  I may still invest some time getting this going though depending on interest.

For Windows, the closest UI framework that I've seen run is [mono's Windows Forms](http://forums.dotnetfoundation.org/t/anyone-porting-winforms-mono-to-net-core/898/4), however it is broken and unmaintained to begin with so that's a non starter.

For Linux, the best would be to get GTK# compiled/running under .NET Core.  I have not seen any progress or interest on this yet.

Hope this helps!
Curtis.

**Comment by polgarijog** [comment]
Thank you for your answer - and your work too:)

**Comment by tom-corwin** [comment]
I want to +1 this, and also mention that it seems they are 'planning' to add `ICustomMarshaler` in the 1.2 release of .NET Core.

**Comment by ronnyek** [comment]
Any news at all on this front?

**Comment by cwensley** [comment]
@ronnyek not yet, will still need `ICustomMarshaler` for macOS support which will come with .NET Standard 2.0 support in .NET Core afaik.  GTK will require its bindings compiled for .NET Core (which may be easier with .NET Standard 2.0), and there's still absolutely no way to get a (native) GUI on windows using .NET Core.

**Comment by HinTak** [comment]
quick google'ing, found somebody had started a gtk binding for .NET core 
https://github.com/robertsundstrom/gtk-core

**Comment by cwensley** [comment]
@HinTak excellent find, thanks!  I forgot to mention that @cra0zy's NativeGtk port (when done) may also be usable with .NET Core, which will essentially be the same thing.

**Comment by mzji** [comment]
Since .Net Core 2.0 preview is release, maybe now is the time to do some exploring?

**Comment by cra0zy** [comment]
> Hi! Since .Net Core 2.0 preview is released, maybe now is the time to do some exploration?

No... each backend has a dependency which does not support .net core...

**Comment by mzji** [comment]
@cra0zy AvaloniaUI/Avalonia is a WPF-like .Net Core compatible UI Framework, could this be a backend of Eto?

**Comment by cra0zy** [comment]
> @cra0zy AvaloniaUI/Avalonia is a WPF-like .Net Core compatible UI Framework, could this be a backend of Eto?

That would require a whole new backed and would defeat the purpose of why Eto even exists...

**Comment by feliwir** [comment]
How about this issue nowadays? .NET Standard 2.0 is mature and many libraries support it nowadays

**Comment by cra0zy** [comment]
@feliwir It's WIP: #914

Also I started maintaining my own fork of Gtk# which supports .NET Core: https://github.com/GtkSharp/GtkSharp

**Comment by cwensley** [comment]
Ok, .NET Standard for Eto.dll is in #949

Now we just need to get the platforms to support it.

**Comment by cra0zy** [comment]
Gtk backend is now working with .NET Core: #953

**Comment by cwensley** [comment]
Since WPF and WinForms are now [coming to .NET Core with v3.0](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/), this should eventually be possible on all platforms!

**Comment by dsoronda** [comment]
Just want to comment that Eto works with  Gtk3 (using Eto.Platform.Gtk) on .NET core on Windows and Linux

**Comment by brenthuisman** [comment]
@dsoronda Can I ask what you had to change? I've tried to compile some of the Eto examples/tests with dotnetcore2.2, but that generates errors about .Net assemblies. I tried to correct these by updating the *.csproj files but unsuccessfully so far.

**Comment by meteorsnows** [comment]
.NET 5 is coming. The .NET Core 3. Hopefully future is so bright. Eto Forms be the first one to the train thanks!

**Comment by cwensley** [comment]
Yes, .NET 5 is exciting and awesome!  Eto will still need to ensure compatibility with .NET Framework 4.x, but hopefully we can use multi-targeting to target both net45 and net5.  I think before then, I would still like to support .NET Core 3 when the tooling is more finalized (and I get a bit of time to do it).  

This is a really exciting future that Eto.Forms will fall pretty neatly into imo.

**Comment by fredrikhr** [comment]
Finally got everything set up for getting Eto.WinForms for .NET Core 3.0 in https://github.com/picoe/Eto/pull/1292

I will continue to look into WPF as well, but I imagine that to be fairly easy now since the groundwork for the CI builds is taken care of.
