### ISSUE TITLE
.xeto designer - remember preview/xaml layout

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#458]
If I use the xeto xaml designer and drag the divider between preview and xaml code to show more code and less preview, the designer reverts to the default preview:code ratio after looking at another source file. I need to manually adjust it each time it is shown again.

**Comment by cwensley** [comment]
Thanks for the suggestion!  This would be easy to do if it just remembers it for the running instance.  I'll have to figure out how to save persistent settings in VS and XS to get this going.

I'd also like to add options so you can collapse the preview entirely and/or change its orientation (similar to the wpf designer).

**Comment by mennodeij** [comment]
Remembering in the running instance is perfect; I think the default XAML editor of Visual Studio doesn't remember between sessions either. Addition of collapse/orientation would be a nice addition too.

**Comment by cwensley** [comment]
Now fixed!  The preview will remember the position of the splitter.  Implementing vertical orientation is tracked with issue picoe/Eto.DevExtensions#5 .
