### ISSUE TITLE
xeto clr-namespace, default to own assembly

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#460]
It would be nice to use `xmlns:my="clr-namespace:MyApp.Views"` instead of `xmlns:my="clr-namespace:MyApp.Views;assembly=MyApp"`. 
What I mean is, if the assembly directive is missing, to look in the assembly of the form itself, before bailing.

**Comment by cwensley** [comment]
Good idea, thanks for the suggestion!

I agree this should be done. I haven't looked into whether portable.xaml will need updating for this, but it should be an easy fix regardless. (;
