### ISSUE TITLE
xeto designer - parts of the API documentation are missing in the tooltip

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#461]
All the references in the API documentation, like `<see cref="...">` are missing in the xeto editor in VS2015.

In this specific example, in the last sentence: "use the  constructor", should read "use the RadioButton constructor", as the API docs have <see cref="C:Eto.Forms.RadioButton(RadioButton)"/> in them.

![img_0248](https://cloud.githubusercontent.com/assets/1713187/12947817/623520b0-cffe-11e5-9eb8-b5b99044e44c.PNG)

**Comment by cwensley** [comment]
Thanks for reporting the issue!

I knew about it at the time, but didn't get to fixing it before release. Ideally I'd like to bold the refs so it makes it easier to read. (;
