### ISSUE TITLE
[WPF] Background color of inner DockPanel is set

### ISSUE THREAD

**Issue by steffenWi** [picoe/Eto#465]
Hi,

when a Control is created, two DockPanels are created and one is added as a child to the other DockPanel. The inner DockPanel's Background Color is then set to '_System.Windows.SystemColors.ControlBrush_'. 

For me that's currently a problem, as I've a 'normal' WPF project in which I want to add an Eto Form. I already have styles in place that color WPF controls. I found a few more lines where a BackgroundColor was set hardcoded. I'd like to know if that's really neccessary or if those lines could be removed (which I'll do for now in my local copy)/what the preferred way to manage color based styling is, as I can't find anything on that.

**Comment by cwensley** [comment]
What you can do without modifying Eto is to use styles:

```c#
Style.Add<Eto.Wpf.Forms.FormHandler>(null, handler =>
{
	var main = handler.Control.Content as System.Windows.Controls.Panel;
	var contentPanel = main.Children[3] as System.Windows.Controls.DockPanel;
	contentPanel.ClearValue(System.Windows.Controls.Control.BackgroundProperty);
});
```

I have also just added the `FormHandler.ContentPanel` property to make it easier to do this, so with the develop branch you can simply do:

```c#
Style.Add<Eto.Wpf.Forms.FormHandler>(null, handler =>
{
    handler.ContentPanel.ClearValue(System.Windows.Controls.Control.BackgroundProperty);
});
```

Please let me know if this resolves your issue.  The default background color of the window will most likely stay as is, so this will be your best option.

Hope this helps!
Curtis.

**Comment by cwensley** [comment]
Closing as I assume the answer fixes the problem.  Thanks again for submitting the issue!
