### ISSUE TITLE
[Bug] Defining new XAML Markup Extensions causes exceptions in the XAML Preview

### ISSUE THREAD

**Issue by gjroelofs** [picoe/Eto#466]
Defining a new custom Markup Extension will cause an exception to be thrown by the XAML UI Preview. The Markup Extension can compile & runs correctly.

**How to reproduce**:

Define a custom XAML Markup Extension, e.g.:

```C#
namespace Extensions {
    [MarkupExtensionReturnType(typeof(object))]
    public class BindExtension : MarkupExtension {
          public override object ProvideValue(IServiceProvider serviceProvider) {
            return null;
          }
    }
}
```

And use it in XAML:

```XML
<Form
  xmlns="http://schema.picoe.ca/eto.forms" 
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
  xmlns:e="clr-namespace:Extensions;assembly=Editor"
  Title="Example"
  >
        <TextBox Text="{e:Bind}" />
</Form>
```

**Exception thrown**: `System.ArgumentException: Object of type 'Eto.Serialization.Xaml.DesignerUserControl' cannot be converted to type 'System.String'`

**Comment by cwensley** [comment]
Hm, closed the wrong issue with that commit.  oops!

**Comment by gjroelofs** [comment]
And here I was all excited to try the new release! :D
