### ISSUE TITLE
x86_64 in osx

### ISSUE THREAD

**Issue by observer1** [picoe/Eto#468]
Hi
I need to run my app in osx in x86_64 mode because it uses a dylib compiled for this, I have already installed the universal packages of mono, but it can't load the dylib when I run the launcher.exec file, the dilyb contains gstreamer code and the newest versions of it are only for 64 bits, I tested with an older version for 32 bits and it works fine but I need the latest to fix some bugs
How can I do this

Thanks for your help

**Comment by cwensley** [comment]
Hi @observer1,

Thanks for reporting the issue.  Unfortunately, the only way to use 64-bit with Eto at the moment is to use Xamarin.Mac 2 platform.  The Eto.Platform.Mac.Template currently only provides a 32-bit launcher.

This is on my medium term list to look at, but any help would be appreciated as well.

**Comment by cwensley** [comment]
This is now done!  Eto.Platform.Mac64 now creates a 64 bit .app bundle, which still requires mono to be installed to run.
