### ISSUE TITLE
GridView draws a box inside rows in gtk3 linux

### ISSUE THREAD

**Issue by observer1** [picoe/Eto#469]
Hi
I'm seeing that gridviews and treeviews are drawed with a box above the rows when using gtk3 in linux, inside the box there is a space where you can see the rows but the box covers a big part of the rows.
I have a test case with basically the same program writen in gtk-sharp and the other in eto.forms that shows that the problem is not in gtk-sharp, can I attach the program here?

Thanks for your help

**Comment by cwensley** [comment]
This is a known problem with 2.2 and I believe it has been fixed in the develop branch.  Could you give it a go to see if it resolves your issue?

Thanks!
Curtis.

**Comment by observer1** [comment]
Thanks I downloaded the code from github and it worked

**Comment by cwensley** [comment]
Great, thanks for checking!
