### ISSUE TITLE
Triggering code-completion crashes Visual Studio 2015 with Code Preview open.

### ISSUE THREAD

**Issue by DanWatkins** [picoe/Eto#471]
1) Create a new Eto.Forms Application targeting .NET 4.6 with Form="Code Preview" and SharedCode="Full .NET".

2) Have MainForm.eto.cs open with Code Preview on top and the partial class code below. Start typing "using System." and Visual Studio will crash when pressing ".". 

I presume this is caused because when just "using System" is entered on a line, there is technically a compile error at this point (the preview window even says "Compile error: ; expected). When pressing "." which will trigger auto-completion, Visual Studio then crashes.

The unhandled exception given when choosing "Debug" with VS 2015 is:

_An unhandled exception of type 'System.NullReferenceException' occurred in WindowsBase.dll
Additional information: Object reference not set to an instance of an object._

![autocompletioncrash](https://cloud.githubusercontent.com/assets/1879175/13549634/8644b3c4-e2cf-11e5-8a46-c488b258964e.png)

Environment Information:
Windows 10 x64
Visual Studio Community 2015 Update 1
Eto.Forms Addin 2.2.0.3

**Comment by cwensley** [comment]
Fixed with commit da7693918a4d7ef5ea19d768aa49f45b25e905ef.
