### ISSUE TITLE
MainForm.Eto.cs designer error

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#476]
The designer says:
`Could not find control. Make sure you have a single class derived from control`.

This is from the fresh template.
I am using Visual Studio 2015.

**Comment by cwensley** [comment]
Thanks for the report!  I've seen this before, and it may already be fixed, but I have to do more testing.  I think it was due to the packaging of the addin.

**Comment by AngeloG** [comment]
Can confirm this happening on 2.2.0.3 installed via the extension manager in Visual Studio.

**Comment by fromm666** [comment]
Having the same problem with 2.2.0.3, also installed through the extension manager in VS15.

**Comment by jhorv** [comment]
Same problem, 2.2.0.3 in VS 2015 w/ Update 3.  Seems like it worked several weeks ago, maybe before Update 3?

**Comment by cwensley** [comment]
Hopefully this is now fixed!  I've swapped out the compiler to use Roslyn (to support c#6), and it is also now using an AppDomain to separate out the designer.  Give it a try and let me know how it goes.
