### ISSUE TITLE
set Scrollable.ScrollSize throws exception on Wpf

### ISSUE THREAD

**Issue by gene-l-thomas** [picoe/Eto#480]
Calling the setter on Scrollable.ScrollSize on Wpf throws an InvalidCastException:

```
An unhandled exception of type 'System.InvalidCastException' occurred in Eto.Wpf.dll

Additional information: Unable to cast object of type 'EtoScrollViewer' to type 'System.Windows.Controls.Border'.
```

On WinForms, Gtk3 and Gtk2 the code works as it should.

**Comment by gene-l-thomas** [comment]
The following code exersises the fault on Wpf:
 
 using System;
 using Eto.Forms;
 using Eto;
 using Eto.Drawing;

 namespace etogtkbug
 {
    class MainForm : Form
    {
        ListContentControl ListContent;
        Scrollable Scrollable;

        public class ListContentControl : Drawable
        {
            public ListContentControl()
            {
                Paint += HandlePaint;
            }

            private void HandlePaint(object sender, PaintEventArgs e)
            {
                // coordinates are virtual against this
                // we move this with the SelectedIndex

                Graphics g = e.Graphics;

                g.Clear(SystemColors.WindowBackground);
                g.DrawLine(Colors.Black, 0, 0, 100, 100);
                g.DrawLine(Colors.Black, 100, 0, 0, 100);
            }
        }

        public MainForm()
        {
            ListContent = new ListContentControl();

            Scrollable = new Scrollable()
            {
                Border = BorderType.Line,
                Content = ListContent
            };

            Scrollable.Size = new Size(100, 500);
            ListContent.Size = new Size(100, 1000);
            Scrollable.ScrollSize = new Size(100, 1000);
                // An unhandled exception of type 'System.InvalidCastException' occurred in Eto.Wpf.dll
                // Additional information: Unable to cast object of type 'EtoScrollViewer' to type 'System.Windows.Controls.Border'.

            Content = Scrollable;
        }
    }
    

    public class EtoGtkBug
    {
        [STAThread]
        public static void Main(string[] args)
        {
            Application app = new Application(Platforms.Wpf);
            app.Run(new MainForm());
        }
    }
 }

**Comment by cwensley** [comment]
Thanks for reporting the issue! Shouldn't be too hard to fix but we need tests for this since the scroll size is usually determined automatically.

**Comment by gene-l-thomas** [comment]
The attached .zip file tests the bug.
