### ISSUE TITLE
Can't Create XAML Project

### ISSUE THREAD

**Issue by coldbluelava** [picoe/Eto#481]
I keep getting the following error when trying to create a XAML project:

"An error occurred while retrieving metadata for 'Portable.Xaml.0.6.1' from source https://packages.nuget.org".

Any ideas on what's causing this? I really wanna start learning C#/Xamarin now that Xamarin is free and open source.

**Comment by cwensley** [comment]
Hi @ColdBlueLava, thanks for reporting the issue.  This may be because your nuget package sources don't contain the v2 url. 

To check, edit the `NuGet.Config` file on your machine.  For Visual Studio it's located at `%APPDATA%\NuGet\NuGet.Config`, and Xamarin Studio on Mac or Linux it's `~/.config/NuGet/Nuget.Config`.

It should contain the 'https://www.nuget.org/api/v2/' url as a package source, and not be disabled. e.g:
```xml
<configuration>
  <packageSources>
      <add key="Official NuGet Gallery" value="https://www.nuget.org/api/v2/" />
      <!-- other sources... -->
  </packageSources>
  <disabledPackageSources />
</configuration>
```

**Comment by ColdBlueLava** [comment]
@cwensley - I'm still receiving the error dialog with the added key. I've made sure to restart Visual Studio.

**Comment by cwensley** [comment]
@ColdBlueLava, does nuget work for any other solution under visual studio?  Also, what version of Visual Studio are you using?

Cheers,
Curtis.

**Comment by ColdBlueLava** [comment]
@cwensley - I did some more tests, and the same error appears for the JSON project. I am using Visual Studio 2015 Community. The "About" dialog: Version 14 Update 2.

I can use the "Code" Project without any errors, however the Code Preview says "could not find a control"

**Comment by flyingxu** [comment]
@cwensley I'm have the same issue. I'm using VS 2015 update 2, installed eto.forms project template.
In the project wizard dialog, I select separate assemblies, full .net, and Xaml. but it failed with the same error message as @ColdBlueLava .

After the error message, a solution is created with only 1 project (it should have several projects if I don't use xaml and create the solution successfully.) MainForm.xeto is created, and I can preview it's content.

If I build the solution, in MainForm.xeto.cs, I get an error for code `using Eto.Serialization.Xaml;`
`Error	CS0234	The type or namespace name 'Serialization' does not exist in the namespace 'Eto' (are you missing an assembly reference?)`	
If I use nuget PM console and run `Install-Package Eto.Serialization.Xaml`, Eto.Serialization.Xaml is added to the project successfully and the project compiled OK.

But this is only 1 dll project, I guess there should be a exe (wpf or something else) project be created. How can I work around that?

Fei

**Comment by cwensley** [comment]
Hm, this is definitely something to do with installing the nuget packages, as it installs both **Portable.Xaml** and **Newtonsoft.Json** via the internet whereas the Eto packages are supplied by the addin itself.  

@flyingxu one thing you can try in the meantime is to create a code based project, then add Eto.Serialization.Xaml and a xaml control to it afterwards (which there are file templates for).
