### ISSUE TITLE
Eto.Forms equivalent to Application.DoEvents or Form.Invoke?

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#484]
I could not find a suitable alternative to `Application.DoEvents` or `Form.Invoke` for my multithreaded Eto.Forms application where multiple threads manipulate the UI. Without the use of these in Windows Forms or Eto.Forms, I get an invalid cross-thread operation exception. Does Eto offer an alternative?

**Comment by cwensley** [comment]
Use `Application.Instance.Invoke()` and `Application.Instance.AsyncInvoke()` to invoke actions on the main thread from other threads.  

`Application.Instance.RunIteration()` is equivalent to `DoEvents`, but I do not recommend to use this API as any long-running work should instead be done in background threads or use async/await.

Hope this helps!
Curtis.

**Comment by 0xFireball** [comment]
Thank you!
