### ISSUE TITLE
WPF drawing a bitmap in a separate thread fails

### ISSUE THREAD

**Issue by craigcmiller** [picoe/Eto#485]
The following example fails in WPF but works fine in WinForms. It looks like WPF graphics code running in a separate thread may not work at all.

using System;
using System.Diagnostics;
using Eto;
using Eto.Drawing;
using Eto.Forms;
using System.Threading;
using static System.Console;

namespace CrashTest
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            new Application(Platform.Detect).Run(new MainForm());
        }
    }

    public class MainForm : Form
    {
        public MainForm()
        {
            Title = "Crash Test Form";
            ClientSize = new Size(600, 600);
            Content = new CrashDrawable();
        }
    }
    
    public class CrashDrawable : Drawable
    {
        private readonly Thread _thread;
        private Bitmap _bitmap;

        public CrashDrawable()
        {
            _thread = new Thread(DrawSomething);
        }

        protected override void OnLoadComplete(EventArgs e)
        {
            base.OnLoadComplete(e);

            _thread.Start();
            _thread.Join();

            //DrawSomething();

            Invalidate();
        }

        private void DrawSomething()
        {
            try
            {
                // This line (and all graphics calls) fail in running in a thread
                _bitmap = new Bitmap(600, 600, PixelFormat.Format32bppRgba);

                using (Graphics graphics = new Graphics(_bitmap))
                {
                    graphics.Clear(Colors.LightBlue);

                    graphics.DrawEllipse(Colors.DarkRed, 10f, 10f, _bitmap.Width - 20f, _bitmap.Height - 20f);
                }
            }
            catch (Exception ex)
            {
                WriteLine(ex);
                Debugger.Break();
            }
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            if (_bitmap != null)
                e.Graphics.DrawImage(_bitmap, 0f, 0f);
        }
    }
}

**Comment by cwensley** [comment]
Yeah this is a (very) unfortunate limitation of WPF in that everything (and I mean everything) must be done on the main thread.  Allowing you do do this in a separate thread will only be possible by performing everything on the main thread using Application.Instance.Invoke(), which defeats the purpose.  

That being said, it'd be nice if it would at least work, even though not very efficiently.

**Comment by craigcmiller** [comment]
It does seem to be possible to draw in a separate thread, freeze the render target and then pass it back to the main thread. It would be great if this could be done in Eto.Forms.

        private void DrawInThread()
        {
            Thread thread = new Thread(() =>
            {
                RenderTargetBitmap renderTargetBitmap = new RenderTargetBitmap(200, 200, 96, 96, PixelFormats.Default);

                DrawingVisual drawingVisual = new DrawingVisual();
                using (DrawingContext drawingContext = drawingVisual.RenderOpen())
                {
                    drawingContext.DrawEllipse(Brushes.Red, null, new Point(100, 100), 95, 95);
                    drawingContext.DrawEllipse(Brushes.Blue, null, new Point(100, 100), 85, 85);
                }

                renderTargetBitmap.Render(drawingVisual);

                renderTargetBitmap.Freeze();

                Application.Current.Dispatcher.Invoke(DispatcherPriority.Normal, new Action(() =>
                {
                    Image.Source = renderTargetBitmap;
                }));
            });

            thread.Start();
        }

**Comment by cwensley** [comment]
Hm, I stand corrected!  If this is the case we should be able to get this going relatively easy.

Thanks!

**Comment by cwensley** [comment]
Thanks again for reporting this issue!  Eto's WPF platform now keeps a frozen copy of the bitmap in the case you use it or update it from multiple threads.

Cheers!
Curtis.

**Comment by lindexi** [comment]
renderTargetBitmap.Render spend too long

**Comment by cwensley** [comment]
@lindexi thanks for the feedback!  Unfortunately, that sounds like a new issue so please file a new issue with an example.

Cheers!
Curtis.

**Comment by lindexi** [comment]
@cwensley I only want to say it.
