### ISSUE TITLE
Source for Launcher.exec

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#489]
Where can I get the source for the `Launcher.exec` file in MonoMac bundles?

I would like to port it for use in other applications; for some reason, it fails to launch WinForms applications running on Mono. Is there a reason for this or will I have to modify the functionality?

**Comment by cwensley** [comment]
Hey!

This was actually from an app bundle built from MonoDevelop, which at one point was open source but is now proprietary.  This is probably not going to be the case going forward now that MS acquired Xamarin, but I don't think it has been open sourced yet.

We should probably build a custom version of this for Eto.Forms though - that way we can have a little more control over it.

**Comment by 0xFireball** [comment]
1. Which was open source and now proprietary, MonoDevelop or the app bundle? Isn't MonoDevelop open source?
2. Please let me know if you build a custom version, this would be very helpful in porting Windows apps to OS X.

**Comment by cwensley** [comment]
Hi @0xFireball,

1. MonoDevelop is open source, but the addin that was used to create the MonoMac app bundle was removed when they transitioned to the paid Xamarin.Mac.  See [this commit](https://github.com/mono/monodevelop/commit/94a3704df22832a1e715c1c6916420211b968ddf).

2. One could potentially use monodevelop's launcher as a basis to create a new launcher, it is [here](https://github.com/mono/monodevelop/blob/2945ef1e5db5acca77b48f10c9ce982273480c3b/main/build/MacOSX/monostub.m)

**Comment by cwensley** [comment]
The launcher source is [here](https://github.com/xamarin/xamarin-macios/blob/master/runtime/launcher.m).  In the latest release this is now has a 32 and 64 bit version.
