### ISSUE TITLE
WPF ResizeGrip Visible

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#491]
ResizeGrip is visible in Windows/Dialogs.

I saw that you are explicitly hiding it in Gtk so I assume that it shouldn't be visible in WPF.

**Comment by cwensley** [comment]
This was only done as the GTK resize grip was (typically) drawn overtop other controls and causes it to look pretty ugly, whereas in windows it behaves much better and looks correct.

It might be a good idea to add ability to control whether the resize grip is actually shown (when the form/dialog is actually resizable).

**Comment by cra0zy** [comment]
Fixed in: #719
