### ISSUE TITLE
TreeGridView no way to add just one item

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#493]
Currently from what I've seen, the only way of adding 1 value to treeGridView is by refreshinh the entire DataStore... which when you have a lot of values isn't that lightweight.

**Comment by cwensley** [comment]
Thanks for reporting!  with the `TreeView`, you can use the `RefreshItem` on the parent node to invalidate its children collection.  However you are correct in that the `TreeGridView` does not support this very well.

This is related to #240 where it should support hooking into MVVM and collection changes to automatically update the UI when the model changes.

**Comment by cra0zy** [comment]
Fixed in #672
