### ISSUE TITLE
Eto WebView

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#494]
How can I debug some JS running in the WebView? Is there a way to hook OnError or something?

`ExecuteScript` causes a `NullReferenceException`

**Comment by cwensley** [comment]
You are probably calling `ExecuteScript` before the `WebView.DocumentLoaded` event is fired.  There's no current way to hook into JS error event, but this is probably not a JS error anyway.  Any JS errors can be trapped in your JS code using try/catch, etc.

Hope this helps!

**Comment by 0xFireball** [comment]
Thanks!
