### ISSUE TITLE
On WPF Modifier key presses not captured

### ISSUE THREAD

**Issue by GeneThomas** [picoe/Eto#499]
This does not work in a simple application, but does work in the Eto.Test application, which must be doing something special, as when the relevant parts KeyEventsSection.cs and AllControlsBase.cs are moved to a new application (attached) it fails. i.e. Hitting Control does not cause the Log.Write() to show a message box but hitting X does.
[ModifierKeys.zip](https://github.com/picoe/Eto/files/233269/ModifierKeys.zip)

On WinForms the modifier key presses are captured.

**Comment by gene-l-thomas** [comment]
Attaching a very simple app that MessageBox.Show()s the key down keys showing that the modifier keys are not captured.
[ModifierKeysSimple.zip](https://github.com/picoe/Eto/files/233276/ModifierKeysSimple.zip)

**Comment by gene-l-thomas** [comment]
Without capturing the modifier key presses it makes it impossible to implement drag and drop where Control toggles between copy and move, as per Windows Explorer and Nautilus.

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Yes, the modifier keys don't trigger key events at this time, but you can use `MouseEventArgs.Modifiers` to determine what keys are down during mouse events to perform different actions.

**Comment by gene-l-thomas** [comment]
But I need the control Key to toggle Copying vs Moving when I am doing drag and drop.

**Comment by cwensley** [comment]
Thanks again for reporting the issue, this should now be fixed!
