### ISSUE TITLE
Gtk3 Line Warp

### ISSUE THREAD

**Issue by harry-cpp** [picoe/Eto#502]
Line Warp is not working in Gtk3 with label.

**Comment by Sejsel** [comment]
This seems to be fixed with 2.5.0, Word wrapping seems to be working correctly now. It was not functional in 2.4.1.

**Comment by cwensley** [comment]
@Sejsel great, thanks for the confirmation.  I did a lot of changes to work more closely with Gtk3's layout system for 2.5.0 and use the Gtk.Grid vs. the deprecated Gtk.Table, etc that fixed some of those issues.   Closing until we can find a specific example that doesn't work right
