### ISSUE TITLE
Unable to run Eto.Forms app in OSX using v2.2 but works with v2.1

### ISSUE THREAD

**Issue by arisrell** [picoe/Eto#505]
I installed the latest VS addin 2.2 and created a test app in VS2013 in Windows 7 using the following settings:

Combined Windows and Linux assembly, separate Mac
Full .Net
Code Preview

Compiled the app just created using configuration=Release  platform=Any CPU

Copied the .app folder to Macbook and run it,  there is some sort of issue with Launcher.exec.

Using exactly the same steps as above but using v2.1 alpha, the test app works fine.

Why can't I run the app using v2.2 in Mac, I need to use v2.2 because of the new Eto.Forms.Binding.

Please help me figure out why it will not run on Mac.  Do I have to copy the solution to each platform and compile it there?  Is this how it is normally done? Compile the solution in separate OS such as:

Visual Studio for Windows
Xamarn Studio for Mac
MonoDevelop for Linux

Thanks

**Comment by cwensley** [comment]
> Copied the .app folder to Macbook and run it, there is some sort of issue with Launcher.exec.

This is probably where things went wrong.  If you just copy the .app folder from windows to OS X, it won't get the right executable permission set up for Launcher.exec.  If you zip the .app folder, copy to OS X, then unzip, it should work!

Hope this helps!
Curtis.

**Comment by arisrell** [comment]
I zipped the folder and unzipped, same issue.
I did chmod 777 to Luancher.exec, still same issue too.

Any more suggestion, I could try.

Thanks

**Comment by arisrell** [comment]
Thank you very much.  Works in El Capitan OS X.
