### ISSUE TITLE
[QUESTION] PasswordChar

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#507]
Is there a property I could use on the textbox for a `PasswordChar` like in WinForms? I would like to be able to replace the input text with asterisks at the very least.

**Comment by cwensley** [comment]
You should use the `PasswordBox` control for this.  On some platforms (e.g. OS X) it is much more secure in the way it stores the password, etc so that it's harder to get its value outside of the app.

**Comment by 0xFireball** [comment]
This should probably be in another issue thread, but I want to avoid clogging it up if I can.

My Eto application works totally fine on Windows on WPF and WinForms, however, the MonoMac version fails to launch. When I manually open the application in the Contents/MonoBundle folder with Mono, I see an error trace that the application was unable to detect the platform and closes immediately.
