### ISSUE TITLE
App not launching on OS X 10.11

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#509]
My Eto application works totally fine on Windows on WPF and WinForms, however, the MonoMac version fails to launch. When I manually open the application in the Contents/MonoBundle folder with Mono, I see an error trace that the application was unable to detect the platform and closes immediately.

By the way, I really like Eto.Forms!

**Comment by 0xFireball** [comment]
It is still broken.

**Comment by cwensley** [comment]
@0xFireball, how are you copying the .app bundle to your mac?  If you simply copy from say, a vmware/parallels share, it won't run due to the Launcher.exec not being set as executable.  If you zip it on windows, copy to mac, then unzip, it should work.

Otherwise, there may be other issues going on, such as other assemblies not being copied properly to the bundle, or using something that is windows only.

Note that you cannot just run mono on the executable, you must actually execute the Launcher.exec in the Contents/MacOS folder.

**Comment by 0xFireball** [comment]
1) I have been zipping the `.app` before sending to OS X. I zipped it on Windows with 7-zip, and copied the zip to the Mac.
2) I originally tried launching by double-clicking the `.app` like other apps. However, the icon bounced for a few moments then closed. The app works totally fine on Windows on both WinForms and WPF; only after the app failed to launch did I try the `mono` command.
3) Is there any way to get a trace on `Launcher.exec`?

**Comment by cwensley** [comment]
Do you mind attaching the .app bundle?  It may help me tell what's going on there. 

Other than looking in Console.app, there isn't much else you can really see as the error mechanism in monomac isn't very useful in this situation.

**Comment by blahlicus** [comment]
Hey @cwensley,

I am recently developing an application with the Eto framework and am having a similar problem with @0xFireball.

I am deploying on OS X 10.8.3, the operating system has mono installed.

I am using Visual Studio with the NuGet package from Eto, my applications work perfectly fine in Windows, Linux, and Mac, but I cannot get the Mac application bundle (the .app directory) to work properly. For testing purposes I've created a new test project.


Screenshots below is a new project started and compiled in Windows, the files are zipped in windows and passed to the Mac OS.

This screenshot is the eto mono app ran via the terminal (see the bash command):

![screenshot1](http://i.imgur.com/yA7qXwX.png)

As you can see the application starts with no problem at all, but clicking the .app mac bundle does not work, see screenshot below:

![screenshot2](http://i.imgur.com/oYFTgra.png)

I've also uploaded the error message [here](https://gist.github.com/blahlicus/c6107b0691ba45bc12e9bfc5049b4766).


Attached below is the zip file containing the mac bundle and other stuff.

[etotest2.zip](https://github.com/picoe/Eto/files/276503/etotest2.zip)

**Comment by 0xFireball** [comment]
We are obviously having a problem with the app bundle, most likely `Launcher.exec`. @blahlicus is reporting it on an older version. On OS X 10.11, however, I am not getting the `App quit unexpectedly` error; instead, the app opens and quits seemingly immediately, and I am not sure how to debug this as I am a Windows and Linux user.

**Comment by cwensley** [comment]
Hey guys, thanks for the info and the sample app!

Try removing these lines from Info.plist, and see if that works for you:

```
<key>CFBundleResourceSpecification</key>
<string>ResourceRules.plist</string>
```

I think those were incorrectly added as part of the template.

**Comment by blahlicus** [comment]
Hey, thanks for the pointer @cwensley, unfortunately that didn't work.

I removed those two lines and I am getting the same error from my previous post.

[Here's](https://gist.github.com/blahlicus/aa62e3dc4367b6001d62652737a965d9) the modified info.plist

Is my problem replicable or is this an isolated issue?

**Comment by cwensley** [comment]
@blahlicus, if I remove those two lines, it runs fine for me.  What version of mono do you have installed?

**Comment by 0xFireball** [comment]
I tried it on El Capitan, and I see no change.
On May 22 2016, at 12:54 pm, Curtis Wensley <notifications@github.com> wrote:

@blahlicus<https://github.com/blahlicus>, if I remove those two lines, it runs fine for me. What version of mono do you have installed?

**Comment by cwensley** [comment]
@0xFireball, thanks for checking as well.. what version of mono is installed?

**Comment by cwensley** [comment]
also, make sure you re-build the solution after making that change.. it might not be rebuilding the .app bundle since it isn't part of the normal build process.

**Comment by cwensley** [comment]
hm, according to [this](https://github.com/TooTallNate/NodObjC/issues/21), there may be a problem with creating the NSWindow before NSApplication instance is created..  at least for the NSInternalInconsistencyException exception that is thrown..  Odd that it works for me though, however I'm on El Capitan so unsure if that is why it works..

**Comment by blahlicus** [comment]
Hey guys, thanks for the info and testing,

I rebuilt the project after editing the lines in `_project_/_project_.Desktop.Mac/MyApp.app/Contents/info.plist`, still no luck, same error.

I'll test it out in Capitan tomorrow, but I don't think the UI call stack is related... running the following bash command within the same directory as `_project_.Desktop.exe` launches the application without problem.

`mono _project_.Desktop.exe`

**Comment by blahlicus** [comment]
Hey,

Just an update, I just tested the application bundle under El Capitan with mono 4.4, I could confirm that it is working, not sure why it didn't work with Mountain Lion though.

**Comment by 0xFireball** [comment]
I tried creating a new project on OS X 10.11 with the MonoMac and XamMac2 platforms installed, but the app still crashed with the invalidoperation failed to detect platform error :(

**Comment by cwensley** [comment]
@0xFireball, did you use Eto's XS addin to create the project templates, or did you use the nuget packages to create the .app bundle?  Could you attach the .app bundle to take a look?

**Comment by 0xFireball** [comment]
I used the NuGet packages to create it, because the addin wasn't available for the version of xamarin studio i am using (the alpha channel)
Also, could you please update the addin?
I'll upload the app bundle soon; I can't do it right now because i don't have my Mac.

**Comment by cwensley** [comment]
These issues should be resolved now, the Info.plist has been fixed.  I'll close for now but if you're still having issues pleas upload the app bundle so we can figure out what's going wrong there.

Thanks again for reporting the issue!
Curtis.
