### ISSUE TITLE
PropertyCell in TreeGridView

### ISSUE THREAD

**Issue by smartquant** [picoe/Eto#510]
I am looking into building a PropertyGrid control for Eto.Forms using the TreeGridView. The PropertyCell example code shows how this would work with a GridView control. However, the categories in a PropertyGrid mean that the underlying control should be a TreeGridView. 

I cannot adapt the example using a TreeGridView. First, it seems to me that binding is not working in conjunction with the TreeGridView (TreeGridViewHandler.GetItemAtRow can be changed to return the model instead the TreeGridItem. Then my example works with Winforms, but all other examples are broken).
Second and more importatnt, I cannot find any way to make PropertyCell working within a TreeGridView column. An example TreeGridView including a PropertyCell would be extremely helpful to point me in the right direction.

**Comment by cra0zy** [comment]
Duno about using TreeGridView, but I made a custom one using drawable + system colors: https://youtu.be/Ce_jWRPdsZA?t=18s

Anyway if you are interested in the code it's available in https://github.com/mono/MonoGame/pull/4786

**Comment by cra0zy** [comment]
@cwensley Would you be interested in me porting over the PropertyGrid I did for MonoGame Pipeline Tool?

I made the grid quite extendable: https://github.com/MonoGame/MonoGame/tree/develop/Tools/Pipeline/Controls/PropertyCells

**Comment by cwensley** [comment]
This should now be fixed with #1414.  The TreeGridView didn't like having its first column as a CustomCell on macOS, and a few other things weren't working (CustomCell on Gtk/Gtk3 for example).

Still needs a bit of work on Gtk+3 due to size of buttons being massive, but that may be fixable using some native styles.

The interface is also pretty minimal, so it could probably be swapped out with @cra0zy 's implementation with minimal effort.

**Comment by harry-cpp** [comment]
The new propertygrid looks great! The only weird thing I found is that bool property cell has a checkbox all the way on the right.

**Comment by cwensley** [comment]
@cra0zy yeah it's that way on purpose..  I can't remember what that purpose is, so perhaps it should be changed to be to the left of the text if that is more normal..  or at least have an option.
