### ISSUE TITLE
[Gtk3] Combobox wrong height

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#516]
Combobox gets really silly sized:

Gtk 2 (normal):
![screenshot from 2016-05-22 13-58-49](https://cloud.githubusercontent.com/assets/6773302/15453866/b11fe896-2025-11e6-9f5d-965fcaf27628.png)

Gtk 3 (paranormal :P):
![screenshot from 2016-05-22 13-59-26](https://cloud.githubusercontent.com/assets/6773302/15453865/b11e22ae-2025-11e6-877a-4a48a0196f49.png)

**Comment by cwensley** [comment]
Hm, it's probably not the ComboBox here, it's most likely the DateTimePicker control, which is a composite of other controls to 'act' like an editable drop down..  There's been other sizing issues with it..  I wonder if there's a new control for GTK3 that would work instead of creating it manually?

**Comment by cra0zy** [comment]
> Hm, it's probably not the ComboBox here, it's most likely the DateTimePicker control, which is a composite of other controls to 'act' like an editable drop down.. There's been other sizing issues with it.. I wonder if there's a new control for GTK3 that would work instead of creating it manually?

It's Combobox, DropDown and DateTimePicker, all 3 do the same thing. If I remove the DateTimePicker the combobox remains stretched.

**Comment by cra0zy** [comment]
This got fixed by something, so closing...
