### ISSUE TITLE
[MonoMac] Application crashes if user cancels OpenFileDialog

### ISSUE THREAD

**Issue by blahlicus** [picoe/Eto#518]
OpenFileDialog works properly under Gtk and winforms but it crashes under MonoMac/Cocoa if the user presses cancel instead of selecting a file to open.

I recreated this bug in a test application. [This link](https://gist.github.com/blahlicus/6969eb1248c4808d21ac18401cde6644) contains the source file to the test application, I experienced this bug with OS X El Capitan and Mono 4.4.

[This zip file](https://github.com/picoe/Eto/files/277924/OpenFileDialogBugExecutables.zip) contains the Mac Application Bundle and other compiled binaries of the above test application.

**Comment by cwensley** [comment]
Hi @blahlicus,

This is because of [this line](https://gist.github.com/blahlicus/6969eb1248c4808d21ac18401cde6644#file-etoopenfiledialogtest-cs-L37)

Try using `string.IsNullOrEmpty(dialog.FileName)` instead.  It is not guaranteed to be non-null.

Hope this helps!
Curtis.
