### ISSUE TITLE
[WPF] Treeview RefreshItem does not work

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#519]
Treeview RefreshItem does not work if the control was visible from the start.

**Comment by cwensley** [comment]
Thanks for reporting the problem, but I'm not sure I follow exactly what you are trying to do here.

Do you have some sample code or at least steps to reproduce?

**Comment by cra0zy** [comment]
I really did poorly explained it... I have to switch to Windows to remember how to cause it... Anyway if I remember correctly you should be able to cause it using the example app by simply adding a new item to either the base or as a sub item.

**Comment by cra0zy** [comment]
Finally had some free time, anyway the problem occurs when you try to insert an item in a subitem and refresh it, it will never refresh it...

Repro steps:
 - start test app
 - navigate to `Controls>TreeView` section
 - click Insert
 - select the new item
 - click Insert

Bonus steps if you want to cause a crash:
 - click Remove
 - click Insert

**Comment by cra0zy** [comment]
Closing since it has been fixed... and we are killing treeview anyway.

**Comment by michaldobrodenka** [comment]
You are killing TreeView? I'm building new application around TreeView? Will it be supported? What should I use instead?

**Comment by cwensley** [comment]
@michaldobrodenka use TreeGridView

**Comment by cra0zy** [comment]
TreeGridView
