### ISSUE TITLE
Linux sample application doesn't generate an exe

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#521]
I fired up MonoDevelop (5.1) under Debian Jessie with Mono 4.2.3 installed. I then installed the Eto.Forms sample nuget package (accepting replacement of the source files) and attempted to build the exe. I got the following output :

Building: etofrmstest (Debug|x86)

Build started 5/27/2016 1:55:41 PM.
__________________________________________________
Project "/home/phil/Documents/development/etofrmstest/etofrmstest/etofrmstest.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: x86
	
	Target CopyFilesMarkedCopyLocal:
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Forms.2.2.0/lib/net45/Eto.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/Eto.dll'
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Platform.Mac.2.2.0/lib/net45/MonoMac.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/MonoMac.dll'
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Platform.Mac.2.2.0/lib/net45/Eto.Mac.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/Eto.Mac.dll'
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Platform.Wpf.2.2.0/lib/net45/Eto.Wpf.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/Eto.Wpf.dll'
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Platform.Windows.2.2.0/lib/net45/Eto.WinForms.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/Eto.WinForms.dll'
		Copying file from '/home/phil/Documents/development/etofrmstest/packages/Eto.Platform.Gtk.2.2.0/lib/net45/Eto.Gtk2.dll' to '/home/phil/Documents/development/etofrmstest/etofrmstest/bin/Debug/Eto.Gtk2.dll'
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
Done building project "/home/phil/Documents/development/etofrmstest/etofrmstest/etofrmstest.csproj".-- FAILED

Build FAILED.
	 0 Warning(s)
	 0 Error(s)

---------------------- Done ----------------------

Build successful.

There’s no executable, however.

**Comment by philstopford** [comment]
I've entered this as a bug because I've tried it on a few different Linux systems and haven't had success yet. The same procedure generates an executable on Mac and Windows.

**Comment by cwensley** [comment]
Did you install the PCL reference assemblies?  I believe the package is "referenceassemblies-pcl" as noted [here](http://www.mono-project.com/docs/getting-started/install/linux/).

**Comment by philstopford** [comment]
Yes, I followed the instructions there. Out of options, I just deployed the big gun : installing mono-complete. That seems to sort it out, but it seems peculiar to have to do this.

**Comment by cwensley** [comment]
I agree that it kind of sucks to have to install pretty much everything to get it to compile, and it really sucks that mono doesn't give nary a clue on what it is actually missing, or that there was actually a problem.  I'm glad you got it working though!

**Comment by philstopford** [comment]
There is one remaining curiosity - I don't seem to be able to run the resulting binary from MonoDevelop. I have to go to the terminal (mono myprogram.exe). Is that expected?

**Comment by cra0zy** [comment]
Did you set the exe project as startup project?

**Comment by cra0zy** [comment]
On a side note current stable version of MonoDevelop is 5.10 and current stable version of mono is 4.4.0, you might want to update your components.

**Comment by philstopford** [comment]
Yes, it was set. I've got similar issues on Mac now so it feels like a common problem. I'm going to try with a new solution/project to see what might be happening

**Comment by philstopford** [comment]
On Linux, I simply can't get MonoDevelop to run the sample application, even freshly created. I can run it from the terminal directly, though. On Mac, I can get it to run until the point I make a change. I'll file that as a separate bug.

**Comment by philstopford** [comment]
Mono 4.4 doesn't make a difference. Odd. I'll try a different distribution when I get a moment.

**Comment by cwensley** [comment]
Is this still a problem with latest mono (2.6) and monodevelop (6.1)?

**Comment by philstopford** [comment]
Seems to be OK here.

**Comment by cwensley** [comment]
Cool, thanks for the quick response!  Glad to hear it's working now.
