### ISSUE TITLE
Question: anchor or similar?

### ISSUE THREAD

**Issue by gusmanb** [picoe/Eto#523]
Hi.

I'm starting to test Eto.Forms and I didn't found any documentation about it, is there any type of mechanism to auto adapt layouts to window size? something like Anchor and Dock on WinForms, or any way to specify sizes in percentages?

Cheers.

**Comment by cwensley** [comment]
Hopefully that has answered the questions, @gusmanb.  There is no anchor, but dock is pretty much default for all containers.  

To 'anchor', you place the control(s) in the appropriate cells in a TableLayout, so they can be either to the left or right with ScaleWidth as false.  Note that you must have at least one cell with ScaleWidth = true, so you'd have to add a cell between the left and right in order for empty space to appear between them.

Hope this helps!
Curtis.
