### ISSUE TITLE
Wpf cut text not working

### ISSUE THREAD

**Issue by JBildstein** [picoe/Eto#526]
When using the cut shortcut Ctrl+X in a TextArea or TextBox it hangs for a little bit (0.5-1second) and then shows this message in the output window:
`Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.dll`
This exception doesn't surface to my application though.

The selected text is copied to the clipboard but still remains in the box about 95% of the time.
Normal copy (Ctrl+C) also shows the same signs (hanging + exception) but since it does what it should (copy the text) it's not as bad.

Eto version 2.2.0 on .Net 4.5.2
I tried it in WPF and WinForms but only WPF shows that behavior.

**Comment by dfyx** [comment]
There is a general problem with cutting in WPF that might be related. There are posts on [Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/798501/textbox-cut-bug-in-wpf) and [StackOverflow](http://stackoverflow.com/questions/18299579/cannot-cut-text-from-textbox) with more details.

**Comment by JBildstein** [comment]
Thank you @dfyx, those issues you linked seem to describe my issue.
I have been using it in a VM with a copy/paste feature to the host so it's very likely that I hit this WPF bug.
Nothing Eto.Forms can do here, so I'll close it.
