### ISSUE TITLE
[MonoMac] KeyDown, KeyUp events not firing

### ISSUE THREAD

**Issue by blahlicus** [picoe/Eto#528]
The KeyDown and KeyUp events for Eto Controls and Forms are not firing within MonoMac, they work as expected under Winforms/wpf/gtk.

Example below:

Create your button somewhere:

```
var btn = new Button();
MainForm.Content = btn;
```

Add event handler after initialisation :

```
public MainForm()
{
  InitializeComponent();
  btn.KeyDown += (sender, e) => this.KeyBtnKeyPressed(sender, e);
}

private void KeyBtnKeyPressed(object sender, KeyEventArgs e)
{
  (sender as Button).Text = e.KeyData.ToShortcutString();
}
```

Expected result for sample above is that giving the focus to the button (via clicking on it) then pressing a key on the keyboard should change the text of the button into the pressed key, but it doesn't work under MonoMac, I think it has something to do with the Cocoa interface.

**Comment by cwensley** [comment]
Thanks for submitting the issue!  However, this might be because buttons in OS X do not take focus when you click on them (this is standard behaviour on this platform).  You must hit the 'tab' key to focus the button, or programatically set its focus.  You can try calling `button.Focus()` during the click event.

**Comment by cwensley** [comment]
Just tested this on macOS Sierra.  When you click a button it does _not_ set keyboard focus the button, and this has been standard behaviour on Mac for a long time.  If you hit the tab key to tab to the button or set its focus manually, it does pass key up/down events to the button control.

I don't think it would be a good idea to make Eto focus the button when you click it as it won't keep standard behaviours.  So, if you require this, I'd suggest handling the Click event and then calling `myButton.Focus()`.

Hope this helps!
Curtis.
