### ISSUE TITLE
NSWindowCollectionBehavior.FullScreenAuxiliary on MonoMac

### ISSUE THREAD

**Issue by oliverdarvall** [picoe/Eto#532]
```
NSView view = mainForm.ToNative();

view.Window.CollectionBehavior = NSWindowCollectionBehavior.FullScreenAuxiliary | NSWindowCollectionBehavior.CanJoinAllSpaces;

view.Window.Level = NSWindowLevel.ScreenSaver;
view.Window.ToggleFullScreen(view);
```

When setting the CollectionBehaviour to FullScreenPrimary the window responds as expected. The "Maximize" button changes to a "Fullscreen" arrow and the application does go to fullscreen when then clicked.

However, when setting the Property to FullScreenAuxiliary the "Maximize" button stays as a maximize button. If I understand correctly the button should also change to the "Fullscreen" arrow, but when then pressed it will allow your window to share the current fullscreen window.

**Comment by cwensley** [comment]
I think you might have the incorrect idea of what FullScreenAuxiliary does, it allows you to create a window that shares the same screen as _another_ full screen window.  From the [docs](https://developer.apple.com/reference/appkit/nswindowcollectionbehavior/1419617-fullscreenauxiliary): "Windows with this collection behavior can be shown on the same space as the fullscreen window."

So, it seems it is for child windows that you want to appear above a full screen window.

**Comment by cwensley** [comment]
Thanks again for reporting this.  I am assuming that it is just a misunderstanding of what this feature does.  Regardless, this isn't part of Eto per se, as you are just using the Mac/AppKit api's so I'll close for now.
