### ISSUE TITLE
Remove RefreshItem from TreeView / TreeGridView

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#533]
@cwensley Is there any reason why you made it so refresh needs to be called after adding an item? 

I found this to be a major problem when for example you have a list of 100 values with icons in a treeview, and when you want to add just one more, you need to refresh the previous 100 which takes a second or two. Especially problematic when you have to do it  more times immediately after that call.

**Comment by cwensley** [comment]
This would be taken care of by #240, closing this as a duplicate.
