### ISSUE TITLE
Confusing licence

### ISSUE THREAD

**Issue by dsoronda** [picoe/Eto#540]
I'm sorry but I'm confused by LICENCE file (or I missed something?).

Can you be more specific under what kind of Free/Payed usage can we use Eto.Forms ?

Is it free as in beer/speech ?

Thanks.

**Comment by cwensley** [comment]
Eto.Forms's is licensed as "New BSD", which is very similar to MIT and gives you all the freedom to use Eto.Forms for pretty much whatever you like (including commercial applications).  You just need to include the license with your application.  I am, however, not a lawyer.

AFAIK, the BSD license only restricts you from use the author's names to endorse/promote your products without permission (vs. MIT).

**Comment by cwensley** [comment]
Thanks again for the question. I've added the type of license to the top of the LICENSE file, so you can do searches of what exactly that means and if it's suitable for your purposes.  

I think it's a bit out of scope for this project to specify what that means legally, though I hope this helps.

**Comment by cra0zy** [comment]
Side note related to LICENSE, you can connect it to the repo so it's visible in top bar ie. https://github.com/mono/xwt

**Comment by cwensley** [comment]
@cra0zy yeah I saw some projects have that but I have no idea how to hook that up.. I think it might be reading the license text to see if it matches a known license.

**Comment by dsoronda** [comment]
> AFAIK, the BSD license only restricts you from use the author's names to endorse/promote your products without permission (vs. MIT).

Thanks, I really didn't know that. 👍
