### ISSUE TITLE
DataContextChanged not called when assigning DataContext to Equal, new value

### ISSUE THREAD

**Issue by jhg14** [picoe/Eto#543]
_Problem_
I'm not receiving an occurrence of DataContextChanged when I expect to, nor are bindings updated, when assigning the DataContext of my class that extends TableLayout. The instance assigned is equal (both Equals() & HashCode()) to the previously assigned instance. 

_Work around_
I was able to work around this by assigning DataContext to null before assigning it
to the new value.

_Reproduce_
    Attach a debug message to DataContextChanged
    Assign DataContext to some instance X of a type that properly implements Equals/HashCode
    Assign new but Equal instance to DataContext
    _DataContextChanged won't occur here and bindings will not be updated_

_Version_
Eto.Forms version 2.2.0
Eto.Serialization.Xaml version 2.2.0

**Comment by cwensley** [comment]
Hm, interesting.  Probably need to use ReferenceEquals to determine if the value has changed instead of just Equals.  Thanks for reporting the issue!

**Comment by jhg14** [comment]
Happy to help!
