### ISSUE TITLE
Adding a user-defined panel breaks the Xaml preview

### ISSUE THREAD

**Issue by spinda** [picoe/Eto#545]
Steps to reproduce:

1. In Visual Studio 2015, create a new `Eto.Forms.Application` project called `MyProject`, with `Xaml` selected and default settings for everything else.
2. In the `MyProject` project, `Add` a new `Eto.Forms Panel (Xaml)` called `Panel1`, with the default settings.
3. Use the following XAML in `MainForm.xeto`:

    ```xaml
    <?xml version="1.0" encoding="UTF-8"?>
    <Form
      xmlns="http://schema.picoe.ca/eto.forms" 
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="clr-namespace:MyProject;assembly=MyProject"
      Title="My Eto Form"
      ClientSize="400, 350">
      <StackLayout>
        <local:Panel1/>
      </StackLayout>
    </Form>
    ```
4. Observe that the preview panel stops updating and a red bar appears across the bottom with the message `Exception has been thrown by the target of an invocation.` The tooltip indicates that [this exception](https://github.com/picoe/Eto/blob/develop/Source/Eto/Widget.cs#L221-L222) is being thrown, from `MyProject.Panel1.ctor()` &rarr; `Eto.Forms.Panel.ctor()` &rarr; `Eto.Widget..ctor()`.

Closing and reopening `MainForm.xeto`, rebuilding the solution, and restarting Visual Studio all do nothing to help with the problem. Deleting `<local:Panel1/>` from `MainForm.xeto` is the only way to fix the preview pane.

**Comment by cwensley** [comment]
Should now be fixed!  Visual Studio can actually show the content of the user-defined panel (as it utilizes AppDomains), whereas Xamarin Studio will just show a placeholder in the designer.
