### ISSUE TITLE
Change the background color of the XAML preview pane (or handle dark themes better)

### ISSUE THREAD

**Issue by spinda** [picoe/Eto#547]
I use the dark theme in VS2015, so my XAML preview pane ends up looking like this:

![xeto-bg](https://cloud.githubusercontent.com/assets/7958605/17459103/b2569b50-5be0-11e6-938f-13124f6495a9.PNG)

I can set a `BackgroundColor` on the root element of my XAML, but then I have to remove it before building or all platforms will no longer use their native background colors.

**Comment by cwensley** [comment]
This should now be fixed in the VS addin for 2.3
