### ISSUE TITLE
[WPF] Scrollable not sizing correctly (2.2 and 2.3 dev branch)

### ISSUE THREAD

**Issue by se5a** [picoe/Eto#550]
This branch shows the issue well:
https://github.com/se5a/EtoTests/tree/ScrollableTestDevBranch/EtoApp1

To reproduce in the above:
run with WPF as startup project.
Click the Scrollable Test button
A new tab will be created with a scrollable and a number of items.
The scrollable is not sized correctly and the button is not visible at the bottom. 
doing the above with GTK2 as the startup will show what the scrollable should look like. 

Note: I *think* I recall testing this in an older version of the 2.3 dev branch some months ago and it appeared that the problem had been fixed, this may be a regression.

**Comment by cwensley** [comment]
Now fixed!  Thanks for submitting the issue and the test app, it really helped ensure things were working right!
