### ISSUE TITLE
FolderBrowserDialog does not scroll selection into view (with solution)

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#559]
The WPF and WinForms implementation of the SelectFolderDialogHandler both use the FolderBrowserDialog control. I have noticed that this does not scroll the selection into view if it is below the size of the control.
To solve this problem, I propose replacing line 11 in  Eto/Source/Eto.{Wpf|WinForms}/Forms/SelectFolderDialogHandler.cs 
from 

```
Control = new swf.FolderBrowserDialog ();
```

to 

```
Control = new swf.FolderBrowserDialog {RootFolder = Environment.SpecialFolder.MyComputer};
```

When the RootFolder is set to MyComputer, the selection always scrolls into view.

**Comment by cwensley** [comment]
@mennodeij thanks for reporting, but I'm testing out the current functionality and it seems like the solution you've provided doesn't work, plus it limits the selection in the dialog so you can't select network folders or use the libraries collections, etc
![selectfolderdialog2](https://cloud.githubusercontent.com/assets/367446/19305719/90aa9396-9072-11e6-82dd-b49c80261036.gif)

**Comment by cwensley** [comment]
I found this [super hack](http://stackoverflow.com/a/15440926/981187), but I hesitate to put something so hacky into Eto, it seems like this is just how the dialog was designed.

**Comment by cwensley** [comment]
A better solution here would be to use the WindowsAPICodePack to use the new vista and newer OpenFileDialog in folder select mode, which shouldn't have this problem

**Comment by cwensley** [comment]
Thanks again for reporting!  Now using the vista style dialog (if supported by the OS) for both Wpf and WinForms which should be much more awesome. (;
