### ISSUE TITLE
[2.3] TabControl can sometimes be unhappy about order.

### ISSUE THREAD

**Issue by se5a** [picoe/Eto#575]
I'm failing to repeat the problems in a simple example, I've not been able to figure out why this happens.
I'm not seeing the problem in 2.2, however #563 seemed to indicate something marginally similar.
This happens in both WPF and GTK2, however the Crash happens in a different place in GTK2, and the workaround does not work. 

Symptoms:
- Crash on `myTabControl.Pages.Add(myTabPage);` with exception "System.InvalidCastException" "Object must implement IConvertible" this is sometimes an inner exception. 
- Empty DropDowns, ComboLists etc. 
- DataContext gets set twice. (to the same object) ie 

WorkAround:
Ensure you set the myTabPage.Content *After* adding the myTabPage to the myTabControl:
```
myTabControl.Pages.Add(myTabPage);
myTabPage.Content = c;
```
not:
```
myTabPage.Content = c;
myTabControl.Pages.Add(myTabPage);
```

**Comment by se5a** [comment]
Because a comlicated example is better than none:
here's a link to a non simple actual project where I'm having this problem:
https://github.com/Pulsar4xDevs/Pulsar4x/tree/ECS-CrossPlatform
that is using eto 2.2 and works,
run with the wpf project as startup, let it build and get nuget packages etc. 
click File -> New Game 
click Ok in the new game dialog with the defaults.
click System Info in the toolbar (second to last button)
it should display without issue. 
update to eto 2.3
follow repeat the above and you'll get a crash in mainwindow.xeto.cs
repeat the above in gtk2 and you'll get a crash in SystemInfoCMD.cs
switch the order of the tab content and adding to the control and the problem goes away in wpf, but remains in gtk. 

note other tab pages in that project have the same problem, most notably is the rather complex Component Template Design. (which also has the scrollable size problem which 2.3 fixes)

**Comment by cwensley** [comment]
@se5a, thanks for the link to the repro, it certainly helps even if you can't figure out a simpler repro.  It should hopefully be enough for me to investigate what's going on there.

**Comment by cwensley** [comment]
Thanks again for reporting the issue, it should be fixed in latest develop.
