### ISSUE TITLE
Duplicate Events Raised On Forms With Inheritance

### ISSUE THREAD

**Issue by AdamCWray** [picoe/Eto#576]
When creating an inheritance tree of objects with an Eto form or control at the bottom of the chain, if more than one level overrides the same event handler, when the event occurs, the objects handler can be called once for each override rather than just once.

As an example we have a base form that inherits from Eto.Form and it has an override for OnClosed. All our other forms inherit from this base form and on occasion they may also provide an override for OnClosed. When the Closed event gets triggered for a form like this, the OnClosed method is called twice.

I believe the problem to be in the FindTypeEvents method in the EventLookup class. This method walks the non-Eto inheritance tree looking for methods that match the Eto event handlers and will do a yield return every time it finds a match. In the case of multiple overrides in the inheritance tree, it will find the handler at each level and this causes the event to be hooked up as many times as it is overriden.

My suggestion (and how we have temporarilly fixed it) is to remember which events had already been found and only do the yield return when you find a new one. See attached file for code.
[EventLookup.txt](https://github.com/picoe/Eto/files/522091/EventLookup.txt)

**Comment by cwensley** [comment]
Hey @AdamCWray, thanks for the report and the detailed analysis, it helps a lot!

**Comment by cwensley** [comment]
Thanks again for the report!  This should now be fixed in the develop branch.
