### ISSUE TITLE
Closable TabControl

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#577]
It would be nice if there was a control that has tabs like in VS/MonoDevelop/Any web browser, aka. the ones that can be closed by the user.

**Comment by cwensley** [comment]
At least on macOS Sierra, this feature is now available "by default" for any app without any code changes.  Otherwise this is pretty much a dupe of #225 and/or #21

**Comment by cra0zy** [comment]
Ah, sorry for creating a duplicate issue...

**Comment by cwensley** [comment]
@cra0zy no prob, it happens (;
