### ISSUE TITLE
Eto.Forms.Designer in MonoDevelop

### ISSUE THREAD

**Issue by oldtomdevel** [picoe/Eto#583]
I tried Eto.Forms with MonoDevelop 5.10 for Linux. Generally, it works i.e. I can build exe files which are able to run on different machines. However, it is stated that Eto.Forms includes a preview function. But whenever I try to open a Form with the Eto.Forms designer (by the context menu of MonoDevelop), it does not work but displays the error message "Cannot find the reference assemblies folder". Does anybody have an idea what to do?

**Comment by cra0zy** [comment]
There is a newer version of addin that has fixed this, but you will need MonoDevelop 6 installed for it.

PS. Don't use the flatpak version of MonoDevelop, it's very buggy.

**Comment by oldtomdevel** [comment]
Does that refer to Eto.Forms 2.3.0? MonoDevelop 5.10 gives a message that this newer version should be available. However, the update does in fact not work as the update stops with message "Updating 'Eto.Forms 2.2.0' to 'Eto.Forms 2.3.0' failed. Unable to find versions of 'Eto.Platform.Gtk, Eto.Platform.Gtk3, Eto.Platform.Windows' that are compatible with 'Eto.Forms 2.3.0'."
Assuming that this update would work in MonoDevelop 6, where to get it from? On their web site, I can find MonoDevelop 6 only as flatpak, which I should not use...

**Comment by cwensley** [comment]
@oldtomdevel, you can still use MonoDevelop 5.10, but the designer will not work.  It also has issues with NuGet when upgrading packages that depend on exact versions of other nuget packages.  The best you can do there is to remove all Eto nuget packages then re-add them with the 2.3 version.  I'm not sure if XS/MD 6.1 has the same issue.

As for the designer, it's only currently supported for MD/XS 6.x, so you'll have to upgrade your install to get the latest stuff.  To get the latest MD for linux, I recommend using Xamarin's packages, which information about them are [here](http://www.monodevelop.com/download) under the Linux heading.

**Comment by cra0zy** [comment]
Not to be a party pooper, but it seems that the new addin doesn't work with MonoDevelop 6.1 :(

It does install, but you can't create a new project and you can't open the designer... I'll post a video a bit later so you can see.

**Comment by vinidiktov** [comment]
I recently installed MonoDevelop 6.1.2 via flatpak on Ubuntu 6.10 and the addin doesn't work for me either.

I get the error message "Unknown solution type: MonoMac".
