### ISSUE TITLE
[WPF] Keyboard Shortcuts don't work for MenuItems if they are added after Menu assignment

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#584]
WPF Keyboard Shortcuts don't work for MenuItems if they are added after Menu assignment. Example:

Keyboard shortcuts work:

``` c#
var menubar = new MenuBar();

var command = new Command();
command.Shortcut = Keys.Control | Keys.N;
menubar.Items.Add(command);

Menu = menubar;
```

Keyboard shortcuts don't work:

``` c#
Menu = new MenuBar();

var command = new Command();
command.Shortcut = Keys.Control | Keys.N;
Menu.Items.Add(command);
```

**Comment by cwensley** [comment]
I can't repro this in develop or 2.3.  You are assigning the MenuText for the Command, right?

**Comment by cra0zy** [comment]
I had to make the following change to get shortcuts to work: https://github.com/MonoGame/MonoGame/pull/5240/files

The menu items did show ie. `Ctrl + N` next to the item, but the shortcut did not work.
