### ISSUE TITLE
[Feature] Plottings

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#589]
![](http://sibeeshpassion.com/wp-content/uploads/2016/03/Chart-Widgets-With-Server-Side-Data-In-MVC-Using-Angular-JS-And-Web-API-Output-1024x875.png)

**Comment by cwensley** [comment]
This is probably best implemented using oxyplot, which other people have already started working on but needs to be finished up:  See oxyplot/oxyplot#341

**Comment by cra0zy** [comment]
Moved to https://github.com/picoe/Eto.Toolkit/issues/3

@cwensley This can be closed.
