### ISSUE TITLE
[Feature] Add a pixel map....

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#592]
...that draws a Color array as a series of squares and optionally puts a border separating them.

Example:
![](http://imag.malavida.com/mvimgbig/download-fs/nero-discspeed-13989-3.jpg)

**Comment by claunia** [comment]
Partially implemented in #586.

**Comment by cra0zy** [comment]
Moved to: https://github.com/picoe/Eto.Toolkit/issues/6

@cwensley This can be closed.
