### ISSUE TITLE
How to declare GridView in Xaml?

### ISSUE THREAD

**Issue by vinidiktov** [picoe/Eto#602]
I'm trying to figure out how to declare a GridView in xaml.

So far, I've tried this:

```
<GridView ID="gridView1">
       <GridColumn HeaderText="Freq.">
       </GridColumn>
       <GridColumn HeaderText="Lemma">
       </GridColumn>
</GridView>  
```

How do I specify the DataCell types?

Do I have to specify anything else for it to function properly?

**Comment by cwensley** [comment]
You declare the type of cells as a child node of the GridColumn, like so:

```
<GridView>
    <GridColumn HeaderText="Freq.">
        <TextBoxCell Binding="{Binding MyTextProperty}"/>
    </GridColumn>
</GridView>
```

Unfortunately, the `{Binding MyTextProperty}` portion of this isn't working quite at the moment, so you have to do that in the code behind.  Or, if you update to the latest Portable.Xaml (0.15), you should be able to do this to specify the property to use in from your model:

```
<GridView>
    <GridColumn HeaderText="Freq.">
        <TextBoxCell x:Arguments="MyTextProperty"/>
    </GridColumn>
</GridView>
```

**Comment by cwensley** [comment]
Looks like this was resolved from your [reply](https://groups.google.com/forum/#!topic/eto-forms/xweS6OJSEgA) on the forum.  The fix to allow the {Binding} markup extension is tracked with issue #439.
