### ISSUE TITLE
Gtk2/3: PrintDialogSection crash

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#611]
The changes in commit 2605877e9bb3ed90ecf996a975b21043b3740650 / PR #597 causes a crash in certain cases, such as the Printing > Print Dialog section in Eto.Test.

Not sure why, but it could be because the content can't actually fit in the splitter pane.

@cra0zy could you look into this?

**Comment by cwensley** [comment]
Ok, gtk3 doesn't appear to crash, but it does shrink the tree view in Eto.Test, which is unexpected at least.

**Comment by cra0zy** [comment]
#613 should fix this.

**Comment by cwensley** [comment]
awesome turnaround, though what do you think about how the TreeView is shrunk when clicking on the Print Dialog section in Eto.Test?  Considering Splitter.FixedPanel is set to Panel1, it shouldn't change its size, only Panel2 in that case.

**Comment by cra0zy** [comment]
TreeView is shrunk because there wasn't enough space on the right side, this is normal in Gtk. FixedPanel in Gtk is only valid for user resizing.

**Comment by cwensley** [comment]
Hm, ok so the solution to this would be to put the PrintDialogSection in a Scrollable.  It might trip some people up where the behaviour of the Splitter is different across platforms though.

I'll close this as I've merged in #613.
