### ISSUE TITLE
SingleValueCell<T> and formatting?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#615]
I need to do some formatting on cell-values before they appear in a GridView.
For example 15.345 must be displayed as 15.3m
How could this be done? I know, with Bindings, but I don't get it, even after reading the Wiki.
Just a short sample would be nice :-)

**Comment by cwensley** [comment]
Something like this would work (minus error checking):

```c#
var column = new GridColumn
{
	Editable = true,
	DataCell = new TextBoxCell
	{
		Binding = Binding.Property((MyModel m) => m.DoubleProperty)
					 .Convert(d => d.ToString("##.0m"), s => double.Parse(s.TrimEnd('m')))
	}
};
```

You could also add a new string property to your model that does the to/from string conversion.  Doing the `double.Parse()` is only needed if you want the cell to be editable.

**Comment by TomQv** [comment]
That's it :-)

**Comment by cwensley** [comment]
Closing as I believe this was answered, thanks for the inquiry!  Let me know if this was not actually solved for you.
