### ISSUE TITLE
Combobox stops working with Stacked Dialogs on Mac OSX platform

### ISSUE THREAD

**Issue by AdamCWray** [picoe/Eto#623]
There is an issue with comboboxes misbehaving on dialog boxes when the dialog box has been opened from another dialog box on the Mac desktop platform.

Steps to reproduce:
Create a dialog and add a combobox with a few items in a Mac (Xamarin) project
When the dialog is displayed the combobox works fine and clicking the caret on the right hand side drops the list down.
Amend the dialog to add a button that will create another dialog with a combobox on it.
When the first dialog is displayed, the combobox on it stills works fine. Click the button to open the second dialog. The combobox on this second dialog now no longer works correctly. Just clicking on the caret does not drop the list down. You need to click once on the caret (to give the combobox focus) then move the mouse pointer to over the text part of the combobox and hold the mouse button down - the list should now appear but you cannot select items with the list.

I am guessing that there is some clash between the two dialog boxes and the combobox for focus but am unsure and this only happens on the Mac with which I have limited development experience.

**Comment by AdamCWray** [comment]
Some more information about this issue.
The problem seems to stem from whether or not the dialog has an Owner specified. If the dialog has no owner then the combobox works find on both Windows and OSX, if the owner is specified then the combobox works on Windows but does not on OSX.

A simple solution would appear to be to never set an owner, but this itself causes an issue with 'losing' dialog boxes.

On Windows if the dialog box has no owner, then it is possible to lose the dialog behind the form that created it:
  Create a form and have that form show a dialog
  If the dialog has no owner, bring up another window in front of this form and dialog.
  From the task bar select the icon for the form/dialog application - only the form will appear, you cannot click on it or do anything as the dialog has focus, but has disappeared behind the form.
  If the dialog has the form as owner, then no matter what you do with other windows, the dialog will always appear on top of the form

On OSX it does not seem to matter if the dialog has an owner or not, the dialog will always show on top of the caller.

I am not sure how other platforms may behave and in my case I will do a platform test and if OSX just ignore any owner, but the issue with why comboboxes do not work on a dialog with an owner in OSX remains.

**Comment by cwensley** [comment]
Hey @AdamCWray, thanks for all the information, it really helps narrow things down.

My guess is the modal loops for each of the dialogs are interfering with each other, possibly either not exiting properly, or exiting altogether.

**Comment by cwensley** [comment]
Should be fixed with PR #739
