### ISSUE TITLE
Remove WinForms platform

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#627]
As mentioned in #619, WinForms may not need to exist anymore.  It should be removed assuming there are no objections to this.

I'll schedule this for 3.0 to make sure we don't let this fall off the radar.

**Comment by TomQv** [comment]
I hope I misunderstood this!
We are just busy with a new app for Windows and Mac and decided to use Eto for the UI. This app is quiet big and will be in our product range for the next couple of years. It must run on Windows 7,8,10 and MacOS. So we are using Eto.WinForms of course. 
And now you want to remove it?
Tom

**Comment by cra0zy** [comment]
> I hope I misunderstood this!
> We are just busy with a new app for Windows and Mac and decided to use Eto for the UI. This app is quiet big and will be in our product range for the next couple of years. It must run on Windows 7,8,10 and MacOS. So we are using Eto.WinForms of course.
> And now you want to remove it?
> Tom

There is Eto.Wpf backend which works on Windows... why not use that instead of Eto.WinForms?

**Comment by cwensley** [comment]
@TomQv, don't worry - it won't be removed if there are people that depend on it!!

This is a placeholder so that at least it is understood that people should try to migrate to the Eto.Wpf platform on windows instead, but I do realize that this might not always be feasible.

This is also a great place for me to get feedback from the Eto.Forms community on whether or not it can actually be removed without impacting people.  Note this is scheduled for 3.0 currently, which is a long ways off (the 2.x series will still be going for a while).

As always, I appreciate the feedback!

**Comment by HugoRoss** [comment]
How about server-side programming? I don't know if it is still the same, but in the past WPF used to be a very poor choice if the application was intended to be running on terminal servers. The server hardware usually had poor graphic cards without 2D/3D support which resulted in bad performance and high CPU usage. Also WPF's visual effects, the blendings and animations look bad in an RDP session with reduced colors and limited band with. Unless people tell me these issues are all long gone, I would plead to still support WinForms.

**Comment by mrpastewart** [comment]
My thoughts on this would be don't remove support for something unless the upstream provider deprecated it from the framework themselves. So until Microsoft deprecates System.Windows.Forms from .net it sould be supported and not until then.

**Comment by mdpopescu** [comment]
-1 against removing WinForms.

**Comment by cra0zy** [comment]
Instead of doing something pointless like saying "I'm against it" or "I'm for it" just vote with thumbs up or thumbs down on the original comment/issue...

**Comment by cwensley** [comment]
It would also be helpful to know why winforms is needed vs WPF, so that perhaps we can address those issues.  Right now, it appears we have three reasons:

1. Apps that use WPF may not run in Terminal Server very well.
For this, I would argue that is not the case as many people (including myself) use Visual Studio quite often through Terminal Services which uses WPF extensively.  It doesn't seem to be an actual use case, just supposition.

2. Microsoft still supports Windows Forms.
I'm not sure this is a good metric to support this case.  We don't have the same amount of resources as Microsoft so we have to be more particular on where we spend those resources.  I don't think end users really care about how apps run on their machine, just that they run.  WPF runs on all supported versions of Windows so keeping WinForms provides no added benefit when creating cross platform apps.

3. Some apps may have been already built/tested using WinForms.
This I can totally understand, it takes resources to develop for and test other platforms.  Though with a clear direction, we can get people to eventually migrate to WPF and reduce the number of new projects that depend on WinForms.

Keeping WinForms makes it more difficult and time consuming to add new features or make major enhancements.  People also expect things to work in more modern ways, where WinForms is very limiting (e.g. no support for custom controls in a GridView, etc).

It comes down to the question, why do we need two ways of running apps on Windows?  I'd like to know any reasons (and how many users this affects) so we can make an informed decision on what to do.

**Comment by cra0zy** [comment]
> why do we need two ways of running apps on Windows?

You are forgetting WinRT, so it's actually three ways...

Also you could count Gtk 2 and 3 as well, five ways then...

**Comment by cwensley** [comment]
@cra0zy fair point, though GTK requires additional dependencies and don't feel like native windows apps so I don't really count those. (;

**Comment by SlowLogicBoy** [comment]
> Apps that use WPF may not run in Terminal Server very well.
I was working in a company that wrote only WPF apps and all of them were intended to run through RDP in Windows Server 2008 and newer.

**Comment by TomQv** [comment]
For me only 3. is relevant. We are doing WinForms since many years and now busy with our first app, which is also targeting Mac OS. Its also our first project with Eto. I didn't think of WPF, when we started, choosing WinForms was just automatically. But in the meanwhile we noticed several problems with Eto, which might be the WinForms-Implementation. Its still not too late to switch over. Would you recommend rather using Eto.WPF? Is it more "mature" then Eto.WinForms? Our apps have a long life-cycle, maybe WPF is even better choice for future Windows-Versions?

**Comment by philstopford** [comment]
I'd like to retain WinForms support until such time as there is an OpenGL control available under WPF. That seemed to be a problem up to now, though.

**Comment by smoothdeveloper** [comment]
I'm not using eto forms in production applications, but I'd rather have it support winforms for windows target for the stuff I was planning to use it for.

What is the drawback of keeping winforms? even if some parts aren't implemented, it is up to the users to contribute those if they need it.

Scrapping that codebase just because winforms is not cool or there is some API coverage which is missing compared to WPF seems like a waste of efforts put into supporting winforms in the first place.

**Comment by cwensley** [comment]
@philstopford, couldn't OpenGL be supported under WPF using something like [HwndHost](https://msdn.microsoft.com/en-us/library/system.windows.interop.hwndhost(v=vs.110).aspx)? 

@smoothdeveloper thanks for the feedback, but it would be interesting to know _why_ you require winforms vs WPF.  Removing WinForms would make it easier to implement new features and fix bugs (as was mentioned), not just because it isn't cool.  It takes a lot of work.

I could just not update it, but it would get stale quite quickly.  If someone wanted to step up as the WinForms maintainer that might be an option to help spread the load.

**Comment by smoothdeveloper** [comment]
@cwensley one area is font rendering, things work the way I expect out of the box with WinForms while in WPF it seems to be a real headache, in fact this is true for most system controls.

Right now I'm using WinForms target from scripting / REPL environment, I'll need to check if that still works with WPF.

I think having unsupported features / controls in targets such has WinForms would be fine in order to not hold back development of the API and other targets, those would be considered up-for-grabs for people actually intending to rely on those.

Now I don't have much experience with the project, and definitely can't pretend I could take maintenance of WinForms target.

**Comment by TomQv** [comment]
> couldn't OpenGL be supported under WPF using something like HwndHost?
Yes, I'm using OpenTK.GLControl with WPF this way, works fine:

var glcontrol = new OpenTK.GLControl();
var host = new System.Windows.Forms.Integration.WindowsFormsHost();
host.Child = glcontrol;
var etocontrol= host.ToEto();

**Comment by cwensley** [comment]
@smoothdeveloper have you tried [this](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test.Wpf/Startup.cs#L16-L17)?  It enables GDI font rendering with WPF, if that is what you desire.

**Comment by philstopford** [comment]
@TomQv : do you have a small example project showing this in action? I'm hoping to get some time to try and make this work with etoViewport, but a reference might help me find my way in case of trouble.

**Comment by cwensley** [comment]
Closing as we'll be keeping WinForms for the foreseeable future based on the feedback and the renewed effort for WinForms on .NET 5.
