### ISSUE TITLE
Remove MonoMac platform(s)

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#632]
Now that Xamarin.Mac is free and open source, we can dump the MonoMac platforms.

Xamarin.Mac has a much faster runtime, with better debugging/exception handling, and supports bundling the mono runtime when using Xamarin Studio on a Mac.  

Recent versions of mono also now support nint/nuint/nfloat, so we can run these apps similarly to how MonoMac works, which means we can still create an app bundle on Windows machines that would require mono to be installed.

We should also transition the Eto.Platform.Mac.Template nuget package to include the Xamarin.Mac.dll instead, and see if we can create a 64-bit launcher.  Currently, there seems to only be a 32-bit launcher included with Xamarin.Mac for projects that don't bundle the mono runtime.

MonoMac64 may need to stay around for a bit as I know of at least one company that depends on it still (but hopefully that can change soon). I am unaware of anyone else using it though, unless someone wants to chime in here.

**Comment by Berrysoft** [comment]
@cwensley It's more than two years after. I still cannot bundle a XamMac64 app in Release config.

**Comment by cwensley** [comment]
@Berrysoft thanks for letting me know, however I'm not sure that is relevant to this issue.  This is a placeholder to (eventually) remove MonoMac and MonoMac64 platforms.   Could you file a separate issue with the details of your problem?  Thanks.

**Comment by Berrysoft** [comment]
@cwensley I remember there's a issue saying that we will soon be able to bundle a XamMac64 app on non-Mac OS. But I can't find it.

**Comment by cwensley** [comment]
@Berrysoft you can with MonoMac, just not with Xamarin.Mac at this time.  You need to use the Eto.Platform.Mac64 v2.5.* nuget package, which is available as beta or CI builds on myget.  You also need mono installed for it to perform the bundling of mono inside your app in Release mode.

**Comment by Berrysoft** [comment]
@cwensley You're right. I found I hadn't express it clearly. I succeed in bundle MonoMac app on Windows, but not for XamMac64 app. I wonder when I could bundle a XamMac64 app on Windows.

**Comment by cwensley** [comment]
@Berrysoft Ah that makes more sense, thanks for providing the details.  

My plans on this have changed a little in the light that Xamarin.Mac will probably not run on .NET Core.  Given this, I am planning on adding support for .NET Core to the Eto.Platform.Mac64 package and support bundling a .NET Core based app.

Also, there are new dependencies and custom dylibs, etc that Xamarin.Mac now requires (it is no longer a simple .dll), so bundling using Xamarin.Mac.dll is going to be painful at best and probably break often when they decide to change things.  I do not think it is worth my time trying to constantly play catch up with them (it is hard enough with VS for Mac).

Just curious, what does not meet your needs with the existing bundling using Eto.Platform.Mac64?

**Comment by Berrysoft** [comment]
@cwensley MonoMac works well, but I'm a little worried that it isn't active, because the mono team is focusing on Xamarin.Mac and Xamarin.Forms. I'm afraid it will be deprecated. And by the way, MonoMac is built based on mono, have you found a way to move it to .NET Core?

**Comment by cwensley** [comment]
@Berrysoft I am maintaining a fork of MonoMac specifically for Eto.Forms.  This is also how it got 64-bit support, and it is also pretty much ready to go for .NET Core.  See the fork here: https://github.com/cwensley/monomac

**Comment by Berrysoft** [comment]
@cwensley It seems great! Thanks for your reply!

**Comment by cwensley** [comment]
MonoMac isn't going anywhere, at least until Xamarin.Mac supports .NET Core.  Closing this as we're keeping it for the foreseeable future.
