### ISSUE TITLE
[WPF] Infinite loop in Scrollable

### ISSUE THREAD

**Issue by TripleWhy** [picoe/Eto#638]
Reproduce:

1. Checkot https://github.com/TripleWhy/EtoErrorDemo
Or put a Scrollable inside a TabPage inside a TabControl and set the Scrollable's Border to BorderType.None.
2. Use Windows 10.
3. Go to Windows Settings > System > Screen and set "Change size of text, apps and other elements" to 125% (my Windows isn't english, so the exact names my vary).
4. Logout and Login if you changed the value.
5. Start the Application using WPF.

Scrollable.HandleSizeChanged is now called infinitely,the scrollbars alternate visibility, and the program doesn't continue. I also tried this with 150% and that doesn't have the issue.

I tried to solve this myself (Pull request #636), but my solution breaks Textareas inside Scrollables.

**Comment by cwensley** [comment]
Hey @TripleWhy,

Thanks for reporting the issue!  It has been reported before with issue #477, even with an alternate solution in PR #552.  I haven't been able to reproduce the problem so thanks for putting one together.  I'll give it a try when I get a chance.

Perhaps give PR #552 a test in your environment and let me know if that fixes it for you, it might be a good stopgap solution.  I'd like to find a better solution to this problem, possibly like you tried to do but there's quite a few edge cases as you found so it needs some good testing.

**Comment by TripleWhy** [comment]
Hi,

I am aware of the mentioned issue and PR, however that issue does not mention scaling or borders to be part of the Problem. I also cannot reproduce it with the release version 2.3.0 and therefore did not bother to test the PR. (I cannot compile the mentioned commit 2c78b0f.)

I did now test the PR #552 and It does fix my problem. However I now have 1 free pixel line at the right and bottom that shows the Scroller, but not the Content. (As you would expect from that fix.)
