### ISSUE TITLE
WinForm vs. WPF

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#641]
I changed my current project now from WinForm to WPF.  Was actually easy and with a compiler symbol I can even switch between the two platforms now to compare.

First, WPF looks more modern, nicer, not like old XP anymore, thats nice. I'm using lots of lists and trees with sqlite-dbs and DataBindings. This feels somehow smoother. Must say, very promising.

But, second, there are a lot of bugs in the implementation.
I noticed already several strange issues with WinForms. Most of them are gone with WPF, but now there is other issues. 

Before going into details now I would like to know, if this is still work in progress?

**Comment by cwensley** [comment]
Hey @TomQv,

Thanks for the inquiry!  Yeah, WPF is much more modern looking and in many ways much superior to Windows Forms in terms of performance (there is one drawback, which I'll get to).

As it stands, the WPF platform is "complete", in that there are no major issues or functionality problems (that is known) other than what's been reported on github.  It is also one of the platforms that I focus on heavily for my client work.

If you have any particular problems, then filing them into separate issues with a small test case (if needed) would certainly be helpful.

I hope this clears it up!
Curtis.

**Comment by cwensley** [comment]
Closing this as I believe you've added the separate issues already.  Thanks again!
