### ISSUE TITLE
GtkSharp clipboard issue [with solution]

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#651]
I recently ran into a problem where an image was placed on the clipboard using

    Clipboard cb = new Clipboard();
    cb.SetData(stream.ToArray(), "image/png");

Then, when I pasted into another app (in this case LibreOffice) the image would not be pasted, and the terminal that was running my app showed the following error message:

    Gtk-CRITICAL **: _gtk_selection_request: assertion '(data.format >= 8) 
        && (data.format % 8 == 0)' failed

Some googling later, I found the solution. In the Gtk clipboard handler, on line 130 In the Eto code, the value of zero is used for the format field: 

    AddEntry(type, value, (data, selection) => 
        selection.Set(Gdk.Atom.Intern(type, false), 0, value));

Looking at the error message above, it seemed that a multiple of 8 was needed. So, I copied your implementation of the clipboard handler, changed the zero into an 8 and pasting now works!

    AddEntry(type, value, (data, selection) => 
        selection.Set(Gdk.Atom.Intern(type, false), 8, value));

So, if you could change the zero on line 130 of the Gtk clipboard handler to 8 that would be the solution to this problem.

PS. I could not make a Bitmap object of the byte stream; this gave another error that the format was not supported. The only way to make it work was the approach outlined above.

**Comment by cwensley** [comment]
Thanks for reporting the issue!   It appears the 'data format' is actually the number of bits per 'unit', whatever that means.  Since we're storing bytes, 8 seems reasonable.

**Comment by cwensley** [comment]
By the way, do you have a copy of an image that doesn't load?   I know GTK has problems loading `ico` files that have PNG/compressed images in them..

**Comment by mennodeij** [comment]
>do you have a copy of an image that doesn't load?

Sorry no, the images I work with are generated (graphs from OxyPlot).
