### ISSUE TITLE
[Question] Can Eto Create Accordion Controls/Dialogs?

### ISSUE THREAD

**Issue by 8bitgentleman** [picoe/Eto#665]
I want to create a dialog that functions like this

![photo1258206525175998431](https://cloud.githubusercontent.com/assets/4028391/21904172/c3d72882-d8d0-11e6-82fc-3162b210592f.jpg)
![photo1258206525175998430](https://cloud.githubusercontent.com/assets/4028391/21904174/c6a1c496-d8d0-11e6-8d1b-132dd96ffd50.jpg)

So most options/values are hidden unless the button is pressed and then the dialog expands. 

I've been looking through the [controls page](https://github.com/picoe/Eto/wiki/Controls) of your wiki and your [documentation](http://api.etoforms.picoe.ca/html/R_Project_EtoForms.htm) but haven't found a control that can do what I want. 
Is this possible with Eto? If so, how and what control should I use?

**Comment by SlowLogicBoy** [comment]
Quick and dirty mock-up, sorry for non-standard coding style

```CS
internal class CollapserControl : Panel
        {
        public bool IsCollapsed { get; private set; }
        public bool IsExpanded => !IsCollapsed;

        private Control m_collapsableControl;

        public CollapserControl (Control content)
            {
            m_collapsableControl = content;
            Content = null;
            IsCollapsed = true;
            }

        public void Collapse ()
            {
            Content = null;
            IsCollapsed = true;
            }

        public void Expand ()
            {
            Content = m_collapsableControl;
            IsCollapsed = false;
            }
        }

    internal class MainForm : Form
        {
        public MainForm ()
            {
            var container = new DynamicLayout ();
            var collapser =
                new CollapserControl (new StackLayout
                    {
                    Items = {new Button {Text = "btn1"}, new Button {Text = "btn2"}, new Button {Text = "btn3"}}
                    });
            var collapse = new Button {Text = "^"};
            collapse.Click += (sender, args) =>
                {
                if (collapser.IsCollapsed)
                    {
                    collapser.Expand ();
                    }
                else
                    {
                    collapser.Collapse ();
                    }
                };
            container.AddRow (collapse);
            container.AddRow (collapser);
            Content = container;
            }
        }
```

**Comment by cwensley** [comment]
A more complete example [here](https://gist.github.com/cwensley/9bed58a4f6f440e0a878e0b3542d322c).  No need for a `CollapserControl` of sorts, you can just use the `Visible` property to show or hide the content.

Also created a python equivalent [here](https://gist.github.com/cwensley/004aa3218f159278ded8287346a5b59f).

**Comment by cwensley** [comment]
I think this was answered, let me know if you have any problems with the example.

Cheers!
Curtis.
