### ISSUE TITLE
Changing the content of StackLayout does not respect VerticalContentAlignment

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#677]
When a control in a StackLayout is replaced with a new control, the stack layout's VerticalContentAlignment is not applied when the StackLayout is layed out again.
Repro: make a stacklayout (VerticalContentAlignment = Center) with a label, a combobox and a button. Upon button click, assign a new combo box to the Items[1] of the stacklayout. Result: the label goes from Center to Top vertical alignment.

**Comment by mennodeij** [comment]
This happens on WPF and GTK.

Example:

    public class MainForm : Form
    {
        public MainForm()
        {
            Content = new StackLayout
            {
                VerticalContentAlignment = VerticalAlignment.Center,
                Orientation = Orientation.Horizontal,
                Items =
                {
                    new Label {Text = "Hallo"},
                    new ComboBox
                    {
                        Items =
                        {
                            "Aap",
                            "Noot",
                            "Mies"
                        },
                        SelectedIndex = 1
                    },
                    new Button
                    {
                        Text = "Click me!",
                        Command = ButtonCommand
                    }
                }
            };

        }

        private ICommand _buttonCommand;
        private ICommand ButtonCommand => _buttonCommand ?? (_buttonCommand = new RelayCommand<string>(OnCommandExecute));

        private void OnCommandExecute(string obj)
        {
            StackLayout s = Content as StackLayout;
            if (s == null) return;
            s.Items[1] = new ComboBox
            {
                Items =
                {
                    "Zus",
                    "Wim",
                    "Jet"
                },
                SelectedIndex = 1
            };
        }

**Comment by cwensley** [comment]
Hey @mennodeij,

Thanks for the report and the repro!  Probably an oversight in the implementation.  I'll take a look!

Cheers,
Curtis.

**Comment by cwensley** [comment]
Now fixed!  Thanks a bunch for the error report and repro.  I've turned your repro into a manual unit test as well.
