### ISSUE TITLE
Double Buffered drawing slower than drawing to main Graphics context

### ISSUE THREAD

**Issue by k5jae** [picoe/Eto#678]
It looks like when Graphics.Dispose() is called there is a slow operation taking place. I'm attempting to use multi layer drawing to speed up the painting where it doesn't draw everything every time. The result is worse performance than drawing all elements on the main Graphics context. This is on Ubuntu Gtk2 using daily build. Is there something I'm doing wrong? Is there a high performance sample? I noticed the double buffered sample has the same issue.

**Comment by cwensley** [comment]
This is probably due to the transition to/from a Gdk.Pixbuf.  We could possibly just store the Cairo surface that was drawn, and only convert to a Pixbuf if one is actually needed.

On top of that, the conversion could probably be optimized if the stride and bits are the same as the Pixbuf.

**Comment by cwensley** [comment]
This is now fixed!  Should be extremely fast as it'll use the Cairo surface directly if you subsequently draw the Bitmap on another Graphics context.  

The translation to pixbuf was also really slow and I've improved the performance of that as well.  It now only does this when necessary e.g. using Lock(), or using the image for the ImageView or other UI controls.

**Comment by k5jae** [comment]
Awesome! I'll​ give it a go.

Thanks.
