### ISSUE TITLE
TreeGridView ReloadItem does not always work

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#681]
Example of not working scenario: https://gist.github.com/cra0zy/e9f2742f9496bfe49f52bd81823e6b9d

I think the problem occurs when removing item with subitems, I may be wrong...

**Comment by cwensley** [comment]
Thanks for the report!  Is this on GTK3?

**Comment by cra0zy** [comment]
Both GTK2 and GTK3.

**Comment by cra0zy** [comment]
Thanks for the quick fix :D

**Comment by cwensley** [comment]
@cra0zy no problem! It's best to fix these things while I have it fresh in my mind (;

**Comment by msasso69** [comment]
I noticed that on Mac if no items are selected ReloadItem loops internally forever (precisely in TreeGridViewHandler.ReloadItem/Control.SelectedItems)
![image](https://cloud.githubusercontent.com/assets/21080030/25149963/a889e096-2480-11e7-8bb4-0fa7f6be7984.png)
As you can see from the attached picture despite there are only 7 items in the TreeGridView and Count in SelectedRows is 0, the list in the SelectedItems is endless, as a result the code never exits from the foreach loop in TreeGridViewHandler.ReloadItem.
As a workaround to avoid the infinite loop it is enough to select just an item...

**Comment by cwensley** [comment]
Hi @msasso69,

Thanks for reporting your issue!  Please file a new issue so we can schedule that to be fixed.  If you supply a simple repro it'll get fixed much faster than if not. 

Cheers!
Curtis.

**Comment by msasso69** [comment]
Done => Mac: TreeGridView ReloadItem loops forever if no items selected #787
