### ISSUE TITLE
Panel-Content-Parent  bug

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#682]
When moving a control from one panel to another, the control.Parent-property is not updated:
Or is there another way to find out, in which container a control is?
```
var panel1=new Panel();
var panel2=new Panel();
var label=new Label{Text="Label"};

panel1.Content=label;
Debug.Assert(label.Parent==panel1);    // OK

panel1.Content=null;
panel2.Content=label;
Debug.Assert(label.Parent==panel2);   // not OK, parent is still panel1
```

**Comment by cwensley** [comment]
Thanks for the report!  Are you testing this on the develop branch or 2.3?  There's been a bunch of changes regarding this since 2.3 was released so this may already be fixed.

**Comment by TomQv** [comment]
I'm on the develop branch, using the source-code, but didn't update the last three days, currently using the Commits from Jan 26, 2017 .

**Comment by cwensley** [comment]
Ok good to know, thanks!  Don't bother checking anything newer than that though, I doubt it's fixed since then.
