### ISSUE TITLE
Drag and drop - is it possible

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#690]
Just wondering if d&d is possible - I would like to drop a file onto a running application to open it.
Another would be to drag and drop items between different ListBoxes. Any hints? thx

**Comment by SlowLogicBoy** [comment]
I don't think so. for now.

There is PR for this, however it's a WIP and not active for quite some time https://github.com/picoe/Eto/pull/437

**Comment by cwensley** [comment]
Yeah as @SlowLogicBoy pointed out it's been WIP for a while.  This is actually a duplicate issue of #320.

No promises, but I will likely look at it after the 2.4 release.  Otherwise if someone wants to fix up the PR, that would be great!

Closing this as duplicate.

**Comment by cwensley** [comment]
By the way, if you are only intending on doing D&D within the app you can (probably) handle it using a series of MouseDown/MouseMove/MouseUp events.  Not ideal, but it is an option.

**Comment by SlowLogicBoy** [comment]
> By the way, if you are only intending on doing D&D within the app you can (probably) handle it using a series of MouseDown/MouseMove/MouseUp events. Not ideal, but it is an option.

Do you happen to have an example for this? I have ugly one that I use :/.

**Comment by smoothdeveloper** [comment]
@SlowLogicBoy I have a simple exemple of dragging (click down, move, and click up) in a control:

```fsharp
let makeDraggingEvent (control: Control) =
  let mutable mouseInside = false
  let mutable mouseDragging = false
  let startDragging = Event<_>()
  let stopDragging = Event<_>()
  let dragging = Event<_>()
  
  control.MouseEnter.Add <| fun _ -> mouseInside <- true
  control.MouseLeave.Add <| fun _ -> mouseInside <- false
  control.MouseDown
  |> Event.filter (fun e -> ((e.Buttons &&& MouseButtons.Primary) = MouseButtons.Primary) && mouseInside)
  |> Event.add (fun e -> 
    mouseDragging <- true
    startDragging.Trigger e
  )

  control.MouseUp
  |> Event.filter (fun e -> ((e.Buttons &&& MouseButtons.Primary) = MouseButtons.Primary) && mouseDragging)
  |> Event.add (fun e -> 
    mouseDragging <- false
    stopDragging.Trigger e
  )

  control.MouseMove
  |> Event.filter (fun _ -> mouseDragging)
  |> Event.add (dragging.Trigger)

  startDragging, dragging, stopDragging
```

That function returns me 3 events that I then expose in my control:

```fsharp
type Knob(drawingFunction) as this =
  inherit Drawable()
  let mutable mouseDraggingStartPoint = PointF()
  let mutable mouseDraggingStartValue = 0
  let mutable value = 0

  let startDrag, dragging, stopDrag = makeDraggingEvent this

  let valueChanged = Event<_>()

  do
    startDrag.Publish |> Event.add (fun e ->
      mouseDraggingStartPoint <- e.Location
      mouseDraggingStartValue <- value
    )
    dragging.Publish |> Event.add (fun args ->
      let diff = int ((args.Location.X - mouseDraggingStartPoint.X) / 2.f)
      let newValue = clamp 0 127 (mouseDraggingStartValue + diff)
      this.Value <- newValue
    )
    this.Paint
    |> Event.add (fun args ->
      drawingFunction this args
    )
  member val Text = "" with get,set 
  member x.ValueChanged = valueChanged.Publish
  member x.Value
    with get() = value 
    and set(v) = 
      if v <> value then
        let oldValue = value
        value <- v
        this.Invalidate()
        valueChanged.Trigger (oldValue, value)

```

This works well for simple click / hold / move / release kind of logic but I haven't yet implemented something which is taking objects and droping on a target.

**Comment by smoothdeveloper** [comment]
I concur that I'd like to have framework support instead of rolling my own hackish and not so well designed way to handle that in my application code.

**Comment by SlowLogicBoy** [comment]
> I concur that I'd like to have framework support instead of rolling my own hackish and not so well designed way to handle that in my application code.

Thanks, still better then my solution was.
