### ISSUE TITLE
can't use Eto wpf from script

### ISSUE THREAD

**Issue by smoothdeveloper** [picoe/Eto#696]
I'm trying to play with Eto and WPF platform from the REPL:

Here is the code I have:

```fsharp
#load "./paket-files/include-scripts/net46/include.eto.platform.wpf.fsx"
#r "System.ObjectModel"
#r "System.ComponentModel"
#r "PresentationFramework"
open Eto.Forms

Eto.Platform.Initialize(Eto.Platforms.Wpf)
let form = new Form()
form.Show()
```

it gives a null reference exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eto.Forms.Form.Show()
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\tmp\eto\test.fsx:line 8
```

I've attached a zip you can extract in a folder to reproduce the issue, run build.bat to install the dependencies from nuget, after which you can open test.fsx in VS and by selecting the code and right click "Send to Interactive" try to execute (there is also command to call from command line in build.bat).

[eto.scripting.zip](https://github.com/picoe/Eto/files/751798/eto.scripting.zip)

**Comment by smoothdeveloper** [comment]
Aside, it seems the Eto.Platform.Wpf nuget should have explicit dependencies on `System.ObjectModel`, `System.ComponentModel` and `PresentationFramework` (and others?) so the generated load scripts will do that `#r` work for me.

**Comment by cwensley** [comment]
You're missing an Application object.  When using from a script you may be able to attach it like so, instead of calling `Eto.Platform.Initialize`:

`new Application(Eto.Platforms.Wpf).Attach()`

**Comment by cwensley** [comment]
And as for the aside, those are meant to be used for .net standard / .net core.  There is no PresentationFramework nuget, for example.

**Comment by smoothdeveloper** [comment]
@cwensley you are right, adding even `let app = new Application()` in my script makes it work!

> those are meant to be used for .net standard / .net core

I'm refering to the nuspec which should mention the framework libraries (for .net framework here) used, I think there is a spot to put GAC references, there are other nuget packages which list those and paket can generate the appropriate references.

**Comment by cwensley** [comment]
@smoothdeveloper ah, right I forgot about those.  Those should definitely go in the nuspec.

**Comment by cwensley** [comment]
@smoothdeveloper actually, in thinking about the references we don't want to add these as the references won't necessarily be available (nor should they be required).  

For example, if you add Eto.Platform.Wpf nuget on Xamarin Studio on macOS, it doesn't have PresentationFramework.dll so it won't be able to reference that.  And if you do, the assembly wouldn't be runnable on linux or mac, which you would want if you are using a single launch executable for all platforms.

I hope this makes sense.

**Comment by smoothdeveloper** [comment]
I think in that case the conditionals in the proj file would solve the issue?

Yes I'm not sure about the workflow for multiplatform, I plan (when I'll get there) to have a main project per platform setting up platform and with the references, and in my implementation, if I need custom handling per platform, I'll use compiler defines.

Are there projects in the wild that reference Eto WPF platform and expect it to even compile (outside of windows)? I don't think this is actually doable but I might be wrong.

**Comment by cwensley** [comment]
conditionals in the proj file would work, but there's no way to specify the conditional in the nuspec afaik.  

All Eto projects would reference the Eto WPF platform.  The typical setup is to have a single MyProject.exe that references Eto's GTK, WPF, and Mac platform nuget packages.  It would then build a single .exe which would in effect run on all platforms, as Eto chooses which assembly to load.  You would also be able to build this project on any platform.

Adding the windows-only references would make the Eto.Forms.Sample nuget package and the VS/XS "combined" template useless on linux and macOS as you'd not be able to compile.

**Comment by smoothdeveloper** [comment]
@cwensley paket solves that problem (on client side) as it will put the conditionals so proj file remain stables and will compile on all platforms.

In the nuspec there is a way to specify the targetFramework (https://docs.microsoft.com/en-us/nuget/schema/nuspec#framework-assembly-references).

That said, I believe what you say and understand the concern on building on all targets, I think it is doable with paket but not sure nuget client knows how to deal with conditionals on the references.

**Comment by cwensley** [comment]
Hm, interesting about paket, I have not used it before.

Thanks for pointing out targetFramework, though I don't think it'd help as there's no differentiation between mono on linux/macOS vs. .NET Framework on Windows (they would all be net45).

**Comment by smoothdeveloper** [comment]
paket is a life saver, especially if you have dealt with binding redirects, or packages.config pollution (transitive deps) / or package version inconsistencies in your repositories / solutions / project files.
