### ISSUE TITLE
BitmapData SetPixel () Crashes with AccessViolation

### ISSUE THREAD

**Issue by jaebird** [picoe/Eto#698]
If I use a PixelFormat.Format24bppRgb for a bitmap and then Lock() the bitmap data and try to write near the end of the bitmap (last line of the bitmap), the application crashes with an AccessViolation part way into the line. I think that it is writing past the end of the locked bitmap data bits. It crashes on both Linux and Windows. If I use a bitmap with PixelFormat.Format32bppRgba, all works well

**Comment by cwensley** [comment]
Thanks for the report.  Do you have a sample of something that crashes? it'd help a lot.

**Comment by cwensley** [comment]
As an example, [this test](https://github.com/mcneel/Eto/blob/develop/Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs#L334) passes on all platforms currently, which does as you describe.

**Comment by jaebird** [comment]
I'll try to create something. My ugly workaround is to create a bitmap with
a height slightly larger. I could be doing something wrong.

**Comment by jaebird** [comment]
Can I email you a zipped solution that replicates my issue?

**Comment by cwensley** [comment]
@jaebird sure that's no problem.  Perhaps hop on [gitter.im](http://gitter.im/picoe/Eto) to exchange email addresses.

**Comment by jaebird** [comment]
It was my error.
