### ISSUE TITLE
MyGet Daily Packages

### ISSUE THREAD

**Issue by jaebird** [picoe/Eto#699]
Monodevelop claims that 2.3.0 is an update to the 2.3.0-build### and will revert back to 2.3.0 if an update is done on the packages for the solution. Could this be fixed by bumping myget to 2.3.1-build###?

**Comment by cwensley** [comment]
Ah yikes, you're right.. the myget packages should be 2.4.0-build### which would update to 2.4.0 when released.

**Comment by jaebird** [comment]
Thank you! I've been fighting this for awhile and haven't had time to mention it.

**Comment by cwensley** [comment]
Well I appreciate that you did. 😄   

I'm actually quite surprised that it wasn't mentioned before.  I'll have to make sure to update the release script as well so it doesn't happen again.

**Comment by jaebird** [comment]
That was fast. Thanks.
