### ISSUE TITLE
Monodevelop Addin depends on Xamarin.Mac.dll

### ISSUE THREAD

**Issue by k5jae** [picoe/Eto#701]
The Eto.Forms addin is dependent on the presence of Xamarin.Mac.dll to be in the addin directory. If it is not there, the designer will not preview the xeto file.

**Comment by cwensley** [comment]
Thanks for the report!  Is this when you're trying to use the preview on linux?

**Comment by jaebird** [comment]
I think I have similar issues on both Linux and Windows. Monodevelop 6.3
git from Ubuntu 16.04 will throw an exception, once the dll is placed in
the addin directory, it works. When I use the Windows Xamarin Studio 6.x
latest, I haven't gotten the preview to work even with the dll present. It
stops throwing the exception, but is not displayed.

**Comment by cwensley** [comment]
Thanks for the details, it helps!  

I had only really got the preview working on macOS so far, I still have to get it working for linux.  I wasn't planning on looking at windows as you can just use Visual Studio instead.  Hopefully though, getting it working on linux should also make it work on windows (;

**Comment by benpocalypse** [comment]
Not that this helps, but I'm anxiously awaiting a fix to this, as I do most of my developing in Monodevelop in Linux. Really appreciate the work on this library though - fills a huge hole in the world of cross platform development in my opinion.

**Comment by cwensley** [comment]
Should now be fixed with #974.  A new version of the addin will be published along with the 2.4 release, or you can build it manually.
