### ISSUE TITLE
[WPF] Graphics.Clear() on 32-bit alpha image does not wipe it with transparency

### ISSUE THREAD

**Issue by k5jae** [picoe/Eto#702]
I have a bitmap which is layered onto a control surface, thus must have a transparent background. However, on Windows with WPF, when I want to update elements on the bitmap, if I use the Clear() on the bitmap, elements are not wiped with transparency and are left untouched. If I Clear with a different color, it works, but I lose my lower layers.

This works on Gtk as expected.

**Comment by cwensley** [comment]
Thanks for reporting!  I'll take a look.

**Comment by cwensley** [comment]
Hm, ok I'll need a repro for this.  The test [here](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Drawing/ClearSection.cs#L103-L111) seems to work fine, so there's probably something else needed to replicate the issue.

**Comment by k5jae** [comment]
I should have time to work on this soon.

**Comment by k5jae** [comment]
Here is a repo test case:
https://gist.github.com/k5jae/ef7f5986d87ac922f4cb7d080c4dd090

The gridlines and filter band are drawn on a bitmap. The Red line from 0,0 to width,height is drawn directly on the surface. As the form is resized, all drawn object render directly to surface. Once the resize is complete, the bitmap is updated. On WPF, the Clear() doesn't seem to be working the same way as Gtk. Although this example doesn't "need" the clear since the bitmap is created whenever the form is resized, in the actual application there are other things drawn to the image that are not triggered by resize. In those cases, the bitmap needs to be cleared, so the updated elements can be drawn.

**Comment by cwensley** [comment]
@k5jae awesome, thanks for the repro!  Should make it easier to track down what is going on there.

**Comment by k5jae** [comment]
It would be interesting to know if this sample works fine on mac as well, since that will be a target for me eventually. :)

**Comment by cwensley** [comment]
I usually do test these things on all platforms after fixing it on one.  I may try to turn it into an automated unit test as well.
