### ISSUE TITLE
Eto project addin reference not set exception when creating project

### ISSUE THREAD

**Issue by MNGoldenEagle** [picoe/Eto#703]
Creating a new project using the Eto addin on Visual Studio 2015 causes the following error to appear:
"Object reference not set to an instance of an object."

I'm using the following settings to create the project:
* Name: EtoApp1
* Add to existing solution
* Combined Windows & Linux assembly, separate Mac
* Shared Project
* Xaml

It looks like it can't find the Eto.Serialization.Xaml reference, but it's hard to tell if that's the error preventing the project from finishing or if that's a side effect of the project not finishing.  Not sure if there are log files for creating projects; if so I'll be happy to attach.

**Comment by cwensley** [comment]
I think I know why this is happening, it's possibly because of how the addin has specified what repo to use for nuget (for portable.xaml).  This should hopefully be fixed for 2.4.

Thanks for reporting the issue!

Cheers,
Curtis.

**Comment by cwensley** [comment]
Should be fixed with #986, as it now uses dotnet template engine which should be much more stable (with a lot less custom code)
