### ISSUE TITLE
[Gtk] Dialog in Application.Run outputs Gtk-Critical

### ISSUE THREAD

**Issue by k5jae** [picoe/Eto#708]
If I create a dialog and ShowModal within the main form ctor or on the Application.Run(), Gtk spits out a warning:
Gtk-CRITICAL **: IA__gtk_main_quit: assertion 'main_loops != NULL' failed

It seems that the application runs correctly. Tested in Gtk2

**Comment by cwensley** [comment]
You need to call ShowModal inside the [`Application.Initialized`](https://github.com/picoe/Eto/blob/develop/Source/Eto/Forms/Application.cs#L42) event.

A shortcut for this is something like this:

`new Application.Run(new MyDialog());`

Hope this helps!
Curtis.

**Comment by jaebird** [comment]
I had initially tried that and got the same warning:

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
(Eto.Test.Gtk2:12420): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed
(Eto.Test.Gtk2:12420): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed

**Comment by cra0zy** [comment]
@cwensley You can safely ignore most Gtk warnings, this can be closed since there is no actual error.
