### ISSUE TITLE
[Gtk] Label wrap issue

### ISSUE THREAD

**Issue by jaebird** [picoe/Eto#709]
On Gtk2, when a particular refresh happens, a label that is configured to wrap, will wrap at about 50% of the label control. This can be reproduced by using the Test application under the Controls->Label section. Once visible, press the "Alt" key to cause the label to wrap. Resizing the window will reset the wrap correctly. In user applications, this happens at random times, however, this use case shows the same issue in a repeatable manner.

Tested on Ubuntu 16.10. I believe this issue has been present in Eto.Forms for awhile.

**Comment by cra0zy** [comment]
Here is a sort of a workaround if you need it:
```c#
Style.Add<LabelHandler>("Wrap", h => h.Control.MaxWidthChars = 55);
```

And on the label just need to set the style:
```c#
label1.Style = "Wrap";
```

**Comment by jaebird** [comment]
After a bit of digging, I've worked up a change to Eto.Forms that passes the tests I threw at it. This changes the Source/Eto.Gtk/Forms/Controls/LabelHandler.cs source code. Shown below in diff format:

> @@ -34,9 +34,20 @@ namespace Eto.GtkSharp.Forms.Controls
 			protected override void OnSizeRequested(ref Gtk.Requisition requisition)
 			{
 				int width, height;
\-				Layout.GetPixelSize(out width, out height);
\-				requisition.Width = width;
\-				requisition.Height = height;
\+				if (wrapWidth != null && wrapWidth > 0)
\+				{
\+					Layout.Width = (int)(wrapWidth * Pango.Scale.PangoScale);
\+					Layout.GetPixelSize(out width, out height);
\+					requisition.Width = width;
\+					requisition.Height = height;
\+				}
\+				else
\+				{
\+					Layout.GetPixelSize(out width, out height);
\+
\+					requisition.Width = width;
\+					requisition.Height = height;
\+				}
 			}
 			#else

I can work up a PR if required.

**Comment by jaebird** [comment]
Another label issue was caused by the the one time OnRealized if a label was set as content to a form. The size of the label would not initially be set to the size of the form. The below diff fixes that issue:

>@@ -56,6 +67,25 @@ namespace Eto.GtkSharp.Forms.Controls
 				SetWrapWidth(allocation.Width);
 			}
\+ 
\+			protected override void OnRealized()
\+			{
\+				// the allocation may default to 1, in that case ignore OnRealized
\+				if (Allocation.Width > 1 && wrapWidth != Allocation.Width)
\+				{
\+					Layout.Width = (int)(Allocation.Width * Pango.Scale.PangoScale);
\+					int pixWidth, pixHeight;
\+					Layout.GetPixelSize(out pixWidth, out pixHeight);
\+					HeightRequest = pixHeight;
\+					wrapWidth = Allocation.Width;
\+#if GTK3
\+					if (Parent != null)
\+						Gtk.Application.Invoke((sender, e) => Parent.QueueResize());
\+#endif
\+				}
\+
\+				base.OnRealized();
\+			}
\+
 			void SetWrapWidth(int width)
 			{
 				if (!IsRealized || SingleLineMode || width == 0)

There is a weird init issue that can occur when a Label is within a Layout, the Allocation width is 1. So only do the OnRealized pango layout if the width is > 1. The pango layout stuff could be rolled into a single method instead of copied out like this.

Note, I did not test with Gtk3 with this patch. However, I did grab the #define GTK3, not sure if required.

**Comment by cwensley** [comment]
Hey @jaebird, thanks for looking into the fix.  Yes, a PR would certainly be helpful.

**Comment by jaebird** [comment]
Added PR #713

**Comment by cwensley** [comment]
Thanks again!
