### ISSUE TITLE
Left, Top for controls?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#722]
I want to arrange three CheckBoxes in a Stacklayout:
```
[] Check1
[] Check2
    [] Check2a
```

So I need a kind of Left-property. I could put check2a in another container and use Padding, but maybe there is something simpler?

**Comment by cwensley** [comment]
What you're looking for is more of a `Margin` property.  This should be implemented with #556, but is a ways off.  Using a `Panel` with `Padding` is the way to go at this point.

**Comment by cwensley** [comment]
Closing as there's an alternative and another issue tracking this feature.  Thanks for reporting!
