### ISSUE TITLE
Separate Width / Height properties

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#723]
Currently when setting `Width` of something Eto does:
```
Width
{
    set
    {
        Size = new Size(value, Size.Height);
    }
}
```
which creates a lot of problems because by setting `Width` we are also setting `Height` to the current size of the object, and if you had already set the `Height` to something like `-1` and the control is already visible, it will change the `Height` value of the control.

CC. @cwensley

**Comment by cwensley** [comment]
This also causes problems now that the layout is integrated with WPF and Mac layout systems, so actual width/height is not the same.  E.g. this does not work:

```c#
  var pixelLayout = new PixelLayout();
  var tableLayout = new TableLayout();
  pixelLayout.Add(tableLayout, 0, 0);
  pixelLayout.SizeChanged += (s, e) =>
  {
    tableLayout.Width = pixelLayout.Width;
    tableLayout.Height = pixelLayout.Height; // this sets the width to the current width, not the desired width
  };
```
