### ISSUE TITLE
[Gtk2] Eto.Test application crashes when resized

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#740]
I'm not sure what's changed, but running Eto.Test.Gtk2 on macOS now crashes when you resize the main window.  Happens inside the Splitter like before, even though it is no longer passing false for the shrink parameter of Pack1/Pack2.  I haven't tested on other platforms.

@cra0zy, any ideas?

**Comment by cra0zy** [comment]
It does not crash on Linux, or at least I can't get it to crash.

**Comment by cwensley** [comment]
@cra0zy cool, thanks for looking into that.  I'll see if I can find out what's going on.

**Comment by cra0zy** [comment]
What error do you get in console?
