### ISSUE TITLE
[Mac] Can't get GridViewItem from GridView.ContextMenu

### ISSUE THREAD

**Issue by nast90210** [picoe/Eto#744]
I have GridView and create ContextMenu. But if GridViewItem wasn't selected I can't get item on which ContextMenu was open. Either I can't get item from GridView.MouseDown.

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Looks like we need to add a `GridView.GetCellAt(PointF)` method so you can get the row & column info from a particular mouse position.

**Comment by nast90210** [comment]
It's look like it's only Mac problem. In GTK MouseDownEvent select GridRow that was under cursor. I don't have Windows, so I don't know about WinForm and WPF

**Comment by SlowLogicBoy** [comment]
Winforms - Doesn't select item with right click
WPF - does
