### ISSUE TITLE
Implement Notification and TrayIndicator for Mac

### ISSUE THREAD

**Issue by cwensley** [picoe/Eto#750]

**Comment by cwensley** [comment]
@cra0zy just so you know, I'll have to change the API for Notification a bit for macOS, and probably win10.  Notifications can come in while the app isn't even running, so there'll have to be a way to handle notifications at the Application level.

This probably just means that the `Notification.Activated` event will move to `Application.NotificationActivated`.

I'm thinking an (optional) unique ID and custom data will be passed back so the app developer can lookup what type of notification was sent.

**Comment by cra0zy** [comment]
Okey :)
