### ISSUE TITLE
Possible to do Visual Studio style dockcontrol and panels?

### ISSUE THREAD

**Issue by Linchy** [picoe/Eto#753]
Hi, In Visual Studio you can do the following:

1. Drag panels to new locations via their toolbar, which then docks them to that location
2. On drag it gives a visual indicator to show other locations where the control can be placed
3. Panels can be 'floated' as if they were their own window
4. All panels can be resized

Does anything exist like this out of the box for Eto.Forms?

**Comment by SlowLogicBoy** [comment]
1. and 2. #340 - looks abandoned
3. 4. #710 - similar to this, however no drag and drop or floating (MDI Windows), at least for now and only works for GTK.

**Comment by Linchy** [comment]
Thanks for the answer. Looks like I'll have to change my design

**Comment by cra0zy** [comment]
@Linchy I like the idea for the control, tho it is very hard to make a good docking control :(

> #710 - similar to this, however no drag and drop or floating (MDI Windows), at least for now and only works for GTK.

You can rearange the tabs, if you are referring to that when you say "drag and drop", and the version for the other platforms should come later this week.

**Comment by cra0zy** [comment]
@cwensley This should get closed and moved to: https://github.com/picoe/Eto.Toolkit/issues/9
