### ISSUE TITLE
Mac: TreeGridView ReloadItem loops forever if no items selected

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#787]
I noticed that on Mac if no items are selected ReloadItem loops internally forever (precisely in TreeGridViewHandler.ReloadItem/Control.SelectedItems)

![image](https://cloud.githubusercontent.com/assets/21080030/25339780/1834e44a-2904-11e7-9068-36e23f416062.png)

As you can see from the attached picture despite there is only 1 item in the TreeGridView and Count in SelectedRows is 0, the list in the SelectedItems is endless, as a result the code never exits from the foreach loop in TreeGridViewHandler.ReloadItem.
As a workaround to avoid the infinite loop it is enough to select just an item...

The following simple program reproduces the error:

    using System;
    using Eto;
    using Eto.Forms;

    namespace ReloadItemNotWorking
    {
        public class Program
        {
            [STAThread]
            public static void Main(string[] args)
            {
                new Application(Platform.Detect).Run(new MyForm2());
            }

            public class MyForm2 : Form
            {
                public MyForm2()
                {
                    TreeGridView tree = new TreeGridView();
                    tree.Columns.Add(new Eto.Forms.GridColumn { DataCell = new TextBoxCell(0) });
                    TreeGridItemCollection model = new TreeGridItemCollection();
                    TreeGridItem item = new TreeGridItem();
                    item.Values = new object[] { "text" };
                    model.Add(item);
                    tree.DataStore = model;

                    //tree.SelectedItem = item;
                    tree.ReloadItem(item); // we never exit from this call unless we uncomment the above row

                    Content = new StackLayout
                    {
                        HorizontalContentAlignment = HorizontalAlignment.Stretch,
                        Items =
                        {
                            tree
                        }
                    };
                }
            }
        }
    }

**Comment by msasso69** [comment]
I forgot to say that the verion of Eto is 2.4.0-alpha dated 15th Apr 2017, OS X version: 10.10.5, mono --version: Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/08fd525 Thu Nov 10 20:28:28 EST 2016

**Comment by msasso69** [comment]
I propose the following fix in TreeGridViewHandler.cs:

		public IEnumerable<object> SelectedItems
		{
			get
			{
				**if (Control.SelectedRowCount > 0)
				{**
					foreach (var row in Control.SelectedRows)
					{
						var item = Control.ItemAtRow((nnint2)row) as EtoTreeItem;
						if (item != null)
							yield return item.Item;
					}
				**}
				else yield break;**
			}
		}

**Comment by msasso69** [comment]
If you want I can create a pull request if it helps to speed things up...

**Comment by cwensley** [comment]
@msasso69 yes that would be wonderful, thanks!!

**Comment by cwensley** [comment]
Thanks again for submitting the issue!  Instead, I have fixed the problem with monomac's NSIndexSet which would incorrectly iterate forever in the enumerator even though it has zero items in it.

**Comment by msasso69** [comment]
Thanks Curtis, it works like a charm now. I have to admit that I'm really impressed by the fact that not only you are doing a terrific job with Eto, but you also fix MonoMac! Thanks again!
