### ISSUE TITLE
[Help] Getting Eto to run using Rider on Ubuntu?

### ISSUE THREAD

**Issue by SimplySerenity** [picoe/Eto#802]
Hi guys I'm just trying to get a the very minimum working right now, but everytime I try to run the project I get the "Could not detect platform. Are you missing a platform assembly?" error, but I've got the Eto.Gtk3.dll referenced. Any advice?

**Comment by SlowLogicBoy** [comment]
because it tries to access Gtk2 my guess, you can explicitly tell which platform to use `new Application(new Eto.Wpf.Platform());` in your case that would be GTK3, also you need gtk-sharp3 lib installed

**Comment by cra0zy** [comment]
@SlowLogicBoy You are already correct, he is just missing `gtk-sharp3` package.

**Comment by SimplySerenity** [comment]
@cra0zy @SlowLogicBoy 

Thank you both for your help, that was the issue.
