### ISSUE TITLE
exposing methods to be called by JS in WebView

### ISSUE THREAD

**Issue by everplays** [picoe/Eto#804]
I want to provide a set of functions to be called by JS from WebView. However, based on what I understood from [this](https://github.com/picoe/Eto/blob/7e5fbee1ef4dc0d3c4c470c0e861a4d1f5b65a82/Source/Eto.Gtk/NativeMethods.cs), I do not think there is a way to allow a method to be called with javascript from WebView. Please correct me if I am wrong.

I am not sure how much difficult it would be as C# is not what I speak but I am willing to implement it with your help.

**Comment by cra0zy** [comment]
Just make javascript navigate to something and than stop the webview from navigating, ie:

js side:
```js
window.location.href = "action://button1_clicked";
```

c# side:
```c#


private void Webview1_DocumentLoading(object sender, WebViewLoadingEventArgs e)
{
    if (e.Uri.Scheme == "action")
    {
        switch (e.Uri.Host)
        {
            case "button1_clicked":
                // do something
                break;
        }
        
        e.Cancel = true;
    }
}
```

**Comment by everplays** [comment]
That is a clever workaround, thanks.

One question though:

The JS API already exists and makes a call like `Foo.Bar("some-string")` and I can not change the JS code because there are already other implementations depending on it. Therefore, I should define the `Foo.Bar` method myself using [ExecuteScript](https://github.com/picoe/Eto/blob/9e8f9163a5d470fd3ce33bcb1b2d8dbc3390e733/Source/Eto/Forms/Controls/WebView.cs#L334) with something like this:

```javascript
Foo = {
  Bar: function(param) {
    window.location.href = 'action//bar?param=' + encodeURIComponent(param);
  }
}
```

Now, the question is that when should I make the `ExecuteScript` call to be sure that these methods will be defined before JS actually tries to call them? Right now, I think `OnDocumentLoaded` is my best bet but I am not sure.

**Comment by cra0zy** [comment]
> Right now, I think OnDocumentLoaded is my best bet but I am not sure.

Yup, that is it.

**Comment by everplays** [comment]
For the record, I had to use `DocumentLoading` because if I used `DocumentLoaded`, the JS codes that used `document ready` event or made the call in the html body would fail. The rest worked as expected.
