### ISSUE TITLE
GridViewHandler.DataStore slow on WPF

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#811]
This took me a while now...

I'm using a sqlite-table object as datasource for a GridView to benefit from the virtual loading of huge amount of records. 
My datastore is:
 public class ListCursor : IList, IEnumerable<object> 
which fetches the records from sqlite as they are needed to display.

Works perfect in Eto.Winform, but in Eto.WPF was very slow.

Difference is:
Eto.Wpf.Forms.Controls.GridViewHandler.DataStore.Set is changing this to ObservableCollection, which loads all records first, and WinForm not. 

So for WPF I had to change my datastore  to:
 public class ListCursor : IList, IEnumerable<object>, INotifyCollectionChanged

Don't know, if this is by intention... just saying. I'm also not sure anymore, if this was always like this, somehow I feel, that this was fine in the past.

Tom

**Comment by TomQv** [comment]
> So for WPF I had to change my datastore to:
> public class ListCursor : IList, IEnumerable, INotifyCollectionChanged

doesn't work when editing cells, then all records starting from first one are read again from database....
why? should only affect the one which was just edited.

**Comment by TomQv** [comment]
ok, what makes the GridView in WPF nearly unusable for large sqlite-tables is
GridViewHandler.GetItemAtRow (int row), because this calls IEnumerable.ElementAt() which alway loads everything from first element in GetEnumerator().

In Winforms, this is solved different, works much better, didn't check Mac yet,

**Comment by cwensley** [comment]
Thanks for the report!  I have a fix coming..
