### ISSUE TITLE
Get Array of Controls and call Static method in XAML 

### ISSUE THREAD

**Issue by markokosticdev** [picoe/Eto#820]
Can I write something similar for getting Array of Controls:
XAML:
```
<x:Array Type='{x:Type Button}'> 
  <Button /> 
  <Button /> 
</x:Array> 
```

CLASS:
```
Button[]  buttons;

public MainForm ()
		{
			XamlReader.Load (this);
                        buttons[1].Text = "text...";
		}
```

How to call Static method in XAML 
CODE:

`new ImageView{Image=Icon.FromResource ("image.png")}
`

**Comment by cwensley** [comment]
To get the button array, you need to use x:Name, e.g.
```
<x:Array Type='{x:Type Button}' x:Name='buttons'> 
```

As for getting a resource, you can use the Resource markup extension.  E.g.

```<ImageView Image='{Resource image.png}'/>```

**Comment by markokosticdev** [comment]
This does not work for me

```
<x:Array Type='{x:Type Button}' x:Name='buttons'> 
  <Button /> 
  <Button /> 
</x:Array> 
```
I get exception in XamlReader line  again but again again {Resource image.png} work thank you!

**Comment by cwensley** [comment]
What is the exception?

**Comment by cwensley** [comment]
This works:

```
<?xml version="1.0" encoding="UTF-8"?>
<Panel 
xmlns="http://schema.picoe.ca/eto.forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
xmlns:e="clr-namespace:Eto.Test.Sections.Controls;assembly=Eto.Test" 
xmlns:l="clr-namespace:Eto.Test.Sections.Serialization.Xaml;assembly=Eto.Test" 
>
	<Panel.Properties>
		<x:Array Type='{x:Type Button}' x:Key="MyButtons"> 
  			<Button /> 
  			<Button /> 
		</x:Array> 
	</Panel.Properties>
	<!-- other content -->
</Panel>
```

Then in the code behind:

```c#
var myButtons = Properties.Get<Button[]>("MyButtons");
```

Now, if you want to get an array or list of all buttons *within* a container, then you'd just iterate and turn that into a list using the `Children` property, like so:

```c#
var buttons = myContainer.Children.OfType<Button>().ToArray();
```

Hope this helps!
