### ISSUE TITLE
OpenFileDialog Mac

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#826]
Any idea, how to turn off this animation, when showing a OpenFileDialog with Eto.Mac? I would like the dialog just to show up immediately without this "unfolding-effect".

**Comment by cwensley** [comment]
You should just be able to pass null to the ShowDialog() method.

**Comment by cwensley** [comment]
@TomQv did that work for you?  If so, it would be great to know and close the issue.

**Comment by TomQv** [comment]
Yes, all good, thank you.
Close issue.
