### ISSUE TITLE
Extending Taskbar with controls

### ISSUE THREAD

**Issue by SlowLogicBoy** [picoe/Eto#827]
It would be nice to have ability to add controls to taskbar in windows (I don't know how other platforms behave with this):
![image](https://user-images.githubusercontent.com/3121637/27213957-85e07fda-5272-11e7-8a0f-49c06612d0c7.png)

**Comment by cra0zy** [comment]
Mac/Linux don't have anything similar to that so I don't think it would be a good idea to add it to the Eto API.

You can always use custom code for your Windows build to add those buttons.

**Comment by cra0zy** [comment]
@cwensley This should be closed since its a platform specific thing.

**Comment by SlowLogicBoy** [comment]
This I guess could be added to Eto.Toolkit for windows specific stuff ;). Also if app uses TrayIcon this can be done there.

**Comment by cra0zy** [comment]
Eto.Toolkit is meant for controls that exist on all platforms, so no.

This is a Windows specific thing so it makes no sense trying to wrap it.

**Comment by cwensley** [comment]
Yeah there's no real point wrapping a platform-specific api when it's only ever going to work on a single platform.. you might as well just use that platform-specific API directly.  

If there's at least two platforms with similar functionality then it would make more sense to do.
