### ISSUE TITLE
Eto.Forms Visual Studio Addin for Visual studio 2017 and Visual studio 2017 for Mac

### ISSUE THREAD

**Issue by EbramSamy** [picoe/Eto#829]
Is there Eto.Forms Visual Studio Addin for Visual studio 2017 and Visual studio 2017 for Mac ?

**Comment by DanWatkins** [comment]
I think this is covered in #772

**Comment by EbramSamy** [comment]
OK that is for Mac is there Eto.Forms Visual Studio Addin for Visual Studio 2017 for windows?

**Comment by cwensley** [comment]
@EbramSamy that issue is for both so I will close this as duplicate.  I will be working on the addins soon as 2.4 is nearing release. (;
