### ISSUE TITLE
Get current active window (similar Form.ActiveForm)

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#830]
How can I get the current active window (if there are several opened SDI document windows)? Similar to the Form.ActiveForm property of WinForms

**Comment by cwensley** [comment]
Try `var activeForm = Application.Instance.Windows.FirstOrDefault(f => f.HasFocus);`

**Comment by Serg-Norseman** [comment]
Strange result from time to time. But let it be so.
