### ISSUE TITLE
WPF: error in setter Scrollable.ScrollSize

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#833]
Assigning a value to the Scrollable.ScrollSize property results in an error: 
> Unable to cast object of type 'EtoScrollViewer' to type 'System.Windows.Controls.Border'.

I think the bug is in `Eto / Source / Eto.Wpf / Forms / Controls / ScrollableHandler.cs`, 
`public Size ScrollSize`, in the line 
`var content = (swc.Border) Control.Child;`

I found another solution for my needs. But the above error still exists.

**Comment by Serg-Norseman** [comment]
#480

**Comment by cwensley** [comment]
Thanks for finding the duplicate!  And thanks for helping narrow down the cause.

**Comment by Serg-Norseman** [comment]
To fix this, in theory, it is very easy - this line is not used in any way

**Comment by cwensley** [comment]
Cool!  Care to test it out and see if it actually works for you?  A PR would be very helpful as well if you have the time.

**Comment by Serg-Norseman** [comment]
Yes, I will try. For my project I need a lot of different functions and me will probably have to deal with all the detected inconsistencies.
