### ISSUE TITLE
Scrollable and nested Drawable

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#837]
How is it possible that after I set the size of the nested Drawable component in the Scrollable component, at the last ClientSize is equal to anything - or the Size of the component is -1, -1, or equal to the size of the nested Drawable, and even from Bounds I can not find out the real size of the Scrollable component. No property works as expected. I've been fighting for three days on the program and there's only one garbage left. Accessing ClientSize or ClientRectangle (in Scrollable) during drawing leads to an exception. How does it work? How at runtime is the component, find out its real size, if accessing VisibleRect during drawing also leads to an exception?

**Comment by SlowLogicBoy** [comment]
> Accessing ClientSize or ClientRectangle (in Scrollable) during drawing leads to an exception. How does it work?

What exception? most likely it happens because OnPaint/Drawing is happening on different thread.

To Find out size OnPaint event argument has property called ClipRectangle, which determines size of drawable area.

**Comment by Serg-Norseman** [comment]
> most likely it happens because OnPaint/Drawing is happening on different thread.

How is this possible? I have a Drawable drawing handler, implemented in Scrollable. In the drawing process, I refer to the ClientSize, ScrollPosition, or other properties of the Scrollable component. And I get an exception. How should this be implemented? Your answer only gives more questions.

**Comment by Serg-Norseman** [comment]
Ok. Let's assume. And another question, say outside the drawing mode, I need for some calculations of the content, and find out the size of the viewable Scrollable component (Visible area size, "Viewport"). How to do it? I was trying to: Width, Height, Size, Bounds, ClientSize (Scrollable). All of them return -1, -1. But VisibleRect, at some points in time, produces the correct size, in some nested Drawable size, in most cases -1, -1. The ScrollSize property has a real content size - Drawable size. So how do you know the size of a Visible region?

**Comment by SlowLogicBoy** [comment]
``` cs
using Eto.Forms;

var app = new Application(new Eto.Wpf.Platform());

var form = new Form {
    Content = new Scrollable  {
        Content = new Drawable()
    }
};

form.LoadComplete += (s, e) => {
    form.Invalidate(); 
    form.Dump(); //Step 2: After invalidate sizes become 0 (since they are still not visible)
};

form.KeyDown += (s, e) => {
        form.Dump(); //Step 3: After I press any key I get correct sizes
};

app.Run(form.Dump()); //Step 1: Here I get sizes -1
```
Try invoking `Invalidate()` method in `LoadComplete` event, this might help since it helped me.

**Comment by Serg-Norseman** [comment]
Thank you. Your advice did not work for me, but led me to the idea of what to try to change in my code. The idea worked. Prior to that, I equally tried to take the VisibleRect property in the OnSize and OnScroll handlers of the component. At the same time, I worked so hard that only today I thought that if the VisibleRect property on OnSize contains only the correct size, and with OnScroll only the correct position of the scroll, then it's necessary to process them separately. Separate buffering of the size and position for internal purposes helped. At least the result is still not perfect, but better than it was.
