### ISSUE TITLE
[Wpf] MouseEnter not hit when a "selected" item is in the Menu

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#839]
Hi All,

I noticed that when I add one or more ButtonMenuItem in the Menu the first item in the Menu is initially selected, this prevents me to use the override MouseEnter in whatever control untill I click anywhere in the main form or in any of its children. 
This is very annoying because I cannot force the user to click on the form with no reason.

What I say is easily reproducible with the following simple code:

	using System;
	using Eto;
	using Eto.Forms;
	using Eto.Drawing;

	namespace MouseEnterNotHitWhenEnabledMenuItemIsPresentInTheMenu
	{
		public class Program
		{
			[STAThread]
			public static void Main(string[] args)
			{
				new Application(Platform.Detect).Run(new MyForm());
			}
			
			public class MyForm : Form
			{
				public MyForm()
				{
					Width = 50;
					Height = 100;

					Content = new StackLayout
					{
						HorizontalContentAlignment = HorizontalAlignment.Stretch,
						VerticalContentAlignment = VerticalAlignment.Stretch,
						Items = 
						{
							new StackLayoutItem(new MyClass(), true)
						}
					};

					Menu = new MenuBar
					{
						Items =
						{
							new ButtonMenuItem() { Text = "text1" }
							//new ButtonMenuItem() { Text = "text1", Enabled = false }
						}
					};
				}
			}

			public class MyClass : Drawable
			{
				public MyClass()
				{
					BackgroundColor = Colors.Yellow;
				}

				protected override void OnMouseEnter(MouseEventArgs e)
				{
					base.OnMouseEnter(e);
					BackgroundColor = Colors.Blue;
				}

				protected override void OnMouseLeave(MouseEventArgs e)
				{
					base.OnMouseLeave(e);
					BackgroundColor = Colors.Red;
				}
			}
		}
	}

Commenting the ButtonMenuItem I get the desired behaviour, but I need a MenuBar in my application.

I also noticed that setting Enabled = false to the ButtonMenuItem the form detects the MouseEnter event without having to click on it, but if for example I re-enable the ButtonMenuItem programmatically (let's say in the OnLoadCompleted) then I again have to click on the form so that the MouseEnter works again.

I would like to point out that there is no need for the items in the MenuBar to be initially selected.
Is it possible to avoid that the items in the MenuBar, the first one to be precise, is initially selected?

On Mac I do not have this strange behaviour, only in Wpf, I haven't tried on WinForms nor on Linux.

Can somebody please help? 
Thanks
Massi

**Comment by cwensley** [comment]
This probably has something to do with the fact that you don't have any focusable controls on your form.  If you set MyClass.CanFocus = true, then it should set it as the currently focused control.

However, it should be triggering the MouseEnter event when the mouse hovers over the control.  Does it not even fire when you move the mouse outside of the control and then back in?

**Comment by msasso69** [comment]
Yes Curtis! Thank you very much for your quick answer! It works like a charm now! :)
I endeed tried to use myClass.SetFocus() but it had no effect since I was missing this myClass.CanFocus property!
Thanks again. Problem Solved! :)
