### ISSUE TITLE
Multiline Label height measurement issues

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#843]
It seems that Eto has some issues when measuring Labels with wrapped text. It only seems to work correctly with GTK, on WPF you need to resize the form horizontally in order to view the contents at the bottom of the form (scrolling won't work because the scrolling area is cut above the end of the form). On MonoMac it is even worse, you'll need to increase the form size in both directions in order to view the rest of the controls on the form. Screenshots will follow to demonstrate the issue.

**Comment by DanWBR** [comment]
On GTK, no issues, layout is shown correctly (scrollbar goes until the end of the layout area):

![captura de tela 2017-08-01 as 08 56 12](https://user-images.githubusercontent.com/2669419/28826701-0b8c0830-7699-11e7-8f10-20f94c7cb969.png)

On WPF, you need to resize the form to view the bottom contents:

![captura de tela 2017-08-01 as 08 58 30](https://user-images.githubusercontent.com/2669419/28826737-262ec240-7699-11e7-93fe-acf56ae98673.png)

![captura de tela 2017-08-01 as 08 58 49](https://user-images.githubusercontent.com/2669419/28826748-2e6cfb8e-7699-11e7-878f-27375b773cdc.png)

On MonoMac, even more manual resizing work is required...

![captura de tela 2017-08-01 as 08 59 43](https://user-images.githubusercontent.com/2669419/28826766-3e127a1e-7699-11e7-81ef-87d09b483507.png)

![captura de tela 2017-08-01 as 09 00 09](https://user-images.githubusercontent.com/2669419/28826776-47662c96-7699-11e7-91b4-57e2fc7b3f59.png)

![captura de tela 2017-08-01 as 09 00 14](https://user-images.githubusercontent.com/2669419/28826794-53b33796-7699-11e7-84ca-604a199bd0da.png)

**Comment by cwensley** [comment]
Thanks for reporting the issue!  What version of Eto are you using?

**Comment by DanWBR** [comment]
Hi Curtis, I'm using version 2.3.0 from NuGet. Congratulations by the way, Eto.Forms is a fantastic piece of work.

**Comment by cwensley** [comment]
@DanWBR ok, good to know.  This may already be fixed in Eto 2.4 (which is not released yet), but you can try it by adding the [myget](https://www.myget.org/F/eto/) feed to your nuget sources and using the pre-release versions.

**Comment by cwensley** [comment]
Thanks for the nice comments btw, it's very much appreciated!  I'm glad you've found it useful.

**Comment by DanWBR** [comment]
You're welcome. I'm currently working on a new interface for DWSIM (https://github.com/DanWBR/dwsim4), a Chemical Process Simulator. The new code isn't public yet but I have a video with what I've done so far: https://www.youtube.com/watch?v=1IUG6hMs8Uo

I'm focusing on using WPF on Windows, GTK 2 on Linux and MonoMac on OSX. This enables compilation of the whole project for all platforms using a single solution on Visual Studio on Windows.

I'm using SkiaSharp (https://github.com/mono/SkiaSharp) for the Process Flowsheet Diagram designer, and I've managed to successfully create an Eto control layer for the SkiaSharp canvas. I can create a separate project for it if you're interested, it may be useful for someone else.

**Comment by cwensley** [comment]
Hey @DanWBR, wow that looks very impressive!

I have been meaning to look into integrating SkiaSharp, and that would be extremely useful to a lot of people (including myself!).

**Comment by DanWBR** [comment]
@cwensley v2.4.0 partially fixes this issue. WPF now works as expected (scrollbar ok), but MonoMac still looks the same (no scrollbar and bottom contents remain hidden from the user until the form is manually resized).

![captura de tela 2017-08-01 as 14 46 16](https://user-images.githubusercontent.com/2669419/28842346-4ec45062-76cb-11e7-80e6-6372229e50e6.png)

![captura de tela 2017-08-01 as 14 47 50](https://user-images.githubusercontent.com/2669419/28842367-6d098dee-76cb-11e7-9e67-5fd506e9e227.png)

**Comment by cwensley** [comment]
@DanWBR The scrollbar on macOS might actually be there, but it doesn't show until you start scrolling..  Also, when you resize the form it should show the scroll indicator for a brief moment.  If it is indeed still not showing, let me know.

**Comment by DanWBR** [comment]
@cwensley It isn't there, I've tried scrolling with the touchpad, it does scroll but only the visible part of the form is shown ("rubber/stretching" effect). The rest of the controls at the bottom will only appear after you resize the form.

**Comment by cwensley** [comment]
Ok that definitely sounds like a bug then.  Do you have time to put together a simple sample that reproduces it?  It would help greatly in fixing the problem.

**Comment by DanWBR** [comment]
@cwensley here's a sample code which will demonstrate the issue:

`using System;
using System.Collections.Generic;
using Eto.Drawing;
using Eto.Forms;
using Editors;

namespace Editors
{
    public class Class1
    {

        public void Create()
        {

            var container = new DynamicLayout();

            container.BeginVertical();
            
            container.Padding = 10;

            CreateAndAddLabelRow(container, "Property Packages");

            CreateAndAddDescriptionRow(container, "A Property Package is a set of " +
                "models and methods/equations which are responsible for the calculation of compound and phase properties and for providing " +
                "thermodynamic properties for Unit Operation calculations, like enthalpy and entropy.\n\n" +
                "You need to add at least one Property Package to your simulation.");

            CreateAndAddDropDownRow(container, "Add New Property Package", new List<string>() {"item1", "item2" }, 0, (sender, e) => { });

            CreateAndAddLabelRow(container, "Added Property Packages");

            CreateAndAddLabelRow(container, "Flash Algorithms");

            CreateAndAddDescriptionRow(container, "The Flash Algorithms in DWSIM are the components responsible for determining a particular set " +
            "of phases at thermodynamic equilibrium, their amounts (and the amounts of the compounds on each phase) at the specified conditions like " +
            "Temperature, Pressure, Total Enthalpy and Total Entropy. Some Flash Algorithms are capable of predicting equilibrium between one vapor " +
            "and one liquid phase, while others support another co-existing liquid and/or solid phase. As the amount of phases considered in " +
            "equilibrium increases, the calculation time/complexity also increases while the results' reliability decreases.\n\n" +
            "Some flash algorithms are more capable/reliable than others, depending on the mixture for which the flash calculation request is being " +
            "requested. DWSIM features a selection of flash algorithms that are capable of calculating VLE, VLLE and SLE.\n\n" +
            "The 'Nested Loops (VLE)' algorithm satisfies the requirements of most Vapor-Liquid Equilibria systems.");

            CreateAndAddDropDownRow(container, "Add New Flash Algorithm", new List<string>(), 0, (sender, e) => { });

            CreateAndAddLabelRow(container, "Added Flash Algorithms");

            CreateAndAddEmptySpace(container);

            container.EndVertical();

            container.Width = 500 - container.Padding.Value.Left * 2 - container.Padding.Value.Right * 2;

            List<TabPage> tabs = new List<TabPage>();

            tabs.Add(new TabPage(new Scrollable { Content = container, Border = BorderType.None }) { Text = "Thermo" });
            tabs.Add(new TabPage(new Panel()) { Text = "Reactions" });

            var tabctrl = new TabControl();
            foreach (var tab in tabs)
            {
                tabctrl.Pages.Add(tab);
            }

            var form = new Form() { Content = new Scrollable { Content = tabctrl, Border = BorderType.None }, ClientSize = new Size(500, 400) };
            form.Show();

        }

        public static void CreateAndAddEmptySpace(DynamicLayout container)
        {
            container.AddRow(new TableRow(new Label { Text = "", Height = 10 }));
        }

        public Label CreateAndAddLabelRow(DynamicLayout container, String text)
        {
            var label = new Label { Text = text, Font = SystemFonts.Bold(null, FontDecoration.None), Wrap = WrapMode.Word };
            container.AddRow(new TableRow(label));
            CreateAndAddEmptySpace(container);
            return label;
        }

        public static void CreateAndAddDescriptionRow(DynamicLayout container, String text)
        {
            container.AddRow(new TableRow(new Label { Text = text, Wrap = WrapMode.Word, Font = SystemFonts.Label(SystemFonts.Default().Size - 2.0f) }));
            CreateAndAddEmptySpace(container);
        }
        
        public static DropDown CreateAndAddDropDownRow(DynamicLayout container, String text, List<String> options, int position, Action<DropDown, EventArgs> command)
        {

            var txt = new Label { Text = text, VerticalAlignment = VerticalAlignment.Center };
            var drop = new DropDown { Width = 200 };

            foreach (var item in options)
            {
                drop.Items.Add(item);
            }

            drop.SelectedIndex = position;

            if (command != null) drop.SelectedIndexChanged += (sender, e) => command.Invoke((DropDown)sender, e);

            var tr = new TableRow(txt, null, drop);

            container.AddRow(tr);
            CreateAndAddEmptySpace(container);

            return drop;

        }

    }
}
`

**Comment by liciobruno** [comment]
I have a similar problem with Eto Forms 2.4.1 and F#
If I insert a Scrollable without manually setting the size, I don't have the scrollbars (the content is intentionally bigger than the main form). To have the scrollbars I need to set a size, and then they are displayed, but in this way I cannot resize the Scrollable.
Is it the same bug?

**Comment by cwensley** [comment]
Ok this particular case is now (mostly) working on Gtk, Gtk3, Gtk2, Mac, XamMac, and WPF.  On Mac and WPF it sizes the scroll area based on the preferred size instead of the actual size.  I'll create a separate issue to track that.
