### ISSUE TITLE
GTK2 - DropDown truncated list item text issue on v2.4.0

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#845]
List item text is being truncated on DropDown in v2.4.0. It was working nicely on v2.3.0.

Code to reproduce: https://gist.github.com/DanWBR/4042e0446916cffeb895cf0266cce335

![captura de tela 2017-08-01 as 16 09 57](https://user-images.githubusercontent.com/2669419/28845245-5e8e178a-76d5-11e7-94e3-008bf2e5690b.png)

It seems to happen only with strings with more than 2 chars (in the screenshot below, second item is "ENG" and third one is "CGS"):

![captura de tela 2017-08-01 as 16 07 30](https://user-images.githubusercontent.com/2669419/28845277-75770498-76d5-11e7-95d9-631f001cc1db.png)

This doesn't happen on WPF or in MonoMac.

**Comment by DanWBR** [comment]
Maybe this is the culprit? https://github.com/picoe/Eto/commit/d3022a9f7e7f5382836587f748b6b3ed5167448e

**Comment by cra0zy** [comment]
> Maybe this is the culprit? d3022a9

I did ask you to skip setting `Width` in my last comment to check exactly that...

**Comment by DanWBR** [comment]
@cra0zy I checked now, it only happens when I set `Width`.

**Comment by DanWBR** [comment]
@cra0zy Can I revert this using a style, for now?

**Comment by cra0zy** [comment]
Okey, I know what needs fixing now.
