### ISSUE TITLE
Mac-app crash on start

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#848]
With the latest commit from  Aug 1, 2017 my XamMac2-app crashes on start in MacView.cs line 604 

Messaging.void_objc_msgSendSuper_CGRect(control.SuperHandle, sel, rect);

Removing this line makes the app start.
I noticed lots of changes in this file since last version...

Tom

**Comment by cwensley** [comment]
Hey @TomQv, has something else changed on your end?  Nothing was committed on August 1st that touches any part of the Mac platform or even the public API.   Perhaps you're using the beta or alpha version of Xamarin.Mac?  Also check that you're only linking the framework assemblies and not all assemblies in Release mode.

With the stable channel of Xamarin I don't see any issues on my end so if you have any insight that would help.

**Comment by TomQv** [comment]
Here is commit from 1.Aug:
https://github.com/picoe/Eto/commits/develop
and the MacView.cs has lots of changes. I didn't change anything else.

**Comment by cwensley** [comment]
Hm, I'm not seeing the same thing you are.. there's only two changes [here](https://github.com/picoe/Eto/commit/126d179fa444325264b6bc768f331aeda7ec4b33) and [here](https://github.com/picoe/Eto/commit/545dad8cbd03a2275db5f19759532e186014c39a), neither are touching MacView.cs

**Comment by cwensley** [comment]
<img width="995" alt="screen shot 2017-08-07 at 9 33 31 am" src="https://user-images.githubusercontent.com/367446/29036251-88d7abd2-7b53-11e7-9e5d-a029b53d0140.png">

**Comment by TomQv** [comment]
https://github.com/picoe/Eto/blob/develop/Source/Eto.Mac/Forms/MacView.cs#L604

This line was not in  my previous version. Ok, I dont know, when it was added, I didn't update for a while. Just downloaded the recent commit now.

**Comment by cwensley** [comment]
Yeah that was updated 3 months ago, after looking at the blame.  It seems like it'd have something to do with setting the BackgroundColor of a control.  It appears to work with MonoMac with Eto.Test, but not with Xamarin.Mac.  Thanks for the report, I'll look into it.

**Comment by cwensley** [comment]
Thanks again for reporting the issue @TomQv, it really helps out.  This should now be fixed!

**Comment by TomQv** [comment]
Thanks for the quick fix, its fine now.
(how is one suppose to know this :) I'm a windows-developer and the mac is driving me crazy.....)

**Comment by cwensley** [comment]
> how is one suppose to know this :) I'm a windows-developer and the mac is driving me crazy.....

Testing, testing.. and more testing (;

It's the same for Gtk if you aren't familiar with it.  And WPF.. and WinForms..  Things like this would (eventually) be caught before releasing though, as it's a supported test case.  I don't run the tests on all (mac) platforms for each commit so things can get out of whack in the develop branch.

Right now I use MonoMac primarily while developing due to it being used for the projects I work on (albeit 64 bit), however that will eventually transition to Xamarin.Mac making these sorts of issues less frequent on the develop branch.
