### ISSUE TITLE
Add TextChangingEventArgs.NewText property

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#866]
It would be way more useful if TextChangingEventArgs provided `OldText` and `NewText` next to `Cancel` instead of the stuff it currently contains.

**Comment by cwensley** [comment]
OldText is equivalent to Control.Text, and NewText could be calculated from Control.Text and the arguments provided.

They currently are very useful for the `MaskedTextBox` and other controls.

**Comment by cra0zy** [comment]
If you have the old and new text you can just as easy calculate the reverse. In more situations you'd just be interested in the new text, not what got replaced.

**Comment by cwensley** [comment]
I would say it's not quite as easy to do the inverse; you'd need to iterate through all characters of the two strings, and you would also not know that someone selected a portion of the text and replaced it with a single character, for example.  

Regardless, adding a 'NewText' property to the args would certainly be useful for those situations where you just care about the entire string.

**Comment by cra0zy** [comment]
> I would say it's not quite as easy to do the inverse; you'd need to iterate through all characters of the two strings, and you would also not know that someone selected a portion of the text and replaced it with a single character, for example.

1) "Testing", user selects "ing", types in "i", you get "Testi"
2) "Testing", user selects "ng", preses delete, you get "Testi"

Does it really matter for your software to know which one of those 2 happened? you only care about start and end result.

**Comment by cwensley** [comment]
It depends on whether the information of relevance is the text or the text the user is inputting.  In some cases, for example the MaskedTextBox, the relevant information isn't the final string but the new text that is being entered in.

I'm not sure why we need to remove any functionality here, is there something I'm missing?

**Comment by cra0zy** [comment]
> It depends on whether the information of relevance is the text or the text the user is inputting. In some cases, for example the MaskedTextBox, the relevant information isn't the final string but the new text that is being entered in.

My example wouldn't make a difference on MaskedTextBox.... yes it does not use end string in the same sense, but it would still behave the same non the less.

> I'm not sure why we need to remove any functionality here, is there something I'm missing?

While reimplementing NativeGTK I skipped adding part of functionality of the args, they seemed... redundant...

**Comment by cra0zy** [comment]
> While reimplementing NativeGTK I skipped adding part of functionality of the args, they seemed... redundant...

I mean it makes no sense to perform the calculations on the per platform side, when you can achieve the same thing be performing them on PCL side.

**Comment by cwensley** [comment]
Hey @cra0zy is this still going to be an issue now that we've switched gears back to using gtk#?

**Comment by cra0zy** [comment]
I mean I would still like to make them better.
