### ISSUE TITLE
WPF CheckBoxCellHandler events not fired

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#871]
was trying now for 2h to figure out, why no event is fired when clicking on a Checkbox-Cell in a TreeGridView. Its working with Mac, but not with WPF.
Must be something in Eto.Wpf.Forms.Cells.CheckBoxCellHandler
Any help would be appreciated.
Tom

**Comment by cwensley** [comment]
Which event are you trying to use?  CellClick/CellDoubleClick?

**Comment by cwensley** [comment]
Hm, there are no Checked/Unchecked events on CheckBoxCell..  It uses the binding to set a boolean value.

**Comment by cwensley** [comment]
And for WPF I believe the GenerateEditingElement isn't used as it is already editable with the default view.  Unlike things like a TextBoxCell, which will only show the TextBox when editing

**Comment by TomQv** [comment]
yes, of course,  but internally on the native side, the events are used for that. So GenerateEditingElement  must be called.

**Comment by cwensley** [comment]
You did set `GridColumn.Editable = true`, right?  Other than that, a simple example of what you're trying to do would help as I'm not sure what is actually the problem here.  Is the binding to get/set the boolean value on your model not working?

**Comment by TomQv** [comment]
Yes...  I added a CheckBoxCell to your Test.TreeGridViewSection and everything is working correctly.
So its my problem, must figure out, where I do different, 
sorry...

**Comment by cwensley** [comment]
Not a problem at all, keep reporting issues as they come up!

**Comment by TomQv** [comment]
Ok, I had a Style on the TreeGridView handling Editing, a forgotten and unsuccessful try to get a Drag&Drop.
Removed the style and now its working, but still not nice, because I need two cell-clicks. First to select the cell then to check or uncheck.
So I'm using the CellClick-Event now, works better because its independent of the selection.
Thanks, issue solved.

**Comment by cwensley** [comment]
Closing as the issue was due to non-Eto code. I believe you already have issue #647 open to adjust the behaviour of the CheckBoxCell.
