### ISSUE TITLE
Drag&Drop items between Grid and TreeGrid

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#872]
I know, Drag&Drop is on the list since long, but my usecase is maybe much easier.

In our app we have a TreeGridView and a GridView. We need to be able to drag items from the grid into the tree and vice-versa. Its similar like moving mails in Thunderbird between folders.

I'm thinking of handling all sorts of Mouse-events for this. MouseDown, MouseMove with button pressed, MouseUp etc. Would this work? For Mac and Wpf?

Any other ideas?

**Comment by SlowLogicBoy** [comment]
I had something like this working on Wpf.
Used Main Content as `PixelLayout`, and when I detected dragging I put label in that layout under a cursor, and while mouse button is down and mouse moved I just moved that label, on mouse up I just assumed that dragging is complete and looked over which control mouse was.

**Comment by cwensley** [comment]
Hm, you could probably hook up to the MouseDown/MouseMove/MouseUp of the source control via something like this:

1. On the MouseDown start your 'drag' by checking which items are select and/or what is under the mouse cursor (translated via PointFromScreen()) using GridView.GetCellAt().
2. On MouseUp (still of the source control), call GetCellAt() on the other control using the new location of the mouse cursor.  You now know where to 'drop' it when the MouseUp event comes in.

If you hook the logic up to both the tree and grid then you can get two-way drag/drop.

Hope this helps!

**Comment by TomQv** [comment]
Its working now, but I hooked in to the native control using the Drag...-events. At least for WPF I'm done. Hope, I will also make it for MacOS.

**Comment by TomQv** [comment]
Ok, already stuck with MacOS.
On the WPF side I'm just adding event-handler to my control to enable drag&drop:


```
UIElement wpfcontrol = WpfHelpers.ToNative(etocontrol); ;
wpfcontrol.AllowDrop = allowdrop;
DragDropEffects effects = DragDropEffects.None;

if (allowdrag)
{
	wpfcontrol.MouseMove += (object sender, System.Windows.Input.MouseEventArgs e) =>
	{
		if (e.LeftButton == System.Windows.Input.MouseButtonState.Pressed)
			System.Windows.DragDrop.DoDragDrop(wpfcontrol, DragDropManager.SELECTION , 
	};
}

wpfcontrol.DragEnter += (object sender, DragEventArgs e) =>
{
	var action = DragDropManager.DragOver(dragdropcontrol, e.KeyStates.HasFlag(DragDropKeyStates.ShiftKey));
	effects=EffectFromAction(action);
	e.Effects = effects;
	e.Handled = true;
};

wpfcontrol.DragOver += (object sender, DragEventArgs e) =>
{
	e.Effects = effects;
	e.Handled = true;
};

wpfcontrol.Drop += (object sender, DragEventArgs e) =>
{
	DragDropManager.Drop(dragdropcontrol, e.KeyStates.HasFlag(DragDropKeyStates.ShiftKey));
	e.Handled = true;
};
```

But this approach doesn't work for mac, because there are no events. The base-class must be subclassed and this is beyond my mac-skills.  Will wait, until drag&drop becomes part of Eto.

**Comment by cwensley** [comment]
This should be taken care of with #880, which is coming along.  It might be best to wait for that since it is coming soon and tacking it onto the Mac side like you did for WPF isn't quite as straightforward (requires adding methods to subclasses, etc).
