### ISSUE TITLE
Add ability to reload a TreeGridView item without reloading all its children

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#877]
Hi, its me again...

How do I update a single item in a TreeGridView after a property changed?

```
myitem1=new MyItem ("item1");
myitem2=new MyItem ("item2");
tree.Datastore= new TreeGridItemCollection {myitem1,myitem2};
var namecolumn=new GridColumn { DataCell= new TextCell("Name"));
tree.Columns.Add(namecolumn);

```

when I change Name from a myitem, the tree is not updated, only after a  tree.ReloadItem (myitem), which also rebuilds the whole tree instead of only this item.

```
public class MyItem : TreeGridItem, INotifyPropertyChanged
{
        public MyItem (string name)
        {
             _name=name;
        }
	string _name;
	public string Name
	{
		get
		{ return _name ; }
		set
		{
			if (value != _name)
			{
				_name = value;
				NotifyPropertyChanged("Name");
			}
		}
	}

	#region "INotifyPropertyChanged"

	public event PropertyChangedEventHandler PropertyChanged;
	private void NotifyPropertyChanged(String propertyName)
	{
		PropertyChanged?.Invoke (this, new PropertyChangedEventArgs(propertyName));
	}

	#endregion
}

```

**Comment by cwensley** [comment]
Thanks for reporting the issue! (and all the others, it's really appreciated!)

`TreeGridView.ReloadItem()` should only rebuild that particular item (and its children).  There's no way to specify to reload just the data for that row though, which would be very useful.

**Comment by cwensley** [comment]
Oh, and as for the INotifyPropertyChanged support, that is tracked with #240

**Comment by cwensley** [comment]
This was implemented a while ago, there's an overload of ReloadItem that takes a bool to specify that it should reload children or not.  e.g. `TreeGridView.ReloadItem(myItem, false)`
