### ISSUE TITLE
[Mac] WeakHandler null for TexBoxCellHandler.CellView

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#884]
Hi Curtis,

I know that before reporting a bug I should isolate it and make it reproducible, but it's months that I'm struggling with crashes that happen after I populate a GridView.
The crash happens here:
![image](https://user-images.githubusercontent.com/21080030/30484511-e5af7506-9a2a-11e7-962c-1d0cb4b3d86a.png)
because the WeakHandler of the control is null.
The control is always a Eto.Mac.Forms.Cells.TexBoxCellHandler.CellView:
![image](https://user-images.githubusercontent.com/21080030/30484653-58d49cd2-9a2b-11e7-9041-38940aaef9cc.png)
Of course I'll try to isolate the problem better than this (it's not easy since my application grew quite complex and with small snippets of code I never manage to reproduce the problem), but if you could give me some hints on where to investigate I would be really grateful.
To detail the problem a little further I always create an ObservableCollection<> of something, assign it to the DataStore and then populate it on the fly.

Any clue of what could go wrong or how to investigate it? I'm getting short of ideas :(

Thanks
Massi

**Comment by cwensley** [comment]
@msasso69 Not sure what I can recommend here.  It is _probably_ something getting GC'd, but then revived by the MonoMac runtime which then loses all of its .NET state.

We can probably avoid the crashing at least by checking if `control.WeakHandler` is null before executing this code.  e.g.

```c#
var childHandler = control.WeakHandler?.Target as IMacViewHandler;
```

Hope this helps!
Curtis.

**Comment by msasso69** [comment]
Thanks but I have already tried it with no luck. Once I get the exception I get tons of them and the system becomes compromised. I'm not sure if this is happening just by chance but it looks like I can limit the chances to have the exception if I randomly click on the GridView(s) while they are filled in, as if somehow the framework keeps some objects alive...
I'll keep on trying to reproduced the problem in a smaller application because as you can see by the following picture my application grew pretty big and I have GridView(s) in the main closable tabs and in most of the bottom and right collapsible tool tabs.
![image](https://user-images.githubusercontent.com/21080030/31848601-7f4302f2-b653-11e7-8934-600c1bec57ac.png)

**Comment by cwensley** [comment]
@msasso69 with that change, there shouldn't be any exceptions thrown.  Were you getting a different exception or crashing somewhere else after trying that?

**Comment by msasso69** [comment]
Yes,
I waited before replying you because I wanted to be sure of that, but I'm now confident that your fix is correct. I do not know what I did in the past, probably I just put a break-point in the crashing code and skipping the "if condition" manually, but since I got thousand of exception I just assumed I was not going in the right direction.
Ensuring instead programmatically that childHandler get a value even if control.weakHandler is null fixes indeed the problem and I'm not getting anymore the hated exception!
You can close the issue as resolved.
Thanks a lot!!!

**Comment by cwensley** [comment]
@msasso69 thanks for the reply and verifying that the fix works!  Cheers!
