### ISSUE TITLE
Workaround to group Eto-Buttons in MacOS ?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#889]
I would like to group some buttons in MacOS like described here:
[https://christiantietze.de/posts/2016/06/segmented-nstoolbaritem/](https://christiantietze.de/posts/2016/06/segmented-nstoolbaritem/)

My idea is to configure the grouping with the text-property, which I don't need, and add a style:
```
var button1= new Button { Style="groupedtoolbarbutton", Text="g1", Image= img1 };
var button2= new Button { Style="groupedtoolbarbutton", Text="g1", Image= img2 );
var button3= new Button { Style="groupedtoolbarbutton", Text="g2", Image= img3 };
var button4= new Button { Style="groupedtoolbarbutton", Text="g2", Image= img4 );
```
In the style-handler I would collect the buttons and group them according to the text-property.
```
Eto.Style .Add <Eto.Mac.Forms.Controls.ButtonHandler >("groupedtoolbarbutton", handler =>
{
        var group = handler.Text;
        handler.Text = string.Empty;
	// collect buttons and join buttons with equal group
	// todo
});
```
I just don't know, how... I'm absolute not familiar with MacOS-UI and Cocoa, that's why I'm using Eto. Does somebody maybe know, if  this is possible and how to put this in c# in the style-handler?

Thanks
Tom

**Comment by SlowLogicBoy** [comment]
For toolbar you can try use `SeparatorToolItem`, for spacing items in `StackLayout` I use `new StackLayoutItem(new Label(), true);`

**Comment by TomQv** [comment]
Actually I mean grouping together  not separating:
![201606141536_mail](https://user-images.githubusercontent.com/6605960/30645220-45b090a0-9e15-11e7-9a4d-cc6faab4c193.png)

**Comment by cwensley** [comment]
@TomQv You'd have to create a custom control for this with at least two handler implementations (just like all the other controls).  One for mac, and one for the other platforms using a themed handler.

The [TabControlHandler](https://github.com/picoe/Eto/blob/develop/Source/Eto.Mac/Forms/Controls/TabControlHandler.cs) and associated TabPageHandler is probably close to what you'd need to contain a list of other items.  It might be best if they weren't actually buttons but rather a different class so you're not needlessly creating Button instances.

Hope this helps!
Curtis.

**Comment by TomQv** [comment]
But I have no idea, how to archive this on the mac-side.
So I also say "help wanted" :)

**Comment by cwensley** [comment]
@TomQv Perhaps take a look at the documentation for [NSSegmentedControl](https://developer.apple.com/documentation/appkit/nssegmentedcontrol) and its [overview](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/SegmentedControl/Articles/SegmentedControlBasics.html).  It should give you a good starting point, hopefully. (;

**Comment by TomQv** [comment]
Just to bring this up again, I was trying but didn't manage...
Help... :)

**Comment by TomQv** [comment]
I just realize, that Eto can anyway not have more toolbars, then only one in the mainform. 
But I need more, so I'll find another solution with grouped buttons or so.

So we can cancel/close this.

**Comment by cra0zy** [comment]
I don't know how to program Mac GUIs, but for Gtk I did this using styles, something similar could probably be achieved for Mac as well:

![pipelinetool](https://user-images.githubusercontent.com/6773302/35185620-f7e298c0-fe07-11e7-954c-8e089802bf42.png)

**Comment by RotsiserMho** [comment]
Hello, I see that this issue is closed with the addition of SegmentedButton but how does one add that to a Toolbar?

**Comment by cwensley** [comment]
@RotsiserMho using this control on the Toolbar would require #32.  I've bumped it up to 2.x to get to it sooner.
