### ISSUE TITLE
[GTK2] the descendant from GridView does not receive the OnColumnHeaderClick event

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#894]
[GTK2] the descendant from GridView does not receive the OnColumnHeaderClick event.
In the Wpf-platform everything is fine, the event comes.

And is it planned to be able to display the sorting marker in the column headers in the future?

**Comment by Serg-Norseman** [comment]
Because apparently I did poorly formulate the problem, I made a small demo for checking the bug. On this demo, I was able to check for a problem: in the Wpf platform mode, GridView receives events when clicking on the column headers. In Gtk platform mode, GridView does not receive an event. The code is shown below. Eto version 2.3.0.0.

`using System;
using System.Collections.ObjectModel;
using Eto;
using Eto.Forms;

namespace Test1.Wpf
{
    class MyPoco
    {
        public string Text { get; set; }
        public bool Check { get; set; }
    }

    class MyForm : Eto.Forms.Form
    {
        void grid_ColumnHeaderClick(object sender, GridColumnEventArgs e)
        {
            MessageBox.Show("HeaderClick", "Event", MessageBoxType.Information);
        }

        public MyForm()
        {
            this.ClientSize = new Eto.Drawing.Size(400, 300);
            this.Title = "Hello, Eto.Forms";

            var collection = new ObservableCollection<MyPoco>();
            collection.Add(new MyPoco { Text = "Row 1", Check = true });
            collection.Add(new MyPoco { Text = "Row 2", Check = false });
			collection.Add(new MyPoco { Text = "Row 3", Check = false });
			collection.Add(new MyPoco { Text = "Row 4", Check = false });
			collection.Add(new MyPoco { Text = "Row 5", Check = false });

            var grid = new GridView { DataStore = collection };

            grid.Columns.Add(new GridColumn {
                DataCell = new TextBoxCell { Binding = Binding.Property<MyPoco, string>(r => r.Text) },
                HeaderText = "Text"
            });

            grid.Columns.Add(new GridColumn {
                DataCell = new CheckBoxCell { Binding = Binding.Property<MyPoco, bool?>(r => r.Check) },
                HeaderText = "Check"
            });

            grid.ColumnHeaderClick += grid_ColumnHeaderClick;

            Content = grid;
        }
    }

    public class Program
    {
        [STAThread]
        public static void Main(string[] args)
        {
            //var application = new Application(Platforms.Wpf);
			var application = new Application(Platforms.Gtk2);
            application.Run(new MyForm());
        }
    }
}
`

**Comment by cwensley** [comment]
Hey @Serg-Norseman, thanks for putting together a repro of the issue, it is really helpful!!

#283 tracks the feature to add sorting indicators.  Help is welcome on that, as it isn't on the short term  radar currently.

As for this issue, I'll take a look at it for 2.5

**Comment by cwensley** [comment]
In order to get the `ColumnHeaderClick` event to fire, you need to set `GridColumn.Sortable = true` for the columns you wish to allow to be clicked.  WPF incorrectly had this as true by default, and WinForms fired it regardless.  This should now be fixed and consistent across platforms.
