### ISSUE TITLE
[WPF] any images for toolbar buttons have a size of 16 * 16 and are distorted

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#896]
In WPF mode, any images for toolbar buttons have a size of 16 * 16 and are distorted (my original is 20 * 20). Earlier I was advised to use styles. But experiments and search by source showed that the problem seems to be this:
( Eto/Source/Eto.Wpf/Forms/ToolBar/ButtonToolItemHandler.cs )
`swcImage = new swc.Image { MaxHeight = 16, MaxWidth = 16 };`
......
`swcImage.Source = image.ToWpf(Screen.PrimaryScreen.LogicalPixelSize, swcImage.GetMaxSize().ToEtoSize());`

How to solve this problem, within the ideology and approach of Eto?

**Comment by cwensley** [comment]
Hm, yeah I've been trying to remove as much of the fixed image sizes as possible.  Seems there's a few other spots that need updating.  Thanks for reporting the issue!

**Comment by Serg-Norseman** [comment]
I can supplement this message that the code probably behaves differently with different DPI of displays (WPF problem?). I'm not good at this. However, one and the same program, unchanged, has differently scaled icons on different displays. Size everywhere is small. But on the one display, where DPI is standard - icons are smaller than their normal size, but quite contrasting. On the other, where in Windows settings are scale is increased - the icons are almost blurry. I do not know what else to look for ...

**Comment by cwensley** [comment]
@Serg-Norseman that is going to be normal though, as it is resizing to 16x16 logical pixels, which will not be 16x16 pixels when the scale is adjusted.  What might be happening on WPF is your image might have a different DPI specified, and WPF takes that into account when trying to render the image.  AFAIK, they should be set at 96 dpi to get a 1:1 ratio with 'standard' scale.

To get pixel perfect on all DPI scales, you would need to use the `Icon` with various `@2x`, `@1.5` etc variants of the image.

When I take a look at this, I'll be sure to keep the DPI scaling in mind to make sure it can be displayed correctly.

**Comment by Serg-Norseman** [comment]
Closed in v2.8.0. Thank you!
