### ISSUE TITLE
Pressing Delete in TreeGridView deletes the selected tree items in WinForms

### ISSUE THREAD

**Issue by maxvoxel8** [picoe/Eto#900]
Does not happen on Mac or WPF. The KeyDown/KeyUp events do not fire so there doesn't seem to be any way to intercept it either. Collapsing and expanding the parent node recreates the tree items.

**Comment by cwensley** [comment]
Thanks for reporting the issue!

**Comment by cwensley** [comment]
Hey @maxvoxel8, I can't seem to replicate this issue.  Do you recall anything that may have caused it?  Were you using 2.3 at the time maybe?

**Comment by maxvoxel8** [comment]
Yes. I think it went away when I updated.

**Comment by cwensley** [comment]
@maxvoxel8 awesome, thanks.  (;
