### ISSUE TITLE
Question: How to style specific controls for a dark theme

### ISSUE THREAD

**Issue by apreiml** [picoe/Eto#901]
Hi, 

I want to create a dark look on my application and I tried to style the controls according to. I didn't figure out a few things:

* How can I set the focus style of a button?
* How can I change the background of table cells?
* How can I change the look when a table row is focused.

If it's not possible with eto.forms itself, can I change the style of the WindowsForms engine directly?

**Comment by SlowLogicBoy** [comment]
With [Styling](https://github.com/picoe/Eto/wiki/Styling) you can change platform specific stuff, like accessing WinForms/WPF controls directly

**Comment by apreiml** [comment]
Thanks a lot for your help and time!

**Comment by cwensley** [comment]
Closing as this appears resolved.
