### ISSUE TITLE
GridView with F#

### ISSUE THREAD

**Issue by javicabanas** [picoe/Eto#903]
Hi,

I am testing eto to be used in a project instead of Window forms.

I am not able to figure out how to fill a gridview with some test data. Here you have the code I am using:

```
let app = new Application()
let form = new Form(Title="Test form", Topmost=false, Size = Size(300, 200))

let groupBox =

    let txGroupBox = new GroupBox()
    txGroupBox.Text <- "Test group"

    let transferredExams = new GridView()
    transferredExams.ShowHeader <- true
    transferredExams.DataStore <- ["SFDasfd"]

    let mrn = new GridColumn()
    mrn.HeaderText <- "Column 1"
    mrn.Editable <- true
    mrn.AutoSize <- true
    mrn.Width <- 150
    mrn.DataCell <- new TextBoxCell(0)
    transferredExams.Columns.Add mrn

    let layout =
        let row = new TableRow()
        row.Cells.Add(new TableCell(transferredExams, false))
        let ret = new TableLayout()
        ret.Rows.Add row
        ret

    txGroupBox.Content <- layout
    txGroupBox

form.Content <- groupBox
form.Show()

[<System.STAThread>]
app.Run form
```
As a result I got an empty cell. I don't know how to bind DataStore with cells. I could see there are several empty cells when I add several data items to DataStore, like that:

 transferredExams.DataStore <- ["Data1"; "Data2"] -> two rows with 1 empty cell per row.

Thanks,
Javier Fernández

**Comment by cwensley** [comment]
Try: 
```fs
transferredExams.DataStore <- [ ["Row 1"], ["Row 2"] ]
```

Each item in the data store needs to be an array, if you are going to use `new TextBoxCell(0)`, which specifies to use the first element in each row item.

Hope this helps!

**Comment by javicabanas** [comment]
Thanks cwensley,

I am trying with this:

`transferredExams.DataStore <- Seq.cast [["Data1"]; ["Data2"]]`

But I get two rows with empty cells.

**Comment by javicabanas** [comment]
Sorry, I have closed the issue by mistake, I am reopening it again.

**Comment by javicabanas** [comment]
Finally, your clue heps me. I have to use an array for each row, like here:

transferredExams.DataStore <- [[|"Data1"|]; [|"Data2"|]]

This line works as a charm.

Thanks so much, cwensley.

**Comment by cwensley** [comment]
@javicabanas awesome, glad you figured it out.  I just found the same result as well and was typing a response when you posted that. (;

Alternatively, you could create a new class with properties for each column, as long as these are "real" clr properties.  I'm not sure how F# mangles classes but if it's anything like IronPython there may be additional hoops you have to go through to make them "real".

**Comment by javicabanas** [comment]
I will use a record, like that:

```
type MyRecord = {
    Column1 : string
    Column2 : string
    Column3 : DateTime
}
```

And an ObservableCollection, as it is recommended here: https://github.com/picoe/Eto/wiki/GridView. For example:

`let collection = new ObservableCollection<MyRecord>()`

Yesterday I tried something like that, but it didn't work. 

It is difficult to find examples in F#.

Thanks again.
