### ISSUE TITLE
It's possible to hide a border of the form?

### ISSUE THREAD

**Issue by Quant1um** [picoe/Eto#916]
It's possible to hide a border of the form and/or replace it by own?
![image](https://user-images.githubusercontent.com/31078520/32701984-76d290e8-c7f0-11e7-97f6-4a6045730101.png)

**Comment by cwensley** [comment]
Yes, set `myForm.WindowStyle = WindowStyle.None`.

If you want to do something windows specific (ala your example image), use a native style and do whatever WPF or WinForms needs to do what you want:

e.g.

```c#
Eto.Style.Add<Eto.Wpf.Forms.FormHandler>(null, h => {
  var wpfWindow = h.Control;
  // wpfWindow.DoWpfStuffThatDoesWhatYouWant();
});
```

Hope this helps!
Curtis.

**Comment by Quant1um** [comment]
@cwensley Thanks! It works.
