### ISSUE TITLE
WPF GridView.ScrollToRow issue

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#924]
create a GridView, fill DataStore and select and scroll to a specific item.
SelectRow(i) is working, but ScrollToRow(i) is not working, the Grid just stays at position 0.

Apparently, because the Grid is filled asynchronous and still busy, when the SelectRow-call comes.

See here:
http://dotnet-experience.blogspot.com.es/2010/12/wpf-listview-scrollintoview.html

Tom

**Comment by msasso69** [comment]
TomQv, I know I'm not helping you, but I'm using the latest "develop" branch and it is working fine for me with WPF (I just checked to be sure).

**Comment by cwensley** [comment]
@TomQv did you test the develop branch, or are you using 2.3?  Let me know so I can schedule or close this.

**Comment by TomQv** [comment]
I'm always using the latest source.
This is fine now, ScrollToRow is working.

**Comment by cwensley** [comment]
@TomQv thanks for confirming.
