### ISSUE TITLE
Mac - ContextMenu not opening on single selected row

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#927]
This is extremely strange and difficult:

- Eto.Mac.Xamarin
- a GridView, one or more columns, some rows of data
- a ContextMenu

Clicking with the right mousebutton in one of the cells of the single selected row, doesn't trigger the ContextMenu. Nothing happens.
Not even GridViewHandler.RightMouseDown() is triggert.

When I click another row, which is not selected, or in the empty space next to the cells of the selected row, it works.  It also works, if more then one rows are selected. 

Just not on the cells of a single selected row, which is the most often use-case.

So what could cause e selected cell, not to trigger right mousebutton down?

It works fine on your Eto.Samples, also in a small, new Testproject, just not in the scope of our big App.

I was searching now for hours, tried everything, compared both versions, no success. Any ideas, where else I can look? What could cause this odd behaviour?

Thanks
Tom

**Comment by cwensley** [comment]
Hey @TomQv, not sure what I can do without any sort of reproduction of the issue (so I'm closing this and no repro).  I'm not sure what could be causing it, but if you get any insights please re-open or comment on this issue and we can look into it.

Just make sure you're using the develop branch (or 2.4.0 when it comes out) to ensure this isn't already fixed.

Cheers!
Curtis.
