### ISSUE TITLE
Wpf Drag&Drop Effects

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#932]
How to change the Effect (the mouse-icon) during a DragOver?
Just assigning another value to e.Effect doesn't have any effect on the mouse-icon.

Tom

**Comment by TomQv** [comment]
in WpfFrameworkElement changing the way, effects are handled like this, then it seems to be fine:

```
protected virtual void HandleDrop(sw.DragEventArgs e, DragEventArgs args)
{
	IsDragEntered = false;
	Callback.OnDragLeave(Widget, args);
	Callback.OnDragDrop(Widget, args);
	//e.Handled = args.Effects != DragEffects.None;
	e.Effects = args.Effects.ToWpf();
	e.Handled = true;
}

protected virtual void HandleDragEnter(sw.DragEventArgs e, DragEventArgs args)
{
	Callback.OnDragEnter(Widget, args);
	//e.Handled = args.Effects != DragEffects.None;
	e.Effects = args.Effects.ToWpf();
	e.Handled = true;
}

protected virtual void HandleDragOver(sw.DragEventArgs e, DragEventArgs args)
{
	Callback.OnDragOver(Widget, args);
	//e.Handled = args.Effects != DragEffects.None;
	e.Effects = args.Effects.ToWpf();
	e.Handled = true;
}


```

**Comment by TomQv** [comment]
Another thing regarding effects and mouse-icon.
Using your sample, dragMode "No Node", dragging an item over the destination-grid the mouse-icon is like flickering, as if internally the effect is permanently changing back and forth. This doesn't look nice.
Ok, its just cosmetics, but maybe you'll see something.

**Comment by cwensley** [comment]
Hey @TomQv, thanks for the feedback!

I'm not seeing the same problem you see, the mouse cursor shows correctly.  That change also doesn't make any sense, you must be setting args.Effects to DragEffects.None then (or not setting it?).

The following two lines are equivalent if you have set an Effect:

```c#
e.Handled = args.Effects != DragEffects.None; // this should set e.Handled = true here
e.Handled = true; // superfluous, the above sets it to true
```

**Comment by TomQv** [comment]
I'm changing the effect during DragOver depending on testing, if drop is allowed or not on the current control. With Wpf Effects must be set before Handled is set to true.

**Comment by cwensley** [comment]
Hey @TomQv, thanks again for reporting the issue!  This should now hopefully be fixed.  Let me know if you run into any other problems.
