### ISSUE TITLE
[Mac] menu items remain disabled

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#936]
Hi,

I noticed that clicking on a menu item in the menu bar when a Dialog is shown has the undesired effect of making the sub menu items disabled for good. 
This happens on Mac only.

## Expected Behavior
after closing a dialog the sub menu items should be enabled

## Actual Behavior
after closing a dialog the sub menu items remain disabled

## Steps to Reproduce the Problem
When a dialog is still open try clicking in the menu bar on an item that has some sub items, you'll see that after closing the dialog the sub items will be still disabled

## Code that Demonstrates the Problem
The issue can be easily reproduced even with a simple MessageBox and the following test code:
```
using System;
using Eto;
using Eto.Forms;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyMainForm());
		}

		public class MyMainForm : Form
		{
			public MyMainForm()
			{

				Button btn = new Button { Text = "Click me!" };
				btn.Click += (sender, e) =>
				{
					MessageBox.Show("click on the menu item without closing the dialog");
				};
				Menu = new MenuBar
				{
					Items = 
					{
						new ButtonMenuItem 
						{
							Text = "MyMenu",
							Items =
							{
							new ButtonMenuItem { Text = "1" },
							new ButtonMenuItem { Text = "2" },
							new ButtonMenuItem { Text = "3" }
							}
						}
					}
				};
				Content = btn;
			}
		}
	}
}
```

 Try launching the program and click on MyMenu, you'll get this:

![image](https://user-images.githubusercontent.com/21080030/34110720-cdc323da-e407-11e7-910d-797655063d88.png)

The sub menu items are enabled (CORRECT)

Now click on the button "Click me!" and without closing the message box click again on MyMenu, you'll get this:

![image](https://user-images.githubusercontent.com/21080030/34111053-cf8b1de8-e408-11e7-9864-ee102775fcae.png)

The sub menu items are grayed out (CORRECT)

Now close the message box and click again on MyMenu, this time you'll get this:

![image](https://user-images.githubusercontent.com/21080030/34111077-f5183942-e408-11e7-8d4e-a311cfa671e2.png)

The sub menu items are still grayed out (WRONG)

Note that in a real application clicking on a disabled menu item has the effect of closing the menu drop down but no Click event is fired

## Specifications

  - Version: latest develop branch
  - Platform(s): Mac

**Comment by cwensley** [comment]
Yikes!
