### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#946]
I was just wondering, seeing that it has been a while since the release of 2.3.0, if a release of a new version is still in the works for the near future? If not, I will consider just building Eto from source in my project.
Thanks!

**Comment by SlowLogicBoy** [comment]
You can get latest pre-release builds from MyGet.
[Here](https://github.com/picoe/Eto/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4) is what's left for 2.4 release.

**Comment by mennodeij** [comment]
Ok, thanks for pointing out the myget source for pre-release builds, I did not know about that.
