### ISSUE TITLE
Wish list: Text alignment for Graphics.DrawText()

### ISSUE THREAD

**Issue by JonSargent** [picoe/Eto#947]
Sorry for peppering the repo with posts of late!

Just a wish-list item here: text alignment for Eto.Drawing.Graphics.DrawText().  Would be terrific for custom buttons and other 2D graphics. :)

Or a way to hack it?  Font class give LineHeight, but not sure there's a way to get the width of a string.  (Obviously Labels have this figured out.)

**Comment by cwensley** [comment]
Use `Graphics.MeasureString()` to determine the bounds of the string, then you can use that to determine where to place the string.

**Comment by JonSargent** [comment]
Perfect, thanks!
