### ISSUE TITLE
Wizard dialog

### ISSUE THREAD

**Issue by shirokalex** [picoe/Eto#948]
Hi,

Is there something like Wizard dialog (page container with Back, Next and Cancel buttons) in Eto.Forms?

**Comment by cwensley** [comment]
No there is not, but it is not difficult to create one yourself.    Something like this might be a good candidate for an Eto extended controls library, as it may not make sense to be in the core.

**Comment by shirokalex** [comment]
Ok, thank you for the answer. 
I added project with my simple realization: https://github.com/shirokalex/EtoWizardDialog. 
Maybe it will be useful to someone.
