### ISSUE TITLE
The order of TreeGridItem(s) using a CustomCell in a TreeGridView is not kept when scrolling

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#961]
I needed to have a TreeView with a checkbox an image and a text in just one column and I achieved what I needed making use of a CustomCell, but I bumped into the following problem:

## Expected Behavior
The order of TreeGridItem(s) with CustomCell(s) should not be messed up when scrolling up and down the TreeGridView

## Actual Behavior
Scrolling up and down a TreeGridView that contains CustomCell(s) completely screws the order of the items

## Steps to Reproduce the Problem

  1. Run the program below
![image](https://user-images.githubusercontent.com/21080030/35188476-1605d5aa-fe36-11e7-8077-802f3084158b.png)

  2. Scroll down
![image](https://user-images.githubusercontent.com/21080030/35188485-3c8d8b46-fe36-11e7-9692-84795c45c4c2.png)
(the order is already wrong)

  3. Scroll up
![image](https://user-images.githubusercontent.com/21080030/35188490-59f031c0-fe36-11e7-8036-d2b76d124c42.png)
(the order is wrong and there are even duplicates)

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using Eto.Drawing;
using System.Collections.Generic;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);

			TreeGridView tree = new TreeGridView();

			// using a normal TextBoxCell the order is preserved
			//tree.Columns.Add(new GridColumn { DataCell = new TextBoxCell(0), Width = 150 });

			// using a CustomCell the order is lost when scrolling the control
			tree.Columns.Add(new GridColumn { DataCell = new MyCustomCell(), Width = 150 });

			// fill the model
			TreeGridItemCollection model = new TreeGridItemCollection();
			for (int i = 0; i < 20; i++)
				model.Add(new TreeGridItem() { Values = new object[] { i.ToString() } });
			tree.DataStore = model;

			// create the layout
			var table = new StackLayout
			{
				HorizontalContentAlignment = HorizontalAlignment.Stretch,
				VerticalContentAlignment = VerticalAlignment.Stretch,
				Items =
				{
					new StackLayoutItem(tree, true)
				}
			};
			var form = new Form { Content = table, Size = new Size(200, 200) };

			app.Run(form);
		}

		public class MyCustomCell : CustomCell
		{
			protected override Control OnCreateCell(CellEventArgs args)
			{
				TreeGridItem item = args.Item as TreeGridItem;
				return new StackLayout
				{
					Items = { new Label() { Text = (string)item.Values[0] } }
				};
			}
		}
	}
}
```

## Specifications

  - Version: 19th Dec 2018 develop branch
  - Platform(s): tested on Mac and WPF

**Comment by cwensley** [comment]
This is most likely a problem in your code.  Cells are cached to improve performance. You need to handle [CustomCell.OnConfigureCell](https://github.com/picoe/Eto/blob/3f2847be5a40228d023e0ef7dad1dc82d4e175e3/src/Eto/Forms/Cells/CustomCell.cs#L323) to set up your cell for a different set of data.

I've added some new docs to help point others in the right direction in #965

**Comment by msasso69** [comment]
Yes, you are right, populating the data in OnConfigureCell instead of in OnCreateCell did the trick. Thanks
