### ISSUE TITLE
WinForms controls in Eto cross platform

### ISSUE THREAD

**Issue by RobotCaleb** [picoe/Eto#968]
I'm trying to determine if Eto will help me with my project.
I have a licensed project from which I want to use a WinForms control.
I want to use Eto because it provides cross-platform tray indicator functionality.

My two supported operating systems are Windows and Linux.
WinForms on Windows isn't a problem, neither does WinForms under Mono on Linux seem to be problem.
However, I think I'm butting against Eto and WinForms compatibility.

Ideally, I have a system tray component (done) that I click on and execute something that pops a window with this third party control. (also done. I use Eto for system tray, and pop a WinForms form with this control)

The problem is that I can't close that form properly. I'm assuming this is due to popping a WinForms form in a Eto Application.

If I try to load that control into a Eto Form using `MyControl.ToEto()` I end up getting a Widget missing reference and it wants me to include `gtk-sharp` dll, which seems strange.

In the end I think I'm doing something weird or am attempting to do something unsupported.

I'm happy to try to provide some condensed code if needed, but I figured someone would be able to tell me if I'm up the wrong tree without.

**Comment by cwensley** [comment]
I guess you have a single project that targets both Windows/WinForms and Linux/Gtk?

You're possibly using the wrong `.ToEto()` extension.  Try using `Eto.WinForms.WinFormsHelpers.ToEto(MyControl)`, which will convert a WinForms control into an Eto control.

If you want to use native controls within Eto, you'll have to separate out your code or use logic to do the correct thing on a per-platform basis.  For example, you can't use the above method when running under Gtk.

Also, it is normal to have to reference the 'native' dll's (gtk-sharp, System.Windows.Forms, etc) when you want to use native functionality.

Hope this helps!
Curtis.

**Comment by cwensley** [comment]
@RobotCaleb Did my suggestions help?

**Comment by cwensley** [comment]
@RobotCaleb Hopefully my suggestions helped.  Closing for now but feel free to submit more info.
