### ISSUE TITLE
Wpf - Label with long text in Scrollable

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#973]
When a Label with a long text is added to a scrollable, WrapMode is ignored and it messes up the width to the full length of the text and  the label is just one line without wrapping.

I would expect, that a label with a WrapMode  should not be considered in determining the scroll-width.

Or maybe I just didn't figure out yet, how to use this properly..

Tom

**Comment by cwensley** [comment]
I think this is actually expected behaviour, as a label usually wants to take as much width as possible.  In a Scrollable, the available width is infinite.

To make the Label shrink, you could set its `Width` to a minimum size so it won't shrink too small and use the `Scrollable.ExpandContentWidth` (which is by default true) so the label will be expanded to the width of the scrollable area.

Does this work differently on WinForms or any other platform?

**Comment by TomQv** [comment]
Actually I don't know, what the default behaviour is.
I just want a scrollable, which can only scroll vertical and the label must wrap. A workaround is wrapping the label in a StackLayout.

I also didn't figure out, what ExpandContentWidth  or ExpandContentHeight is doing. I doesn't seem to have any effect. The only thing I noticed is that when both are true, loading time of a control takes very long, several seconds, because of many layout-calls. When both are false, loading is normal, fast.

Only talking about wpf now.

**Comment by cwensley** [comment]
If you only want a `Scrollable` to scroll vertically, set `Scrollable.Content.Width = 1;`, whatever the content may be.

**Comment by cwensley** [comment]
@TomQv did you test out my suggestion?  It'd be nice to know if that worked for you or if we need to do something to support this scenario.

**Comment by TomQv** [comment]
You mean set Scrollable.Content.Width = 1 ?
Not really.

I definitely have to set both  ExpandContentWidth or ExpandContentHeight to false, otherwise initial loading of the layout takes 1-2 seconds (not more then 20 controls in the layout).

My workaround is to give labels a fixed width.
I'm fine with this for now.

But labels should have a property to control if their width should rule the container or if they must adapt to the container.

**Comment by cwensley** [comment]
@TomQv Hm, it'd be nice to figure out why it's taking that long with ExpandContentWidth/Height turned on, do you have a test case that you can share?

As for this issue, it is working as expected unless my suggestion doesn't work.  It would require EpandContentWidth to be set to true though.  If it does, let's close this issue and open a new one with the performance problem.

**Comment by cwensley** [comment]
Closing as this is expected behaviour.
