### ISSUE TITLE
[Feature Request] Addin for Rider

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#977]
It would be nice to have an addin for [Rider](https://www.jetbrains.com/rider/).

**Comment by cwensley** [comment]
Thanks for the request.  It's been asked already in picoe/Eto.DevExtensions#11 

For the 2.4 release there'll be new dotnet templates that Rider will have access to directly!  I'm not sure what else we can do for Rider specifically, but that would probably do it.

Closing as duplicate.
